### ISSUE TITLE
Substitution loop error in filterIntronsFindStrand.pl

### ISSUE THREAD

**Issue by abmudd** [Gaius-Augustus/BRAKER#10]
I'm attempting to run BRAKER v2.1.2 on a genome with large chromosomes (the largest being over 1 Gb in size), and I ran into the following error message in the file errors/filterIntronsFindStrand.stderr:

> Substitution loop at PATH/to/BRAKER-2.1.2/scripts/filterIntronsFindStrand.pl line 122, \<FASTA\> chunk 1.

Of course, the obvious fix is to split apart the chromosomes before running BRAKER - please do note that BRAKER then ran successfully with split chromosomes. However, I still wanted to note the error for this particular use case. Thank you.

**Comment by KatharinaHoff** [comment]
Thank you for reporting this. This seems to be a known Perl issue for regular expressions on very long strings (e.g. referenced at https://www.nntp.perl.org/group/perl.perl5.porters/2014/10/msg221751.html).

We used to read the fasta file in a... probably not most elegant way, basically making all sequences a single-line entry:

```
# genome file in fasta format
open (FASTA, "<".$genome) or die "Cannot open file: $genome\n";
$/="\n>";
while(<FASTA>) {
  /[>]*(.*)\n/;
  $seqname = $1;
  $seq = $';
  $seq =~ s/>//;
  $seq =~ s/\n//g;
  $annos{$seqname} = $seq;
}
close(FASTA) or die("Could not close fasta file $genome!\n");
```
I changed this to line-by-line processing, now. So filterIntronsFindStrand.pl should not die at this exact point with a long chromsome, again. I am not sure about all other parts of BRAKER and Augustus scripts, though. The issue might arise at a different point in the pipeline, again. https://github.com/Gaius-Augustus/BRAKER/commit/6d722f2b58f9e51165ef31ddb3722ee07182c22a
