### ISSUE TITLE
BRAKER with an intron-sparse eukaryotic genome

### ISSUE THREAD

**Issue by krabapple** [Gaius-Augustus/BRAKER#100]
My genome is expected to have relatively few introns, despite being from a eukaryote.  Does this mean BRAKER won't work well for structural annotation with this genome?

**Comment by KatharinaHoff** [comment]
Few introns can be ok. The majority of genes not having introns means that
RNA-Seq data will have a low impact because it will not be considered for
the majority of genes.

**Comment by krabapple** [comment]
But aren't RNAseq reads useful as evidence that a gene model is 'real',
regardless of whether there are introns?  I may only have RNAseq evidence
to input to Braker.

**Comment by krabapple** [comment]
I'm still curious to know why you think RNAseq reads would *not* be particularly useful for calling gene models in a eukaryote genome with very few introns.   Is BRAKER's 'genome only' mode so good in such cases that RNA seq data would not add value?

**Comment by KatharinaHoff** [comment]
Maybe read the BRAKER1 paper... it’s explained there. I am writing from my
phone.

Katharina
