### ISSUE TITLE
optimize_augustus.pl lacks required --AUGUSTUS_CONFIG_PATH flag

### ISSUE THREAD

**Issue by michaelkarlcoleman** [Gaius-Augustus/BRAKER#103]
Calls to `optimize_augustus.pl` are missing the `--AUGUSTUS_CONFIG_PATH` flag, which is required.  Without this, the script ends up trying to use the value of the environment variable `$AUGUSTUS_CONFIG_FLAG`, which may differ than the `--AUGUSTUS_CONFIG_PATH` flag given to `braker.pl`.

https://github.com/Gaius-Augustus/BRAKER/blob/440f3b83d69582fdd5b1b55b247024e5fb544802/scripts/braker.pl#L9938-L9954

**Comment by KatharinaHoff** [comment]
Your help is appreciated!

The missing --AUGUSTUS_CONFIG_PATH flag has been added with commit https://github.com/Gaius-Augustus/BRAKER/commit/19ea8529e79536b7d01912b7ec4fbe0b132e95ed
