### ISSUE TITLE
Request: Make flanking_DNA value easier to see in log file.

### ISSUE THREAD

**Issue by jasonsydes** [Gaius-Augustus/BRAKER#104]
Hi @KatharinaHoff,

Thank you for BRAKER!  I've been working some with @michaelkarlcoleman on the 3'-UTR BRAKER issue.  Looking at #98, I noticed that the value for flanking_DNA is hard to discern from the log files.  It looks like it's currently in the line after "create genbank file ..." in the log file: specifically, it's the 3rd argument to gff2gbSmallDNA.pl .

Thank you!!
Jason

**Comment by KatharinaHoff** [comment]
Ok, made it more obvious, commit https://github.com/Gaius-Augustus/BRAKER/commit/86f05e0908149019bcfa717be470ed7804caf114

Katharina
