### ISSUE TITLE
Update GeneMark requirement (4.33 too old)

### ISSUE THREAD

**Issue by michaelkarlcoleman** [Gaius-Augustus/BRAKER#106]
GeneMark 4.33 no longer works, as `braker.pl` now uses the `--gc_donor` flag, which it seems to lack.

The current latest release, 4.46, seems to work.

**Comment by KatharinaHoff** [comment]
Good point. Fixed with commit https://github.com/Gaius-Augustus/BRAKER/commit/e4e94437d2bb8fbe139e89df9ddf8c57308194a9

Thanks!

Katharina
