### ISSUE TITLE
reuse a trained model for upgraded version assembly

### ISSUE THREAD

**Issue by XClaws** [Gaius-Augustus/BRAKER#107]
Dear Developer,

Thank you for developing such a nice annotation tool.
Currently, I have to re-annotate an upgraded version of genome assembly.
Can I apply the previous trained Augustus model (based on the previous genome assembly before mapping) to the new assembly?
There is no extra RNA-seq/protein data added.
Thank you in advance and look forward to hearing from you.

**Comment by KatharinaHoff** [comment]
In many cases, that works ok. 

It may be worth retraining if the first assembly that was used to train AUGUSTUS with BRAKER was highly fragmented or poorly masked for repeats.

Katharina

**Comment by XClaws** [comment]
Dear Katharina,

Thank you for the quick reply and kind suggestion.
I think it solved my question perfectly.
All the best,

Wei
