### ISSUE TITLE
odds result with busco evaluation

### ISSUE THREAD

**Issue by bitezhu** [Gaius-Augustus/BRAKER#109]
Hi，
I've been trying to annotate my plant genome with braker2, and now I finally get the results successfully. Then it occurred to me to evaluate genome completeness with BUSCO, so to avoid another Augutus running ,I used the "proteins" mode in BUSCO. I have two *aa file, which are "augustus.hints.aa","augustus.hints_utr.aa". The BUSCO summary results are showing below，I find it's very confusing ,because utr annotation should not impact amino sequences . 
Besides this, I also find many genes in "augustus.hints.aa" and "augustus.hints_utr.aa" with same ID do have different sequence, I don't know whether this is a bug.
Here is my broker command line:
perl toolkit/BRAKER/scripts/braker.pl --genome=.Ah_2019v2.msk --bam=merged.s.bam --species=Ah --softmasking --gff3 --workingdir=./ --UTR=on --PYTHON3_PATH=//toolkit/anaconda3/bin/

##############################################
augustus.hints.aa
C:94.8%[S:81.8%,D:13.0%],F:2.2%,M:3.0%,n:2121
        2011    Complete BUSCOs (C)
        1736    Complete and single-copy BUSCOs (S)
        275     Complete and duplicated BUSCOs (D)
        47      Fragmented BUSCOs (F)
        63      Missing BUSCOs (M)
        2121    Total BUSCO groups searched
--------------------------------------------------------------
augustus.hints_utr.aa
C:61.2%[S:47.9%,D:13.3%],F:26.2%,M:12.6%,n:2121
        1298    Complete BUSCOs (C)
        1016    Complete and single-copy BUSCOs (S)
        282     Complete and duplicated BUSCOs (D)
        555     Fragmented BUSCOs (F)
        268     Missing BUSCOs (M)
        2121    Total BUSCO groups searched

###############################################

**Comment by KatharinaHoff** [comment]
Your observation is not all that unusual. Predicting UTRs with AUGUSTUS can alter the coding sequence prediction substantially. In contrast to other tools such as e.g. GeMoMa, that only update already annotated CDS with UTRs according to evidence, AUGUSTUS actually trains parameters for the UTR region.

Always carefully analyze your results, the way you did is a good approach. In your case, you probably want to discard the gene set with UTRs and keep the one without.

**Comment by bitezhu** [comment]
> Your observation is not all that unusual. Predicting UTRs with AUGUSTUS can alter the coding sequence prediction substantially. In contrast to other tools such as e.g. GeMoMa, that only update already annotated CDS with UTRs according to evidence, AUGUSTUS actually trains parameters for the UTR region.
> 
> Always carefully analyze your results, the way you did is a good approach. In your case, you probably want to discard the gene set with UTRs and keep the one without.

OK then, but I'll look forward to a new version with better UTR annotation. BRAKER is a great tools, thanks for your work, KatharinaHoff.
