### ISSUE TITLE
Error: fix_in_frame_stop_codon_genes.py

### ISSUE THREAD

**Issue by kazuaki0816** [Gaius-Augustus/BRAKER#110]
Hi Developer

**I executed the following command using the files included in the example directory.**
# run command
$ braker.pl --genome=/home/local/tool/BRAKER/example/genome.fa --bam=/home/yamaguchi/local/tool/BRAKER/example/RNAseq.bam --prot_seq=/home/yamaguchi/local/tool/BRAKER/example/prot.fa --prg=gth

**I received the following error message.**
# Error message
Failed to execute: /home/.pyenv/shims/python3 /home/local/tool/Augustus/scripts/fix_in_frame_stop_codon_genes.py -g /home/local/tool/BRAKER/example/braker/genome.fa -t /home/local/tool/BRAKER/example/braker/augustus.Ppri5.gtf -b /home/local/tool/BRAKER/example/braker/bad_genes.lst -o augustus.Ppri5_fix_ifs_ -s Sp_7 -m off --UTR off --print_utr off -a /home/local/tool/Augustus/bin/../config -C /usr/bin -A /home/local/tool/Augustus/bin/../config/../bin -S /home/local/tool/Augustus/bin/../config/../scripts -H /home/local/tool/BRAKER/example/braker/hintsfile.gff.Ppri5 -e /home/local/tool/BRAKER/scripts/cfg/gth.cfg  > /home/local/tool/BRAKER/example/braker/fix_in_frame_stop_codon_genes_augustus.Ppri5.log 2> /home/local/tool/BRAKER/example/braker/errors/fix_in_frame_stop_codon_genes_augustus.Ppri5.err

**The following logs remained in the output files of "fix_in_frame_stop_codon_genes_augustus.Ppri5.err" and "getAnnoFastaFromJoingenes.augustus.Ppri5_tmp.stderr", respectively.**
# fix_in_frame_stop_codon_genes_augustus.Ppri5.err
Traceback (most recent call last):
  File "/home/local/tool/Augustus/scripts/fix_in_frame_stop_codon_genes.py", line 528, in <module>
    bad_genes.append(g_id_of_tx[tx_id])
KeyError: 'tx_id'

#getAnnoFastaFromJoingenes.augustus.Ppri5_tmp.stderr
/home/local/tool/Augustus/scripts/getAnnoFastaFromJoingenes.py:97: DeprecationWarning: 'U' mode is deprecated
  with open(args.genome, "rU") as genome_handle

**What is the cause of this error?
I look forward to your reply.**

Best regards,

**Comment by KatharinaHoff** [comment]
Please update BRAKER and Augustus from github (e.g. git pull). Part of your error message indicates that you are not using the most recent code.

**Comment by psur9757** [comment]
@KatharinaHoff 

When I tried with BRAKER and AUGUSTUS latest version as of Nov 13 – AUGUSTUS bin folder didn't have the `utrrnaseq` script and so the BRAKER run aborted.

I tried with latest BRAKER and AUGUSTUS 3.3.2 – I get fix in frame stop codon step error
```
ERROR in file /usr/local/braker2/dev/scripts/braker.pl at line 7659
Failed to execute: /usr/local/python/3.5.1/bin/python3 /usr/local/augustus/3.3.2/scripts/fix_in_frame_stop_codon_genes.py -g /scratch/RDS-FSC-BLRseq-RW/BLR/results/annotation/structural/BLR560/braker/genome.fa -t /scratch/RDS-FSC-BLRseq-RW/BLR/results/annotation/structural/BLR560/braker/augustus.hints.gtf -b /scratch/RDS-FSC-BLRseq-RW/BLR/results/annotation/structural/BLR560/braker/bad_genes.lst -o augustus.hints_fix_ifs_ -s BLR -m on --UTR off --print_utr off -a /scratch/BLRseq/BLR/results/annotation/structural/BLR560/braker/augustus_config -C /usr/local/cdbfasta/1.00/bin -A /usr/local/augustus/3.3.2/bin -S /usr/local/augustus/3.3.2/scripts -H /scratch/RDS-FSC-BLRseq-RW/BLR/results/annotation/structural/BLR560/braker/hintsfile.gff -e /usr/local/braker2/dev/scripts/cfg/rnaseq.cfg  > /scratch/RDS-FSC-BLRseq-RW/BLR/results/annotation/structural/BLR560/braker/fix_in_frame_stop_codon_genes_augustus.hints.log 2> /scratch/RDS-FSC-BLRseq-RW/BLR/results/annotation/structural/BLR560/braker/errors/fix_in_frame_stop_codon_genes_augustus.hints.err
```

I also tried BRAKER late-2.1.4 version and AUGUSTUS v3.3.2 – Same fix in frame stop codon error.

Any suggestions to fix it.

**Comment by KatharinaHoff** [comment]
Please use the latest code from github. If utrrnaseq binary is missing, please go to the auxprogs/utrrnaseq folder and follow compilation instructions. Copy the binary to Augustus/bin .

**Comment by KatharinaHoff** [comment]
I hope the problem was resolved. In any case, Anica has continued to improve the script...
