### ISSUE TITLE
GeneMark-ET.stderr: (in cleanup)  at ../Object/InsideOut.pm line 1953 during global destruction.

### ISSUE THREAD

**Issue by xiaoyezao** [Gaius-Augustus/BRAKER#111]
Hi, 
I run the braker pipeline on a plant genome. The job seems to finish successfully, but GeneMark-ET.stderr is full of lines:
`(in cleanup)  (in cleanup) at ../Object/InsideOut.pm line 1953 during global destruction.`

Is this normal, or something goes wrong here?

Thanks

**Comment by Peng-Y3** [comment]
Hi ! Recently I have meet the same problem , how do you solve this, could you tell me ?
Thanks

**Comment by lijing28101** [comment]
I also have this problem. Did you solve it? @Peng-Y3 @xiaoyezao
