### ISSUE TITLE
Is it possible to resume braker from some point?

### ISSUE THREAD

**Issue by xiaoyezao** [Gaius-Augustus/BRAKER#112]
Hi,

My braker job stops at `fix_in_frame_stop_codon_genes.py` because of this issue: `Falied to execute: fix_in_frame_stop_codon_genes.py #71`. I replaced this script with the latest one and run it manually. However, it seems the pipeline does not finish and more steps are needed to run. Do I have to rerun the job from the very beginning? Or any workaround to continue from where it stops?

Thanks

**Comment by KatharinaHoff** [comment]
I recommend that you run the job from beginning (i.e. new job).

Katharina

**Comment by xiaoyezao** [comment]
Thank you very much!

**Comment by cpouchon** [comment]
Hi Katharina, 

I have the same issue. 

Is it possible to continue a job ? 

My annotation crashed from a memory issue after 3 days of running. 

Thank you very much, 

Cheers

**Comment by KatharinaHoff** [comment]
There is in many cases no clean way to resume the job. I am wondering
whether you are using the latest version of BRAKER.

Pouchon Charles ***@***.***> schrieb am Mo. 9. Dez. 2024 um
14:53:
