### ISSUE TITLE
Error in file bamToWig.py at line 173: Return code of subprocess was 1

### ISSUE THREAD

**Issue by xiaoyezao** [Gaius-Augustus/BRAKER#116]
Hi,

I use augustus-3.3.3 but replaced the script `bamToWig.py` with the latest one. I run braker with the option:` -UTR=on`, and got the error: `Error in file bamToWig.py at line 173: Return code of subprocess was 1`.

I have no idea about this error. Can you please help?

Thanks

**Comment by KatharinaHoff** [comment]
Was that really all? Because line 173 of bamToWig.py is supposed to also output the command that failed running.

Katharina

**Comment by KatharinaHoff** [comment]
Closing because information is not sufficient to track the problem.
