### ISSUE TITLE
Adjust GeneMark max core ceiling?

### ISSUE THREAD

**Issue by michaelkarlcoleman** [Gaius-Augustus/BRAKER#117]
Not sure about the history of this, but would it be possible to skip clamping the max core count to 48?  We performed a run with 112 cores (with the latest GeneMark), and it seemed to run correctly.

(Warning isn't a problem, but it's mildly inconvenient to have to comment out the actual clamp.)

https://github.com/Gaius-Augustus/BRAKER/blob/036eb3b28fb3591cd58010489898b860332bbd41/scripts/braker.pl#L3742-L3760

**Comment by KatharinaHoff** [comment]
That's good hear.

We implemented the upper limit after one user reported problems with more than 48 cores. It might depend on the properties of an individual genome. GeneMark itself doesn't really have a limit for 48 cores... just sometimes the genome bins are apparently too small if you split the data into too many bins. I'll consider deleting line 3759 and only issue a warning.

**Comment by KatharinaHoff** [comment]
I have removed the hard coded upper limit with commit https://github.com/Gaius-Augustus/BRAKER/commit/cf2dd4a1125fd0b1e4f3deb4d41100cab7d9fb91
