### ISSUE TITLE
augustus not executable on this machine despite permission -rwxrwxr-x

### ISSUE THREAD

**Issue by astulaaa** [Gaius-Augustus/BRAKER#119]
Hi!

I have added augustus to the path for braker2 to locate 
example here: export AUGUSTUS_CONFIG_PATH=/Project1/Resources/Programs/Augustus/Augustus/config/:$PATH
And I get braker error in file /braker.pl at line 3176  ... augustus not executable on this machine.      However, I can see that augustus program that I linked is executable with file writing permissions  
 "-rwxrwxr-x"
What could be the problem?

**Comment by KatharinaHoff** [comment]
For checking whether augustus is executable, BRAKER runs 

`augustus > /dev/null 2> /dev/null` and checks whether the return code is 0. That should be the case if everything is ok with the augustus binary. You can confirm in your shell what the return code is by running

`echo "$?"` after executing above line.

Is it 0 on your machine?

Katharina

**Comment by astulaaa** [comment]
Hello, oddly enough in shell it did not return anything. This is in the log file of an actual run, hope that helps:    --AUGUSTUS_CONFIG_PATH=/anaconda3/envs/Augustus/config 1> /dev/null 2>/BiO/Programs/braker/errors/new_species.stderr in the "CREATING DIRECTORY STRUCTURE" 
section 
and --ALIGNMENT_TOOL_PATH=/Programs/Genomethreader/gth-1.7.1-Linux_x86_64-64bit/bin --prg=gth --CPU=47 >> /Programs/braker/errors/startAlign.stdout 2>>/Programs/braker/errors/startAlign.stderr. This is still running (and augustus is different version as well as different directory now)

**Comment by KatharinaHoff** [comment]
You can hand the paths to dependencies explicitely to BRAKER when starting the script, instead of relying on environment variables, that in your case seem to be a mess. (There's also a --AUGUSTUS_BIN_PATH, --AUGUSTUS_SCRIPTS_PATH .)

**Comment by tomasbruna** [comment]
Hi,

error code 127 is returned when `augustus` cannot be found, i.e. it is not in your $PATH variable.

You can solve this by adding AUGUSTUS to the `$PATH` or, just like Katharina suggested, you can tell BRAKER where AUGUSTUS is directly with the option:

`--AUGUSTUS_CONFIG_PATH /path/to/Augustus/config` to point to the location of AUGUSTUS config directory. BRAKER will then assume that AUGUSTUS `bin` and `scripts` directories are located in the parent dir of `config`.

Using this option should be enough, if AUGUSTUS is installed in a standard way.

Tomas

**Comment by Xiaofei-git** [comment]
Thanks a lot!

Xiaofei

**Comment by Xiaofei-git** [comment]
Fixed, it turns out my AUGUSTUS is not installed properly. Thanks a lot!

**Comment by CLAIRE-cuhk** [comment]
> For checking whether augustus is executable, BRAKER runs
> 
> `augustus > /dev/null 2> /dev/null` and checks whether the return code is 0. That should be the case if everything is ok with the augustus binary. You can confirm in your shell what the return code is by running
> 
> `echo "$?"` after executing above line.
> 
> Is it 0 on your machine?
> 
> Katharina

Hi,

I got a similar error:
ERROR: in file /exeh_1/claire/biosoft/braker2/BRAKER/scripts/braker.pl at line 3322
/exeh_1/claire/biosoft/miniconda/miniconda3/envs/braker2/bin/augustus not executable on this machine.
I am running the braker in a conda envs because I downloaded AUGUSTUS using conda. When I run `echo "$?"`, the system returns 0.

**Comment by tomasbruna** [comment]
Just to verify, do you get "0" result when you run those two commands in succession?

    augustus > /dev/null 2> /dev/null
    echo "$?"

In the same environment you run BRAKER.

Tomas

**Comment by StromTroopers** [comment]
Hello, what if the commande `augustus > /dev/null 2> /dev/null` gives us a `1` as a result in the cluster machines ? 
I set the `augustus/bin` directory with `chmod +777` and added in the bash script the bin, script and confi path ...

**Comment by tomasbruna** [comment]
Hello @StromTroopers,

try to run the command without redirecting the output to `/dev/null`, i.e.

    augustus

It should print what's the problem.

Giving the paths via `--AUGUSTUS_SCRIPTS_PATH` etc., like you did, should work without any issues, if the augustus binary itself is executable.

Best,
Tomas

**Comment by aditi17142** [comment]
Hi!
I am running braker in my local by pulling Augustus from docker. But Augustus isn't working.
I am using Augustus image from docker and using in my local. But its not working, the error is:

# Mon Mar 15 11:14:29 2021: ERROR: in file ./braker.pl at line 3657
/home/Desktop/config/../bin/augustus not executable on this machine

Kindly help.

**Comment by tomasbruna** [comment]
Hello,

when you try to execute AUGUSTUS separately, outside of BRAKER, does it work?

Best,
Tomas

**Comment by aditi17142** [comment]
Thank you very much for replying.

I checked and realized Augustus is not working in my local.
Kindly guide how can I use Augustus from docker in my local machine, where all other dependencies are correctly installed and are working.

Thank you.

**Comment by KatharinaHoff** [comment]
This is an issue for the AUGUSTUS repository where people who make the
docker image are working. (I am not sure how to do what you want to do.)

Katharina

**Comment by aditi17142** [comment]
Thanks!

**Comment by aditi17142** [comment]
Hi!
I checked Augustus, it is working outside braker.
wherever I write augustus, it outputs
AUGUSTUS (3.3) is a gene prediction tool
written by M. Stanke, O. Keller, S. König, L. Gerischer and L. Romoth.

usage:
augustus [parameters] --species=SPECIES queryfilename

'queryfilename' is the filename (including relative path) to the file containing the query sequence(s)
in fasta format.

SPECIES is an identifier for the species. Use --species=help to see a list.

parameters:
. 
.
.
but when I am working with braker command, it gives an error

**Command:**
./braker.pl /home/Desktop/GenomeAnnotation/ProtHint/genome.fasta --hints=/home/Desktop/GenomeAnnotation/ProtHint/ProtOut/prothint_augustus.gff --softmasking --AUGUSTUS_CONFIG_PATH=/usr/local/bin/augustus

**Output:**
Use of uninitialized value $species in concatenation (.) or string at ./braker.pl line 1710.
#**********************************************************************************
#                               BRAKER CONFIGURATION                               
#**********************************************************************************
# BRAKER CALL: ./braker.pl /home/yeastbiofuel/Desktop/GenomeAnnotation/ProtHint/genome.fasta --hints=/home/yeastbiofuel/Desktop/GenomeAnnotation/ProtHint/ProtOut/prothint_augustus.gff --softmasking --AUGUSTUS_CONFIG_PATH=/usr/bin//augustus
# Wed Mar 17 15:17:43 2021: braker.pl version 2.1.5
# Wed Mar 17 15:17:43 2021: Checking whether hints from RNA-Seq and/or proteins are present in hintsfile
# Wed Mar 17 15:17:43 2021: REMARK: Protein input detected, BRAKER will be executed in the EP mode (--epmode).
# Wed Mar 17 15:17:43 2021: Configuring of BRAKER for using external tools...
#*********
: WARNING: Command line flag --AUGUSTUS_CONFIG_PATH was provided. The given path /usr/bin//augustus is not a directory. Cannot use this as variable $AUGUSTUS_CONFIG_PATH in braker.pl!
#*********
# Wed Mar 17 15:17:43 2021: ERROR: in file ./braker.pl at line 1656
Tried guessing $AUGUSTUS_CONFIG_PATH from system augustus path, but /usr/bin/../config is not a directory.
# Wed Mar 17 15:17:43 2021: ERROR: in file ./braker.pl at line 1708
AUGUSTUS_CONFIG_PATH/species (in this case /usr/bin/../config/) is not writeable.
There are 3 alternative ways to set this variable for braker.pl:
   a) provide command-line argument --AUGUSTUS_CONFIG_PATH=/your/path
   b) use an existing environment variable $AUGUSTUS_CONFIG_PATH
      for setting the environment variable, run
           export AUGUSTUS_CONFIG_PATH=/your/path
      in your shell. You may append this to your .bashrc or
      .profile file in order to make the variable available to all
      your bash sessions.
   c) braker.pl can try guessing the location of
      $AUGUSTUS_CONFIG_PATH from an augustus executable that is
      available in your $PATH variable.
      If you try to rely on this option, you can check by typing
           which augustus
      in your shell, whether there is an augustus executable in
      your $PATH
      Be aware: the $AUGUSTUS_CONFIG_PATH must be writable for
                braker.pl because braker.pl is a pipeline that
                optimizes parameters that reside in that
                directory. This might be problematic in case you
                are using a system-wide installed augustus 
                installation that resides in a directory that is
                not writable to you as a user.

Please guide.
Thank you.

**Comment by tomasbruna** [comment]
Please adjust the `AUGUSTUS_CONFIG_PATH` to `--AUGUSTUS_CONFIG_PATH=/usr/local/bin/augustus/config` or wherever the `config` folder of Augustus is located on your system.

**Comment by aditi17142** [comment]
./braker.pl /home/Desktop/GenomeAnnotation/ProtHint/genome.fasta --hints=/home/Desktop/GenomeAnnotation/ProtHint/ProtOut/prothint_augustus.gff --softmasking --AUGUSTUS_CONFIG_PATH=/home/augustus/config --AUGUSTUS_BIN_PATH=/home/Desktop/bin --AUGUSTUS_SCRIPTS_PATH=/home/Desktop/Augustus/scripts --GENEMARK_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies/GeneMarkES --DIAMOND_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies --CDBTOOLS_PATH=/home/Desktop/GenomeAnnotation/BRAKER/cdbfasta
#**********************************************************************************
#                               BRAKER CONFIGURATION                               
#**********************************************************************************
# BRAKER CALL: ./braker.pl /home/Desktop/GenomeAnnotation/ProtHint/genome.fasta --hints=/home/Desktop/GenomeAnnotation/ProtHint/ProtOut/prothint_augustus.gff --softmasking --AUGUSTUS_CONFIG_PATH=/home/augustus/config --AUGUSTUS_BIN_PATH=/home/Desktop/bin --AUGUSTUS_SCRIPTS_PATH=/home/Desktop/Augustus/scripts --GENEMARK_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies/GeneMarkES --DIAMOND_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies --CDBTOOLS_PATH=/home/Desktop/GenomeAnnotation/BRAKER/cdbfasta
# Thu Mar 18 10:36:17 2021: braker.pl version 2.1.5
# Thu Mar 18 10:36:17 2021: Checking whether hints from RNA-Seq and/or proteins are present in hintsfile
# Thu Mar 18 10:36:17 2021: REMARK: Protein input detected, BRAKER will be executed in the EP mode (--epmode).
# Thu Mar 18 10:36:17 2021: Configuring of BRAKER for using external tools...
# Thu Mar 18 10:36:17 2021: Command line flag --AUGUSTUS_CONFIG_PATH was provided. Setting $AUGUSTUS_CONFIG_PATH in braker.pl to /home/augustus/config.
# Thu Mar 18 10:36:17 2021: Setting $AUGUSTUS_BIN_PATH to command line argument --AUGUSTUS_BIN_PATH value /home/Desktop/bin.
# Thu Mar 18 10:36:17 2021: Setting $AUGUSTUS_SCRIPTS_PATH to command line argument --AUGUSTUS_SCRIPTS_PATH value /home/Desktop/Augustus/scripts.
# Thu Mar 18 10:36:17 2021: Trying to guess $PYTHON3_PATH from location of python3 executable that is available in your $PATH
# Thu Mar 18 10:36:17 2021: Setting $PYTHON3_PATH to /usr/bin
# Thu Mar 18 10:36:17 2021: Setting $GENEMARK_PATH to command line argument --GENEMARK_PATH value /home/Desktop/GenomeAnnotation/ProtHint/dependencies/GeneMarkES.
# Thu Mar 18 10:36:17 2021: Setting $DIAMOND_PATH to command line argument --DIAMOND_PATH value /home/Desktop/GenomeAnnotation/ProtHint/dependencies.
# Thu Mar 18 10:36:17 2021: Setting $CDBTOOLS_PATH to command line argument --CDBTOOLS_PATH value /home/Desktop/GenomeAnnotation/BRAKER/cdbfasta.
# Thu Mar 18 10:36:17 2021: ERROR: in file ./braker.pl at line 3657
/home/Desktop/bin/augustus not executable on this machine.

**Comment by aditi17142** [comment]
Thank you @tomasbruna.

**Comment by aditi17142** [comment]
./braker.pl --genome=genome.fasta --hints=/home/Desktop/GenomeAnnotation/ProtHint/ProtOut/prothint_augustus.gff --softmasking --AUGUSTUS_CONFIG_PATH=/home/augustus/config --AUGUSTUS_BIN_PATH=/home/Augustus/bin --AUGUSTUS_SCRIPTS_PATH=/home/Augustus/scripts --GENEMARK_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies/GeneMarkES --DIAMOND_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies --CDBTOOLS_PATH=/home/Desktop/GenomeAnnotation/BRAKER/cdbfasta
# Thu Mar 18 14:45:55 2021: Log information is stored in file /home/Desktop/GenomeAnnotation/BRAKER/scripts/braker/braker.log
ERROR: in file /home/Desktop/GenomeAnnotation/BRAKER/scripts/./helpMod.pm at line 307
 found neither /home/Augustus/scripts/filterIntronsFindStrand.pl nor /home/Augustus/scripts/filterIntronsFindStrand.pl nor /home/augustus/scripts/filterIntronsFindStrand.pl nor /home/Desktop/GenomeAnnotation/BRAKER/scripts/braker/filterIntronsFindStrand.pl!
Please Check the environment variables AUGUSTUS_CONFIG_PATH and command line options AUGUSTUS_BIN_PATH and AUGUSTUS_SCRIPTS_PATH or install AUGUSTUS, again!

**Comment by tomasbruna** [comment]
Hello,

the `braker.pl` file should be in the same folder as all other BRAKER scripts (including `filterIntronsFindStrand.pl`).

I guess what happened in your case is that you moved `braker.pl` to a different folder and it cannot find all the other scripts it depends on.

Best,
Tomas

**Comment by aditi17142** [comment]
Thank you for replying @tomasbruna 
braker.pl and other files including filterIntronsFindStrand.pl are in the /scripts folder only.

**Comment by aditi17142** [comment]
I tried again by installing Augustus all over again. I have obtained the same output again.

./braker.pl --genome=genome.fasta --hints=/home/Desktop/GenomeAnnotation/ProtHint/ProtOut/prothint_augustus.gff --softmasking --AUGUSTUS_CONFIG_PATH=/home/Desktop/config --AUGUSTUS_BIN_PATH=/home/Desktop/GenomeAnnotation/augustus-3.4.0/bin --AUGUSTUS_SCRIPTS_PATH=/home/Desktop/GenomeAnnotation/augustus-3.4.0/scripts --GENEMARK_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies/GeneMarkES --DIAMOND_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies --CDBTOOLS_PATH=/home/Desktop/GenomeAnnotation/BRAKER/cdbfasta
# Fri Mar 19 12:43:31 2021: Log information is stored in file /home/Desktop/GenomeAnnotation/BRAKER/scripts/braker/braker.log
ERROR: in file /home/Desktop/GenomeAnnotation/BRAKER/scripts/./helpMod.pm at line 307
 found neither /home/Desktop/GenomeAnnotation/augustus-3.4.0/scripts/filterIntronsFindStrand.pl nor /home/Desktop/GenomeAnnotation/augustus-3.4.0/scripts/filterIntronsFindStrand.pl nor /home/Desktop/scripts/filterIntronsFindStrand.pl nor /home/yeastbiofuel/Desktop/GenomeAnnotation/BRAKER/scripts/braker/filterIntronsFindStrand.pl!
Please Check the environment variables AUGUSTUS_CONFIG_PATH and command line options AUGUSTUS_BIN_PATH and AUGUSTUS_SCRIPTS_PATH or install AUGUSTUS, again!

**Comment by tomasbruna** [comment]
Hello @aditi17142,

you are right, this really seems to be a bug. Until we fix it, please call BRAKER using the absolute path:

```
/home/yeastbiofuel/Desktop/GenomeAnnotation/BRAKER/scripts/braker.pl  --genome=genome.fasta ..
```

Sorry about this and thanks for reporting this issue!
Tomas

**Comment by aditi17142** [comment]
Thank you for replying @tomasbruna

**Comment by aditi17142** [comment]
I ran the command:

./braker.pl --genome=genome.fasta --hints=/home/Desktop/GenomeAnnotation/ProtHint/ProtOut/prothint_augustus.gff --softmasking --AUGUSTUS_CONFIG_PATH=/home/Desktop/config --AUGUSTUS_BIN_PATH=/home/Desktop/GenomeAnnotation/augustus-3.4.0/bin --AUGUSTUS_SCRIPTS_PATH=/home/Desktop/GenomeAnnotation/augustus-3.4.0/scripts --GENEMARK_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies/GeneMarkES --DIAMOND_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies --CDBTOOLS_PATH=/home/yeastbiofuel/Desktop/GenomeAnnotation/BRAKER/cdbfasta --workingdir=/home/Desktop/GenomeAnnotation/BRAKER/braker_output

ERROR: in file /home/Desktop/GenomeAnnotation/BRAKER/scripts/./helpMod.pm at line 307
 found neither /home/Desktop/GenomeAnnotation/augustus-3.4.0/scripts/sortGeneMark.py nor /home/

/Desktop/GenomeAnnotation/augustus-3.4.0/scripts/sortGeneMark.py nor /home/Desktop/scripts/sortGeneMark.py nor /home/Desktop/GenomeAnnotation/BRAKER/braker_output/sortGeneMark.py!
Please Check the environment variables AUGUSTUS_CONFIG_PATH and command line options AUGUSTUS_BIN_PATH and AUGUSTUS_SCRIPTS_PATH or install AUGUSTUS, again!

Whenever I am using braker command, I have encountered another error. Its looking for a file sortGeneMark.py in augustus folder, while the file is in the BRAKER/scripts/ folder itself, where I have run the command.

**Comment by aditi17142** [comment]
I guess there is this problem with each executable file present in BRAKER/scripts.
Each time, I am running braker.pl, I am witnessing error: executable file "ensure_n_training_genes.py" not found. Though I am running the command in scripts folder. 

Kindly guide how to go about it.
Thank you.

**Comment by tomasbruna** [comment]
Hello,

does this error happen when you run BRAKER with the absolute path as suggested previously (with ` /home/Desktop/GenomeAnnotation/BRAKER/scripts/braker.pl`)?

Even with the relative path (`./braker.pl`), the problem should be fixed, I committed a fix on Saturday. Did you update BRAKER (specifically, the https://github.com/Gaius-Augustus/BRAKER/blob/master/scripts/helpMod.pm script) since then?

Tomas

**Comment by aditi17142** [comment]
Hi!
I updated the file "helpMod.pm" and have run the BRAKER, using the relative path (./braker.pl)
The command is running. Waiting for the output, if no error emerges.

Thank you very much for replying.

**Comment by aditi17142** [comment]
I run the command:

./braker.pl --genome=genome.fasta --hints=/home/Desktop/GenomeAnnotation/ProtHint/ProtOut/prothint_augustus.gff --softmasking --AUGUSTUS_CONFIG_PATH=/home/Desktop/config --AUGUSTUS_BIN_PATH=/home/Desktop/GenomeAnnotation/augustus-3.4.0/bin --AUGUSTUS_SCRIPTS_PATH=/home/Desktop/GenomeAnnotation/augustus-3.4.0/scripts --GENEMARK_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies/GeneMarkES --DIAMOND_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies --CDBTOOLS_PATH=/home/Desktop/GenomeAnnotation/BRAKER/cdbfasta --workingdir=/home/Desktop/GenomeAnnotation/BRAKER/braker_output

# Tue Mar 23 10:04:32 2021: Log information is stored in file /home/Desktop/GenomeAnnotation/BRAKER/braker_output/braker.log
ERROR in file ./braker.pl at line 8069
Failed to execute: perl /home/Desktop/GenomeAnnotation/augustus-3.4.0/scripts/optimize_augustus.pl --aug_exec_dir=/home/Desktop/GenomeAnnotation/augustus-3.4.0/bin --rounds=5 --species=Sp_19 --kfold=8 --AUGUSTUS_CONFIG_PATH=/home/Desktop/config --onlytrain=/home/Desktop/GenomeAnnotation/BRAKER/braker_output/train.gb.train.train /home/Desktop/GenomeAnnotation/BRAKER/braker_output/train.gb.train.test 1>/home/Desktop/GenomeAnnotation/BRAKER/braker_output/optimize_augustus.stdout 2>/home/Desktop/GenomeAnnotation/BRAKER/braker_output/errors/optimize_augustus.stderr!

Is the error means that it couldn't find Perl executable files.
Kindly guide. 
Thank you.

**Comment by tomasbruna** [comment]
Please share the contents of `/home/Desktop/GenomeAnnotation/BRAKER/braker_output/optimize_augustus.stdout` and `/home/Desktop/GenomeAnnotation/BRAKER/braker_output/errors/optimize_augustus.stderr`

There should be some useful error messages in those files.

**Comment by aditi17142** [comment]
Hi!
Thank you.
I have dropped the output file from above command:

[optimize_augustus.zip](https://github.com/Gaius-Augustus/BRAKER/files/6194547/optimize_augustus.zip)

[optimize_augustus_stderr.zip](https://github.com/Gaius-Augustus/BRAKER/files/6194553/optimize_augustus_stderr.zip)

**Comment by KatharinaHoff** [comment]
Please make sure that all required executables are in your PATH variable. optimize_augustus.pl was unable to locate etraining, which resides in Augustus/bin/.

**Comment by aditi17142** [comment]
Thank you @KatharinaHoff 
Actually, I am unable to find what all executables are required in /AUGUSTUS/bin
All the executables are found in /AUGUSTUS/scripts

The command is taking long in processing and later I am encountering these errors.
Kindly suggest if I can fix the requirement of executables, as I do not know what all executables are required.

I shall be highly obliged.

**Comment by tomasbruna** [comment]
Hello,

as Katharina suggested, adding the AUGUSTUS bin directory to your PATH would solve the issue. This could be done like this, before running BRAKER:

```
export PATH=/home/Desktop/GenomeAnnotation/augustus-3.4.0/bin:$PATH
``` 

I also have an alternative solution to the one Katharina suggested. I think the error you are getting is a result of a bug, fixed recently in https://github.com/Gaius-Augustus/Augustus/commit/d1c4f9f335579a69f3b56e54f02cf0c36a1ed7ba. If you download the latest optimize_augustus.pl form https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/optimize_augustus.pl and replace the old one in `/home/Desktop/GenomeAnnotation/augustus-3.4.0/scripts`, the problem should go away.

> The command is taking long in processing and later I am encountering these errors.

I encourage you to first test BRAKER on the example tests (in https://github.com/Gaius-Augustus/BRAKER/tree/master/example/tests). They take a maximum of ~20 minutes and you can thus quickly judge whether everything works correctly before running BRAKER on a large dataset.

Best,
Tomas

**Comment by aditi17142** [comment]
Thank you so much for replying @tomasbruna and @KatharinaHoff 
I have added AUGUSTUS bin directory to the path in bash file.
I updated optimize_augustus.pl and only then ran the final braker command. But still I am encountering error.
Further, I am now going with example test files.

Thank you.

**Comment by aditi17142** [comment]
Thank you so much!
i could run BRAKER successfully.
Kindly share the source from where I can interpret the results correctly.

**Comment by tomasbruna** [comment]
Glad to hear it worked out!

> Kindly share the source from where I can interpret the results correctly.

You can start by reading what each output represents: https://github.com/Gaius-Augustus/BRAKER#output-of-braker

If you want to understand more what BRAKER2 does (which will definitely help you to interpret the results), please read a recent publication about BRAKER2: https://academic.oup.com/nargab/article/3/1/lqaa108/6066535

**Comment by minghuiyin** [comment]
when I run braker.pl, I got this error:
ERROR: augustus executable not found at ~/miniconda3/envs/test_env/bin/augustus/config/../bin/augustus.
I'll appreciate if anyone could help me to solve this problem!
