### ISSUE TITLE
question about splice sites

### ISSUE THREAD

**Issue by peterthorpe5** [Gaius-Augustus/BRAKER#12]
Dear Braker,
      (your software has been great for me on my published genomes - thanks!!!)

In the code line 7303 in the latest Braker (December2018) there is a line --allow_hinted_splicesites=gcag,atac - these are non-cononical splice sites, which I know my beast of interest has. Does Braker by default allow non-cononical splice sites (depending on RNAseq or protein evidence)? or do you have to specify them, see the line below

In the developmental options:
--splice_sites (default GTAG) ... this says it is for the UTR regions. Is this for the UTR only, or do you need to specify the non-cononical splice sites for Braker to use in the main genic predictions?

cheers,

Peter Thorpe

**Comment by KatharinaHoff** [comment]
Hi Peter,
for predictions without UTR model, BRAKER will predict genes with --allow_hinted_splicesites=gcag,atac by default.
The --splice_sites option of braker.pl refers to which putative introns from RNA-Seq data shall be used for building UTR training examples, only. 
The answer is therefore: no, you don't need to specify those two splice sites for the main gene prediction step.
Best,
Katharina

**Comment by peterthorpe5** [comment]
Thank you!!
