### ISSUE TITLE
Error in training gene selection in --esmode

### ISSUE THREAD

**Issue by tomasbruna** [Gaius-Augustus/BRAKER#121]
When filtering GeneMark output in --esmode, genes > 800 nt are supposed to be chosen. Instead, only individual exons > 800 nt are chosen for Augustus.

This is caused by a change in GeneMark output, the following code 

https://github.com/Gaius-Augustus/BRAKER/blob/036eb3b28fb3591cd58010489898b860332bbd41/scripts/braker.pl#L6361-L6372

assumes a unique gene identifier in the 9.th gtf column, however, the column now contains additional information. `transcript_id` needs to be used instead.

**Comment by KatharinaHoff** [comment]
Hi Tomas!

Thank you for pointing this out! I am fixing it with commit https://github.com/Gaius-Augustus/BRAKER/commit/d682e7592c9a0a57204eb96a2953e831b76e047b .

Thanks!

Katharina
