### ISSUE TITLE
Number of cores not detected

### ISSUE THREAD

**Issue by fergsc** [Gaius-Augustus/BRAKER#128]
Hi, I am running Braker2 on a pbs system and the number of core is not being detected. BRAKER.log contains this message.

 ```
WARNING: Your system does not have 16 cores available, only 1. Braker will use the 1 available instead of the chosen 16.
```

Are there any known issues/work arounds for this.

thanks.

**Comment by KatharinaHoff** [comment]
nproc is apparently not available on your system (or the system was identified as Linux). I have changed the code a bit. If the system is identified as linux, you shouldn't have problems anymore, in the future. If nproc is not there, I try to grep the number of cores from a system file, and if that doesn't work, I only issue a warning, now. If the system does not identify as linux, please reopen and let me know.

https://github.com/Gaius-Augustus/BRAKER/commit/d7249fdf5fd5fb6d2f71b32b15ca5d925c1bfc97

Katharina

**Comment by nathanweeks** [comment]
A colleague just encountered this in BRAKER v2.1.4---good to know it's addressed in the latest release. FWIW, a portable way of checking number of "CPUs" (the definition of which isn't so portable; e.g., could be hardware threads on CPUs that support SMT) is the command `getconf _NPROCESSORS_ONLN`, which is specified by POSIX, and should be fairly portable to most Unix-like operating systems (including macOS, FreeBSD, Solaris, and other operating systems that lack by default lack /proc/cpuinfo)

**Comment by KatharinaHoff** [comment]
Thanks, that's a great idea. I have adapted the code to use that! https://github.com/Gaius-Augustus/BRAKER/commit/0404ee39ecfe8770ba7f6cb643cc70566f4aa703

**Comment by fergsc** [comment]
Finally made it back to doing some annotation, thanks for changing this.

I am on a linux based HPC and there are some issues with querying the number of CPUs available for me. When trying to find the number of available CPUs, you get the number available on the queueing comupter and not the actuall HPC.

**Comment by nathanweeks** [comment]
@fergsc : `getconf _NPROCESSORS_ONLN` should return the number of processor cores (or hardware threads, if SMT is enabled in the CPU) for the compute node that braker.pl is running on. This could cause issues if your batch job hasn't reserved all of the processors on a node (e.g., if you've reserved half of the processors on a node, braker.pl would still attempt to use all by default, leading to oversubscription). If you're using, e.g., SLURM, you could invoke `braker.pl --cores=${SLURM_CPUS_ON_NODE}`, as that environment variable contains the "Count of processors available to the job on this node".

But that's just a guess, and might not be what is going on here; would need additional details.
