### ISSUE TITLE
default gene name to custom name

### ISSUE THREAD

**Issue by gitarunprasanna83** [Gaius-Augustus/BRAKER#130]
Hi,
Braker produces output gff with default gene ids :

g1
g1.t1
g1.t1.exon1
g1.t1.CDS1

Is it possible to pass an argument in braker so that I can have a custom names straightaway? For example,

Sp_gene1 .... i.e instead "g" I can have a prefix "Sp_gene". This way, it saves lot of effort downstream.

Thanks in advance.

**Comment by KatharinaHoff** [comment]
No, BRAKER will currently not rename the gene models.

When renaming them yourself, be aware that some AUGUSTUS genes are called "g1...", other are called "jg1..."... and GeneMark calls them "1_g"

Katharina
