### ISSUE TITLE
Braker runtime

### ISSUE THREAD

**Issue by kazuaki0816** [Gaius-Augustus/BRAKER#131]
I am running the following command. 
$ braker.pl --species=yourSpecies --cores 8 --genome=/home/Braker/genome.fasta.masked --prot_seq=/home/Braker/Protein_hints.fasta --prg=gth --bam=/home/Braker/RNAseq_hints.sorted.bam --softmasking --UTR=off --makehub --gff3 --AUGUSTUS_ab_initio --email=hoge@co.jp

The Braker run has not finished and the gth process has been in progress for about a month. 
I created Protein_hints.fasta by selecting and translating closely related transcripts assembly sequences using Transdecoder. The number of sequences is 853,133.
Is the gth process protracted due to the number of protein sequences?

By the way, the genome assembly sequence includes scaffold sequences of 10 kb or less, and shows the following stats.
Number of scaffolds: 67,748
Total assembly size: 2,871,809,165
Minimum length: 500
Average length: 42,389.6
Maximum length: 187,018,787

**Comment by baizixiansheng** [comment]
For the running time, I have kill the task, but the data is still uploaded. I wonder know how to stop the data being uploaded. There is my condition:
`-rw-r--r-- 1 chens customer 17G Feb  5 19:15 prot_addstop.fasta`

**Comment by KatharinaHoff** [comment]
I am not sure what you mean. BRAKER should not upload data to any server.
