### ISSUE TITLE
Breaker error using example files

### ISSUE THREAD

**Issue by kazuaki0816** [Gaius-Augustus/BRAKER#134]
**I installed the latest Breaker, Augustus, and GeneMark today.
I then ran the test with example files and got the following error.** 
$ braker.pl --cores 8 --genome=genome.fa --bam=RNAseq.bam --softmasking
mv: Missing destination file operand
Try 'mv --help' for more information.
ERROR in file /home/local/tool/BRAKER/scripts/braker.pl at line 5506
Failed to execute: mv $to_be_merged $hints_file_temp

**So I modified it as follows.**
5461	$cmdString = 'mv $not_to_be_merged $hints_file_temp';
→ $cmdString = "mv $not_to_be_merged $hints_file_temp";
5502	$cmdString = 'mv $to_be_merged $hints_file_temp';
→ $cmdString = "mv $to_be_merged $hints_file_temp";

**I ran the modified script. Then I experienced the following error.**
$ braker.pl --cores 8 --genome=genome.fa --bam=RNAseq.bam --softmasking
Thu Dec 12 14:40:07 2019: Log information is stored in file /home/local/tool/BRAKER/example/braker/braker.log
Thu Dec 12 14:40:14 2019: ERROR: in file /home/local/tool/BRAKER/scripts/braker.pl at line 4865
The hints file is empty. Maybe the genome and the RNA-seq file do not belong together.

$ braker.pl --genome=genome.fa --prot_seq=prot.fa --prg=gth --bam=RNAseq.bam --softmasking
Thu Dec 12 17:23:45 2019: Log information is stored in file /home/local/tool/BRAKER/example/braker/braker.log
Thu Dec 12 17:23:55 2019: ERROR: in file /home/local/tool/BRAKER/scripts/braker.pl at line 4865
The hints file is empty. Maybe the genome and the RNA-seq file do not belong together.

**When I entered the following command, the result files were output successfully.**
$ braker.pl --genome=genome.fa --prot_seq=prot.fa --prg=gth --trainFromGth --softmasking
Thu Dec 12 14:51:59 2019: Log information is stored in file /home/local/tool/BRAKER/example/braker/braker.log
WARNING: Number of reliable training genes is low (69). Recommended are at least 600 genes

**Comment by KatharinaHoff** [comment]
Please run a git pull. I think this problem has already been fixed.
