### ISSUE TITLE
new proteins from repeated BRAKER2 runs

### ISSUE THREAD

**Issue by krabapple** [Gaius-Augustus/BRAKER#136]
I'm running BRAKER2 in the mode that uses RNAseq + closely-related protein sequences as evidence (proteins are used in training and prediction steps -- i.e., the final mode described in the PDF).  My genome is an intron-sparse eukaryotic genome with a high percentage of repetitive elements (these are softmasked).  I've found that running BRAKER repeatedly, with exactly the same parameters (except assigning a new species ID and output dir for each run), returns different numbers of proteins sequences...to be expected, I guess, since  random seeds are involved.  After 4 runs BRAKER2 is returning between 19-21,000 proteins (augustus.hints.aa) per run.  But an average of ~4500 new protein sequences are unique to the run (i.e. not identical to any sequence in the other 3 runs).  Does this sound normal? Is there a point where running BRAKER iteratively would return few or no new proteins?

**Comment by KatharinaHoff** [comment]
There are several random components in BRAKER. We sometimes also run replicates to get an estimate on standard deviation. It’s usually smaller, though. Maybe it depends on the reference set, too (e.g. two transcript variants from different runs might both be in reference annotation, thus effect is cancelled).
