### ISSUE TITLE
wheat_metapars.cfg for species wheat does not exist

### ISSUE THREAD

**Issue by xiaoaozqd** [Gaius-Augustus/BRAKER#137]
When I used the pre-trained parameters for wheat, there is an error as follow, how can I find this file or create it by myself?
`
wd=braker_pre_trained

if [ -d $wd ]; then
    rm -r $wd
fi

( time braker.pl --cores 20 --genome=./ds_w0.fa --bam=ABOSW7_sorted.bam,ACOSW1_sorted.bam --species=wheat --skipAllTraining --softmasking --workingdir=$wd ) &> braker_pre_trained.log
`
error "Config file /home/zengqd/miniconda3/envs/braker2/config//species/wheat/wheat_metapars.cfg for species wheat does not exist!"

**Comment by KatharinaHoff** [comment]
Go to the $AUGUSTUS_CONFIG_PATH, browse through a couple of folders of different species, one of them will have a *_metapars.cfg file. Copy that file to your species folder, rename the file stem to your species name.

The metapars file is not actively used with --skipAllTraining, so the contents don't matter.

**Comment by KatharinaHoff** [comment]
https://github.com/Gaius-Augustus/BRAKER/commit/77cf43fe984f9a94be9222ab52b13571eb4c97bc

This problem should in the future not arise, anymore.

Katharina
