### ISSUE TITLE
Failed to execute: perl /home/spider/project/yuantao/soft/gm_et_linux_64/gmes_petap.pl

### ISSUE THREAD

**Issue by taotaoyuan** [Gaius-Augustus/BRAKER#138]
This is my braker.log
`#**********************************************************************************
#                               BRAKER CONFIGURATION                               
#**********************************************************************************
# BRAKER CALL: /root/miniconda3/envs/braker2/bin/braker.pl --species=nephila_laurinae --genome=/home/spider/project/yuantao/test/LTR/nep_masked/laurinae.fasta.masked --bam=/home/spider/project/yuantao/test/01_augustus/nep_unmaskedAligned.sortedByCoord.out.bam --prot_seq=/home/spider/project/yuantao/test/03_run_braker/proteins.fa --cores 8 --softmasking
# Tue Dec 24 21:49:41 2019: braker.pl version 2.1.4
# Tue Dec 24 21:49:41 2019: Configuring of BRAKER for using external tools...
# Tue Dec 24 21:49:41 2019: Found environment variable $AUGUSTUS_CONFIG_PATH. Setting $AUGUSTUS_CONFIG_PATH to /home/spider/soft/miniconda3/config/
# Tue Dec 24 21:49:41 2019: Found environment variable $AUGUSTUS_BIN_PATH. Setting $AUGUSTUS_BIN_PATH to /home/spider/soft/miniconda3/bin/
# Tue Dec 24 21:49:41 2019: Found environment variable $AUGUSTUS_SCRIPTS_PATH. Setting $AUGUSTUS_SCRIPTS_PATH to /home/spider/soft/miniconda3/bin/
# Tue Dec 24 21:49:41 2019: Found environment variable $GENEMARK_PATH. Setting $GENEMARK_PATH to /home/spider/project/yuantao/soft/gm_et_linux_64
# Tue Dec 24 21:49:41 2019: Found environment variable $BAMTOOLS_PATH. Setting $BAMTOOLS_PATH to /home/spider/soft/miniconda3/bin/
# Tue Dec 24 21:49:41 2019: Found environment variable $SAMTOOLS_PATH. Setting $SAMTOOLS_PATH to /home/spider/soft/miniconda3/bin/
# Tue Dec 24 21:49:41 2019: Found environment variable $ALIGNMENT_TOOL_PATH. Setting $ALIGNMENT_TOOL_PATH to /home/spider/soft/miniconda3/bin/
# Tue Dec 24 21:49:41 2019: Found environment variable $DIAMOND_PATH. Setting $DIAMOND_PATH to /home/spider/soft/miniconda3/bin/
# Tue Dec 24 21:49:41 2019: Found environment variable $PYTHON3_PATH. Setting $PYTHON3_PATH to /home/spider/soft/miniconda3/bin/
# Tue Dec 24 21:49:41 2019: Found environment variable $CDBTOOLS_PATH. Setting $CDBTOOLS_PATH to /home/spider/project/yuantao/soft/cdbfasta-master
#*********
# WARNING: in file /root/miniconda3/envs/braker2/bin/braker.pl at line 4095
No alignment tool was specified for aligning protein sequences against genome. Setting GenomeThreader as default alignment tool.
#*********
#**********************************************************************************
#                               CREATING DIRECTORY STRUCTURE                       
#**********************************************************************************
# Tue Dec 24 21:49:41 2019: create working directory /home/spider/project/yuantao/test/03_run_braker/braker.
mkdir /home/spider/project/yuantao/test/03_run_braker/braker
# Tue Dec 24 21:49:41 2019: create working directory /home/spider/project/yuantao/test/03_run_braker/braker/GeneMark-ET.
mkdir /home/spider/project/yuantao/test/03_run_braker/braker/GeneMark-ET
# Tue Dec 24 21:49:41 2019: create working directory /home/spider/project/yuantao/test/03_run_braker/braker/species
mkdir /home/spider/project/yuantao/test/03_run_braker/braker/species
# Tue Dec 24 21:49:41 2019: create working directory /home/spider/project/yuantao/test/03_run_braker/braker/errors
mkdir /home/spider/project/yuantao/test/03_run_braker/braker/errors
# Tue Dec 24 21:49:41 2019: changing into working directory /home/spider/project/yuantao/test/03_run_braker/braker
cd /home/spider/project/yuantao/test/03_run_braker/braker
# Tue Dec 24 21:49:41 2019: Creating parameter template files for AUGUSTUS with new_species.pl
# Tue Dec 24 21:49:41 2019: new_species.pl will create parameter files for species nephila_laurinae in /home/spider/soft/miniconda3/config//species/nephila_laurinae
perl /home/spider/soft/miniconda3/bin/new_species.pl --species=nephila_laurinae --AUGUSTUS_CONFIG_PATH=/home/spider/soft/miniconda3/config/ 1> /dev/null 2>/home/spider/project/yuantao/test/03_run_braker/braker/errors/new_species.stderr
# Tue Dec 24 21:49:41 2019: check_fasta_headers(): Checking fasta headers of file /home/spider/project/yuantao/test/LTR/nep_masked/laurinae.fasta.masked
#*********
# WARNING: in file /root/miniconda3/envs/braker2/bin/braker.pl at line 1205
file /home/spider/project/yuantao/test/03_run_braker/braker/genome.fa contains a highly fragmented assembly (70409 scaffolds). This may lead to problems when running AUGUSTUS via braker in parallelized mode. You set --cores=8. You should run braker.pl in linear mode on such genomes, though (--cores=1).
#*********
#**********************************************************************************
#                               PROCESSING HINTS                                   
#**********************************************************************************
# Tue Dec 24 21:51:01 2019: Converting bam files to hints
# Tue Dec 24 21:51:01 2019: Checking bam headers
# Tue Dec 24 21:51:01 2019: create header file /home/spider/project/yuantao/test/03_run_braker/braker/nep_unmaskedAligned_header.sam
/home/spider/soft/miniconda3/bin//bamtools header -in /home/spider/project/yuantao/test/01_augustus/nep_unmaskedAligned.sortedByCoord.out.bam > /home/spider/project/yuantao/test/03_run_braker/braker/nep_unmaskedAligned_header.sam
# Tue Dec 24 21:51:02 2019: Deleting SAM header file /home/spider/project/yuantao/test/03_run_braker/braker/nep_unmaskedAligned_header.sam (will not be needed from here on)
# Tue Dec 24 21:51:02 2019: Deleting /home/spider/project/yuantao/test/03_run_braker/braker/nep_unmaskedAligned_new_header.sam
# Tue Dec 24 21:51:02 2019: make hints from BAM file /home/spider/project/yuantao/test/01_augustus/nep_unmaskedAligned.sortedByCoord.out.bam
/home/spider/soft/miniconda3/bin//bam2hints --intronsonly --in=/home/spider/project/yuantao/test/01_augustus/nep_unmaskedAligned.sortedByCoord.out.bam --out=/home/spider/project/yuantao/test/03_run_braker/braker/bam2hints.temp.0.gff 1> /home/spider/project/yuantao/test/03_run_braker/braker/errors/bam2hints.0.stdout 2>/home/spider/project/yuantao/test/03_run_braker/braker/errors/bam2hints.0.stderr
# Tue Dec 24 21:59:27 2019: add hints from BAM file /home/spider/project/yuantao/test/01_augustus/nep_unmaskedAligned.sortedByCoord.out.bam to hints file
cat /home/spider/project/yuantao/test/03_run_braker/braker/bam2hints.temp.0.gff >>/home/spider/project/yuantao/test/03_run_braker/braker/hintsfile.temp.gff
# Tue Dec 24 21:59:27 2019: Joining hints that are identical (& from the same source) into multiplicity hints (input file /home/spider/project/yuantao/test/03_run_braker/braker/hintsfile.temp.gff)
# Tue Dec 24 21:59:27 2019: sort hints of type rnaseq
cat /home/spider/project/yuantao/test/03_run_braker/braker/hintsfile.temp.gff | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -n -k 3,3 | sort -s -k 1,1 >/home/spider/project/yuantao/test/03_run_braker/braker/hints.rnaseq.temp.sort.gff
# Tue Dec 24 21:59:27 2019: join multiple hints
perl /home/spider/soft/miniconda3/bin/join_mult_hints.pl </home/spider/project/yuantao/test/03_run_braker/braker/hints.rnaseq.temp.sort.gff >/home/spider/project/yuantao/test/03_run_braker/braker/hintsfile.temp.gff 2>/home/spider/project/yuantao/test/03_run_braker/braker/errors/join_mult_hints.rnaseq.stderr
# Tue Dec 24 21:59:27 2019: filter introns, find strand and change score to 'mult' entry
perl /home/spider/soft/miniconda3/bin/filterIntronsFindStrand.pl /home/spider/project/yuantao/test/03_run_braker/braker/genome.fa /home/spider/project/yuantao/test/03_run_braker/braker/hintsfile.temp.gff --score 1>/home/spider/project/yuantao/test/03_run_braker/braker/hintsfile.gff 2>/home/spider/project/yuantao/test/03_run_braker/braker/errors/filterIntronsFindStrand.stderr
# Tue Dec 24 21:59:39 2019: rm /home/spider/project/yuantao/test/03_run_braker/braker/hintsfile.temp.gff
# Tue Dec 24 21:59:39 2019: Making protein hints
# Tue Dec 24 21:59:39 2019: Changing to /home/spider/project/yuantao/test/03_run_braker/braker
cd /home/spider/project/yuantao/test/03_run_braker/braker
# Tue Dec 24 21:59:39 2019: running Genome Threader to produce protein to genome alignments
perl /home/spider/soft/miniconda3/bin/startAlign.pl --genome=/home/spider/project/yuantao/test/03_run_braker/braker/genome.fa --prot=/home/spider/project/yuantao/test/03_run_braker/proteins.fa --ALIGNMENT_TOOL_PATH=/home/spider/soft/miniconda3/bin/ --prg=gth --CPU=8 >> /home/spider/project/yuantao/test/03_run_braker/braker/errors/startAlign.stdout 2>>/home/spider/project/yuantao/test/03_run_braker/braker/errors/startAlign.stderr
# Wed Dec 25 01:25:47 2019: Alignments from file /home/spider/project/yuantao/test/03_run_braker/proteins.fa created.
# Wed Dec 25 01:25:47 2019: alignment file /home/spider/project/yuantao/test/03_run_braker/braker/align_gth/gth.concat.aln in round 0 was empty.
# Wed Dec 25 01:25:47 2019: moving startAlign output files
mv /home/spider/project/yuantao/test/03_run_braker/braker/align_gth /home/spider/project/yuantao/test/03_run_braker/braker/align_gth0
# Wed Dec 25 01:25:47 2019: Preparing hints for running GeneMark
# Wed Dec 25 01:25:47 2019: Filtering intron hints for GeneMark from /home/spider/project/yuantao/test/03_run_braker/braker/hintsfile.gff...
cat /home/spider/project/yuantao/test/03_run_braker/braker/genemark_hintsfile.gff.rnaseq | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -k 3,3 | sort -s -k 1,1 | /home/spider/soft/miniconda3/bin/join_mult_hints.pl > /home/spider/project/yuantao/test/03_run_braker/braker/genemark_hintsfile.gff.rnaseq.tmp
mv /home/spider/project/yuantao/test/03_run_braker/braker/genemark_hintsfile.gff.rnaseq.tmp /home/spider/project/yuantao/test/03_run_braker/braker/genemark_hintsfile.gff
#**********************************************************************************
#                              RUNNING GENEMARK-EX                                 
#**********************************************************************************
# Wed Dec 25 01:25:47 2019: Checking whether file /home/spider/project/yuantao/test/03_run_braker/braker/genemark_hintsfile.gff contains sufficient multiplicity information...
#*********
# WARNING: 
# The file /home/spider/project/yuantao/test/03_run_braker/braker/genemark_hintsfile.gff contains less than 150 introns with multiplicity >= 10! (In total, 16 unique introns are contained. 0 have a multiplicity >= 10.) Possibly, you are trying to run braker.pl on data that does not supply multiplicity information. This will e.g. happen if you try to use introns generated from assembled RNA-Seq transcripts; or if you try to run braker.pl in epmode with mappings from proteins without sufficient hits per locus.
# A low number of intron hints with sufficient multiplicity may result in a crash of GeneMark-EX.
#*********
# Wed Dec 25 01:25:47 2019: Executing GeneMark-ET
# Wed Dec 25 01:25:47 2019: changing into GeneMark-ET directory /home/spider/project/yuantao/test/03_run_braker/braker/GeneMark-ET
cd /home/spider/project/yuantao/test/03_run_braker/braker/GeneMark-ET
# Wed Dec 25 01:25:47 2019: Executing gmes_petap.pl
perl /home/spider/project/yuantao/soft/gm_et_linux_64/gmes_petap.pl --verbose --sequence=/home/spider/project/yuantao/test/03_run_braker/braker/genome.fa --ET=/home/spider/project/yuantao/test/03_run_braker/braker/genemark_hintsfile.gff --et_score 10 --max_intergenic 50000 --cores=8 --soft_mask 1000 1>/home/spider/project/yuantao/test/03_run_braker/braker/GeneMark-ET.stdout 2>/home/spider/project/yuantao/test/03_run_braker/braker/errors/GeneMark-ET.stderr
`
I have a problem with this error:
Failed to execute: perl /home/spider/project/yuantao/soft/gm_et_linux_64/gmes_petap.pl --verbose --sequence=/home/spider/project/yuantao/test/03_run_braker/braker/genome.fa --ET=/home/spider/project/yuantao/test/03_run_braker/braker/genemark_hintsfile.gff --et_score 10 --max_intergenic 50000 --cores=8 --soft_mask 1000 1>/home/spider/project/yuantao/test/03_run_braker/braker/GeneMark-ET.stdout 2>/home/spider/project/yuantao/test/03_run_braker/braker/errors/GeneMark-ET.stderr

**Comment by labrat9** [comment]
@taotaoyuan did you figure out what your issue was? I am currently experiencing the same issue :(

**Comment by KatharinaHoff** [comment]
GeneMark versions have changed significantly since the issue was opened. It might no longer be an issue. In any case, it seems to be rather a GeneMark than a BRAKER issue. I am closing this issue.
