### ISSUE TITLE
samtools sort code

### ISSUE THREAD

**Issue by cascoamarillo** [Gaius-Augustus/BRAKER#14]
Hi,
Running braker with RNAseq data (bam files) and UTR=on, I encountered one error at the samtools sort step:
In the original braker.pl the code is (line 8991):
`    $cmdString .= "$SAMTOOLS_PATH/samtools sort -\@ "
               .($CPU-1) . " -o $otherfilesDir/merged.s.bam "
               .  "$otherfilesDir/merged.bam "
               .  "1> $otherfilesDir/samtools_sort_before_wig.stdout "
               .  "2> $errorfilesDir/samtools_sort_before_wig.stderr";
    print LOG "\n$cmdString\n" if ($v > 3);`

Looking at samtools sort:

Usage:   samtools sort [options] <in.bam> <out.prefix>
Options: -n        sort by read name
         -f        use <out.prefix> as full file name instead of prefix
         -o        final output to stdout
         -l INT    compression level, from 0 to 9 [-1]
         -@ INT    number of sorting and compression threads [1]
         -m INT    max memory per thread; suffix K/M/G recognized [768M]

So, I thought it may be not correct running it with with  "-o  as final output to stdout". I changed it to:

`    $cmdString .= "$SAMTOOLS_PATH/samtools sort -\@ "
               .($CPU-1) . " $otherfilesDir/merged.bam "
               .  "$otherfilesDir/merged.s "
               .  "1> $otherfilesDir/samtools_sort_before_wig.stdout "
               .  "2> $errorfilesDir/samtools_sort_before_wig.stderr";
    print LOG "\n$cmdString\n" if ($v > 3);`

Deleting the "-o" option, where merged.bam is the input and merged.s is the output name which will be merged.s.bam

I hope this is right.

Thanks

PS. The braker version I am using: I did git clone braker last December'18, and I see in README.TXT file it is from August 22nd.

**Comment by cascoamarillo** [comment]
My bad. I did not see I was using samtools installed in the PATH from another package (piPipes). The version is:

`Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.19-44428cd
`
Thank you.
You may close it now.

**Comment by KatharinaHoff** [comment]
I have added a comment in the braker.pl code at https://github.com/Gaius-Augustus/BRAKER/commit/04d78166bb1f2eeb0ed0343c1f341ac5aea31dc5
I will close this issue.

**Comment by liliailham** [comment]
How to get this version of samtools?

**Comment by KatharinaHoff** [comment]
If you use our container, the included samtools will be compatible.
