### ISSUE TITLE
no exons in augustus.hints.gtf

### ISSUE THREAD

**Issue by krabapple** [Gaius-Augustus/BRAKER#140]
I run BRAKER2 current version with these options:

braker.pl --genome=softmasked.fasta \
       --species=6bDec11_ng2 \
       --prot_seq=523_final_prots.fa \
       --prg=gth \
       --bam=STAR_RNAseq_aligned.bam \
       --gth2traingenes \
       --softmasking \
       --workingdir=braker_1

ie. input evidence include RNAseq, and close homology proteins, and proteins are used in both stages

Later, attempting to do a STAR mapping of RNAseq again, using the augustus.hints.gtf file as an input, STAR threw and error because the augustus.hints.gtf  file contains no 'exon' lines.  I checked and this is true of all the BRAKER2 runs I have done on this genome.  The gtf contains only gene, transcript, CDS, and start/stop codon features.

Is this normal with the options I used?  Do I need to use the .bam evidence only/UTR-finding modes  order to generate 'exon' features in the gtf?

**Comment by krabapple** [comment]
Update: I ran BRAKER2 with only RNAseq as input.  (and did not use --UTR=on).  The augustus.hints.gtf file now has exon features as well as CDS.   

So it appears that when proteins are part of input, only CDS are produced?  Is this the expected behavior, and if so, is there a way to also predict exons (which can be longer than CDS) when proteins are part of evidence?

**Comment by KatharinaHoff** [comment]
Without the UTR flag turned on, AUGUSTUS in BRAKER will produce exon features that are identical to CDS features.

If you mix evidence, joingenes will not output these duplicate features.

**Comment by krabapple** [comment]
Thank you.  To be clear, this also means that --UTR=on doesn't work when mixed evidence is used?

**Comment by krabapple** [comment]
Thank you. To be clear, this also means that --UTR=on doesn't work when
mixed evidence is used?

On Fri, Jan 3, 2020 at 3:55 PM Katharina Hoff <notifications@github.com>
wrote:

> Without the UTR flag turned on, AUGUSTUS in BRAKER will produce exon
> features that are identical to CDS features.
>
> If you mix evidence, joingenes will not output these duplicate features.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Gaius-2DAugustus_BRAKER_issues_140-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DALY7U5VHMJML7RY5QTGJWETQ36Q3ZA5CNFSM4KCGKSHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEICB6II-23issuecomment-2D570695457&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2Zel7OrFNp7vge-EaCVcNA&m=nitu57a69BxsbRH58jF127fUwdXBeEOh8Elsb1cQorM&s=KACa8TbSfSNKIxBP8YIimak4x8tD-38f_s8ns9kmHcM&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ALY7U5WGLSZEHHFV3RS5JRDQ36Q3ZANCNFSM4KCGKSHA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2Zel7OrFNp7vge-EaCVcNA&m=nitu57a69BxsbRH58jF127fUwdXBeEOh8Elsb1cQorM&s=vlNUInwR3ZzHzBk354gJYvj0QB-b7uM3zHMF5NwenGM&e=>
> .
>


-- 
Dr. Steven Sullivan
Center for Genomics & Systems Biology
New York University
12 Waverly Place
New York, NY 10003

**Comment by KatharinaHoff** [comment]
It means that --UTR=on should only work if only RNA-Seq evidence is provided. (Not saying that the script correctly catches all other possibilities.)
