### ISSUE TITLE
Force BLAST instead of DIAMOND

### ISSUE THREAD

**Issue by Neato-Nick** [Gaius-Augustus/BRAKER#147]
Hi,

I have both DIAMOND and BLAST in my path, and since Braker prefers DIAMOND it tries to use that first. Unfortunately, diamond is failing with makedb.

Copy and pasted from errors/aa2nonred.stderr:

```
Error: CPU does not support POPCNT. Please compile the software from source.
ERROR in file /dfs/BPP/Grunwald_Lab/home/carleson/opt/Augustus/scripts/aa2nonred.pl at line 182
```

Is there a way to force Braker to use blastp from my path instead of diamond? Or maybe a way to implement error handling so that if diamond fails for any reason, Braker tries to use blastp instead?

**Comment by Neato-Nick** [comment]
Update - I ended up compiling diamond from source into a local directory like the error message suggested. I supply that to braker using --DIAMOND_PATH, the pipeline runs all the way through just fine.

If you don't have the capacity or don't think error handling the aligner is a good idea at all, I won't be offended if you close this issue.

**Comment by KatharinaHoff** [comment]
There are probably ways to handle this. But I currently don't have the capacity to fix it. I will leave the issue open.

**Comment by KatharinaHoff** [comment]
We are migrating to using DIAMOND, only. I will close this issue.
