### ISSUE TITLE
ERROR: in file /home/chens/anaconda3/envs/braker2/bin/./helpMod.pm at line 307

### ISSUE THREAD

**Issue by baizixiansheng** [Gaius-Augustus/BRAKER#149]
Hello, when I run the command `braker.pl --cores 24 --species=A --genome=/data/database/ZW.LG.fasta --bam=A.bam` which on conda, the errors as follow. I have no idea to solve it. Thank you very much for having a look
`ERROR: in file /home/chens/anaconda3/envs/braker2/bin/./helpMod.pm at line 307`
 `found neither /home/chens/anaconda3/envs/braker2/bin/fix_joingenes_gtf.pl nor /home/chens/anaconda3/envs/braker2/scripts/fix_joingenes_gtf.pl nor /home/chens/anaconda3/envs/braker2/scripts/fix_joingenes_gtf.pl nor /home/chens/anaconda3/envs/braker2/bin/fix_joingenes_gtf.pl!
Please Check the environment variables AUGUSTUS_CONFIG_PATH and command line options AUGUSTUS_BIN_PATH and AUGUSTUS_SCRIPTS_PATH or install AUGUSTUS, again!`

**Comment by baizixiansheng** [comment]
After I add an environment, there still report an error:
`# Thu Jan 16 18:17:25 2020: Logfile: /project/annotation/braker/stylo_new/braker.log!
ERROR in file /home/chens/anaconda3/envs/braker2-2.1.2/bin/braker.pl at line 5831
Failed to execute: /home/chens/anaconda3/envs/braker2-2.1.2/bin//etraining --species=stylo_new --AUGUSTUS_CONFIG_PATH=/home/chens/anaconda3/envs/braker2-2.1.2/config/ /project/annotation/braker/stylo_new/train.f.gb 1> /project/annotation/braker/stylo_new/gbFilterEtraining.stdout 2>/project/annotation/braker/stylo_new/errors/gbFilterEtraining.stderr`
And the /project/annotation/braker/stylo_new/errors/gbFilterEtraining.stderr file as follow:
`/home/chens/anaconda3/envs/braker2-2.1.2/bin//etraining: ERROR
	Input file not in genbank format.`
The braker command is `braker.pl --cores 30 --species=stylo_new --genome=/data/stylo_transcriptome/ZW.LG.fasta --bam=Stylo.bam`.

**Comment by KatharinaHoff** [comment]
Please git clone BRAKER and AUGUSTUS from github instead of using release code that is automatically downloaded for creating conda environment for BRAKER. Release code is often outdated.

If the error persists after that, please reopen the issue.

Katharina

**Comment by Artifice120** [comment]
I am having the exact same issue and error message but I checked and my AUGUSTUS is version 3.5.0

**Comment by Artifice120** [comment]
it only occurs when I try to add a species.
