### ISSUE TITLE
ERROR in randomSplit.pl line 47: LOCUS names in genbank file are not unique!

### ISSUE THREAD

**Issue by qslin** [Gaius-Augustus/BRAKER#15]
Hi, 
I'm trying to run BRAKER/2.10 using only proteins of short evolutionary distance. My script is : 
```
braker.pl \
 --cores=8 \
 --softmasking=1 \
 --genome=/home/CAM/qlin/CE10_Genome/versions/1.9.2/repeatMasker_20181201_soft/CE10g_v1.92.fa.masked \
 --prot_seq=/home/CAM/qlin/LF10_Genome/BRAKER2/t3/braker/Sp_12/augustus.hints.filter.fa \
 --prg=gth \
 --gth2traingenes \
 --trainFromGth 
```
The program failed with this error: 
`ERROR in randomSplit.pl line 47: LOCUS names in genbank file are not unique!`
And I found this error in the gbFilterEtraining.stderr file:
```
mRNA contains character m
GBProcessor::getGeneList(): GBProcessor::getJoin( ):  failed!!!
Encountered error after reading 1 annotations.
```
Could you help me solve this problem? Thank you so much!

**Comment by KatharinaHoff** [comment]
I assume the problem did not occur anymore, I will close this issue.

**Comment by xiekunwhy** [comment]
This problem persists.

braker: my $version = "2.1.6";
augustus: AUGUSTUS (3.4.0) is a gene prediction tool

I think many users were ignore this error since the pipeline ignore this error and work through.

Best,
Kun

**Comment by xiekunwhy** [comment]
I used braker to annotated 8 genomes, this error always there when I check optimize_augustus.stderr.
