### ISSUE TITLE
restarting a crashed run

### ISSUE THREAD

**Issue by MarkChristianHarrison** [Gaius-Augustus/BRAKER#151]
Hello,
I had an issue with the augustus script - fix_in_frame_stop_codon_genes.py - after the pipeline had been running for four days. I expect it to now work after reinstalling augustus from github. But I was wondering if it is possible to continue the pipeline from where it crashed, rather restarting completely.
Thanks,
Mark

**Comment by KatharinaHoff** [comment]
There are ways to use preliminary results of a previous BRAKER run. I am currently documenting them better, and documentation will be merged into master branch, soon.

**Comment by KatharinaHoff** [comment]
I have documented options for reusing partial results of a previous BRAKER run in release v2.1.5.

**Comment by lyy005** [comment]
Hi Katharina, 
I just wanted to follow up on this issue and see if there's any way for me to restart a crashed Braker run? 

Thank you! 

YY
