### ISSUE TITLE
Do bam files need to be sorted /indexed before input to BRAKER2?

### ISSUE THREAD

**Issue by krabapple** [Gaius-Augustus/BRAKER#153]
The BRAKER manual does not specify.  I'm using STAR as the aligner.  The Augustus protocol paper (Hoff and Stanke 2018) calls sorting optional (if using the STAR aligner).

**Comment by krabapple** [comment]
The BRAKER2 manual does not specify.

**Comment by KatharinaHoff** [comment]
It should be optional.

**Comment by krabapple** [comment]
Does that mean it sorts the input bam file when --UTR , --addUTR, or either, are used?

It also means that a file used in a --bam=  option never needs to be sorted before running the BRAKER command?

**Comment by KatharinaHoff** [comment]
It only sorts the file at a later stage. You need to provide sorted bam files to BRAKER because it will first carry out bam2hints for standard BRAKER1 run. I will close this issue.
