### ISSUE TITLE
prepare gtf from gff3 for Augustus

### ISSUE THREAD

**Issue by HegedusB** [Gaius-Augustus/BRAKER#155]
This is not an issue report. I just want to ask if it is possible to use another gene prediction set then what the genemark produce for the AUGUSTUS. I have a manually curated gene model set stored in a gff3 format file which I converted to gtf format (similar to what the genemark produce). After I ran the filterGenemark.pl script to filter out the best gene candidates for model building (based on the inton hints) I got 0 good gene models. I think the genemark gtf format is a little tricky and I could not reproduce it correctly. Can you give some advice? Thanks for any help.

**Comment by KatharinaHoff** [comment]
The filterGenemark.pl script will filter for those genes that have evidence from RNA-Seq or protein hints. Did you provide such complementary data?

**Comment by HegedusB** [comment]
Thanks for the quick replay.  I used bam2hints to get intron information from paired-end read alignment. The reads are coming from an RNA-seq experiment.

**Comment by KatharinaHoff** [comment]
If your manually curated model are in agreement with that evidence, and the script produces no "good genes", you likely have a small format bug in the input data.

**Comment by HegedusB** [comment]
Thanks! It is good to know the program can handle the  manually curated models. I will try to figure out where I made the mistake.

**Comment by KatharinaHoff** [comment]
This is not a problem with BRAKER. I will close the issue.
