### ISSUE TITLE
RNAseq alignments

### ISSUE THREAD

**Issue by KristinaGagalova** [Gaius-Augustus/BRAKER#156]
Hi,
 
I have a conceptual question about the BRAKER pipeline. I am both familiar with RNAseq alignment and genome annotation.

Several RNAseq aligners (STAR, HISAT2) recommend to use a bed file with the genes coordinated for a better alignment. The indexing in those regions are more fine-grained thus there is a higher chance to align split reads (reads aligning on 2 separate exons).
In this case we need to have annotated genes which we don't in the case of non-model organisms.
Can be this a circular problem in the case of the BRAKER pipeline? (we need good RNAseq alignments for good gene predictions, we need gene predictions for good RNAseq alignments)

Have you also tried to see if that impacts the BRAKER pipeline and what do you recommend for the RNAseq alignments?

Thank you in advance

**Comment by KatharinaHoff** [comment]
I have not experimented with this. I don’t expect to see major problems, though. 

The beneficial effect on splice site discovery might be small compared to overall runtime.

**Comment by KatharinaHoff** [comment]
Closing issue because it's not a BRAKER issue on its own.
