### ISSUE TITLE
Decreasing accuracy after optimization of AUGUSTUS

### ISSUE THREAD

**Issue by ConcettaDe4** [Gaius-Augustus/BRAKER#158]
Hi @KatharinaHoff ,

I have run BRAKER2 with RNA-seq data. I have noticed that after the optimization of AUGUSTUS with the default value of optimization rounds the accuracy prediction decreased. In particular, I have the following values: 

- The accuracy after initial training (no optimize_augustus.pl, no CRF) is 0.719533333333333
- The accuracy after training (after optimize_augustus.pl, no CRF) is 0.7166

In addition if I compare the specificity and sensitivity of AUGUSTUS prediction at gene level I have the following values:

- Initial training firsttest.stdout: Sensisitivity: 0.3 and Specificity: 0.219
- Second training secondtest.stdout : Sensisitivity: 0.293 and Specificity: 0.218 

I was wondering why the accuracy of AUGUSTUS training after optimization decreased.

Many thanks,

Concetta

**Comment by KatharinaHoff** [comment]
This is not expected behaviour. Difference is minor, though. 

Accuracy is overall strinkingly low, though. I probably wouldn't trust the gene models, much.
