### ISSUE TITLE
Overinflated number of single exon genes

### ISSUE THREAD

**Issue by david0rr** [Gaius-Augustus/BRAKER#159]
After running Braker2 with RNA-seq and prot.hints I have found my resulting Braker.gtf file has a much higher number of single exon genes than expected, especially when compared to closely related species from high quality annotations.

Do you have any ideas to what might be causing this?

Thanks

David

**Comment by V-JJ** [comment]
Hello!

Same here, did you found the reason behind this?

Thanks in advance,
