### ISSUE TITLE
braker2 and GeneMark-ES Suite version 4.48_3.60_lic

### ISSUE THREAD

**Issue by lfaino** [Gaius-Augustus/BRAKER#162]
Dear Developer,

do you know if there are compatibility problems between GeneMark-ES Suite version 4.48_3.60_lic and Braker2.1.4? 
I`m having few problems.

Cheers
Luigi

**Comment by lfaino** [comment]
here the error that i get:

#*********
# WARNING: The number of cores was set to 48, which is greater than 48. GeneMark is likely to die if you set such a high number of cores. Decreasing number of cores to 48. You might want to restart the process in order to use your resources, efficiently. Please be aware that a very large number of cores also may not be used, efficiently by optimize_augustus.pl during cross validation. braker.pl will automatically compute the number of cores that will effectively be used for optimizing AUGUSTUS parameter in such a way that each each bucket will contain at least 200 training genes. We usually use 8 cores for 8-fold cross validation.
#*********
# Mon Feb 10 12:56:05 2020: Log information is stored in file /data/braker/braker.log
# Mon Feb 10 13:05:53 2020: ERROR: in file /opt/LoReAn/third_party/software/BRAKER/scripts/braker.pl at line 6492
Training gene file in genbank format /data/braker/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.
# Mon Feb 10 13:05:53 2020: ERROR: in file /opt/LoReAn/third_party/software/BRAKER/scripts/braker.pl at line 6492
Training gene file in genbank format /data/braker/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.


i use:
braker.pl version 2.1.4
GeneMark-ES Suite version 4.48_3.60_lic
AUGUSTUS (3.3.3) is a gene prediction tool

cheers
Luigi

**Comment by lfaino** [comment]
apparently, this script is nor working 

`perl /opt/LoReAn/third_party/software/augustus/scripts/filterGenesIn_mRNAname.pl /data/braker/good_genes.lst /data/braker/train.gb`

**Comment by KatharinaHoff** [comment]
I made a new BRAKER release today that was developed and tested with the GeneMark version that you refer to. Please update BRAKER. Please also make sure that you clone AUGUSTUS from github to have latest AUGUSTUS scripts for BRAKER. Reopen the issue if your problem persists.

Katharina

**Comment by lfaino** [comment]
@KatharinaHoff is the latest release of augustus (tar.gz file) the same present at the github?

**Comment by KatharinaHoff** [comment]
No. git clone will download latest AUGUSTUS sources.
