### ISSUE TITLE
WARNING: ETPmode enabled but /scratch/evidence.gff does not exist!

### ISSUE THREAD

**Issue by A-J-F-Mackintosh** [Gaius-Augustus/BRAKER#165]
Hi all,

I am currently trying to annotate an insect genome assembly with braker2. I am using the most recent version (2.1.4.1) installed through conda.

I am currently generating poorer results than I would like. braker2 predicts ~18,000 genes that contain ~83% complete BUSCOs, when I would actually expect ~15,500 genes and a BUSCO score similar to that of the assembly (95%). The command I am submitting looks like this:

 `braker.pl --softmasking --verbosity=3 --workingdir=/scratch --cores 40 --gff3 --genome=my_species.contigs.softmasked.fasta --species=my_species_10RNAseq_transcripts_proteins --bam=ind1.bam,ind2.bam,ind3.bam,ind4.bam,ind5.bam,ind6.bam,ind7.bam,ind8.bam,ind9.bam,ind10.bam,transcripts.bam --prot_seq=proteins.fasta --prg=gth --gth2traingenes`

I have ten RNA-seq datasets (mapped with hisat2), a denovo transcriptome (mapped with gmap), and proteins from five species within the same family as my species.

While braker2 does finish and produces an annotation, it does give a warning:

`WARNING: ETPmode enabled but /scratch/evidence.gff does not exist!`

I have looked in the code and am having trouble seeing why the evidence.gff isn't produced. Is this a crucial step in braker? Could it explain why I am generating a somewhat poor annotation?

Best wishes,

Alex

**Comment by KatharinaHoff** [comment]
Hi Alex,
I am currently taking care of your issue. It's kind of fixed in the branch EPintrons. But I need to make some more changes prior merging back into master branch.
Katharina

**Comment by KatharinaHoff** [comment]
Hi Alex,

I made a new release 2.1.5 today that fixes your issue. 

Katharina

**Comment by A-J-F-Mackintosh** [comment]
Hi Katharina,

Many thanks for taking care of this.

Do you know whether the problem will have adversely affected my past braker runs? I am not sure how the evidence.gff is used and so don't know what the effect would have been.

Best wishes,

Alex

**Comment by KatharinaHoff** [comment]
I recommend letting the new BRAKER rerun ProtHint. I am not sure if the
pipeline will run smoothly otherwise (I changed things in usage of BRAKER).

Best,

Katharina
