### ISSUE TITLE
utrrnaseq error in reading merged.wig file

### ISSUE THREAD

**Issue by gitarunprasanna83** [Gaius-Augustus/BRAKER#166]
Hello,

I installed braker 2.1.4 using conda (bundled with Augustus 3.3.3). The installation seems to be fine and working. I ran it with `--UTR=on`. I am not sure, if the utrrnaseq is being compatible with wig output produced by bam2wig.py. For instance, 
it generated 6 gb of rnaseq2utr.err file which has the following lines:

> Error in wiggle file (line 3): Position in '2730           1' is not an integer! Row will be ignored!
> Error in wiggle file (line 4): Position in '2731           1' is not an integer! Row will be ignored!

and so on.. Is this a problem with reading delimiter by utrrnaseq ? Trying so hard to make UTR work !

Thanks in advance.

**Comment by KatharinaHoff** [comment]
I will not work on this because we are switching to a different approach for UTR prediction, soon. (Probably released middle of April, you'll see it in a development branch, earlier.)

Best,

Katharina
