### ISSUE TITLE
merge_transcript_sets.pl 

### ISSUE THREAD

**Issue by minhasbushra** [Gaius-Augustus/BRAKER#167]
I am getting an error for merge_transcript_sets.pl (merge_transcripts_multi_anchored.stderr) 

Use of uninitialized value $txid in hash element at line :

        push(@{$txid_to_elements{$txid}}, $line);

Any help would be appreciated.
Thanks

**Comment by KatharinaHoff** [comment]
Please provide more information about the context (e.g. call, format of input files, ...)

**Comment by minhasbushra** [comment]
Thanks for your reply, So I am running the test6 with the example data. My command is 

braker.pl --specie=test3 --cores 23 --genome=genome.fa --prot_seq=prot.fa --prg=gth --bam=RNAseq.bam --gth2traingenes --softmasking --workingdir=braker_output --BLAST_PATH=/projects//.........

In the error directory, I am getting:

**merge_transcripts_multi_anchored.stderr** filled with these lines
Use of uninitialized value $txid in hash element at /braker-2.1.3/scripts/merge_transcript_sets.pl line 70, <IN> line 1 (for all line 1 through 12198)

Line  70 **push(@{$txid_to_elements{$txid}}, $line);**

**merge_transcripts_single_anchored.stderr**
Processing file /Braker_test/braker_output/step2.gtf
Processing file /Braker_test/braker_output/GeneMark-ET/genemark.f.single_anchored.gtf

In the logfile everything looks ok till AUGUSTUS prediction complete, the problem is at 

**"Trying to create merged gene set from GeneMark-EX and AUGUSTUS predictions (braker.gtf/braker.utr.gtf)..."**

Also, there is another error startAlign.stdout in the error directory.

CmdString: /opt/genomethreader-1.7.1/bin/gth -genomic /braker_output/tmp_gth/genome2R.fa -protein /braker_output/tmp_gth/protFileFor_genome2R.fa/prot_addstop.fa -gff3out -skipalignmentout -paralogs -gcmincoverage 80 -prseedlength 20 -prminmatchlen 20 -prhdist 2 -o  /Braker_test/braker_output/align_gth/2R.gth.aln 2>/Braker_test/braker_output/align_gth/2R.gth.stderr

I appreciate your help!!
Thanks

**Comment by KatharinaHoff** [comment]
Oh dear. Now you went through all the trouble to document the problem, and I managed to make a new release, today. Can you please confirm whether your error persists with the latest code from github for AUGUSTUS and BRAKER? I am sorry...

**Comment by minhasbushra** [comment]
Oh no worries :). I am on it right now. I will get back if I came across anything .. 

Thanks again

**Comment by minhasbushra** [comment]
I updated everything. Still getting this ..... for line 1 through 12198

Processing file ../Braker_test/braker_output/augustus.hints.gtf
Use of uninitialized value $txid in hash element at /home/braker-2.1.3/scripts/merge_transcript_sets.pl line 70, <IN> line 1.
Use of uninitialized value $txid in hash element at /home/braker-2.1.3/scripts/merge_transcript_sets.pl line 70, <IN> line 2.
Use of uninitialized value $txid in hash element at /home/braker-2.1.3/scripts/merge_transcript_sets.pl line 70, <IN> line 3.
Use of uninitialized value $txid in hash element at /home/braker-2.1.3/scripts/merge_transcript_sets.pl line 70, <IN> line 4.
Use of uninitialized value $txid in hash element at /home/braker-2.1.3/scripts/merge_transcript_sets.pl line 70, <IN> line 5.
Use of uninitialized value $txid in hash element at /home/braker-2.1.3/scripts/merge_transcript_sets.pl line 70, <IN> line 6.

**Comment by KatharinaHoff** [comment]
Please update marge_transcript_sets.pl from github (e.g. git clone/git pull). I think it's fixed with commit https://github.com/Gaius-Augustus/BRAKER/commit/80bfd8fbec36a6a279251cac7eca502ef2b85f36 .
It made an error when designing the script. Actually, the effect of this error on the final output was minor, the transcript sets were correctly merged. Only gene lines were missing.

The startAlign.stdout should not be in errors directory. I will look into this. It's not an error containing file.

**Comment by KatharinaHoff** [comment]
startAlign.stdout will now not go to error directory and will be deleted after the run (https://github.com/Gaius-Augustus/BRAKER/commit/cf395086bfab97c4f263ce90dc2b703cd2b0baa8 )

Hope that solves all your problems.

Katharina
