### ISSUE TITLE
Gene prediction with no coverage in bam file

### ISSUE THREAD

**Issue by minhasbushra** [Gaius-Augustus/BRAKER#173]
Hi,

I am having a problem with a few genes. For example, in my augustus.hints.gtf, a gene looks like

**contig_10107_pilon      AUGUSTUS        gene    1       2058    0.92    +       .       g1577
contig_10107_pilon      AUGUSTUS        transcript      1       2058    0.92    +       .       g1577.t1
contig_10107_pilon      AUGUSTUS        CDS     1       2058    0.92    +       0       transcript_id "g1577.t1"; gene_id "g1577";
contig_10107_pilon      AUGUSTUS        exon    1       2058    .       +       .       transcript_id "g1577.t1"; gene_id "g1577";
contig_10107_pilon      AUGUSTUS        stop_codon      2056    2058    .       +       0       transcript_id "g1577.t1"; gene_id "g1577";**

When I looked at my genome, the gtf file, and the bam file on IGV, I don't see any hints for the gene predicted. 

I am not sure what's going on. Any suggestions? I am attaching the IGV  screenshot too. 

<img width="919" alt="Screen Shot 2020-02-24 at 3 42 26 PM" src="https://user-images.githubusercontent.com/40889342/75278848-3c9da580-57d0-11ea-9022-e80e2a89bdb8.png">
 
The thing is that the predicted gene is just AC rich repeat. I am using softmasked genome.  
Thanks

**Comment by minhasbushra** [comment]
Also, since I updated all the scripts from github, I noticed a lot of files are not being produced that were produced previously. 

 This is how my braker output directory looks like

**GeneMark-ET        augustus.hints.codingseq  bam_header.map  braker.log  genemark_hintsfile.gff  hintsfile.gff  what-to-cite.txt   augustus.hints.aa  augustus.hints.gtf        braker.gtf      errors      genome_header.map       species**

**Comment by KatharinaHoff** [comment]
AUGUSTUS predicts genes ab initio, i.e. with statistical model only, and with evidence (for these you find evidence in browser). It is expected behaviour of both GeneMark-EX and AUGUSTUS to predict a certain proportion of genes without evidence.
Katharina
