### ISSUE TITLE
Annotation projection

### ISSUE THREAD

**Issue by psur9757** [Gaius-Augustus/BRAKER#174]
I have an annotated genome for a microbial isolate (the reference). We recently sequenced related isolates and I was wondering if it is possible to project the annotation from our reference to newly sequenced isolates using BRAKER? I don't want to predict genes but transfer previous annotations to new genome coordinates. Thank you.

**Comment by KatharinaHoff** [comment]
Unless the microbial isolate is eukaryotic and has a marjority of genes with introns, BRAKER is the wrong approach for annotating the microbial genome...
