### ISSUE TITLE
twoBitInfo and faToTwoBit not installed

### ISSUE THREAD

**Issue by schellt** [Gaius-Augustus/BRAKER#178]
Dear @KatharinaHoff ,
after configuring BRAKER version 2.1.5 according installation instructions from README there are still these warning messages:

`twoBitInfo not installed. It is available at http://hgdownload.soe.ucsc.edu/admin/exe and should be added to your $PATH. bamToWig.py will automatically download this tool to the working directory but permanent global installation is recommended.`

`faToTwoBit not installed. It is available at http://hgdownload.soe.ucsc.edu/admin/exe and should be added to your $PATH. bamToWig.py will automatically download this tool to the working directory but permanent global installation is recommended.`

I would be nice if you could add twoBitInfo and faToTwoBit to the dependencies in the README.
Thank you very much and best regards,
Tilman

**Comment by KatharinaHoff** [comment]
Hi Tilman,
thanks for noticing. I added it to the README.md https://github.com/Gaius-Augustus/BRAKER/commit/bf7c54105cb12841161b7d79af9dcfd9af214e10
Katharina
