### ISSUE TITLE
Encountering problem with braker run

### ISSUE THREAD

**Issue by sagnikbanerjee15** [Gaius-Augustus/BRAKER#179]
Hello,

I have installed braker along with all its dependencies as suggested. I am running braker with a small portion of the arabidopsis genome along with the corresponding bam file. I keep running into the following error:

(in cleanup) 	(in cleanup)  at /home/sagnik/anaconda3/lib/site_perl/5.26.2/Object/InsideOut.pm line 1953 during global destruction.
	(in cleanup) 	(in cleanup)  at /home/sagnik/anaconda3/lib/site_perl/5.26.2/Object/InsideOut.pm line 1953 during global destruction.

ERROR in file ./braker.pl at line 6393
Failed to execute: perl /work/LAS/rpwise-lab/sagnik/finder/lib/gm_et_linux_64/gmes_petap.pl --verbose --sequence=/work/LAS/rpwise-lab/sagnik/finder/lib/BRAKER/scripts/braker/genome.fa --ET=/work/LAS/rpwise-lab/sagnik/finder/lib/BRAKER/scripts/braker/genemark_hintsfile.gff --et_score 10 --max_intergenic 50000 --cores=30 --gc_donor 0.001 1>/work/LAS/rpwise-lab/sagnik/finder/lib/BRAKER/scripts/braker/GeneMark-ET.stdout 2>/work/LAS/rpwise-lab/sagnik/finder/lib/BRAKER/scripts/braker/errors/GeneMark-ET.stderr
Failed to execute: perl /work/LAS/rpwise-lab/sagnik/finder/lib/gm_et_linux_64/gmes_petap.pl --verbose --sequence=/work/LAS/rpwise-lab/sagnik/finder/lib/BRAKER/scripts/braker/genome.fa --ET=/work/LAS/rpwise-lab/sagnik/finder/lib/BRAKER/scripts/braker/genemark_hintsfile.gff --et_score 10 --max_intergenic 50000 --cores=30 --gc_donor 0.001 1>/work/LAS/rpwise-lab/sagnik/finder/lib/BRAKER/scripts/braker/GeneMark-ET.stdout 2>/work/LAS/rpwise-lab/sagnik/finder/lib/BRAKER/scripts/braker/errors/GeneMark-ET.stderr
The most common problem is an expired or not present file ~/.gm_key!

I have the latest key.
Could you please help?

Thank you.

**Comment by sagnikbanerjee15** [comment]
I have resolved the above error but now I am getting a different error. I am running BRAKER on S.cerevisiae and I got stuck on an error. Here is the error.

# Wed Mar 11 18:33:45 2020: Log information is stored in file /work/LAS/rpwise-lab/sagnik/FINDER1_manuscript/data/finder1_runs/Saccharomyces_cerevisiae/braker/braker.log
#*********
# WARNING: Number of reliable training genes is low (247). Recommended are at least 600 genes
#*********
Error in file /work/LAS/rpwise-lab/sagnik/FINDER1_manuscript/data/finder1_runs/Saccharomyces_cerevisiae/braker/Augustus/scripts/bamToWig.py at line 173: Return code of subprocess was 127['/work/LAS/rpwise-lab/sagnik/softwares/anaconda3/envs/finder/bin/faToTwoBit', '/work/LAS/rpwise-lab/sagnik/FINDER1_manuscript/data/finder1_runs/Saccharomyces_cerevisiae/braker/genome.fa', 'twoBitFile_apwabazjqf']
ERROR in file /work/LAS/rpwise-lab/sagnik/finder/lib/BRAKER/scripts/braker.pl at line 10709
Failed to execute: /work/LAS/rpwise-lab/sagnik/softwares/anaconda3/envs/finder/bin/python3 /work/LAS/rpwise-lab/sagnik/FINDER1_manuscript/data/finder1_runs/Saccharomyces_cerevisiae/braker/Augustus/scripts/bamToWig.py -b /work/LAS/rpwise-lab/sagnik/FINDER1_manuscript/data/finder1_runs/Saccharomyces_cerevisiae/braker/merged.s.bam -g /work/LAS/rpwise-lab/sagnik/FINDER1_manuscript/data/finder1_runs/Saccharomyces_cerevisiae/braker/genome.fa -o /work/LAS/rpwise-lab/sagnik/FINDER1_manuscript/data/finder1_runs/Saccharomyces_cerevisiae/braker/merged.wig 2> /work/LAS/rpwise-lab/sagnik/FINDER1_manuscript/data/finder1_runs/Saccharomyces_cerevisiae/braker/errors/bamToWig.err

I running BRAKER with --overwrite --gff3 --UTR=on --fungus --softmasking --cores=30 --genome=PATH_TO_GENOME.

Could you please take a look at this?

Thank you.

**Comment by KatharinaHoff** [comment]
Please run without --UTR=on . I will not fix this since we are soon migrating to another way of generating UTR examples, anyway.

Katharina

**Comment by sagnikbanerjee15** [comment]
All right. Thanks.

**Comment by iar28** [comment]
Hello, 
I'm getting a similar issue. I do have a new gm_key in ~/.gm_key. I hope you could help me sort this out. Cheers!

braker.pl --species=Dglo --cores=8 --genome=GCA_003255025.1_ASM325502v1_genomic_simpleheader.fna --softmasking --bam=SRR6384561.sam.bam,SRR6384565.sam.bam,SRR6384567.sam.bam,SRR6384562.sam.bam,SRR6384566.sam.bam,SRR6384568.sam.bam --GENEMARK_PATH=/home/illorens/bin/gmes_linux_64
# Fri Sep 18 13:37:54 2020: Log information is stored in file /projects/ensa/plants/D_glom/bam/braker/braker.log
ERROR in file /home/illorens/miniconda3/envs/testenv/bin/braker.pl at line 6372
Failed to execute: perl /home/illorens/bin/gmes_linux_64/gmes_petap.pl --verbose --sequence=/projects/ensa/plants/D_glom/bam/braker/genome.fa --ET=/projects/ensa/plants/D_glom/bam/braker/genemark_hintsfile.gff --et_score 10 --max_intergenic 50000 --cores=8 --gc_donor 0.001 --soft_mask 1000 1>/projects/ensa/plants/D_glom/bam/braker/GeneMark-ET.stdout 2>/projects/ensa/plants/D_glom/bam/braker/errors/GeneMark-ET.stderr
Failed to execute: perl /home/illorens/bin/gmes_linux_64/gmes_petap.pl --verbose --sequence=/projects/ensa/plants/D_glom/bam/braker/genome.fa --ET=/projects/ensa/plants/D_glom/bam/braker/genemark_hintsfile.gff --et_score 10 --max_intergenic 50000 --cores=8 --gc_donor 0.001 --soft_mask 1000 1>/projects/ensa/plants/D_glom/bam/braker/GeneMark-ET.stdout 2>/projects/ensa/plants/D_glom/bam/braker/errors/GeneMark-ET.stderr
The most common problem is an expired or not present file ~/.gm_key!


cat errors/GeneMark-ET.stderr
Can't locate YAML.pm in @INC (you may need to install the YAML module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/illorens/bin/gmes_linux_64/parse_by_introns.pl line 21.
BEGIN failed--compilation aborted at /home/illorens/bin/gmes_linux_64/parse_by_introns.pl line 21.
        (in cleanup)    (in cleanup)  at /home/illorens/miniconda3/envs/testenv/lib/site_perl/5.26.2/Object/InsideOut.pm line 1953 during global destruction.

cat GeneMark-ET.stdout
check before run
create directories
commit input data
data report
commit training data
training data report
prepare initial model
get GC of sequence
GC 34
build initial ET model
error on call: /home/illorens/bin/gmes_linux_64/parse_by_introns.pl  --section ET_ini  --cfg  /projects/ensa/plants/D_glom/bam/braker/GeneMark-ET/run.cfg  --parse_dir /projects/ensa/plants/D_glom/bam/braker/GeneMark-ET/run/ET_ini

**Comment by tomasbruna** [comment]
Hello,

the line `Can't locate YAML.pm in @inc` explains the error. Installing the [YAML](https://metacpan.org/pod/YAML) Perl module should fix the problem.

The list of required Perl modules as well as the installation instruction for them can be found here https://github.com/Gaius-Augustus/BRAKER#perl-pipeline-dependencies.

You can check whether all Perl modules required by GeneMark are installed by running the `check_install.bash` script located in the GeneMark directory.

Best,
Tomas

**Comment by iar28** [comment]
Thanks Tomas.

Indeed, it was a YAML.pm error. I am running braker on an HPC so eventhough the perl modules were installed in my usr/bin/env I had to specify the location of YAML to run GeneMark. 
For this I used the script 
./change_path_in_perl_scripts.pl from GeneMark. 

Thanks a lot for your help
