### ISSUE TITLE
UTRs annotations

### ISSUE THREAD

**Issue by cascoamarillo** [Gaius-Augustus/BRAKER#18]
Hi,
I have been running braker with RNAseq data (bam files) and UTR=on; I wanted to add UTRs annotations into my genes. After getting all the output considered (gtf and gff files, etc), I encountered this scenario on some (many) genes: the presence of more than one annotated 5'UTR and/or 3'UTR within the gene and the same isoform. See below for a simplified example:

`Contig1001	AUGUSTUS	gene	35608	37394	0.08	-	.	g8717
Contig1001	AUGUSTUS	transcript	35608	37394	0.08	-	.	g8717.t1
Contig1001	AUGUSTUS	tts	35608	35608	.	-	.	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	3'-UTR	35608	35986	0.46	-	.	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	exon	35608	36139	.	-	.	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	stop_codon	35987	35989	.	-	0	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	CDS	35987	36139	1	-	0	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	intron	36140	36198	1	-	.	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	CDS	36199	36313	1	-	1	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	exon	36199	36313	.	-	.	transcript_id "g8717.t1"; gene_id "g8717";
...
Contig1001	AUGUSTUS	intron	36949	37004	1	-	.	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	CDS	37005	37222	1	-	0	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	exon	37005	37227	.	-	.	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	start_codon	37220	37222	.	-	0	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	5'-UTR	37223	37227	1	-	.	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	5'-UTR	37281	37394	0.25	-	.	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	exon	37281	37394	.	-	.	transcript_id "g8717.t1"; gene_id "g8717";
Contig1001	AUGUSTUS	tss	37394	37394	.	-	.	transcript_id "g8717.t1"; gene_id "g8717";`

When I look into the RNAseq profile (IGV) I understand more or less why it's annotated this way: lack of RNAseq coverage that would link both initially separated 5'UTRs (or 3'UTRs). 

But my question is; I haven't seen this in other genome annotation files; is this any common in other braker annotations with UTR=on (this are two Illumina 150PE lanes which give ~30x coverage)? Should I merge/connect the double UTRs as one for further analysis?

Thank you

**Comment by KatharinaHoff** [comment]
I don't really see the problem: yes, there are two 5'-UTR features for
transcript g8717.t1, but they are part of the same UTR. They are only
separated by an intron. On its own, this is not a problem.
Best,
Katharina
