### ISSUE TITLE
failed to open file top_chains.gff!

### ISSUE THREAD

**Issue by schellt** [Gaius-Augustus/BRAKER#180]
Dear @KatharinaHoff,
running BRAKER release version 2.1.5 with this command line:
`braker.pl --genome=<genome.fa> --bam=<rna.bam> 
--prot_seq=<prot.fa> --softmasking --etpmode --gff3 --cores 48 --workingdir=<wd> --UTR=on --prg=ph --verbosity=4`
unfortunately produced the following error:
```
[Fri Feb 28 18:38:09 2020] ProtHint finished.
ERROR in file braker.pl at line 5010
failed to open file top_chains.gff!
```
First I assumed that my `prot.fa` was the issue. BRKER stated the first time that:
```
# WARNING: Detected | in fasta header of file prot.fa. This may later on cause problems! The pipeline will create a new file without spaces or "|" characters and a genome_header.map file to look up the old and new headers. This message will be suppressed from now on!
#*********
# Fri Feb 28 09:43:47 2020: Assuming that this is not a DNA fasta file because other characters than A, T, G, C, N, a, t, g, c, n were contained. If this is supposed to be a DNA fasta file, check the content of your file! If this is supposed to be a protein fasta file, please ignore this message!
#*********
 WARNING: empty line was removed! This warning will be supressed from now on!
#*********
# Fri Feb 28 09:43:54 2020: Assuming that this is not a protein fasta file because other characters than AaRrNnDdCcEeQqGgHhIiLlKkMmFfPpSsTtWwYyVvBbZzJjXx were contained. If this is supposed to be DNA fasta file, please ignore this message.
```
So I changed the headers with Augustus' `simplifyFastaHeaders.pl`, removed trailing asterisks and translated amino acids O and U to X. As far as I saw BRAKER executes `simplifyFastaHeaders.pl` or something similar. I could not find any restrictions for `--prot_seq` (except the above warning message) in the README.
After starting the same BRAKER command (of cause with the changed `prot.fa`) in a clean working directory the same error was produced.

Afterwards I checked the README of BRAKER again and saw the statement "--UTR=on is currently not compatible with bamToWig.py as released in AUGUSTUS 3.3.3". Since I run BRAKER with the 3.3.3 release of Augustus I now omitted the `--UTR` option. As far as I understood from this statement: "Please use the latest version of AUGUSTUS", the release of Augustus was tested.
The last run I conducted was now like this:
`braker.pl --genome=<genome.fa> --bam=<rna.bam> 
--prot_seq=<prot.fa> --softmasking --etpmode --gff3 --cores 48 --workingdir=<wd> --prg=ph --verbosity=4`, where `prot.fa` is the original file containing "O", "U" and "*".
In the end the same error occurred.

In all runs the STDERR files (`find_python3_biopython.err`, `find_python3_re.err`, `GeneMark-ES.stderr`, `new_species.stderr`) in the errors directory are empty.

I think I used the dependencies in their supported versions:
```
augustus/3.3.3
bamtools/2.5.1
diamond/0.9.24
genemark/4.48_3.60_lic
ncbi-blast/2.2.31
perl/5.30.0
prothint/2.2.0
python3/3.7.4
samtools/1.7
```

The only errors I found were `error: Alignment is missing after header` and two/three `Broken pipe`/`Segmentation fault` from ProtHint in all three runs. Running ProtHint with its included test data didn't produce these errors. I am not sure if this is the root of the BRAKER error but obviously it crashes after (successfully?) running ProtHint.

After briefly checking the braker.pl code and asking google, I am still not sure which command or tool should produce `top_chains.gff`.

I attached the `braker.log` file as well as the STDERR of the third BRAKER run (without `--UTR`):
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/4274617/braker.log)
[braker.stderr.log](https://github.com/Gaius-Augustus/BRAKER/files/4274618/braker.stderr.log)

I would be glad, if you could help.
Thank you very much.
Tilman

**Comment by KatharinaHoff** [comment]
This sounds like ProtHint is not in the latest version. First versions of ProtHint would not generate top_chains.gff, it's a rather recently added feature.

**Comment by schellt** [comment]
Dear Katharina,
Unfortunately your answer is not displayed here.
"This sounds like ProtHint is not in the latest version. First versions of ProtHint would not generate top_chains.gff, it's a rather recently added feature."

Thank you very much for the clarification.
Indeed I used release version 2.2.0 of ProtHint, which is not the latest but the recommended one in the README.
When I use ProtHint's release version 2.3.0 `top_chains.gff` is produced and BRAKER continues to run.

Unfortunately BRAKER crashed shortly afterwards while `log_reg_prothints.pl`. The good news is that the error was because `Math::Utils` was not installed.

It would suggest to update the README:
- change supported ProtHint version from 2.2.0 to 2.3.0
- add `Math::Utils` to "Perl pipeline dependencies" in the README

**Comment by KatharinaHoff** [comment]
Thanks for telling me that I forgot to add it. It's now in. https://github.com/Gaius-Augustus/BRAKER/commit/8eac5e87214681b96dccc574152b368e9e41e43d
