### ISSUE TITLE
PBS job failing to limit ncpus

### ISSUE THREAD

**Issue by lucasrocmoreira** [Gaius-Augustus/BRAKER#183]
Hello,

I am attempting to run braker on a HPC cluster with a PBS system. I am setting up my run to 8 cores with the '--cores' argument. However, my job is being constantly killed because braker is overshooting that number by a lot.

This is my command:
`/home/lmoreira/programs/BRAKER/scripts/braker.pl --genome=pseudochromosomes-subset_sorted.fasta --prot_seq=bird_proteins.fasta --epmode --softmasking --ALIGNMENT_TOOL_PATH=/home/lmoreira/programs/ProtHint/bin --cores=4`

Is there anything I'm missing? Do you have any advice/idea of what might be happening?

Thanks a lot.

**Comment by KatharinaHoff** [comment]
Are you using the latest version of BRAKER? I am asking because I recently fixed that problem (at least I that I did). Please git clone BRAKER....

**Comment by lucasrocmoreira** [comment]
It is working now with the most recent version.
Thanks!
