### ISSUE TITLE
Issue during Alignment Processing

### ISSUE THREAD

**Issue by lucasrocmoreira** [Gaius-Augustus/BRAKER#184]
Hi,

I am running annotation for a bird genome using the epmode:
`braker.pl --cores 4 --genome=pseudochromosomes-subset_sorted.fasta \
--prot_seq=bird_proteins.fasta --epmode --softmasking --ALIGNMENT_TOOL_PATH=/home/lmoreira/programs/ProtHint/bin`

I have encountered an error after alignment which I couldn't find a solution for:
`[Mon Mar  9 14:31:02 2020] Alignment of pairs finished
[Mon Mar  9 14:31:02 2020] Translating coordinates from local pair level to contig level
[Mon Mar  9 14:31:55 2020] Finished spliced alignment
[Mon Mar  9 14:31:59 2020] Processing the output
[Mon Mar  9 14:34:20 2020] error: ProtHint exited due to an error in command: grep topProt=TRUE Spaln/spaln.gff > topProteins.gff
ERROR in file /home/lmoreira/programs/BRAKER/scripts/braker.pl at line 5010
Failed to execute /home/lmoreira/programs/ProtHint/bin/prothint.py --threads=4 --geneMarkGtf /nas1/lmoreira/BRAKER/braker/GeneMark-ES/genemark.gtf 
nas1/lmoreira/BRAKER/braker/genome.fa /nas1/lmoreira/BRAKER/braker/proteins.fa`

I checked the Spaln/spaln.gff file and there are no matches for 'topProt=TRUE', so topProteins.gff is empty.

Do you know what might be happening?

Thanks

**Comment by tomasbruna** [comment]
Hello,

could you share couple lines from `spaln/spaln.gff` and `diamond/diamond.out` files? That could help diagnose what went wrong here.

Tomas

**Comment by lucasrocmoreira** [comment]
Here is spaln/spaln.gff:

> 1	Spaln_scorer	CDS	124744775	124744837	.	+	1	prot=A0A093GJF7_DRYPU; exon_id=13; eScore=28; seed_gene_id=95854_g;
1	Spaln_scorer	CDS	124745287	124745717	.	+	2	prot=A0A093GJF7_DRYPU; exon_id=16; eScore=551; seed_gene_id=95854_g;
1	Spaln_scorer	CDS	124744775	124744837	.	+	1	prot=A0A093GLT3_DRYPU; exon_id=13; eScore=28; seed_gene_id=95854_g;
1	Spaln_scorer	CDS	124745287	124745717	.	+	2	prot=A0A093GLT3_DRYPU; exon_id=16; eScore=551; seed_gene_id=95854_g;
1	Spaln_scorer	CDS	124744775	124744837	.	+	1	prot=A0A093GCF0_DRYPU; exon_id=13; eScore=28; seed_gene_id=95854_g;
1	Spaln_scorer	CDS	124745287	124745717	.	+	2	prot=A0A093GCF0_DRYPU; exon_id=16; eScore=551; seed_gene_id=95854_g;
1	Spaln_scorer	CDS	124744775	124744837	.	+	1	prot=A0A093GVF0_DRYPU; exon_id=13; eScore=28; seed_gene_id=95854_g;
1	Spaln_scorer	CDS	124745287	124745717	.	+	2	prot=A0A093GVF0_DRYPU; exon_id=16; eScore=547; seed_gene_id=95854_g;
1	Spaln_scorer	CDS	124744775	124744837	.	+	1	prot=A0A093GQS8_DRYPU; exon_id=13; eScore=28; seed_gene_id=95854_g;
1	Spaln_scorer	CDS	124745287	124745717	.	+	2	prot=A0A093GQS8_DRYPU; exon_id=16; eScore=545; seed_gene_id=95854_g;

Here is diamond.out

> 95854_g	tr|A0A3Q2TYG0|A0A3Q2TYG0_CHICK
95854_g	tr|A0A093GJF7|A0A093GJF7_DRYPU
95854_g	tr|A0A093GLT3|A0A093GLT3_DRYPU
95854_g	tr|A0A093GCF0|A0A093GCF0_DRYPU
95854_g	tr|A0A093GVF0|A0A093GVF0_DRYPU
95854_g	tr|A0A093GQS8|A0A093GQS8_DRYPU
95854_g	tr|A0A093FV53|A0A093FV53_DRYPU
95854_g	tr|A0A093GEK2|A0A093GEK2_DRYPU
95854_g	tr|A0A093GKU6|A0A093GKU6_DRYPU
95854_g	tr|A0A093GW79|A0A093GW79_DRYPU

**Comment by tomasbruna** [comment]
Hi,

thanks! The problem is the pipe (`|`) character in the protein fasta headers. Somewhere along the pipeline, the pipe causes issues and leads to a mismatch in protein IDds.

We never tested ProtHint with proteins with a pipe character in the fasta header -- so thanks for catching this problem! I will open an issue in ProtHint's GitHub and will fix this problem soon. 

In the meantime, please replace all the `|` characters with an underscore (`_`), that should solve the issue.

Best,
Tomas

**Comment by lucasrocmoreira** [comment]
Thanks. I'll try that and report here soon.

**Comment by lucasrocmoreira** [comment]
I removed all special characters from the headers and it's working fine now. Thanks
