### ISSUE TITLE
Braker ETP mode - problem in ProtHint

### ISSUE THREAD

**Issue by minhasbushra** [Gaius-Augustus/BRAKER#185]
In the braker log while  Calling prothint.py...
 Fri Mar 13 12:35:21 2020: starting prothint.py
/projects/...../ProtHint/bin/prothint.py --threads=27 --geneMarkGtf /projects/...../output/GeneMark-ES/genemark.gtf /projects/...../output/genome.fa /projects/...../output/proteins.fa

I am getting these errors 

[Fri Mar 13 12:51:38 2020] DIAMOND finished
[Fri Mar 13 12:51:38 2020] Preparing pairs for alignments
[Fri Mar 13 12:54:24 2020] Preparation of pairs finished
[Fri Mar 13 12:54:25 2020] Starting spliced alignment with spaln
[Fri Mar 13 12:54:25 2020] Loading alignment pairs into memory
[Fri Mar 13 12:55:36 2020] Pairs loaded. Number of pairs to align: 997208
[Fri Mar 13 12:55:36 2020] Starting the alignments
[Fri Mar 13 12:55:36 2020] 0/997208 (0.0%) pairs aligned
**error: Could not read dna alignment start position
error: Could not read dna alignment start position
error: Could not read dna alignment start position
error: Could not read dna alignment start position
[Fri Mar 13 12:56:17 2020] 998/997208 (0.1%) pairs aligned**

Any idea whats going on? I ran the example test3 and it worked perfectly fine without any errors or warnings 

Thanks 
Bushra

**Comment by tomasbruna** [comment]
Hi Bushra,

does ProtHint crash or does it continue with couple of these errors in the log?

I have observed very rare differences in the output of Spaln before, depending on a hardware. Sometimes, the resulting difference affects formatting of the output file and it cannot be parsed --resulting in this error. However, if it happens only for some alignments, the error can be safely ignored. In your case, it seems that it affected 4 out of the first 998 alignments (0.4%), which is unusually high, but the overall result should still be relatively unaffected.

Let me know how many more errors you are seeing in the log. If there is a lot, this might be a different issue than the one I just described.

In any case, I will change the message from "error" to a "warning" and add some more description. Thanks for this suggestion.

Best,
Tomas

**Comment by minhasbushra** [comment]
Hi Tomas, 

Thanks for your reply. ProtHint didn't crashed, but my log file is full of these errors. I just pasted 4 error messages, but there are a lot more. ~ 20   **error: Could not read DNA alignment start position** lines for every point increase on the percentage of pairs aligned. e.g between 

[Fri Mar 13 14:21:17 2020] 127643/997208 (12.8%) pairs aligned 
and [Fri Mar 13 14:21:59 2020] 128640/997208 (12.9%) pairs aligned

there are ~10 error lines. 

The braker output looks fine though. 

Thanks
Bushra

**Comment by tomasbruna** [comment]
Hi Bushra,

glad to hear the BRAKER run looks good! 

With ~20 errors per every point increase, the problems affect 0.2% of all the alignments -- so it does not create any problems for the overall ProtHint or BRAKER result.

But I agree with you that this behavior is not optimal, I will try to pinpoint the cause of this problem in the ProtHint code.

Best,
Tomas
