### ISSUE TITLE
Issue running second iteration of ProtHint

### ISSUE THREAD

**Issue by lucasrocmoreira** [Gaius-Augustus/BRAKER#186]
Hi,

I encountered an error at the beginning of the second iteration of ProtHint (after Augustus training). This is the log file:

`# Sat Mar 14 13:19:01 2020: Running ProtHint again with additional seeds from augustus.hints.gtf to produce more hints from protein sequence file (this may take a couple of hours)...`
`# Sat Mar 14 13:19:01 2020: Calling prothint.py...`
`# Sat Mar 14 13:19:01 2020: starting prothint.py`
`/home/lmoreira/programs/ProtHint/bin/prothint.py --threads=8 --geneSeeds /nas1/lmoreira/BRAKER/braker/augustus.hints_iter1.gtf --prevGeneSeeds /nas1/lmoreira/BRAKER/braker/GeneMark-ES/genemark.gtf --prevSpalnGff /nas1/lmoreira/BRAKER/braker/Spaln/spaln_iter1.gff /nas1/lmoreira/BRAKER/braker/genome.fa /nas1/lmoreira/BRAKER/braker/proteins.fa`

I get this error:
```
usage: prothint.py [-h] [--workdir WORKDIR] [--geneMarkGtf GENEMARKGTF]
                   [--diamondPairs DIAMONDPAIRS]
                   [--maxProteinsPerSeed MAXPROTEINSPERSEED] [--evalue EVALUE]
                   [--minExonScore MINEXONSCORE] [--cleanup] [--pbs]
                   [--threads THREADS] [--version] [--ProSplign]
                   [--maxSpalnCoverage MAXSPALNCOVERAGE]
                   [--ensureDiamondPairs ENSUREDIAMONDPAIRS]
                   genome.fasta proteins.fasta
```
`prothint.py: error: unrecognized arguments: --geneSeeds --prevGeneSeeds --prevSpalnGff /nas1/lmoreira/BRAKER/braker/Spaln/spaln_iter1.gff /nas1/lmoreira/BRAKER/braker/genome.fa /nas1/lmoreira/BRAKER/braker/proteins.fa`
`ERROR in file /home/lmoreira/programs/BRAKER/scripts/braker.pl at line 5178`
`Failed to execute /home/lmoreira/programs/ProtHint/bin/prothint.py --threads=8 --geneSeeds /nas1/lmoreira/BRAKER/braker/augustus.hints_iter1.gtf --prevGeneSeeds /nas1/lmoreira/BRAKER/braker/GeneMark-ES/genemark.gtf --prevSpalnGff /nas1/lmoreira/BRAKER/braker/Spaln/spaln_iter1.gff /nas1/lmoreira/BRAKER/braker/genome.fa /nas1/lmoreira/BRAKER/braker/proteins.fa!`

It seems that prothint.py is not understanding some of the arguments. Any idea of what might be happening?

**Comment by tomasbruna** [comment]
Hi Lucas,

the second iteration was just added to BRAKER2 -- only the latest version of ProtHint supports the second iteration. Please clone the latest ProtHint from `https://github.com/gatech-genemark/ProtHint` to get the functionality.

Even with this error, the results from the first iteration of BRAKER should already be available to you.

I will create a ProtHint release today and update BRAKER's requirements to point to it. 

Thanks for reporting all these issues!

Tomas
