### ISSUE TITLE
Problem running BRAKER in etpmode at filterGenesIn_mRNAname.pl

### ISSUE THREAD

**Issue by gabelow** [Gaius-Augustus/BRAKER#190]
Hi Katherine,

I've been trying to run BRAKER2 in ETP mode with a RepeatModeler/RepeatMasker-masked genome, STAR-aligned RNA-seq bam file, and the Aves section of OrthoDB (which I built by querying the OrthoDB API for all orthologs under the Aves clade). 

After investigating, I think the run works correctly when processing the RNA and protein hints as far as I can tell, producing 40593 genes in train.gb (although there seems to be a very low good gene rate calculated). However, when it has to run filterGenesIn_mRNAname.pl, it seems to output 0 genes. I manually cross-checked whether entries in train.gb and good_genes.lst matched and there doesn't seem to be a problem for the few examples that I tested.

I've attached my run log, braker.log, and filterGenemark.stdout files. Any help or advice you could provide is greatly appreciated! I'm also happy to provide any other files you might need to check this out.

Thank you in advance!
Gabriel

[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/4364725/braker.log)
[braker_VIC030_NPI_rnaproteinsodb_scratch.log](https://github.com/Gaius-Augustus/BRAKER/files/4364726/braker_VIC030_NPI_rnaproteinsodb_scratch.log)
[filterGenemark.stdout.txt](https://github.com/Gaius-Augustus/BRAKER/files/4364727/filterGenemark.stdout.txt)

**Comment by gabelow** [comment]
Hi again,

I've been trying to investigate this error further and found that I was able to replicate it when running BRAKER only on the Aves OrthoDB subsection fasta file that I built previously, in EP mode without RNA-seq input. This time, train.gb has 37073 genes, but train.f.gb ends up with 0 genes.

Is there a known problem with filterGenesIn_mRNAname.pl? I really don't understand why the run breaks at this step.

Best,
Gabriel

**Comment by stu2** [comment]
This problem was related to the greedy regex in an older version of filterGenesIn_mRNAname.pl; this seems to have been fixed on 12 November 2019 (at least in the Augustus repo).

**Comment by francicco** [comment]
Hi @stu2,

I have the same problem. Do I have to try the filterGenesIn_mRNAname.pl from Augustus?

Best
F

**Comment by stu2** [comment]
Hi, yes you need the most recent one. Or you can edit line 38 in that script yourself
`    if ( $_ =~ m/transcript_id \"(.*)\"/ ) { `
change to:
`    if ( $_ =~ m/transcript_id \"([^"]*)\"/ ) { `
