### ISSUE TITLE
Training gene file in genbank format train.f.gb does not contain any training genes

### ISSUE THREAD

**Issue by mictadlo** [Gaius-Augustus/BRAKER#196]
Hi,
I ran the `braker.pl version 2.1.5` from bioconda `braker.pl --UTR=on --genome=$1 --bam=$2 --species=$3 --cores 10 --softmasking --gff3 --DIAMOND_PATH=/work/waterhouse_team/miniconda2/envs/braker2/bin/`. However, I have got this error:

```
# Fri Apr  3 07:09:55 2020: Log information is stored in file /lustre/scratch/waterhouse_team/LAB20/wm-no-dust/braker/braker.log
# Sat Apr  4 03:07:58 2020: ERROR: in file /work/waterhouse_team/miniconda2/envs/braker2/bin/braker.pl at line 7099
Training gene file in genbank format /lustre/scratch/waterhouse_team/LAB20/wm-no-dust/braker/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.
# Sat Apr  4 03:07:58 2020: ERROR: in file /work/waterhouse_team/miniconda2/envs/braker2/bin/braker.pl at line 7099
Training gene file in genbank format /lustre/scratch/waterhouse_team/LAB20/wm-no-dust/braker/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.
```
What did I miss?

Thank you in advance,

Best wishes,

Michal

**Comment by WTarabidopsis** [comment]
Hi, 
I'm a new user of BRAKER and I also trapped by this problem. Even the test file raised the same ERROR, have you solved it?

**Comment by tomasbruna** [comment]
Hello, did you try installing the latest version of AUGUSTUS? Using `git pull` from AUGUSTUS's GitHub.

**Comment by WTarabidopsis** [comment]
Thanks, my Augustus is the newest version and I'm not sure whether it's caused by this software. I solved this problem by modifying the `filterGenesIn_mRNAname.pl` script as mentioned by other users.
from
`$_ =~ m/transcript_id \"(.*)\"/`
to
`$_ =~ m/transcript_id \"(.*?)\"/`

**Comment by KatharinaHoff** [comment]
Actually, you are not using the latest Augustus. It does not contain that line of code, anymore, in filterGenesIn_mRNAname.pl:

https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/filterGenesIn_mRNAname.pl

Please be aware that the releases of Augustus are regrettably always lagging behind. I am for example not authorized to make a new Augustus release, myself. Therefore, you need to clone the latest Augustus from Github, instead of downloading release code.

Best,

Katharina

**Comment by aelezi01** [comment]
Hi Katharina, 

I have cloned the latest Augustus from Github a few days ago but I still have this error message, any clue on how to fix it?

Thank you in advance!
