### ISSUE TITLE
Eliminate logger::simple dependency?

### ISSUE THREAD

**Issue by mathog** [Gaius-Augustus/BRAKER#198]
BRAKER is the only package we have installed which uses logger::simple.  logger::simple can be installed with cpanminus but it is not available as a native package (rpm etc.) on any common Linux distribution.  See:

https://rpmfind.net/linux/rpm2html/search.php?query=perl-logger-simple&submit=Search
https://pkgs.org/search/?q=perl-logger-simple

Unless there is something very special about that logging package using it needlessly complicates installation of BRAKER.  Could you possibly use log4perl instead?  There are native packages for that on all common linux distros:

https://pkgs.org/search/?q=log4perl

**Comment by tomasbruna** [comment]
Hi,

thanks for this suggestion. Logger::Simple seems to be used only in the GeneMark part of the code, I will try to replace it in the next GeneMark release.

Tomas

**Comment by tomasbruna** [comment]
Logger::Simple was finally removed from GeneMark (be92e018f5727e70f66a64ff58b40210db1cd48e)
