### ISSUE TITLE
How do I interpret these transcript names?

### ISSUE THREAD

**Issue by gabelow** [Gaius-Augustus/BRAKER#199]
Hi Katherina,

I'm not quite sure what to make of these transcript names that start with different prefixes. For example:

# overlap start --------------------------------------------------------------------------------
# this overlap has 1 different transcripts
# This transcript jg26236.t1 is derived from g22042.t1 from the input file /mnt/main/EYR/EYR054/annotation/braker2_rnaseq_odb10_7proteomes_EYR054/
augustus.E.gtf
# It is supported by 0 other predicted genes
# the core of this joined transcript has priority 2
QKXG01002020.1  AUGUSTUS        gene    1441815 1442360 .       +       .       jg26236
QKXG01002020.1  AUGUSTUS        transcript      1441815 1442360 .       +       .       transcript_id "jg26236.t1"; gene_id "jg26236"
QKXG01002020.1  AUGUSTUS        start_codon     1441815 1441817 .       +       0       transcript_id "jg26236.t1"; gene_id "jg26236";
QKXG01002020.1  AUGUSTUS        CDS     1441815 1442360 0.62    +       0       transcript_id "jg26236.t1"; gene_id "jg26236";
QKXG01002020.1  AUGUSTUS        exon    1441815 1442360 .       +       .       transcript_id "jg26236.t1"; gene_id "jg26236";
QKXG01002020.1  AUGUSTUS        stop_codon      1442358 1442360 .       +       0       transcript_id "jg26236.t1"; gene_id "jg26236";
QKXG01000329.1  AUGUSTUS        gene    112899  113862  .       +       .       m1-g20753
QKXG01000329.1  AUGUSTUS        transcript      112899  113862  0.17    +       .       transcript_id "m1-g20753.t1"; gene_id "m1-g20753"
QKXG01000329.1  AUGUSTUS        start_codon     112899  112901  .       +       0       transcript_id "m1-g20753.t1"; gene_id "m1-g20753";
QKXG01000329.1  AUGUSTUS        CDS     112899  113111  0.6     +       0       transcript_id "m1-g20753.t1"; gene_id "m1-g20753";
QKXG01000329.1  AUGUSTUS        exon    112899  113111  .       +       .       transcript_id "m1-g20753.t1"; gene_id "m1-g20753";
QKXG01000329.1  AUGUSTUS        exon    112899  113111  .       +       .       transcript_id "m1-g20753.t1"; gene_id "m1-g20753";
QKXG01000329.1  AUGUSTUS        intron  113112  113793  0.27    +       .       transcript_id "m1-g20753.t1"; gene_id "m1-g20753";
QKXG01000329.1  AUGUSTUS        CDS     113794  113862  0.26    +       0       transcript_id "m1-g20753.t1"; gene_id "m1-g20753";
QKXG01000329.1  AUGUSTUS        exon    113794  113862  .       +       .       transcript_id "m1-g20753.t1"; gene_id "m1-g20753";
QKXG01000329.1  AUGUSTUS        exon    113794  113862  .       +       .       transcript_id "m1-g20753.t1"; gene_id "m1-g20753";
QKXG01000329.1  AUGUSTUS        stop_codon      113860  113862  .       +       0       transcript_id "m1-g20753.t1"; gene_id "m1-g20753";

What is the difference between transcripts beginning with "jg" and those with "m1-g"? Should I be keeping both? There are a lot more starting with jg than m1-g.

Thanks in advance for your time!

Cheers,
Gabriel

**Comment by KatharinaHoff** [comment]
In BRAKER, we used to use an AUGUSTUS component calles joingenes to merge gene sets. Transcript names starting with "jg" come from joingenes. Joingenes is known to miss certain genes, and we later add them, they have names started with "m1-g" etc. 

However, we are now using TSEBRA for merging gene sets and this issue is no longer relevant.
