### ISSUE TITLE
Spaln still keep running but progress stop at "(99.9%) pairs aligned"

### ISSUE THREAD

**Issue by WenhaoLiu0218** [Gaius-Augustus/BRAKER#200]
Hi,
I ran BRAKER for a ~60Mb genome (scaffold N50: 1.6Mb) three days ago, the script is as follows:

wd=braker-new
( time /hwfssz1/ST_AGRIC/USER/yujin/software/perl-5.30.0/bin/perl /hwfssz1/ST_AGRIC/USER/xuyan/software/BRAKER-master/scripts/braker.pl --species=S-nr-new --genome=S_V1_hardsoft.fa --prot_seq=/hwfssz1/ST_AGRIC/USER/xuyan/software/BRAKER-master/NR-chlorophyta.pep --epmode --softmasking --workingdir=$wd --cores=16 --gff3 --ALIGNMENT_TOOL_PATH=/hwfssz1/ST_AGRIC/USER/xuyan/software/BRAKER-master/ProtHint/bin --DIAMOND_PATH=/zfssz5/BC_PUB/Software/03.Soft_ALL/diamond-0.9.10/bin --GENEMARK_PATH=/hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64) &>braker-new.log

The cpu time is keep increasing and there is no error in all of the log files, but the progress looks like stopping at somewhere(see as below). A week ago i also ran BRAKER for another genome (~50MB) with the same way, it was successful and only took me one day to finish. So I don't know is something went wrong or just a normal phenomena? Thank you very much if i will get the response!

the tail of the brakes-new.log:
[Thu Apr  9 12:30:14 2020] 140548/141254 (99.5%) pairs aligned
[Thu Apr  9 12:30:28 2020] 140689/141254 (99.6%) pairs aligned
[Thu Apr  9 12:30:40 2020] 140831/141254 (99.7%) pairs aligned
[Thu Apr  9 12:30:52 2020] 140972/141254 (99.8%) pairs aligned
[Thu Apr  9 12:31:06 2020] 141113/141254 (99.9%) pairs aligned

the tail of the braker-new/brakes.log:
# Thu Apr  9 09:58:31 2020: Calling prothint.py...
# Thu Apr  9 09:58:31 2020: starting prothint.py
/hwfssz1/ST_AGRIC/USER/xuyan/software/BRAKER-master/ProtHint/bin/prothint.py --threads=16 --geneMarkGtf /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_ME/USER/xuyan/S/05.annotation/gene-annotation/BRAKER2/braker-new/GeneMark-ES/genemark.gtf /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_ME/USER/xuyan/S/05.annotation/gene-annotation/BRAKER2/braker-new/genome.fa /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_ME/USER/xuyan/S/05.annotation/gene-annotation/BRAKER2/braker-new/proteins.fa

**Comment by tomasbruna** [comment]
Hi,

sorry for a late reply -- I see you closed the issue, did the program finish successfully and how long was the delay between 99.9% and 100%? 

It can sometimes happen that the last couple of alignments (at 99.9%) take longer time than the rest. This is because ProtHint runs in parallel (16 threads in your case) and some alignments of long gene-protein pairs can take much longer than others. At 99.9%, ProtHint can be waiting for a couple of long-running threads to finish alignments for such gene-protein pairs before it can proceed with the next step.

Tomas

**Comment by TypicalSEE** [comment]
Met the same problem. Spaln keeps running for a single nuc-prot pair. The last pair has been running for 3 days while the others finished within just 2 hours. I checked the files of the last pair in $WD/Spaln, the nucleotide sequence is of 19Kb and the prot sequence is of 3.5K aa. I think it might be a bug of Spaln.
