### ISSUE TITLE
Example file ep.hints missing

### ISSUE THREAD

**Issue by matthewholding28** [Gaius-Augustus/BRAKER#201]
Hello,

The file ep.hints is missing from /BRAKER/example/

This makes it impossible to run the example data based on protein evidence. 

Thank you!

**Comment by tomasbruna** [comment]
Hello,

thanks for this report - it seems that the instructions in the https://github.com/Gaius-Augustus/BRAKER/blob/master/example/README.brakerexamples file are not up to date with the current tests.

The description of tests was moved to the main BRAKER readme file (https://github.com/Gaius-Augustus/BRAKER/blob/master/README.md#example-data), the `ep.hints` file is not used anymore.

@KatharinaHoff  -- is it safe to delete the https://github.com/Gaius-Augustus/BRAKER/blob/master/example/README.brakerexamples file and link the example file in the README.md instead?

Tomas

**Comment by tomasbruna** [comment]
Updated in https://github.com/Gaius-Augustus/BRAKER/commit/12f888196d483bb77f540d85dababbe34fdab711
