### ISSUE TITLE
failed to execute: .... GenomeThreader/bin/gth

### ISSUE THREAD

**Issue by Xiaofei-git** [Gaius-Augustus/BRAKER#202]
Dear there, 

I got the error as below, could you direct me why and how to fix it? Thanks a lot!

ERROR in file ~/software/BRAKER/scripts/startAlign.pl at line 673
failed to execute: ~/software/GenomeThreader/bin/gth -genomic ...pathto/braker/tmp_gth/genomechr11_random.fa -protein ...pathto/braker/tmp_gth/protFileFor_genomechr11_random.fa/mikado_loci_protein_addstop.fasta -gff3out -skipalignmentout -paralogs -gcmincoverage 80 -prseedlength 20 -prminmatchlen 20 -prhdist 2 -o  ...pathto/braker/align_gth/chr11_random.gth.aln 2>...pathto/braker/align_gth/chr11_random.gth.stderr!

**Comment by tomasbruna** [comment]
Hi,

I recently addresed a similar issue with GenomeThreader in this issue: https://github.com/Gaius-Augustus/BRAKER/issues/181

Can you check if this solution is relevant to you?

Tomas
