### ISSUE TITLE
Long internal N-regions

### ISSUE THREAD

**Issue by Juke34** [Gaius-Augustus/BRAKER#204]
I recently discovered that GeneMark crashes when it encounters long N-region (>10000) during the prediction (the training is fine).
I was wondering if BRAKER deals with that problem in a specific way to avoid to crash?

**Comment by tomasbruna** [comment]
Hello,

can you confirm you are using the latest version of GeneMark? I thought we fixed this problem in GeneMark a couple of versions back but it's possible it still occurs under some circumstances.

The problem should not affect the BRAKER results in a negative way, only predictions in regions with long stretches of Ns (where no genes would be predicted anyway) are affected by the crash.

If the problem does occur with the latest GeneMark version, can you share the log files from:

- `GeneMark-E*.stdout`
- `GeneMark-E*/gmes.log`

The files should be in the BRAKER working directory.

Thanks!
Tomas

**Comment by Juke34** [comment]
The problem was on gmhmm3 version 3.60_lic. It was failing on this long N-regions ungracefully (segmentation fault). I contacted Mark Borodovsky and Alexandre Lomsadze end of February about this problem. They explained me that the maximum gap length should be less than maximum intergenic length in the model file “gm_ap.hmm”. They told me they they will prepare a new release of the code that will warn user about the mismatch in gap length and maximum intergenic length. 

I wanted to know if you do anything special to avoid this problem (adapting the maximum intergenic length, removing the long N-regions). From what you said, Genemark will fails on those region what would not be a problem because later Augustus will not fail in those regions. This is fine if BRAKER processes sequences by chunks. Indeed if BRAKER does not divides up sequences into chunks, we could imagine in the case of annotating chromosome, if it fails very early all the remaining part would not be annotated. What is the BRAKER behaviour? Does it divides up sequences to perform the annotations?

**Comment by tomasbruna** [comment]
Thanks for the update and more info, this is indeed a different problem than the one already fixed.

In BRAKER, GeneMark is first run for the whole sequence, which is internally divided into chunks.

Then, reliable predictions from GeneMark are selected to train AUGUSTUS, and AUGUSTUS is run on the whole sequence with this model, regardless of GeneMark success on a particular chunk.

Therefore, if the failure of GeneMark in chunks with long stretches on Ns does not affect the rest of GeneMark predictions in other chunks, this should not cause any big problems for BRAKER. There is a way to check this -- take a look at the file `GeneMark-E*/genemark.f.multi_anchored.gtf` and count the number of genes in this file. If there are > 3000 genes, everything should be fine.

I will bring up this issue with Alexandre Lomsadze again, pre-processing of the sequence to remove these problematic regions should be done automatically by GeneMark, removing this problem completely.

Tomas

**Comment by Juke34** [comment]
Thank you for the explanation.
If GeneMark could deal automatically with this it would be wonderful. 
It is potentially not easy, because it needs a step of pre-processing to remove those region and a step of post processing to rebuild the original sequence, and shift all gene models positions  to stay coherent.

**Comment by Juke34** [comment]
Btw I have another question maybe should I open another issue. It' about how you Braker create the chunks. Sequence are split randomly (could be split in the middle of a gene)? Are the chunks abutting or there is an overlap between chunks?

**Comment by KatharinaHoff** [comment]
For AUGUSTUS, sequences are not split randomly, they are split in sequential order by some chunk size with an overlap, and subsequently, gene structures in the overlapping region are stitched together.

**Comment by tomasbruna** [comment]
GeneMark tries to split the sequence in places where long repeats are masked. If there are long continuous stretches of unmasked sequence, the sequence is split arbitrarily, so a gene can potentially be split. However, even if this happens, it will not affect the training of AUGUSTUS within BRAKER in a noticeable way.

**Comment by KatharinaHoff** [comment]
I am closing this issue.
