### ISSUE TITLE
--makehub option doesn't work

### ISSUE THREAD

**Issue by gbdias** [Gaius-Augustus/BRAKER#206]
Hi,

- When I add the `--makehub` option to my BRAKER run all the BRAKER steps finish successfully but the makehub command gets stuck for a long time with no progress being made.
```
#**********************************************************************************
#                               GENERATING TRACK DATA HUB
#**********************************************************************************
# Sun May  3 16:56:24 2020: generating track data hub for UCSC  Genome Browser
/home/gui/miniconda/envs/braker_4/bin/python3 /home/gui/miniconda/envs/braker_4/bin/make_hub.py -g /scratch/gui/braker2_2304382.sapelo2/braker/genome.fa -e myemail@gmail.com -l hub_Sp_ -L Sp_3 -X /scratch/gui/braker2_2304382.sapelo2/braker -P  > /scratch/gui/braker2_2304382.sapelo2/braker/makehub.log 2> /scratch/gui/braker2_2304382.sapelo2/braker/errors/makehub.err
```
- The error files are empty so I'm not sure how to debug this. Have you guys ever encountered this behavior?

Thanks

**Comment by KatharinaHoff** [comment]
I have not seen this. However, many updates have happened since this issue was opened (fewer on the MakeHub side, more on the BRAKER side). I assume that the problem was solved somewhere down the line. I will close this issue.
