### ISSUE TITLE
test1.sh: Genbank format file XXX contains 0 genes

### ISSUE THREAD

**Issue by TypicalSEE** [Gaius-Augustus/BRAKER#209]
Hi, I'm running BRAKER test1 ("test1.sh" in the example directory), and an error occurred.
I made some minor modifications to test1.sh so that example data can be found. The command is as follows:
`export PATH=...;
wd=test1;
( time perl /vol2/liuyang_group/liuyang/software/BRAKER/scripts/braker.pl --genome=./data/genome.fa --hints=./data/RNAseq.hints --softmasking --workingdir=$wd --cores=8) &> test1.log`

The content of the log file "test1.log" is as follows:
\# Fri May  8 12:28:08 2020: Log information is stored in file /vol2/liuyang_group/liuyang/BRYOPHYTA/test/0508_braker_test/test1/braker.log
\# Fri May  8 12:47:04 2020: ERROR: in file /vol2/liuyang_group/liuyang/software/BRAKER/scripts/braker.pl at line 7409
Training gene file in genbank format /vol2/liuyang_group/liuyang/BRYOPHYTA/test/0508_braker_test/test1/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.
\# Fri May  8 12:47:04 2020: ERROR: in file /vol2/liuyang_group/liuyang/software/BRAKER/scripts/braker.pl at line 7409
Training gene file in genbank format /vol2/liuyang_group/liuyang/BRYOPHYTA/test/0508_braker_test/test1/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.

real    19m1.452s
user    41m23.355s
sys     0m18.319s

The BRAKER scripts were obtained by directly `git clone https://github.com/Gaius-Augustus/BRAKER.git` today (May 8, 2020).
Another log file "braker.log" has a size of 16KB, so it is attached here.
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/4597097/braker.log)

Appreciate it very much if you could help me solve this problem!
Thanks.

**Comment by WTarabidopsis** [comment]
Hi,
I got the similar issue as yours, even with the testing data. Have you solved this problem? Does this because of the reads or fasta file name?
