### ISSUE TITLE
--UTR=on works?

### ISSUE THREAD

**Issue by francicco** [Gaius-Augustus/BRAKER#210]
Hi,
I was wondering if the UTR prediction now works, because the pipeline stopped during that stage, `utrs.gff` is empty.

Thanks
F

**Comment by KatharinaHoff** [comment]
No, all development on that end have been on hold since we lost daycare for
our kid on my end. It may take weeks or months until I return to research
and development. Sorry.

**Comment by francicco** [comment]
I see,

Is there a step I can use, or I have to re run the analysis with the flag onff?
Thanks
F

**Comment by KatharinaHoff** [comment]
It’s currently quite buggy. I wouldn’t recommend it. But feel free to try.

**Comment by francicco** [comment]
I'll rerun it, no problem! ;)
F

**Comment by francicco** [comment]
Hi @KatharinaHoff,

I re-run everything wiht --UTR=off. It looks like everything went smooth with the `BRAKER RUN FINISHED` in the log file. Is the final result `augustus.hints.*` right?

Cheers
F

P.S. I always loved this tool!

**Comment by tomasbruna** [comment]
Hi @francicco,

yes, that's the final output. More details about outputs are in this issue https://github.com/Gaius-Augustus/BRAKER/issues/194

Best,
Tomas

**Comment by leleory** [comment]
Hi @KatharinaHoff,
Has any development be made on the UTR prediction in Braker or is this development still on hold?
If not, can you recommend any other tools to add UTRs to the genes in the braker.gtf file?
Thank you,
Lel

**Comment by KatharinaHoff** [comment]
We have developed GUSHR, and this has been integrated into BRAKER. So far,
all tests look ok.

Not correctly implemented is handling of stranded bam files.

Use git clone/pull; not release code.

Katharina

**Comment by leleory** [comment]
Great news, thank you! I will give it a try
.
Do I need to run BRAKER from the beginning or can I start with the braker.gtf? 
As I am working with a mollusc and could not find Augustus config files for a closely related species I assume I need re-run BRAKER.

Lel

**Comment by KatharinaHoff** [comment]
You could run additional UTR training and prediction on the basis of an
existing augustus.hints.gtf. Please have a look at the documentation in
README.md of BRAKER.

**Comment by leleory** [comment]
It worked!

I run BRAKER with GUSHR with the softmasked genome, bam files, the augustus.hints.gtf file and the --addUTR=on parameter. There were no errors and the run finished with two gtf files: genes_in_gb.gtf and gushr.gtf.

The gushr.gtf file seems to contain all the models from augustus.hints.gtf with added UTRs.

Can you tell me what is in the genes_in_gb.gtf file?

Does GUSHR need species specific config with UTR parameters for it to work or that is only needed for the AUGUSTUS accuracy test which is run at the end of BRAKER?

I also have a tangential question. After the BRAKER run we have a mollusc (oyster) specific parameter set. Is there a way we can add this to the Augustus repository? There is at present no such set which could be used with Augustus.

Thank you for the help!
Lel

**Comment by leleory** [comment]
When I try to convert the gushr.gtf file into genepred I got the following error:
gtfToGenePred gushr.gtf gushr.genepred
gushr.gtf doesn't appear to be a GTF file (GFF not supported by this program)

One problem is that the gene and transcript features if these are on the (-) strands then the start and end coordinates are "reversed". See example below:
head gushr.gtf
LG10_ScCEduL_115_HRSCAF_144     GUSHR   gene    12204   9622    .       -       .       jg33594
LG10_ScCEduL_115_HRSCAF_144     GUSHR   transcript      12204   9622    .       -       .       jg33594.t1
LG10_ScCEduL_115_HRSCAF_144     AnnotationFinalizer     3'-UTR  4953    6020    .       -       .       transcript_id "jg33594.t1"; gene_id "jg33594";
LG10_ScCEduL_115_HRSCAF_144     AUGUSTUS        stop_codon      6021    6023    .       -       0       transcript_id "jg33594.t1"; gene_id "jg33594";

In the first line the start/end is given in relative coordinates (12204, 9622) as the gene feature is on the reverse strand. The same is true for the transcript. The other features are given with absolute coordinates, so these are fine.

The other problem is that for the gene and transcripts do not have the "gene_id;" and the "transcript_id; gene_id" tags. 
Also changing 5'- and 3'-UTR into 5UTR and 3UTR leads to the correct genepred format. So the below has no error any more:

head gushr_test.gtf
LG10_ScCEduL_115_HRSCAF_144     AUGUSTUS        gene    12204   9622.   -       .       gene_id "jg33594";
LG10_ScCEduL_115_HRSCAF_144     AUGUSTUS        transcript      9622    12204   .       -       .       transcript_id "jg33594.t1"; gene_id "jg33594";
LG10_ScCEduL_115_HRSCAF_144     AUGUSTUS        3UTR    4953    6020    .       -       .       transcript_id "jg33594.t1"; gene_id "jg33594";
LG10_ScCEduL_115_HRSCAF_144     AUGUSTUS        stop_codon      6021    6023    .       -       0       transcript_id "jg33594.t1"; gene_id "jg33594";

As the GTF/GFF formats are rather flexible I am not sure that all the above constitute to real problems with the format.

Best wishes,
Lel

**Comment by leleory** [comment]
One more formatting comment for the gushr_test.gff file.
The gene/transcript/UTR feature lines frequently have SPACE followed by TAB as field delimiters, instead of the expected single TAB character around positions and strands.
grep -P "\ttranscript\t" ../gushr.gtf | head | whitespace           
LG10_ScCEduL_115_HRSCAF_144￫GUSHR￫transcript￫12204￫9622￫.￫-·￫.￫jg33594.t1¶
LG10_ScCEduL_115_HRSCAF_144￫GUSHR￫transcript￫15008·￫15642￫.￫+·￫.￫jg33595.t1¶
LG10_ScCEduL_115_HRSCAF_144￫GUSHR￫transcript￫15758￫16777·￫.￫+￫.￫jg33596.t1¶

**Comment by francicco** [comment]
I see a lot of inconsistencies in the GTF, I mean the exon feature in the 3rd column is missing. It's really hard to convert and handle the file.
F

**Comment by KatharinaHoff** [comment]
Your issue has been noted. Might take a while until we are able to look
into fixing it.

**Comment by leleory** [comment]
Thank you Katharina! It is really good that the software works and adds the UTRs. 
@francicco Solving the small issues with the GTF is just now text processing. Converting the GTF to genepred and then bed12 with the kent tools is easy, and then one can covert it back again to UCSC's gtf format.

**Comment by francicco** [comment]
I don't kown @leleory, it seems very convoluted and prone to errors. I'm using mikado and it's very stringent, any single coordinate error makes it complain.

F

**Comment by francicco** [comment]
Sorry, I think I was a bit grumpy HAHAHAH.
I'm just fighting with these coversions since a few days, it's so frustrating.

You're doing a great job!!!
Seriously.
Sorry again!
F

**Comment by KatharinaHoff** [comment]
You can now add UTRs to gtf files generated by BRAKER by using stringtie assembly for transcriptome with https://github.com/Gaius-Augustus/BRAKER/blob/utr_from_stringtie/scripts/stringtie2utr.py . Hope that's more stable.
