### ISSUE TITLE
train.f.gb contains 0 genes

### ISSUE THREAD

**Issue by smallfishcui** [Gaius-Augustus/BRAKER#212]
Hi Katharina,

I have been using the most updated scripts of braker2 and augustus, and the newest filterGenesIn_mRNAname.pl,  but still  get the error, as  the issue #126 and #196 mentioned. 
The file train.gb and good_genes.lst showed quite many genes, and the name seems to be matching.
So far I can only get it over by giving braker a species parameter, however if so do I still need the training? 

Thanks,
Cui

**Comment by tomasbruna** [comment]
Hi Cui,

do you get this problem when running [tests](https://github.com/Gaius-Augustus/BRAKER/tree/master/example/tests),  in the example folder? More details about running tests are here https://github.com/Gaius-Augustus/BRAKER#example-data.

Tomas

**Comment by smallfishcui** [comment]
Hi Tomas,
Thank you very much for the hint!
According to your suggestion I tried the test1.sh and found there is an error raised by new_species.pl:
Failed to create new species with new_species.pl, check write permissions in /home/.conda/pkgs/augustus3.3.3/config/species directory!
I check the directory and give the write permission to all the folders in species, config, but still this script doesnt work. 
With my own data, I had tried to make a directory with my species name and leave it in the species folder, the pipeline went through, but because there isnt any parameter in the species folder it failed at some point duing augustus training. 
I am not sure, maybe this is not a braker problem any more, but do you know what could be the reason?

thanks,
Cui

**Comment by smallfishcui** [comment]
Hi again,

I solved the problem mentioned in my last message about the writing permission to the config folder by setting the config folder to the compiled version of augustus.
However, the test1 finished with the same error:
# Wed May 20 10:55:36 2020: ERROR: in file /home/conda/envs/braker2/bin/braker.pl at line 7409
Training gene file in genbank format /home/.conda/envs/braker2/example/braker/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.
# Wed May 20 10:55:36 2020: ERROR: in file /home/.conda/envs/braker2/bin/braker.pl at line 7409
Training gene file in genbank format /home/.conda/envs/braker2/example/braker/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.

best,
Cui

**Comment by smallfishcui** [comment]
Hi again,

I eventually found out my problem- I installed braker and augustus using conda, but I only replaced the new scripts in the packages folders, and did not realize that the scripts need to be changed from the environment bin folders. After I replace the scripts in .conda/envs/bin/, this problem did not occur any more. I am closing this issue now.

best,
Cui
