### ISSUE TITLE
gmhmme3 error: error, negative argument in LOG function

### ISSUE THREAD

**Issue by mbnmbn00** [Gaius-Augustus/BRAKER#213]
I'm using Braker 2.1.5 to annotate sixty fungal genomes.
I successfully ran for 56 genomes but failed on four genomes.

Error message in `GeneMark-ET.stdout`:
```
warning on: /global/projectb/scratch/mbnmbn00/tools/FunGAP/external/gm_et_linux_64/gmhmme3  -m /global/projectb/scratch/mbnmbn00/analysis/Lentinula/resequencing/braker1_out/SRR3504433/GeneMark-ET/run/ET_C_1/ET_C_1.mod   -f tr   -o /global/projectb/scratch/mbnmbn00/analysis/Lentinula/resequencing/braker1_out/SRR3504433/GeneMark-ET/run/ET_C_2/hmmout/dna.fa_1.out  /global/projectb/scratch/mbnmbn00/analysis/Lentinula/resequencing/braker1_out/SRR3504433/GeneMark-ET/data/training/dna.fa_1
error, negative argument in LOG function : -0.104000
error, negative argument in LOG function : -0.104000
```

My genome is quite fragmented (~10,000 sequences).

I attach the ET_C_1.mod and GeneMark-ET.stdout files.
[Archive.zip](https://github.com/Gaius-Augustus/BRAKER/files/4654677/Archive.zip)

**Comment by tomasbruna** [comment]
Hi @mbnmbn00,

thanks for the report, I got the `.mod` file. Do you think you could also upload one of the problematics sequences, for example `/global/projectb/scratch/mbnmbn00/analysis/Lentinula/resequencing/braker1_out/SRR3504433/GeneMark-ET/data/training/dna.fa_1`? That would be of great help when we try to reproduce this error.

Thanks,
Tomas

**Comment by mbnmbn00** [comment]
Thank you for the quick response. I attach the requested file.
[dna.fa_1.zip](https://github.com/Gaius-Augustus/BRAKER/files/4664067/dna.fa_1.zip)

I ran twice with different BAM files and got the same error.

**Comment by tomasbruna** [comment]
Thanks!

I was able to reproduce this error, I will pass these inputs to Alex Lomsadze, maintainer of `gmhmme3` binary (http://exon.gatech.edu/GeneMark/contact.html). Can you send me your e-mail address so that I can keep you in the loop?

Best,
Tomas

**Comment by mbnmbn00** [comment]
mbnmbn00@gmail.com here you go!

**Comment by tomasbruna** [comment]
Hello @mbnmbn00,

we have finally fixed this error. Please try the latest version of GeneMark-ET from http://topaz.gatech.edu/GeneMark/license_download.cgi.

Best,
Tomas

**Comment by mbnmbn00** [comment]
Wow. That's awesome! Thank you so much! I will try it out.
