### ISSUE TITLE
train.f.gb does not contain any training genes

### ISSUE THREAD

**Issue by bam2wigKillMe** [Gaius-Augustus/BRAKER#214]
when i try the cmd below which is similiar to test1.sh, braker report: train.f.gb does not contain any training genes.
$ braker.pl --genome=genome.fa --bam=RNAseq.bam --softmasking --cores=8
# Thu May 21 22:14:11 2020: Log information is stored in file /path_to_braker/BRAKER-master/example/braker/braker.log
# Thu May 21 22:24:32 2020: ERROR: in file /path_to_braker/BRAKER-master/scripts/braker.pl at line 7409
Training gene file in genbank format /path_to_braker/BRAKER-master/example/braker/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.
# Thu May 21 22:24:32 2020: ERROR: in file /path_to_braker/BRAKER-master/scripts/braker.pl at line 7409
Training gene file in genbank format /path_to_braker/BRAKER-master/example/braker/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.

GeneMark-ET.stderr only got hundreds of lines like this:
(in cleanup)    (in cleanup)  at /path/biosoft/conda/envs/braker/lib/site_perl/5.26.2/Object/InsideOut.pm line 1953 during global destruction.

The braker/braker.log's last lines are like this:
# Thu May 21 23:26:22 2020: Filtering train.gb for "good" mRNAs:
perl /path/biosoft/conda/envs/braker/bin/filterGenesIn_mRNAname.pl /path_to_braker/BRAKER-master/example/mytest/braker/good_genes.lst /path_to_braker/BRAKER-master/example/mytest/braker/train.gb > /path_to_braker/BRAKER-master/example/mytest/braker/train.f.gb 2>/path_to_braker/BRAKER-master/example/mytest/braker/errors/filterGenesIn_mRNAname.stderr
# Thu May 21 23:26:22 2020: Genbank format file /path_to_braker/BRAKER-master/example/mytest/braker/train.f.gb contains 0 genes.

What shall i do? Big thank you for any answer!

**Comment by tomasbruna** [comment]
Hello,

this problem is likely caused by an older version of Augustus. Please clone the latest Augustus from its GitHub:

    git clone git@github.com:Gaius-Augustus/Augustus.git

More details about this issue were discussed here https://github.com/Gaius-Augustus/BRAKER/issues/196

Best,
Tomas

**Comment by bam2wigKillMe** [comment]
Hello,
Thank you for your answer. But my Augustus is 3.3.3. Is it the newest version? or the master of Augustus is the newest version?
Thank you again!
Best wishes!

**Comment by bam2wigKillMe** [comment]
i just git clone the augustus, and reinstall it, changed PATH and AUGUSTUS_CONFIG_PATH, but still the same:
# Fri May 22 12:40:35 2020: ERROR: in file /path/mysoft/BRAKER-master/scripts/braker.pl at line 7409
Training gene file in genbank format /path/mysoft/BRAKER-master/example/mytest/braker/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.

**Comment by bam2wigKillMe** [comment]
Thank you for your answer very much, I found out that i used to install augustus by bioconda, so it overrided my newest augustus!

Thank you so much again!
Best wished!
