### ISSUE TITLE
Probably Braker didn't try to locate prothint by $ALIGNMENT_TOOL_PATH

### ISSUE THREAD

**Issue by bam2wigKillMe** [Gaius-Augustus/BRAKER#216]
when i ran the test2.sh, it reported errors like this after a hour and half:
Use of uninitialized value $ALIGNMENT_TOOL_PATH in concatenation (.) or string at /path/mysoft/BRAKER-master/scripts/braker.pl line 5152.
Can't exec "/prothint.py": 没有那个文件或目录 at /path/mysoft/BRAKER-master/scripts/braker.pl line 5158.
ERROR in file /path/mysoft/BRAKER-master/scripts/braker.pl at line 5161
Failed to execute /prothint.py --threads=11 --geneSeeds ......(too long, so i didn't copy the rest of cmd)

And I'm sure I put $ALIGNMENT_TOOL_PATH in my ~/.bashrc, and source it.
And I took a look at the braker.log, and I didn't see the braker try to locate it with $ALIGNMENT_TOOL_PATH.

So I think it's probably a bug.
Thank you for answers very much.

Best wishes!

**Comment by bam2wigKillMe** [comment]
To correct, I found test2/braker.log did locate $ALIGNMENT_TOOL_PATH, but the test2_restart1.sh did not.

**Comment by tomasbruna** [comment]
Hello,

thanks for these reports, I will take a look at what's wrong with these tests (also at the issue https://github.com/Gaius-Augustus/BRAKER/issues/215) over the weekend.

Best,
Tomas

**Comment by bam2wigKillMe** [comment]
Thank you for your attention!

**Comment by tomasbruna** [comment]
Hello @bam2wigKillMe,

you are correct, this is a bug which needs fixing, thanks for reporting it. There is a new feature in BRAKER2 which runs the ProtHint protein mapping twice, in 2 iterations, for better sensitivity.

The $ALIGNMENT_TOOL_PATH is however only set in the first iteration. Thus, when the code is restarted from the middle (like in test2_restart1.sh), the path is never set for the purposes of the second iteration, hence the crash.

**Comment by bam2wigKillMe** [comment]
Thank you for your replies!

**Comment by tomasbruna** [comment]
I am re-opening this issue -- until this problem is fixed.

**Comment by tomasbruna** [comment]
Fixed in https://github.com/Gaius-Augustus/BRAKER/commit/97ecb8a061f5141a852b1fa7a732fa00bc04e233
