### ISSUE TITLE
Segmentation fault (core dumped) after running test3.sh for 8h 40min

### ISSUE THREAD

**Issue by bam2wigKillMe** [Gaius-Augustus/BRAKER#217]
Sorry to bother you again, but I just can't fix it after searching for websites and here.

I run example/tests/test3.sh, and it crushed like:
sh: 
line 1: 31498 Segmentation fault (core dumped)
/path/mysoft/Augustus/bin/augustus --species=Sp_5 --AUGUSTUS_CONFIG_PATH=/path/mysoft/Augustus/config --extrinsicCfgFile=/path/mysoft/BRAKER-master/scripts/cfg/ep.cfg --alternatives-from-evidence=true --hintsfile=/path/mysoft/BRAKER-master/example/tests/test3/hintsfile.gff.Ppri5 --UTR=off --exonnames=on --codingseq=on --allow_hinted_splicesites=gcag,atac --softmasking=1 /path/mysoft/BRAKER-master/example/tests/test3/genome.fa > /path/mysoft/BRAKER-master/example/tests/test3/augustus.Ppri5.gff 2> /path/mysoft/BRAKER-master/example/tests/test3/errors/augustus.Ppri5.stderr

ERROR in file /path/mysoft/BRAKER-master/scripts/braker.pl at line 9309
Failed to execute: /path/mysoft/Augustus/bin/augustus --species=Sp_5 --AUGUSTUS_CONFIG_PATH=/path/mysoft/Augustus/config --extrinsicCfgFile=/path/mysoft/BRAKER-master/scripts/cfg/ep.cfg --alternatives-from-evidence=true --hintsfile=/path/mysoft/BRAKER-master/example/tests/test3/hintsfile.gff.Ppri5 --UTR=off --exonnames=on --codingseq=on --allow_hinted_splicesites=gcag,atac --softmasking=1 /path/mysoft/BRAKER-master/example/tests/test3/genome.fa 1>/path/mysoft/BRAKER-master/example/tests/test3/augustus.Ppri5.gff 2>/path/mysoft/BRAKER-master/example/tests/test3/errors/augustus.Ppri5.stderr!

This is the test3/errors/augustus.Ppri5.stderr :
Error in hint line: 2R ProtHint Intron 7705784 7705843 5 - . al_score=0.434846; splice_sites=gt_ag;
No source specified (e.g. by source=M in the last column)
Unknown hint feature 'Intron'. Ignoring it. For a list of the 17 allowed features see the first column of the table in config/extrinsic/extrinsic.cfg.

And in test3/hintsfile.gff.Ppri5, I found many "Intron"s that may cause this problem because augustus recognize "intron", right?
But why are there so many "Intron"s in hintsfile.gff.Ppri5:
2R both intron 11989328 11989381 1000 + . src=M;pri=6;
2R both intron 11990933 11991064 1000 + . src=M;pri=6;
2R ProtHint Intron 7705784 7705843 5 - . al_score=0.434846; splice_sites=gt_ag;
2R ProtHint Intron 8970544 8970611 5 - . al_score=0.479567; splice_sites=gt_ag; topProt=TRUE;
2R ProtHint Intron 7705967 7706019 5 - . al_score=0.398344; splice_sites=gt_ag;

Thanks in advance!

**Comment by dianamosa** [comment]
Hello, did you be able to solve this issue? I am having the same problem with test 2.

sh: line 1: 34677 Segmentation fault      (core dumped) /home/usr/Augustus-3.3.3/bin/etraining --species=Sp_4 --AUGUSTUS_CONFIG_PATH=/home/usr/Augustus-3.3.3/config /home/usr/BRAKER/example/braker/train.f.gb > /home/usr/BRAKER/example/braker/gbFilterEtraining.stdout 2> /home/usr/BRAKER/example/braker/errors/gbFilterEtraining.stderr
ERROR in file /home/usr/conda/envs/braker/BRAKER/scripts/braker.pl at line 7455
Failed to execute: /home/usr/Augustus-3.3.3/bin/etraining --species=Sp_4 --AUGUSTUS_CONFIG_PATH=/home/usr/Augustus-3.3.3/config /home/usr/BRAKER/example/braker/train.f.gb 1> /home/usr/BRAKER/example/braker/gbFilterEtraining.stdout 2>/home/usr/BRAKER/example/braker/errors/gbFilterEtraining.stderr

**Comment by bam2wigKillMe** [comment]
> Hello, did you were able to solve this issue? I am having the same problem with test 2.
> 
> sh: line 1: 34677 Segmentation fault (core dumped) /home/usr/Augustus-3.3.3/bin/etraining --species=Sp_4 --AUGUSTUS_CONFIG_PATH=/home/usr/Augustus-3.3.3/config /home/usr/BRAKER/example/braker/train.f.gb > /home/usr/BRAKER/example/braker/gbFilterEtraining.stdout 2> /home/usr/BRAKER/example/braker/errors/gbFilterEtraining.stderr
> ERROR in file /home/usr/conda/envs/braker/BRAKER/scripts/braker.pl at line 7455
> Failed to execute: /home/usr/Augustus-3.3.3/bin/etraining --species=Sp_4 --AUGUSTUS_CONFIG_PATH=/home/usr/Augustus-3.3.3/config /home/usr/BRAKER/example/braker/train.f.gb 1> /home/usr/BRAKER/example/braker/gbFilterEtraining.stdout 2>/home/usr/BRAKER/example/braker/errors/gbFilterEtraining.stderr

Not yet. But I believe it's a bug.
@tomasbruna

**Comment by KatharinaHoff** [comment]
The tests problem is on our radar. I still cannot work on maintaining of
BRAKER due to lack of daycare for my kid because of Corona crisis
regulations. Please be patient...

**Comment by tomasbruna** [comment]
Hello,

the test sets were finally updated (https://github.com/Gaius-Augustus/BRAKER/pull/248). Please get the latest BRAKER version and try the tests again. Note that you will also need to update ProtHint, there is a new release https://github.com/gatech-genemark/ProtHint/releases/tag/v2.5.0.

Best,
Tomas

**Comment by cgjosephlee** [comment]
I encounter similar problem that etraining complained `Species-specific configuration files not found`, and `Sp_1` seems not created automatically.
I'm using latest git version for both braker2 (e412971) and augustus (4fdb3c4).

Also, can you provide a specific git commit version of braker2 and augustus that are compatible? Latest versions are evolving and not always working together. Or, version tags would be nice.

**Comment by tomasbruna** [comment]
Hello @cgjosephlee,

the versions of BRAKER2 and AUGUSTUS you specified should be compatible. In general, we are trying to make the latest versions in the master branches of both tools compatible.

> Also, can you provide a specific git commit version of braker2 and augustus that are compatible?

We will create compatible releases of the latest versions of the tools to solve this problem, soon.

About the issue you encountered, can you share the full BRAKER2 log of the failed run? Thanks!

Best,
Tomas

**Comment by dzaccook** [comment]
> Hello, did you were able to solve this issue? I am having the same problem with test 2.
> 
> sh: line 1: 34677 Segmentation fault (core dumped) /home/usr/Augustus-3.3.3/bin/etraining --species=Sp_4 --AUGUSTUS_CONFIG_PATH=/home/usr/Augustus-3.3.3/config /home/usr/BRAKER/example/braker/train.f.gb > /home/usr/BRAKER/example/braker/gbFilterEtraining.stdout 2> /home/usr/BRAKER/example/braker/errors/gbFilterEtraining.stderr
> ERROR in file /home/usr/conda/envs/braker/BRAKER/scripts/braker.pl at line 7455
> Failed to execute: /home/usr/Augustus-3.3.3/bin/etraining --species=Sp_4 --AUGUSTUS_CONFIG_PATH=/home/usr/Augustus-3.3.3/config /home/usr/BRAKER/example/braker/train.f.gb 1> /home/usr/BRAKER/example/braker/gbFilterEtraining.stdout 2>/home/usr/BRAKER/example/braker/errors/gbFilterEtraining.stderr

I have the same errors but I installed Augustus-3.4, how did you deal with it?

**Comment by bam2wigKillMe** [comment]
> > Hello, did you were able to solve this issue? I am having the same problem with test 2.
> > sh: line 1: 34677 Segmentation fault (core dumped) /home/usr/Augustus-3.3.3/bin/etraining --species=Sp_4 --AUGUSTUS_CONFIG_PATH=/home/usr/Augustus-3.3.3/config /home/usr/BRAKER/example/braker/train.f.gb > /home/usr/BRAKER/example/braker/gbFilterEtraining.stdout 2> /home/usr/BRAKER/example/braker/errors/gbFilterEtraining.stderr
> > ERROR in file /home/usr/conda/envs/braker/BRAKER/scripts/braker.pl at line 7455
> > Failed to execute: /home/usr/Augustus-3.3.3/bin/etraining --species=Sp_4 --AUGUSTUS_CONFIG_PATH=/home/usr/Augustus-3.3.3/config /home/usr/BRAKER/example/braker/train.f.gb 1> /home/usr/BRAKER/example/braker/gbFilterEtraining.stdout 2>/home/usr/BRAKER/example/braker/errors/gbFilterEtraining.stderr
> 
> I have the same errors but I installed Augustus-3.4, how did you deal with it?

Update BRAKER and ProtHint as Tomas said.

**Comment by dzaccook** [comment]
> > > Hello, did you were able to solve this issue? I am having the same problem with test 2.
> > > sh: line 1: 34677 Segmentation fault (core dumped) /home/usr/Augustus-3.3.3/bin/etraining --species=Sp_4 --AUGUSTUS_CONFIG_PATH=/home/usr/Augustus-3.3.3/config /home/usr/BRAKER/example/braker/train.f.gb > /home/usr/BRAKER/example/braker/gbFilterEtraining.stdout 2> /home/usr/BRAKER/example/braker/errors/gbFilterEtraining.stderr
> > > ERROR in file /home/usr/conda/envs/braker/BRAKER/scripts/braker.pl at line 7455
> > > Failed to execute: /home/usr/Augustus-3.3.3/bin/etraining --species=Sp_4 --AUGUSTUS_CONFIG_PATH=/home/usr/Augustus-3.3.3/config /home/usr/BRAKER/example/braker/train.f.gb 1> /home/usr/BRAKER/example/braker/gbFilterEtraining.stdout 2>/home/usr/BRAKER/example/braker/errors/gbFilterEtraining.stderr
> > 
> > 
> > I have the same errors but I installed Augustus-3.4, how did you deal with it?
> 
> Update BRAKER and ProtHint as Tomas said.

Thank you! All soft have been up to date.

**Comment by tomasbruna** [comment]
Hello @dzaccook,

are you able to run `etraining` (in `/home/usr/Augustus-3.3.3/bin/`) alone or does it give you a segmentation fault?

Tomas

**Comment by XK4959** [comment]
How to solve this problem, I also encountered the same problem.
But I run another genome with the same command and there is no problem.
