### ISSUE TITLE
failed to execute: $PATH/exonerate

### ISSUE THREAD

**Issue by FloraDanica** [Gaius-Augustus/BRAKER#219]
Dear Authors and all,

I try the code :

braker.pl --cores 32 --species=morus3 --genome=/$PATH/genome.fa --softmasking --bam=$PATH/star.bam --prot_seq=$PATH/proteome.aa.fa --prg=$PATH/exonerate --gff3

then I got the ERROR:
"ERROR in file $PATH/braker2/bin/startAlign.pl at line 629
failed to execute:$PATH/braker2/bin/exonerate --model protein2genome --maxintron 30000 --showtargetgff --showalignment no --query merged_Mnotabilis_Malba_proteome_aa_addstop.fa -t   $PATH/braker/tmp_exonerate/genomeCP050236.1.fa > $PATH/braker/align_exonerate/CP050236.1.exonerate.aln 2> $PATH/braker/align_exonerate/CP050236.1.exonerate.stderr!"

I read the answer in #181 and I tried as they said, but I still got the same error. What should I do?

**Comment by Xiaofei-git** [comment]
Did you check your fasta file to see if there is any illegal character?

**Comment by KatharinaHoff** [comment]
Please use ProtHint instead of Exonerate when working with BRAKER.
