### ISSUE TITLE
ERROR in file /TOOLS/BRAKER/scripts/braker.pl at line 8306

### ISSUE THREAD

**Issue by tdcollingsworth** [Gaius-Augustus/BRAKER#222]
Hello, BRAKER Team !

I have encountered a similar problem as previously reported in #87.

The run command and output are:
```
braker.pl --genome=/WORKSPACE/20-APX-02-2.fa --prot_seq=/WORKSPACE/protein_aa.fa --prg=gth --trainFromGth --softmasking --species=20-APX-02-2 --verbosity=4 --workingdir=/WORKSPACE/20-APX-02-2/ --nocleanup --cores=8
# Wed May 27 13:08:06 2020: Log information is stored in file /WORKSPACE/20-APX-02-2/braker.log
ERROR in file /TOOLS/BRAKER/scripts/braker.pl at line 8306
Failed to execute: /usr/bin/python3 /TOOLS/Augustus/scripts/fix_in_frame_stop_codon_genes.py -g /WORKSPACE/20-APX-02-2/genome.fa -t /WORKSPACE/20-APX-02-2/augustus.hints.gtf -b /WORKSPACE/20-APX-02-2/bad_genes.lst -o augustus.hints_fix_ifs_ -s 20-APX-02-2 -m on --UTR off --print_utr off -a /TOOLS/Augustus/config/ -C /TOOLS/cdbfasta -A /TOOLS/Augustus/bin/ -S /TOOLS/Augustus/scripts/ -H /WORKSPACE/20-APX-02-2/hintsfile.gff -e /TOOLS/BRAKER/scripts/cfg/gth.cfg  > /WORKSPACE/20-APX-02-2/fix_in_frame_stop_codon_genes_augustus.hints.log 2> /WORKSPACE/20-APX-02-2/errors/fix_in_frame_stop_codon_genes_augustus.hints.err
```
"fix_in_frame_stop_codon_genes_augustus.hints.log" is empty.

The contents of "fix_in_frame_stop_codon_genes_augustus.hints.err" are:
```
cat 20-APX-02-2/errors/fix_in_frame_stop_codon_genes_augustus.hints.err 
Traceback (most recent call last):
  File "/TOOLS/Augustus/scripts/fix_in_frame_stop_codon_genes.py", line 737, in <module>
    for ifs_line in ifs_handle:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 168: ordinal not in range(128)
```
The contents of "fix_IFS_log_..." are:
```
Creating directory tmp_hdoqhuza/.
Trying to execute the following command:
/TOOLS/cdbfasta/cdbfasta /WORKSPACE/20-APX-02-2/genome.fa
Suceeded in executing command.
Trying to execute the following command:
/TOOLS/cdbfasta/cdbyank -a 20-APX-02-2_9 /WORKSPACE/20-APX-02-2/genome.fa.cidx
Suceeded in executing command.
Trying to execute the following command:
/bin/grep -w 20-APX-02-2_9 /WORKSPACE/20-APX-02-2/hintsfile.gff
Suceeded in executing command.
Trying to execute the following command:
/TOOLS/Augustus/bin/augustus --mea=1 --species=20-APX-02-2 --softmasking=on --UTR=off --print_utr=off --genemodel=complete --alternatives-from-evidence=0 --exonnames=off --predictionStart=550501 --predictionEnd=552782 --AUGUSTUS_CONFIG_PATH=/TOOLS/Augustus/config/ tmp_hdoqhuza/genome.20-APX-02-2_9.fa --hintsfile=tmp_hdoqhuza/hints.20-APX-02-2_9.gff --extrinsicCfgFile=/TOOLS/BRAKER/scripts/cfg/gth.cfg
Suceeded in executing command.
```

Some versioning information:
```
> braker.pl --version
braker.pl version 2.1.5
> python3 --version
Python 3.6.9
```
What else can I check or try to help us find a solution?

Thank you for your time!

**Comment by tomasbruna** [comment]
Hello @tdcollingsworth ,

this seems to be the same error as described here https://github.com/Gaius-Augustus/Augustus/issues/148. I recommend monitoring that issue.

I encountered this problem before when my system locales were broken. Following this tutorial could help https://perlgeek.de/en/article/set-up-a-clean-utf8-environment. Let us know if that helps.

Until the problem is resolved (either by fixing locales or something in the script itself), you can skip the `fix_in_frame_stop_codon_genes.py` procedure with `--skip_fixing_broken_genes` so that you can run BRAKER successfully to the end. You can see how many and which genes are affected by the in-frame stop codon in `/WORKSPACE/20-APX-02-2/bad_genes.lst`.

Best,
Tomas

**Comment by tdcollingsworth** [comment]
Hey, @tomasbruna -

I was able to configure the locales correctly which solved the problem!

Thank you so much for the prompt, helpful support -- we're excited to be able to use your tool in our workflows!

Cheers,
Timothy

**Comment by 17863952296** [comment]
> Hello @tdcollingsworth ,
> 
> this seems to be the same error as described here [Gaius-Augustus/Augustus#148](https://github.com/Gaius-Augustus/Augustus/issues/148). I recommend monitoring that issue.
> 
> I encountered this problem before when my system locales were broken. Following this tutorial could help https://perlgeek.de/en/article/set-up-a-clean-utf8-environment. Let us know if that helps.
> 
> Until the problem is resolved (either by fixing locales or something in the script itself), you can skip the `fix_in_frame_stop_codon_genes.py` procedure with `--skip_fixing_broken_genes` so that you can run BRAKER successfully to the end. You can see how many and which genes are affected by the in-frame stop codon in `/WORKSPACE/20-APX-02-2/bad_genes.lst`.
> 
> Best, Tomas

I encountered the same problem. but it's valid when I set up a clean utf-8 environment, same problems  remained been reported again.
