### ISSUE TITLE
GeneMark repeated (in cleanup) error

### ISSUE THREAD

**Issue by matthewholding28** [Gaius-Augustus/BRAKER#226]
Hello! Thank you in advance for your advice. 

I realize that other's have raised things related to this issue here, but I haven't seen a specific answer that has allowed me to work toward a fix. Here is my braker2 call, where I am running alignments of RNA-seq data done in HISAT2 and a protein fasta as extrinsic evidence: 

braker.pl --cores=62 --species=Bidaho --genome=masked_wMito.fasta \
--bam=Cecum_align_sorted.bam,Heart_align_sorted.bam,Kidney_align_sorted.bam,Liver_align_sorted.bam,Sm_Int_align_sorted.bam,Testes_align_sorted.bam \
--prot_seq=uniprot_odb10_CYP450_concat_aa.fasta \
--etpmode --softmasking

My GeneMark-ES.stderr file is quickly filled with thousands of the following repeat lines: 

(in cleanup)    (in cleanup)  at /usr/local/share/perl/5.26.1/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /usr/local/share/perl/5.26.1/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /usr/local/share/perl/5.26.1/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /usr/local/share/perl/5.26.1/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /usr/local/share/perl/5.26.1/Object/InsideOut.pm line 1953 during global destruction.

Using previous issues posted here and elsewhere, I have attempted the following fixes to deal with these errors, but nothing has helped yet:
1. Updated Genemark and put a new .gm_key in my home directory
2. Used change_path_in_perl_scripts.pl to ensure appropriate perl is called
3. Attempted to test Genemark scripts directly with Genemark's example input files, but only the Genemark-EP mode test dataset are actually provided with the latest Genemark download, so that is not a helpful test.

**Comment by tomasbruna** [comment]
Hello @matthewholding28,

does the BRAKER run fail and what stage? Are there other error messages than this one? This particular error occurs when Perl tries to clean memory which was already cleaned up, so it does not really affect the GeneMark execution.

Tomas
