### ISSUE TITLE
Augustus error:  *_exon_probs.pbl not found

### ISSUE THREAD

**Issue by grexor** [Gaius-Augustus/BRAKER#227]
I am running Braker with RNA-seq only like this:

`braker.pl --nocleanup --cores=8 --species=myspecies --genome=mygenome.fasta --bam=mybamfile.bam`

However, after "RUNNING GENEMARK-EX" step, it looks like the Augustus training fails. It just says this for training:

```
#**********************************************************************************
#                               TRAIN AUGUSTUS                                     
#**********************************************************************************
# Wed Jun 10 20:40:50 2020: training AUGUSTUS
# Wed Jun 10 20:40:50 2020: Copying optimized parameters to working directory 
/braker/myspecies
cp -r /Augustus/config//species/myspecies /braker/myspecies
```

And then it moves on to:

```
#**********************************************************************************
#                               PREDICTING GENES WITH AUGUSTUS (NO UTRS)           
#**********************************************************************************
# Wed Jun 10 20:40:50 2020: RUNNING AUGUSTUS
```

Now, the problem is, when debugging the Augustus prediction of genes, Augustus writes an error like this:

`ExonModel: Couldn't open file /Augustus/config/species/myspecies/myspecies_exon_probs.pbl
`

Looks like the training of Augustus didn't work? Also, it seems it points Augustus to use species files from the **Augustus/config/species/myspecies** folder, instead of the copied ones in **/braker/myspecies**?

I am debugging this by looking at files in the run subfolder **augustus_files_hints**.

Thanks for any help,
Gregor

**Comment by wuyh0328** [comment]
I'm also having such a problem, have you solved it?
