### ISSUE TITLE
trouble to restart braker with UTR option on

### ISSUE THREAD

**Issue by nicolascerveau** [Gaius-Augustus/BRAKER#232]
Dear Braker designer,

First of all I would to thank you a lot for the great tool you create and provide to the scientific community.

I am trying to use it since some days now and got a first genome annotation only with CDS. I restarted from beginning with UTR option on but braker failed and I am now trying to restart it but it doesn't work and I get this error message:
########################################################################
# Mon Jun 22 15:09:53 2020: ERROR: in file /usr/product/bioinfo/BRAKER/2.1.5/scripts/braker.pl at line 1315
Config file /usr/users/ncervea/augustus_config_dir/species/Lstagnalis_single-paired_second_start/Lstagnalis_single-paired_second_start_utr_probs.pbl for species Lstagnalis_single-paired_second_start does not exist!
########################################################################

Is there any way to generate the missing file in order that I restart braker? This would save me a lot of time.

In order to firstly start the run I adapted the test6.sh to my dataset and to restart I used the test6_restart3.sh but got the above error message.

Thanks a lot in advance for your help,
Best regards,

Nicolas

**Comment by KatharinaHoff** [comment]
I am sorry. This is a bug. Line numbers have changed for sure since the issue opened. It is not our priority to fix re-running failed UTR jobs, at the moment. Generally, I recommend not to use the UTR option until we have fixed a couple of other problems on that end. Timeline unsure.
