### ISSUE TITLE
generate different annotation of test3.sh

### ISSUE THREAD

**Issue by zhanghaoipp** [Gaius-Augustus/BRAKER#235]
I installed braker2 by conda and replaced the filterGenesIn_mRNAname.pl file in env/braker2/bin by the one clone by github to resolve the problem of empty train.g.gb. Then I download the example and run test3.sh (add --cores 30). But when I compared the generated braker.gtf file with the one in results/test3 folder, I found lots of differences, like the pictures below. Is it due to different version of any software? The log files attached. In the pictures, braker1.gtf is the example provided and braker2.gtf is generated by my run.
[test3.log](https://github.com/Gaius-Augustus/BRAKER/files/4872098/test3.log)
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/4872102/braker.log)

![2](https://user-images.githubusercontent.com/15721672/86504807-b9303880-bdef-11ea-9258-944b0e4baede.jpg)
![1](https://user-images.githubusercontent.com/15721672/86504809-bcc3bf80-bdef-11ea-982a-97b35dde6498.jpg)

**Comment by tomasbruna** [comment]
Hello @zhanghaoipp,

the problem is most likely on our side, the test3.sh is currently not really up-to-date with the newest version of BRAKER. I am working on a fix.

Tomas

**Comment by tomasbruna** [comment]
Hello @zhanghaoipp,

please try to run the current `test3.sh`, there should not be many differences now.

Tomas

**Comment by zhanghaoipp** [comment]
> Hello @zhanghaoipp,
> 
> please try to run the current `test3.sh`, there should not be many differences now.
> 
> Tomas

Thank you @tomasbruna ! Could you tell me which files you update? I used the conda version, I do not know which files should be replaced.

**Comment by zhanghaoipp** [comment]
It seems you update the braker.pl and example folder.

**Comment by tomasbruna** [comment]
Hello @zhanghaoipp,

correct, everything in the `example` folder needs to be updated. Also, update all scripts in the `scripts` folder (https://github.com/Gaius-Augustus/BRAKER/tree/master/scripts). Some of the scripts are completely new, not present in the conda version.

Make sure to get the latest ProtHint, version v2.5.0, from this link https://github.com/gatech-genemark/ProtHint/releases/tag/v2.5.0. BRAKER will warn you and exit if you are not using this ProtHint version.

Tomas

**Comment by zhanghaoipp** [comment]
> Hello @zhanghaoipp,
> 
> correct, everything in the `example` folder needs to be updated. Also, update all scripts in the `scripts` folder (https://github.com/Gaius-Augustus/BRAKER/tree/master/scripts). Some of the scripts are completely new, not present in the conda version.
> 
> Make sure to get the latest ProtHint, version v2.5.0, from this link https://github.com/gatech-genemark/ProtHint/releases/tag/v2.5.0. BRAKER will warn you and exit if you are not using this ProtHint version.
> 
> Tomas

Thank you! It seems I also need to update augustus from 3.3 to 3.4

**Comment by tomasbruna** [comment]
Yes, it is best to get the latest AUGUSTUS, especially the scripts in https://github.com/Gaius-Augustus/Augustus/tree/master/scripts folder.
