### ISSUE TITLE
The output gff didn't contain any introns.

### ISSUE THREAD

**Issue by wangxinbio** [Gaius-Augustus/BRAKER#24]
The output gff didn't contain any introns. It is abnormal for my data. What is the reasons for it ?
![image](https://user-images.githubusercontent.com/12146966/54310353-92217800-45a8-11e9-8bfe-682e8766beaa.png)

**Comment by KatharinaHoff** [comment]
What kind of species did you apply BRAKER to? With or without evidence? If
with evidence, how many introns were in the evidence? How many with high
multiplicity?

**Comment by wangxinbio** [comment]
@KatharinaHoff  My command is 
braker.pl --gff3--genome=FINAL.fasta --bam=RNA.sort.bam
I also found a abnormal. 
Error rate of missing stop codon is 916.

Why the rate is more than 1 ?

**Comment by KatharinaHoff** [comment]
1) What kind of species did you apply BRAKER to?

2) How many introns were in the evidence? 

3) How many with high multiplicity?

4) How many training genes are in train.gb?

**Comment by wangxinbio** [comment]
@KatharinaHoff  
1. a wild tomato
2. 243134 in the hintsfile.gff
3.How can I get this number ?
4. 927 genes in the good/train.gb.

**Comment by KatharinaHoff** [comment]
No, that does not sound ok or normal. A tomato should definitely have genes with introns. 
(You can open the hintsfile and check in the last column whether the mult=INT has high numerical values; GeneMark will ignore introns with values <10... but BRAKER should also issue a warning if you have too fee of these introns.)

BRAKER adjusts the stopCodonExcludedFromCDS parameters, automatically. I am therefore surprised to see that most of your genes have no stop codon. Is it possible that you are trying to run BRAKER on a highly fragmented assembly that consists of a large number of short contigs?

We routinely run BRAKER on Solanum lycopersicum (with various RNA-Seq data sets). For example, I predicted genes with 207308 introns in that genome, using the current BRAKER and GeneMark releases.

**Comment by wangxinbio** [comment]
Thanks. The most hintsfile mult=INT has a value > 10. Yes. The contig is not very long.

**Comment by KatharinaHoff** [comment]
From your screenshot, it looks like a 5-Million bp scaffold. That should be long enough... is it fragmented inside the scaffold, i.e. are there lots of stretches of the letter N?

**Comment by KatharinaHoff** [comment]
Since it is a tomato that you are working with, why don't you try mapping the tomato proteins (e.g. from RefSeq) against the scaffold with GenomeThreader? GenomeThreader has a high specificity and is reasonably fast. You can do it with or without BRAKER. If you do it with BRAKER, AUGUSTUS will be trained on the GenomeThreader models.

**Comment by wangxinbio** [comment]
@KatharinaHoff  The draft genome is contigs and no N in it. I don't know why I got an abnormal result. The RNA-seq is paired-end and I used hisat2 to align it to the draft genome.

**Comment by KatharinaHoff** [comment]
The data situation sounds ok, but it is obviously not working. As I said before: try mapping the proteins. See whether that gives you better results. 

If you don't want to spend the time on downloading and mapping the tomato proteins, you can also apply AUGUSTUS with the existing tomato parameter set within BRAKER (there is an example call in the documentation).

**Comment by wangxinbio** [comment]
@KatharinaHoff  Thanks ver much. I will try.

**Comment by wangxinbio** [comment]
@KatharinaHoff Thanks very much. I will try.
