### ISSUE TITLE
50% of seemingly incorrect ab initio gene models in ep, et, and etp modes 

### ISSUE THREAD

**Issue by pi3rrr3** [Gaius-Augustus/BRAKER#242]
Hello,

I have assembled an ant genome using PacBio data (270Mb, ~3,000 contigs, N50: 1Mb). The assembly has been polished with both PacBio and Illumina data, and anchored onto the pseudo-chromosomal assembly of a species from the same genus. Genome Busco v4 is fairly good: C:98.5%[S:97.9%,D:0.6%],F:0.4%,M:1.1%,n:5991.
I have called and masked repeats with RepeatModeler2 and RepeatMasker, respectively, masking 31% of the genome. 
I am now annotating the softmasked genome with Braker2, using 50M RNAseq reads (9 different libraries subsampled and pooled together, aligned against an hard masked genome and removing secondary alignments) and the odb10 Arthropoda set (170 species, including 40 of the same order and 17 of the same family).

I am using the latest Braker2 version from GitHub. For Augustus, I unfortunately cannot install it straight from GitHub on the local cluster, so I use the latest conda version instead (3.3.3). My command for the etp mode is as follows:

	braker.pl --verbosity=3 --etpmode --softmasking --gff3 --cores 20 \
  		--genome=my_softmasked_genome.fa \
  		--prot_seq=my_proteins.fasta --prg=ph \
  		--bam=my_rnaseq_primary.bam \
  		--workingdir=my_wd

et and ep modes give ~34k genes, while etp mode gives ~30k genes, always with _mean_ gene lengths around 3kb. Busco runs on the longest isoforms give the following: 

	ep mode: 	C:95.6%[S:94.9%,D:0.7%],F:2.3%,M:2.1%,n:5991
	et mode: 	C:95.5%[S:94.8%,D:0.7%],F:2.0%,M:2.5%,n:5991
	etp mode: 	C:97.4%[S:96.8%,D:0.6%],F:1.4%,M:1.2%,n:5991

It looks very good, there is a clear gain from the etp mode, but ant genomes sequenced so far have usually between 14 and 18k genes, while I have 30k in etp mode...

Following #65 , and considering only the output of the etp mode, blasting predicted proteins against themselves doesn’t suggest insufficient TE masking. However, 14k genes (over 30k) have absolutely no hint (from `hintsfile.gff`), and their median length is 512bp, whereas the remaining 16k (with at least one hint) have a median size of 2.5kb. If I am not mistaken, _ab initio_ predictions are expected from Augustus despite providing hints, but I wonder whether something might be wrong with the training in my case?

While this is overly conservative, I can remove the 14k genes with no RNAseq/protein support and rerun Busco, to see the value added by these short genes:

	etp mode - all models (same as above): 			C:97.4%[S:96.8%,D:0.6%],F:1.4%,M:1.2%,n:5991
	etp mode - only models supported by evidence:		C:97.3%[S:96.7%,D:0.6%],F:1.3%,M:1.4%,n:5991

Of course I am missing a few "real" genes, but 1/ statistics are quite comparable to me and 2/ the total gene count is then as expected (which makes me feel good, which is also important).
However, if it is not too much of a hassle, I'd rather try and keep these "real" genes, and potentially refine my Braker run. I would also like to understand what is going on! Is there a way to tweak Augustus so that predictions are more robust in my case? If not I guess I can blast the 14k genes and keep the "good looking" ones only.

In any case, thanks for the wonderful tool!

Pierre

**Comment by tomasbruna** [comment]
Hello Pierre,

thank you for the extensive report.

this is, unfortunately, a fairly normal behavior. I think the training of AUGUSTUS itself is fine in your case, there is not much you can do to improve the training. Within BRAKER, the short, unsupported genes are already excluded from the AUGUSTUS training set.

Short, purely ab initio false positives are inevitable with increasing size of intergenic regions, even with good masking. There are many tweaks that can be done to AUGUSTUS to predict fewer unreliable genes (impose a limit on minimum gene length without external support, decrease the probability of purely ab initio genes, etc.) but all such tweaks are pretty much the same as filtering out short, unsupported predictions.

We will take a look into automating the filtering process. It definitely makes sense to flag short unsupported genes, highly repeated genes, etc., and report gene sets with various degrees of confidence.

For your particular case, since you already did this filtering, I can recommend doing a functional analysis of the unreliable genes and keeping the ones that have a putative function assigned (with some good confidence).

Best,
Tomas

**Comment by pi3rrr3** [comment]
Dear Tomas,

Many thanks for your answer! I would be helpful to flag these unsupported genes, indeed - the user could then look at them in more detail and decide whether to keep them or not. 

In my case, I have blasted the 14k predicted proteins without any hint against uniprot and got hits for 2.4k of them. After filtering, I could recover 1.6k additional proteins (including all missing BUSCOs), leading to 17k "good" predictions (from the initial 30k), in the same ballpark as the other ant genomes sequenced so far!

I am now using [EnTAP](https://entap.readthedocs.io/en/latest/index.html) for the functional annotation part, feeding in all Braker2's protein sequences. I'll see how their filtering approach compares to my blast results.

Best,
Pierre

**Comment by longzhangnation** [comment]
Hi  @pi3rrr3 ,
  I met the same situation as you . I get a lot more genes than expected , and I want to filter these low quality predictions . I am wondering how you find the unsupported genes from `hintsfile.gff` . Let me tell you how I finish it . First I got the braker2 output file using eptmode . Then I use `awk` to extract the first , forth and fifth line of the `hintsfile.gff` to file1 . Similarly , I did the same to the `augustus.hints.gff3` ,and output it to file2 . After that I `grep file1 file2  `  , and  from the last column of the greping result , I  know which gene could be supported . Do you think I did the right ?

**Comment by pi3rrr3** [comment]
Hi @longzhangnation ,

Based on my data and assuming you do `grep -f`, this may not be sufficient: you will only pick start/stop codons by comparing coordinates straight from the gff files, as `hintsfile.gff` contains mostly intron coordinates while `augustus.hints.gff3` contains CDS coordinates. I would assume any correct gene model without proper start/stop codon may be removed from your final gene list.

What I did instead was to subset gene entries in `augustus.hints.gff3`, and for each of them collect all entries from `hintsfile.gff` falling within each gene. I could then compile the number of hints per gene and their source (RNAseq, protein data or both, based on the second column of `hintsfile.gff`). I just filtered based on the presence/absence of hints (possibly wrong gene models in my case had no hint and a much smaller size, which I also looked at), and blasted all genes without hints against uniprot to recover gene models which did not have any hint from Braker2, but which seemed okay to me. 

Note there may be better / simpler / more elegant options, like functional analysis, as mentioned earlier.

**Comment by longzhangnation** [comment]
So if I understand correctly , you got the genes locus from  augustus.hint.gff3 , and obtain the coordinates in from hintsfile.gff . Then you chekc if the coordinates in the hintsfile .gff fall in the area of gene locus  . If so , then the gene is supported , else , it is not supported by any hints . Am I right ?

**Comment by pi3rrr3** [comment]
Yes. For a subset of genes I manually checked that intron and CDS coordinates matched, which was the case. Nested gene structures could be problematic but they don't seem so frequent in my data.

**Comment by longzhangnation** [comment]
Hi @pi3rrr3 
  Sorry for my late reply and bothering you again  . According to you description , I think it may be better for my data . But I can not compile the number of supported hints  automatically . Do you have a script to accomplish it ? Would you mind sharing it ?
