### ISSUE TITLE
No augustus.gtf output

### ISSUE THREAD

**Issue by brkldj** [Gaius-Augustus/BRAKER#249]
Hi,

I'm trying to run braker with only RNA-seq, like this:
`braker.pl --genome=genome.fasta --species=speciesX --bam RNAseqdata.bam --cores=8 --GENEMARK_PATH=[path] --AUGUSTUS_CONFIG_PATH=[path] --AUGUSTUS_BIN_PATH=[path] --AUGUSTUS_SCRIPTS_PATH=[path]`
It runs for about a day and produces `braker.gtf`, among others, but no `augustus.gtf`. There are no error messages that would suggest something went wrong, and running this command on the test data also does not produce an `augutus.gtf` file. According to [Figure 2](https://github.com/Gaius-Augustus/BRAKER#overview-of-modes-for-running-braker) I should expect one. An [issue which sounds similar](https://github.com/Gaius-Augustus/BRAKER/issues/205) does not solve my problem (i.e. starting with a new species name does not change the outcome).
I'm running braker v. 2.1.5 and Augustus v. 3.3.3 recently cloned from github. Any suggestions are greatly appreciated.

**Comment by tomasbruna** [comment]
Hello @brkldj,

do you see a file name `augustus.hints.gtf`? Depending on the used options, there can be different results in the form of `augustus.*.gtf`. I see why the figure caused confusion, we will update it.

For more details about different BRAKER outputs, see https://github.com/Gaius-Augustus/BRAKER#output-of-braker

Best,
Tomas

**Comment by brkldj** [comment]
Hi Tomas,

thank you! There is indeed an `augustus.hints.gtf`. Is this the final output of augustus that should be provided to evm? If yes, I'm curious why is it called "hints"? 

Cheers,
Lidija

**Comment by tomasbruna** [comment]
Hello Lidija,

yes, you can use this as the final output.

The "hints" in the name signify that AUGUSTUS utilized hints during the prediction step. BRAKER can also produce an output called `augustus.ab_initio.gtf`. This output is generally less accurate since it only uses hints when training the AUGUSTUS model.

More detailed description of these files is here https://github.com/Gaius-Augustus/BRAKER#output-of-braker

Best,
Tomas

**Comment by brkldj** [comment]
Hi Tomas,

excellent, thank you! Knowing this, the [output](https://github.com/Gaius-Augustus/BRAKER#output-of-braker) section also makes sense.
I'll leave the issue open in case you're using it as a reminder to update the figure. But my question is resolved.

Cheers,
Lidija
