### ISSUE TITLE
Replace BLAST by DIAMOND

### ISSUE THREAD

**Issue by KatharinaHoff** [Gaius-Augustus/BRAKER#25]
Replace BLAST by DIAMOND for aa2nonred.pl (originally an AUGUSTUS script). Intention: speed up BRAKER.

**Comment by MarioStanke** [comment]
Why not an new alternative and default rather than a replacement?

**Comment by KatharinaHoff** [comment]
Will keep backwards compatibility.

**Comment by KatharinaHoff** [comment]
aa2nonred.pl has been extended to use DIAMOND (hosted in AUGUSTUS repository, commit https://github.com/Gaius-Augustus/Augustus/commit/39e8fb03edce315b4cb642c2be24e97c06210df2).

With a test set of 947 genes, BLAST needed 13 minutes, 36 seconds. With DIAMOND, we now need only 2.2 seconds. Results are highly similar but not identical. I think we can neglect the differences and proceed with using DIAMOND. (On the test set, exactly one gene was treated differently.)

**Comment by KatharinaHoff** [comment]
Added DIAMOND to BRAKER for aa2nonred.pl in commit https://github.com/Gaius-Augustus/BRAKER/commit/e117150b8ad66ecf7cd5828c7f7fe476a4a8c191
