### ISSUE TITLE
braker.pl can't find PROTHINT_PATH()

### ISSUE THREAD

**Issue by qiyubio** [Gaius-Augustus/BRAKER#250]
Hi there,

There is a bug on barker.pl. I clone the BRAKER on Monday, and run the test1 code:
"braker.pl --genome=../genome.fa --bam=../RNAseq.bam --softmasking --workingdir=$wd --cores 8 --gm_max_intergenic 10000"

It failed and give error:
# ERROR: in file /opt/BRAKER/scripts/braker.pl at line 3774
# Could not run ProtHint. Please check ProtHint installation by running the test located in /example folder.
Although I setted up the path for ProtHint:
echo $PROTHINT_PATH
/opt/ProtHint/bin/

I patched the code by adding "set PROTHINT_PATH()"  (line 856 of braker.pl) outside of a loop, which seems work. But you might have better idea and update the code to fix it. 

Please check. 
Thanks.
Qi

**Comment by tomasbruna** [comment]
Hi Qi,

thank you so much for spotting this!

The error occurred because ProtHint is not set when proteins are not used. The check for ProtHint's executability needs to be skipped in such a case.

Thanks again,
Tomas

**Comment by qiyubio** [comment]
Hi Tomas,

Works like a charm. Thanks for that quick fix.

Bests,
Qi
