### ISSUE TITLE
the genetic code table parameters available?

### ISSUE THREAD

**Issue by 18616831168** [Gaius-Augustus/BRAKER#252]
I am currently working on annotation of protozoan genomes. I see that there is a corresponding parameter "--translation_table=INT" in the script "braker.pl", but some notes indicate that it is currently unavailable, is it true? Is there any way to help? Thank you a lot!

**Comment by 18616831168** [comment]
The command I need to execute is "braker.pl --translation_table= 6".

**Comment by KatharinaHoff** [comment]
This will currently not work ok with BRAKER if GeneMark is used.

Katharina

**Comment by SebastianBechara** [comment]
Hi,
I'm also trying to use braker.pl --translation_table=6 to annotate a ciliate genome. Is it now supported with the latest version? If not are you able to give a rough approximation when it will be? Thank you very much!

**Comment by KatharinaHoff** [comment]
It’s currently not supported yet. No timeline estimate yet.
