### ISSUE TITLE
singularity template for BRAKER

### ISSUE THREAD

**Issue by qiyubio** [Gaius-Augustus/BRAKER#253]
Hi, I build a container for BRAKER, maybe it's worth to share with others who plan to install BRAKER on cluster. Since def file are not allowed to be attached, I host it on my GitHub for now. 
https://github.com/qiyubio/BRAKER_singularity/blob/master/braker.def

Here are some notes:
1. The GeneMark package has to be downloaded before building container.
2. Since BRAKER need to write to AUGUSTUS_CONFIG, it has to be located outside of container. The default setting in this container is AUGUSTUS_CONFIG_PATH=~/Augustus/config/. This means a manually setup of ~/Augustus/config/ is necessary.
3. Please create links inside of container according to your cluster.

Cheers,
Qi

**Comment by KatharinaHoff** [comment]
Thanks a lot for sharing! That's really nice of you!

Katharina

**Comment by desmodus1984** [comment]
Hi @qiyubio ,

Does that container come with Augustus?
I am trying to install Augustus and I have a fatal error
../include/randseqaccess.hh:21:10: fatal error: mysql++/mysql++.h: No such file or directory
#include <mysql++.h>
^
compilation terminated.
Makefile:61: recipe for target 'randseqaccess.o' failed
make: *** [randseqaccess.o] Error 1

during the installation with "make" - hopefully I am doing the right thing.
the only thing that I found is that I need to install  libmysql++-dev but I need admin priviliges, which I don't.

Could you please make a gzip out of Augustus config folder and share it to use it with the container?
That would be awesome!

Thank you

**Comment by RicPic95** [comment]
Hi @qiyubio,

I was able to build the singularity image, thank you!
I am now trying to run some example to see if it works, but it comes out this error:
`ERROR in file /opt/BRAKER/scripts/braker.pl at line 5061`
`Could not close output fasta file /opt/BRAKER/example/braker/genome.fa!`
Could you please help me solving this problem?

Thank you!

**Comment by KatharinaHoff** [comment]
We are now providing a BRAKER docker container that can be used in sigularity. Prerequisite is that you have GeneMark installed  with the license key inside your home directory on the host machine.

```
singularity build braker.sif docker://katharinahoff/braker-notebook:devel
```

```
singularity exec braker.sif braker.pl
```

We hope that in the future we will be able to provide a docker container that contains GeneMark.
