### ISSUE TITLE
BRAKER run fails in "fix_in_frame_stop_codon_genes.py"

### ISSUE THREAD

**Issue by IF76** [Gaius-Augustus/BRAKER#254]
Hi,

I have tried to execute latest github BRAKER/AUGUSTUS pipeline on with RNA-Seq data (including latest versions of all software dependencies such as GeneMark, Diamond, ProtHint etc.) multiple times, and each time the run would brake at
`fixing AUGUSTUS genes with in frame stop codons...` step:
```
/usr/bin/python3 /root/Augustus/scripts/fix_in_frame_stop_codon_genes.py -g /root/working/rnaonly/genome.fa -t /root/working/rnaonly/augustus.hints.gtf -b /root/working/rnaonly/bad_genes.lst -o augustus.hints_fix_ifs_ -s Sp_1 -m on --UTR off --print_utr off -a /root/Augustus/bin/../config -C /usr/bin -A /root/Augustus/bin/../config/../bin -S /root/Augustus/bin/../config/../scripts -H /root/working/rnaonly/hintsfile.gff -e /root/BRAKER/scripts/cfg/rnaseq.cfg  > /root/working/rnaonly/fix_in_frame_stop_codon_genes_augustus.hints.log 2> /root/working/rnaonly/errors/fix_in_frame_stop_codon_genes_augustus.hints.err
```

Upon inspecting `fix_in_frame_stop_codon_genes_augustus.hints.err` error log, the content would be identical for every failed run:
```
Traceback (most recent call last):
  File "/root/Augustus/scripts/fix_in_frame_stop_codon_genes.py", line 737, in <module>
    for ifs_line in ifs_handle:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 168: ordinal not in range(128)
```
If `--skip_fixing_broken_genes` option was used, same run would finish without problems.

Furthermore, I tried to scan all BRAKER generated intermediate files for `Ã` character ( hexadecimal `0xc3` ) but could not find any.

The draft genome I work with is *soft-masked* and highly continuous consisting of contigs and only four scaffolds (each containing a single stretch of 100 **N**s).

Any help would be much appreciated.

Thank you,

I.F.

**Comment by tomasbruna** [comment]
Hi @IF76,

this issue has been successfully resolved before. Take a look at https://github.com/Gaius-Augustus/BRAKER/issues/222 for one solution. Another fix was proposed here: https://github.com/Gaius-Augustus/Augustus/issues/148.

Best,
Tomas

**Comment by IF76** [comment]
Hi @tomasbruna,

Thank you for the quick response.

Yes, the problem was non-existing UTF-8 environment. I was able to successfully resolve the issue.

Regards,

I.F.
