### ISSUE TITLE
can not install python3 module re in a conda environment

### ISSUE THREAD

**Issue by wuxiaopei0509** [Gaius-Augustus/BRAKER#256]
Dear.
I use conda to install perl and python modules required by BRAKER2, However the python3 module can not be installed by any solutions. When I run, it happens:
Could not find python3 module re:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/miniconda2/envs/braker2/lib/python3.8/re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
How can I install the module?
Thank you!

**Comment by KatharinaHoff** [comment]
re is usually part of python, already.
