### ISSUE TITLE
protein output braker

### ISSUE THREAD

**Issue by giulialopatriello95** [Gaius-Augustus/BRAKER#262]
Hi there!

I was wondering if there is a fast way to ouput protein sequences from the file braker.gtf.
I am using the file "augustus.hints.aa" but I would like to retrieve also the genemark predicted proteins.

Best regards,
Giulia

**Comment by KatharinaHoff** [comment]
You can use this script:
https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/getAnnoFastaFromJoingenes.py

Katharina
