### ISSUE TITLE
brake2 finishing without predictions on the example files

### ISSUE THREAD

**Issue by DEsalasL** [Gaius-Augustus/BRAKER#265]
Hi, I'm trying to use the example files as shown below, but braker2 stops because the training file comes out empty. is that expected? if not, what could be wrong? please see the info below:

braker.pl --hints=RNAseq.hints --species=ANY  --genome=genome.fa --softmasking --cores=10

# Thu Sep 10 13:52:04 2020: ERROR: in file /scratch2/software/anaconda/envs/braker2/bin/braker.pl at line 7099
Training gene file in genbank format /misc/scratch4/xxx/braker2_test/braker/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.

This is the tail of the braker log file:
Thu Sep 10 12:52:24 2020: Genbank format file /tmp/build/braker2_test/braker/train.f.gb contains 0 genes.

**Comment by tomasbruna** [comment]
Hello @DEsalasL,

are you running the latest versions of BRAKER and AUGUSTUS (cloned from GitHub's master branch)?

This error has been fixed in recent updates.

Tomas

**Comment by DEsalasL** [comment]
Hi Tomas,
I updated the software as you suggested and the problem went away.  Many thanks for your prompt reply.
D
