### ISSUE TITLE
No redicted GeneMark genes classified as "good". 

### ISSUE THREAD

**Issue by cdmmoeller** [Gaius-Augustus/BRAKER#266]
Hi,

BRAKER is running fine until AUGUSTUS, which prints the following: 
```
#  Tue Sep  8 21:10:28 2020: concatenating good and downsampled GeneMark training genes to /home/prbl/analysis/BRAKER_GENEMark_runs/Ascaber64k_BRAKER_080920/braker/good_genes.lst.
cat /home/prbl/analysis/BRAKER_GENEMark_runs/Ascaber64k_BRAKER_080920/braker/GeneMark-ET/genemark.d.gtf > /home/prbl/analysis/BRAKER_GENEMark_runs/Ascaber64k_BRAKER_080920/braker/good_genes.lst
# Tue Sep  8 21:10:28 2020 ERROR: file /home/prbl/analysis/BRAKER_GENEMark_runs/Ascaber64k_BRAKER_080920/braker/good_genes.lst contains no good training genes. This means that with RNA-Seq data, there was insufficient coverage of introns; or with protein data, there was insufficient support from protein alignments/GaTech protein mapping pipeline hints; or without any evidence, there  were only very short genes. In most cases, you will see  this happening if BRAKER was executed with some kind of  extrinsic evidence (either/or RNA-Seq/protein). You can then  try to re-run BRAKER without any evidence for training  and later use the such trained AUGUSTUS parameters for a  BRAKER run without any training and the available evidence. Accuracy of training without any evidence is lower than with  good evidence. 
```
If I understand correctly, the initial gene predictions by GeneMark have been classified into "good" and "bad" genes according to the coverage of their constituent introns,  and not enough have been classified as "good" for AUGUSTUS training. Here's **filterGenemark.stdout**
```
Number of cds hints is 0
Average gene length: 3278
Average number of introns: 5.08570653647952
Good gene rate: 0
Number of genes: 32215
Number of complete genes: 29496
Number of good genes: 0
Number of one-exon-genes: 2612
Number of bad genes: 29746
Good intron rate: 0
One exon gene rate (of all genes): 0.0810802421232345
```
So I checked the number of introns in genemark.gtf to be 133368. Of those, 57352 have a coverage >10. This seems contradictory to the error message about not enough introns having a sufficient coverage score. This leads me to believe there might another issue that I'm missing.

I'm linking **braker.log** and **GeneMark-ET.stdout** in case they can be of any use 
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/5208027/braker.log) 
[GeneMark-ET.stdout.txt](https://github.com/Gaius-Augustus/BRAKER/files/5208033/GeneMark-ET.stdout.txt)

Some background info:

**Genome:** Plant genome from Compositae family. Initial asseembly is 6.5Gb (N50=64kb), selected contigs >64kb for a total of 29k contigs.

**Masking:** Genome was softmaksed using custom library generated by RepeatModeler, and masked with RepeatMasker. Additional tandem repeat masking using TRF following (https://www.biorxiv.org/content/10.1101/2020.08.10.245134v1.supplementary-material). 

**External evidence:** 6 RNA-seq libraries of 25M paired-end reads mapped to selected contigs (unmasked) using HISAT2. Alignment rate of ~30%.

**Command:** 
```
/home/prbl/software/BRAKER-2.1.5/scripts/braker.pl --cores=24 --species=Ascaber64k_BRAKER_080920 --softmasking --genome=/home/prbl/data/genomes/Ascaber/assembly_new/Ascaber_64k.fa.combined.masked --bam=/home/prbl/analysis/alignment/Ascaber/L_64k.sorted.bam,/home/prbl/analysis/alignment/Ascaber/P_64k.sorted.bam,/home/prbl/analysis/alignment/Ascaber/R_64k.sorted.bam,/home/prbl/analysis/alignment/Ascaber/S_64k.sorted.bam,/home/prbl/analysis/alignment/Ascaber/UF_64k.sorted.bam,/home/prbl/analysis/alignment/Ascaber/W_64k.sorted.bam
```

Best,
Christian

**Comment by tomasbruna** [comment]
Hello Christian,

can you upload the `genemark.gtf` and `hintsfile.gff`? I want to check what's happening with the supported genes.

Thanks!
Tomas

**Comment by cdmmoeller** [comment]
Hi Tomas,

Thanks for taking a look at this. Here are the files:

[genemark.gtf.gz](https://github.com/Gaius-Augustus/BRAKER/files/5253064/genemark.gtf.gz)
[hintsfile.gff.gz](https://github.com/Gaius-Augustus/BRAKER/files/5253065/hintsfile.gff.gz)

Best,
Christian

**Comment by tomasbruna** [comment]
Hello Christian,

I took a look at the files and only 12 introns predicted in `genemark.gtf` are present in `hintsfile.gff`, even though there are enough introns with high coverage in `hintsfile.gff`.

This explains the problem.

From the logs, I noticed you are not running the latest version of BRAKER. Can you try cloning the latest BRAKER from master branch? You can test if everything works in the latest version by running [test1.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test1.sh). There were some changes in the way how GeneMark-ET is called and its result passed to AUGUSTUS.

I do not expect the update will fully solve the issue (the program might finish but the result will still be bad) but I want to get the run with the latest code version before consulting this problem with other BRAKER developers.

Thank you for your continued patience in trying to make this work, I'm sure finding out what's causing this problem will greatly benefit GeneMark and BRAKER.

Best,
Tomas

**Comment by cdmmoeller** [comment]
Hi Tomas,

After cloning the latest BRAKER, the run now finishes.

Some basic stats about augustus.hints.gtf: Number of predicted genes: 20414. Mean number of exons pr. gene: 7.6, mean exon length: 367 bp, mean intron length: 163.

Due to the size of the output files I am unable to share them here. If you are still interested in seeing them, could I perhaps send them to you by email? 

Best,
Christian

**Comment by tomasbruna** [comment]
Hello Christian,

sorry for the late answer. Yes, please send the files (bruna.tomas@gmail.com), I will take a look.

If the files are too large to send by email, I will create a Dropbox file request where you can upload the results.

Best,
Tomas

**Comment by KatharinaHoff** [comment]
I will close this issue because I assume it was taken to email.
