### ISSUE TITLE
More than one bam inputs but only one was used?

### ISSUE THREAD

**Issue by PeiwenLi** [Gaius-Augustus/BRAKER#267]
Hi!
I am running BRAKER2 with RNA-seq data and protein data (i.e. the --etpmode). I included more than one .bam file as inputs. However, when I check the braker.log file, I found that only **ONE** .bam file was called in the 'PROCESSING HINTS' step (line 64-73 in the file below)? Please find the command I used in the log file below:
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/5210129/braker.log)
Did I do something wrong? 

P.S. The program is still running, so the attached braker.log file is incomplete.

Thanks a lot.
Peiwen

**Comment by tomasbruna** [comment]
Hello @PeiwenLi,

remove the space after commas separating your bam files, i.e. use

    --bam file1.bam,file2.bam
instead of

    --bam file1.bam, file2.bam

With the space, the `file2.bam` can be interpreted as a separate argument, not as a part of the bam input.

Tomas
