### ISSUE TITLE
Filtering hints file?

### ISSUE THREAD

**Issue by apredeus** [Gaius-Augustus/BRAKER#268]
Hello, 

I have previously obtained annotations using Braker2, using only RNA-seq on a softmasked genome. 

The results are questionable - with lots of fragmented gene models being the main problem. 

I've discovered that many hints generated from BAM file have very low support (multiplicity of 1), while some have huge coverage. Would it make sense to filter the hints file to only keep splice sites with certain minimal coverage? Does Braker2 already discriminates these based on coverage? 

Also, I see from logs that about 1,000 GeneMark predicted genes were deemed "good". Is there a way to check what these genes are? 

Thank you.

**Comment by tomasbruna** [comment]
Hello,

BRAKER already assigns more weight to hints with high coverage compared to the ones with low coverage. However, if you have a lot of RNA-Seq data, it might be helpful to filter out the weakest hints. If you are also using protein evidence, I would recommend doing that.

Also, there are more details in https://github.com/Gaius-Augustus/BRAKER/issues/242 about the filtering of a BRAKER result.

The "good genes" from GeneMark will be merged with the final output of AUGUSTUS in the `braker.gtf` file.

Best,
Tomas

**Comment by apredeus** [comment]
Brilliant, thank you very much!
