### ISSUE TITLE
bam file sorting

### ISSUE THREAD

**Issue by rob123king** [Gaius-Augustus/BRAKER#27]
I get this error from bam2hints but it's coordinate sorted by samtools sort defaults. "BAM file MUST be sorted by target sequence names" any ideas why this is, should be coordinate sorted right?

**Comment by KatharinaHoff** [comment]
Hi Robert,
no, the file must also be target sequence name sorted (it is samtools sort
-n).
Best,
Katharina

**Comment by rob123king** [comment]
just samtools sort without any other options, ok i'll do samtools sort -n which is read sorted rather than coordinate. Target sequence sounds confusing to me its sort by read name rather than coordinate.

**Comment by KatharinaHoff** [comment]
Point taken, I have changed the error message in Augustus/auxprogs/bam2hints: https://github.com/Gaius-Augustus/Augustus/commit/5823599ce03c8d128305dc57bb00dff060046377

**Comment by rob123king** [comment]
thanks
