### ISSUE TITLE
gc_probability option for GeneMark

### ISSUE THREAD

**Issue by apredeus** [Gaius-Augustus/BRAKER#270]
Hello, 

I was wondering why is `--gc_probability` set to 0.001 by default? I just checked the latest human genome annotation (Gencode), and for ~ 361k unique introns present there, about 6,500 are GCAG and ~348k are GTAG - so, the frequency is 0.018. Similar estimates from ProtHint for another organism I'm working on resulted in a value of ~ 0.03. 

Is there a specific reason it's set so low? Thank you!

**Comment by tomasbruna** [comment]
Hello,

there is no specific reason for setting it to this exact value. In future development, we plan to estimate the probability automatically during training. For now, it is set to very low to be rather conservative in predicting the GC-AG introns.

Feel free to increase the probability if your geome shows evidence of more frequent GC-AG introns.

Best,
Tomas

**Comment by apredeus** [comment]
Thanks again! I'm curious as to whether it will make a difference. I'll let you know if I do the test.
