### ISSUE TITLE
Segmentation fault in prothint

### ISSUE THREAD

**Issue by lfaller-zymergen** [Gaius-Augustus/BRAKER#272]
Hello!

I got the following error while running braker.pl:

```
/opt/ProtHint/bin/spalnBatch.sh: line 61: 34816 Done                    "$binDir/../dependencies/spaln" $mode -LS -pw -S1 -O1 -l $alignmentLength "$nuc" "$prot" 2> /dev/null
     34817 Segmentation fault      | "$binDir/../dependencies/spaln_boundary_scorer" -o "${nuc}_${prot}" -w 10 -s "$binDir/../dependencies/blosum62.csv" -e $min_exon_score
```

I am running this on a computer with 48 CPUs and 140 GB of RAM. The input genome is 9.5 Megabases in size.

Do you think this kind of job requires more compute resources? 

Thanks!

**Comment by tomasbruna** [comment]
Hello,

your computer is more than adequate for the job, the issue must be something else.

Does the error occur in the beginning of protein alignment, or after completing several alignments? If it completes several alignments, there should be lines like this in the BRAKER stderr output:

```
[Tue Sep 22 20:37:27 2020] Enqueueing pair 0/132035 (0.0%)
[Tue Sep 22 20:37:27 2020] Enqueueing pair 133/132035 (0.1%)
[Tue Sep 22 20:37:27 2020] Enqueueing pair 265/132035 (0.2%)
[Tue Sep 22 20:37:28 2020] Enqueueing pair 397/132035 (0.3%)
...
```


I also wonder, does the program finish successfully when running on the example data provided in the repository? Specifically, did you try to run the [test2.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test2.sh)? More details about example inputs are [here](https://github.com/Gaius-Augustus/BRAKER#example-data).

Best,
Tomas

**Comment by lfaller-zymergen** [comment]
This is the only error message I can find in the logs and the program does finish successfully.

I've seen it pop up only once per braker job that I run. In the example below, the "enqueueing" step seems to have been about half-way done. I've also seen it at the 75% mark.

```
[Wed Sep 23 00:54:09 2020] Enqueueing pair 61105/108149 (56.5%). Est. time left: 00:32:48 (hh:mm:ss)
[Wed Sep 23 00:54:13 2020] Enqueueing pair 61213/108149 (56.6%). Est. time left: 00:32:43 (hh:mm:ss)
[Wed Sep 23 00:54:17 2020] Enqueueing pair 61321/108149 (56.7%). Est. time left: 00:32:38 (hh:mm:ss)
/opt/ProtHint/bin/spalnBatch.sh: line 61:  5668 Done                    "$binDir/../dependencies/spaln" $mode -LS -pw -S1 -O1 -l $alignmentLength "$nuc" "$prot" 2> /dev/null
      5669 Segmentation fault      | "$binDir/../dependencies/spaln_boundary_scorer" -o "${nuc}_${prot}" -w 10 -s "$binDir/../dependencies/blosum62.csv" -e $min_exon_score
[Wed Sep 23 00:54:22 2020] Enqueueing pair 61429/108149 (56.8%). Est. time left: 00:32:34 (hh:mm:ss)
[Wed Sep 23 00:54:26 2020] Enqueueing pair 61537/108149 (56.9%). Est. time left: 00:32:29 (hh:mm:ss)
[Wed Sep 23 00:54:31 2020] Enqueueing pair 61645/108149 (57.0%). Est. time left: 00:32:25 (hh:mm:ss)
[Wed Sep 23 00:54:35 2020] Enqueueing pair 61754/108149 (57.1%). Est. time left: 00:32:20 (hh:mm:ss)
```

I have been able to run `test2.sh` but I will dig out the logs once more to see if the same error message pops up there as well.

**Comment by tomasbruna** [comment]
Hello,

thanks for the clarification. In rare cases, Spaln (which is used inside ProtHint) crashes with a segmentation fault. These errors are very rare and usually hardware dependent, so they are hard to debug.

These errors only affect individual alignments, ProtHint continues normally after. In your case, only 1 out of 108149 alignments was affected, so there will be no noticeable effect on the final result.

I do not expect any errors like this in the `test2.sh` but please let me know if you see them.

Best,
Tomas
