### ISSUE TITLE
The hints file is empty. Maybe the genome and the RNA-seq file do not belong together

### ISSUE THREAD

**Issue by chilijuido23** [Gaius-Augustus/BRAKER#276]
Hello guys! when I try to run the example data test1,and the command like these: 
braker.pl --genome=genome.fa  --bam=RNAseq.bam --softmasking --workingdir=. --GENEMARK_PATH=../gmes_linux_64/  -AUGUSTUS_SCRIPTS_PATH=../augustus-3.3.3/script/ --AUGUSTUS_BIN_PATH=../augustus-3.3.3/bin/ --AUGUSTUS_CONFIG_PATH=../augustus-3.3.3/config/ 
Then it was nterrupted and the erros like that   ERROR: in file /home/juido/sofetware/BRAKER-master/scripts/braker.pl at line 5325
The hints file is empty. Maybe the genome and the RNA-seq file do not belong together
  I'll thank you all guys for this!

**Comment by tomasbruna** [comment]
Hello,

this issue should be resolved if you clone the latest BRAKER and AUGUSTUS from their master branches.

Let me know if that does not help (or if you are already using the latest code).

Best,
Tomas

**Comment by chilijuido23** [comment]
Thank you tomasbruna. Anaconda help me solved all the dependencies. I'm exhausted for the package dependencies.

**Comment by XK4959** [comment]
How can I solve it? I also encountered the same problem

**Comment by tomasbruna** [comment]
Hi @XK4959,

can you share the full `braker.log`? Also, are you working with the latest BRAKER (here from the master branch on GitHub)?

Tomas

**Comment by XK4959** [comment]
Hi，@tomasbruna，
Thank you, I have successfully solved the problem.
The cause of the problem is that there are spaces in my genome header, and the bam file used has only the first column of the header. After I deleted the last few columns of the genome header, the problem was solved successfully.
But I ran into other problems later:
1. The splain.gff file ran using the ep mode protein is empty.
2. The train.g.gb file ran by rna is empty.
I don't know how to solve these two problems.
I am sure that the data used is closely related, and no error was reported during the operation of the braker, but it was stopped in these two places.

**Comment by tomasbruna** [comment]
Hi @XK4959,

can you share the `braker.log` file? Maybe I can deduce the cause of this problem from there, let's start with that.

By the way, when you run the example tests (for example the [test3.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3.sh)), does BRAKER2 finish without issues?

Tomas

**Comment by XK4959** [comment]
Hi,@tomasbruna
The attached braker.ep.log is the log file generated by me running the protein and genome using the ep process, and the attachment braker.rna.log is the log file generated by me running the genome and transcriptome.
I haven't used the sample file to test, and I will test it later. I have used the genome to run the es process and the genome plus protein to run the gt process.
Thank you
Xinlong
[braker.rna.log](https://github.com/Gaius-Augustus/BRAKER/files/6113912/braker.rna.log)
[braker.ep.log](https://github.com/Gaius-Augustus/BRAKER/files/6113913/braker.ep.log)

**Comment by XK4959** [comment]
Attachment: Run file generated by running braker.ep.log

[nohup-ep.txt](https://github.com/Gaius-Augustus/BRAKER/files/6114041/nohup-ep.txt)

**Comment by tomasbruna** [comment]
Hello @XK4959,

in the log files, I see a couple of issues. First, it looks like you are using an older version of AUGUSTUS (Augustus-3.3.1-tag1). BRAKER2 is not compatible with this version, please update AUGUSTUS from https://github.com/Gaius-Augustus/Augustus. This is causing the `Genbank format file train.f.gb contains 0 genes` error.

The second error is probably related to an incorrect ProtHint installation. ProtHint is looking for a script in `/users/gaoxl/soft/gth-1.7.1-Linux_x86_64-64bit/bin/../dependencies/spaln_boundary_scorer` but it cannot find it. ProtHint won't work if you only copy the scripts from the `bin` folder to some location - it also needs the `dependencies` folder to be present in the same directory as `bin`. The easiest way to fix this is to download a fresh ProtHint from `https://github.com/gatech-genemark/ProtHint/releases/tag/v2.6.0`. Take a look at more details here https://github.com/Gaius-Augustus/BRAKER#prothint.

Finally, please update the BRAKER2 code from the master branch here on GitHub (if you have not already done so), many errors have been recently fixed.

Best,
Tomas

**Comment by XK4959** [comment]
Hi,@tomasbruna
Thank you very much,I think this will solve my problem.

Xinlong
