### ISSUE TITLE
Augustus accuracy for a new species

### ISSUE THREAD

**Issue by apredeus** [Gaius-Augustus/BRAKER#279]
Hello all, 

I'm not sure if this is a Braker or Augustus question, but I'll ask it here since Braker (2.1.5) is what I'm using for my annotation. 

I've tried several different approaches for my species (using RNA-seq hints, protein hints, or both), and in all cases the program seems to find quite a few "good" genes (e.g. my latest one: train.f.gb contains 3331 genes; train.ff.gb contains 3287 genes; train.fff.gb contains 3247 genes). However, Augustus accuracy seems pretty low both before and after training:

> The accuracy after initial training (no optimize_augustus.pl, no CRF) is 0.618446666666667
> The accuracy after training (after optimize_augustus.pl, no CRF) is 0.632733333333333

I've done a similar exercise in Drosophila genome, and Augustus seems to do much better (the accuracy is 0.87 before and 0.91 after). 

Any suggestions on how it can be improved? Is 0.65 a bad accuracy in general for Augustus after training? (I'm not sure how is it calculated). I'm getting quite a few fragmented genes, and that's the main thing I'm trying to fix. Thank you!

**Comment by KatharinaHoff** [comment]
It will not easy to improve this in any automated way.

The mentioned accuracy value is basically an average of gene, cds and nucleotide accuracy in the test set that was hold out from training. This number also must not be worrying if the resulting gene structures make sense in context with evidence. Please use a genome browser to visualize your data and check for quality control.
