### ISSUE TITLE
Failure during training

### ISSUE THREAD

**Issue by OnlyHigh** [Gaius-Augustus/BRAKER#28]
Hi, 
Running BRAKER2 I get the following error:

```
bio@biocomp04:~/Documents/Purpureocillium/March2019$ ~/apps/BRAKER-2.1.2/scripts/braker.pl  --genome=./working-genomes/361.fa --species=Purp --AUGUSTUS_CONFIG_PATH=/home/bio/apps/augustus-3.3.2/config/ --prot_seq=hints-annotation.faa --prg=gth --ALIGNMENT_TOOL_PATH=/home/bio/apps/gth-1.7.1-Linux_x86_64-64bit/bin --trainFromGth
# Wed Mar 27 20:01:51 2019: Logfile: /home/bio/Documents/Purpureocillium/March2019/braker/Purp/braker.log!
ERROR in file /home/bio/apps/BRAKER-2.1.2/scripts/braker.pl at line 5831
Failed to execute: /home/bio/apps/augustus-3.3.2/config/../bin/etraining --species=Purp --AUGUSTUS_CONFIG_PATH=/home/bio/apps/augustus-3.3.2/config /home/bio/Documents/Purpureocillium/March2019/braker/Purp/train.f.gb 1> /home/bio/Documents/Purpureocillium/March2019/braker/Purp/gbFilterEtraining.stdout 2>/home/bio/Documents/Purpureocillium/March2019/braker/Purp/errors/gbFilterEtraining.stderr
```

When I do: 
``` 
less /home/bio/Documents/Purpureocillium/March2019/braker/Purp/errors/gbFilterEtraining.stderr
```

I get: 
``` 
/home/bio/apps/augustus-3.3.2/config/../bin/etraining: ERROR
        Input file not in genbank format.
```
Find attached the genbank file

[train.gb.zip](https://github.com/Gaius-Augustus/BRAKER/files/3015876/train.gb.zip)

How can I fix it? 
Thanks in advance, 
Luis Alfonso.

**Comment by KatharinaHoff** [comment]
Hi Luis,
can you please check whether the file

/home/bio/Documents/Purpureocillium/March2019/braker/Purp/train.f.gb

has any contents? If yes, can you please post the first entry?

Thank you.

Katharina

**Comment by OnlyHigh** [comment]
Hi Katarina, 
The file is empty, 

Cheers, 
Luis Alfonso.

**Comment by KatharinaHoff** [comment]
That looks like training failed because no training genes were generated. You proteins did not map sufficiently.

**Comment by OnlyHigh** [comment]
Hi Katarina, 
It's weird because is suppose to be the same species, 

Thank you! 
Cheers, 
Luis Alfonso. 

PD, would you recommend to annotate with the ``` hints.gff ``` file generated?

**Comment by KatharinaHoff** [comment]
That's all weird.

Did you confirm that the pipeline works with GenomeThreader on your installation with the BRAKER/example/tests/test4.sh ?
