### ISSUE TITLE
Questions when evaluating the results from test datasets by Braker

### ISSUE THREAD

**Issue by bam2wigKillMe** [Gaius-Augustus/BRAKER#284]
Hello, I tried to evaluate Braker's performance by using the results from Braker's test run, I tried compare_intervals_exact.pl to test if my local braker works  fine, the following output seems it works well.
```compare_intervals_exact.pl -f1 mytest/test3/braker.gtf -f2 results/test3/braker.gtf --verbose
# CDS in file mytest/test3/braker.gtf: 1467
# CDS in file results/test3/braker.gtf: 1469

#in	match	unique	%match	CDS

1467	1445	22	98.50	mytest/test3/braker.gtf
1469	1445	24	98.37	results/test3/braker.gtf
```
And I then downloaded reference gtf from ensemble, and evaluated it by compare_intervals_exact.pl and evaluate_gtf.pl from EVAL package, and this time seemed no gene matched at all, below are my test codes and results:
```wget ftp://ftp.ensemblgenomes.org/pub/plants/release-48/gff3/arabidopsis_thaliana/Arabidopsis_thaliana.TAIR10.48.chromosome.5.gff3.gz
gunzip Arabidopsis_thaliana.TAIR10.48.chromosome.5.gff3.gz
# to get last 1Mb gff from the reference
awk '{if($4>26975502-1000000 && NR >100){print NR;exit } }' Arabidopsis_thaliana.TAIR10.48.chromosome.5.gff3 
178204
wc -l Arabidopsis_thaliana.TAIR10.48.chromosome.5.gff3
187901
tail -n 9698 Arabidopsis_thaliana.TAIR10.48.chromosome.5.gff3 > ara.1mb.gff3
gffread -T ara.1mb.gff3 -o ara.1mb.gtf
# Transform the last 1Mb reference start from 0 instead of (26975502-1000000), because braker.gtf starts from 0, too, and if I didn't transform, there's nothing matched.
cat ara.1mb.gtf | awk 'OFS="\t" {if(NF > 5 && $4>=25975502) {print $1,$2,$3,$4-25975502,$5-25975502,$6,$7,$8,$9,$10,$11,$12}}' >ara.trans1mb.gtf

compare_intervals_exact.pl -f1 ara.trans1mb.gtf -f2 mytest/test2.1/braker.gtf –verbose
# After transformation, the match rate is still 0
#in	match	unique	%match	CDS
1665	0	1665	0.00	ara.trans1mb.gtf
1458	0	1458	0.00	braker.gtf

evaluate_gtf.pl ara.trans1mb.gtf mytest/test2.1/braker.gtf  | less
# Although Nucleotide result is not 0, but the results is not good.
Gene Sensitivity                0.00%     
Gene Specificity                0.00%     
Transcript Sensitivity          0.00%     
Transcript Specificity          0.00%     
Exon Sensitivity                0.00%     
Exon Specificity                0.00%     
Nucleotide Sensitivity          8.99%     
Nucleotide Specificity          26.53%    
```
In Braker README, the testset is last 1,000,000 nucleotides of Arabidopsis thaliana's chromosome Chr5, but I found in the genome.fa file, there are 8 sequence named "X1", "X2", ... , "X8", which is confusing, did this mean they are 8 contigs of the Chr5.
please show me where I was wrong.

**Comment by tomasbruna** [comment]
Hello,

the last 1 Mbp are split into 8 artificial contigs, to create a test example with multiple FASTA entries. You would have to split the last 1 Mbp of _A. thaliana_ Chr5 annotation in the same way and rename the resulting contigs to X1..X8 to do the comparison.

Even after such a transformation, the prediction results would not be very good. The small subset of the genome in this test sequence is not long enough for BRAKER training to work well. Similarly, the RNA-Seq and protein inputs are very limited.

The purpose of these tests is to quickly check whether the pipeline works as intended (which it does according to the first example you shared), not really to evaluate the prediction accuracy. For that, you could download the full _A. thaliana_ genome, protein, and RNA-Seq sets. Such a procedure is described in the supplement of https://www.biorxiv.org/content/10.1101/2020.08.10.245134v1.article-metrics.

Best,
Tomas

**Comment by bam2wigKillMe** [comment]
Thank you for your reply very much, I will read and try the supplement procedure you mentioned above.
Best.
