### ISSUE TITLE
the output file braker.gtf is not correct 

### ISSUE THREAD

**Issue by qisun2** [Gaius-Augustus/BRAKER#285]
I checked two of the gtf files produced by BRAKER: "augustus.hints.gtf" and "braker.gtf".  "augustus.hints.gtf" is correct, but "braker.gtf" has lots of errors in the file.  I am not too concerned by file "braker.gtf" itself, as I only use  the "augustus.hints.gtf" in my pipeline. But I am worried whether it was caused by some underlying compatibility problem with GeneMark. Previously, I have ran into version compatibility issues among braker, augustus, genemark and other dependencies. I am a little paranoid now. 

The errors in braker.gtf exist in both my run, and also in the test results from your github repository (https://github.com/Gaius-Augustus/BRAKER/tree/master/example/results/test1) .

I have not looked into the details of the errors, but this braker.gtf file was rejected by quite a few downstream software I tested and report errors in the file. For example,  the gtf2gff.pl script from Augustus processes this file without reporting error messages, but output an obviously wrong gff3 file with no single "gene" "mRNA" .

**Comment by jelber2** [comment]
The following worked for me to produce a GFF3 file with unique IDs per entry (needed by some downstream tools). Most of the perl code below is to modify the GTF input so that it has `transcript_id "gene#.t#"; gene_id "gene#";` per transcript line and `gene_id "gene#";` per gene line. The unique ids are actually the line numbers of the input file.

    # combine the augustus and genemark predictions from BRAKER2
    cat augustus.hints.gtf \
    GeneMark-EP/genemark.f.multi_anchored.gtf > braker.gtf

    or 
    cat augustus.hints.gtf \
    GeneMark-ETP/genemark.f.multi_anchored.gtf > braker.gtf

    # use GFFRead (https://github.com/gpertea/gffread) to add missing gene lines to genemark.gtf file (--keep-genes), adjust the stop codons,
    # remove transcript with missing start or stop codons (-J)
    # sort the output and convert to GFF3 not GTF (--sort-alpha)
    /genetics/elbers/gffread-0.12.3.Linux_x86_64/gffread -g $genome_path --adj-stop -J --sort-alpha -E --keep-genes \
    <(perl -pe "s/\t(\S+)(\.t\d+)\n/\ttranscript_id \"\1\2\"; gene_id \"\1\";\n/ if /\ttranscript\t/g" braker.gtf|perl -pe "s/\t(\S+)\n/\tgene_id \"\1\";\n/ if /\tgene\t/g") -o- 2>gffread.log | \
    perl -pe "s/\ttranscript\t/\tmRNA\t/g" | \
    cat -n - | perl -pe "s/^/ /g" | \
    perl -pe "s/^\s+(\S+)\s+(.+)Parent=(\S+)\n/\2 ID=\3.\1;Parent=\3\n/ if /\tParent/" | \
    perl -pe "s/^\s+\S+\s+(.+)\n/\1\n/ if /^\s+/" > output.gff3

**Comment by tomasbruna** [comment]
Hello @qisun2,

> But I am worried whether it was caused by some underlying compatibility problem with GeneMark. Previously, I have ran into version compatibility issues among braker, augustus, genemark and other dependencies. I am a little paranoid now.

I understand the worries :) Currently, the issues with `braker.gtf` are only caused by problems in output combination, the tools are compatible. Thanks for pointing this out, we will fix the formatting issues.

Best,
Tomas

**Comment by MattHuff** [comment]
I have noticed this issue with BRAKER 2.1.6 in our lab as well. We first ran the script with default output options, and `braker.gtf` was missing "gene" and "mRNA" features. I recently reran the script with the `--gff3` output option selected and found that the same issue is carried over into the `braker.gff3` file. I have been able to work around this, but I think it is worth knowing that the issue is consistent between the two output types.

**Comment by xizhesun** [comment]
> I have noticed this issue with BRAKER 2.1.6 in our lab as well. We first ran the script with default output options, and `braker.gtf` was missing "gene" and "mRNA" features. I recently reran the script with the `--gff3` output option selected and found that the same issue is carried over into the `braker.gff3` file. I have been able to work around this, but I think it is worth knowing that the issue is consistent between the two output types.

I also used braker 2.1.6 with "--gff3". the output file "braker.gff3" has "gene" and "mRNA" features. I wish this information could help you. What I confused about is that why the software outputs two gff file?

**Comment by Peterlyko** [comment]
> 
> 
> Please try the following workaround with [GenomeTools](http://genometools.org/) to produce a valid gff from gtf:
> 
> ```
> gt gtf_to_gff3 <(grep -P "\tCDS\t|\texon\t" braker.gtf ) > braker.gff
> ```

This works for me, thank you. (And thanks for reminding me, that GenomeTools exists)
