### ISSUE TITLE
Questions about using local sequencing data from NGS and full length sequencing

### ISSUE THREAD

**Issue by bam2wigKillMe** [Gaius-Augustus/BRAKER#286]
Hello, 
Our lab is planning to annotate genome with our local NGS and full-length sequencing data which is unpublic yet. 
I notice in BRAKER's README, you said BRAKER was not officially support long read data, how about now? Are there some progress going?
Recently, I learned about how VARUS works, but I found it seemed to not work with local sequencing data, so could you please tell me how to get a good coverage of genome from my local data without VARUS? Should I align the data by STAR or hisat2 directly? Are there some alignment tools that BRAKER recommend for NGS and full-length sequencing?  

best

**Comment by KatharinaHoff** [comment]
We are internally working on long read integration, but it will be several
months before we produce results that can be used. In the meantime, you can
add long read information (bam file) in the same way as short read
information - this just doesn't take full advantage of the long read
information, yet.

For short read data, I recommend that you either run two-pass STAR mapping,
or Hisat2 mapping. (Possibly polished) long reads can be aligned with GMAP.
You can also manually produce additional hints from the GMAP alignment
following instructions for IsoSeq and/or ESTs in
https://doi.org/10.1002/cpbi.57

Katharina

**Comment by bam2wigKillMe** [comment]
Dear Katharina, thank you! I will follow your instructions. That's very helpful

**Comment by goodgodric28** [comment]
Is there any update on this long read integration?

**Comment by jjwujay** [comment]
Is there any update on iso-seq?

**Comment by KatharinaHoff** [comment]
Stay with us ;-) There will soon be a talk at PAG San Diego about this.

**Comment by KatharinaHoff** [comment]
**BRAKER and TSEBRA at PAG XXIX**

:sparkles: Lars Gabriel will give a talk about PacBio ccs integration into gene prediction with BRAKER and TSEBRA at PAG on Sunday, Jan 9 2022 4:25 PM. The workflow for PacBio data integration is documented at https://github.com/Gaius-Augustus/BRAKER/blob/master/docs/long_reads/long_read_protocol.md

The slides will be made available within the BRAKER docs folder after PAG.
