### ISSUE TITLE
plans for Docker image?

### ISSUE THREAD

**Issue by Sanrrone** [Gaius-Augustus/BRAKER#289]
Dears Braker staff,
bracker2 will solve several problems for eukaryotic genomes annotations. But, due its heavy external dependencies is difficult to install even for who are experienced on unix enviroment. This kind of software is ideal to dockerize and it would be a great idea have the docker image ready to use in a future, Have you plans for it?

Thanks in advance,
Regards.

**Comment by tomasbruna** [comment]
Hello,

currently, there is a docker image available for the latest BRAKER2 release through Bioconda at https://bioconda.github.io/recipes/braker2/README.html.

However, this latest release is a bit old, many new improvements and bug fixes are only available when you clone the latest BRAKER from the master branch.

We will make a new up-to-date release soon.

Best,
Tomas
