### ISSUE TITLE
Genemark-ETP crashes with empty evidence.gff

### ISSUE THREAD

**Issue by holmrenser** [Gaius-Augustus/BRAKER#290]
As per @KatharinaHoff's suggestion in #281, I re-ran braker using RNAseq evidence and protein evidence in the form of orthodb protein sequences. I am annotating a monocot plant species, and have used all (~800K) viridiplantae orthodb proteins. I use ~20 RNAseq libraries.

My initial attempt crashed after prothint finished because Math::Utils was not installed. However, I found a file `prothint.gff`, which I am providing as `--prothints` in my second attempt to circumvent having to run ProtHint again. 

This time, GeneMark-ETP crashes with an empty `evidence.gff` file. 

`GeneMark-ETP.stdout` looks as follows:
```
check before run
create directories
commit input data
error, output file is empty data/evidence.gff
error on call: /mnt/LTR_userdata/holme003/progs_nobackup/gmes_linux_64/reformat_gff.pl --out data/evidence.gff  --trace info/dna.trace  --in /lustre/BIF/nobackup/holme003/xerophyta/annotation/xerophyta_4/braker/evidence.gff  --quiet
```

Any tips?

**Comment by conchoecia** [comment]
I am getting the same error and am wondering how to fix it.

**Comment by holmrenser** [comment]
The only way I got things to work is reinstall everything from scratch with the latest git releases.

**Comment by tomasbruna** [comment]
Hello Rens,

I am so sorry for missing this issue and not replying earlier. @conchoecia, Rens is correct, updating BRAKER2 from its master branch on GitHub should resolve the issue. The option `--prothints` is from an older version that had many problems with ProtHint integration.

Rens, were you able to finish the BRAKER2 run in the end?

Tomas

**Comment by holmrenser** [comment]
No worries @tomasbruna. Like I said: installing braker/augustus from scratch from their respective git master branches worked for me in the end. I fully realize that releasing complex software with many dependencies is not trivial, which is why I tend to gravitate to bioconda releases. It would be very handy if braker/augustus and their allies followed some sort of release schedule with accompanying bioconda releases. If you need help putting things together let me know!

**Comment by tomasbruna** [comment]
Thanks for the offer to help! We are planning to solve this mess with a new BRAKER2 bioconda release. There is also a plan to make a bioconda package for GeneMark and ProtHint, once we solve some licensing issues (https://github.com/gatech-genemark/ProtHint/issues/6).

**Comment by KatharinaHoff** [comment]
The actual issue was solved.
