### ISSUE TITLE
braker.pl is not compatible with GeneMark 4.62 (latest)

### ISSUE THREAD

**Issue by cooketho** [Gaius-Augustus/BRAKER#298]
I can see that you have tested BRAKER with GeneMark 4.59, but as far as I can see that version is no longer available for download. On their website, I can only see version 4.62, so that is what I installed. I can't get test1.sh to work. The reason is that BRAKER tries to execute the following command, which fails because --gc_donor does not exist as an option in GeneMark v4.62, nor is "auto" an acceptable option to pass to --soft_mask. Please download the latest GeneMark and use the following commands to reproduce the issue:

So to recap, this command (issued by BRAKER) does not work:

```
perl /usr/local/genemark/gmes_petap/gmes_petap.pl \
--verbose \
--sequence=~/BRAKER/example/tests/test1/genome.fa \
--ET=~/BRAKER/example/tests/test1/genemark_hintsfile.gff \
--cores=8 \
--gc_donor 0.001 \
--soft_mask auto \
--max_intergenic=10000 \
> ~/BRAKER/example/tests/test1/GeneMark-ET.stdout
```

This command works:
```
perl /usr/local/genemark/gmes_petap/gmes_petap.pl \
--verbose \
--sequence=~/BRAKER/example/tests/test1/genome.fa \
--ET=~/BRAKER/example/tests/test1/genemark_hintsfile.gff \
--cores=8 \
--max_intergenic=10000 \
> ~/BRAKER/example/tests/test1/GeneMark-ET.stdout
```

Can you please update braker.pl? Thank you!

**Comment by tomasbruna** [comment]
Hello,

can you double-check the GeneMark version? Both 4.59 and 4.62 support the `--gc_donor` option, the problem must be in something else.

Best,
Tomas

**Comment by cooketho** [comment]
Sorry! You're right.

I think the GENEMARK_PATH environmental variable wasn't set properly, so it was defaulting to an older version (4.38) that our sysadmin had installed elsewhere.

It is working now. I'll go ahead and close this.
