### ISSUE TITLE
AUGUSTUS versions

### ISSUE THREAD

**Issue by Sea-bar** [Gaius-Augustus/BRAKER#300]
Hello,
BRAKER2 was tested with Augustus v3.3.4, however the latest Augustus release I see is v3.3.3 from Sept 13, 2019 (https://github.com/Gaius-Augustus/Augustus). The BRAKER2 documentation says v3.3.3 is not compatible. So, I am wondering what version of Augustus I am supposed to use and where to get it. I seem to be getting multiple errors related to missing Augustus scripts using older versions.

Thanks

**Comment by tomasbruna** [comment]
Hello, please get the latest AUGUSTUS by cloning the code from its master branch.

    git clone https://github.com/Gaius-Augustus/Augustus.git

Best,
Tomas

**Comment by abretaud** [comment]
Hi!
What about the compatibility with [augustus 3.4.0](https://github.com/Gaius-Augustus/Augustus/releases/tag/v3.4.0) released last december?

I know it may seem easier at first to just use latest code from dependencies, but it makes installation using package managers like Conda super difficult (not even considering the licensing issues with GenMark and ProtHint), and it really ruins reproducibility.

If the master branch of Augustus/Braker are more usable than the latest release, wouldn't it be better to just make new releases? I really think frequent, even imperfect, releases are much much better than no (or outdated) releases

**Comment by tomasbruna** [comment]
Hi @abretaud,

I completely agree, we were planning to release a new BRAKER together with AUGUSTUS, but we had some personal issues which froze the development. You can expect a new release very soon!

Tomas

**Comment by abretaud** [comment]
Cool, good to know :)

**Comment by abretaud** [comment]
Looking at the 2.1.6 release I guess this issue can be closed (thanks for the release!)
There's just this note which I think is out of date now: https://github.com/Gaius-Augustus/BRAKER#g2
