### ISSUE TITLE
align2hints.pl constructs incorrect stop hints for SPALN evidence

### ISSUE THREAD

**Issue by marchoeppner** [Gaius-Augustus/BRAKER#301]
Hi,

when parsing SPALN models with align2hints.pl, both the start AND the stop hint are computed from the first cds feature, producing invalid stop hints - and that can lead to split models and other issues. The correct solution would be to check if a cds feature is the last in a chain or store the start/stop coordinate from the mRNA feature and use that as stop hint (probably easier, as this requires less logic)

Problem is here: 
https://github.com/Gaius-Augustus/BRAKER/blob/a8c343f0c7fbb4d65a1c75f9804a7f7d5e2477e9/scripts/align2hints.pl#L334

**Comment by tomasbruna** [comment]
Hi @marchoeppner,

thanks for reporting this problem! It indeed looks like that with GenomeThreader, the code is currently using the `mRNA` feature, but with Spaln, it's failing as you described.

In case you are planning to use Spaln, please note that this mode of using protein hints from Spaln is deprecated, BRAKER2 is now using the [ProtHint](https://github.com/gatech-genemark/ProtHint) pipeline (which is also internally using Spaln).

@KatharinaHoff, do you have any relevant test set on which we could debug this problem? I never tested BRAKER2 in this mode. Also, should we remove this way of using Spaln from BRAKER2? No one is maintaining this mode anymore and there are likely more errors similar to this one.

Best,
Tomas

**Comment by KatharinaHoff** [comment]
I think we should remove the visibility of the option to use spaln from
usage. I don’t want to delete the code itself. Definitely no time to debug
this.
