### ISSUE TITLE
braker.pl  6302

### ISSUE THREAD

**Issue by Lillian-21** [Gaius-Augustus/BRAKER#304]

**Comment by Lillian-21** [comment]
Hi, I have updated BRAKER and dependences after I meet the empty top_chains.gff file. But now I am stuck in another step. 

My code is:  braker.pl --species=xxx  --genome=xxx.fa --softmasking --prot_seq=All.pep --bam=xxx.out.bam --etpmode --workingdir=$wd --cores=16 --gff3 --ALIGNMENT_TOOL_PATH=ProtHint/bin --DIAMOND_PATH=diamond-0.9.10/bin --GENEMARK_PATH=gmes_linux_64.

The tail of braker-rna.log is: 
[Sun Dec  6 22:20:23 2020] Processing the output
[Sun Dec  6 22:20:26 2020] Output processed
[Sun Dec  6 22:20:26 2020] ProtHint finished.
cat: xxx/genemark_hintsfile.gff.rnaseq.tmp: No such file or directory
ERROR in file xxx/braker.pl at line 6302
Failed to execute: cat xxx/genemark_hintsfile.gff.rnaseq.tmp xxx/genemark_hintsfile.gff.prot.tmp > xxx/genemark_hintsfile.gff

**Comment by tomasbruna** [comment]
Hello @Lillian-21,

did you try to run [test3.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3.sh) and was the run successful? More details about the example inputs can be found here https://github.com/Gaius-Augustus/BRAKER#example-data.

Also, please note that in the latest BRAKER2, the path to ProtHint is passed as `--PROTHINT_PATH`, not `--ALIGNMENT_TOOL_PATH`.

Best,
Tomas

**Comment by Lillian-21** [comment]
Thanks a lot. 
I have run test3.sh and test5.sh successfully. 
At the same time, I update my input bam file, which is still running now.

**Comment by TypicalSEE** [comment]
I also met this problem. In my case, the problem is caused by different FASTA IDs. BRAKER seems to prefer the full header line as a sequence's  ID, while in the bam file sequence ID is the first field of the header line.

**Comment by KatharinaHoff** [comment]
The genome fasta file should have exactly the same content as the genome sequence name in the bam file for running BRAKER. This is easiest achieved by having only one (space- and semicolon-free) field in the fasta header.
