### ISSUE TITLE
ERROR: in file /home/kasuza/conda/bin/braker.pl at line 6492

### ISSUE THREAD

**Issue by mengxin-mx-cpu** [Gaius-Augustus/BRAKER#305]
when I excute the command below.
braker.pl --genome genome.fa --bam RNAseq.bam --softmasking --cores 48

It returns error after 8 minuts:

# Mon Dec  7 11:34:00 2020: ERROR: in file /home/kasuza/conda/bin/braker.pl at line 6492
Training gene file in genbank format /lustre/kasuza/example/braker/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think th
is is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.

**Comment by tomasbruna** [comment]
Hello,

did you try updating BRAKER and AUGUSTUS from their master branches on GitHub?

Take a look at https://github.com/Gaius-Augustus/BRAKER/issues/214, I believe it is the same problem.

Best,
Tomas

**Comment by mengxin-mx-cpu** [comment]
Hello
I git clone https://github.com/Gaius-Augustus/Augustus.git and install agian.

'(braker2) [root@client48 Augustus]# augustus --version
AUGUSTUS (3.3.3) is a gene prediction tool
written by M. Stanke, O. Keller, S. König, L. Gerischer and L. Romoth.
(braker2) [root@client48 Augustus]# 

then i run 
time braker.pl --genome=genome.fa --bam=RNAseq.bam --softmasking --cores 48 

it breaked

(base) [root@node01 example]# time braker.pl --genome=genome.fa --bam=RNAseq.bam --softmasking --cores 48 
# Tue Dec  8 10:03:43 2020: Log information is stored in file /kasuza/example/braker/braker.log
ERROR in file /home/kasuza/conda/bin/braker.pl at line 6699
Failed to execute: perl /opt/augustus-3.3.3/scripts/aa2nonred.pl /kasuza/example/braker/traingenes.good.fa /kasuza/example/braker/traingenes.good.nr.fa --DIAMOND_PATH=/home/kasuza/tools --cores=48 --diamond 1> /kasuza/example/braker/aa2nonred.stdout 2>/kasuza/example/braker/errors/aa2nonred.stderr

i cat the file aa2nonred.stderr:
*********
Processing query chunk 0, reference chunk 0, shape 1, index chunk 3.
Building reference index...  [0.012822s]
Building query index...  [0.010975s]
Building seed filter...  [0.007664s]
Searching alignments...  [0.003298s]
Deallocating buffers...  [0.000209s]
Computing alignments... No such file or directory
 [0.004027s]
Error: Error reading file /kasuza/example/braker/diamond-tmp-SHhjV1
ERROR in file /opt/augustus-3.3.3/scripts/aa2nonred.pl at line 205
Failed to execute: /home/kasuza/tools/diamond blastp --db /kasuza/example/braker/traingenes.good.fa.nonreddb --outfmt 0 --query /kasuza/example/braker/traingenes.good.fa.nonreddb --threads 48 --out /kasuza/example/braker/traingenes.good.fa.blastout!
(base) [root@node01 example]#

**Comment by mengxin-mx-cpu** [comment]
(braker2) [root@node01 example]# braker.pl --checkSoftware
#**********************************************************************************
#                               BRAKER CONFIGURATION                               
#**********************************************************************************
# BRAKER CALL: /home/kasuza/conda/envs/braker2/bin/braker.pl --checkSoftware
# Tue Dec  8 10:31:50 2020: braker.pl version 2.1.5
# Tue Dec  8 10:31:50 2020: Configuring of BRAKER for using external tools...
# Tue Dec  8 10:31:50 2020: Found environment variable $AUGUSTUS_CONFIG_PATH. Setting $AUGUSTUS_CONFIG_PATH to /opt/augustus-3.3.3/config
# Tue Dec  8 10:31:50 2020: Found environment variable $AUGUSTUS_BIN_PATH. Setting $AUGUSTUS_BIN_PATH to /opt/augustus-3.3.3/bin
# Tue Dec  8 10:31:50 2020: Found environment variable $AUGUSTUS_SCRIPTS_PATH. Setting $AUGUSTUS_SCRIPTS_PATH to /opt/augustus-3.3.3/scripts
# Tue Dec  8 10:31:50 2020: Found environment variable $GENEMARK_PATH. Setting $GENEMARK_PATH to /home/kasuza/gmes_linux_64
# Tue Dec  8 10:31:50 2020: Found environment variable $DIAMOND_PATH. Setting $DIAMOND_PATH to /home/kasuza/tools
# Tue Dec  8 10:31:50 2020: Found environment variable $PYTHON3_PATH. Setting $PYTHON3_PATH to /home/kasuza/conda/bin/
# Tue Dec  8 10:31:50 2020: Found environment variable $CDBTOOLS_PATH. Setting $CDBTOOLS_PATH to /home/kasuza/tools/cdbfasta
# Tue Dec  8 10:31:50 2020: Exiting braker.pl because it had been started with --softwareCheck option. No training or prediction or file format check will be performed.
(braker2) [root@node01 example]# 


I have been tortured for several days.....

**Comment by mengxin-mx-cpu** [comment]
when I run braker2，In this section it breaks.I see the log,The command is:

/sasusa/example/braker/diamond blastp --db /kasuza/example/braker/traingenes.good.fa.nonreddb --outfmt 0 --query /sasusa/example/braker/traingenes.good.fa.nonreddb --threads 48 --out /kasuza/example/braker/traingenes.good.fa.blastout

Then I perform alone,It return error,I am not sure is the diamond's problem or not,but it seems to it's problem,I have tried the version 0.9.24 and diamond v2.0.5.143 (C). can you help me.

Processing query block 1, reference block 1/1, shape 2/2, index chunk 4/4.
Building reference seed array... [0.007s]
Building query seed array... [0.007s]
Computing hash join... [0.002s]
Building seed filter... [0.005s]
Searching alignments... [0.002s]
Deallocating buffers... [0s]
Clearing query masking... [0s]
Computing alignments... No such file or directory
terminate called after throwing an instance of 'File_read_exception'
what(): Error reading file /kasuza/example/braker/diamond-tmp-DzkIVZ
Aborted

**Comment by mengxin-mx-cpu** [comment]
I have see the braker.log

#                               TRAIN AUGUSTUS                                     
#**********************************************************************************
# Tue Dec  8 21:18:53 2020: training AUGUSTUS
# Tue Dec  8 21:18:53 2020: creating softlink from /kasuza/example/braker/GeneMark-ET/genemark.gtf to /kasuza/example/braker/traingenes.gtf.
ln -s /kasuza/example/braker/GeneMark-ET/genemark.gtf /kasuza/example/braker/traingenes.gtf
# Tue Dec  8 21:18:53 2020: Converting gtf file /kasuza/example/braker/traingenes.gtf to genbank file
# Tue Dec  8 21:18:53 2020: Computing flanking region size for AUGUSTUS training genes
# Tue Dec  8 21:18:53 2020: create genbank file /kasuza/example/braker/train.gb
perl /opt/augustus-3.3.3/scripts/gff2gbSmallDNA.pl /kasuza/example/braker/traingenes.gtf /kasuza/example/braker/genome.fa 1096 /kasuza/example/braker/train.gb 2>/kasuza/example/braker/errors/traingenes.gtf_gff2gbSmallDNA.stderr
# Tue Dec  8 21:18:53 2020: Genbank format file /kasuza/example/braker/train.gb contains 255 genes.
#  Tue Dec  8 21:18:53 2020: concatenating good and downsampled GeneMark training genes to /kasuza/example/braker/good_genes.lst.
cat /kasuza/example/braker/GeneMark-ET/genemark.d.gtf > /kasuza/example/braker/good_genes.lst
# Tue Dec  8 21:18:53 2020: Filtering train.gb for "good" mRNAs:
perl /opt/augustus-3.3.3/scripts/filterGenesIn_mRNAname.pl /kasuza/example/braker/good_genes.lst /kasuza/example/braker/train.gb > /kasuza/example/braker/train.f.gb 2>/kasuza/example/braker/errors/filterGenesIn_mRNAname.stderr
# Tue Dec  8 21:18:53 2020: Genbank format file /kasuza/example/braker/train.f.gb contains 79 genes.
# Tue Dec  8 21:18:53 2020: Running etraining to catch gene structure inconsistencies:
/opt/augustus-3.3.3/bin/etraining --species=Sp_1 --AUGUSTUS_CONFIG_PATH=/opt/augustus-3.3.3/config /kasuza/example/braker/train.f.gb 1> /kasuza/example/braker/gbFilterEtraining.stdout 2>/kasuza/example/braker/errors/gbFilterEtraining.stderr
# Tue Dec  8 21:18:54 2020: Filtering /kasuza/example/braker/train.f.gb file to remove inconsistent gene structures...
perl /opt/augustus-3.3.3/scripts/filterGenes.pl /kasuza/example/braker/etrain.bad.lst /kasuza/example/braker/train.f.gb 1> /kasuza/example/braker/train.ff.gb 2>/kasuza/example/braker/errors/etrainFilterGenes.stderr
# Tue Dec  8 21:18:54 2020: Genbank format file /kasuza/example/braker/train.ff.gb contains 79 genes.
# Tue Dec  8 21:18:54 2020: BLAST or DIAMOND training gene structures against themselves:
perl /opt/augustus-3.3.3/scripts/aa2nonred.pl /kasuza/example/braker/traingenes.good.fa /kasuza/example/braker/traingenes.good.nr.fa --DIAMOND_PATH=/home/kasuza/tools --cores=48 --diamond 1> /kasuza/example/braker/aa2nonred.stdout 2>/kasuza/example/braker/errors/aa2nonr
ed.stderr


(braker2) [root@node01 augustus-3.3.3]# perl /opt/augustus-3.3.3/scripts/aa2nonred.pl /kasuza/example/braker/traingenes.good.fa /kasuza/example/braker/traingenes.good.nr.fa --DIAMOND_PATH=/home/kasuza/tools --cores=48 --diamond
# Tue Dec  8 22:16:44 2020: Did not find environment variable $DIAMOND_PATH
# Tue Dec  8 22:16:44 2020: Setting $DIAMOND_PATH to command line argument --DIAMOND_PATH value /home/kasuza/tools.
diamond v2.0.5.143 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 48
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: /kasuza/example/braker/traingenes.good.fa.nonreddb
Opening the database file...  [0.003s]
Loading sequences...  [0.001s]
Masking sequences...  [0.01s]
Writing sequences...  [0s]
Hashing sequences...  [0s]
Loading sequences...  [0s]
Writing trailer...  [0s]
Closing the input file...  [0s]
Closing the database file...  [0.002s]
Database hash = f9febe04cfeee8f1342e4130b42e27eb
Processed 79 sequences, 28855 letters.
Total time = 0.018s
diamond v2.0.5.143 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 48
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /kasuza/example/braker
Opening the database...  [0.002s]
#Target sequences to report alignments for: 25
Reference = /kasuza/example/braker/traingenes.good.fa.nonreddb.dmnd
Sequences = 79
Letters = 28855
Block size = 2000000000
Opening the input file...  [0.001s]
Opening the output file...  [0.001s]
Loading query sequences...  [0s]
Masking queries...  [0.016s]
Building query seed set...  [0.001s]
The host system is detected to have 404 GB of RAM. It is recommended to increase the block size for better performance using these parameters : -b8 -c1
Algorithm: Double-indexed
Building query histograms...  [0.004s]
Allocating buffers...  [0s]
Loading reference sequences...  [0s]
Masking reference...  [0.006s]
Initializing temporary storage...  [0.051s]
Building reference histograms...  [0.004s]
Allocating buffers...  [0s]
Processing query block 1, reference block 1/1, shape 1/2, index chunk 1/4.
Building reference seed array...  [0.009s]
Building query seed array...  [0.008s]
Computing hash join...  [0.002s]
Building seed filter...  [0.006s]
Searching alignments...  [0.003s]
Processing query block 1, reference block 1/1, shape 1/2, index chunk 2/4.
Building reference seed array...  [0.008s]
Building query seed array...  [0.008s]
Computing hash join...  [0.003s]
Building seed filter...  [0.006s]
Searching alignments...  [0.003s]
Processing query block 1, reference block 1/1, shape 1/2, index chunk 3/4.
Building reference seed array...  [0.008s]
Building query seed array...  [0.008s]
Computing hash join...  [0.003s]
Building seed filter...  [0.006s]
Searching alignments...  [0.003s]
Processing query block 1, reference block 1/1, shape 1/2, index chunk 4/4.
Building reference seed array...  [0.008s]
Building query seed array...  [0.008s]
Computing hash join...  [0.003s]
Building seed filter...  [0.006s]
Searching alignments...  [0.003s]
Processing query block 1, reference block 1/1, shape 2/2, index chunk 1/4.
Building reference seed array...  [0.008s]
Building query seed array...  [0.008s]
Computing hash join...  [0.003s]
Building seed filter...  [0.006s]
Searching alignments...  [0.003s]
Processing query block 1, reference block 1/1, shape 2/2, index chunk 2/4.
Building reference seed array...  [0.008s]
Building query seed array...  [0.008s]
Computing hash join...  [0.002s]
Building seed filter...  [0.007s]
Searching alignments...  [0.003s]
Processing query block 1, reference block 1/1, shape 2/2, index chunk 3/4.
Building reference seed array...  [0.008s]
Building query seed array...  [0.007s]
Computing hash join...  [0.002s]
Building seed filter...  [0.006s]
Searching alignments...  [0.003s]
Processing query block 1, reference block 1/1, shape 2/2, index chunk 4/4.
Building reference seed array...  [0.008s]
Building query seed array...  [0.007s]
Computing hash join...  [0.002s]
Building seed filter...  [0.006s]
Searching alignments...  [0.003s]
Deallocating buffers...  [0s]
Clearing query masking...  [0s]
Computing alignments... No such file or directory
terminate called after throwing an instance of 'File_read_exception'
  what():  Error reading file /kasuza/example/braker/diamond-tmp-WBoRYE
ERROR in file /opt/augustus-3.3.3/scripts/aa2nonred.pl at line 205
Failed to execute: /home/kasuza/tools/diamond blastp --db /kasuza/example/braker/traingenes.good.fa.nonreddb --outfmt 0 --query /kasuza/example/braker/traingenes.good.fa.nonreddb --threads 48 --out /kasuza/example/braker/traingenes.good.fa.blastout!
(braker2) [root@node01 augustus-3.3.3]#

**Comment by mengxin-mx-cpu** [comment]
I change the version of diamond to 2.0.5

and  modify the "/opt/augustus-3.3.3/scripts/aa2nonred.pl" file ,add option --no-unlink

$cmdString = "$DIAMOND_PATH/diamond blastp --db $tempdbname --outfmt 0 --query $tempdbname --out $tempoutfile --no-unlink";


This fixed my problem,Anyway,Thanks a lot for your help!

**Comment by KatharinaHoff** [comment]
Interesting. Thanks for reporting this.
