### ISSUE TITLE
Error line 6565: error on call: probluid

### ISSUE THREAD

**Issue by Louis-MG** [Gaius-Augustus/BRAKER#309]
Hello, 
I managed to install braker and want to run it with --UTR=on. I provided a bam, a masked genome (soft) and a fasta for the proteins. I had the warning about the "|" in the headers so i took care of that in case it might be the cause of the problem. I still get the following error: 
`The most common problem is an expired or not present file ~/.gm_key!
`
I dig into the GeneMark-ES.stdout  and it shows the following:
```check before run
create directories
commit input data
soft_mask is in the 'auto' mode. soft_mask was set to: 100
data report
error on call: /home/lmgueguen/gmes_linux_64/probuild  --seq data/dna.fna  --allow_x  --stat_fasta info/dna.multi_fasta
```
There is only one empty file in /data/training/ , the program stops after a minute or so. Th other error file GeneMark-ES.stderr shows:
`	(in cleanup) 	(in cleanup)  at /usr/local/share/perl/5.30.0/Object/InsideOut.pm line 1953 during global destruction.
` 
Any hint on the problem ?

**Comment by tomasbruna** [comment]
Hello,

this could be the same problem as you encountered in https://github.com/Gaius-Augustus/BRAKER/issues/96.

Do you get a segmentation fault when running the following command?

    /home/lmgueguen/gmes_linux_64/probuild  --seq data/dna.fna  --allow_x  --stat_fasta info/dna.multi_fasta

If not, what is the error message?

The `(in cleanup) (in cleanup)` error is only related to memory management of one of the Perl modules used, it is not really a problem.

Best,
Tomas

**Comment by Louis-MG** [comment]
Well I set up the braker pipeline on another machine with sudo access as I am in a hurry.

I thought about it indeed, but the gmhmme3 did not yield a segmentation fault when I tried the same command as the last time. The command you give produces nothing particular.

**Comment by Louis-MG** [comment]
Update @tomasbruna : 
Because the command did not show any error I decided to give my script another try, and this time I got the following (did not change anything):
```
build initial ES model
running step ES_A
running gm.hmm on local system
6550 contigs in training
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_740.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_741.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_742.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_750.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_760.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_761.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_763.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_776.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_783.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_787.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_791.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_793.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_794.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_796.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_802.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_804.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_809.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_822.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_825.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_826.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_827.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_828.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_831.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_833.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_835.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_837.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_838.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_840.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_844.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_845.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_848.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_851.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_852.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_857.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_858.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_860.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_862.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_863.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_865.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_866.out
error on open file: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_867.out
error on open file: /home/lmgueguen/braker_wd/GeneMarkconcatenate predictions: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1
training level ES_A: /home/lmgueguen/braker_wd/GeneMark-ES/run/ES_A_1
Initial	20232
Internal	32278
Terminal	20024
Single	2470
Intron:	53847	140793207
Intergenic:	12039	103631168
error, no valid sequences were found
error on call: /home/lmgueguen/gmes_linux_64/make_nt_freq_mat.pl --cfg /home/lmgueguen/braker_wd/GeneMark-ES/run.cfg --section start_ATG   --format INI
```
I will run it again later to see if that is consistant.

**Comment by tomasbruna** [comment]
> Update: still running, no error so far. Lacking storage maybe?

That could well be, I have never experienced an instability like this -- GeneMark either always fails, or always runs.

Fingers crossed for this run

**Comment by mengguoqingup** [comment]
hello ， i have a same problem when i run genemark -es along. how did you solved this problem? 
thank you!
Initial 0
Internal        1
Terminal        1
Single  1
Intron: 2       12346
Intergenic:     1       25645
error, no valid sequences were found
error on call: /opt/biosoft/gmes_linux_64/make_nt_freq_mat.pl --cfg /home/annotation/mengguoqing/Rosa/rosa_rugosa_chinesis/megahit_asme/GM/run.cfg --section stop_TGA    --format TERM_TGA

Initial 0
Internal        1
Terminal        1
Single  1
Intron: 2       12346
Intergenic:     1       25645
error, no valid sequences were found
error on call: /opt/biosoft/gmes_linux_64/make_nt_freq_mat.pl --cfg /home/annotation/mengguoqing/Rosa/rosa_rugosa_chinesis/megahit_asme/GM/run.cfg --section stop_TGA    --format TERM_TGA

**Comment by tomasbruna** [comment]
Hello @mengguoqingup,

in your case, GeneMark-ES fails because it only predicts 3 exons in the iteration. How large is your input sequence and how long are the contigs? I wonder if this problem is caused by the input being too small.

Best,
Tomas

**Comment by mengguoqingup** [comment]
@tomasbruna @ Thank you so much! I am sorry to bother again， but now I have a new problem in genemark.
may help?thank you
 warning on: /opt/biosoft/gmes_linux_64/gmhmme3  -m /home/annotation/mengguoqing/Rosa/yingcaoqiangwei/megahit_asme/GM/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_152074.out  /home/annotation/mengguoqing/Rosa/yingcaoqiangwei/megahit_asme/GM/output/data/dna.fa_152074
warning on: /opt/biosoft/gmes_linux_64/gmhmme3  -m /home/annotation/mengguoqing/Rosa/yingcaoqiangwei/megahit_asme/GM/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_152169.out  /home/annotation/mengguoqing/Rosa/yingcaoqiangwei/megahit_asme/GM/output/data/dna.fa_152169
*** glibc detected *** /opt/biosoft/gmes_linux_64/gmhmme3: double free or corruption (!prev): 0x00000000015c13d0 ***
======= Backtrace: =========
[0x49df1a]
[0x4a0cec]
[0x401792]
[0x47ec7e]
[0x4003e9]
======= Memory map: ========
00400000-00560000 r-xp 00000000 fd:03 807547933                          /opt/biosoft/gmes_linux_64/gmhmme3
0075f000-00762000 rw-p 0015f000 fd:03 807547933                          /opt/biosoft/gmes_linux_64/gmhmme3
00762000-00779000 rw-p 00000000 00:00 0
0142a000-015f0000 rw-p 00000000 00:00 0                                  [heap]
7f71c8000000-7f71c8027000 rw-p 00000000 00:00 0
7f71c8027000-7f71cc000000 ---p 00000000 00:00 0
7f71cd7ac000-7f71cda57000 rw-p 00000000 00:00 0
7fffe3cc5000-7fffe3ce7000 rw-p 00000000 00:00 0                          [stack]
7fffe3cf0000-7fffe3cf2000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
warning on: /opt/biosoft/gmes_linux_64/gmhmme3  -m /home/annotation/mengguoqing/Rosa/yingcaoqiangwei/megahit_asme/GM/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_159532.out  /home/annotation/mengguoqing/Rosa/yingcaoqiangwei/megahit_asme/GM/output/data/dna.fa_159532

**Comment by tomasbruna** [comment]
Hi @mengguoqingup,

what was the solution for the original problem? Was the input sequence just too short?

This new error is something I have not seen before, it might be caused by something unexpected in your input. Can you share the intermediate input files, these ones?

- `/home/annotation/mengguoqing/Rosa/yingcaoqiangwei/megahit_asme/GM/output/gmhmm.mod`
- `/home/annotation/mengguoqing/Rosa/yingcaoqiangwei/megahit_asme/GM/output/data/dna.fa_152169`

I will try to run `gmhmme3` and see if I can reproduce this error.

By the way, what version of `gmhmme3` do you have? This can be determined by running `gmhmme3` without arguments, like this:

     /opt/biosoft/gmes_linux_64/gmhmme3

Tomas

**Comment by KatharinaHoff** [comment]
I am closing here since we didn't get a response on the solution, and it was not really a BRAKER but a GeneMark problem.
