### ISSUE TITLE
Add Dockerfile to git repo

### ISSUE THREAD

**Issue by krokicki** [Gaius-Augustus/BRAKER#317]
We are trying to run BRAKER on an HPC cluster using Singularity, but the Docker container provided (https://biohpc.cornell.edu/lab/userguide.aspx?a=software&i=684) uses /root which doesn't play nicely with Singularity. I'd like to try fixing this, but I don't see the Dockerfile in git anywhere. Would it be possible to add it here?

**Comment by nathanweeks** [comment]
I suspect that Docker image isn't maintained by the BRAKER developers, but an official Dockerfile for BRAKER would be convenient.

**Comment by KatharinaHoff** [comment]
Yes, that's not our container... sorry. If we had the time, we would look into making our own docker container. It's on the to-do-list, but please don't get your hopes up that it will happen any time soon.

I run BRAKER on several HPC systems without root access. I use conda to create a perl & python environment.
