### ISSUE TITLE
More genes predicted than expected gene number

### ISSUE THREAD

**Issue by ghost** [Gaius-Augustus/BRAKER#319]
Hi,

I am using braker2 for a maize genome annotation. I performed 2 rounds of annotation given homologous evidence (protein in fasta) and aligned RNA BAM file. In the 1st round, I used a hard-masked genome and annotated genes in ETP mode. In the 2nd round, I used a soft-masked genome and assigned --skipAllTraining so that only running Augustus prediction with pre-trained and already existing parameters. 

The final gff file (If I am not wrong) should be the output file from the 2nd round in augustus.hints.gtf format. I simply checked how many genes predicted in this program. I found that more than 60,000 genes (with protein sequence in augustus.hints.aa) were annotated. However, based on the most-updated maize reference genome, we know there should have estimated 41,000 genes. Far more genes were predicted in braker2. 

I checked the gff file for the score column but have not figured out a good way to filter the annotated genes. Obviously, there are many false positively predicted genes. Do you have any idea about how to solve the problem? Or can you give some hints on how to understand the "score" column in gff file, potentially, if cutoff can be set on it so that low-quality genes can be filtered out?

Many thanks in advance. 

Best,
Meiyuan

**Comment by Huangyizhong** [comment]
Hi, Meiyuan
I also used the BRAKER2 to do the gene prediction these days. When I run the  gmes_petap.pl script, there have a problem, showing as follw:
cannot find an apropriate clone(). at /home/goldenpigs/.cpanm/work/1612520303.54933/Hash-Merge-0.302/lib/Hash/Merge.pm line 7.
Have you meet such problems and if you can give me some advices?
Thanks in advance 
Best wishes
Huangyizhong

**Comment by tomasbruna** [comment]
Hi Meiyuan,

we have an experimental script to deal with this problem in a separate BRAKER branch. The script takes on input the predicted gene set (`augustus.hints.gtf`) and the hints generated in the course of a BRAKER run (should be stored in `hintsfile.gff`). Based on the hints, it splits the predicted genes into several categories:

- Genes fully supported by hints. These are the most confident predictions.
- Genes at least partially supported by hints.
- Genes not supported by hints. These are fully computational predictions and thus the least confident.

The script is called `selectSupportedSubsets.py` and it's located here https://github.com/Gaius-Augustus/BRAKER/tree/report/scripts/predictionAnalysis. To run it, you will need to have the `predictionAnalysis.py` file saved in the same folder.

Please let me know if you were able to run the filtering script and whether it worked.

Best,
Tomas

**Comment by MeiyuanJi** [comment]
Thanks Tomas.

Let's me try this tool and update you then.

Best,
Meiyuan

**Comment by MeiyuanJi** [comment]
Hi Yizhong,

I didn't encounter this problem. I guess we might have different methods
for installing BRAKER2. I used conda to create an environment for
installing BRAKER2 dependencies. And updated few tools afterwards for the
job running. Sorry about that.

Meiyuan

**Comment by MeiyuanJi** [comment]
Hi Tomas,

I just ran the script "selectSupportedSubsets.py" given output files from Braker2. This is the result summary:

Total prediction in augustus.hints.aa: 63,323 sequences
Full support: 8,315 transcripts
Partial support: 25,121 transcripts
No support: 38,202 transcripts
Expected values based on reference genome: ~43,000 protein coding. 

I might use the fully and partially supported trancripts as confident prediction. And for no-support, further evaluation is need. I heard some people using IntroProScan for protein domain searching, or using Blast searching the refseq database. That might be useful for the no-supported transcripts correction. Your script is very helpful.

I have a question about the number. As you can find, the sum of (full + partial + no) != augustus prediction. Can you explain a little bit about it? 

Many thanks. 

Meiyuan

**Comment by tomasbruna** [comment]
Hi Meiyuan,

> IntroProScan for protein domain searching, or using Blast searching the refseq database.

Those are both good choices I would recommend as well.

> I have a question about the number. As you can find, the sum of (full + partial + no) != augustus prediction. Can you explain a little bit about it?

The set of _full_ is a subset of _partial_.

Best,
Tomas

**Comment by Hans-zhao831** [comment]
@MeiyuanJi 

Hi Meiyuan，
I think your experience is very helpful, but I don't understand why the first round used a hard-masked genome and the second round used the soft-masked one. Why is it set up this way? And may I ask which literature is referenced for this operation?

Thanks in advance

**Comment by tianjio** [comment]
> `augustus.hints.gtf``hintsfile.gff`
Hi Tomas,
I used this command'python selectSupportedSubsets.py hintsfile.gff augustus.hints.gtf --fullSupport  fullsupport.gff --anySupport anySupport.gff --noSupport nosupport.gff',The script works well，but there is nothing in the three output files.

Many thanks in advance.
Best,
Tian
