### ISSUE TITLE
optimize_augustus.pl line 1224:Could not read the accuracy values out of predictions.txt when processing bucket 1

### ISSUE THREAD

**Issue by tuguangxian** [Gaius-Augustus/BRAKER#32]
While using BRAKER2 I keep getting such error:
my code:
perl /he_lab/share/data/tuguangxian/tgx/software/miniconda3/envs/augustus/bin/optimize_augustus.pl --rounds=5 --species=qiaozuigui --kfold=9  --AUGUSTUS_CONFIG_PATH=/he_lab/share/data/local/augustus/augustus-3.3.2/config --onlytrain=/he_lab/share/data/tuguangxian/tgx/data/genome/qiaozuigui/nGS/05_braker2/braker/qiaozuigui/train.gb.train.train --cpus=9 /he_lab/share/data/tuguangxian/tgx/data/genome/qiaozuigui/nGS/05_braker2/braker/qiaozuigui/train.gb.train.test 1>/he_lab/share/data/tuguangxian/tgx/data/genome/qiaozuigui/nGS/05_braker2/braker/qiaozuigui/optimize_augustus.stdout

error:
replaced tx with 0 MEA txs
replaced tx with 0 MEA txs
replaced tx with 0 MEA txs
sh: 行 1: 81016 段错误               (核心已转储) augustus --species=qiaozuigui --AUGUSTUS_CONFIG_PATH=/he_lab/share/data/local/augustus/augustus-3.3.2/config/ --/Constant/dss_end=4 --/Constant/dss_start=3 --/Constant/ass_start=3 --/Constant/ass_end=2 --/Constant/ass_upwindow_size=30 --/IntronModel/d=100 --/IntronModel/ass_motif_memory=3 --/IntronModel/ass_motif_radius=3 --/ExonModel/tis_motif_memory=3 --/ExonModel/tis_motif_radius=2 --/Constant/trans_init_window=20 --/Constant/init_coding_len=15 --/ExonModel/patpseudocount=5.0 --/ExonModel/etpseudocount=3 --/ExonModel/etorder=2 --/Constant/intterm_coding_len=5 --/ExonModel/slope_of_bandwidth=0.3 --/ExonModel/minwindowcount=10 --/IGenicModel/patpseudocount=5.0 --/IntronModel/patpseudocount=5.0 --/IntronModel/slope_of_bandwidth=0.4 --/IntronModel/minwindowcount=4 --/IntronModel/asspseudocount=0.00266 --/IntronModel/dsspseudocount=0.0005 --/IntronModel/dssneighborfactor=0.00173 --/ExonModel/minPatSum=233.3 --/Constant/probNinCoding=0.23 --/Constant/decomp_num_steps=1 --/ExonModel/infile=exon-tmp2.pbl --/IntronModel/infile=intron-tmp2.pbl --/IGenicModel/infile=igenic-tmp2.pbl --/UtrModel/infile=utr-tmp2.pbl tmp_opt_qiaozuigui/bucket2.gb > tmp_opt_qiaozuigui/predictions-2.txt
Could not read the accuracy values out of predictions.txt when processing bucket 1. at /he_lab/share/data/tuguangxian/tgx/software/miniconda3/envs/augustus/bin/optimize_augustus.pl line 1224
any idea what may be the reason?Thank you!

**Comment by KatharinaHoff** [comment]
The message means that initially a transcript with a spliced stop codon was predicted by AUGUSTUS. Then MEA was executed to re-predict in that region and (most likely) predict a transcript without stop codon. I am not sure why this produced an error in optimize_augustus.pl, though.

**Comment by KatharinaHoff** [comment]
@MarioStanke I tried locating the message in AUGUSTUS code and cannot find it. Please have a look.

**Comment by tuguangxian** [comment]
Thank you very much!
 In the ../errors/GeneMark-ET.stderr folder, there are such errors, will be associated with it? 

(in cleanup)    (in cleanup)  at /usr/local/share/perl/5.26.1/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /usr/local/share/perl/5.26.1/Object/InsideOut.pm line 1953 during global destruction.

**Comment by tuguangxian** [comment]
> The message means that initially a transcript with a spliced stop codon was predicted by AUGUSTUS. Then MEA was executed to re-predict in that region and (most likely) predict a transcript without stop codon. I am not sure why this produced an error in optimize_augustus.pl, though.

Thank you very much!
In the ../errors/GeneMark-ET.stderr folder, there are such errors, will be associated with it?

(in cleanup) (in cleanup) at /usr/local/share/perl/5.26.1/Object/InsideOut.pm line 1953 during global destruction.
(in cleanup) (in cleanup) at /usr/local/share/perl/5.26.1/Object/InsideOut.pm line 1953 during global destruction.

**Comment by KatharinaHoff** [comment]
The errors are not related.
