### ISSUE TITLE
true positive rate of BRAKER's annotation about exons

### ISSUE THREAD

**Issue by bam2wigKillMe** [Gaius-Augustus/BRAKER#321]
Is there a way to find out the statistics of BRAKER's annotation about exons, like true positive rate, when the species is a new species or well annotated in public databases?
My tutor told me there is such things when BRAKER is training and iterating. So I read the braker.log but found nothing but many comands. And Neither has the README of BRAKER.
Could you please tell me a way to get these statistics, or is it possible to know these statistics when BRAKER annotation a new species or a well studied model species?
Thank you for your attention, Best Wishes.

**Comment by tomasbruna** [comment]
Hello,

for a well-studied species, you can supply a reference annotation using the options:

- `--eval=reference.gtf`  Reference set to evaluate predictions against.
- `--eval_pseudo=pseudo.gff3` File with pseudogenes that will be excluded from accuracy evaluation (may be empty file).

The `--eval_pseudo` option needs to be specified but you can supply an empty file in case you do not have any annotated pseudogenes.

The accuracy results will be saved to a file called `eval.summary`.

You can also run this evaluation separately with the  [compare_intervals_exact.pl](https://github.com/Gaius-Augustus/BRAKER/blob/master/scripts/compare_intervals_exact.pl) script.

---

For a new species for which a reference annotation does not exist, you can evaluate the completeness of your predicted gene set with BUSCO. You can take a look at how we did this to evaluate BRAKER2 accuracy in the [paper about BRAKER2](https://academic.oup.com/nargab/article/3/1/lqaa108/6066535#222619774). The [supplementary material of the paper](https://academic.oup.com/nargab/article/3/1/lqaa108/6066535#supplementary-data) has specific commands that can be used to do the BUSCO analysis (section 1.11.5).

Best,
Tomas

**Comment by bam2wigKillMe** [comment]
Thank you, Tomas, that's really helpful, I will try these methods now!

Best.
