### ISSUE TITLE
GUSHR output

### ISSUE THREAD

**Issue by francicco** [Gaius-Augustus/BRAKER#322]
Hi,

I'm using GUSHR to get the UTRs with `--AUGUSTUS_ab_initio --gff3 --addUTR=on`. I guess the final output would be `augustus.hints_utr.gtf`/`augustus.hints_utr.gff3`.

Unfortunately, both don't have the `exon` feature. That makes the conversion to a bed12 format quite complicated for me.

`augustus.ab_initio_utr.gff` and `augustus.ab_initio_utr.gtf` have it. Would it be possible to have it as well for `augustus.hints_utr`?

Thanks a lot
F

**Comment by aubombarely** [comment]
Hello, 

  I have the same problem. The GTF/GFF files do not have "exon" features. Did someone fix this issue?

  Thanks

   Best regards

   Aureliano

**Comment by francicco** [comment]
I make a script of my own.
F

**Comment by tomomano** [comment]
I also have the same problem. I hope it will be fixed in future updates.

@aubombarely May I ask how you fixed it?

**Comment by francicco** [comment]
Guys, see if this script helps you
https://github.com/francicco/-ComparativeGenomicsOfHeliconiini/blob/main/BRAKER-gushrGFF3toBED12v1.0.py

F

**Comment by tomomano** [comment]
@francicco 

Thank you very much for sharing the script.
I was reading it, and I wonder if you did some preprocessing on the GTF before running this python script.

GTF file produced by BRAKER (augustus.hints_utr.gtf) is not strictly following GTF specification, which usually look something like this:

```
Scaffold_1	GUSHR	gene	32915	41645	.	+	.	g23776
Scaffold_1	GUSHR	transcript	32915	41645	.	+	.	g23776.t1
Scaffold_1	AnnotationFinalizer	5'-UTR	32915	34406	.	+	.	transcript_id "g23776.t1"; gene_id "g23776";
Scaffold_1	AUGUSTUS	start_codon	34407	34409	.	+	0	transcript_id "g23776.t1"; gene_id "g23776";
Scaffold_1	AUGUSTUS	CDS	34407	34985	1	+	0	transcript_id "g23776.t1"; gene_id "g23776";
Scaffold_1	AUGUSTUS	stop_codon	34983	34985	.	+	0	transcript_id "g23776.t1"; gene_id "g23776";
```

In rows of "gene" type, there is no "ID" attribute nor "gene_ID" attribute.
Likewise, rows of "transcript" type contain no "ID" nor "transcript_ID" attribute.
This is very annoying.

After looking at your code, I noticed that you assume the presence of these attributes?
I mean, I can quickly fix GTF by adding these attributes, but I wonder if you have any suggested preprocessing tool to fix GTF.

Again, thank you for sharing the code and this is a very nice example to teach me how I should recover missing exon tags.

**Comment by tomomano** [comment]
@francicco 
OK, I found this script (https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/gtf2gff.pl).
Using GFF file generated by `gtf2gff.pl`, your Python script worked beautifully. Thank you.

**Comment by francicco** [comment]
Great! Happy to help! It took me a while to make it work! If you use it in for a paper let me know!
Cheers
F
