### ISSUE TITLE
AddUTR=on on braker output

### ISSUE THREAD

**Issue by KristinaGagalova** [Gaius-Augustus/BRAKER#324]
Hi, 

I am running the ```AddUTR=on``` with the braker.gtf from a previous run.

For some of the genes, I am having a huge mismatch of the UTR assignments (UTRs are assigned to the gene very far away from the star/stop codon).

I attach an example in the screenshot.
![Screenshot from 2021-02-19 10-54-18](https://user-images.githubusercontent.com/25466163/108573242-fdae0d00-72c8-11eb-8e55-a6d439d7eecf.png)

Is the braker.gtf format maybe not suitable for ```AddUTR=on```?

Thank you in advance for the help

**Comment by KatharinaHoff** [comment]
It's a problem in the method. I will close here because we won't fix it on this end of the software.
