### ISSUE TITLE
esource: invalid source key: RM 

### ISSUE THREAD

**Issue by francicco** [Gaius-Augustus/BRAKER#325]
Hi,

I'm many genomes to annotate with BRAKER only few fail. The error I get from one of the is in the `Third etraining - now with CRF` step. Etraining throw me this error:

/mnt/storage/home/tk19812/scratch/software/Augustus/bin/etraining: ERROR
	FeatureCollection::esource: invalid source key: RM

Anything I can do?

Thanks
F

**Comment by KatharinaHoff** [comment]
Can you please provide the braker.log file and if there is a
etraining.stdout & etraining.stderr file, these files, too?

It seems a weird error because the hints should not go into training at
all. RM is our source key for repeat masker information. It's a hints
source key.

**Comment by francicco** [comment]
Hi @KatharinaHoff 

Here are the files:

[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/6027928/braker.log)
[crftraining.stderr.txt](https://github.com/Gaius-Augustus/BRAKER/files/6027929/crftraining.stderr.txt)
[crftraining.stdout.txt](https://github.com/Gaius-Augustus/BRAKER/files/6027930/crftraining.stdout.txt)

Thanks
F

**Comment by francicco** [comment]
Hi Katharina,

Any update?

Cheers
F

**Comment by monpau** [comment]
Hi, 
I've also experiencing the same error. My braker.log and crftraining.std* look exactly the same as Francisco's. 

Any suggestions?

Thanks

**Comment by tiramisutes** [comment]
Hi,
I'm also experiencing the same error.

**Comment by WenChangYu** [comment]
Hi, 
I also experience the same error.

Any help?

**Comment by WenChangYu** [comment]
Hi,
When I use --crf option, I encounter the same error.

Any suggestions?

**Comment by kmkocot** [comment]
I am having the same issue when trying to use --crf here. I'm using braker.pl version 2.1.6 and Augustus 3.4.0.

**Comment by kmkocot** [comment]
Hi all. Switching back from Augustus 3.4.0 to 3.3.3 fixed this issue for me for what it's worth.

**Comment by RenscoHogers** [comment]
Hi all, indeed switching to 3.3.3 worked to fix this issue, but is there any progress on fixing this issue in 3.4.0?

**Comment by KatharinaHoff** [comment]
@MarioStanke have we fixed this in the current AUGUSTUS?
