### ISSUE TITLE
braker2/augustus gff3 output

### ISSUE THREAD

**Issue by michieitel** [Gaius-Augustus/BRAKER#33]
Hi!

How can I transfer the output gff3 of the Braker2 ab initio gene annotation pipeline to a valid EMBL flat file that I can submit to ENA?

I tried using EMBLmyGFF3 (https://github.com/NBISweden/EMBLmyGFF3). The tool seems working fine, but the BRAKER gff3 seems to be non-standard and I am always getting warnings and error  messages like this (just dropped the first lines of the log):

> 13:59:49 ERROR feature: >>stop_codon<< is not a valid EMBL feature type. You can ignore this message if you don't need the feature.
> Otherwise tell me which EMBL feature it corresponds to by adding the information within the json mapping file.
> 13:59:49 ERROR feature: >>start_codon<< is not a valid EMBL feature type. You can ignore this message if you don't need the feature.
> Otherwise tell me which EMBL feature it corresponds to by adding the information within the json mapping file.
> 13:59:51 ERROR feature: >>inferred_parent<< is not a valid EMBL feature type. You can ignore this message if you don't need the feature.
> Otherwise tell me which EMBL feature it corresponds to by adding the information within the json mapping file.
> 13:59:51 WARNING feature: Partial CDS. The CDS with ID = g5589.t1.braker.CDS2 not a multiple of three.
> /home/meitel/.local/lib64/python2.7/site-packages/Bio/Seq.py:2071: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
>   BiopythonWarning)
> 13:59:52 WARNING feature: Partial CDS. The CDS with ID = g5848.t1.braker.CDS2 not a multiple of three.
> 13:59:52 WARNING feature: Partial CDS. The CDS with ID = g5903.t1.braker.CDS3 not a multiple of three.
> 13:59:52 WARNING feature: Partial CDS. The CDS with ID = g5825.t1.braker.CDS2 not a multiple of three.
> 13:59:52 WARNING feature: Partial CDS. The CDS with ID = g6051.t1.braker.CDS1 not a multiple of three.
> 13:59:52 WARNING feature: Partial CDS. The CDS with ID = g5770.t1.braker.CDS2 not a multiple of three.
> 13:59:52 WARNING feature: Partial CDS. The CDS with ID = g5770.t1.braker.CDS3 not a multiple of three.
> 13:59:52 WARNING feature: Partial CDS. The CDS with ID = g5770.t1.braker.CDS4 not a multiple of three.
> 13:59:52 WARNING feature: Partial CDS. The CDS with ID = g5770.t1.braker.CDS5 not a multiple of three.
> 13:59:52 WARNING feature: Partial CDS. The CDS with ID = g5770.t1.braker.CDS7 not a multiple of three.
> 

I am basically getting this error for all genes and wonder if the braker2 gff is non-standard.

These are the first lines of the output gff3:

> scaffold_154	AUGUSTUS	gene	5501	7878	0.85	-	.	ID=g1.braker;
> scaffold_154	AUGUSTUS	mRNA	5501	7878	0.52	-	.	ID=g1.t1.braker;Parent=g1.braker
> scaffold_154	AUGUSTUS	stop_codon	5501	5503	.	-	0	Parent=g1.t1.braker;
> scaffold_154	AUGUSTUS	CDS	5501	5587	0.85	-	0	ID=g1.t1.braker.CDS1;Parent=g1.t1
> scaffold_154	AUGUSTUS	exon	5501	5587	.	-	.	ID=g1.t1.braker.exon1;Parent=g1.t1;
> scaffold_154	AUGUSTUS	intron	5588	7152	0.84	-	.	Parent=g1.t1.braker;
> scaffold_154	AUGUSTUS	CDS	7153	7878	0.57	-	0	ID=g1.t1.braker.CDS2;Parent=g1.t1
> scaffold_154	AUGUSTUS	exon	7153	7878	.	-	.	ID=g1.t1.braker.exon2;Parent=g1.t1;
> scaffold_154	AUGUSTUS	start_codon	7876	7878	.	-	0	Parent=g1.t1.braker;
> scaffold_154	AUGUSTUS	mRNA	6946	7878	0.33	-	.	ID=g1.t2.braker;Parent=g1.braker
> scaffold_154	AUGUSTUS	stop_codon	6946	6948	.	-	0	Parent=g1.t2.braker;
> scaffold_154	AUGUSTUS	CDS	6946	7878	0.33	-	0	ID=g1.t2.braker.CDS1;Parent=g1.t2
> scaffold_154	AUGUSTUS	exon	6946	7878	.	-	.	ID=g1.t2.braker.exon1;Parent=g1.t2;
> scaffold_154	AUGUSTUS	start_codon	7876	7878	.	-	0	Parent=g1.t2.braker;
> scaffold_154	AUGUSTUS	gene	10822	13441	0.34	+	.	ID=g2.braker;
> scaffold_154	AUGUSTUS	mRNA	10822	13441	0.34	+	.	ID=g2.t1.braker;Parent=g2.braker
> scaffold_154	AUGUSTUS	start_codon	10822	10824	.	+	0	Parent=g2.t1.braker;
> scaffold_154	AUGUSTUS	CDS	10822	10946	0.42	+	0	ID=g2.t1.braker.CDS1;Parent=g2.t1
> scaffold_154	AUGUSTUS	exon	10822	10946	.	+	.	ID=g2.t1.braker.exon1;Parent=g2.t1;
> scaffold_154	AUGUSTUS	intron	10947	11358	0.42	+	.	Parent=g2.t1.braker;
> scaffold_154	AUGUSTUS	CDS	11359	11608	0.49	+	1	ID=g2.t1.braker.CDS2;Parent=g2.t1
> scaffold_154	AUGUSTUS	exon	11359	11608	.	+	.	ID=g2.t1.braker.exon2;Parent=g2.t1;
> scaffold_154	AUGUSTUS	intron	11609	13147	0.38	+	.	Parent=g2.t1.braker;
> scaffold_154	AUGUSTUS	CDS	13148	13441	0.38	+	0	ID=g2.t1.braker.CDS3;Parent=g2.t1
> scaffold_154	AUGUSTUS	exon	13148	13441	.	+	.	ID=g2.t1.braker.exon3;Parent=g2.t1;
> scaffold_154	AUGUSTUS	stop_codon	13439	13441	.	+	0	Parent=g2.t1.braker;
> 
> 

Any suggestions/comments are highly appreciated.

Michael

**Comment by Juke34** [comment]
More information about the issue can be found here: https://www.biostars.org/p/374463/

You copied pasted this gff sample in the biostars post: 

> scaffold_001 AUGUSTUS gene 2081205 2082079 1 + . ID=g5848.braker; 
> scaffold_001 AUGUSTUS mRNA 2081205 2082079 1 + . ID=g5848.t1.braker;Parent=g5848.braker 
> scaffold_001 AUGUSTUS start_codon 2081205 2081207 . + 0 Parent=g5848.t1.braker; 
> scaffold_001 AUGUSTUS CDS 2081205 2081252 1 + 0 ID=g5848.t1.braker.CDS1;Parent=g5848.t1 
> scaffold_001 AUGUSTUS exon 2081205 2081252 . + . ID=g5848.t1.braker.exon1;Parent=g5848.t1; 
> scaffold_001 AUGUSTUS intron 2081253 2081594 1 + . Parent=g5848.t1.braker; 
> scaffold_001 AUGUSTUS CDS 2081595 2081656 1 + 0 ID=g5848.t1.braker.CDS2;Parent=g5848.t1 
> scaffold_001 AUGUSTUS exon 2081595 2081656 . + . ID=g5848.t1.braker.exon2;Parent=g5848.t1; 
> scaffold_001 AUGUSTUS intron 2081657 2081747 1 + . Parent=g5848.t1.braker; 
> scaffold_001 AUGUSTUS CDS 2081748 2081820 1 + 1 ID=g5848.t1.braker.CDS3;Parent=g5848.t1 
> scaffold_001 AUGUSTUS exon 2081748 2081820 . + . ID=g5848.t1.braker.exon3;Parent=g5848.t1; 
> scaffold_001 AUGUSTUS intron 2081821 2081890 1 + . Parent=g5848.t1.braker; 
> scaffold_001 AUGUSTUS CDS 2081891 2082079 1 + 0 ID=g5848.t1.braker.CDS4;Parent=g5848.t1 
> scaffold_001 AUGUSTUS exon 2081891 2082079 . + . ID=g5848.t1.braker.exon4;Parent=g5848.t1; 
> scaffold_001 AUGUSTUS stop_codon 2082077 2082079 . + 0 Parent=g5848.t1.braker;

There is a problem with ID/parent relationship. Parent `Parent=g5848.t1;`does not exist while the transcript ID is `g5848.t1.braker`. Only intron features have the correct parent.
In top of that the feature with the ID `g5848.t1.braker.CDS4`do not have the semi-colon at the end of the line. 
So the file is corrupted.

What is the command line you have generated to produce this output?
Do you have modified the BRAKER output file before using it as input of EMBLmyGFF3?

**Comment by KatharinaHoff** [comment]
First (of possible further) answers:

BRAKER usually produces the following type of output if --gff3 is enabled:

```

2R      AUGUSTUS        gene    404098  404511  0.72    +       .       ID=g1;
2R      AUGUSTUS        mRNA    404098  404511  0.72    +       .       ID=g1.t1;Parent=g1;
2R      AUGUSTUS        start_codon     404098  404100  .       +       0       Parent=g1.t1;
2R      AUGUSTUS        CDS     404098  404511  0.72    +       0       ID=g1.t1.CDS1;Parent=g1.t1;
2R      AUGUSTUS        exon    404098  404511  .       +       .       ID=g1.t1.exon1;Parent=g1.t1;
2R      AUGUSTUS        stop_codon      404509  404511  .       +       0       Parent=g1.t1;
2R      AUGUSTUS        gene    495318  642389  0.43    +       .       ID=g2;
2R      AUGUSTUS        mRNA    495318  642389  0.43    +       .       ID=g2.t1;Parent=g2;
2R      AUGUSTUS        start_codon     495318  495320  .       +       0       Parent=g2.t1;
2R      AUGUSTUS        CDS     495318  495329  0.61    +       0       ID=g2.t1.CDS1;Parent=g2.t1;
2R      AUGUSTUS        exon    495318  495329  .       +       .       ID=g2.t1.exon1;Parent=g2.t1;
2R      AUGUSTUS        intron  495330  495603  0.82    +       .       Parent=g2.t1;
2R      AUGUSTUS        CDS     495604  495784  0.85    +       0       ID=g2.t1.CDS2;Parent=g2.t1;
2R      AUGUSTUS        exon    495604  495784  .       +       .       ID=g2.t1.exon2;Parent=g2.t1;
2R      AUGUSTUS        intron  495785  547231  1       +       .       Parent=g2.t1;
2R      AUGUSTUS        CDS     547232  547363  1       +       2       ID=g2.t1.CDS3;Parent=g2.t1;
2R      AUGUSTUS        exon    547232  547363  .       +       .       ID=g2.t1.exon3;Parent=g2.t1;
2R      AUGUSTUS        intron  547364  578871  1       +       .       Parent=g2.t1;
2R      AUGUSTUS        CDS     578872  578991  1       +       2       ID=g2.t1.CDS4;Parent=g2.t1;
2R      AUGUSTUS        exon    578872  578991  .       +       .       ID=g2.t1.exon4;Parent=g2.t1;
2R      AUGUSTUS        intron  578992  579043  1       +       .       Parent=g2.t1;
2R      AUGUSTUS        CDS     579044  579217  1       +       2       ID=g2.t1.CDS5;Parent=g2.t1;
2R      AUGUSTUS        exon    579044  579217  .       +       .       ID=g2.t1.exon5;Parent=g2.t1;
2R      AUGUSTUS        intron  579218  642099  1       +       .       Parent=g2.t1;
2R      AUGUSTUS        CDS     642100  642389  0.69    +       2       ID=g2.t1.CDS6;Parent=g2.t1;
2R      AUGUSTUS        exon    642100  642389  .       +       .       ID=g2.t1.exon6;Parent=g2.t1;
2R      AUGUSTUS        stop_codon      642387  642389  .       +       0       Parent=g2.t1;
```

I have no idea where the Parent=g1.braker lines come from because I don't see them in my own output. In general, we convert gtf to gff3 with the AUGUSTUS script gff2gtf.pl (https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/gtf2gff.pl), and we have been using it for many years without seeing that kind of problem.

**Comment by KatharinaHoff** [comment]
From the biostars link (thank you, @Juke34 ), I take it that incomplete genes are an issue, here. Augustus will - in general - predict complete and incomplete genes. The incomplete genes are genes at the boundaries of sequences. They are not all "nonsense" or "useless", sometimes, they carry information that people are interested in. You can suppress the prediction of incomplete genes by providing `--augustus_args="genemodel=complete"` to braker.pl .

Another issue might be genes that include stop codons... that happens when AUGUSTUS predicts a gene with a spliced stop codon. We currently don't have a quick fix for this, yet. Working on it.

**Comment by KatharinaHoff** [comment]
BRAKER uses a script to convert AUGUSTUS gtf output to gff3 format, it is gtf2gff.pl. The output of this script was indeed not correct for some features (missing ID field e.g. for intron etc.). I have fixed this (see issue https://github.com/Gaius-Augustus/Augustus/issues/74 and commit https://github.com/Gaius-Augustus/Augustus/commit/842a069ad0d065e08c182eb5f86724d7232601e6 ). The problem should not occur for users of BRAKER, anymore.

I am closing this issue.
