### ISSUE TITLE
Add=UTR produces long introns in UTRs and likely non accurate

### ISSUE THREAD

**Issue by KristinaGagalova** [Gaius-Augustus/BRAKER#351]
Hi, 
Thank you first for BRAKER2 and for trying to maintain it during this difficult time.
I've run BRAKER with the ```AddUTR=on``` option with the following commands, first and second run as recommended by your guidelines
```
braker.pl --GENEMARK_PATH=/home/kgagalova/src/gmes_linux_64 \
        --AUGUSTUS_CONFIG_PATH=/projects/spruceup_scratch/dev/anaconda3/envs/busco4.1.4/config \
        --PROTHINT_PATH=/home/kgagalova/src/gmes_linux_64/ProtHint/bin \
        --species=myspecies \
        --genome=$GENOME \
        --bam=$BAM \
        --prot_seq=$PROTEINS \
        --cores=12 \
        --softmasking \
        --etpmode \
        --useexisting
```
```
braker.pl --GENEMARK_PATH=/home/kgagalova/src/gmes_linux_64 \
        --AUGUSTUS_CONFIG_PATH=/projects/spruceup_scratch/dev/anaconda3/envs/busco4.1.4/config \
        --PROTHINT_PATH=/home/kgagalova/src/gmes_linux_64/ProtHint/bin \
        --GUSHR_PATH=/home/kgagalova/src/GUSHR \
        --species=myspecies \
        --genome=$GENOME \
        --bam=$BAM \
        --cores=24 \
        --softmasking \
        --skipAllTraining \
        --addUTR=on \
        --AUGUSTUS_hints_preds=augustus.hints.gtf
```
About 30% of the predicted UTR features contain quite long introns as shown in the figure below and that's probably an artifact
example: five prime UTR in gene WAG0027609 matches the three prime UTR in WAG0027610
![Selection_060](https://user-images.githubusercontent.com/25466163/113756211-fc447280-96c5-11eb-9212-d046d04fc77c.png)
This looks like it's due to the reads mapping to other UTRs from more distant genes. Is that something that can be corrected by filtering the mapped reads or the distance from the genes?
I believe GUSHR is producing some UTR annotations that are a bit off
Thank you in advance for your reply

**Comment by KristinaGagalova** [comment]
Sorry, the distance track is not visible - the intron length of ```WAG0027609``` is ~30Kbp

**Comment by tomasbruna** [comment]
Hello @KristinaGagalova,

thanks for reporting this problem. We are aware of this issue, the same problem was also reported in https://github.com/Gaius-Augustus/BRAKER/issues/303. There is no active development of GUSHR right now, but this will be one of the first problems to address when we get back to improving the UTR predictions.

Tomas

**Comment by KatharinaHoff** [comment]
We will unlikely solve it in GUSHR. I will close this because we won't fix it. Apologies.
