### ISSUE TITLE
braker2 output: gff file is missing and species folder is empty

### ISSUE THREAD

**Issue by prasoonnema** [Gaius-Augustus/BRAKER#353]
Hello, 
I have to annotate novel diplonema genome. So that I chose to use braker.

I have run command prothint to generate and prothint_augustus.gff used to run braker in next step.

Along with bam file obtained from Star aligner using --twopassMode Basic

1.) prothint.py dj.fa `protein_homo_database.fasta

2.) braker.pl --genome=genome.masked.fa --species=species_name --hints=prothint_augustus.gff --bam genomestaralign.bam --etpmode --softmasking `–AUGUSTUS_ab_initio

genemark.gtf is present, However, Augustus.gff file is missing and species folder is also empty. I am sending the Braker.log for more details as attachment. [braker.log](https://github.com/Gaius-Augustus/BRAKER/files/6317856/braker.log) 

Could anybody please suggest, where I am making mistake or it is fine ? Any suggestion, how can I improve the pipeline ? Thank you very much in advance :)

**Comment by Zea1nfO** [comment]
Hi
  Have you run the test3.sh and test5.sh under the example directory?
  Mabye you should get though it first.
  I also encounter some issue before. Running test can help us to debug.
best

**Comment by prasoonnema** [comment]
Thank you. it is running perfectly now.  I wanted to use genemark accessory script. generateReport.py , but I am getting following script. 
Traceback (most recent call last):
File "generateReport.py", line 18, in
import statistics.predictionAnalysis as analysis
ModuleNotFoundError: No module named 'statistics.predictionAnalysis'; 'statistics' is not a package . 

I

**Comment by tomasbruna** [comment]
@prasoonnema, just out of curiosity, what was the original issue you fixed to make BRAKER2 run?

Thanks,
Tomas

**Comment by prasoonnema** [comment]
@tomasbruna Hi Tomas,  Original error, I could not figure out. I was running the Braker2 on server. I guess, initial error because of permission. I have installed braker2 in my system. And it is working perfectly.  
Thanks, Prasoon
