### ISSUE TITLE
whether to use pipeline D or additional pipeline C when protein data exists?  

### ISSUE THREAD

**Issue by krabapple** [Gaius-Augustus/BRAKER#357]
My genome is small (180 Mb)  and haploid.   As BRAKER2 evidence I have good mapped RNA seq data from this organism, and ~550 same-species/close-species protein sequences. 

Formerly I would use additional pipeline C ["training GeneMark-ET on the basis of RNA-Seq spliced alignment information, training AUGUSTUS on a set of training gene structures compiled from RNA-Seq supported gene structures predicted by GeneMark-ET and spliced alignment of proteins of a very closely related species"], but now I see  "This pipeline is deprecated since pipeline D can also use proteins of closely related species in addition to OrthoDB." (Ditto additional pipeline A, which uses close-protein data for Augustus prediction but not training)

Pipeline D and additional pipelines A/C seem quite different  (e.g. OrthoDB/ProtHint/GeneMarkETP+ vs. proteins.fa/genomethreader/GenemarkET).  Closely-related protein seqs can be added to OrthoDB input for pipeline D.

However the warning for pipeline D is "we found this approach to work well for large genomes, but **accuracy on small and medium sized genomes is unstable."**  

So I'm trying to decide which approach is best  -- pipeline D, because my protein data set is limited to 550 sequences. and OrthoDB input could greatly augment that; but arguing against pipeline D, my genome is too small --  or stay with additional pipelines A/C?

(Or, not use protein evidence at all, since that seems to prevent BRAKER from predicting UTRs??)

**Comment by tomasbruna** [comment]
Hello, I would recommend using the pipeline D (and adding OrthoDB proteins to your closely related ones). You can still add UTRs to the pipeline D, as illustrated in https://github.com/Gaius-Augustus/BRAKER#testing-braker-with-proteins-of-any-evolutionary-distance-and-rna-seq.

The meaning of **accuracy on small and medium-sized genomes is unstable** is a bit misleading. What be observed is that in some genomes, it was better to use proteins alone rather than proteins + RNA-Seq. This was true especially when there were many close proteins available, I would not worry about that since you do not have many closely related proteins.

Hope this helps,
Tomas

**Comment by tomasbruna** [comment]
The RNA-Seq alignment looks good to me

> The BRAKER pipeline has been running for nearly 2 days now but has been stuck here since day 1:

ProtHint outputs its progress to `stderr`, please check that to see at what stage it is.

**Comment by krabapple** [comment]
The only error files generated as of now (nothing has changes since I posted, the script is technically still running) are these:


```

[sullis02@log-1 braker2_May5_pipelineD_1]$ find . -name "*err"
./errors/find_python3_re.err
./errors/new_species.stderr
./errors/GeneMark-ES.stderr
./errors/find_python3_biopython.err


```


None of these prothint outputs, I think?  All of them are empty files.

The dirs and files generated so far are:

```

[sullis02@log-1 braker2_May5_pipelineD_1]$ ls -lgF  --group-directories-first | cut -d " " -f 5-15

    4096 May  5 19:49 diamond/
    4096 May  5 18:55 errors/
    4096 May  5 19:48 GeneMark-ES/
    4096 May  5 18:55 GeneMark-ETP/
  262144 May  7 01:23 Spaln/
    4096 May  5 18:55 species/
    9897 May  5 19:48 braker.log
     513 May  5 19:48 cmd.log
    5719 May  5 19:46 GeneMark-ES.stdout
 4119013 May  5 19:49 gene_stat.yaml
May  5 18:55 genome.fa
    9416 May  5 18:55 genome_header.map
May  5 19:51 nuc.fasta
May  5 18:55 proteins.fa
May  5 19:48 protwu9c4wen
19407749 May  5 19:49 seed_proteins.faa
    1640 May  5 18:55 what-to-cite.txt



```

**Comment by krabapple** [comment]
I notice the slurm file for this batch process contain ProtHint run logging. I am attaching it here

[slurm-6461558.zip](https://github.com/Gaius-Augustus/BRAKER/files/6448260/slurm-6461558.zip)

**Comment by tomasbruna** [comment]
Hello,

it looks like ProtHint is stuck at 99.9%. My best guess is that this error occurred https://github.com/gatech-genemark/ProtHint/issues/14.

Do you have access to the node the code is running on? Killing the stuck Spaln process should immediately solve this problem. If not, let me know -- I wanted to fix this for a while, I can try to make a fix tomorrow and send you a version that will have a timeout for hanging Spaln alignments.

Tomas

**Comment by krabapple** [comment]
Based on your suggestios our sysadmin  killed process 2281719

<img width="1056" alt="PastedGraphic-5" src="https://user-images.githubusercontent.com/49412726/118016819-d98c2600-b323-11eb-85de-8c40d8bf7a2f.png">

This immediately produced one more output fil call 'tmp' and then the entire BRAKER process died.

tmp contains  gtf-like lines like this
```

]$ head tmp
Contig1_pilon_pilon     Spaln_scorer    start_codon     1924117 1924119 .       +       0       prot=412133_1:015690; al_score=0.487603; eScore=5360; seed_gene_id=8989_g; topProt=TRUE;
Contig1_pilon_pilon     Spaln_scorer    CDS     1924117 1927239 .       +       0       prot=412133_1:015690; exon_id=1; eScore=5360; seed_gene_id=8989_g; topProt=TRUE;
Contig1_pilon_pilon     Spaln_scorer    stop_codon      1927240 1927242 .       +       0       prot=412133_1:015690; al_score=0.512397; eScore=5360; seed_gene_id=8989_g; topProt=TRUE;
Contig4_pilon_pilon     Spaln_scorer    start_codon     13650408        13650410        .       +       0       prot=412133_1:00abf7; al_score=0.461157; eScore=991; seed_gene_id=31375_g; topProt=TRUE;
Contig4_pilon_pilon     Spaln_scorer    CDS     13650408        13650989        .       +       0       prot=412133_1:00abf7; exon_id=1; eScore=991; seed_gene_id=31375_g; topProt=TRUE;
Contig4_pilon_pilon     Spaln_scorer    stop_codon      13650990        13650992        .       +       0       prot=412133_1:00abf7; al_score=0.568595; eScore=991; seed_gene_id=31375_g; topProt=TRUE;
Contig4_pilon_pilon     Spaln_scorer    start_codon     13650408        13650410        .       +       0       prot=412133_1:00ddf7; al_score=0.31405; eScore=610; seed_gene_id=31375_g;
Contig4_pilon_pilon     Spaln_scorer    CDS     13650408        13650939        .       +       0       prot=412133_1:00ddf7; exon_id=1; eScore=610; seed_gene_id=31375_g;
Contig4_pilon_pilon     Spaln_scorer    start_codon     13650408        13650410        .       +       0       prot=1144522_1:003e64; al_score=0.0380165; eScore=375; seed_gene_id=31375_g;
Contig4_pilon_pilon     Spaln_scorer    CDS     13650408        13650890        .       +       0       prot=1144522_1:003e64; exon_id=1; eScore=375; seed_gene_id=31375_g;

```

So it doesn't appear that this fix worked.

**Comment by tomasbruna** [comment]
Did you have a chance to run BUSCO or any other quality assessment tool for both outputs? I wonder whether the noisy output from pipeline D also contains more BUSCO genes than the one with close proteins only.

There is also a new way of combining protein and RNA inputs, with TSEBRA: https://www.biorxiv.org/content/10.1101/2021.06.07.447316v1. That should lead to better results than pipeline D.

**Comment by krabapple** [comment]
No, I did not;  I have since abandoned using  RNA and protein inputs together.  I can't use TSEBRA because running BRAKER in RNA evidence only mode (BRAKER1) fails at the GeneMark step (as Dr. Hoff predicted to me), since the only use BRAKER makes of RNA-Seq mapping data is for predicting introns.  My genome is extremely intron-poor, causing GeneMark to fail.  I have not figured out how to alter extrinsic.cfg to employ RNA-seq mapping data for other uses, eg transcript prediction (similar to what Stringtie does).   Meanwhile, running BRAKER in protein-evidence-only mode (BRAKER1)  either fails or succeeds depending on the size and contents of the evidence file. Using the Protozoa subset of OrthoDB as evidence (>1.7 million fasta records)  produces an enourmous number (>95,000) of gene models, though on the positive side,  the maximum #CDS/gene went down to 2.  Using a far smaller set of closely-related proteins (553 fasta records) caused GeneMark to fail due to lack of introns. [error message: "The hints file(s) for GeneMark-EX contain less than 1000 introns. (In total, 88 unique introns are contained.)
# Genemark-EX might fail due to the low number of hints."]

**Comment by KatharinaHoff** [comment]
You can run BRAKER without any evidence to solve the problem that genemark
fails. After the run has finished (ignore the output, you only want to have
the resulting species parameter set) take this hints file from the failed
braker run and the species set from the success run and use both to run
predictions only with braker. Do it once for RNAseq, once for proteins,
then use TSEBRA (but not with the default parameter set, there is a more
relaxed parameter set for species with less evidence).

**Comment by krabapple** [comment]
Hello, thank you for the suggestion.  To help me attempt it, can you clarify the steps? I am confused as to what you mean by the 'success run' and the 'failed run' in this case.  

The _ab initio_ run you are suggesting I do, is that the 'success run'? (and  I should use the species folder/file generated by this?)
And my failed RNAevidence-only BRAKER1 run, is that the 'failed run' ? (and I should use the hints generated by this?)

If not, what runs are you referring to?

**Comment by KatharinaHoff** [comment]
Yes, that's what I meant.
