### ISSUE TITLE
One or more chromosome/scaffold is missing in the final augustus.hints.gtf

### ISSUE THREAD

**Issue by agroppi** [Gaius-Augustus/BRAKER#360]
Hi,

I experienced this issue with the version 2.1.4 last year and now I had the same issue with the 2.1.5 version : 
I work on plant genomes (between 7 to 8 chromosomes)
With the Braker 2.1.4 version, 2 chromosomes out of 8 were missing in the augustus.hints.gtf file.
I was unable to find something wrong in the logs or error files.
Stranger thing... when I looked in gthTrainGenes.gtf ; hintsfile.gff ; genemark_hintsfile.gff the "missing" chromosome(s) is here.
I updated to version 2.1.5 and the problem was gone.
But now on a another plant genome (7 chromosomes) while using Braker 2.1.5 : same issue. One chromosome out of 7 is missing in the augustus.hints.gtf file. But this chromosome is in the other gtf files ...
I have updated to 2.1.6, and the scipt is running.
I hope it will end successfullly.

Any idea about the reason of this issue ?

Thanks

My command line : 

```
braker.pl \
--genome=../genome/mygenome.fasta \
--prot_seq=../close_species_sequences_prot.fasta \
--prg=gth \
--bam=../rnaseq.out.bam \
--gth2traingenes \
--softmasking \
--workingdir=/mydirectory \
--cores 20
```

**Comment by agroppi** [comment]
On clue : 
In the braker.gtf file all the lines for mys "missing chromosome in augustus.hints.gtf file are from Genemark : 
```
chr1	GeneMark.hmm	stop_codon	71396683	71396685	.	-	0	gene_id "115682_g"; transcript_id "115682_t"; count "1_1";
chr1	GeneMark.hmm	CDS	71396683	71396869	.	-	1	gene_id "115682_g"; transcript_id "115682_t"; cds_type "Terminal"; count "3_3";
chr1	GeneMark.hmm	exon	71396683	71396869	0	-	.	gene_id "115682_g"; transcript_id "115682_t"; cds_type "Terminal"; count "3_3";
chr1	GeneMark.hmm	CDS	71396995	71397428	.	-	0	gene_id "115682_g"; transcript_id "115682_t"; cds_type "Internal"; count "2_3";
chr1	GeneMark.hmm	exon	71396995	71397428	0	-	.	gene_id "115682_g"; transcript_id "115682_t"; cds_type "Internal"; count "2_3";
chr1	GeneMark.hmm	CDS	71397520	71398071	.	-	0	gene_id "115682_g"; transcript_id "115682_t"; cds_type "Initial"; count "1_3";
chr1	GeneMark.hmm	exon	71397520	71398071	0	-	.	gene_id "115682_g"; transcript_id "115682_t"; cds_type "Initial"; count "1_3";
chr1	GeneMark.hmm	start_codon	71398069	71398071	.	-	0	gene_id "115682_g"; transcript_id "115682_t"; count "1_1";
```
... ?

**Comment by tomasbruna** [comment]
Hello,

this indeed is a mystery, I have no idea what can be wrong. @KatharinaHoff, have you encountered such an error before?

@agroppi, if this error persists in v2.1.6, can you try running BRAKER2 with ProtHint, as [described here](https://github.com/Gaius-Augustus/BRAKER#braker-with-proteins-of-any-evolutionary-distance) and illustrated in the [test3.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3.sh)? I would like to see if this problem is specific to the GenomeThreader-based way of running BRAKER2, which is now deprecated.

Thanks!
Tomas

**Comment by agroppi** [comment]
Dear @tomasbruna 

I have done many tests : 
1/ Braker 2.1.6 with the former options (see here above)
==> failed with a error linked to python : 
`/usr/bin/env: python3: No such file or directory`
here is the log : 
[braker_2.1.6_gth2traingenes .log](https://github.com/Gaius-Augustus/BRAKER/files/6403765/braker_2.1.6_gth2traingenes.log)

2/ Braker 2.1.6 as you suggested (like test3.sh)
```
braker.pl \
--genome=../genome/mygenome.fasta \
--prot_seq=../orthoDB_proteins.fasta \
--bam=../rnaseq.out.bam \
--etpmode \
--softmasking \
--workingdir=/mydirectory \
--cores 20
```

==> failed with with error : 
```
[Tue Apr 27 23:08:30 2021] ProtHint finished.
ERROR in file /module/apps/braker/2.1.6/bin/braker.pl at line 8072
Failed to execute: /gpfs/module/apps/braker/2.1.6/bin/optimize_augustus.pl --aug_exec_dir=/module/apps/braker/2.1.6/bin --rounds=5 --species=Sp_4 .......
```
I try the resume procedure _2 ; _3 but failed again

3/ I tried to run ProtHint first and then to run braker on only "prothint_augustus.gff"

==> failed with error : 

`failed to execute: etraining --species=Sp_3 --AUGUSTUS_CONFIG_PATH=/module/apps/braker/2.1.6/config/ --/augustus/verbosity=0 --/ExonModel/verbosity=0 --/IGenicModel/verbosity=0 --/IntronModel/verbosity=0 --/UtrModel/verbosity=0 --/genbank/verbosity=0 tmp_opt_Sp_3/curtrain  `

here is the log : 
[braker_2.1.6_Prot_ProtHint_only.log](https://github.com/Gaius-Augustus/BRAKER/files/6403840/braker_2.1.6_Prot_ProtHint_only.log)

Any idea how to solve these issues ?

Thanks again

**Comment by KatharinaHoff** [comment]
Just for the sake of completeness: I have not seen this happening before.

**Comment by agroppi** [comment]
When I tried to run ProtHint first and then to run braker on only "prothint_augustus.gff" : 
```
braker.pl \
--genome=mygenome.fasta \
--hints=prothint_augustus.gff \
--softmasking \
--workingdir=mydirectory \
--cores 20
```
The run fails as described here above (3/)

Then I tried to restart with the restart_3 procedure : 
```
braker.pl \
--genome=./my genome.fasta \
--hints=$oldDir/hintsfile.gff  \
--skipAllTraining \
--species=$species \
--softmasking \ 
--workingdir=$wd \
--cores 20
```
All seems to end well ... but ....
In the log i have : 
```
# Fri Apr 30 15:11:39 2021: AUGUSTUS prediction complete
# Fri Apr 30 15:11:39 2021: Trying to create merged gene set from GeneMark-EX and AUGUSTUS predictions (braker.gtf/braker.utr.gtf)...
# Fri Apr 30 15:11:39 2021: deleting empty files
# Fri Apr 30 15:11:39 2021: find /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3 -empty
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/augustus.hints.tmp.gtf
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/augustus.hints.gtf
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/augustus.hints.aa
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/getAnnoFastaFromJoingenes.augustus.hints_hints.stdout
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/getAnnoFastaFromJoingenes.augustus.hints_tmp.stdout
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/augustus.hints.codingseq
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/errors/find_python3_re.err
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/errors/createAugustusJoblist_hints.stderr
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/errors/getAnnoFastaFromJoingenes.augustus.hints_tmp.stderr
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/errors/splitMfasta.stderr
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/errors/gtf2gff.augustus.hints.gtf.stderr
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/errors/filterIntronsFindStrand_userHints_0.stderr
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/errors/find_python3_biopython.err
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/errors/join_mult_hints.all.stderr
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/errors/getAnnoFastaFromJoingenes.augustus.hints_hints.stderr
# Fri Apr 30 15:11:39 2021: deleting job lst files (if existing)
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/tmp_no_merge_hints.gff
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/aug_hints.lst
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/hints.job.lst
rm /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/tmp_merge_hints.gff
/gpfs/module/apps/braker/2.1.6/bin/braker_cleanup.pl --wdir=/gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3
Deleting file /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/genome.fa
Deleting file /gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only_restart_3/augustus.hints.gff
#**********************************************************************************
#                               BRAKER RUN FINISHED                                
#**********************************************************************************
```

augustus.hints.gff is deleted because it is empty :(

full log is here : 
[braker_2.1.6_Prot_ProtHint_only_restart3.log](https://github.com/Gaius-Augustus/BRAKER/files/6406350/braker_2.1.6_Prot_ProtHint_only_restart3.log)


How can it be possible ?

Thanks

**Comment by tomasbruna** [comment]
Hello @agroppi,

the `restart_3` procedure probably does not work because the training never finished successfully before.

From the log (shared in 3/), everything is looking good until the `optimize_augustus.pl` fails. Can you share the contents of the following log files?

- `/gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only/optimize_augustus.stdout`
- `/gpfs/scratch/ag/Assemblage_Rose/Rosa_wichurana_1.0_Braker2_Annotation/Braker_2.1.6_prothint_done_ProtOrthoDB_only/errors/optimize_augustus.stderr`

I hope this will help us to determine what went wrong during  `optimize_augustus.pl`.

Best,
Tomas

**Comment by agroppi** [comment]
Hi @tomasbruna 

Here are the two files : 
[optimize_augustus.stderr_and_stdout.zip](https://github.com/Gaius-Augustus/BRAKER/files/6413709/optimize_augustus.stderr_and_stdout.zip)
One thing I noticed is that in the stderr the command who failed is  : `etraining `...
However, it should have be with the prefix : `AUGUSTUS_BIN_PATH=/module/apps/braker/2.1.6/bin` ?

Here are all my export path : 
```
export GENEMARK_PATH=/module/apps/GeneMark/4.65
export AUGUSTUS_BIN_PATH=/module/apps/braker/2.1.6/bin
export AUGUSTUS_CONFIG_PATH=/module/apps/braker/2.1.6/config
export AUGUSTUS_SCRIPTS_PATH=/module/apps/braker/2.1.6/bin
export BAMTOOLS_PATH=/module/apps/braker/2.1.6/bin
export BLAST_PATH=/module/apps/braker/2.1.6/bin
export SAMTOOLS_PATH=/module/apps/braker/2.1.6/bin
export PYTHON3_PATH=/module/apps/braker/2.1.6/bin
export CDBTOOLS_PATH=/module/apps/braker/2.1.6/bin
export DIAMOND_PATH=/module/apps/braker/2.1.6/bin
export ALIGNMENT_TOOL_PATH=/module/apps/braker/2.1.6/bin
export PROTHINT_PATH=/module/apps/GeneMark/4.65/ProtHint/bin
```

Thanks again

Alexis

**Comment by tomasbruna** [comment]
Hi Alexis,

thanks for sharing the logs, I think I know what's happening now.

There is a bug in `optimize_augustus.pl` -- at some point when it calls `etraining`, it assumes that the binary is present in your `$PATH`.

This bug was fixed in https://github.com/Gaius-Augustus/Augustus/commit/d1c4f9f335579a69f3b56e54f02cf0c36a1ed7ba so you can resolve this issue by replacing `optimize_augustus.pl` in `/gpfs/module/apps/braker/2.1.6/bin/` by the [fixed version](https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/optimize_augustus.pl).

Or, you can add `etraining` to your `$PATH`:

    export PATH=/module/apps/braker/2.1.6/bin:$PATH

Best,
Tomas

**Comment by agroppi** [comment]
Hi @tomasbruna
Hooray! :)
It works
Thank you for your help

Cheers from Bordeaux (France)

Alexis

**Comment by tomasbruna** [comment]
Hi Alexis,

Great news! Greetings from Atlanta :)

Tomas
