### ISSUE TITLE
Braker runnign time?

### ISSUE THREAD

**Issue by chodarq** [Gaius-Augustus/BRAKER#363]
Hi all,
Just a quick question. According to the recomentation of use 1 core for braker run. There is an estimated running time for braker pipeline with proteins?
This is my command line:

`braker.pl --genome=C_horridus_ref.fna.mask --species==Choridus --prot_seq=busco.fa --epmode --gff3 --cores=1`
The assembly is about 1.3Gb. Tomas already told me about change my DB to OrthoDB for the multiplicity issue. But, with the current run, it's expected that braker was running for about 4 days? Im running in a server with 30 cores and 256Gb of memory.

Thanks! All the best,
Christian.

**Comment by tomasbruna** [comment]
Hello Christian,

> According to the recomentation of use 1 core for braker run.

Do you mean this recommendation?

https://github.com/Gaius-Augustus/BRAKER/blob/639355a1017a2ca541b2751601acee36e7e66b3f/scripts/braker.pl#L1336-L1349

I would actually recommend trying to use 30 cores and see whether everything works. A run with just 1 core would be pretty slow on such a large genome.

To give a more specific runtime estimate -- we've recently run BRAKER2 with Vertebrata proteins on X. tropicalis (1.4Gb). Using 8 CPUs, the run took a little under 4 days to complete. The ProtHint part itself (protein mapping) took about 12 hours in that run, the most time-consuming step is usually the AUGUSTUS training.

Best,
Tomas

**Comment by chodarq** [comment]
Hi Tomas,
It's exactly those recomendation. Some of the asemblies that i'm using are very fractioned. Anyway, thanks for the estimation and for tour help.
All the best,
Christian.
