### ISSUE TITLE
Error while running BRAKER with --AUGUSTUS_ab_initio and --gff3

### ISSUE THREAD

**Issue by zx-morningstar** [Gaius-Augustus/BRAKER#365]
Here is my braker(2.1.6) run:
`# BRAKER CALL: $braker/scripts/braker.pl --cores=8 --gff3 --softmasking --genome=$genome/genome.fa --AUGUSTUS_ab_initio --hints=hintsfile.gff --workingdir=wd`

last cmd in the braker.log:
`# Thu Apr 29 08:57:52 2021: converting gtf file $wd/braker.gtf to gff3 format , outputfile $wd/braker.gff3.`
`cat $wd/braker.gtf | perl -ne 'if(m/\tAUGUSTUS\t/ or m/\tAnnotationFinalizer\t/ or m/\tGUSHR\t/ or m/\tGeneMark.hmm\t/) {print $_;}' | perl $augustus/scripts/gtf2gff.pl --gff3 --out=$wd/braker.gff3 >> $wd/gtf2gff3.log 2>> $wd/errors/gtf2gff3.err
`

here is the file errors/gtf2gff3.err:
`transcript file_1_file_1_g12306.t1 has conflicting gene parents: and file_1_file_1_g12306. Remember: In GTF txids need to be overall unique. at $augustus/scripts/gtf2gff.pl line 120, <STDIN> line 1269312.`

and braker crashed after outputed to errors/gtf2gff3.err.

**Comment by tomasbruna** [comment]
Hello,

can you share your `braker.gtf` file? I was trying to reproduce this error but the conversion works for me...

Until this is fixed, please try converting the `gtf` output with [GenomeTools](http://genometools.org/), like this

```
gt gtf_to_gff3 <(grep -P "\tCDS\t|\texon\t" braker.gtf ) > braker.gff
```

Tomas

**Comment by bam2wigKillMe** [comment]
Hello Tomas,
Thank you for your reply.
My braker.gtf file is over 100Mb, I can reproduce the error with the first gene in the file. Here it is:
`Chr3	AUGUSTUS	stop_codon	25123910	25123912	.	-	0	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	CDS	25123910	25124119	1	-	0	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	exon	25123910	25124119	.	-	.	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	intron	25124120	25124515	1	-	.	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	CDS	25124516	25124695	1	-	0	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	exon	25124516	25124695	.	-	.	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	intron	25124696	25125162	1	-	.	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	CDS	25125163	25125264	1	-	0	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	exon	25125163	25125264	.	-	.	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	intron	25125265	25127125	1	-	.	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	CDS	25127126	25127264	1	-	1	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	exon	25127126	25127264	.	-	.	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	intron	25127265	25127793	1	-	.	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	CDS	25127794	25128013	1	-	2	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	exon	25127794	25128013	.	-	.	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	intron	25128014	25128977	1	-	.	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	CDS	25128978	25129005	1	-	0	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	gene	25123910	25129005	1	-	.	file_1_file_1_g29573
Chr3	AUGUSTUS	transcript	25123910	25129005	1	-	.	file_1_file_1_g29573.t1
Chr3	AUGUSTUS	exon	25128978	25129005	.	-	.	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
Chr3	AUGUSTUS	start_codon	25129003	25129005	.	-	0	transcript_id "file_1_file_1_g29573.t1"; gene_id "file_1_file_1_g29573";
`

Sent from Mail for Windows 10
