### ISSUE TITLE
Failed to execute mv genemark_hintsfile.gff.rnaseq.tmp genemark_hintsfile.gff

### ISSUE THREAD

**Issue by ZhenyanLuo** [Gaius-Augustus/BRAKER#366]
Hi,

I am trying to use BRAKER2 to predict genes based on protein sequence from remote species only. The version I used was 2.1.6.
Command I used was  ./braker_2.1.6/BRAKER/scripts/braker.pl --cores=15 --genome=/home/zhenyan/NLR_project/tmp/Eglobulus_101_V1_cp_all_20kbflanking_removed.fasta --prot_seq=/home/zhenyan/NLR_project/genome/prothint_sequences.fa --species=Eglobulus_101_V1_cp --gff3 --prg=spaln --epmode=1
Then I got error:
cannot stat '/home/zhenyan/NLR_project/braker/genemark_hintsfile.gff.rnaseq.tmp': No such file or directory
ERROR in file ./braker.pl at line 6305
Failed to execute: mv /home/zhenyan/NLR_project/braker/genemark_hintsfile.gff.rnaseq.tmp /home/zhenyan/NLR_project/braker/genemark_hintsfile.gff
I can find genemark_hintsfile.gff.rnaseq in the output folder, but no genemark_hintsfile.gff.rnaseq.tmp

braker.log looks like this:
# Sun May  2 22:50:50 2021: Creating parameter template files for AUGUSTUS with new_species.pl
# Sun May  2 22:50:50 2021: new_species.pl will create parameter files for species Eglobulus_101_V1_cp in /home/zhenyan/anaconda3/envs/snakemake/config//species/Eglobulus_101_V1_cp
perl /home/zhenyan/NLR_project/Augustus/scripts/new_species.pl --species=Eglobulus_101_V1_cp --AUGUSTUS_CONFIG_PATH=/home/zhenyan/anaconda3/envs/snakemake/config/ 1> /dev/null 2>/home/zhenyan/NLR_project/braker/errors/new_species.stderr
# Sun May  2 22:50:50 2021: check_fasta_headers(): Checking fasta headers of file /home/zhenyan/NLR_project/tmp/Eglobulus_101_V1_cp_all_20kbflanking_removed.fasta
# Sun May  2 22:50:52 2021: check_fasta_headers(): Checking fasta headers of file /home/zhenyan/NLR_project/genome/prothint_sequences.fa
# Sun May  2 22:50:52 2021: Assuming that this is not a DNA fasta file because other characters than A, T, G, C, N, a, t, g, c, n were contained. If this is supposed to be a DNA fasta file, check the content of your file! If this is supposed to be a protein fasta file, please ignore this message!
#*********
 WARNING: empty line was removed! This warning will be supressed from now on!
#*********
#**********************************************************************************
#                               PROCESSING HINTS
#**********************************************************************************
# Sun May  2 22:50:52 2021: Making protein hints
# Sun May  2 22:50:52 2021: Changing to /home/zhenyan/NLR_project/braker
cd /home/zhenyan/NLR_project/braker
# Sun May  2 22:50:52 2021: running Spaln to produce protein to genome alignments
perl /home/zhenyan/NLR_project/Augustus/scripts/startAlign.pl --genome=/home/zhenyan/NLR_project/braker/genome.fa --prot=/home/zhenyan/NLR_project/genome/prothint_sequences.fa --ALIGNMENT_TOOL_PATH=/home/zhenyan/anaconda3/envs/snakemake/bin --prg=spaln --CPU=15 >> /home/zhenyan/NLR_project/braker/startAlign.stdout 2>>/home/zhenyan/NLR_project/braker/errors/startAlign.stderr
# Mon May  3 09:46:47 2021: Alignments from file /home/zhenyan/NLR_project/genome/prothint_sequences.fa created.
# Mon May  3 09:46:47 2021: concatenating alignment file to /home/zhenyan/NLR_project/braker/protein_alignment_spaln.gff3
cat /home/zhenyan/NLR_project/braker/align_spaln/spaln.concat.aln >> /home/zhenyan/NLR_project/braker/protein_alignment_spaln.gff3
# Mon May  3 09:46:53 2021: moving startAlign output files
mv /home/zhenyan/NLR_project/braker/align_spaln /home/zhenyan/NLR_project/braker/align_spaln0
# Mon May  3 09:46:53 2021: Converting alignments from file /home/zhenyan/NLR_project/braker/protein_alignment_spaln.gff3 to hints
# Mon May  3 09:46:53 2021: Converting protein alignment file /home/zhenyan/NLR_project/braker/protein_alignment_spaln.gff3 to hints for AUGUSTUS
perl /home/zhenyan/NLR_project/Augustus/scripts/align2hints.pl --in=/home/zhenyan/NLR_project/braker/protein_alignment_spaln.gff3 --out=/home/zhenyan/NLR_project/braker/prot_hintsfile.aln2hints.temp.gff --prg=spaln
# Mon May  3 09:55:49 2021: concatenating protein hints from /home/zhenyan/NLR_project/braker/prot_hintsfile.aln2hints.temp.gff to /home/zhenyan/NLR_project/braker/prot_hintsfile.temp.gff
cat /home/zhenyan/NLR_project/braker/prot_hintsfile.aln2hints.temp.gff >> /home/zhenyan/NLR_project/braker/prot_hintsfile.temp.gff
# Mon May  3 09:55:54 2021: Checking for hints of src=C and with grp tags that should not be joined according to multiplicity
# Mon May  3 09:56:22 2021: Joining hints that are identical (& from the same source) into multiplicity hints (input file /home/zhenyan/NLR_project/braker/tmp_merge_hints.gff)
# Mon May  3 09:56:22 2021: sort hints of type prot
cat /home/zhenyan/NLR_project/braker/tmp_merge_hints.gff | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -n -k 3,3 | sort -s -k 1,1 >/home/zhenyan/NLR_project/braker/hints.prot.temp.sort.gff
# Mon May  3 10:10:00 2021: join multiple hints
perl /home/zhenyan/NLR_project/Augustus/scripts/join_mult_hints.pl </home/zhenyan/NLR_project/braker/hints.prot.temp.sort.gff >/home/zhenyan/NLR_project/braker/tmp_merge_hints.gff 2>/home/zhenyan/NLR_project/braker/errors/join_mult_hints.prot.stderr
mv /home/zhenyan/NLR_project/braker/tmp_merge_hints.gff /home/zhenyan/NLR_project/braker/prot_hintsfile.temp.gff
# Mon May  3 10:16:49 2021: moving /home/zhenyan/NLR_project/braker/prot_hintsfile.temp.gff to /home/zhenyan/NLR_project/braker/prot_hintsfile.gff
mv /home/zhenyan/NLR_project/braker/prot_hintsfile.temp.gff /home/zhenyan/NLR_project/braker/prot_hintsfile.gff
Deleting /home/zhenyan/NLR_project/braker/prot_hintsfile.temp.gff
# Mon May  3 10:16:49 2021: joining protein and RNA-Seq hints files -> appending /home/zhenyan/NLR_project/braker/prot_hintsfile.gff to /home/zhenyan/NLR_project/braker/hintsfile.gff
cat /home/zhenyan/NLR_project/braker/prot_hintsfile.gff >> /home/zhenyan/NLR_project/braker/hintsfile.gff
# Mon May  3 10:16:50 2021: Deleting /home/zhenyan/NLR_project/braker/prot_hintsfile.gff
# Mon May  3 10:16:50 2021: Moving /home/zhenyan/NLR_project/braker/hintsfile.gff to /home/zhenyan/NLR_project/braker/hintsfile.tmp.gff to enable sorting
mv /home/zhenyan/NLR_project/braker/hintsfile.gff /home/zhenyan/NLR_project/braker/hintsfile.tmp.gff
# Mon May  3 10:16:50 2021: Sorting hints file /home/zhenyan/NLR_project/braker/hintsfile.gff
cat /home/zhenyan/NLR_project/braker/hintsfile.tmp.gff | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -n -k 3,3 | sort -s -k 1,1 > /home/zhenyan/NLR_project/braker/hintsfile.gff
# Mon May  3 10:18:27 2021: Deleting file /home/zhenyan/NLR_project/braker/hintsfile.tmp.gff
rm /home/zhenyan/NLR_project/braker/hintsfile.tmp.gff
# Mon May  3 10:18:27 2021: Preparing hints for running GeneMark
# Mon May  3 10:18:27 2021: Filtering intron hints for GeneMark from /home/zhenyan/NLR_project/braker/hintsfile.gff...
cat /home/zhenyan/NLR_project/braker/genemark_hintsfile.gff.prot | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -k 3,3 | sort -s -k 1,1 | /home/zhenyan/NLR_project/Augustus/scripts/join_mult_hints.pl > /home/zhenyan/NLR_project/braker/genemark_hintsfile.gff.prot.tmp
mv /home/zhenyan/NLR_project/braker/genemark_hintsfile.gff.rnaseq.tmp /home/zhenyan/NLR_project/braker/genemark_hintsfile.gff

I ran test3.sh with RNAseq.hints and protein.fa, it works well without errors. But when I removed --hints option, and add --prg=spaln --epmode=1, I still got the same error as above.

Do you have any suggestion for solving this issue? And, did the command I use have any problem?
Thank you in advance.

**Comment by tomasbruna** [comment]
Hello @ZhenyanLuo,

the BRAKER option `--epmode` does not take an argument. As a result, when it is used as `--epmode=1`, Perl does not know what to do with the argument `1` and actually sets  `--epmode` to 0. I was not aware of this side effect and I'll look into fixing it.

Anyway, to fix your issue, use a modified call:

```
./braker_2.1.6/BRAKER/scripts/braker.pl --cores=15 --genome=/home/zhenyan/NLR_project/tmp/Eglobulus_101_V1_cp_all_20kbflanking_removed.fasta --prot_seq=/home/zhenyan/NLR_project/genome/prothint_sequences.fa --species=Eglobulus_101_V1_cp --gff3 --epmode
```

Notice that I removed the option `--prg=spaln`. This option is not compatible with `--epmode`, it is only present in BRAKER for historical purposes.

Best,
Tomas

**Comment by ZhenyanLuo** [comment]
Hi @tomasbruna ,

Thank you so much for replying. I have another question, another student used BRAKER2 to predict genes from Eglobulus genome, the command he used was ./braker --core=15 --genome=xxx.fa --prot_seq=xxx.fa --epmode --prg=ph, the alignment tool he used was spaln, the command I used on the same genome was ./braker --core=15 --genome=xxx.fa --prot_seq=xxx.fa, alignment tool I used was also spaln, our input files (both genome and protein files) are the same, but he got three more times of predicted gene models than me. I was wondering whether this could be caused by version problem or, I should add --prg=spaln option?

Cheers,
Zhenyan

**Comment by tomasbruna** [comment]
Hi Zhenyan,

> the command he used was ./braker --core=15 --genome=xxx.fa --prot_seq=xxx.fa --epmode --prg=ph

> the command I used on the same genome was ./braker --core=15 --genome=xxx.fa --prot_seq=xxx.fa

These two commands are equivalent, the first command was needed for BRAKER v2.1.5, the command you used works with current BRAKER v.2.1.6. Inside, they run almost the same code.

> the alignment tool he used was spaln
> alignment tool I used was also spaln...

Do you mean that you both used [ProtHint](https://github.com/gatech-genemark/ProtHint), which is [indeed using Spaln as one of the components](https://academic.oup.com/view-large/figure/222619687/lqaa108fig1.jpg)?

> he got three more times of predicted gene models than me.

This is really strange, there should only be small differences between the two runs. Can you share `braker.log` and other log files (such as stderr and stdout outputs) from both runs? I'd like to take a look.

Best,
Tomas

**Comment by ZhenyanLuo** [comment]
Hi Tomas,

Thanks for replying. Yes we both used ProtHint, and use Spaln as one of the components. I have attached braker.log and stderr output from both run here, even the name of input genome is different, their contents are the same:
[braker_2.1.6.zip](https://github.com/Gaius-Augustus/BRAKER/files/6430876/braker_2.1.6.zip)
[braker_2.1.5.zip](https://github.com/Gaius-Augustus/BRAKER/files/6430877/braker_2.1.5.zip)

Thanks,
Zhenyan

**Comment by tomasbruna** [comment]
Hello Zhenyan,

from the logs, it looks like the difference already occurs with GeneMark.

Can you count the number of genes in `GeneMark-ES/genemark.gtf ` and `GeneMark-EP/genemark.gtf` in both `braker_2.1.5` and `braker_2.1.5`? This will help me to determine at which stage exactly the predictions start to differ. Thanks!

> The genome file only contains uppercase letters.

Since your genome is pretty large, you might need to repeat-mask the genome to get a good prediction. But let's first figure out why the predictions differ between versions :)

Tomas

**Comment by ZhenyanLuo** [comment]
Hi Tomas,

Thank you so much for the quick reply. I got 33609 genes in GeneMark-EP/genemark.gtf and 34027 genes in GeneMark-EP/genemark.gtf. He got 46403 genes in GeneMark-EP/genemark.gtf and 45859 genes in GeneMark-ES/genemark.gtf. 

Cheers,
Zhenyan

**Comment by tomasbruna** [comment]
Are you both using the latest GeneMark version from http://exon.gatech.edu/GeneMark/license_download.cgi ?

**Comment by ZhenyanLuo** [comment]
Hi Tomas,

Mine is version 4.63_lic, I am not sure which version he used, still waiting for his reply. I will update to 4.65_lic (the latest one) and run again to see whether this is the reason. 
Thanks.

Cheers,
Zhenyan

**Comment by tomasbruna** [comment]
There should not really be a difference between `4.63` and `4.65`, these are both recent. My best theory now is that your friend is using some very old version, otherwise, I cannot explain this difference with identical inputs.

**Comment by ZhenyanLuo** [comment]
Hi Tomas,

I requested the other student to run braker again with 4.65, he got 42655 predicted gene models this time, and his GeneMark output was same as the previous version he used. Do you have any idea what cause this difference?
Thanks.

Cheers,
Zhenyan

**Comment by tomasbruna** [comment]
Hello Zhenyan,

there can be changes in the number of genes predicted by BRAKER overall (these should be relatively small), but I cannot explain the different number of genes predicted by GeneMark.

Can you double-check that you are both treating the repeat-masking in the same way? Such a big difference could definitely be caused by that.

Tomas
