### ISSUE TITLE
test1 Error

### ISSUE THREAD

**Issue by inspirewind** [Gaius-Augustus/BRAKER#367]
Hi I have set up all the dependencies, and encountered the following error when running test1.
The command is
`braker.pl --genome genome.fa --hints RNAseq.hints --softmasking`

The Error message is

> Wed May  5 00:22:14 2021: Log information is stored in file /mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/example/braker/braker.log
ERROR in file /mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/scripts//braker.pl at line 6666
Failed to execute: perl /mnt/d/__wsl/full_pipeline/gmes_linux_64/gmes_petap.pl --verbose --sequence=/mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/example/braker/genome.fa --min_contig=1000 --ET=/mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/example/braker/genemark_hintsfile.gff --cores=1 --gc_donor 0.001 --soft_mask auto 1>/mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/example/braker/GeneMark-ET.stdout 2>/mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/example/braker/errors/GeneMark-ET.stderr
Failed to execute: perl /mnt/d/__wsl/full_pipeline/gmes_linux_64/gmes_petap.pl --verbose --sequence=/mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/example/braker/genome.fa --min_contig=1000 --ET=/mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/example/braker/genemark_hintsfile.gff --cores=1 --gc_donor 0.001 --soft_mask auto 1>/mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/example/braker/GeneMark-ET.stdout 2>/mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/example/braker/errors/GeneMark-ET.stderr
The most common problem is an expired or not present file ~/.gm_key!

I think I have set up the key file.
Then I Checked the documentation on the homepage of BARKER2，it says

> When providing paths to software to BRAKER, please use absolute, non-abbreviated paths. For example, BRAKER might have problems with --SAMTOOLS_PATH=./samtools/ or --SAMTOOLS_PATH=~/samtools/. Please use SAMTOOLS_PATH=/full/absolute/path/to/samtools/, instead. This applies to all path specifications as command line options to braker.pl. Relative paths and absolute paths will not pose problems if you export a bash variable, instead, or if you append the location of tools to your $PATH variable.

This is my path setting
`export PATH=/mnt/d/__wsl/full_pipeline/RepeatMasker:$PATH
export PATH=/mnt/d/__wsl/full_pipeline/samtools/bin:$PATH
export PATH=/mnt/d/__wsl/full_pipeline/augustus-3.4.0/bin:/mnt/d/__wsl/full_pipiline/augustus-3.4.0/scripts:$PATH
export GENEMARK_PATH=/mnt/d/__wsl/full_pipeline/gmes_linux_64
export BAMTOOLS_PATH=/mnt/d/__wsl/full_pipeline/bamtools_for_augustus/bin
export DIAMOND_PATH=/mnt/d/__wsl/full_pipiline/
export PROTHINT_PATH=/mnt/d/__wsl/full_pipeline/ProtHint/bin
export PATH=/mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/scripts/:$PATH
export SAMTOOLS_PATH=/mnt/d/__wsl/full_pipeline/samtools
export PATH=/mnt/d/__wsl/full_pipeline/diamond/:$PATH`
I am confused about GENEMARK version because the dir name is a little different from the demonstration on the document, did I download the wrong version? I sincerely need your help.
Best Wishes,
Rui Li

**Comment by tomasbruna** [comment]
Hello Rui Li,

what do the GeneMark output files (`/mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/example/braker/errors/GeneMark-ET.stderr` and `/mnt/d/__wsl/full_pipeline/BRAKER-2.1.6/example/braker/GeneMark-ET.stdout`) say?

You can test GeneMark separately, by running `check_install.bash` which is available in the GeneMark folder.

> the dir name is a little different from the demonstration on the document

This is a good point. I will fix the documentation.

Best,
Tomas

**Comment by inspirewind** [comment]
Hi Tomas,
Thanks for you help!

These are errors files
[GeneMark-ET.stderr.zip](https://github.com/Gaius-Augustus/BRAKER/files/6431365/GeneMark-ET.stderr.zip)
[GeneMark-ET.stdout.zip](https://github.com/Gaius-Augustus/BRAKER/files/6431364/GeneMark-ET.stdout.zip)
It is a little strange that GeneMark-ET.stderr does not have any output.

I ran the test of `check_install.bash`, and it says
![image](https://user-images.githubusercontent.com/37958868/117233652-22406c80-ae56-11eb-86c1-f8a036b40ca6.png)
The code that caused the error in the bash shellscript is
`message=$($dir/gmhmme3 -v 2>&1 >/dev/null)
if [[ $message == *"License key"* ]] ;
then
  echo "Error, installation key is missing or expired"
  exit 1
fi`
Then I ran the command of `gmhmme3 -v` in the terminal, and it says
![image](https://user-images.githubusercontent.com/37958868/117233871-85320380-ae56-11eb-9b8b-cb291fd08377.png)
It looks like the error is here.

What should I do next? My device information is
![image](https://user-images.githubusercontent.com/37958868/117234136-fc679780-ae56-11eb-9c12-6e45baa3008b.png)

Best,
Rui Li

**Comment by tomasbruna** [comment]
Hello Rui Li,

thanks for the logs, it is now clear what's causing the problem.

Please contact Alex Lomsadze (his email is here http://exon.gatech.edu/GeneMark/contact.html), he should be able to prepare a binary that is compatible with your system. I will let Alex know that you are about to contact him.

Best,
Tomas

**Comment by inspirewind** [comment]
Hi @tomasbruna,
Sorry to bother you again.
I have contacted Alex Lomsadze but there is no response. Maybe this problem is caused by wsl, do I need to change the system environment first? Can you tell me the development system environment you use？

Some information that might be useful

> $ strace -i ./gmhmme3 -v
[00007fde7d9162fb] execve("./gmhmme3", ["./gmhmme3", "-v"], 0x7fffc10bf350 /* 29 vars */) = 0
[00000000004eac27] uname({sysname="Linux", nodename="inspirewind-3500U", ...}) = 0
[00000000004eb04a] brk(NULL)            = 0x820000
[00000000004eb04a] brk(0x821180)        = 0x821180
[000000000047efc0] arch_prctl(ARCH_SET_FS, 0x820860) = 0
[00000000004eb04a] brk(0x842180)        = 0x842180
[00000000004eb04a] brk(0x843000)        = 0x843000
[00000000004cbd60] open(".gm_key", O_RDONLY) = -1 ENOENT (No such file or directory)
[00000000004eb04a] brk(0x842000)        = 0x842000
[00000000004cbd60] open("/home/inspirewind/.gm_key", O_RDONLY) = 3
[00000000004cbdc0] close(3)             = 0
[00000000004cbd60] open("/home/inspirewind/.gm_key", O_RDONLY) = 3
[00000000004cbd14] fstat(3, {st_mode=S_IFREG|0777, st_size=91, ...}) = 0
[00000000004cd20a] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6994380000
[00000000004cbe20] read(3, "ACAAATCCTCACGGCGTATATATTCTTGAAAT"..., 4096) = 91
[00000000004cbdc0] close(3)             = 0
[00000000004cd227] munmap(0x7f6994380000, 4096) = 0
[ffffffffff600400] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffffffff600400} ---
[????????????????] +++ killed by SIGSEGV (core dumped) +++
[1]    59 segmentation fault (core dumped)  strace -i ./gmhmme3 -v

> $ cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 24
model name      : AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
stepping        : 1
microcode       : 0xffffffff
cpu MHz         : 2100.000
cache size      : 512 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 23
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave osxsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw wdt topoext fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni
bogomips        : 4200.00
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

> $ cat /proc/version
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020
> $ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l

Best,
Rui Li

**Comment by tomasbruna** [comment]
Hello Rui Li,

we only use Red Hat 6.10 for development, but I've successfully tested BRAKER on Ubuntu 20.4 or Linux Mint 19 before.

I am not sure whether the binary was ever successfully used in wsl, please try asking Alex again. Alternatively, you can try using Linux in a VirtualBox to make things work, I've successfully tested that before.

Tomas

**Comment by inspirewind** [comment]
Hi Tomas,
I have passed tests in cloud server, HPC and virtual machine , and it seems that the error is caused by wsl. Thank you!
