### ISSUE TITLE
Can't locate Hash/Merge.pm

### ISSUE THREAD

**Issue by Arkadiy-Garber** [Gaius-Augustus/BRAKER#37]
Getting this error during the GeneMark-ET part of the pipeline:

```
Can't locate Hash/Merge.pm in @INC (you may need to install the Hash::Merge module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/arkadiy_garber/bin/gm_et_linux_64/gmes_petap/parse_by_introns.pl line 22.
BEGIN failed--compilation aborted at /home/arkadiy_garber/bin/gm_et_linux_64/gmes_petap/parse_by_introns.pl line 22.
        (in cleanup)    (in cleanup)  at /home/arkadiy_garber/anaconda3/lib/site_perl/5.26.2/Object/InsideOut.pm line 1953 during global destruction.
```

The Hash::Merge module is, indeed, installed. And the gmes_petap.pl script is executable otherwise:

```
arkadiy_garber@server:/scratch/1/arkadiy/PacBIO_data/assembly_and_trimmed_reads$ perl /home/arkadiy_garber/bin/gm_et_linux_64/gmes_petap/gmes_petap.pl
# -------------------
Usage:  /home/arkadiy_garber/bin/gm_et_linux_64/gmes_petap/gmes_petap.pl  [options]  --sequence [filename]

GeneMark-ES Suite version 4.38
   includes transcript (GeneMark-ET) and protein (GeneMark-EP) based training and prediction

Input sequence/s should be in FASTA format

Algorithm options
  --ES           to run self-training
  --fungus       to run algorithm with branch point model (most useful for fungal genomes)
  --ET           [filename]; to run training with introns coordinates from RNA-Seq read alignments (GFF format)
  --EP           [filename]; to run training with introns coordinates from protein splice alighnmnet (GFF format)
  --et_score     [number]; 10 (default) minimum score of intron in initiation of the ET algorithm
  --ep_score     [number]; 4 (default) minimum score of intron in initiation of the EP algorithm
  --evidence     [filename]; to use in prediction external evidence (RNA or protein) mapped to genome
  --training     to run only training step
  --prediction   to run only prediction step
  --predict_with [filename]; predict genes using this file species specific parameters (bypass regular training and prediction steps)

Sequence pre-processing options
  --max_contig   [number]; 5000000 (default) will split input genomic sequence into contigs shorter then max_contig
  --min_contig   [number]; 50000 (default); will ignore contigs shorter then min_contig in training 
  --max_gap      [number]; 5000 (default); will split sequence at gaps longer than max_gap
                 Letters 'n' and 'N' are interpreted as standing within gaps 
  --max_mask     [number]; 5000 (default); will split sequence at repeats longer then max_mask
                 Letters 'x' and 'X' are interpreted as results of hard masking of repeats
  --soft_mask    [number] to indicate that lowercase letters stand for repeats; utilize only lowercase repeats longer than specified length

Run options
  --cores        [number]; 1 (default) to run program with multiple threads 
  --pbs          to run on cluster with PBS support
  --v            verbose

Customizing parameters:
  --max_intron          [number]; default 10000 (3000 fungi), maximum length of intron
  --max_intergenic      [number]; default 10000, maximum length of intergenic regions
  --min_gene_prediction [number]; default 300 (120 fungi) minimum allowed gene length in prediction step

Developer options:
  --usr_cfg      [filename]; to customize configuration file
  --ini_mod      [filename]; use this file with parameters for algorithm initiation
  --test_set     [filename]; to evaluate prediction accuracy on the given test set
  --key_bin
  --debug
# -------------------
```

thanks,
Arkadiy

**Comment by Arkadiy-Garber** [comment]
Full command:

`perl /home/arkadiy_garber/bin/gm_et_linux_64/gmes_petap/gmes_petap.pl --sequence=/scratch/1/arkadiy/Mealybug_PacBIO_data/assembly_and_trimmed_reads/braker/braker/mealybug/genome.fa --ET=/scratch/1/arkadiy/Mealybug_PacBIO_data/assembly_and_trimmed_reads/braker/braker/mealybug/hintsfile.gff --cores=1 1>/scratch/1/arkadiy/Mealybug_PacBIO_data/assembly_and_trimmed_reads/braker/braker/mealybug/GeneMark-ET.stdout 2>/scratch/1/arkadiy/Mealybug_PacBIO_data/assembly_and_trimmed_reads/braker/braker/mealybug/errors/GeneMark-ET.stderr
`

**Comment by Arkadiy-Garber** [comment]
Update: For thoroughness, I installed all perl modules using conda as instructed on the instructions page:

`conda install -c anaconda perl
conda install -c bioconda perl-app-cpanminus
conda install -c bioconda perl-hash-merge
conda install -c bioconda perl-parallel-forkmanager
conda install -c bioconda perl-scalar-util-numeric
conda install -c bioconda perl-yaml
conda install -c bioconda perl-class-data-inheritable
conda install -c bioconda perl-exception-class
conda install -c bioconda perl-test-pod
conda install -c anaconda biopython
conda install -c bioconda perl-file-homedir
conda install -c bioconda perl-file-which # skip if you are not comparing to reference annotation
cpanm Logger::Simple`

Still getting same error:

`Can't locate Hash/Merge.pm in @INC (you may need to install the Hash::Merge module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/arkadiy_garber/bin/gm_et_linux_64/gmes_petap/parse_by_introns.pl line 22.
BEGIN failed--compilation aborted at /home/arkadiy_garber/bin/gm_et_linux_64/gmes_petap/parse_by_introns.pl line 22.
        (in cleanup)    (in cleanup)  at /home/arkadiy_garber/anaconda3/lib/site_perl/5.26.2/Object/InsideOut.pm line 1953 during global destruction.`

**Comment by OnlineArts** [comment]
$ cpan
$ > install Hash::Merge

Generally, you need all these Perl modules:
-    YAML
-    Hash::Merge
-    Logger::Simple
-    Parallel::ForkManager

for GeneMark-ES

**Comment by Arkadiy-Garber** [comment]
This has been tried already. As I mentioned previously, all relevant Perl modules have been installed.

The error was fixed by updating the @INC path (where all the modules are stored). Once the perl install is carried out with anaconda, the path to the perl executable needs to be retrieved using:

`which perl`

I needed to then go into each individual '.pl' script in the 'gmes_petap' directory and replace the shebang (line that starts with '#!') with the location of the anaconda-installed executable.

**Comment by SvitlanaLukicheva** [comment]
Hello,

I also had this issue and found the same solution. I just wanted to add that there is a script in gmes_petap allowing to change the path to the Perl executable in all the files at once, it is called `change_path_in_perl_scripts.pl` and it can save time. :)

The command is:
`perl ./change_path_in_perl_scripts.pl full_path_to_perl_executable`

**Comment by parima678** [comment]
Thanks very much @SvitlanaLukicheva, your comment helped resolve the issue.
