### ISSUE TITLE
do duplicate AA sequences in protein evidence matter?

### ISSUE THREAD

**Issue by krabapple** [Gaius-Augustus/BRAKER#371]
Subject says it all.  I notice that there are exact duplicate amino acid sequences in OrthoDB download .fasta files, and wondered if it's better to make the sequences nonredundant before use in e.g., pipeline D, or not.

**Comment by tomasbruna** [comment]
If these duplicates are from different species, it might be best to keep the redundancy. This will increase the confidence in hints mapped from these proteins since they are conserved across different species.

**Comment by krabapple** [comment]
Thanks.
