### ISSUE TITLE
Online documentation differs from current BRAKER-master/docs/userguide.pdf

### ISSUE THREAD

**Issue by krabapple** [Gaius-Augustus/BRAKER#372]
for example, the 'Data description' section is quite different between the two.

online (https://github.com/Gaius-Augustus/BRAKER#data-description)
```
genome.fa - genome file in fasta format
RNAseq.bam - RNA-Seq alignment file in bam format (this file is not a part of this repository, it must be downloaded separately from http://topaz.gatech.edu/GeneMark/Braker/RNAseq.bam)
RNAseq.hints - RNA-Seq hints (can be used instead of RNAseq.bam as RNA-Seq input to BRAKER)
proteins.fa - protein sequences in fasta format
```

in BRAKER-master/docs/userguide.pdf (downloaded today):
```
genome.fa - genome file in fasta format
RNAseq.bam - RNA-Seq alignment file in bam format (this file is not in github, it must be downloaded separately from
http://bioinf.uni-greifswald.de/bioinf/braker/RNAseq.bam)
RNAseq.hints - RNA-Seq hints (can be used instead of RNAseq.bam as RNA-Seq input to BRAKER)
prot.fa - protein sequences of close homology in fasta format
orthodb_small.fa - small proportion of OrthoDB in fasta format
```

The actual data files supplied currently in BRAKER-master/examples are:
genome.fa
proteins.fa
RNA.hints

along with a recommendation in README.TXT to download an RNAseq.bam file from
 http://bioinf.uni-greifswald.de/bioinf/braker/RNAseq.bam

//
The testing commands also differ:

online:  (https://github.com/Gaius-Augustus/BRAKER#testing-braker-with-proteins-of-any-evolutionary-distance)
> ### Testing BRAKER with proteins of any evolutionary distance
> The following command will run the pipeline according to Figure 4:
> 
> braker.pl --genome genome.fa --prot_seq proteins.fa --softmasking --cores N
> This test is implemented in test2.sh, expected runtime is ~20 minutes.
> 

BRAKER-master/docs/userguide.pdf:
> ### Testing BRAKER with hints from proteins of unknown evolutionary
> distance
> The following command will test the pipeline according to Figure 4 (implemented in test2.sh ):
> braker.pl --genome=../genome.fa --prot_seq=../orthodb_small.fa \
> --epmode --softmasking
> Runtime of this command is ~24 minutes (including the runtime of ProtHint).
> 

//

I suspect the online user guide is more up to date of the two, can you confirm?

**Comment by tomasbruna** [comment]
Hello @krabapple,

yes, I confirm, the pdf is outdated, please refer to the main `README.md` file. I apologize for the confusion caused by this.

@KatharinaHoff, should we completely remove the pdf user guide? It is hard to keep up-to-date with constant improvements to the main README file.

Best,
Tomas

**Comment by KatharinaHoff** [comment]
I will remove the userguide pdf. https://github.com/Gaius-Augustus/BRAKER/commit/ce4477c2ec084bc055b43fe987b1266721e0ef4b
