### ISSUE TITLE
error startAlign.pl at line 629  - BRAKER2 v 2.1.5

### ISSUE THREAD

**Issue by grendon** [Gaius-Augustus/BRAKER#374]
The command I ran and its progress are included in this log

[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/6437309/braker.log)

The startAlign.pl program produced exonerate alignment files for all scaffolds. 
Then startAlign.pl was repeating the same cmds and it aborted.

This is the contents of the startAlign.stderr file:

`sh: line 1: 788083 Killed                  /home/apps/software/exonerate/2.2.0-IGB-gcc-8.2.0/bin/exonerate --model protein2genome --maxintron 30000 --showtargetgff --showalignment no --query clean_proteins_addstop.fasta -t /home/groups/earthbiogenome/results/20210430_EB29_GeneMark/braker_w_fly/tmp_exonerate/genomescaffold1_21674113_scaffold1,21674113,f3Z21674113.fa > /home/groups/earthbiogenome/results/20210430_EB29_GeneMark/braker_w_fly/align_exonerate/scaffold1_21674113_scaffold1,21674113,f3Z21674113.exonerate.aln 2> /home/groups/earthbiogenome/results/20210430_EB29_GeneMark/braker_w_fly/align_exonerate/scaffold1_21674113_scaffold1,21674113,f3Z21674113.exonerate.stderr
ERROR in file /home/apps/software/BRAKER/2.1.5-IGB-gcc-8.2.0/scripts/startAlign.pl at line 629
failed to execute: /home/apps/software/exonerate/2.2.0-IGB-gcc-8.2.0/bin/exonerate --model protein2genome --maxintron 30000 --showtargetgff --showalignment no --query clean_proteins_addstop.fasta -t   /home/groups/earthbiogenome/results/20210430_EB29_GeneMark/braker_w_fly/tmp_exonerate/genomescaffold1_21674113_scaffold1,21674113,f3Z21674113.fa > /home/groups/earthbiogenome/results/20210430_EB29_GeneMark/braker_w_fly/align_exonerate/scaffold1_21674113_scaffold1,21674113,f3Z21674113.exonerate.aln 2> /home/groups/earthbiogenome/results/20210430_EB29_GeneMark/braker_w_fly/align_exonerate/scaffold1_21674113_scaffold1,21674113,f3Z21674113.exonerate.stderr!
`

I ran the above command.  It did not produce output and the error file has this message:

`** FATAL ERROR **: Cannot read file [clean_proteins_addstop.fasta]
exiting ...`

That is very odd because that missing file was produced by the program itself; I mean, it was not a parameter I provided.

Is there a way to correct this problem?  Thanks

**Comment by tomasbruna** [comment]
Hello,

the exonerate support is in BRAKER only for historical reasons, it has not been maintained for a while. Even if we managed to fix this issue, more problems would likely occur.

Do you need to use exonerate specifically? Using the protein hints from ProtHint with `--hints=/home/groups/earthbiogenome/results/20210430_EB29_GeneMark/prothint_masked/prothint_augustus.gff` should be good enough.

It might help to get the latest[ BRAKER release](https://github.com/Gaius-Augustus/BRAKER/releases/tag/v2.1.6) if you are running into other issues in the execution mode with protein hints.

Tomas

**Comment by grendon** [comment]
Hi Tomas,
bypassing exonerate and using instead the hits parameter with prohints_augustus.gff is what I did and it worked. Thanks.
