### ISSUE TITLE
Error at Augustus training step

### ISSUE THREAD

**Issue by siva5** [Gaius-Augustus/BRAKER#384]
I was trying to run the BRAKER pipeline for a plant genome (~ 4GB size) with the --etpmode. I am facing an issue during the augustus step - "Running etraining to catch gene structure inconsistencies". There is no error displayed in the braker.log file but in the /errors folder, I find the following error in the traingenes.gtf_gff2gbSmallDNA.stderr file.

`substr outside of string at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 531, <FASTA> chunk 1.
Use of uninitialized value $join in numeric gt (>) at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 532, <FASTA> chunk 1.
Use of uninitialized value $join in numeric gt (>) at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 532, <FASTA> chunk 1.
substr outside of string at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 531, <FASTA> chunk 1.
Use of uninitialized value $join in numeric gt (>) at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 532, <FASTA> chunk 1.
Use of uninitialized value $join in numeric gt (>) at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 532, <FASTA> chunk 1.
Use of uninitialized value $length in subtraction (-) at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 573, <FASTA> chunk 1.
substr outside of string at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 591, <FASTA> chunk 1.
Use of uninitialized value $ten in numeric gt (>) at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 592, <FASTA> chunk 1.
substr outside of string at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 591, <FASTA> chunk 1.
Use of uninitialized value $ten in numeric gt (>) at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 592, <FASTA> chunk 1.
substr outside of string at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 591, <FASTA> chunk 1.
Use of uninitialized value $ten in numeric gt (>) at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 592, <FASTA> chunk 1.
substr outside of string at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 591, <FASTA> chunk 1.
Use of uninitialized value $ten in numeric gt (>) at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 592, <FASTA> chunk 1.
substr outside of string at /mstore/software/Augustus/scripts/gff2gbSmallDNA.pl line 531, <FASTA> chunk 1.`

I am attaching the braker.log afile. The error file is 1445425 lines long and ~170 MB in size, and contains the same lines as above redundantly. 

I would be happy if anyone can tell me how to troubleshoot this problem.

[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/6582012/braker.log)

Siva

**Comment by tomasbruna** [comment]
Hello Siva,

please try to re-run with the newest BRAKER (version 2.1.6) and use the `--softmasking` option in your BRAKER call.

It might not help, but it will be easier to debug when the run comes from the latest version.

Best,
Tomas

**Comment by siva5** [comment]
Hi Tomas,

I tried re-running with the newest version of BRAKER with the --softmasking option. However, I am still getting the same error in the traingenes.gtf_gff2gbSmallDNA.stderr file as above.
@tomasbruna  Any pointers on to how to solve this would be helpful.

I am attaching the braker.log file for reference.
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/6708597/braker.log)

Siva

**Comment by tomasbruna** [comment]
Hello Siva,

can you also share the following files?
* `/mstore/smp/user/siva/braker/errors/gbFilterEtraining.stderr` 
* `/mstore/smp/user/siva/braker/gbFilterEtraining.stdout`

It seems that BRAKER was able to successfully run `gff2gbSmallDNA.pl` (despite all the errors in the log) and it fails during `etraining`. I hope that these files will help us understand why.

Best,
Tomas

**Comment by siva5** [comment]
@tomasbruna Both the above files you asked for are empty. The only error file that has content is the traingenes.gtf_gff2gbSmallDNA.stderr as mentioned above. 

However, I just checked the log file of the script submitted, and there seems to be an error -

> sh: line 1: 95695 Segmentation fault      (core dumped) /mstore/software/Augustus/bin//etraining --species=Lsativus --AUGUSTUS_CONFIG_PATH=/mstore/software/Augustus/config/ /mstore/smp/user/siva/braker/train.f.gb > /mstore/smp/user/siva/braker/gbFilterEtraining.stdout 2> /mstore/smp/user/siva/braker/errors/gbFilterEtraining.stderr
ERROR in file /mstore/smp/user/siva/BRAKER-2.1.6/scripts/braker.pl at line 7468
Failed to execute: /mstore/software/Augustus/bin//etraining --species=Lsativus --AUGUSTUS_CONFIG_PATH=/mstore/software/Augustus/config/ /mstore/smp/user/siva/braker/train.f.gb 1> /mstore/smp/user/siva/braker/gbFilterEtraining.stdout 2>/mstore/smp/user/siva/braker/errors/gbFilterEtraining.stderr

I have attached the log file along with.

[lath_braker.sh.log](https://github.com/Gaius-Augustus/BRAKER/files/6713459/lath_braker.sh.log)

**Comment by KatharinaHoff** [comment]
Please make the file /mstore/software/Augustus/config/
/mstore/smp/user/siva/braker/train.f.gb available to us. @Mario this is an
etraining segmentation fault.

It might take a few weeks until Mario can look at it.

**Comment by siva5** [comment]
I am attaching the train.f.gb file as requested.

[train.f.gb.gz](https://github.com/Gaius-Augustus/BRAKER/files/6713713/train.f.gb.gz)

**Comment by ckeeling** [comment]
Hi @KatharinaHoff @tomasbruna

I am encountering a similar problem, except without seeing the segmentation fault, using the following command:
```bash
braker.pl --genome genome.fa --UTR=on --stranded=+,- --bam=merged_fwd.bam,merged_rev.bam --softmasking --cores 48
```

My braker/errors/gbFilterEtraining.stderr is empty, but braker/gbFilterEtraining.stdout reads:
```
# Read in 5562 genbank sequences.
Quantiles of the GC contents in the training set:
0%	0.287
5%	0.319	10%	0.328
15%	0.334	20%	0.339
25%	0.345	30%	0.351
35%	0.356	40%	0.361
45%	0.367	50%	0.372
55%	0.377	60%	0.383
65%	0.389	70%	0.396
75%	0.404	80%	0.412
85%	0.423	90%	0.438
95%	0.463	100%	0.65
HMM-training the parameters...
i= 0 bc= (0.237, 0.263, 0.263, 0.237)
 ** building model for exons *EXON*
start codon frequencies: ATG(5562)
# admissible start codons and their probabilities: ATG(1), CTG(0), TTG(0)
 number of bases in the reading frames: 2690607 2696028 2696037
--- frame = 0 ---    minPatSum = 233
--- frame = 1 ---    minPatSum = 233
--- frame = 2 ---    minPatSum = 233
--- initial frame = 0 ---    minPatSum = 233
--- initial frame = 1 ---    minPatSum = 233
--- initial frame = 2 ---    minPatSum = 233
--- internal exon terminal frame = 0 ---    minPatSum = 233
--- internal exon terminal frame = 1 ---    minPatSum = 233
--- internal exon terminal frame = 2 ---    minPatSum = 233
single, initial, internal, terminal mean exon lengths :
660	169	205	247
single exon : 149
initial exon 0 : 2140
initial exon 1 : 1999
initial exon 2 : 1274
internal exon 0 : 11373
internal exon 1 : 9882
internal exon 2 : 7134
terminal exon : 5413
Frequency of stop codons:
tag: 1544 (0.278)
taa: 2650 (0.476)
tga: 1368 (0.246)
end *EXON*
Storing parameters to file...
Writing exon model parameters [1] to file /home/ckeeling/.../config/species/Sp_4/Sp_4_exon_probs.pbl.
```

I get similar errors when the stranded parameters are not included:
```bash
braker.pl --genome genome.fa --bam=merged.bam --UTR=on --softmasking --cores 48
```

**Comment by siva5** [comment]
@KatharinaHoff @MarioStanke 

I would like to know if there is any updates on how to fix this error. I ran the BRAKER pipeline with another plant genome ( ~ 1 GB) and still face the same error. So at least the problem is not specific to one genome.

**Comment by inspirewind** [comment]
Hi, @tomasbruna @KatharinaHoff,
I am encountering a similar problem. The `gbFilterEtraining.stdout` file outputs the error of the sequence length, and it seems that the difference of each item is very similar.
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/7374374/braker.log)
[gbFilterEtraining.stderr.gz](https://github.com/Gaius-Augustus/BRAKER/files/7374415/gbFilterEtraining.stderr.gz)

**Comment by zmz1988** [comment]
Hi, I got the same error message 
```
sh: line 1: 224093 Segmentation fault     /miniconda3/envs/BRAKER/bin/etraining --species=Arabidopsis --AUGUSTUS_CONFIG_PATH=/Augustus/config /annotation/braker1_etp/train.f.gb > /annotation/braker1_etp/gbFilterEtraining.stdout 2> /annotation/braker1_etp/errors/gbFilterEtraining.stderr
ERROR in file /BRAKER/scripts/braker.pl at line 7493
Failed to execute: /miniconda3/envs/BRAKER/bin/etraining --species=Arabidopsis --AUGUSTUS_CONFIG_PATH=/Augustus/config /annotation/braker1_etp/train.f.gb 1> /annotation/braker1_etp/gbFilterEtraining.stdout 2>/annotation/braker1_etp/errors/gbFilterEtraining.stderr
```
and the gbFilterEtraining.stderr is empty. I read somewhere in the issue that this is caused by the version of brake and prohibit. But my braker version and prothint version are the newest, though Augustus is a bit behind, which is version 3.2.2. I would like to update the Augustus version, but it was a pain and conda environment doesn't allow. 

If this error is caused by the version of softwares, could you please provide a singularity image for us to use? Thanks!!

**Comment by KatharinaHoff** [comment]
You need to update your AUGUSTUS. etraining is part of AUGUSTUS.

**Comment by mhsdwei078** [comment]
Hi, I got the same error message.
In ET EP mode ,the Augustus training step can run. In the ETP mode, the error happened
# Sat Feb 24 13:05:01 2024: Running etraining to catch gene structure inconsistencies:
Segmentation fault (core dumped)
When changing the number of train genes (<8000),  I am still getting the same error.
