### ISSUE TITLE
Problem reading ep_utr.cfg

### ISSUE THREAD

**Issue by kmkocot** [Gaius-Augustus/BRAKER#388]
Hello,

I"m running BRAKER-2.1.6 on a chromosome-level mollusc genome assembly and running into an error. 

Command used: braker.pl --etpmode --useexisting --cores 1 --alternatives-from-evidence=false --crf --filterOutShort --UTR=on --makehub --email kmkocot@ua.edu --softmasking 1 --gff3 --species Dreissena_rostriformis_2021-05-17 --genome PGA_assembly_shortened_headers.fasta.masked --bam RNAseq.bam --hints prothint_augustus.gff 

Printed to the screen:
`# Tue Jun  1 15:21:54 2021: Log information is stored in file /home/wirenia/Desktop/2021-06-01_BRAKER2_Dreissena/braker/braker.log
ERROR in file /home/wirenia/bin/BRAKER-2.1.6/scripts/braker.pl at line 9324
Failed to execute: /home/wirenia/bin/augustus.3.3.3/bin/augustus --species=Dreissena_rostriformis_2021-05-17 --AUGUSTUS_CONFIG_PATH=/home/wirenia/bin/augustus.3.3.3/config --extrinsicCfgFile=/home/wirenia/bin/BRAKER-2.1.6/scripts/cfg/ep_utr.cfg --alternatives-from-evidence=false --hintsfile=/home/wirenia/Desktop/2021-06-01_BRAKER2_Dreissena/braker/hintsfile.gff.Ppri5 --UTR=on --exonnames=on --codingseq=on --allow_hinted_splicesites=gcag,atac --softmasking=1 /home/wirenia/Desktop/2021-06-01_BRAKER2_Dreissena/braker/genome.fa 1>/home/wirenia/Desktop/2021-06-01_BRAKER2_Dreissena/braker/augustus.Ppri5_utr.gff 2>/home/wirenia/Desktop/2021-06-01_BRAKER2_Dreissena/braker/errors/augustus.Ppri5_utr.stderr!`

Braker.log file:
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/6651133/braker.log)

When I try to run the command that failed, here's what I get:
`/home/wirenia/bin/augustus.3.3.3/bin/augustus --species=Dreissena_rostriformis_2021-05-17 --AUGUSTUS_CONFIG_PATH=/home/wirenia/bin/augustus.3.3.3/config --extrinsicCfgFile=/home/wirenia/bin/BRAKER-2.1.6/scripts/cfg/ep_utr.cfg --alternatives-from-evidence=false --hintsfile=/home/wirenia/Desktop/2021-06-01_BRAKER2_Dreissena/braker/hintsfile.gff.Ppri5 --UTR=on --exonnames=on --codingseq=on --allow_hinted_splicesites=gcag,atac --softmasking=1 /home/wirenia/Desktop/2021-06-01_BRAKER2_Dreissena/braker/genome.fa
# This output was generated with AUGUSTUS (version 3.3.3).
# AUGUSTUS is a gene prediction tool written by M. Stanke (mario.stanke@uni-greifswald.de),
# O. Keller, S. König, L. Gerischer, L. Romoth and Katharina Hoff.
# Please cite: Mario Stanke, Mark Diekhans, Robert Baertsch, David Haussler (2008),
# Using native and syntenically mapped cDNA alignments to improve de novo gene finding
# Bioinformatics 24: 637-644, doi 10.1093/bioinformatics/btn013
# Sources of extrinsic information: M RM E W P C 
# Setting exon local malus: 0.985
FeatureCollection::readExtrinsicCFGFile: FeatureCollection::esource: invalid source key: 1
Could not read in file with the configuration of hints: /home/wirenia/bin/BRAKER-2.1.6/scripts/cfg/ep_utr.cfg

/home/wirenia/bin/augustus.3.3.3/bin/augustus: ERROR
	FeatureCollection::readExtrinsicCFGFile: FeatureCollection::esource: invalid source key: 1`

This file does exist: /home/wirenia/bin/BRAKER-2.1.6/scripts/cfg/ep_utr.cfg. I don't understand why augustus is reading it at this point, though.
[contents_of_ep_utr.cfg.txt](https://github.com/Gaius-Augustus/BRAKER/files/6651154/contents_of_ep_utr.cfg.txt)

Any advice how to fix this error would be really helpful!

Thanks!
Kevin

**Comment by tomasbruna** [comment]
Hi Kevin,

the UTR training pipeline is still experimental. This means that the accuracy with UTR training tends to be unstable (in the log file, there is a warning suggesting this: `# WARNING: UTR training decreased AUGUSTUS ab initio accuracy!`) and that it contains some bugs, like the one you are encountering.

I cannot help you with this particular error but I have another suggestion:

Instead of UTR training, run training and prediction without UTRs (i.e., a regular BRAKER run) and add UTRs with GUSHR using the [--addUTR=on](https://github.com/Gaius-Augustus/BRAKER#--addutron) option. This is also illustrated in [test3_add_utrs.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3_add_utrs.sh)

Best,
Tomas

**Comment by kmkocot** [comment]
OK. Thanks for letting me know!
