### ISSUE TITLE
BRAKER give poor result on arabidopsis thaliana genome

### ISSUE THREAD

**Issue by HangweiXi** [Gaius-Augustus/BRAKER#389]
Hi team,

I'm testing braker2 pipeline on arabidopsis thaliana genome. The pipeline I'm choosing is test3, which is the Genemark etp pipeline. I've generated both softmask and hardmask genome, RNA-seq data were mapped to hardmask genome using STAR. Softmasked genome was used as input in the Braker pipeline. The whole orthodb database was downloaded from https://www.orthodb.org/ and used as protein evidence. 

The first try was filed but the Prothint process was finished and generated the "prothint_augustus.gff" file. Then I rerun the braker with the prothint file and bam file, here is the command: 
`braker.pl --cores 16 --species=arabidopsis_test6 \
--genome=Athaliana_TAIR10_masked.fna \
--bam=SRR14759194.bam,SRR14759195.bam,SRR14759196.bam,SRR14759197.bam \
--etpmode --softmasking \
--hints=prothint_augustus.gff --gff3`

The process finished successfully. I extract the cds with braker.gff and run BUSCO on it. It only give ~20% complete BUSCO. I have no idea which step is wrong. Any suggestion is helpful!

Here is the braker log
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/6654150/braker.log)

Cheers,
Hangwei

**Comment by tomasbruna** [comment]
Hello Hangwei,

can you please share the output file named `augustus.hints.gtf`? I want to take a look at the predictions first to rule out the possibility that something went wrong during BUSCO evaluation -- before we start looking into the BRAKER run itself.

Best,
Tomas

**Comment by HangweiXi** [comment]
Hi Tomas,

Thanks for your reply. Here is the gtf file:
[augustus.hints.gtf.zip](https://github.com/Gaius-Augustus/BRAKER/files/6683489/augustus.hints.gtf.zip)

I've tried the BUSCO evaluation approach with the arabidopsis thaliana reference annotation and seems worked well. 

Cheers,
Hangwei

**Comment by tomasbruna** [comment]
Hello Hangwei,

good news, your prediction seems to be in a good shape. I've run the BUSCO analysis (version v4.0.5) with `brassicales_odb10` set and it found **99.5%** of the complete genes:

```
        --------------------------------------------------
        |Results from dataset brassicales_odb10           |
        --------------------------------------------------
        |C:99.5%[S:92.0%,D:7.5%],F:0.2%,M:0.3%,n:4596     |
        |4573   Complete BUSCOs (C)                       |
        |4230   Complete and single-copy BUSCOs (S)       |
        |343    Complete and duplicated BUSCOs (D)        |
        |9      Fragmented BUSCOs (F)                     |
        |14     Missing BUSCOs (M)                        |
        |4596   Total BUSCO groups searched               |
        --------------------------------------------------

```

Here are the commands I used:

    getAnnoFastaFromJoingenes.py -g genome.fasta -o proteins -f augustus.hints.gtf
    python3 busco -m protein -i proteins.aa -o BRAKER -l brassicales_odb10

The `getAnnoFastaFromJoingenes.py` script [is here](https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/getAnnoFastaFromJoingenes.py).

I also compared your predictions against the [reference annotation](https://www.arabidopsis.org/download/index-auto.jsp?dir=%2Fdownload_files%2FGenes%2FAraport11_genome_release) and the exact matches are pretty good.

|   | |
|---------|:----:|
| CDS Sn  | 85.3 |
| CDS Sp  | 86.4 |
| Gene Sn | 82.7 |
| Gene Sp | 73.8 |

This further validates that the predictions are of high quality.

Best,
Tomas

**Comment by HangweiXi** [comment]
It seems the CDS tag in the gtf file is exons, so when I extract CDS I actually extract the exon so the BUSCO only recognized the gene with one exon. I changed the tag to genes and then BUSCO gives me a very good result. Thank you very much for your help.

**Comment by tomasbruna** [comment]
Hi @yulong1227,

I used the [compare_intervals_exact.pl](https://github.com/gatech-genemark/EukSpecies-BRAKER2/blob/master/bin/compare_intervals_exact.pl) script. However, for this kind of assessment, you need a high-quality reference annotation, like the one [I used](https://www.arabidopsis.org/download/index-auto.jsp?dir=%2Fdownload_files%2FGenes%2FAraport11_genome_release) for A. thaliana. Such an annotation won't be available for newly assembled species.

Tomas

**Comment by yulong1227** [comment]
> Hi @yulong1227,
> 
> I used the [compare_intervals_exact.pl](https://github.com/gatech-genemark/EukSpecies-BRAKER2/blob/master/bin/compare_intervals_exact.pl) script. However, for this kind of assessment, you need a high-quality reference annotation, [like the one I used](https://www.arabidopsis.org/download/index-auto.jsp?dir=%2Fdownload_files%2FGenes%2FAraport11_genome_release) for A. thaliana. Such an annotation won't be available for newly assembled species.
> 
> Tomas

Hi, @tomasbruna 

I'm so sorry to reply to you now! I ran `compare_intervals_exact.pl` as you said and used the annotation file `GCF_000003025.6_Sscrofa11.1_genomic.gtf ` for the reference genome.

`compare_intervals_exact.pl --f1 GCF_000003025.6_Sscrofa11.1_genomic.gtf --f2 tsebra2.gtf --gene -verbose`

But the result shows

`# Transcripts-CDS in file GCF_000003025.6_Sscrofa11.1_genomic.gtf: 63565
# After removal of duplications:
# Transcripts-CDS in file GCF_000003025.6_Sscrofa11.1_genomic.gtf: 46911
# Transcripts-CDS in file tsebra2.gtf: 28131
# After removal of duplications:
# Transcripts-CDS in file tsebra2.gtf: 28131
# transc-per-gene hist
# 1 12334
# 2 3624
# 3 1686
# 4 1014
# 5 531
# 6 378
# 7 230
# 8 201
# 9 140
# 10 65
# 11 81
# 12 64
# 13 57
# 14 30
# 15 33
# 16 26
# 17 18
# 18 14
# 19 10
# 20 18
# 21 13
# 22 3
# 23 10
# 24 7
# 25 8
# 26 4
# 27 5
# 28 5
# 29 5
# 30 3
# 31 3
# 32 4
# 33 7
# 34 2
# 35 4
# 37 1
# 38 1
# 39 2
# 40 1
# 41 5
# 42 1
# 43 1
# 44 2
# 46 1
# 48 1
# 49 2
# 50 6
# 51 1
# transc-per-gene hist
# 1 15515
# 2 4600
# 3 770
# 4 193
# 5 45
# 6 13
# 7 2
# 8 1
# 9 1

```
#in	match	unique	%	Gene-CDS

20662	0	20662	0.00	GCF_000003025.6_Sscrofa11.1_genomic.gtf
21140	0	21140	0.00	tsebra2.gtf
```

I don't quite understand why this is and any advice from you would be greatly appreciated!
Best 
Yulong

**Comment by tomasbruna** [comment]
What output do you get when you run the compare script like this, without the `--gene` option?

    compare_intervals_exact.pl --f1 GCF_000003025.6_Sscrofa11.1_genomic.gtf --f2 tsebra2.gtf

**Comment by yulong1227** [comment]
@tomasbruna  Hi,
when i run `compare_intervals_exact.pl --f1 GCF_000003025.6_Sscrofa11.1_genomic.gtf --f2 tsebra2.gtf `,the result is still
![image](https://user-images.githubusercontent.com/99491773/156946552-6902f210-c4c1-4e1b-b7af-b57410171ade.png)


The following are part of the content of my input file：
GCF_000003025.6_Sscrofa11.1_genomic.gtf
![image](https://user-images.githubusercontent.com/99491773/156946648-bfb14985-9923-471d-838d-c2a95885bf62.png)


tsebra2.gtf
![image](https://user-images.githubusercontent.com/99491773/156946664-438811cd-aedb-4321-bba8-f17717add721.png)

I'm guessing it might be a problem with the input file format, or an inappropriate input file was chosen.

I used this script to generate `tsebra2.gtf `
`tsebra.py -g $wdir/braker1/augustus.hints.gtf,$wdir/braker2/augustus.hints.gtf -e $wdir/braker1/hintsfile.gff,$wdir/braker2/hintsfile.gff -l $wdir/long_read_protocol/gmst.global.gtf -c /your/path/to/TSEBRA/config/long_reads.cfg -o tsebra2.gtf`


Thanks!

**Comment by tomasbruna** [comment]
Hi @yulong1227,

sorry for the late reply, I completely missed your comment.

The warning you are getting is a result of space in the "Curated genomics" field. You can remove that, e.g., with:

    sed -i "s/Curated Genomic/Curaged_Genomic/" file.gtf

This explains just the warning though. I think the main issue might be different chromosome names in your prediction and annotation files -- did you check that?

Tomas
