### ISSUE TITLE
YAML not install

### ISSUE THREAD

**Issue by naktang** [Gaius-Augustus/BRAKER#39]
I try to run braker but it shown the following error.

Perl module 'YAML' is required but not installed yet

I try to install YAML module by both conda and cpan.However, It's still produce this error. What should I do?

**Comment by KatharinaHoff** [comment]
This should probably be posted/noted as an Anaconda receipe issue at
https://github.com/bioconda/bioconda-recipes/tree/b8e30dd6e2fd9c8d44fb5f56e44cc528e5f46859/recipes/braker2

**Comment by KatharinaHoff** [comment]
If it is Debian/Ubuntu, install YAML from the package repository:

sudo apt-get update
sudo apt-get install libconfig-yaml-perl

**Comment by parima678** [comment]
Got a solution from the following link
https://github.com/Gaius-Augustus/BRAKER/issues/37
Please refer the comment of @SvitlanaLukicheva in the above link
