### ISSUE TITLE
the .gm_key problem

### ISSUE THREAD

**Issue by chichizhao** [Gaius-Augustus/BRAKER#393]
HI! GREAT AUTHORS!
When i first try to run, It says " The most common problem is an expired or not present file ~/.gm_key! " And I was confused with that the .gm_key has provided in my home dir and I just replace it with the new one, it still not work. I NEED YOU HELP !
# THE SHELL DISPLAY
braker.pl --species=Tang --genome=scaffolds.gapcloser.fasta.masked --prot_seq=proteins.fa --softmasking --gff3 --cores=1 --workingdir=ab_initio --min_contig=4000
Thu Jun 24 20:57:54 2021: Log information is stored in file /home/chichi/data/Typha_angustifolia/x1zc/braker2/ab_initio/braker.log
ERROR in file /home/chichi/anaconda3/envs/braker/bin/braker.pl at line 6576
Failed to execute: perl /home/chichi/softwares/gmes_linux_64/gmes_petap.pl --verbose --cores=1 --ES --gc_donor 0.001 --sequence=/home/chichi/data/Typha_angustifolia/x1zc/braker2/ab_initio/genome.fa  --soft_mask auto --min_contig=4000  1>/home/chichi/data/Typha_angustifolia/x1zc/braker2/ab_initio/GeneMark-ES.stdout 2>/home/chichi/data/Typha_angustifolia/x1zc/braker2/ab_initio/errors/GeneMark-ES.stderr
The most common problem is an expired or not present file ~/.gm_key!

# INSTALLED BRAKER WITH CONDA
# INSTALLED THE GeneMark-ES/ET/EP ver 4.65_lic AND ADD THE PATH TO .bashrc
# run the check_install.bash
check_install.bash
Checking GeneMark-ES installation
Checking Perl setup
All required Perl modules were found
Checking GeneMark.hmm setup
GeneMark.hmm was found
GeneMark.hmm is set
GeneMark.hmm is executable
Performing GeneMark.hmm test run
All required components for GeneMark-ES were found

**Comment by tomasbruna** [comment]
Hello @chichizhao,

did you try to change the shebang in GeneMark scripts with the following command?

    perl change_path_in_perl_scripts.pl "/usr/bin/env perl"

This can help when BRAKER is installed with Conda. More details about this [are here](https://github.com/Gaius-Augustus/BRAKER#genemark-ex).

If this does not help, please share the contents of the following log files:

* `/home/chichi/data/Typha_angustifolia/x1zc/braker2/ab_initio/GeneMark-ES.stdout`
* `/home/chichi/data/Typha_angustifolia/x1zc/braker2/ab_initio/errors/GeneMark-ES.stderr`
* `/home/chichi/data/Typha_angustifolia/x1zc/braker2/ab_initio/GeneMark-ES/gmes.log`

Best,
Tomas

**Comment by chichizhao** [comment]
YOU ARE SO GREAT ！ it works with that command and forgive me for my carelessness with that setting ,thank you a lot !
great job !
chichi

**Comment by zhouyangithub** [comment]
Thanks, the converstion of you two help me a lot. 
:joy:

**Comment by TaehyungKwon** [comment]
/usr/bin/time -v braker.pl \
		--cores=${thread} \
		--softmasking \
		--genome=${genome_masked} \
		--UTR=on \
		--species=${prefix} \
		--bam=${basedir}/2.alignment/${prefix}/${prefix}.sorted.bam

I had the same problem after trying (1) setting gm_key in the home folder, (2) change the perl path for GeneMark-ES. It seems like an issue of GUSHR when Braker trying to predict UTR. I checked GUSHR using "./gushr.py -t example/augustus.gtf -b example/RNAseq.bam -g example/genome.fa -o utrs", and obtained the following error:
_Error in file ./gushr.py at line 281: Return code of subprocess was 127['/home/tkwon/miniconda3/envs/structuralanno/bin/samtools', 'sort', '-@', '1', 'example/RNAseq.bam', '-o', './gushr-XRJECIEPENCO/rnaseq_0_s.bam']_

I suspected that this error comes from a wrong samtools version, or crashed samtools. However, reinstalling the whole conda environment with samtools=1.8 did not work. Could you please help me out?

**Comment by TaehyungKwon** [comment]
I understand. I will try some other things, but in the meantime, I will just skip it!
Thanks.

**Comment by ricardoi** [comment]
Hello, 
I have a problem similar to this! 
I have freshly downloaded and hidden `~/.gm_key`, and perls `PATHs` changed to where perl is. 

**Although, still I have the same error message:**
```
braker.pl --genome=Pillicis.contigs.fasta --species=Pillicis --hints=Phytophthora_ss/prothint_augustus.gff --softmasking --epmode --useexisting
# Wed Mar 30 13:52:12 2022: Log information is stored in file /home/microway/Documents/clade3P/03_annotation/braker/braker.log
ERROR in file /home/microway/git_local/BRAKER/scripts/braker.pl at line 6758
Failed to execute: perl /home/microway/gmes_linux_64/gmes_petap.pl --verbose --seq /home/microway/Documents/clade3P/03_annotation/braker/genome.fa --EP /home/microway/Documents/clade3P/03_annotation/braker/genemark_hintsfile.gff --cores=1  --gc_donor 0.001 --evidence /home/microway/Documents/clade3P/03_annotation/braker/genemark_evidence.gff  --soft_mask auto 1>/home/microway/Documents/clade3P/03_annotation/braker/GeneMark-EP.stdout 2>/home/microway/Documents/clade3P/03_annotation/braker/errors/GeneMark-EP.stderr
Failed to execute: perl /home/microway/gmes_linux_64/gmes_petap.pl --verbose --seq /home/microway/Documents/clade3P/03_annotation/braker/genome.fa --EP /home/microway/Documents/clade3P/03_annotation/braker/genemark_hintsfile.gff --cores=1  --gc_donor 0.001 --evidence /home/microway/Documents/clade3P/03_annotation/braker/genemark_evidence.gff  --soft_mask auto 1>/home/microway/Documents/clade3P/03_annotation/braker/GeneMark-EP.stdout 2>/home/microway/Documents/clade3P/03_annotation/braker/errors/GeneMark-EP.stderr
The most common problem is an expired or not present file ~/.gm_key!
```
------- 
**The genemark std err is _empty_ and err displays the following** 
```
# check before the run
# hard_mask is in the 'auto' mode. hard_mask was set to: 1000
# creat directories
# commit input data
error, output file is empty data/evidence.gff
error on call: /home/microway/gmes_linux_64/reformat_gff.pl --out data/evidence.gff  --trace info/dna.trace  --in /home/microway/Doc
uments/clade3P/03_annotation/braker/genemark_evidence.gff  --quiet
```
--------
**Also I checked genemark install**
```
check_install.bash 
Checking GeneMark-ES installation
Checking Perl setup
All required Perl modules were found
Checking GeneMark.hmm setup
GeneMark.hmm was found
GeneMark.hmm is set
GeneMark.hmm is executable
Performing GeneMark.hmm test run
All required components for GeneMark-ES were found
```
------
**Any suggestions?** 
Thank you

**Comment by sunnyEV** [comment]
Hi

I also, have a similar problem. First time I messed up with the key.

Second time- 
I placed the key in my home folder ~/.gm_key.

I tried more than 3 times, replacing the key with other. 

Showing the same error, suggestions please!


- ERROR in file /home/sun/data/softwares/BRAKER-2.1.6/scripts/braker.pl at line 6586
- Failed to execute: perl /home/sun/data/softwares/genemark/gmes_linux_64_4/gmes_petap.pl --verbose --cores=8 --ES --gc_donor 0.001 --sequence=/DATA/mat/sun/softwares/BRAKER-2.1.6/scripts/braker/genome.fa  1>/DATA/mat/sun/softwares/BRAKER-2.1.6/scripts/braker/GeneMark-ES.stdout 2>/DATA/mat/sun/softwares/BRAKER-2.1.6/scripts/braker/errors/GeneMark-ES.stderr
- **The most common problem is an expired or not present file ~/.gm_key!**
-

**Comment by Jiangjiangzhang6** [comment]
> 

i got the same error , how did you solve this error 
![image](https://user-images.githubusercontent.com/101324838/184527999-88f1f92a-e79d-4edd-b600-ed294489211d.png)

**Comment by sunnyEV** [comment]
Well, Try to download the GeneMark-ES once again and place the gm_key at the home folder.
Problem solved.

**Comment by Ludtson** [comment]
> Well, Try to download the GeneMark-ES once again and place the gm_key at the home folder. Problem solved.

Hi,
@tomasbruna @KatharinaHoff 

I have a similar missing .gm_key issue. I have tried downloading the gm_key many times, but the error persists. Please, what can I do? 
I am running BRAKER 3.03 on a cluster with GeneMark4.71 installed.

Below is the error message I get every time:

ERROR in file /sw/eb/sw/BRAKER/3.0.3-foss-2020a-Python-3.8.2/scripts/braker.pl at line 5310
Failed to execute: /sw/eb/sw/Perl/5.30.2-GCCcore-9.3.0/bin/perl /sw/eb/sw/BRAKER/3.0.3-foss-2020a-Python-3.8.2/GENEMARK/gmes_petap.pl --verbose --seq /scratch/user/ludtson/spb/test/braker/genome.fa --EP /scratch/user/ludtson/spb/test/braker/genemark_hintsfile.gff --cores=1  --gc_donor 0.001 --evidence /scratch/user/ludtson/spb/test/braker/genemark_evidence.gff  --soft_mask auto 1>/scratch/user/ludtson/spb/test/braker/GeneMark-EP.stdout 2>/scratch/user/ludtson/spb/test/braker/errors/GeneMark-EP.stderr
Failed to execute: /sw/eb/sw/Perl/5.30.2-GCCcore-9.3.0/bin/perl /sw/eb/sw/BRAKER/3.0.3-foss-2020a-Python-3.8.2/GENEMARK/gmes_petap.pl --verbose --seq /scratch/user/ludtson/spb/test/braker/genome.fa --EP /scratch/user/ludtson/spb/test/braker/genemark_hintsfile.gff --cores=1  --gc_donor 0.001 --evidence /scratch/user/ludtson/spb/test/braker/genemark_evidence.gff  --soft_mask auto 1>/scratch/user/ludtson/spb/test/braker/GeneMark-EP.stdout 2>/scratch/user/ludtson/spb/test/braker/errors/GeneMark-EP.stderr
The most common problem is an expired or not present file ~/.gm_key!

**Comment by BioHlT** [comment]
Hi @tomasbruna @KatharinaHoff

Was the comment posted above resolved? I ran into the same problem as @Ludtson where the braker.pl fails at line 5310.

ERROR in file /ocean/projects/tra180030p/ytekle/Software/BRAKER/scripts/braker.pl at line 5310
Failed to execute: /jet/home/ytekle/anaconda3/bin/perl /ocean/projects/tra180030p/ytekle/Software/gmes_linux_64/gmes_petap.pl -$
Failed to execute: /jet/home/ytekle/anaconda3/bin/perl /ocean/projects/tra180030p/ytekle/Software/gmes_linux_64/gmes_petap.pl -$
The most common problem is an expired or not present file ~/.gm_key!

I have attempted reinstalling Braker, GeneMark, and adding a new gm_key to the home directory. However, it keeps failing with the same error message. 

Can you please help to resolve this issue?
