### ISSUE TITLE
tsebra naming is incorrect

### ISSUE THREAD

**Issue by sarjopp** [Gaius-Augustus/BRAKER#394]
After running Braker1 and Braker2, then doing fix_gtf_ids.py on each braker.gtf, my output from tsebra.py has inconsistent names:
CSAcor1 AUGUSTUS transcript 1 495 . + . anno1.CSAcor1+_file_1_file_1_g22683.t1
CSAcor1 AUGUSTUS start_codon 2 4 . + . transcript_id "anno2.CSAcor1+_file_1_file_1_g3798.t1"; gene_id "g_31366";
CSAcor1 AUGUSTUS CDS 2 495 0.73 + 2 transcript_id "anno2.CSAcor1+_file_1_file_1_g3798.t1"; gene_id "g_31366";
CSAcor1 AUGUSTUS exon 2 495 . + . transcript_id "anno2.CSAcor1+_file_1_file_1_g3798.t1"; gene_id "g_31366";
CSAcor1 AUGUSTUS stop_codon 493 495 . + 0 transcript_id "anno2.CSAcor1+_file_1_file_1_g3798.t1"; gene_id "g_31366";

As you can see, the transcript ID is "g3798.t1" while the gene ID is "g_31366."

In the original braker.gtf files, and in the fixed_braker.gtf files, the transcript and gene IDs match. The fact that the IDs are messed up makes me scared to trust any of the tsebra output.

**Comment by sarjopp** [comment]
From the Braker docs, it sounds like running in etp mode is discouraged, but that mode is the only way I have gotten internally correct names for transcripts/genes.

**Comment by LarsGab** [comment]
Hi,
thank you for your feedback. Your output looks like a normal TSEBRA output. TSEBRA uses the transcript IDs from the original braker.gtf files, but creates new gene IDs. We implemented it this way because you can use the transcript IDs to trace the transcripts from the TSEBRA output back to the input gene sets. 
However, I see that consistency between transcript IDs and gene IDs might be desirable and we may change this in the next update.
Best,
Lars

**Comment by MarioStanke** [comment]
I think it is desirable that a combiner leaves transcript names as they were in the input. They may have biological names and in some applications one may want to recognize from what gene set it was from, e.g. "snap.g1t1", "genemark.g1.t1".
A separate renaming script may be useful (outputting an optional translation table). That is not TSEBRA specific and may possibly exist already somewhere.

**Comment by sarjopp** [comment]
Thank you both, I had not realized that the mismatch was "a feature, not a
bug." My concern was whether the mismatch would confuse visualization
programs like IGV, but I  also see your point re: keeping the info about
where in the annotation process the transcript originated.

Sara

**Comment by LarsGab** [comment]
Hi,
I added the script ```rename_gtf.py``` to the [TSBERA](https://github.com/Gaius-Augustus/TSEBRA) repository. It can rename a TSEBRA output such that the transcript and gene IDs match. Additionally, you can get a translation table for old to new transcript IDs, if you want to retrace the transcript back to the BRAKER gene sets. See the README.md for more information. 
Best, Lars

**Comment by sarjopp** [comment]
Thank you!
