### ISSUE TITLE
Java version 1.8 check at line 3170 of braker.pl (v2.1.6) can fail in some circumstances

### ISSUE THREAD

**Issue by ckeeling** [Gaius-Augustus/BRAKER#398]
Hello,

I am running BRAKER within a Singularity container. I was having errors with Braker saying that java wasn't version 1.8 when in fact it was.

It turned out that the first part of line 3170 was giving me an error, which was parsed in Braker as not having version 1.8:
```bash
java -version 2>&1
Error occurred during initialization of VM
Could not allocate metaspace: 1073741824 bytes
```

This is probably an issue with how my Singularity container was set up. To resolve this issue, I had to add ```JAVA_TOOL_OPTIONS="-Xmx1g"``` to my Singularity environment. The version command now works.
```bash
java -version 2>&1 
Picked up JAVA_TOOL_OPTIONS: -Xmx1g
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

However, braker.pl at line 3170 is expecting the version number to be in the first line of this output:
```bash
java -version 2>&1 | awk -F[\"\.] -v OFS=. 'NR==1{print $2,$3}'
.
```

If I look at the second line with awk instead, I correctly get 1.8 returned.
```bash
java -version 2>&1 | awk -F[\"\.] -v OFS=. 'NR==2{print $2,$3}'
1.8
```

I needed to edit the braker.pl to change this 1 to a 2 to get it to work for me. However, perhaps a more flexible check can be coded that finds the appropriate line with the version number such as the following:  
```bash
java -version 2>&1 | grep "openjdk version" | awk -F[\"\.] -v OFS=. '{print $2,$3}'
```

**Comment by KatharinaHoff** [comment]
Thank you @ckeeling! https://github.com/Gaius-Augustus/BRAKER/commit/ffc1122cc729bde9268c4414790d7fb0338c654c
