### ISSUE TITLE
genome threader too slow

### ISSUE THREAD

**Issue by pezhmansafdari** [Gaius-Augustus/BRAKER#400]
Hi,

I have found out that I get the best results from the braker if I de novo assemble my RNASeq and map them to the genome with PASA and feed the proteins to breaker as closely related SP as a training set. The problem with this method is that Genome Threader is very slow and takes up to two weeks to map 70,000 proteins. 
What I am wondering is if there is a way to speed up the GTH ( it is dividing the file into 10 no matter how many threads available) or use other software like PASA for generating the hintsfile?
I should add that I used bam files, closely related SP proteins, and the combination of these two. But, de novo assembly of the reads with trinity, mapping them with PASA, and feeding the proteins as closely related SP gives the highest BUSCO score by a large margin. 
All the bests,
Pezhman

**Comment by KatharinaHoff** [comment]
In the current code version in the master branch on github, BRAKER has an option 

```
--traingenes=file.gtf               instead of using GeneMark or GTH to generate
                                              traingenes, provide a gtf file.
```

This was not exactly introduced to enable training from a PASA output. You will have convert the gff3 file to a gtf file, then it should work was well.

Beware: we developed this option for training AUGUSTUS from gene predicted in assembled subreads from PacBio ccs transcriptomes. Our internal results show that this does not work better than using GeneMark-ET with Illumina data for training AUGUSTUS. We tested in _Danio rerio_ and _Araneus ventricosus_. We also tested in Capra hircus, where it did work better, BUT... _Capra hircus_ is a mammal, and it was clear from the start that BRAKER does not adapt certain AUGUSTUS parameters that need to be adjusted for mammalian genomes (i.e. in goat, human parameters will always work better than a retraining).

For gene prediction with assembled PASA transcripts, you could follow the protocol that we developed for including PacBio reads into gene prediction at https://github.com/Gaius-Augustus/BRAKER/blob/master/docs/long_reads/long_read_protocol.md

**Comment by KatharinaHoff** [comment]
I am closing this issue because we will not speed up GenomeThreader (can't).

**Comment by Yutang-ETH** [comment]
Hi all,

Just to let you know, based on my experience with genomethreader, lowering the value of -gcmaxgapwidth, which is said to be the maximum intron length by the manual, would significantly reduce memory usage and accelerate the process of mapping. The default value of this option is 1000000 (1 Mb), which I believe is not practical for plants (I work with plants). For animals or insects, it might be reasonable to use the default value, but here I just want to let you know this option has a large impact on running time and you probably could adjust the value accordingly based on what genome you are studying. Hope this would help.

Best wishes,
Yutang

**Comment by pezhmansafdari** [comment]
Hi,

The other problem is BRAKER splits the genome for threading and if the genome has thousands of contigs that significantly reduces the process. If BRAKER split the protein sequence to the number of provided cores the whole mapping process will be much faster. 

BR,
Pezhman

**Comment by dongzhang0725** [comment]
Have you ever tried ProtHint? It is said to be very fast, check this benchmark: https://github.com/gatech-genemark/ProtHint/tree/master/example

**Comment by Yutang-ETH** [comment]
Hi Pezhman,

Thank you very much for your reply.
What I did is I first split my large protein file to several small chunks with equal size and then use startAlign.pl in Braker2 package to implement genomethreader. This startAlign.pl splits assembly by contigs, so I not only split the assembly but also split my query protein file. Meanwhile, I adjust the max intron length value for genomethreader. So by doing this, it is >300x faster than just applying genomethreader to the whole protein file with the whole assembly and with the default intron length setting.

Hi Zhangdong,
Thank you very much for sharing the information. I saw that prothint uses diamond, so I assume it is fast and I guess they must implement a method to infer splice position, start and stop codon based on the blast results of diamond. Maybe I could have a try.

Best wishes,
Yutang

**Comment by bijendrabio** [comment]
> max intron length value
@Yutang-ETH Curious what max intron length value (-gcmaxgapwidth) you used and suggest specifically for plants?

**Comment by Yutang-ETH** [comment]
> > max intron length value
> > @Yutang-ETH Curious what max intron length value (-gcmaxgapwidth) you used and suggest specifically for plants?

FYI, I used 20 Kb, but you could try larger values. Please see this paper, https://www.sciencedirect.com/science/article/pii/S0092867421014288, they found some large introns (>20kb) in pine. Hope this helps.

Best wishes,
Yutang
