### ISSUE TITLE
The hints file is empty when using more data

### ISSUE THREAD

**Issue by jdavidpeery** [Gaius-Augustus/BRAKER#401]
Currently, I'm trying to run braker using 12 bam files. When I use the first 6 or the last 6, it works just fine. However, when I use all 12, I get the first error mentioned in [Common Problems](https://github.com/Gaius-Augustus/BRAKER#common-problems) - "The hints file is empty. Maybe the genome and the RNA-seq file do not belong together." I did my alignment using STAR and hisat2, and get the same error regardless of which one I use. Any suggestions on what could be going wrong or how I could fix it? The command I'm using to run it is below. Thanks!

braker.pl \
--genome=/scratch/reeu2021/david/braker2/genome/pcg_genome_masked.fasta \
--bam=/scratch/reeu2021/david/braker2/reads/bam/DI_ATCACG_L003_001sorted.bam,\
/scratch/reeu2021/david/braker2/reads/bam/DI_ATCACG_L003_002sorted.bam,\
/scratch/reeu2021/david/braker2/reads/bam/DI_ATCACG_L003_003sorted.bam,\
/scratch/reeu2021/david/braker2/reads/bam/DI_ATCACG_L003_004sorted.bam,\
/scratch/reeu2021/david/braker2/reads/bam/DI_ATCACG_L003_005sorted.bam,\
/scratch/reeu2021/david/braker2/reads/bam/DI_ATCACG_L003_006sorted.bam,\
/scratch/reeu2021/david/braker2/reads/bam/DI_ATCACG_L003_007sorted.bam,\
/scratch/reeu2021/david/braker2/reads/bam/DI_ATCACG_L003_008sorted.bam,\
/scratch/reeu2021/david/braker2/reads/bam/DI_ATCACG_L003_009sorted.bam,\
/scratch/reeu2021/david/braker2/reads/bam/DI_ATCACG_L003_010sorted.bam,\
/scratch/reeu2021/david/braker2/reads/bam/DI_ATCACG_L003_011sorted.bam,\
/scratch/reeu2021/david/braker2/reads/bam/DI_ATCACG_L003_012sorted.bam \
--cores=40 \
--softmasking

**Comment by jdavidpeery** [comment]
Also, I had done this on the unmasked genome and it worked just fine but after masking the genome I get this issue

**Comment by KatharinaHoff** [comment]
Never found out what happend, here... I am closing.
