### ISSUE TITLE
docker Error

### ISSUE THREAD

**Issue by jailynai** [Gaius-Augustus/BRAKER#407]
I run the processing in Braker2 Docker in mac
but I always found the problem：

# Sat Jul 24 13:35:34 2021: Log information is stored in file /usr/Downloads/01-augustus/braker/braker.log
ERROR in file /usr/local/bin/braker.pl at line 6656
Failed to execute: perl /usr/Downloads/gmes_linux_64/gmes_petap.pl --verbose --sequence=/usr/Downloads/01-augustus/braker/genome.fa --ET=/usr/Downloads/01-augustus/braker/genemark_hintsfile.gff --cores=12 --gc_donor 0.001 1>/usr/Downloads/01-augustus/braker/GeneMark-ET.stdout 2>/usr/Downloads/01-augustus/braker/errors/GeneMark-ET.stderr
Failed to execute: perl /usr/Downloads/gmes_linux_64/gmes_petap.pl --verbose --sequence=/usr/Downloads/01-augustus/braker/genome.fa --ET=/usr/Downloads/01-augustus/braker/genemark_hintsfile.gff --cores=12 --gc_donor 0.001 1>/usr/Downloads/01-augustus/braker/GeneMark-ET.stdout 2>/usr/Downloads/01-augustus/braker/errors/GeneMark-ET.stderr

how can i fix them
thanks

**Comment by KatharinaHoff** [comment]
Hhm... never found out what's in the GeneMark output files. Closing here.
