### ISSUE TITLE
which is the max size of gene intron

### ISSUE THREAD

**Issue by mengguoqingup** [Gaius-Augustus/BRAKER#411]
Hello, i have a question
instron>the gap >IGS
which is the max size of gap? 
when the gap less than the max size called gene intron, and greater than the max size called IGS

**Comment by KatharinaHoff** [comment]
I assume that the answer is no longer of interest and will close the issue.

In any case, GeneMark-ES/ET/EP uses a different maximum intron size than AUGUSTUS. In practice, the intron size in BRAKER will in many cases be limited by the allowed gap size in the spliced aligner that produces evidence for gene prediction with AUGUSTUS.
