### ISSUE TITLE
Is the protein prediction results better when incorporating RNA-seq data from the same plant individual? How important is RNA-seq for prediction?

### ISSUE THREAD

**Issue by romseg** [Gaius-Augustus/BRAKER#413]
Dear authors,

I am wondering how important is including RNA-seq data for protein prediction from the same plant specimen I used for sequencing the genome? Would the prediction be more accurate with this RNA-seq data or not? 
I have the option of generating RNA-seq data, but I would only do it if this additional information would produce better prediction results, otherwise I would prefer not to because this would take me a while to get fresh tissue. Thanks.

Romulo

**Comment by romseg** [comment]
Hi Tomas,

I see the importance of using RNA-seq of the same species for the annotation. Now I am wondering how many RNA-seq samples would be the minimum to obtain a good annotation? I will be annotating a diploid plant genome.

My limitation is low budget, so I could only generate a few RNA-seq samples from an adult plant. Perhaps only three: from leaf, flower, and root. Would these samples provide enough evidence for training and prediction of the programs? Or is it necessary to generate more RNA-seq samples? Thank you.

Best,
Romulo

**Comment by tomasbruna** [comment]
Hi Romulo,

In my opinion, the three samples should provide enough evidence. You don't have to worry about covering the full genome with RNA-Seq evidence because a good majority of the genes should already be covered by BRAKER2 with proteins (if you use TSEBRA for combination).

Best,
Tomas

**Comment by romseg** [comment]
Thanks Tomas. I will use TSEBRA for better results.

Best,
Romulo
