### ISSUE TITLE
anaconda installation instructions

### ISSUE THREAD

**Issue by dgordon562** [Gaius-Augustus/BRAKER#415]
I believe (but am not sure) that between:
bash bin/Anaconda3-2018.12-Linux-x86_64.sh # do not install VS (needs root privileges)

and

conda install -c anaconda perl

there should be the following:

export PATH=(anaconda location)/bin:$PATH
export LD_LIBRARY_PATH=(anaconda location)/lib:$LD_LIBRARY_PATH

however this is perhaps not sufficient  because I got:

> conda install -c anaconda perl
Solving environment: failed

CondaValueError: Malformed version string '~': invalid character(s).

what do you suggest?

**Comment by KatharinaHoff** [comment]
At the end of conda installation, it displays instructions on how to export
stuff and initialize conda. Copy that to your ~/.bashrc and source ~/.bashrc

**Comment by dgordon562** [comment]
thanks for your quick response!  following this now...
