### ISSUE TITLE
file_*_file_* in the attributes column of the braker.gtf file

### ISSUE THREAD

**Issue by utritala** [Gaius-Augustus/BRAKER#416]
Hello,
I managed to run BRAKER2 (version 2.1.5) successfully and found that some of the gene ids or transcript ids in the attributes column of the gtf file are prefixed by `file_?_file_?` in the final braker_utr.gtf file. I wonder what does this represent? Example of this is given below: 

```
contig_80761    GUSHR                gene         152158   157224   .     -   .   g26105
contig_80761    GUSHR                transcript   152158   157224   .     -   .   g26105.t1
contig_80761    AUGUSTUS             start_codon  157222   157224   .     -   0   transcript_id "file_1_file_1_g26105.t1"; gene_id "file_1_file_1_g26105";
contig_80761    AnnotationFinalizer  3'-UTR       152158   152396   .     -   .   transcript_id "file_1_file_1_g26105.t1"; gene_id "file_1_file_1_g26105";
contig_76682    AUGUSTUS             stop_codon   83152    83154    .     -   0   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AUGUSTUS             CDS          83152    83207    0.8   -   2   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AUGUSTUS             CDS          85790    85891    0.8   -   2   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AUGUSTUS             CDS          87661    87778    0.89  -   0   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AUGUSTUS             start_codon  87776    87778    .     -   0   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AnnotationFinalizer  3'-UTR       72041    72715    .     -   .   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AnnotationFinalizer  3'-UTR       73081    73191    .     -   .   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AnnotationFinalizer  3'-UTR       73907    73996    .     -   .   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AnnotationFinalizer  3'-UTR       76226    76276    .     -   .   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AnnotationFinalizer  3'-UTR       77971    78095    .     -   .   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AnnotationFinalizer  3'-UTR       78203    78295    .     -   .   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AnnotationFinalizer  3'-UTR       78975    79060    .     -   .   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AnnotationFinalizer  3'-UTR       79305    79444    .     -   .   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AnnotationFinalizer  3'-UTR       81107    82089    .     -   .   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AnnotationFinalizer  3'-UTR       83037    83151    .     -   .   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_76682    AnnotationFinalizer  5'-UTR       87779    87781    .     -   .   transcript_id "file_1_file_1_g1193.t1"; gene_id "file_1_file_1_g1193";
contig_85303    GeneMark.hmm3        stop_codon   59284    59286    .     -   0   gene_id "file_1_file_2_38420_g"; transcript_id "file_1_file_2_38420_t";
contig_85303    GeneMark.hmm3        CDS          59284    59457    .     -   0   gene_id "file_1_file_2_38420_g"; transcript_id "file_1_file_2_38420_t"; cds_type "file_1_file_2_Terminal"; count "file_1_file_2_2_2";
contig_85303    GeneMark.hmm3        exon         59284    59457    0     -   .   gene_id "file_1_file_2_38420_g"; transcript_id "file_1_file_2_38420_t"; cds_type "file_1_file_2_Terminal"; count "file_1_file_2_2_2";
contig_85303    GeneMark.hmm3        CDS          65878    66207    .     -   0   gene_id "file_1_file_2_38420_g"; transcript_id "file_1_file_2_38420_t"; cds_type "file_1_file_2_Initial"; count "file_1_file_2_1_2";
contig_85303    GeneMark.hmm3        exon         65878    66207    0     -   .   gene_id "file_1_file_2_38420_g"; transcript_id "file_1_file_2_38420_t"; cds_type "file_1_file_2_Initial"; count "file_1_file_2_1_2";
contig_85303    GeneMark.hmm3        start_codon  66205    66207    .     -   0   gene_id "file_1_file_2_38420_g"; transcript_id "file_1_file_2_38420_t";
```

Also, how can I perform a sanity check on the output? I have got something like 77662 genes and 80193 transcripts predicted which seems unreal. My assembly is quite fragmented 76218 contigs. Can this cause a problem? Any suggestions here on how to proceed would be really great. 

Many thanks.

**Comment by ilikvlad** [comment]
Hello @tomasbruna, 

I have the same issue and I would like to keep the combination of AUGUSTUS and GeneMark prediction output. Do you have any advice on how to change these predicted genes' names to names based on the names of the scaffolds/contigs that they were predicted from? It would be much easier for downstream analyses to have these information inlcuded in the predicted gene name. 

Thank you,

Best, 

Vladislav

**Comment by tomasbruna** [comment]
Hi Vladislav,

I wrote a quick custom script that does just that. Please get it from: https://gist.github.com/tomasbruna/3bbfc28c49e29f03e75567ab81ab3ab9

Usage:

    ./addContigsToGeneNames.py braker.gtf > braker_contigNames.gtf

Best,
Tomas

**Comment by ilikvlad** [comment]
Hello @tomasbruna and thank you for the script! 

It works for `*.gtf` file format, however not for `*.gff3`. I am not a skilled programmer, so could you please help me with converting the names for `*.gff3` format too? It would be truly helpful if the script could also delete the file_*_file_*_`prefix. Below I attached my example *.gff3 braker2 data.

Thank you, 

BW, 
Vladislav 

[braker.zip](https://github.com/Gaius-Augustus/BRAKER/files/7156240/braker.zip)

**Comment by tomasbruna** [comment]
Hi Vladislav,

sure, here is such script: https://gist.github.com/tomasbruna/cbb718fa551c0b4afd9c6a8ce8ff2592

The usage remains the same:

    ./updateBRAKERGff.py braker.gff3 > braker_updated.gff3

Let me know if this format works for you.

Best,
Tomáš

**Comment by ilikvlad** [comment]
Hello Tomáš, 

thanks, working smoothly! 

Best of luck, 

Vladislav

**Comment by ilikvlad** [comment]
Hello Tomáš, 

sorry for bothering you again... I consulted this with my supervisor and could you please do us a one small favor? Could  you please rewrite the script for *.gff3 files one more time so the name of the gene would include the contig information in the first place? 

So the name would look like this: 

`Contig_name_001.gXXXX.tX.intronXX `

Many thanks, 

BW, 

Vladislav

**Comment by tomasbruna** [comment]
Hi Vladislav,

sure, no problem. I've revised the script, it's here: https://gist.github.com/tomasbruna/cbb718fa551c0b4afd9c6a8ce8ff2592

Let me know whether this is the format you were looking for.

Regards,
Tomáš

**Comment by ilikvlad** [comment]
Hello Tomáš, 

it is almost perfect! The order of the gene names is now perfect, however we would like to ask you one more favor to do. We would like you to delete the *.t1, *.t2 etc. appendix as it marks transcript number and we would have problems with this in the future. The gene isoform name, however, is ok this way, we just need to delete this *.tx appendix from it. 

Thank you, very much appreciate your support and  patience. 

Best, 

Vladislav

**Comment by tomasbruna** [comment]
Hi Vladislav,

this would create an artificial (and likely non-sensical) transcript isoform for genes with more than 1 transcript prediction. Are you sure you want to do that? I would suggest first selecting only one representative isoform per gene before deleting the `.t*` appendix.

Best,
Tomas

**Comment by SchwarzEM** [comment]
Hello Tomas (and Vladislav),

I am Vladislav's supervisor, and I think some confusion may have arisen about what we are asking for.  I agree, completely, that transcripts should end with suffixes like *.t1, *.t2, etc.  What I would like to see is a situation where the "gene=" text precedes names that have had the *.tN suffix stripped from it.  In other words, I'd like to ultimately get FASTA outputs of predicted proteins (or predicted CDS DNAs, or whatever) whose header lines look like this ...

    >Acey_s0217.g307.t1   gene=Acey_s0217.g307
    [M .... (last amino acid residue)]
    >Acey_s0217.g307.t2   gene=Acey_s0217.g307
    [M .... (last amino acid residue)]

... if a given gene (.g307) predicted in the genome scaffold Acey_s0217 happens to have two isoforms.

Obviously, getting a GFF3 with this sort of clear name-formatting is more important than getting a final FASTA.  If we have GFF3 annotation files which do the naming in a helpful way, then it should be feasible to extract coding sequences with gffread + GFF3 + the original genome sequence, as needed.  Conversely, the easier it is to get a well-named FASTA, the easier it is for everybody using BRAKER2 to get gene predictions that make their lives easy (by having the scaffold name embedded right in the gene and the transcript names).
