### ISSUE TITLE
Fail train genes by GeneMark-ES/ET

### ISSUE THREAD

**Issue by haiyun-fan** [Gaius-Augustus/BRAKER#417]
Dear contributor:
 I encountered same errors likes this：xxx/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence support or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for training.

And this is my commond line:
STRA1='xxx/GF.bam'
STRA2='xxx/leaf.bam'
STRA3='xxx/RF.bam'
STRA4='xxx/root.bam'
STRA5='xxx/ST.bam'
STRA6='xxx/FL.bam'
braker.pl --cores 10 --species=test --genome=genome.masked.fasta \
        --softmasking  \
        --prot_seq=./test2.protein.fa  --prg=gth  \
        --bam=${STRA1},${STRA2},${STRA3},${STRA4},${STRA5},${STRA6} \
        --GENEMARK_PATH="xxx/biosoft/gmes_linux_64" \
        --gff3

at the same time my braker version is 2.1.5,can you give some help.

**Comment by haiyun-fan** [comment]
Dear Katharina
      I also change other modeler but encountered same errors，here is my commond ：
   STRA1='/media/fhy/d6ded093-2ba1-4f34-8eae-a5c9d1ee1db2/tom/nextdenovo2/ragoo/ragoo2/Transeq/01-six_tissues/01-STAR/GF.sorted.bam'
STRA2='xxx/leaf.sorted.bam'
STRA3='xxx/RF.sorted.bam'
STRA4='xxx/root.sorted.bam'
STRA5='xxx/ST.sorted.bam'
STRA6='xxx/FL.sorted.bam'
braker.pl --cores 10 --species=MicTom --genome=xxx/nextde_ragoo.v4.fasta.masked \
        --softmasking \
        --bam=${STRA1},${STRA2},${STRA3},${STRA4},${STRA5},${STRA6} \
        --GENEMARK_PATH="/home/xxx/biosoft/gmes_linux_64" \
        --gff3

**Comment by haiyun-fan** [comment]
HI ,it is new erros

#**********************************************************************************
#                               TRAIN AUGUSTUS                                     
#**********************************************************************************
# Wed Sep  8 14:08:31 2021: training AUGUSTUS
# Wed Sep  8 14:08:31 2021: creating softlink from /media/opt/braker/braker/GeneMark-ET/genemark.gtf to /media/opt//braker/braker/traingenes.gtf.
ln -s /media/opt//braker/braker/GeneMark-ET/genemark.gtf /media/opt//braker/braker/traingenes.gtf
# Wed Sep  8 14:08:31 2021: Converting gtf file /media/opt//braker/braker/traingenes.gtf to genbank file
# Wed Sep  8 14:08:31 2021: Computing flanking region size for AUGUSTUS training genes
# Wed Sep  8 14:08:31 2021: create genbank file /media/opt
/braker/braker/train.gb
perl /home/opt/miniconda3/envs/braker2/bin/gff2gbSmallDNA.pl /media/opt/ /ragoo/ragoo2/braker/braker/traingenes.gtf /media/opt//braker/braker/genome.fa 2064 /media/opt/braker/braker/train.gb 2>/media/opt/braker/braker/errors/traingenes.gtf_gff2gbSmallDNA.stderr
#*********
# INFORMATION: the size of flanking region used in this BRAKER run is 2064. You might need this value if you later add a UTR training on top of an already existing BRAKER run.
#*********
# Wed Sep  8 14:08:45 2021: Genbank format file /media/opt/braker/braker/train.gb contains 10808 genes.
#  Wed Sep  8 14:08:45 2021: concatenating good and downsampled GeneMark training genes to /media/opt/braker/braker/good_genes.lst.
cat /media/opt/braker/braker/GeneMark-ET/genemark.d.gtf > /media/opt/braker/braker/good_genes.lst
# Wed Sep  8 14:08:45 2021 ERROR: file /media/opt/braker/braker/good_genes.lst contains no good training genes. This means that with RNA-Seq data, there was insufficient coverage of introns; or with protein data, there was insufficient support from protein alignments/GaTech protein mapping pipeline hints; or without any evidence, there  were only very short genes. In most cases, you will see  this happening if BRAKER was executed with some kind of  extrinsic evidence (either/or RNA-Seq/protein). You can then  try to re-run BRAKER without any evidence for training  and later use the such trained AUGUSTUS parameters for a  BRAKER run without any training and the available evidence. Accuracy of training without any evidence is lower than with  good evidence.

@michaelkarlcoleman @KatharinaHoff

**Comment by KatharinaHoff** [comment]
Well, the error message tells you that you don't have sufficient data for reliable training genes. Did you try running BRAKER with protein data, instead? Otherwise, there's also the option to run without any evidence.

Once trained, you can run BRAKER without training using the evidence of your choice (e.g. the RNA-Seq) even thought that might not help much given that it appears to contain few intron hints.
