### ISSUE TITLE
Error, unexpected condition was detected in GeneMark setup

### ISSUE THREAD

**Issue by tomasbruna** [Gaius-Augustus/BRAKER#418]
Hello,

I am experiencing the same problems as described above (error on running parse_ET.pl, segmentation fault on running gmhmme3 -v and so on) using the latest release of  GeneMark-ES/ET/EP ver 4.68_lic  (Linux 64) in the BRAKER pipeline. 

Running check_install.bash gives the following:

```
Checking GeneMark-ES installation
Checking Perl setup
All required Perl modules were found
Checking GeneMark.hmm setup
GeneMark.hmm was found
GeneMark.hmm is set
Error, unexpected condition was detected
```

I realize that BRAKER was tested with a previous version of GeneMark (GeneMark-ES/ET/EP 4.64_lic), which does not seem to be available for download. Could you please give me some hints for fixing this problem?

Thank you so much!
Hector

_Originally posted by @hcandela in https://github.com/Gaius-Augustus/BRAKER/issues/96#issuecomment-888951218_

**Comment by SunHoLeeM** [comment]
Hello Tomas, I'm having the same problem as Hector.
When trying to run gmhmm3 on its own, it gives segmentation fault.
My OS is Ubuntu 20.04.3 LTS. GeneMark-ES ver 4.68_lic LINUX 64.
Thanks for addressing this.
`suno@DESKTOP-B7K5J6F:~/finaltest/gmes_linux_64/GeneMark-E-tests/GeneMark.hmm/test$ ../../../gmhmme3 -o genemark.gff3 -m ../input/athaliana.mod -f gff3 ../input/sequence.fasta`
`Segmentation fault`

**Comment by tomasbruna** [comment]
Please contact Alex Lomsadze (http://exon.gatech.edu/GeneMark/contact.html) with this information, he will be able to make a working `gmhmme3` binary for your system.

**Comment by SunHoLeeM** [comment]
Will do, thank you a lot Tomas.

**Comment by KatharinaHoff** [comment]
I am closing this issue because it was taken to e-mail conversation about GeneMark.

**Comment by SAMtoBAM** [comment]
Hello
Did this problem get solved?
I am having the same output while running check_install.bash
```
Checking GeneMark-ES installation
Checking Perl setup
All required Perl modules were found
Checking GeneMark.hmm setup
GeneMark.hmm was found
GeneMark.hmm is set
Error, unexpected condition was detected
```

**Comment by tomasbruna** [comment]
Yes, GeneMark now offers versions for different LINUX kernels, see http://exon.gatech.edu/GeneMark/license_download.cgi

Downloading the right version usually fixes this issue.
