### ISSUE TITLE
confusion about --UTR and --addUTR 

### ISSUE THREAD

**Issue by tinyhys** [Gaius-Augustus/BRAKER#419]
![image](https://user-images.githubusercontent.com/37066354/131243752-5476cd4c-22e8-4e2c-adda-4b9714478bfc.png)

Dear developers,
 Thanks for your excellent tools!
 I would like to add UTR features to the annotation result, but I am confused in the two parameter. 
 As the picture shows, in the description of **--UTR=on** , the **--addUTR=on** is used. Should I only TAG --addUTR=on or use both in command line?
Any reply will be grateful!

**Comment by tinyhys** [comment]
I tried using both but failed , so I removed the --addUTR and kept the --UTR=on to allow the UTR training

![image](https://user-images.githubusercontent.com/37066354/131244328-3732a109-7489-4c3e-882a-f5089e265ce2.png)

**Comment by tomasbruna** [comment]
You should only use `--addUTR=on` to add UTRs to an existing annotation result.

This way of adding UTRs is illustrated in the [test examples](https://github.com/Gaius-Augustus/BRAKER#example-data). I recommend you first try running [test3.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3.sh) followed by [test3_add_utrs.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3_add_utrs.sh) to make sure that everything works on your system.

**Comment by tinyhys** [comment]
> You should only use `--addUTR=on` to add UTRs to an existing annotation result.
> 
> This way of adding UTRs is illustrated in the [test examples](https://github.com/Gaius-Augustus/BRAKER#example-data). I recommend you first try running [test3.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3.sh) followed by [test3_add_utrs.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3_add_utrs.sh) to make sure that everything works on your system.

Thanks to your reply!
Sorry for my poor English, by using the words **annotation result**, I mean the **final result** of the braker pipeline as I have no existing annotation result by far~ 
So I would like to employ Augustus to train the UTR parameter in the config/species files. Should I only use --UTR=on ?

BEST WISHES~

**Comment by tomasbruna** [comment]
Hi @tinyhys,

> Sorry for my poor English, by using the words annotation result, I mean the final result of the braker pipeline as I have no existing annotation result by far

No problem, this is actually how I understood your statement. 

> So I would like to employ Augustus to train the UTR parameter in the config/species files. Should I only use --UTR=on ?

Yes, to train AUGUSTUS with UTR model, you would only use `--UTR=on`.

However, the UTR training of AUGUSTUS is not very stable right now. Therefore, it might be better to run a regular BRAKER and add UTRs to existing predictions (annotation result) with `--addUTR=on`.

**Comment by tinyhys** [comment]
> Hi @tinyhys,
> 
> > Sorry for my poor English, by using the words annotation result, I mean the final result of the braker pipeline as I have no existing annotation result by far
> 
> No problem, this is actually how I understood your statement.
> 
> > So I would like to employ Augustus to train the UTR parameter in the config/species files. Should I only use --UTR=on ?
> 
> Yes, to train AUGUSTUS with UTR model, you would only use `--UTR=on`.
> 
> However, the UTR training of AUGUSTUS is not very stable right now. Therefore, it might be better to run a regular BRAKER and add UTRs to existing predictions (annotation result) with `--addUTR=on`.

Thank for your timely reply! I will rerun it as you suggested right now!
