### ISSUE TITLE
The hints file is empty. Maybe the genome and the RNA-seq file do not belong together.

### ISSUE THREAD

**Issue by erroranderroranderror** [Gaius-Augustus/BRAKER#421]
I ran braker with these two files:
1) Yeast genome assembly (fasta file)
2) sorted.bam file produced by bowtie2 with RNA-seq data

However, there are endless errors like:
# Fri Sep  3 15:42:08 2021: Log information is stored in file My_route/braker/braker.log
# Fri Sep  3 15:47:33 2021: ERROR: in file My_route/anaconda3/envs/braker2/bin/braker.pl at line 5614
The hints file is empty. Maybe the genome and the RNA-seq file do not belong together.

and when i ckecked the hintsfile.gff, it's file size was 0.

I also tried to shorten the contig name like utg9, utg10, ... as shown in the 'Common problems'
But, the file size of the hintsfile.gff was still 0.

How could i resolve this error please?
Thank you.

**Comment by KatharinaHoff** [comment]
bowtie2 does not produce spliced alignments. Please use an aligner that
does spliced alignment (e.g. HISAT2 or STAR).

Note, that if you species has no introns, training may fail nevertheless.

Katharina

**Comment by erroranderroranderror** [comment]
Dear Katharina,

Thank you for your reply.

As you mentioned, i processed alignment with HISAT2 and finally it works well.

I will close this thread.

Have a nice day!
