### ISSUE TITLE
BRAKER2 predicting proteins with stop codons in the middle of the protein

### ISSUE THREAD

**Issue by nllg** [Gaius-Augustus/BRAKER#424]
Hello,

I have used BRAKER2 successfully to predict the structure annotation for several plant genomes.
However, I have noticed that in many cases, the proteins predicted contain stop codons in the middle of the protein sequence
for example:
>seq2
MKLRCGGGWKRVPRLTRVSFFL\*ASQRFHNKMKHSKDPFEAAIEEEQEESPPESPAGGGD
DEEGRLEIEQAPEESERDVGVRRQPKKFKSSVAVADGKNKDEDEEEEEENMEAELTKYPT
TADPAKMAKMQVILSQFTEDQMSRYESFRRSAFQKGNMRKLLQGVTGSQKISMPVIIVNC
GIAKMFVGELVETARVVMGERNDSGPIRPCHIRESYRRLKLEGKVPKRSVPRLFR\*

How can we correct this error?

Thank you

Nathaly

**Comment by KatharinaHoff** [comment]
Hi Nathaly,

are you using the most recent version of BRAKER?

I am wondering, because the recent BRAKER executes
fix_in_frame_stop_codon_genes.py , and that's supposed to remove exactly
these internal stop codons. (They result from spliced stop codons in the
first run of AUGUSTUS.)

Best,

Katharina

**Comment by nllg** [comment]
Hi Katharina,

Thank you for your prompt reply.
Indeed I have been running with the previous version of BRAKER2, I did the installation in December 2019.

Ok, I will run with the latest version. However, for some reason, even though I specifically indicate -gff3 option, it only gives the .gtf file (this is from the installation in July 2021)
Is there a way that I can fix this, we do need the .gff3 file 

Thank you,

Nathaly

**Comment by nllg** [comment]
Hi Katharina,

I have just checked the protein file predicted from the new BRAKER v2.1.6 
There are still stop codons in the middle of the protein sequence

>g56957.t1
MVDNKPIMEQVPEYENLTGDVVNEDMKICEIFQANVLLEKFAPSCSDYRNQLKHKKKNLT
LRELISHMRTEEANRLKDKMEELSINSSKSNLVESYVTVVKDRLKGKQKEVSKKELMKKK
NQLNKLESQIQKFEGSCFVCGKIGHRDARCYQRKGKD\*AHLVEQIESELGVLGIVMERNR
TSSSGGQDPIPAPASGNTIRGPYLLMQRLFMDMCKIVSRGMGQLKLYPILLSRQVFQDTL
ARMLEILEGMDQAGALSVTSDGSQTRVGGQTQDLIVAPESQTPRTQPAAVVATRFDIMEF
PDMTSHLVNRPSMTIDEQKMFGRFRIMNPPTYTGDLGEDAYEVIVSCYDRLHNLGFLESH
GVDYTTFQMTGSAKQWWRDYISSRPAGSHPLSWTEFTQVFLSKFVLRSERERKRAGFEGL
QQNGMSIIEYEGKFHALARHASMILPTEAERKVVDAAKELEMIRREGFEQREGKRTRYSG
DYGGAPPRSRGYLGRGYHPQSSRPIHAAIPASEAGYAEHNSSSSVHTSGYFECGDMGHFV
RDCPRTRRGGLPQGSQGSTSRAAQPPARCCAKNGRGGSHSGRGGSPFGRGGVRGGSQSDG
GRSHCYAFPGSHLVEQIESELGVLGVVVPSRLANLVLDKDSKKDGESDVHANLAEDMTLW
GRQASPVFLHCDSQPVRKKFGGSYDRGLETKIILERSRGIGLNPID\*

Could you please help?

Thank you,

Nathaly

**Comment by KatharinaHoff** [comment]
gtf2gff.pl will help you.

NAME
    gtf2gff.pl format convert a GTF file

SYNOPSIS
    gtf2gff.pl <in.gtf --out=out.gff

        Besides easy by-line changes this script can in particular swap
between the different representations of UTRs:
        a) explicit UTR lines (e.g. 3'-UTR or three_prime_utr)
        b) implicit specification by 'exon' and 'CDS' features

OPTIONS
      out                 gff output file
      --printExon         print exon features (may include CDS and UTR
parts)
      --printUTR          print UTR features
      --printIntron       print intron features
      --gff3              output in gff3 format
      --includeStopInCDS  include stop codon in the CDS

DESCRIPTION
        example input:

        chr1 AUGUSTUS  gene        12656   14013   0.04    +   .   g50
        chr1 AUGUSTUS  transcript  12656   14013   0.04    +   .   g50.t1
        chr1 AUGUSTUS  tss         12656   12656   .       +   .
transcript_id "g50.t1"; gene_id "g50";
        chr1 AUGUSTUS  5'-UTR      12656   12867   0.2     +   .
transcript_id "g50.t1"; gene_id "g50";
        chr1 AUGUSTUS  start_codon 12868   12870   .       +   0
transcript_id "g50.t1"; gene_id "g50";
        chr1 AUGUSTUS  intron      12994   13248   1       +   .
transcript_id "g50.t1"; gene_id "g50";
        chr1 AUGUSTUS  CDS         12868   12993   0.8     +   0
transcript_id "g50.t1"; gene_id "g50";
        chr1 AUGUSTUS  CDS         13249   13479   1       +   0
transcript_id "g50.t1"; gene_id "g50";
        chr1 AUGUSTUS  stop_codon  13477   13479   .       +   0
transcript_id "g50.t1"; gene_id "g50";
        chr1 AUGUSTUS  3'-UTR      13480   14013   0.17    +   .
transcript_id "g50.t1"; gene_id "g50";
        chr1 AUGUSTUS  tts         14013   14013   .       +   .
transcript_id "g50.t1"; gene_id "g50";

        example output for --gff3 --printExon:

        chr1 AUGUSTUS  gene                     12656   14013   0.04    +
.   ID=g50;
        chr1 AUGUSTUS  mRNA                     12656   14013   0.04    +
.   ID=g50.t1;Parent=g50;
        chr1 AUGUSTUS  transcription_start_site 12656   12656   .       +
.   ID=g50.t1.tss1;Parent=g50.t1;
        chr1 AUGUSTUS  five_prime_utr           12656   12867   0.2     +
.   ID=g50.t1.5UTR1;Parent=g50.t1;
        chr1 AUGUSTUS  exon                     12656   12993   .       +
.   ID=g50.t1.exon1;Parent=g50.t1;
        chr1 AUGUSTUS  start_codon              12868   12870   .       +
0   ID=g50.t1.start1;Parent=g50.t1;
        chr1 AUGUSTUS  CDS                      12868   12993   0.8     +
0   ID=g50.t1.CDS1;Parent=g50.t1;
        chr1 AUGUSTUS  intron                   12994   13248   1       +
.   ID=g50.t1.intron1;Parent=g50.t1;
        chr1 AUGUSTUS  CDS                      13249   13479   1       +
0   ID=g50.t1.CDS2;Parent=g50.t1;
        chr1 AUGUSTUS  exon                     13249   14013   .       +
.   ID=g50.t1.exon2;Parent=g50.t1;
        chr1 AUGUSTUS  stop_codon               13477   13479   .       +
0   ID=g50.t1.stop1;Parent=g50.t1;
        chr1 AUGUSTUS  three_prime_utr          13480   14013   0.17    +
.   ID=g50.t1.3UTR1;Parent=g50.t1;
        chr1 AUGUSTUS  transcription_end_site   14013   14013   .       +
.   ID=g50.t1.tts1;Parent=g50.t1;

**Comment by nllg** [comment]
Hi Katharina,

Thank you for the gtf2gff.pl tip.

I will look into it.

Do you know what can I do about the stop codons predicted in the middle of the protein sequences with BRAKER v2.1.6?

Thank you,

Nathaly

**Comment by KatharinaHoff** [comment]
Sure, you can run the same script on the old AUGUSTUS gtf/gff3. The fix_…
script.

Best,

Katharina

**Comment by nllg** [comment]
Hi Katharina,

Thanks for this, where can I find the fix_in_frame_stop_codon_genes.py script?

Best,

Nathaly

**Comment by KatharinaHoff** [comment]
It's part auf AUGUSTUS/scripts

Best,
Katharina

**Comment by nllg** [comment]
found it!

Thank you very much!!!

Best,

Nathaly

**Comment by nllg** [comment]
Hi Katharina,

I have ran the fix_in_frame_stop_codon_genes.py script and it still does not fix the in-frame stop codons.

Could you please advise further?

Thank you,

Nathaly

**Comment by hcsun1** [comment]
Hi,
I also have the same problem: There is a stop codon in the middle of the protein sequence. Is it solved? 

Thank you.

**Comment by tomasbruna** [comment]
Hi @hcsun1,

how many times does this happen, does the stop codon occur only in one protein sequence? Are you translating the predictions to proteins yourself, or are the stop codons in the protein output produced by BRAKER? Are you running the latest version of BRAKER which uses the `fix_in_frame_stop_codon_genes.py` script?

Thanks for the info!
Tomas

**Comment by hcsun1** [comment]
Hi tomas,

Thank you for your reply.

I have run the latest version of BRAKER 2.1.6,

/data/lilab/zjwang1/software/BRAKER-2.1.6/scripts/braker.pl --species=$species \
    --genome=$genome \
    --softmasking \
    --bam=./rnaseq.bam\
    --cores=$threads \
    --AUGUSTUS_CONFIG_PATH=/data/lilab/zjwang1/software/new_augustus/Augustus-3.4.0/config \
    --BAMTOOLS_PATH=/data/lilab/zjwang1/software/bamtools/bin \
    --SAMTOOLS_PATH=/data/lilab/zjwang1/software/samtools \
    --GENEMARK_PATH=/data/lilab/zjwang1/software/gmes_linux_64 \
    --CDBTOOLS_PATH=/data/lilab/zjwang1/software/cdbfasta \
    --gff3 \
    --useexisting

 but i also find the stop codon ( X ) in the augustus.hints.aa.
>g28012.t1
MHKHTKLVCNGNGDGAASSINLLKSDEQRQQHTYNYKYYFLFTVVILVTLLLTVVKQLKR
DLTTDIKLGLSLSPSAASQRVQHNPSQSQSAERGRASEKNLIGPVIQKMNAATADDEHND
VEXXXXXXNTREDWGDDVDRVHSGHNDLHVLTYEDEEGDWLIVGDVPWEMFLSAAKRLKI
TRTFP*

I extracted the protein sequence from augustus.hints.gff3 by gffread software, but i also find the stop coden ( . ) in the middle of some protein sequece.
>g5782.t1
MYTISPVHHAKYSSPNPPQATFQSCLPSSVIKVPPPSN.KKKKKKQEKNSNQTLVQNNLSGTWTNPACYA
APVKYIAVPVICNNYANVKVDQPEQGGMKVEENMSSGVNNEGMDGIFWGKMSESFPVFDDSIWT

Could you please advise further?

Thank you,
hcsun

**Comment by KatharinaHoff** [comment]
The X is an unknown amino acid.

**Comment by hcsun1** [comment]
Hi,Katharina
Thank you for your reply.
Why are there unknown amino acids and how to  transform them 

And I extracted the protein sequence from augustus.hints.gff3 by gffread software, i really find the stop coden ( . ) in the middle of some protein sequece.
g5782.t1
MYTISPVHHAKYSSPNPPQATFQSCLPSSVIKVPPPSN.KKKKKKQEKNSNQTLVQNNLSGTWTNPACYA
APVKYIAVPVICNNYANVKVDQPEQGGMKVEENMSSGVNNEGMDGIFWGKMSESFPVFDDSIWT

Thank you

**Comment by KatharinaHoff** [comment]
Unkown amino acids result from unknown nucleotides in the genome. You
cannot “fix” the X if DNA has Ns….

**Comment by hcsun1** [comment]
Hi,Katharina
Thank you for your reply.

I extracted the protein sequence from augustus.hints.gff3 by gffread software.
## gffread  augustus.hints.gff3 -g genome.fa -y pep.fa

I not find unkonwn amino acids ,but i find stop coden amino acids (.).

Do you know what can I do about the stop codons predicted in the middle of the protein sequences ?
g5782.t1
MYTISPVHHAKYSSPNPPQATFQSCLPSSVIKVPPPSN.KKKKKKQEKNSNQTLVQNNLSGTWTNPACYA
APVKYIAVPVICNNYANVKVDQPEQGGMKVEENMSSGVNNEGMDGIFWGKMSESFPVFDDSIWT

Best,
hcsun

**Comment by KatharinaHoff** [comment]
augustus.hints.aa provides protein sequences. In the example that you show
from that file, there is no in frame stop.

You show gffread results for a different gene. It has a stop but it remains
unclear whether the problem persists in the provided protein file.

It is possible that there is an error in the gff3 file since we primarily
work with gtf. I recommend using the provided gtf and aa file.

**Comment by hcsun1** [comment]
Hi,Katharina

This same gene in the provided protein file 'augustus.hints.aa'.
>g5782.t1
MYTISPVHHAKYSSPNPPQATFQSCLPSSVIKVPPPSNXXXXXXXXXXXSNQTLVQNNLS
GTWTNPACYAAPVKYIAVPVICNNYANVKVDQPEQGGMKVEENMSSGVNNEGMDGIFWGK
MSESFPVFDDSIWT*

I am worried that these unknown amino acids will affect the evolutionary tree construction and other subsequent analysis.
 
Best,
hcsun

**Comment by KatharinaHoff** [comment]
Yes, and it doesn’t have a stop in frame. There is only a terminal stop.
You can exclude protein sequences with Xs from your analysis. But the only
way to “fix” the Xs is changing the genome.
