### ISSUE TITLE
Which version of BRAKERv2.1.2 depends on GeneMark-ES?

### ISSUE THREAD

**Issue by slbai01** [Gaius-Augustus/BRAKER#43]
Hi,

I install `braker2` by `conda install braker2`, and download `GeneMark-ESv4.38` at [http://topaz.gatech.edu/GeneMark/license_download.cgi](http://topaz.gatech.edu/GeneMark/license_download.cgi).

When I run `braker.pl --species=test --genome=../00.ref/ref.fa --hints=../01.gth_alignment/merge.hints --epmode`, I got a error

```shell
error on command line: /programs/GeneMark-ES/gm_et_linux_64/gmes_petap/gmes_petap.pl
Unknown option: ep_score
Unknown option: ep
```

`gmes_petap.pl` Algorithm options like:
```shell
Algorithm options
  --ES           to run self-training
  --fungus       to run algorithm with branch point model (most useful for fungal genomes)
  --ET           [filename]; to run training with introns coordinates from RNA-Seq read alignments (GFF format)
  --et_score     [number]; 4 (default) minimum score of intron in initiation of the ET algorithm
  --evidence     [filename]; to use in prediction external evidence (RNA or protein) mapped to genome
  --training     to run only training step
  --prediction   to run only prediction step
  --predict_with [filename]; predict genes using this file species specific parameters (bypass regular training and prediction steps)
```

Does this mean that the `EP` algorithm has been removed?

I want to use the protein sequence of unknown evolutionary distance to predict the genes of the genome. Looking forward to your answer

Shenglong

**Comment by KatharinaHoff** [comment]
Things have moved a bit back and forth with the genemark options over time. (Another example is the name for softmasking option...)

Please download GeneMark-ES Suite version 4.46 . It contains all options required by the current BRAKER code on github.
