### ISSUE TITLE
How to choose the best proteins for annotation

### ISSUE THREAD

**Issue by mictadlo** [Gaius-Augustus/BRAKER#432]
Hi Ian,
I downloaded 1009 proteins for Nicotiana benthamiana from Genbank. After the below filtering I end up with 663 ammino acids sequences:

```
$ grep ">" NbenthamianaGenbankAA.fasta | grep -v partial | grep -v like | grep -v unnamed | wc -l
663
```
However, I noticed many identical descriptions ( https://docs.google.com/document/d/1aAdIAowHjX6D_UtMmOrsn8NByrO2nYOwtivdk5O1ECI/edit?usp=sharing ) but with different IDs and sequence lengths.

How do I choose the protein from the above example and are there any better filtering steps?

Thank you in advance,

Best wishes,

Michal

**Comment by mictadlo** [comment]
Thank you for your reply, I combined those files in the following way:

```
$ cat NbenthamianaGenbankAA.fasta plants/Rawdata/* > genbank-orthodb.aa.fasta
$ sed -r 's/^([^|]+\|){3}//;s/\|//' genbank-orthodb.aa.fasta > genbank-orthodb.aa.clean.fasta
```

Currently, I run Braker with Genbank and orthodb proteins in the following way:

```
braker.pl  --genome=NbLab330.genome.softmasked.fasta --species=LAB330 --prot_seq=genbank-orthodb.aa.fasta --softmasking --gff3 --cores 2 --nocleanup --GENEMARK_PATH=/apps/ProtHint-2.6.0/dependencies/GeneMarkES --PROTHINT_PATH=//apps/ProtHint-2.6.0/bin 
```
I would like to use Braker's results or its temporary results also to train GlimmerHMM and SNAP. After all annotation tools are finished then I would like to merge them with EvidenceModeller. Do I need to include the below parameters, and which files can be used to train those annotation tools?

```
--AUGUSTUS_ab_initio
--crf 
--keepCrf 
```
Thank you in advance,
Michal

**Comment by KatharinaHoff** [comment]
You don’t need MAKER, just see how they train SNAP and GLIMMER (tools, file
formats…)… I found it useful when I had to train them.

**Comment by mictadlo** [comment]
Hi,
I found [here](https://biowize.wordpress.com/2012/06/01/training-the-snap-ab-initio-gene-predictor/) how to train SNAP. They provide a script to convert GFF3 to SNAP's ZFF format (gff3_to_zff.pl). Should I use `augustus.hints.gff3` or `braker.gff3` to train SNAP?

Thank you in advance

Michal

**Comment by KatharinaHoff** [comment]
I recommend to convert the gtf file that was used for training AUGUSTUS to
gff3…

**Comment by mictadlo** [comment]
What is the name of the gtf file which was used to train Augustus?

**Comment by mictadlo** [comment]
Was `traingenes.good.gtf` or `augustus.hints.gtf`  used for training of AUGUSTUS?

**Comment by KatharinaHoff** [comment]
The name and location depends on the way that BRAKER was run. In ETP mode,
for example, there are two
files genemark.f.multi_anchored.gtf genemark.f.single_anchored.gtf in a
folder GeneMark-ETP. In other modes, there are different files in different
folders. These genes are not the exact training gene configuration that is
used for AUGUSTUS (they are e.g. further filtered to remove redundancy,
genes with many exons will be enriched), but these filtered GeneMark genes
will serve as a good basis for training gene finders.

**Comment by KatharinaHoff** [comment]
Responding to your specific question: traingenes.good.gtf is what you are
looking for.
Alternatively, you could filter the augustus.hints.gtf for evidence
supported genes. That will also work well.

**Comment by mictadlo** [comment]
Hi Katharina,
Thank you for your response. 

```

--epmode                            Run ProtHint to generate protein hints (if
                                    not already specified with --hints option)
                                    and use the hints in GeneMark-EP+ to create
                                    a training set for AUGUSTUS.
--etpmode                           Use RNA-Seq and protein hints in GeneMark-ETP+
                                    to create a training set for AUGUSTUS. The
                                    protein hints are generated by ProtHint (see
                                    --epmode).
```

1. Is `--epmode` default?
2. Previously, you mentioned that EvidenceModeler could not model the evidence for
BRAKER genes, but if I would instead of using `--epmode` or `etpmode` I would use `--trainFromGth --gth2traingenes --prg=gth`` then EvidenceModeler would work?

Thank you in advance,

Michal

**Comment by KatharinaHoff** [comment]
`--epmode` is the best mode to integrate information for a huge database of proteins (this may include proteins of a close relatives as well) with BRAKER.

`--etpmode` should no longer be used. Please use TSEBRA for stable accuracy. https://github.com/Gaius-Augustus/TSEBRA

I am not sure whether BRAKER will produce suitable evidence for running EvidenceModeler with `--prg=gth` (an option that we intend to remove permantently) since we trim the CDS hints for AUGUSTUS. You will likely still have to compile custom evidence to make it work well.
