### ISSUE TITLE
Core dump at bam2hints step

### ISSUE THREAD

**Issue by kazuaki0816** [Gaius-Augustus/BRAKER#435]
I have downloaded braker v2.1.6 from github, compiled and used it. Augustus v3.4.0 is also downloaded from github and used. When I run the following command it stops at the bam2hints step. However, the problem is not reproduced when using the files in the braker example directory.
# Genome sequence indexing
	$ hisat2-build -f /home/local/Genome.fasta.masked.simple_header.fna /home/local/Genome/index/INDEX &
# Mapping
	$ hisat2 -p 8 -q -x /home/local/Genome/index/INDEX -1 R1_val_1.fq.gz -2 R2_val_2.fq.gz -S /home/local/Mapping/Mapped.sam --dta-cufflinks 
	$ samtools sort -n -@ 2 /home/local/Mapping/Mapped.sam -o /home/local/Mapping/Mapped_sort.bam
# Braker
	$ pyenv local 3.7.2
	$ nohup braker.pl --species=animal1 --cores=16  --genome=/home/local/Genome.fasta.masked.simple_header.fna --prot_seq=/home/local/protein.faa --prg=gth --min_contig=10000 --bam=/home/local/Mapping/Mapped_sort.bam --softmasking --addUTR=on --GUSHR_PATH=/home/local/tool/BRAKER/scripts/GUSHR &

In bam2hints.0.stderr, there is a message like the following.
	Segmentation fault (core dumped)

Then, the following message is displayed in the log.
	ERROR in file /home/local/tool/BRAKER/scripts/braker.pl at line 5580
	Failed to execute: /home/local/tool/Augustus/src/../config/../bin/bam2hints --intronsonly --in=/home/local/Mapping/Mapped_sort.bam --out=/home/local/Braker/braker/bam2hints.temp.0.gff 1> /home/local/Braker/braker/errors/bam2hints.0.stdout 2>/home/local/Braker/braker/errors/bam2hints.0.stderr!
	mv: '/home/local/Braker/braker/genemark_hintsfile.gff.rnaseq.tmp' Can't stat it: There is no such file or directory
	ERROR in file /home/local/tool/BRAKER/scripts/braker.pl at line 6314
	Failed to execute: mv /home/local/Braker/braker/genemark_hintsfile.gff.rnaseq.tmp /home/local/Braker/braker/genemark_hintsfile.gff

I would appreciate it if you could provide a clear solution to this problem.

**Comment by tomasbruna** [comment]
bam2hints is a part of [Augustus](https://github.com/Gaius-Augustus/Augustus), please open an issue there. It would be helpful if you can prepare a relatively small example bam file that causes the segmentation fault.
