### ISSUE TITLE
error while running unsupervised GeneMark-ET training

### ISSUE THREAD

**Issue by guptapa** [Gaius-Augustus/BRAKER#436]
Hi,
I'm getting following error recorded in gmes.log file while running unsupervised GeneMark-ET training and prediction to generate template genes for training AUGUSTUS:

/home/genome/augustus_training/braker/dependencies/gm_et_linux_64/gmes_petap.pl : [Mon Oct 18 13:47:29 2021] /home/genome/augustus_training/braker/dependencies/gm_et_linux_64/make_nt_freq_mat.pl --cfg /home/GuptaP/run.cfg --section donor_GT    --format DONOR 
/home/genome/augustus_training/braker/dependencies/gm_et_linux_64/gmes_petap.pl : [Mon Oct 18 13:47:29 2021] error

Details in std out file:

check before run
create directories
commit input data
data report
commit training data
training data report
prepare initial model
get GC of sequence
GC 42
build initial ET model
error, no valid sequences were found
error on call: /home/genome/augustus_training/braker/dependencies/gm_et_linux_64/make_nt_freq_mat.pl --cfg /home/GuptaP/run.cfg
 --section donor_GT    --format DONOR

Need help!

Thanks,
Parul

**Comment by guptapa** [comment]
Hi Tomas,
I didn’t try test1.sh but using following script:
/home/augustus_training/braker/dependencies/gm_et_linux_64/gmes_petap.pl --verbose --cores=60 -—sequence=genome.fasta --ET=rice_introns.f.gff

I am following “Alternate Protocol 1—Generating Training Gene Structures from Short Read RNA-Seq Data” from https://math-inf.uni-greifswald.de/storages/uni-greifswald/fakultaet/mnf/mathinf/stanke/augustus_wrp.pdf  and got stuck at Step 8.
Take a look at attached log file.
Please help!

Thanks,
Parul



On Oct 22, 2021, at 3:52 PM, Tomáš Brůna ***@***.******@***.***>> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


Hi Parul,

did you try running the example in test1.sh<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGaius-Augustus%2FBRAKER%2Fblob%2Fmaster%2Fexample%2Ftests%2Ftest1.sh&data=04%7C01%7CParul.Gupta%40oregonstate.edu%7C933487739f2649ed492b08d9959dcf60%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637705327290346774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DNiGykuXDZZr5NWPmJ2bsdU28zhiHK2lmE6Mg1gl4b8%3D&reserved=0> and did that run without issues? Can you also share the full braker.log file?

Best,
Tomas

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGaius-Augustus%2FBRAKER%2Fissues%2F436%23issuecomment-949952252&data=04%7C01%7CParul.Gupta%40oregonstate.edu%7C933487739f2649ed492b08d9959dcf60%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637705327290356730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MHp%2Fr%2BXigUPYrdRqoxfySIcWcNoAYK6gpnYQUisKnu8%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADSLCGIRNGRBWYMWLJKNUETUIHFHNANCNFSM5GHWAOSQ&data=04%7C01%7CParul.Gupta%40oregonstate.edu%7C933487739f2649ed492b08d9959dcf60%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637705327290356730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g8riHSvP40Dt5X3Lpvh1kp2GzC3fMafTkuEhOZTY8To%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CParul.Gupta%40oregonstate.edu%7C933487739f2649ed492b08d9959dcf60%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637705327290366687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RPncnsw0CgqfQ1AIUz5wk6AxoAyIej1DP%2Bbe7Avm9Qw%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CParul.Gupta%40oregonstate.edu%7C933487739f2649ed492b08d9959dcf60%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637705327290376644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ryfxNOWrMP5n1tDvex6wEq2awz2PbuniJ5EDbQJjzJQ%3D&reserved=0>.

**Comment by tomasbruna** [comment]
Hi Parul,

is your genome repeat masked?

I see that you are working with a rice genome (based on the file `rice_introns.f.gff`). GeneMark and other _ab initio_ gene predictors struggle with rice and other grasses due to   [GC3 heterogeneity](https://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-11-308) (this is a problem we are addressing currently). High-quality repeat masking can help to alleviate this issue in the current BRAKER version.

Best,
Tomas

**Comment by Fu-Yin** [comment]
hi, I meet a same issue, my genome only 12M


check before run
create directories
commit input data
data report
commit training data
  aining data report
prepare initial model
get GC of sequence
GC 49
build initial ET model
running step ET_A
running gm.hmm on local multi-core system
10 contigs in training
        (in cleanup)    (in cleanup)  at /perl5/lib/perl5/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /perl5/lib/perl5/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /perl5/lib/perl5/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /perl5/lib/perl5/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /perl5/lib/perl5/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /perl5/lib/perl5/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /perl5/lib/perl5/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at/perl5/lib/perl5/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /perl5/lib/perl5/Object/InsideOut.pm line 1953 during global destruction.
        (in cleanup)    (in cleanup)  at /perl5/lib/perl5/Object/InsideOut.pm line 1953 during global destruction.
concatenate predictions: /media/fuy/04.Giardia_genome/assemblageA/run/ET_A_1
training level ET_A: /media/fuy/04.Giardia_genome/assemblageA/run/ET_A_1
From 13946 loaded 13946 and ignored dublications 0
exon    no_match        match_one       match_two
Initial 1535    1       0
Internal        2978    0       0
Terminal        1533    1       0
Single  514     0       0
CDS_no_match    all     short   long    seq_short       seq_long
CDS_no_match    6560    3784    2776    1650690 4236300
Intergenic      all     between_match   seq_match
Intergenic:     2057    0       0
error, no valid sequences were found
error on call: /pub/software/gm_et_linux_64/gmes_petap/make_nt_freq_mat.pl --cfg run.cfg --section stop_TAA   --format TERM_TAA

**Comment by tomasbruna** [comment]
Hi @Fu-Yin,

in your case, almost no predicted introns are supported by RNA-Seq. This is causing the error.

Are you working with Giardia? The cause of the problem could actually be the fact that Giardia contains very few introns.

Best,
Tomas

**Comment by Fu-Yin** [comment]
> 你好@Fu-Yin,
> 
> 在您的情况下，RNA-Seq 几乎不支持预测的内含子。这导致了错误。
> 
> 你和贾第虫一起工作吗？问题的原因实际上可能是贾第鞭毛虫内含子很少。
> 
> 最好的， 托马斯

Thank you for your guidence, and you are correct, The genome of Giardia is very compactness.
Braker stoped, and I have no idea to make it to continue. 
Could you give me some advice?

**Comment by tomasbruna** [comment]
You can try running BRAKER in the `--esmode` (as illustrated in [test8.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test8.sh)). This could work because the `--esmode` does not rely on evidence-supported introns.
