### ISSUE TITLE
getAnnoFastaFromJoingenes problem

### ISSUE THREAD

**Issue by XK4959** [Gaius-Augustus/BRAKER#438]
Hello, I encountered some problems when running this genome in esmode mode. It was successful to run other genomes before, but I don’t know where the problem lies.

error report：ERROR in file /home/wanghm/miniconda/envs/braker2/bin/braker.pl at line 9646
Failed to execute: /home/wanghm/miniconda/envs/braker2/bin/python3 /home/wanghm/miniconda/envs/braker2/bin/getAnnoFastaFromJoingenes.py -g /home/wanghm/gaoxl/sqf/braker/genome.fa -f /home/wanghm/gaoxl/sqf/braker/augustus.ab_initio.gtf -o /home/wanghm/gaoxl/sqf/braker/augustus.ab_initio 1> /home/wanghm/gaoxl
/sqf/braker/getAnnoFastaFromJoingenes.augustus.ab_initio_tmp.stdout 2>/home/wanghm/gaoxl/sqf/braker/errors/getAnnoFastaFromJoingenes.augustus.ab_initio_tmp.stderr

Attached are log files and genomes that may be useful：
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/7402087/braker.log)
[aa2nonred.stderr.txt](https://github.com/Gaius-Augustus/BRAKER/files/7402089/aa2nonred.stderr.txt)
[getAnnoFastaFromJoingenes.augustus.ab_initio_tmp.stderr.txt](https://github.com/Gaius-Augustus/BRAKER/files/7402090/getAnnoFastaFromJoingenes.augustus.ab_initio_tmp.stderr.txt)
[sqf.fa.txt](https://github.com/Gaius-Augustus/BRAKER/files/7402091/sqf.fa.txt)

**Comment by KatharinaHoff** [comment]
Fixed by commit https://github.com/Gaius-Augustus/Augustus/commit/867e73567dec2e8a6b2855b8346d94c8bdf5cd22 in AUGUSTUS. 

This is not part of a release (and might take a while). Update by `git pull` or by replacing your local copy of getAnnoFastaFromJoingenes.py with https://raw.githubusercontent.com/Gaius-Augustus/Augustus/867e73567dec2e8a6b2855b8346d94c8bdf5cd22/scripts/getAnnoFastaFromJoingenes.py

**Comment by Huangzhongchao6** [comment]
I also have the same problem.
there are errors:
ERROR in file /ifs1/User/huangzhongchao/mambaforge/envs/braker/bin/braker.pl at line 9957
Failed to execute: /ifs1/User/huangzhongchao/mambaforge/envs/braker/bin/python3 /ifs1/User/huangzhongchao/mambaforge/envs/braker/bin/getAnnoFastaFromJoingenes.py -g /ifs1/User/huangzhongchao/777777braker_test/Soly/Soly_test/genome.fa -f /ifs1/User/huangzhongchao/777777braker_test/Soly/Soly_test/augustus.Ppri5.gtf -o /ifs1/User/huangzhongchao/777777braker_test/Soly/Soly_test/augustus.Ppri5 1> /ifs1/User/huangzhongchao/777777braker_test/Soly/Soly_test/getAnnoFastaFromJoingenes.augustus.Ppri5_tmp.stdout 2>/ifs1/User/huangzhongchao/777777braker_test/Soly/Soly_test/errors/getAnnoFastaFromJoingenes.augustus.Ppri5_tmp.stderr
Command exited with non-zero status 1
