### ISSUE TITLE
Braker, the most part of prediction are fragmented

### ISSUE THREAD

**Issue by mehiel96** [Gaius-Augustus/BRAKER#439]
Hi, 
I’m using Braker on the longest scaffold of my genome of interest (as test).
I used the following command: 

braker.pl --genome scaffold.fasta --prot_seq proteoma_carnivora.faa 
--GENEMARK_PATH gmes_linux_64 
--PROTHINT_PATH /mnt/DATA/Software/ProtHint/bin/ 
--bam=sorted.bam --cores=48 --etpmode 
--AUGUSTUS_ab_initio --workingdir=./test_braker
--addUTR=on --GUSHR_PATH /mnt/DATA/Software/GUSHR

Then, I ran BUSCO with carnivora database, on the following augustus.hints.aa and augustus.hints.codingseq for checking the completeness, but no gene has been found.
Meanwhile, when I ran BUSCO with my scaffold, using the -m genome, I obtain around 250 genes.

I checked the output, and I saw that the most part of the predictions are fragmented. 
What could be the solution to this issue?

Thanks for the attention

**Comment by CIWa** [comment]
Hi Katharina,

I am annotating a vertebrate genome, and ran into some issues with the training of AUGUSTUS. The automatically computed parameters generated a highly fragmented, low BUSCO completeness score output, therefore I went with the human parameter set which worked very well for my RNASeq-supported approach.
However, when I try to use the human parameter set for the training with proteins from orthoDB, GeneMark-ES doesn't produce any output, and the braker run fails.

My command: 
`braker.pl --nocleanup --softmasking --cores 48 --species=human --epmode --prot_seq=proteins.fasta --genome=masked .fasta --skipAllTraining
`

I am pretty sure that this is not a problem with my data, as test2.sh, which ran without problems for me before, now failed when I modified it to mimic my original call:
`braker.pl --nocleanup --skipAllTraining --species=human --genome=../genome.fa --prot_seq=../proteins.fa --epmode --sof
tmasking --workingdir=$wd --cores=48 --gm_max_intergenic 10000` 
The error message:

```
error: File "/home/programs/BRAKER-2.1.6/example/tests/test2/GeneMark-ES/genemark.gtf" was not found.
ERROR in file /home/programs/BRAKER-2.1.6/scripts/braker.pl at line 5356
failed to open file /home/programs/BRAKER-2.1.6/example/tests/test2/prothint_augustus.gff
```


The braker.log file:

```
#**********************************************************************************
#                               BRAKER CONFIGURATION                               
#**********************************************************************************
# BRAKER CALL: /home/programs/BRAKER-2.1.6/scripts/braker.pl --nocleanup --skipAllTraining --species=human --genome=../genome.fa --prot_seq=../proteins.fa --epmode --softmasking --workingdir=test2 --cores=48 --gm_max_intergenic 10000
# Wed May 11 14:24:01 2022: braker.pl version 2.1.6
# Wed May 11 14:24:01 2022: Creating directory /home/programs/BRAKER-2.1.6/example/tests/test2.
# Wed May 11 14:24:01 2022: Configuring of BRAKER for using external tools...
# Wed May 11 14:24:01 2022: Found environment variable $AUGUSTUS_CONFIG_PATH. Setting $AUGUSTUS_CONFIG_PATH to /home/programs/augustus-3.4.0/config//
# Wed May 11 14:24:01 2022: Found environment variable $AUGUSTUS_BIN_PATH. Setting $AUGUSTUS_BIN_PATH to /home/programs/augustus-3.4.0/bin/
# Wed May 11 14:24:01 2022: Did not find environment variable $AUGUSTUS_SCRIPTS_PATH (either variable does not exist, or the path given in variable does not exist). Will try to set this variable in a different way, later.
# Wed May 11 14:24:01 2022: Trying to guess $AUGUSTUS_SCRIPTS_PATH from $AUGUSTUS_CONFIG_PATH.
# Wed May 11 14:24:01 2022: Setting $AUGUSTUS_SCRIPTS_PATH to /home/programs/augustus-3.4.0/config///../scripts
# Wed May 11 14:24:01 2022: Did not find environment variable $PYTHON3_PATH
# Wed May 11 14:24:01 2022: Trying to guess $PYTHON3_PATH from location of python3 executable that is available in your $PATH
# Wed May 11 14:24:01 2022: Setting $PYTHON3_PATH to /usr/bin
# Wed May 11 14:24:01 2022: Found environment variable $PROTHINT_PATH. Setting $PROTHINT_PATH to /home/programs/ProtHint/bin
# Wed May 11 14:24:01 2022: Found environment variable $CDBTOOLS_PATH. Setting $CDBTOOLS_PATH to /home/programs/cdbfasta
# Wed May 11 14:24:01 2022: BRAKER will execute GeneMark-EP for training GeneMark and generating a training gene set for AUGUSTUS, using protein information as sole extrinsic evidence source.
#**********************************************************************************
#                               CREATING DIRECTORY STRUCTURE                       
#**********************************************************************************
# Wed May 11 14:24:01 2022: creating file that contains citations for this BRAKER run at /home/programs/BRAKER-2.1.6/example/tests/test2/what-to-cite.txt...
# Wed May 11 14:24:01 2022: create working directory /home/programs/BRAKER-2.1.6/example/tests/test2/GeneMark-EP.
mkdir /home/programs/BRAKER-2.1.6/example/tests/test2/GeneMark-EP
# Wed May 11 14:24:01 2022: create working directory /home/programs/BRAKER-2.1.6/example/tests/test2/GeneMark-ES.
mkdir /home/programs/BRAKER-2.1.6/example/tests/test2/GeneMark-ES
# Wed May 11 14:24:01 2022: create working directory /home/programs/BRAKER-2.1.6/example/tests/test2/species
mkdir /home/programs/BRAKER-2.1.6/example/tests/test2/species
# Wed May 11 14:24:01 2022: create working directory /home/programs/BRAKER-2.1.6/example/tests/test2/errors
mkdir /home/programs/BRAKER-2.1.6/example/tests/test2/errors
# Wed May 11 14:24:01 2022: changing into working directory /home/programs/BRAKER-2.1.6/example/tests/test2
cd /home/programs/BRAKER-2.1.6/example/tests/test2
# Wed May 11 14:24:01 2022: check_fasta_headers(): Checking fasta headers of file /home/programs/BRAKER-2.1.6/example/tests/../genome.fa
# Wed May 11 14:24:01 2022: check_fasta_headers(): Checking fasta headers of file /home/programs/BRAKER-2.1.6/example/tests/../proteins.fa
# Wed May 11 14:24:01 2022: Assuming that this is not a DNA fasta file because other characters than A, T, G, C, N, a, t, g, c, n were contained. If this is supposed to be a DNA fasta file, check the content of your file! If this is supposed to be a protein fasta file, please ignore this message!
# Wed May 11 14:24:01 2022: Assuming that this is not a protein fasta file because other characters than AaRrNnDdCcEeQqGgHhIiLlKkMmFfPpSsTtWwYyVvBbZzJjXx were contained. If this is supposed to be DNA fasta file, please ignore this message.
#**********************************************************************************
#                               PROCESSING HINTS                                   
#**********************************************************************************
# Wed May 11 14:24:01 2022: Running ProtHint to produce hints from protein sequence file (this may take a couple of hours)...
# Wed May 11 14:24:01 2022: Running Genemark-ES for ProtHint...
# Wed May 11 14:24:01 2022: Executing GeneMark-ES
# Wed May 11 14:24:01 2022: Calling prothint.py...
# Wed May 11 14:24:01 2022: starting prothint.py
/home/programs/ProtHint/bin/prothint.py --threads=48 --geneMarkGtf /home/programs/BRAKER-2.1.6/example/tests/test2/GeneMark-ES/genemark.gtf /home/programs/BRAKER-2.1.6/example/tests/test2/genome.fa /home/programs/BRAKER-2.1.6/example/tests/test2/proteins.fa
# Wed May 11 14:24:01 2022: Appending hints from /home/programs/BRAKER-2.1.6/example/tests/test2/prothint_augustus.gff to /home/programs/BRAKER-2.1.6/example/tests/test2/hintsfile.gff
```

The directory test2/GeneMark-ES is empty.  test2/errors only contains find_python3_re.err (empty) and find_python3_biopython.err (also empty).
Do you have any recommendations?

Best wishes,
Isabel

**Comment by mehiel96** [comment]
I'm not sure, but maybe the problem was in "Executing GeneMark-ES". Did you install gmes correctly?

**Comment by CIWa** [comment]
Hi, 
thanks for the suggestion! To be on the safe side, I reinstalled gmes, checked the installation via check_install.bash, and ran test2 again. But unfortunately the problem persists...

**Comment by tomasbruna** [comment]
Hi @CIWa, do you see a file called `GeneMark-ES.stdout`, and what are its contents?

**Comment by CIWa** [comment]
Hi Tomas,
no, I do not see such a file, in neither the GeneMark-ES nor the GeneMark-EP folder.

**Comment by CIWa** [comment]
Hi Tomas and Katharina,

sorry for asking again so soon, but have you found a solution for this? It would be great if I could skip the training in epmode. Or to the community: has anyone found a workaround for this?

Best wishes,
Isabel

**Comment by KatharinaHoff** [comment]
It should be possible. You already ran epmode, that means you have the
hintsfile and can use it with —hints. You can run without epmode, with
skipAllTraining, human parameters, and specify the ep extrinsic config as a
parameter. That will not produce GeneMark predictions. But you will get
Augustus predictions.

CIWa ***@***.***> schrieb am Mo. 23. Mai 2022 um 11:47:

**Comment by CIWa** [comment]
Hi Katharina,

Thanks for the super fast help! But I'm sorry, I am not sure I understood you correctly. epmode crashed before generating the hintsfile:

call of my modified test2:
`braker.pl --nocleanup --skipAllTraining --species=human --genome=../genome.fa --prot_seq=../proteins.fa --epmode --sof tmasking --workingdir=$wd --cores=48 --gm_max_intergenic 10000`

content /test2:
 ```
braker.log
 proteins.fa
 what-to-cite.txt
 genome.fa
 genome_header.map
 errors
 GeneMark-EP
 GeneMark-ES
 species
```
Or do you mean I should use the hintsfile from my RNASeq run?

**Comment by KatharinaHoff** [comment]
Ah, ok, the epmode run did not produce hints. Then, I currently do not have
solution for you. In had understood that you had a successful run with
highly fragmented genes.

**Comment by CIWa** [comment]
Ah, okay :) 
Could one solution be to
1. do a protein-data supported run in epmode with the parameter set specific to my species, which will likely give a not very good result, but then re-use the hintsfile produced by this run in a
2. run, where I use the human parameter set and skip all training?

**Comment by KatharinaHoff** [comment]
Yes, exactly, that's the idea.
