### ISSUE TITLE
The hints file is empty

### ISSUE THREAD

**Issue by bbista** [Gaius-Augustus/BRAKER#44]
Hello, I am using BRAKER for predicting genes using a RNAseq bam file and protein fasta file. I consistently get the following error.
# Tue May 21 04:24:52 2019: ERROR: in file /opt/rit/spack-app/linux-rhel7-x86_64/gcc-4.8.5/braker-2.1.2-75wblifp2zieps5rf7tzp7ajcwvzo2oz/bin/braker.pl at line 4189
The hints file is empty. Maybe the genome and the RNA-seq file do not belong together. I do not know what this error means. Could you help me undersand what is going wrong? 
The script I am using is 
braker.pl    --cores=1    --overwrite  --prg=exonerate --BAMTOOLS_PATH=/opt/rit/spack-app/linux-rhel7-x86_64/gcc-7.3.0/bamtools-2.5.1-7rljcjuix7pff6pcjqnu6c5ztdhk4coj/bin/ --SAMTOOLS_PATH=/opt/rit/spack-app/linux-rhel7-x86_64/gcc-4.8.5/samtools-1.9-k6deogajvbc2bpx3csxjuwtmqh5w65nr/bin/ --PYTHON3_PATH=/opt/rit/spack-app/linux-rhel7-x86_64/gcc-4.8.5/python-3.6.3-u4oaxsbnvbz6s7yxztqvvirlipfjrnx7/bin/ --ALIGNMENT_TOOL_PATH=/opt/rit/spack-app/linux-rhel7-x86_64/gcc-4.8.5/exonerate-2.4.0-ddwi7zhv5cb4rzwsyhpe32jmqn22pmcm/bin/ --prot_seq=protein.faa      --genome=genome.fasta    --bam=ASP_rnaseq_sorted.bam    --gff3

**Comment by SvitlanaLukicheva** [comment]
Hello, I think your problem corresponds to the "Common problem 1" described here: https://github.com/Gaius-Augustus/BRAKER#common-problems

**Comment by bbista** [comment]
Hello, 
I double checked the genome fasta file and the bam files. The headers of the genome FASTA file are short without any white spaces.
The filterIntronsFindStrand.stderr file are filled with the following error for each sequence of the genome file. 
WARNING: 'Scbe7cn_1026_HRSCAF_1040' does not match any sequence in the fasta file. Maybe the two files do not belong together.
Obviously when I grep Scbe7cn_1026_HRSCAF_1040 in the fasta file, I can find it.

Best, 
B

**Comment by SvitlanaLukicheva** [comment]
Are you sure there is no additional character after 'Scbe7cn_1026_HRSCAF_1040' in your fasta file?

**Comment by bbista** [comment]
Yes, I am sure. That is the format of the fasta headers with no additional text.

**Comment by SvitlanaLukicheva** [comment]
Then I have no idea, sorry. I had the same problem and it was because of white spaces in fasta headers.

**Comment by longzhangnation** [comment]
whichi software you use to align? Using STAR is much better

**Comment by KatharinaHoff** [comment]
As @SvitlanaLukicheva already said: this error is issued if the FASTA headers are different from the sequence names in BAM files. 

If you cannot see anything "obvious", there might be invisible characters, such as a windows line break vs. no windows linebreak in the bam file.

We usually don't see this problem with aligners such as GSNAP, STAR, Hisat2 etc. if all files are created and processed on a Unix system.

**Comment by jdavidpeery** [comment]
I was having the same issue when I was using bowtie2 for alignment, but once I switched to STAR for alignment as suggested here, BRAKER2 ran just fine without this error once I removed a semicolon from my scaffold names.

**Comment by KatharinaHoff** [comment]
Braker is not STAR specific. You have to use a mapper that produces spliced
alignments though. (Bowtie is not made for this.)
