### ISSUE TITLE
braker predicted gene models are very high and augustus training accuracy is very low

### ISSUE THREAD

**Issue by joleneyue** [Gaius-Augustus/BRAKER#440]
Dear guys,

i have a question to ask 

we have done two annotations of a plant genome with about 10000 contigs and genome size of 600 Mbp, and GC content of around 42%. We have done the annotation once with hisat and stringtie and got 22 000 gene models which resulted in a busco score of 90% with the virdidiplantae odb.

 i have used the very same bam files to run braker (2.1.6) using only RNA-seq data using the following command line 

braker.pl --species=myspecies --genome=./fasta_files/genome.fas  --bam=./bam_files/Cday1_1.sam.bam,./bam_files/Cday1_2.sam.bam --softmasking --gff3 --cores 15 

 and got 113 000 genes predicted with a busco score of 44%， What could have caused this huge difference?

i checked the augustus training step, the accuracy is like 0.4, why this is so low?

is it a version problem? what did you do with the new version? 

what version to use i can solve this problem ?

Please let me know ,

Thanks a lot,
Cheers,
Jolene

**Comment by KatharinaHoff** [comment]
I am closing this issue. It's not a technical issue and will be very difficult to further advise on without being closely familiar with the data.
