### ISSUE TITLE
Error in protein alignment.

### ISSUE THREAD

**Issue by biozhangzhou** [Gaius-Augustus/BRAKER#442]
Hello,Katharina:
         I have successfully run the test1.sh test2.sh test3.sh which means my installation was OK. Then I'm using 60k evolutionary closely proteins and RNA.bam in etpmode just like test3.sh have set. Error below happend. It looks like there no protein can mapping to my genome. But it couldn't be. Could you please give some tips about it ?
<img width="1632" alt="Screen Shot 2021-11-09 at 9 03 31 PM" src="https://user-images.githubusercontent.com/42492970/140929102-0e72a8c3-e48f-44e3-b868-d5c662310b68.png">

**Comment by tomasbruna** [comment]
Hi @biozhangzhou,

can you share the full BRAKER log?

Also, please try to run ProtHint separately (https://github.com/gatech-genemark/ProtHint) and share the contents of the working directory (after it fails). I'll try to see what's going on from that.

Best,
Tomas
