### ISSUE TITLE
error, no valid sequences were found

### ISSUE THREAD

**Issue by philge** [Gaius-Augustus/BRAKER#445]
I get below output in file "GeneMark-ET.stdout" when I run following BRAKER command
"braker.pl \
	--gff3 \
	--overwrite \
	--species=Bat \
	--cores=48 \
	--genome=scaffolds_FINAL.fasta \
	--bam=./direct_inference_out/merged.bam,/data_all/annotation/scaffolds/iso-seq/hq_isoforms.fasta.sorted.bam"
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/7559186/braker.log)

 check before the run
 hard_mask is in the 'auto' mode. hard_mask was set to: 100
 creat directories
 commit input data
 warning, PLUS file is empty
 prepare input data report
 commit training data
 prepare training data report
 prepare initial model
 find GC of sequence
GC 42
 build initial ET model
running step ET_A
running gm.hmm on local multi-core system
612 contigs in list
concatenate predictions: /data_all/annotation/scaffolds/run/ET_A_1
training level ET_A: /data_all/annotation/scaffolds/run/ET_A_1
From 268998 loaded 268998 and ignored dublications 0
exon	no_match	match_one	match_two
Initial	84581	2658	0
Internal	102370	15795	8641
Terminal	84293	3239	0
Single	60763	0	0
CDS_no_match	all	short	long	seq_short	seq_long
CDS_no_match	332007	307715	24292	94555268	30613660
Intergenic	all	between_match	seq_match
Intergenic:	148415	284	3122359
running step ET_B
running gm.hmm on local multi-core system
612 contigs in list
concatenate predictions: /data_all/annotation/scaffolds/run/ET_B_1
training level ET_B: /data_all/annotation/scaffolds/run/ET_B_1
From 268998 loaded 268998 and ignored dublications 0
exon	no_match	match_one	match_two
Initial	120483	1432	0
Internal	97016	4099	1886
Terminal	120553	1381	0
Single	25571	0	0
CDS_no_match	all	short	long	seq_short	seq_long
CDS_no_match	363623	344886	18737	81024009	23313963
Intergenic	all	between_match	seq_match
Intergenic:	147886	139	1743090
running step ET_C
running gm.hmm on local multi-core system
612 contigs in list
concatenate predictions: /data_all/annotation/scaffolds/run/ET_C_1
training level ET_C: /data_all/annotation/scaffolds/run/ET_C_1
From 268998 loaded 268998 and ignored dublications 0
exon	no_match	match_one	match_two
Initial	120965	137	0
Internal	162949	90	11
Terminal	121005	95	0
Single	23188	0	0
CDS_no_match	all	short	long	seq_short	seq_long
CDS_no_match	428107	412892	15215	72412778	19393321
Intergenic	all	between_match	seq_match
Intergenic:	144652	2	73440
SvsM  0.0266985381998713 vs 0.973301461800129
genes in IvsT all and selected: 151881 37755
1, -2.02789930463521
2, -1.68692352498358
3, -1.69959650565218
4, -1.85531846760606
5, -2.13484870292693
6, -2.50944035565628
7, -2.91474261057624
8, -3.38347689434079
9, -3.80547130440017
10, -4.23259790928951
11, -4.84177970973212
12, -5.31312652252432
13, -5.85674196911331
14, -6.44452863401543
15, -6.66767218532963
16, -7.54314092268354
17, -7.44783074287921
 estimate 1: 0.751180200288384
 estimate 2: 0.667190498387368
 value: 0.667190498387368
IvsT  0.667190498387368 vs 0.332809501612632
running gm.hmm on local multi-core system
612 contigs in list
concatenate predictions: /data_all/annotation/scaffolds/run/ET_C_2
training level ET_C: /data_all/annotation/scaffolds/run/ET_C_2
From 268998 loaded 268998 and ignored dublications 0
exon	no_match	match_one	match_two
Initial	124598	41	0
Internal	229974	16	0
Terminal	124645	33	0
Single	5879	0	0
CDS_no_match	all	short	long	seq_short	seq_long
CDS_no_match	485096	472801	12295	69696075	16613274
Intergenic	all	between_match	seq_match
Intergenic:	130838	0	0
SvsM  0.00538718001845957 vs 0.99461281998154
genes in IvsT all and selected: 191056 35972
1, -2.50297165718564
2, -2.03177987537714
3, -2.00955207829329
4, -1.99739074114726
5, -2.12622105204288
6, -2.28309430365805
7, -2.49518951674358
8, -2.79929603951154
9, -3.08560856141828
10, -3.42232413664636
11, -3.74056494324584
12, -4.12059515420618
13, -4.44076268180245
14, -4.84858906609629
15, -5.24874912197476
16, -5.85576714880477
17, -6.12104828456738
18, -6.39615157481231
19, -6.9069771985783
20, -7.27162031216621
21, -7.27162031216621
22, -7.7824459359322
 estimate 1: 0.811447952432795
 estimate 2: 0.740988450977976
 value: 0.740988450977976
IvsT  0.740988450977976 vs 0.259011549022024
warning, no data in specified range /data_all/data_disk2/software/gmes_linux_64/histogram.pl
running gm.hmm on local multi-core system
612 contigs in list
concatenate predictions: /data_all/annotation/scaffolds/run/ET_C_3
training level ET_C: /data_all/annotation/scaffolds/run/ET_C_3
From 268998 loaded 268998 and ignored dublications 0
exon	no_match	match_one	match_two
Initial	175470	69	0
Internal	277683	44	0
Terminal	175345	53	0
Single	1818	0	0
CDS_no_match	all	short	long	seq_short	seq_long
CDS_no_match	630316	619103	11213	54120408	15486820
Intergenic	all	between_match	seq_match
Intergenic:	177462	0	0
SvsM  0.00371788346205767 vs 0.996282116537942
genes in IvsT all and selected: 172711 27992
1, -3.28312859089595
2, -2.37794695622354
3, -2.11641271492578
4, -2.03719158747099
5, -2.08776416110662
6, -2.22798730491968
7, -2.34089167707721
8, -2.58097447577922
9, -2.84149994107706
10, -3.08427773215079
11, -3.44061817198873
12, -3.72052674610713
13, -4.08057864555559
14, -4.40486329698492
15, -4.83699665217524
16, -5.07488806012401
17, -5.75103766431538
18, -6.08079095068785
19, -6.12880016987421
20, -6.50200441576416
21, -7.29523505488108
22, -7.10417981811837
23, -7.93708894105348
24, -7.46708531180774
 estimate 1: 0.837682602729415
 estimate 2: 0.766582088178409
 value: 0.766582088178409
IvsT  0.766582088178409 vs 0.233417911821591
warning, no data in specified range /data_all/data_disk2/software/gmes_linux_64/histogram.pl
error, no valid sequences were found
error on call: /data_all/data_disk2/software/gmes_linux_64/make_nt_freq_mat.pl --cfg /data_all/annotation/scaffolds/run.cfg --section donor_GT    --format DONOR_1    --phase 1  --quiet

Would you please help me to fix it?

Thanks
Philge

**Comment by xiekunwhy** [comment]
give up braker, the team never solve this problem.

**Comment by xiekunwhy** [comment]
You may try to prepare hints file yourself.
/path/to/Augustus/bin/bam2hints --in=align.bam --out=bam2hints.gff
/path/to/BRAKER/scripts/filterIntronsFindStrand.pl ref.fa bam2hints.gff --score > fixed_hintsfile.gff 2> error.gff

Best,
Kun

**Comment by KatharinaHoff** [comment]
Never learned whether that advice helped... I am closing here.

**Comment by bioinformaticspcj** [comment]
Hi,
I just ran into the same problem, has the bug been fixed? I tried the way Kun mentioned above, but it did not work.
Could anyone give me some advice?
Best,
Bob
