### ISSUE TITLE
How to use braker when the repeat proportion genome of the genome is very high?

### ISSUE THREAD

**Issue by xiekunwhy** [Gaius-Augustus/BRAKER#447]
Hi,

I am trying to use braker2 to do genes prediction on my genome(repeat soft masked), but the repeat proportion of this genome is extremely high(~90%), and braker2 has a poor performence, the gene number produced by braker2 pipeline is ~4 times larger than expected and the BUSCO completeness of braker2 predicted genes(~70%) is much lower than the genome BUSCO completeness(~91%). But braker2 worked well for an other species which with low repeat proportion(~40%).
So I have two questions,
1) Is braker2 still suitable when the proportion of repeat sequences is extremely high?
2) And are there any suggenstions when the repeat proportion is extremely high.

Best,
Kun

**Comment by KatharinaHoff** [comment]
You can try hard masking the genome.

**Comment by xiekunwhy** [comment]
Very poor performance after hard masking.

By the way, I found that there are a lot of in-frame stop codons if I run genemarkES/ET/EP my self, do you have any suggestions to handle it. 
For example, I ran genemarkES like following,
gmes_petap.pl --mask_penalty 0.1 --seq ../Op-f.pctg.mask.fa -cores=8 --ES
and then
gffread genemark.gtf -g ../Op-f.pctg.mask.fa -y genemark.pep.fa
Tere are many many stop codon in genemark.pep.fa
![image](https://user-images.githubusercontent.com/17738229/145990709-d4a7f4fa-6e21-4537-a963-9d56dd9d2a23.png)

Best,
Kun

**Comment by tomasbruna** [comment]
I'm closing this issue since the thread continues in https://github.com/gatech-genemark/GeneMark-EP-plus/issues/4
