### ISSUE TITLE
error on call: /home/**/soft/miniconda3/envs/braker2/bin/probuild and gmes_petap.pl

### ISSUE THREAD

**Issue by Zoey1001** [Gaius-Augustus/BRAKER#448]
Dear developer, I find that some error about gmes_petap.pl and  error on call: /home/**/soft/miniconda3/envs/braker2/bin/probuild
braker.log ,could you please give me some advices?
#**********************************************************************************
#                               BRAKER CONFIGURATION                               
#**********************************************************************************
# BRAKER CALL: /home/**/soft/BRAKER_v2.1.6/scripts/braker.pl --PROTHINT_PATH=/home/**/soft/ProtHint-2.6.0/bin/ --ALIGNMENT_TOOL_PATH=/home/**/soft/miniconda3/envs/braker2/bin --species=Pd_a --genome=Pd_a.fa.masked --bam=/home/**/project/zuoqing/**/trans/clean/N3.map.rna.bam --prot_seq=/home/**/project/Araneus_marmoreus/JC/BRAKER2/proteins.fasta --etpmode --cores 40 --softmasking
# Tue Dec 21 18:17:47 2021: braker.pl version 2.1.6
# Tue Dec 21 18:17:47 2021: Configuring of BRAKER for using external tools...
# Tue Dec 21 18:17:47 2021: Found environment variable $AUGUSTUS_CONFIG_PATH. Setting $AUGUSTUS_CONFIG_PATH to /home/**/soft/miniconda3/envs/braker2/config/
# Tue Dec 21 18:17:47 2021: Found environment variable $AUGUSTUS_BIN_PATH. Setting $AUGUSTUS_BIN_PATH to /home/**/soft/miniconda3/envs/braker2/bin/
# Tue Dec 21 18:17:47 2021: Found environment variable $AUGUSTUS_SCRIPTS_PATH. Setting $AUGUSTUS_SCRIPTS_PATH to /home/**/soft/miniconda3/envs/braker2/bin/
# Tue Dec 21 18:17:47 2021: Trying to guess $PYTHON3_PATH from location of python3 executable that is available in your $PATH
# Tue Dec 21 18:17:47 2021: Setting $PYTHON3_PATH to /home/**/soft/miniconda3/envs/braker2/bin
# Tue Dec 21 18:17:47 2021: Trying to guess $GENEMARK_PATH from location of gmes_petap.pl executable that is available in your $PATH
# Tue Dec 21 18:17:47 2021: Setting $GENEMARK_PATH to /home/**/soft/miniconda3/envs/braker2/bin
# Tue Dec 21 18:17:47 2021: Trying to guess $BAMTOOLS_BIN_PATH from location of bamtools executable that is available in your $PATH
# Tue Dec 21 18:17:47 2021: Setting $BAMTOOLS_BIN_PATH to /home/**/soft/miniconda3/envs/braker2/bin
# Tue Dec 21 18:17:47 2021: Trying to guess $SAMTOOLS_PATH from location of samtools executable in your $PATH
# Tue Dec 21 18:17:47 2021: Setting $SAMTOOLS_PATH to /home/**/soft/miniconda3/envs/braker2/bin
# Tue Dec 21 18:17:47 2021: Trying to guess $DIAMOND_PATH from location of diamond executable that is available in your $PATH
# Tue Dec 21 18:17:47 2021: Setting $DIAMOND_PATH to /home/**/soft/miniconda3/envs/braker2/bin
# Tue Dec 21 18:17:47 2021: Setting $PROTHINT_PATH to command line argument --PROTHINT_PATH value /home/**/soft/ProtHint-2.6.0/bin/.
# Tue Dec 21 18:17:47 2021: Trying to guess $CDBTOOLS_PATH from location of cdbfasta executable that is available in your $PATH
# Tue Dec 21 18:17:47 2021: Setting $CDBTOOLS_PATH to /home/**/soft/miniconda3/envs/braker2/bin
#**********************************************************************************
#                               CREATING DIRECTORY STRUCTURE                       
#**********************************************************************************
# Tue Dec 21 18:17:48 2021: create working directory /home/**/project/zuoqing/**/braker/braker.
mkdir /home/**/project/zuoqing/**/braker/braker
# Tue Dec 21 18:17:48 2021: creating file that contains citations for this BRAKER run at /home/**/project/zuoqing/**/braker/braker/what-to-cite.txt...
# Tue Dec 21 18:17:48 2021: create working directory /home/**/project/zuoqing/**/braker/braker/GeneMark-ETP.
mkdir /home/**/project/zuoqing/**/braker/braker/GeneMark-ETP
# Tue Dec 21 18:17:48 2021: create working directory /home/**/project/zuoqing/**/braker/braker/GeneMark-ES.
mkdir /home/**/project/zuoqing/**/braker/braker/GeneMark-ES
# Tue Dec 21 18:17:48 2021: create working directory /home/**/project/zuoqing/**/braker/braker/species
mkdir /home/**/project/zuoqing/**/braker/braker/species
# Tue Dec 21 18:17:48 2021: create working directory /home/**/project/zuoqing/**/braker/braker/errors
mkdir /home/**/project/zuoqing/**/braker/braker/errors
# Tue Dec 21 18:17:48 2021: changing into working directory /home/**/project/zuoqing/**/braker/braker
cd /home/**/project/zuoqing/**/braker/braker
# Tue Dec 21 18:17:48 2021: Creating parameter template files for AUGUSTUS with new_species.pl
# Tue Dec 21 18:17:48 2021: new_species.pl will create parameter files for species Pd_a in /home/**/soft/miniconda3/envs/braker2/config//species/Pd_a
perl /home/**/soft/miniconda3/envs/braker2/bin/new_species.pl --species=Pd_a --AUGUSTUS_CONFIG_PATH=/home/**/soft/miniconda3/envs/braker2/config/ 1> /dev/null 2>/home/**/project/zuoqing/**/braker/braker/errors/new_species.stderr
# Tue Dec 21 18:17:48 2021: check_fasta_headers(): Checking fasta headers of file /home/**/project/zuoqing/**/braker/Pd_a.fa.masked
# Tue Dec 21 18:19:01 2021: check_fasta_headers(): Checking fasta headers of file /home/**/project/Araneus_marmoreus/JC/BRAKER2/proteins.fasta
# Tue Dec 21 18:19:01 2021: Assuming that this is not a DNA fasta file because other characters than A, T, G, C, N, a, t, g, c, n were contained. If this is supposed to be a DNA fasta file, check the content of your file! If this is supposed to be a protein fasta file, please ignore this message!
# Tue Dec 21 18:19:01 2021: Assuming that this is not a protein fasta file because other characters than AaRrNnDdCcEeQqGgHhIiLlKkMmFfPpSsTtWwYyVvBbZzJjXx were contained. If this is supposed to be DNA fasta file, please ignore this message.
#**********************************************************************************
#                               PROCESSING HINTS                                   
#**********************************************************************************
# Tue Dec 21 18:19:29 2021: Running ProtHint to produce hints from protein sequence file (this may take a couple of hours)...
# Tue Dec 21 18:19:31 2021: Running Genemark-ES for ProtHint...
# Tue Dec 21 18:19:31 2021: Executing GeneMark-ES
# Tue Dec 21 18:19:31 2021: changing into GeneMark-ES directory /home/**/project/zuoqing/**/braker/braker/GeneMark-ES
cd /home/**/project/zuoqing/**/braker/braker/GeneMark-ES
# Tue Dec 21 18:19:31 2021: Executing gmes_petap.pl
perl /home/**/soft/miniconda3/envs/braker2/bin/gmes_petap.pl --verbose --cores=40 --ES --gc_donor 0.001 --sequence=/home/**/project/zuoqing/**/braker/braker/genome.fa  --soft_mask auto 1>/home/**/project/zuoqing/**/braker/braker/GeneMark-ES.stdout 2>/home/**/project/zuoqing/**/braker/braker/errors/GeneMark-ES.stderr
________________________________________________________________________________________________________________________
gmes.log

/home/**/soft/miniconda3/envs/braker2/bin/gmes_petap.pl : [Tue Dec 21 18:19:31 2021] /home/**/soft/miniconda3/envs/braker2/bin/probuild --reformat_fasta --uppercase --allow_x --letters_per_line 60 --out data/dna.fna --label _dna --trace info/dna.trace --in /home/**/project/zuoqing/**/braker/braker/genome.fa  --mask_soft 100 
/home/**/soft/miniconda3/envs/braker2/bin/gmes_petap.pl : [Tue Dec 21 18:19:31 2021] error
______________________________________________________________________________________________________________________________
GeneMark-ES.stdout

check before run
create directories
commit input data
soft_mask is in the 'auto' mode. soft_mask was set to: 100
error on call: /home/**/soft/miniconda3/envs/braker2/bin/probuild --reformat_fasta --uppercase --allow_x --letters_per_line 60 --out data/dna.fna --label _dna --trace info/dna.trace --in /home/spider/project/zuoqing/**/braker/braker/genome.fa  --mask_soft 100

**Comment by tomasbruna** [comment]
Hi @Zoey1001,

I have not seen this kind of error before -- there might be something unexpected in your input genome file that causes probuild to fail. Would you mind sharing the input file, or just a piece of it that causes the error? I'd try to reproduce the error on my side. 

Please send me an email to bruna.tomas@gatech.edu if you don't want to share this file publicly.

Best,
Tomas

**Comment by KatharinaHoff** [comment]
I am closing this issue, assuming it was taken to email.
