### ISSUE TITLE
ProtHint.py's iterative mode failed after finishing ProtHint's alignment

### ISSUE THREAD

**Issue by hhchau2** [Gaius-Augustus/BRAKER#449]
Greeting developers, I've encountered an issue where ProtHint's iterative mode failed after finishing ProtHint's alignment.

The code that I used to run **braker.pl with --epmode** was:

`braker.pl --genome=/home/letbell/Mushroom_Project/Assemble_Contigs/C_Gambosa/scaffolds.fasta --prot_seq=/home/letbell/Mushroom_Project/Protein_DB/Fungi_Protein.fasta --epmode --fungus --species=CGambosa --useexisting --workingdir=C_GambosaT4 --cores 8`

The log output after ProtHint's iterative mode failed:
![image](https://user-images.githubusercontent.com/96798463/147806336-c0488c5a-065f-44a2-9f6e-e1a1df6db690.png)

I checked the spaln.gff files, and it was empty. There was already a similar issue [https://github.com/Gaius-Augustus/BRAKER/issues/443](url) solved, **but I wasn't be able to identify any issues with gtf2gff.pl scripts since I've not modify it.**

The **scaffold.fasta** was assembled via SpAdes for downstream analysis. I've also test with different public SRA experiments that uses pacbio/nanopore, the assembled dataset from **Canu** or **Flye** ran by Braker does not poses any issues with ProtHint's iterative mode.

The log below is from braker.log of a different assembled data set via Flye, and it finished without any error or as it should've been when Braker finished.
![image](https://user-images.githubusercontent.com/96798463/147806316-3c737ff9-cc4f-4ccc-8120-afc56107c0b5.png)

In addition, there was a few error whilte ProtHint aligning genome dataset with the protein dataset as shown here:
![image](https://user-images.githubusercontent.com/96798463/147806422-d14a1082-69bd-47d6-a9e5-21faa0c066f3.png)
I wasn't sure if it's related to cause ProtHint's iterative mode failed pre-maturely, and I have not seen this error in any of the assembly with pacbio or nanopore genome dataset.

Can you please give me some advices? I'm looking forward to your reply! Thank you.

**Comment by hhchau2** [comment]
Update 1:
I found out that there was an issue with **Braker2 installed in conda environment that does not detect Augustus's script and bin config path** even though I did specify in .bashrc. So I installed Augustus via mamba into conda environment instead and it fixed the issue.

**Comment by tomasbruna** [comment]
Hi @hhchau2,

thanks for letting us know about the fix!

> In addition, there was a few error whilte ProtHint aligning genome dataset with the protein dataset as shown here:

If there are still some occasional "segmentation fault" errors, they can be safely ignored (they usually only affect an insignificant fraction of alignments) as long as ProtHint finishes.

Best,
Tomas
