### ISSUE TITLE
The output of braker.gff3 is missing "gene" feature

### ISSUE THREAD

**Issue by inspirewind** [Gaius-Augustus/BRAKER#453]
Hello dear developers,

I want to use `braker.gff3` for downstream analysis, but the `gene` feature is missing when I use the `-gff3` parameter to output the gff file, and everything works fine in the `augustus.hints_iter1.gff` file. I also tried to use `gtf2gff.pl` script from augustus, produced the same error.
In addition, when using `epmode` for prediction, are all prediction results generated by Augustus, is there no difference between `brake.gff3` and `augustus.hints_iter1.gff`?

[gff_output.tar.gz](https://github.com/Gaius-Augustus/BRAKER/files/7893641/gff_output.tar.gz)
Best wishes,
Rui Li

**Comment by LarsGab** [comment]
Hi,

I think you have a similar issue as #457, please take a look at the answer there.
Additional comments:
In your case, there should be a `augustus.hints.gff` gene set in the output, which is the final prediction of BRAKER.
If you want to use the `braker.gff` gene set, you can use `rename_gtf.py` from [TSEBRA](https://github.com/Gaius-Augustus/TSEBRA) to add the 'gene' feature, e.g:
```
rename_gtf.py --gtf braker.gtf --out braker_renamed.gtf
```
However, this will rename the IDs of all transcripts and genes in `braker.gtf`.

Best, 
Lars

**Comment by smallfishcui** [comment]
> 

Hi Lars,

This script skip some transcripts, such as:
HiC_scaffold_19	AUGUSTUS	start_codon	5934653	5934655	.	+	0	transcript_id "file_1_file_1_jg143570.t1"; gene_id "file_1_file_1_jg143570";
do you know what could be the reason?

thanks,
Cui

**Comment by LarsGab** [comment]
Hi Cui,

I wasn't able to reproduce your problem. The script shouldn't remove any transcript from your gene set. 
Can you send me either all lines of the transcript that was skipped or send me an example file, so that I can try to reproduce the issue?

Best,
Lars

**Comment by smallfishcui** [comment]
Hi Lars,

I sent you the file from email. The braker.gtf file was obtained by running braker2 with both RNAseq and prothint evidences. Please let me know how it goes

thanks,
Cui

**Comment by LarsGab** [comment]
Hi,

I looked at your file and I see what the problem is. 
In the current BRAKER version, there is a problem with the format of the `braker.gtf` file. This can lead to some issues with the  `rename_gtf.py` script. In your case, it prints the warning that some transcripts are skipped, even though they aren't actually skipped. 
You can fix the `braker.gtf` format for the TSEBRA scripts with [`fix_gtf_ids.py`](https://github.com/Gaius-Augustus/TSEBRA/blob/main/bin/fix_gtf_ids.py) from TSEBRA, e.g. with:
```
fix_gtf_ids.py --gtf braker.gtf --out braker_fixed.gtf
```
Best, 
Lars

**Comment by smallfishcui** [comment]
Thanks Lars. That worked!
Cui
