### ISSUE TITLE
No such file or directory at gmes_linux_64/gmes_petap.pl line 1881

### ISSUE THREAD

**Issue by zmz1988** [Gaius-Augustus/BRAKER#455]
Hi BRAKER developers, thank you so much for writing this tool! I'm running BRAKER but encounter with some similar errors. For example, an error message like this:

```
(BRAKER) [user@node15 errors]$ cat GeneMark-ES.stderr
Can't exec "/home/user/gmes_linux_64/gc_distr.pl": No such file or directory at /home/user/gmes_linux_64/gmes_petap.pl line 1881.
```

But I do have such file at such place, and they are all executable
```
(BRAKER) [user@node15 errors]$ which gc_distr.pl
~/gmes_linux_64/gc_distr.pl
(BRAKER) [user@node15 errors]$ ls /home/user/gmes_linux_64/
bed_to_gff.pl                      gmes_petap.pl          prior.bp
bp_seq_select.pl                   gmhmme3                probuild
build_mod.pl                       gm_key                 ProtHint
calc_introns_from_gtf.pl           hc_exons2hints.pl      README.GeneMark-ES-suite
change_path_in_perl_scripts.pl     heu_dir                reformat_gff.pl
check_install.bash                 histogram.pl           rescale_gff.pl
compare_intervals_exact.pl         INSTALL                rnaseq_introns_to_gff.pl
countFullySupportedTranscripts.py  lib                    run_es.pl
filter_gff.sh                      LICENSE                run_hmm_pbs.pl
flag_anchored_elements.py          make_nt_freq_mat.pl    scan_for_bp.pl
gc_distr.pl                        other                  selectSupportedSubsets.py
GeneMark-E-tests                   parse_by_introns.pl    star_to_gff.pl
generateReport.py                  parse_ET.pl            statistics
get_below_gc.pl                    parse_gibbs.pl         verify_evidence_gmhmm.pl
get_sequence_from_GTF.pl           parse_set.pl           wbp.cfg
Gibbs3                             predict_genes.pl
gmes.cfg                           predictionAnalysis.py

(BRAKER) [user@node15 errors]$ sh /home/user/gmes_linux_64/check_install.bash 
Checking GeneMark-ES installation
Checking Perl setup
All required Perl modules were found
Checking GeneMark.hmm setup
GeneMark.hmm was found
GeneMark.hmm is set
GeneMark.hmm is executable
Performing GeneMark.hmm test run
All required components for GeneMark-ES were found

```

I have another similar error complaining that no gc_distr.pl at gmes_petap.pl line 1881, when running with the protein hints. I don't quite understand where is wrong. Could you please give me a hint?

Thank you in advance!

**Comment by tomasbruna** [comment]
Hi,

you can try the following fix. Go to the GeneMark folder and run

    perl change_path_in_perl_scripts.pl "/usr/bin/env perl"

More details are in the README file: https://github.com/Gaius-Augustus/BRAKER#genemark-ex

Best,
Tomas

**Comment by tomasbruna** [comment]
I still have no idea what might be causing this issue. The output of the `gc_distr.pl` is not currently used by GeneMark in any way, so you can try deleting the entire line 1881 from `gmes_petap.pl`. Let me know what happens when you run BRAKER with this line deleted.

**Comment by zmz1988** [comment]
The 1881 in gmes_petap.pl is `my $res = system( $com );`, and after I deleted it 

`less /user/annotation/braker2/errors/GeneMark-ES.stderr`
```
Global symbol "$res" requires explicit package name (did you forget to declare "my $res"?) at /home/user/gmes_linux_64/gmes_petap.pl line 1883.
BEGIN not safe after errors--compilation aborted at /home/user/gmes_linux_64/gmes_petap.pl line 2084.
```

deleting the line doesn't seem right...

**Comment by zmz1988** [comment]
hello, I dig in a bit, and find the following. Not sure whether it's related, but seems like the path need to be in the command... But the path of the whole gmes_linux_64 folder is in the .bashrc path... With my shallow knowledge of computer, I don't really understand why. But do you think it has the same problem when execute gc_distr.pl in gmes_petap.pl?

'''
(BRAKER) [user@node15 annotation]$ which gmes_petap.pl
~/gmes_linux_64/gmes_petap.pl
(BRAKER) [user@node15 annotation]$ gmes_petap.pl -help
-bash: /home/user/gmes_linux_64/gmes_petap.pl: /home/user/miniconda3/envs/BRAKER/bin/: bad interpreter: Permission denied
**(BRAKER) [user@node15 annotation]$ perl gmes_petap.pl
Can't open perl script "gmes_petap.pl": No such file or directory**
(BRAKER) [user@node15 annotation]$ perl /home/user/gmes_linux_64/gmes_petap.pl
# -------------------
Usage:  /home/user/gmes_linux_64/gmes_petap.pl  [options]  --sequence [filename]

GeneMark-ES Suite version 4.68_lic
Suite includes GeneMark.hmm, GeneMark-ES, GeneMark-ET and GeneMark-EP algorithms. 
(omit other lines here)

(BRAKER) [user@node15 annotation]$ perl /home/user/gmes_linux_64/gc_distr.pl
 
Usage: /home/user/gmes_linux_64/gc_distr.pl  --in [filename]  --out [filename]  --w [size]

This program calculates GC histogram of sliding non-overlaping windows
Input: DNA sequence file in FASTA like format and the window size/s
Bin size is 1% ; bin is centered on whole number; 101 bins
Bin 0 is set as range 0.0-0.5 and bin 100 as range 99.5-100.0
Ignores windows with less than 50% allowed letters
Output is CSV formatted (the Comma Separated Value File Format)

  --w   [window size]  number/s separated by comma
        if no value, get GC of each FASTA record in file
  --org [species name]

version 2.1;

'''

**Comment by zmz1988** [comment]
Hi I find the reason. I need to add --GENEMARK_PATH in the command line, even though I had put the path in my .bashrc file. I have no idea why, but it works now.
