### ISSUE TITLE
The gene result is little

### ISSUE THREAD

**Issue by phil622** [Gaius-Augustus/BRAKER#464]
I use braker to process an insect with 6 samples rseq data, but the final result is only have 6000+ gene. Is that correct? I think it is kind of little. The specie's genome is almost 600M.

**Comment by phil622** [comment]
this is my command:
braker.pl --cores 40 --species=Callo --genome=Callo_polished.fasta.masked --softmasking --bam=Callo1.sorted.bam,Callo2.sorted.bam,Callo3.sorted.bam,Callo4.sorted.bam,Callo5.sorted.bam,Callo6.sorted.bam --gff3

**Comment by phil622** [comment]
the result of augustus.hints.gtf have only 1000+ genes, and the result of braker.gtf also have no more than 7000 genes.

**Comment by tomasbruna** [comment]
Hi @phil622 ,

did you try running [BRAKER2 with proteins](https://github.com/Gaius-Augustus/BRAKER#braker-with-proteins-of-any-evolutionary-distance)? The process of preparing a plant protein database is described here: https://github.com/gatech-genemark/ProtHint#protein-database-preparation. I hope the results will look better with the protein input.

You can then combine the protein-based result with RNA-Seq-based prediction with [TSEBRA](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04482-0).

Tomas
