### ISSUE TITLE
Conda Installation problems

### ISSUE THREAD

**Issue by ClarenceHsiang** [Gaius-Augustus/BRAKER#465]
Dear BRAKER developers:

Good evening.
I am using conda to install braker2 software in linux system, but the following installation failure message keeps appearing, I would like to ask how to solve it? Thank you very much

-----------------------------------------------------------------------------------
(Python3_9) [hsiang@pomology-serverIII 20211020_Test]$ conda install -c bioconda braker2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.                                  failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - python=3.9 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17
------------------------------------------

**Comment by tomasbruna** [comment]
Hi @ClarenceHsiang,

unfortunately, we don't maintain the Conda distribution in this repository. Since the Conda distribution is not working for you, I'd suggest installing BRAKER "manually", according to the instructions in the [README](https://github.com/Gaius-Augustus/BRAKER#installation) file.

Best,
Tomas
