### ISSUE TITLE
Train from gth hints fails

### ISSUE THREAD

**Issue by pezhmansafdari** [Gaius-Augustus/BRAKER#467]
Hi,

I am trying to run braker with previously created gth hints files by braker and I get the following error message:
ERROR: in file /opt/BRAKER/scripts/braker.pl at line 4809
a protein alignment tool (gth) has been given, but neither a protein sequence file, nor a protein alignment file generated by such a tool have been specified.
This is the command that I am running:

/opt/BRAKER/scripts/braker.pl --species=Plantago --genome=genome.fasta --bam=RNAAligned.out.sort.bam --hints=hintsfile.gff --prg=gth --trainFromGth --cores 40 --gff3 

and these are a few lines from the hints file:
Scv4fVU_1000_HRSCAF_1962        gth2h   start   18153   18155   .       +       0       src=P;grp=asmbl_2248.p1_Scv4fVU_1000_HRSCAF_1962_mRNA1_gene1;pri=5
Scv4fVU_1000_HRSCAF_1962        gth2h   CDSpart 18220   18861   .       +       0       src=P;grp=asmbl_2248.p1_Scv4fVU_1000_HRSCAF_1962_mRNA1_gene1;pri=5
Scv4fVU_1000_HRSCAF_1962        gth2h   stop    18969   18971   .       +       0       src=P;grp=asmbl_2248.p1_Scv4fVU_1000_HRSCAF_1962_mRNA1_gene1;pri=5
Scv4fVU_1000_HRSCAF_1962 

I will be grateful if tell me what I am doing rung.
BR,
Pezhman

**Comment by tomasbruna** [comment]
Hi Pezhman,

GenomeThreader is no longer actively supported in BRAKER, and therefore this issue will probably never be fixed. Please use the new tool [TSEBRA](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04482-0) to combine RNA-Seq- and protein-based BRAKER runs.

If you want to keep using gth, I suggest you run BRAKER with protein fasta file directly, as illustrated in [test6.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test6.sh).

Tomas

**Comment by pezhmansafdari** [comment]
Hi Tomas,

I tried TSEBRA as well. The output of TSEBRA is a gtf file which I was not able to convert to gff3. I need a gff3 file for my downstream analysis.
The problem with gth is that Braker splits the genome to its contigs for multi-threading which is not optimal esp if the genome has thousands of contigs. It takes almost a month for me with 40 CPUs to map the proteins. It would be more efficient if braker was splitting the protein sequences instead of the genome. 
Since braker is not supporting the gth anymore, is there a way to get a gff3 output from TSEBRA?

My bests,
Pezhman

**Comment by LarsGab** [comment]
Hi Pezhman,

you can convert the TSEBRA output to gff3 with ['gtf2gff.pl'](https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/gtf2gff.pl) from AUGUSTUS. However, you must first make sure that the geneIDs and the geneID 'part' of the transcript IDs match (which isn't usually the case in a standard output). You can achieve that with '[rename_gtf.py](https://github.com/Gaius-Augustus/TSEBRA/blob/main/bin/rename_gtf.py)' from TSEBRA. 
For example, you can convert your TSEBRA output 'tsebra.gtf' with:
```
rename_gtf.py --gtf tsebra.gtf --out tsebra_renamed.gtf
gtf2gff.pl < tsebra_renamed.gtf --gff3 --out=tsebra.gff3
```

Best, Lars

**Comment by pezhmansafdari** [comment]
Hi,

Thanks, I managed to convert it.

BR,
Pezhman
