### ISSUE TITLE
Does anyone have a test data ?

### ISSUE THREAD

**Issue by giacuong171** [Gaius-Augustus/BRAKER#469]
Hi, everyone. I'm trying to test a whole-genome annotation pipeline, which uses Braker with evidence ( protein Fasta file and Rna paired-end Fastafiles). The test data of Braker has only the Rna bam file, so i have tried to convert the bam file back to paired-end Fasta files and align it back together. But it didn't work and occur an error ( The number of intro < 1000). So I would like to ask if anyone has a SMALL test data for me to test my pipeline? I really appreciate your help. 
Thank you.

**Comment by KatharinaHoff** [comment]
I suggest a paired end library from SRA in this tutorial: https://github.com/KatharinaHoff/BRAKER-TSEBRA-Workshop It is not super small, but it aligned in reasonable time. (Runtime is mentioned somewhere in that tutorial)
