### ISSUE TITLE
gmst2globalCoords.py error

### ISSUE THREAD

**Issue by zmz1988** [Gaius-Augustus/BRAKER#472]
Hi developers,

I got this issue when following the long-read protocol.

```
(BRAKER) [user@15 long_read_protocol]$ gmst2globalCoords.py -t cupcake.collapsed.gff -p gmst.out -o gmst.global.gtf -g genome.fasta.mod.MAKER.masked
Traceback (most recent call last):
  File "/home/user/BRAKER/scripts/gmst2globalCoords.py", line 100, in <module>
    if tx[gene][tx_id]['strand'] == '-':
KeyError: 'PB.1'

```

Is this caused by the fact that the transcripts sequence in my file is too low?

Thanks in advance!

**Comment by LarsGab** [comment]
Hi, 

there seems to be inconsistencies between the gene IDs of `gmst.out` and `cupcake.collapsed.gff`, i.e. a gene with ID `PB.1` is in `gmst.out` and not in `cupcake.collapsed.gff`.
Can you post the first few lines of `cupcake.collapsed.gff`? Did you modify `cupcake.collapsed.gff`?

Best, Lars

**Comment by zmz1988** [comment]
Hi @LarsGab ,

Sure! I didn't change anything, but the content seems fine for me. Here they are:

```
`(base) [user@node15 long_read_protocol]$ head -n 10 cupcake.collapsed.gff`
Chr1_RagTag_p	PacBio	transcript	50836	52634	.	-	.	gene_id "PB"; transcript_id "PB.1.1";
Chr1_RagTag_p	PacBio	exon	50836	51333	.	-	.	gene_id "PB"; transcript_id "PB.1.1";
Chr1_RagTag_p	PacBio	exon	51426	52203	.	-	.	gene_id "PB"; transcript_id "PB.1.1";
Chr1_RagTag_p	PacBio	exon	52287	52634	.	-	.	gene_id "PB"; transcript_id "PB.1.1";
Chr1_RagTag_p	PacBio	transcript	50948	52640	.	-	.	gene_id "PB"; transcript_id "PB.1.2";
Chr1_RagTag_p	PacBio	exon	50948	51333	.	-	.	gene_id "PB"; transcript_id "PB.1.2";
Chr1_RagTag_p	PacBio	exon	51426	52203	.	-	.	gene_id "PB"; transcript_id "PB.1.2";
Chr1_RagTag_p	PacBio	exon	52287	52640	.	-	.	gene_id "PB"; transcript_id "PB.1.2";
Chr1_RagTag_p	PacBio	transcript	60581	62478	.	-	.	gene_id "PB"; transcript_id "PB.2.1";
Chr1_RagTag_p	PacBio	exon	60581	62478	.	-	.	gene_id "PB"; transcript_id "PB.2.1";

`(base) [user@node15 long_read_protocol]$ head -n 20 gmst.out`
##gff-version 2
##source-version GeneMark.hmm_PROKARYOTIC 3.20
##date: Sat Mar 12 13:53:49 2022
# Sequence file name: cupcake.fa.mrna
# Model file name: GeneMark_hmm.mod
# RBS: true
# Model information: GeneMarkS_default_gcode_1

PB.1.1	GeneMark.hmm	CDS	118	1404	-1682.258873	+	0	gene_id=1, length=1287, gene_score=-1682.258873, rbs_score=3.065484, rbs_spacer=-1, stop_enforced=N, start_codon=0, logodd=131.709748

PB.1.2	GeneMark.hmm	CDS	124	1410	-1682.258873	+	0	gene_id=2, length=1287, gene_score=-1682.258873, rbs_score=3.065484, rbs_spacer=-1, stop_enforced=N, start_codon=0, logodd=131.709748

PB.2.1	GeneMark.hmm	CDS	150	1736	-2122.103747	+	0	gene_id=3, length=1587, gene_score=-2122.103747, rbs_score=0.573659, rbs_spacer=-1, stop_enforced=N, start_codon=0, logodd=135.865386

PB.3.1	GeneMark.hmm	CDS	114	1457	-1751.371345	+	0	gene_id=4, length=1344, gene_score=-1751.371345, rbs_score=0.868757, rbs_spacer=-1, stop_enforced=N, start_codon=0, logodd=122.720255

PB.3.2	GeneMark.hmm	CDS	114	1457	-1751.371345	+	0	gene_id=5, length=1344, gene_score=-1751.371345, rbs_score=0.868757, rbs_spacer=-1, stop_enforced=N, start_codon=0, logodd=122.720255

PB.4.1	GeneMark.hmm	CDS	239	826	-759.861439	+	0	gene_id=6, length=588, gene_score=-759.861439, rbs_score=0.665568, rbs_spacer=-1, stop_enforced=N, start_codon=0, logodd=70.116362

```

**Comment by LarsGab** [comment]
Hi,

using already collapsed transcripts shouldn't lead to this problem.
The issue seems to be with the geneIDs in `cupcake.collapsed.gff`, for example, the geneID of transcript "PB.1.1" should be "PB.1" and not "PB", and for "PB.2.1" it should be "PB.2". 
I haven't encountered this issue before with `collapse_isoforms_by_sam.py`, therefore I have no easy solution for this bug without seeing all outputs.
However, if you don't find the issue with `collapse_isoforms_by_sam.py`, you could just try to fix the geneIDs by yourself and then rerun everything subsequently of `collapse_isoforms_by_sam.py`. Let me know if you need help with fixing the IDs. 

Best, Lars

**Comment by zmz1988** [comment]
Hi, thanks! I will try to fix the gene_id issue in cupcake.collapsed.gff. I assume that I just need to replace the gene_id with the first two parts of the transcripts id, right?

I also have a question about using the collapsed transcript in the step of collapse_isoforms_by_sam.py. I checked the output file cupcake.ignored_ids.txt, and noticed that there are quite some transcripts that has very low coverage and got ignored (I guess ignored means that genes predicted by these transcripts is not in the .gff file?). May I ask how the coverage in this step is calculated? Will the collapsed transcript input affect the coverage?

**Comment by HainanWu** [comment]
Hi, 
I got some issue when following the long-read protocol. According to the following process: 
###################################################################        

#/mnt/sdf1/boshengjun/worka/wuhainan/biosoft/BRAKER/scripts/braker.pl -species=Lnchi_longreadRNA --genome=${data}/Lchi_Chr_softmasked.fa --softmasking --cores ${threads} --hints=${data}/illumina.hints.gff  --workingdir=$wdir/braker1/ 2> $wdir/braker1/braker1.log

#/mnt/sdf1/boshengjun/worka/wuhainan/biosoft/BRAKER/scripts/braker.pl -species=Lnchi_longreadPep --genome=${data}/Lchi_Chr_softmasked.fa --softmasking --cores ${threads} --epmode --prot_seq=${data}/proteins.fa  --workingdir=$wdir/braker2/ 2> $wdir/braker2/braker2.log

######### GeneMarkS-T
#mkdir $wdir/long_read_protocol
cd $wdir/long_read_protocol
#${minimap}/minimap2 -t $threads -ax splice:hq ${data}/Lchi_Chr_softmasked.fa ${data}/m54214_190528_083437.subreads.fastq  > long_reads.sam
#sort -k 3,3 -k 4,4n long_reads.sam > long_reads.s.sam

${anacogent}/collapse_isoforms_by_sam.py --input ${data}/m54214_190528_083437.subreads.fastq --fq  -s long_reads.s.sam --dun-merge-5-shorter -o cupcake

${braker2}/stringtie2fa.py -g ${data}/Lchi_Chr_softmasked.fa -f cupcake.collapsed.gff -o cupcake.fa

${GeneMarkST}/gmst.pl --strand direct cupcake.fa.mrna --output gmst.out --format GFF
#################################################################################
But I found this file (cupcake.collapsed.gff) very small size.
![image](https://user-images.githubusercontent.com/67358477/158556228-297472f7-500f-4be6-9444-9d236cf3afeb.png)

I use "m54214_190528_083437.subreads.fastq" file to mapped the masked genome. As usually, the aligned file cannot be so small size.    should I use the output full-length transcripts from Isoseq3 (total 48450 full-length transcripts)?

**Comment by zmz1988** [comment]
hi @LarsGab, sorry that I can't solve the issue. The gene_id in `gmst.out` is wrong as well... I'm not sure what cause this, as I didn't get any error when running the pipeline with long reads. I also tried from the ccs.fastq or isoseq output before the clustering, and the same problem remains. Cold you please give me some hints how to solve this problem? Thanks in advance!

**Comment by zmz1988** [comment]
Hi, just let you know that I solve my problem. I actually need to install cupcake again following their install instruction. One thing needs to be noticed is that I manually corrected the gene_id in the cupcake.collapsed.gff before as you suggested, but the corrected file still cause me the same problem. So I guess it's just not working without installing cupcake correctly, though I didn't get any error.
