### ISSUE TITLE
error: No spliced alignments were created by Spaln

### ISSUE THREAD

**Issue by Mondlii** [Gaius-Augustus/BRAKER#474]
Hi, 

I was able to work around the Spaln issues I had before, but now I am running into a stranger issue. The software runs until I get an unable to move "genemark_hintsfile.gff.rnaseq.tmp" I checked and I only have the gff.rnaseq and not the tmp one. I have seen previous discussions on this issue and when I try apply the similar fixes I get a sudden gm_key error. 

I am using the latest version, and when I add --epmode to my command it requires a path to prothint, once I add the path the tool dies giving a missing gm_key error. I am thinking this is probably a prothint issue, but with the solution at #366, I saw the line did not require the prothint path or anything. Please help. 

Kind regards,
Mondli

**Comment by tomasbruna** [comment]
Hi @Mondlii,

let's try to debug this on a test example. Did you already try a run of [test3.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3.sh) and are you getting the same issue there?

> I saw the line did not require the prothint path or anything

BRAKER2 won't need a command line path to ProtHint in case it's already present in your [$PATH](http://www.linfo.org/path_env_var.html#:~:text=PATH%20is%20an%20environmental%20variable,commands%20issued%20by%20a%20user.).

Tomas

**Comment by Mondlii** [comment]
Hi Tomas,

Thank you for your response. It seems my main issue was that Prothint was somehow affecting how GeneMark read and accepted the gm_key. Whenever I called Prothint it gave me a gm_key error. So I ran on fresh and newer installations of Spaln and Prothint using a gm_key from my supervisor and it solved the issue. Apologies for the delayed feedback.

Kind regards,
Mondli
