### ISSUE TITLE
An issue with the key?

### ISSUE THREAD

**Issue by DiyaPrabhuram** [Gaius-Augustus/BRAKER#475]
Hello,

I keep getting this error:

ERROR in file BRAKER-2.1.6/scripts/braker.pl at line 6586                                                                                                                                                          Failed to execute: perl /home/diya/project/gmes_linux_64/gmes_petap.pl --verbose --cores=1 --ES --gc_donor 0.001 --sequence=/home/diya/project/braker/genome.fa  --soft_mask auto 1>/home/diya/project/braker/GeneMark-ES.stdout 2>/home/diya/project/braker/errors/GeneMark-ES.stderr                                                                                                                
The most common problem is an expired or not present file ~/.gm_key!

The gm_key file is hidden in my home directory. I even tried re-installing GeneMark to make sure I have the right key but that didn't work either. Could there be another reason why this is happening?

Here's the command I used for reference:

`BRAKER-2.1.6/scripts/braker.pl --genome=genome.fa --prot_seq=proteins.fa --softmasking --GENEMARK_PATH=/home/diya/project/gmes_linux_64/ --DIAMOND_PATH=/home/diya/project/ --PROTHINT_PATH=/home/diya/project/ProtHint-2.6.0/bin/`

Cheers,
Diya

**Comment by DiyaPrabhuram** [comment]
Just an update:

I checked if GeneMark was installed correctly by running the check_install.bash script and this is the message I get:

`Checking GeneMark-ES installation                                                                                                                                                                                  Checking Perl setup                                                                                                                                                                                                All required Perl modules were found                                                                                                                                                                               Checking GeneMark.hmm setup                                                                                                                                                                                        GeneMark.hmm was found                                                                                                                                                                                             GeneMark.hmm is set                                                                                                                                                                                                Error, unexpected condition was detected`

I've installed GeneMark exactly the way I was supposed to. Could this be a licensing issue?

**Comment by tomasbruna** [comment]
HI @DiyaPrabhuram,

are there any more error messages related to the `check_install.bash` test? One common issue is that the default GeneMark binary does not work on new Debian-based systems. You can fix that by downloading a version for "LINUX 64 kernel 4 - 5" from http://exon.gatech.edu/GeneMark/license_download.cgi.

Tomas

**Comment by Jiangjiangzhang6** [comment]
have you solve this error , I GOT the sam 
it show the error of key
but it could run and down in single command ,but its error when run braker.lp
![image](https://user-images.githubusercontent.com/101324838/184528859-32232bfe-d163-4664-aa41-7ad654ad49f5.png)

**Comment by tomasbruna** [comment]
Are there any error or other messages in `.../braker/errors/GeneMark-ET.stderr` or in `.../braker/GeneMark-ET.stdout`?
