### ISSUE TITLE
Could not read the accuracy values out of predictions.txt when processing bucket 1. at /home/xiezy/miniconda3/bin/optimize_augustus.pl line 1223

### ISSUE THREAD

**Issue by yang98415** [Gaius-Augustus/BRAKER#477]
While using BRAKER2 I keep getting such error:
Could not read the accuracy values out of predictions.txt when processing bucket 1. at /home/xiezy/miniconda3/bin/optimize_augustus.pl line 1223

**Comment by tomasbruna** [comment]
Hi @yang98415,

please share the full BRAKER log if you are still having this issue.

Thanks,
Tomas
