### ISSUE TITLE
BRAKER.gtf to EVM

### ISSUE THREAD

**Issue by marco91sol** [Gaius-Augustus/BRAKER#479]
Hi, 

Im trying to use Evidence Modeler on braker.gtf but with no result. I used both scripts for modifying it: 

1. gtf2gff.pl
2. add_name_to_gff3.pl

But, when I launch the validator from EVM, it still gives me the following output:
Fatal Error: cannot parse ID from entry

Do you know, how can I solve it?

**Comment by life404** [comment]
You can use braker.gff3 directly, while can be converted to EVM GFF3 format using `augustus_GFF3_to_EVM_GFF3.pl`. However, before coveting, you need delete the `;` at the end of lline of braker.gff3. For example
```
$ head braker.gff3
HiC_scaffold_3  AUGUSTUS        gene    1720719 1722807 .       +       .       ID=jg51092;
HiC_scaffold_3  AUGUSTUS        mRNA    1720719 1722807 .       +       .       ID=jg51092.t1;Parent=jg51092;
HiC_scaffold_3  AUGUSTUS        start_codon     1720719 1720721 .       +       0       ID=jg51092.t1.start1;Parent=jg51092.t1;
HiC_scaffold_3  AUGUSTUS        CDS     1720719 1720866 0.78    +       0       ID=jg51092.t1.CDS1;Parent=jg51092.t1;

$ sed -i 's/;$//g' braker.gff3

$ head braker.gff3
HiC_scaffold_3  AUGUSTUS        gene    1720719 1722807 .       +       .       ID=jg51092
HiC_scaffold_3  AUGUSTUS        mRNA    1720719 1722807 .       +       .       ID=jg51092.t1;Parent=jg51092
HiC_scaffold_3  AUGUSTUS        start_codon     1720719 1720721 .       +       0       ID=jg51092.t1.start1;Parent=jg51092.t1
HiC_scaffold_3  AUGUSTUS        CDS     1720719 1720866 0.78    +       0       ID=jg51092.t1.CDS1;Parent=jg51092.t1

$ EVidenceModeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl braker.gff3 > braker.evm.gff3

$head braker.evm.gff3
HiC_scaffold_99 Braker  gene    5882    6218    .       +       .       ID=gene.file_1_file_1_jg16.t1;Name=Braker%20prediction
HiC_scaffold_99 Braker  mRNA    5882    6218    .       +       .       ID=model.file_1_file_1_jg16.t1;Parent=gene.file_1_file_1_jg16.t1;Name=Braker%20prediction
HiC_scaffold_99 Braker  exon    5882    6218    .       +       .       ID=model.file_1_file_1_jg16.t1.exon1;Parent=model.file_1_file_1_jg16.t1
HiC_scaffold_99 Braker  CDS     5882    6218    .       +       .       ID=cds.model.file_1_file_1_jg16.t1;Parent=model.file_1_file_1_jg16.t1
```
If you don't do like this, the `;` at the end of line will cause error in the converted EVM GFF3 file.
```
$ EVidenceModeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl braker.gff3|head
HiC_scaffold_96 Augustus        gene    13129   13184   .       -       .       ID=gene.file_1_file_1_jg32.t1;;Name=Augustus%20prediction
HiC_scaffold_96 Augustus        mRNA    13129   13184   .       -       .       ID=model.file_1_file_1_jg32.t1;;Parent=gene.file_1_file_1_jg32.t1;;Name=Augustus%20prediction
HiC_scaffold_96 Augustus        exon    13129   13184   .       -       .       ID=model.file_1_file_1_jg32.t1;.exon1;Parent=model.file_1_file_1_jg32.t1
HiC_scaffold_96 Augustus        CDS     13129   13184   .       -       .       ID=cds.model.file_1_file_1_jg32.t1;;Parent=model.file_1_file_1_jg32.t1
```
As you can see, in the `exon` line, an incorrect `;` appear in the middle of  `ID=model.file_1_file_1_jg32.t1;.exon1;` . The incorrect `;` will cause `ERROR, CDS cds.model.file_1_file_1_jg32.t1.HiC_scaffold_14:43163129-43163185 does not fully map within an exon record.` error when using validator from EVM

**Comment by bijendrabio** [comment]
> You can use braker.gff3 directly, while can be converted to EVM GFF3 format using `augustus_GFF3_to_EVM_GFF3.pl`. However, before coveting, you need delete the `;` at the end of lline of braker.gff3. For example
> 
> ```
> $ head braker.gff3
> HiC_scaffold_3  AUGUSTUS        gene    1720719 1722807 .       +       .       ID=jg51092;
> HiC_scaffold_3  AUGUSTUS        mRNA    1720719 1722807 .       +       .       ID=jg51092.t1;Parent=jg51092;
> HiC_scaffold_3  AUGUSTUS        start_codon     1720719 1720721 .       +       0       ID=jg51092.t1.start1;Parent=jg51092.t1;
> HiC_scaffold_3  AUGUSTUS        CDS     1720719 1720866 0.78    +       0       ID=jg51092.t1.CDS1;Parent=jg51092.t1;
> 
> $ sed -i 's/;$//g' braker.gff3
> 
> $ head braker.gff3
> HiC_scaffold_3  AUGUSTUS        gene    1720719 1722807 .       +       .       ID=jg51092
> HiC_scaffold_3  AUGUSTUS        mRNA    1720719 1722807 .       +       .       ID=jg51092.t1;Parent=jg51092
> HiC_scaffold_3  AUGUSTUS        start_codon     1720719 1720721 .       +       0       ID=jg51092.t1.start1;Parent=jg51092.t1
> HiC_scaffold_3  AUGUSTUS        CDS     1720719 1720866 0.78    +       0       ID=jg51092.t1.CDS1;Parent=jg51092.t1
> 
> $ EVidenceModeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl braker.gff3 > braker.evm.gff3
> 
> $head braker.evm.gff3
> HiC_scaffold_99 Braker  gene    5882    6218    .       +       .       ID=gene.file_1_file_1_jg16.t1;Name=Braker%20prediction
> HiC_scaffold_99 Braker  mRNA    5882    6218    .       +       .       ID=model.file_1_file_1_jg16.t1;Parent=gene.file_1_file_1_jg16.t1;Name=Braker%20prediction
> HiC_scaffold_99 Braker  exon    5882    6218    .       +       .       ID=model.file_1_file_1_jg16.t1.exon1;Parent=model.file_1_file_1_jg16.t1
> HiC_scaffold_99 Braker  CDS     5882    6218    .       +       .       ID=cds.model.file_1_file_1_jg16.t1;Parent=model.file_1_file_1_jg16.t1
> ```
> 
> If you don't do like this, the `;` at the end of line will cause error in the converted EVM GFF3 file.
> 
> ```
> $ EVidenceModeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl braker.gff3|head
> HiC_scaffold_96 Augustus        gene    13129   13184   .       -       .       ID=gene.file_1_file_1_jg32.t1;;Name=Augustus%20prediction
> HiC_scaffold_96 Augustus        mRNA    13129   13184   .       -       .       ID=model.file_1_file_1_jg32.t1;;Parent=gene.file_1_file_1_jg32.t1;;Name=Augustus%20prediction
> HiC_scaffold_96 Augustus        exon    13129   13184   .       -       .       ID=model.file_1_file_1_jg32.t1;.exon1;Parent=model.file_1_file_1_jg32.t1
> HiC_scaffold_96 Augustus        CDS     13129   13184   .       -       .       ID=cds.model.file_1_file_1_jg32.t1;;Parent=model.file_1_file_1_jg32.t1
> ```
> 
> As you can see, in the `exon` line, an incorrect `;` appear in the middle of `ID=model.file_1_file_1_jg32.t1;.exon1;` . The incorrect `;` will cause `ERROR, CDS cds.model.file_1_file_1_jg32.t1.HiC_scaffold_14:43163129-43163185 does not fully map within an exon record.` error when using validator from EVM

This doesn't seems to work with braker.gtf or tsebra.gtf file. I tried the steps you suggested and received following error while validating using "gff3_gene_prediction_file_validator.pl":

ERROR:
Error, feature: model.anno1.jg743953.t2 is described multiple times with different data values:
$VAR1 = {
          'lend' => '139408387',
          'feat_type' => 'exon',
          'rend' => '139408763',
          'parent_ID' => 'model.anno1.jg743953.t2',
          'orient' => '-',
          'contig' => 'Chr1',
          'feature_ID' => 'model.anno1.jg743953.t2'


Example of Gff3 file generated using augustus_GTF_to_EVM_GFF3.pl
```
Chr1	Augustus	gene	139406822	139409543	.	-	.	ID=gene.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2;Name=Augustus%20prediction
Chr1	Augustus	mRNA	139406822	139409543	.	-	.	ID=model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2;Parent=gene.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2;Name=Augustus%20prediction
Chr1	Augustus	exon	139409460	139409543	.	-	.	ID=model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2.exon1;Parent=model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2
Chr1	Augustus	CDS	139409460	139409543	.	-	.	ID=cds.model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2;Parent=model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2
Chr1	Augustus	exon	139408993	139409375	.	-	.	ID=model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2.exon2;Parent=model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2
Chr1	Augustus	CDS	139408993	139409375	.	-	.	ID=cds.model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2;Parent=model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2
Chr1	Augustus	exon	139408833	139408903	.	-	.	ID=model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2.exon3;Parent=model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2
Chr1	Augustus	CDS	139408833	139408903	.	-	.	ID=cds.model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2;Parent=model.anno1.jg743953.t2;gene_id=g_174935;transcript_id=anno1.jg743953.t2
```

**Comment by LarsGab** [comment]
This issue is discussed in https://github.com/Gaius-Augustus/TSEBRA/issues/22 .
