### ISSUE TITLE
/yourSpecies/genome.fa replaced by protein file.

### ISSUE THREAD

**Issue by bbista** [Gaius-Augustus/BRAKER#48]
/yourSpecies/genome.fa replaced by protein file.
When I run something like the following. i find that the /yourSpecies/genome.fa which should be the genome.fasta file gets replace with proteins.fa. Therefore the hints file comes up empty. 
The filterIntronsFindStrand.stderr file are filled with the following error for each sequence of the genome file.
WARNING: 'Scbe7cn_1026_HRSCAF_1040' does not match any sequence in the fasta file. Maybe the two files do not belong together even though the sequences are there in the input file. 

braker.pl --species=yourSpecies --genome=genome.fasta \
       --bam=file1.bam,file2.bam --prot_seq=proteins.fa \
       --prg=(gth|exonerate|spaln)

**Comment by KatharinaHoff** [comment]
I fail to reproduce this problem. The scenario corresponds to test5.sh in the BRAKER examples directory, and that appears to run ok on my machine with the current BRAKER code.
