### ISSUE TITLE
Repeat mask and TE gene

### ISSUE THREAD

**Issue by CAShuangchao** [Gaius-Augustus/BRAKER#480]
Hi,
  I have a question about how to deal with transposable element (TE) when I get Braker's results. I know that the softmasked genome with the option "--softmasking" will play a role by reducing the likelihood of predicting genes in repetitive regions.
  However, this must be on the premise that the screening results of the repeat sequence region are accurate, and the repeat sequence region does not contain normal protein-coding genes except for TEs. But in my test, it was found that the repeated region using RepeatMasker softmasked actually still contained many coding genes which should not be removed rudely.
  For example, among the nearly 40,000 genes displayed in the MSUv7 annotation of Rice, about 2,000 genes were in the shielding region given by RepeatMasker, while the interpro annotation of some of these 2,000 genes showed that they did not include the TEs domain.
  At present, my method is to find out the genes containing TEs according to the interpro results of the preliminary annotation protein, but this method consumes a lot of time, and not all proteins can obtain the interpro annotation.
  Therefore, based on your genome annotation experience, is there any good suggestion that can remove TEs as accurately as possible in the preliminary annotation results without losing other coding genes in the repeat region?

Thanks,
HuangChao

**Comment by tomasbruna** [comment]
Hi @CAShuangchao,

> But in my test, it was found that the repeated region using RepeatMasker softmasked actually still contained many coding genes which should not be removed rudely.

This is pretty common, and therefore, BRAKER accounts for the possibility of true coding genes being overlapped by repeats. That is why the likelihood of predicting genes in repetitive regions is reduced, but not set to 0. So BRAKER might already be doing what you want. Take a look at the discussion in https://github.com/Gaius-Augustus/BRAKER/issues/362 for more details.

Best,
Tomas

**Comment by CAShuangchao** [comment]
Thanks for your reply, I get it. 

Thanks,
huangchao
