### ISSUE TITLE
The .gm_key problem and other issues

### ISSUE THREAD

**Issue by ricardoi** [Gaius-Augustus/BRAKER#481]
Hello, 
I have a problem similar to #393 !! 
I have freshly downloaded and hidden `~/.gm_key`, and perls `PATHs` changed to where perl is. 

**Although, still I have the same error message:**
```
braker.pl --genome=Pillicis.contigs.fasta --species=Pillicis --hints=Phytophthora_ss/prothint_augustus.gff --softmasking --epmode --useexisting
# Wed Mar 30 13:52:12 2022: Log information is stored in file /home/microway/Documents/clade3P/03_annotation/braker/braker.log
ERROR in file /home/microway/git_local/BRAKER/scripts/braker.pl at line 6758
Failed to execute: perl /home/microway/gmes_linux_64/gmes_petap.pl --verbose --seq /home/microway/Documents/clade3P/03_annotation/braker/genome.fa --EP /home/microway/Documents/clade3P/03_annotation/braker/genemark_hintsfile.gff --cores=1  --gc_donor 0.001 --evidence /home/microway/Documents/clade3P/03_annotation/braker/genemark_evidence.gff  --soft_mask auto 1>/home/microway/Documents/clade3P/03_annotation/braker/GeneMark-EP.stdout 2>/home/microway/Documents/clade3P/03_annotation/braker/errors/GeneMark-EP.stderr
Failed to execute: perl /home/microway/gmes_linux_64/gmes_petap.pl --verbose --seq /home/microway/Documents/clade3P/03_annotation/braker/genome.fa --EP /home/microway/Documents/clade3P/03_annotation/braker/genemark_hintsfile.gff --cores=1  --gc_donor 0.001 --evidence /home/microway/Documents/clade3P/03_annotation/braker/genemark_evidence.gff  --soft_mask auto 1>/home/microway/Documents/clade3P/03_annotation/braker/GeneMark-EP.stdout 2>/home/microway/Documents/clade3P/03_annotation/braker/errors/GeneMark-EP.stderr
The most common problem is an expired or not present file ~/.gm_key!
```
------- 
**The genemark std err is _empty_ and err displays the following** 
```
# check before the run
# hard_mask is in the 'auto' mode. hard_mask was set to: 1000
# creat directories
# commit input data
error, output file is empty data/evidence.gff
error on call: /home/microway/gmes_linux_64/reformat_gff.pl --out data/evidence.gff  --trace info/dna.trace  --in /home/microway/Doc
uments/clade3P/03_annotation/braker/genemark_evidence.gff  --quiet
```
--------
**Also I checked genemark install**
```
check_install.bash 
Checking GeneMark-ES installation
Checking Perl setup
All required Perl modules were found
Checking GeneMark.hmm setup
GeneMark.hmm was found
GeneMark.hmm is set
GeneMark.hmm is executable
Performing GeneMark.hmm test run
All required components for GeneMark-ES were found
```
------
**Any suggestions?** 
Thank you

**Comment by JFWolters** [comment]
Essentially the same issue here.

I can add that my issue is specific to braker. Copying the call braker makes to gmes_petap.pl exactly and just running it in the terminal executes without error so the .gmes_key is correct and genemark is configured correctly.

**Comment by sunnyEV** [comment]
> 
> ERROR in file /home/sun/data/softwares/BRAKER-2.1.6/scripts/braker.pl at line 6586
> Failed to execute: perl /home/sun/data/softwares/genemark/gmes_linux_64_4/gmes_petap.pl --verbose --cores=8 --ES --gc_donor 0.001 --sequence=/DATA/mat/sun/softwares/BRAKER-2.1.6/scripts/braker/genome.fa  1>/DATA/mat/sun/softwares/BRAKER-2.1.6/scripts/braker/GeneMark-ES.stdout 2>/DATA/mat/sun/softwares/BRAKER-2.1.6/scripts/braker/errors/GeneMark-ES.stderr

**The most common problem is an expired or not present file ~/.gm_key!**

**Comment by tomasbruna** [comment]
Hi @ricardoi, @JFWolters, @sunnyEV,

did you try to run BRAKER on one of the test inputs in the [example folder](https://github.com/Gaius-Augustus/BRAKER/tree/master/example/tests)? If so, are you getting the same error? I want to rule out the possibility that the error is specific to your input data (since the default GeneMark test with example data works for you, )

Thanks and sorry for the late reply,
Tomas

**Comment by tomasbruna** [comment]
@JFWolters, what does the `GeneMark-E*.stdout` contain in your case? The same message as @ricardoi shared?

**Comment by ricardoi** [comment]
Hello Tomas, I did not try it on the test input example! 
I could try if you think that would help.
Thanks.

**Comment by tomasbruna** [comment]
Hi @ricardoi,

yes, please do run it on the test input. It makes it much easier to debug (and it runs fast).

Tomas

**Comment by JFWolters** [comment]
I have confirmed that I am still getting the same error on the example file.

Here are the results from GeneMark-ES.stdout.
```

# check before the run
# hard_mask is in the 'auto' mode. hard_mask was set to: 1000
# creat directories
# commit input data
# prepare input data report
# commit training data
# prepare training data report
# prepare initial model
# find GC of sequence
GC 37
# build initial ES model
running step ES_A
running gm.hmm on local system
8 contigs in list
warning on: /mnt/bigdata/linuxhome/jwolters/packages/gmes_linux_64/gmhmme3  -m /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_ini/es_ini.mod   -f tr  -d /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/plus_hmm.gff  -k -0.03  -o /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_1.out  /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/data/training/dna.fa_1
warning on: /mnt/bigdata/linuxhome/jwolters/packages/gmes_linux_64/gmhmme3  -m /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_ini/es_ini.mod   -f tr  -d /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/plus_hmm.gff  -k -0.03  -o /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_2.out  /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/data/training/dna.fa_2
warning on: /mnt/bigdata/linuxhome/jwolters/packages/gmes_linux_64/gmhmme3  -m /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_ini/es_ini.mod   -f tr  -d /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/plus_hmm.gff  -k -0.03  -o /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_3.out  /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/data/training/dna.fa_3
warning on: /mnt/bigdata/linuxhome/jwolters/packages/gmes_linux_64/gmhmme3  -m /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_ini/es_ini.mod   -f tr  -d /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/plus_hmm.gff  -k -0.03  -o /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_4.out  /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/data/training/dna.fa_4
warning on: /mnt/bigdata/linuxhome/jwolters/packages/gmes_linux_64/gmhmme3  -m /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_ini/es_ini.mod   -f tr  -d /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/plus_hmm.gff  -k -0.03  -o /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_5.out  /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/data/training/dna.fa_5
warning on: /mnt/bigdata/linuxhome/jwolters/packages/gmes_linux_64/gmhmme3  -m /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_ini/es_ini.mod   -f tr  -d /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/plus_hmm.gff  -k -0.03  -o /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_6.out  /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/data/training/dna.fa_6
warning on: /mnt/bigdata/linuxhome/jwolters/packages/gmes_linux_64/gmhmme3  -m /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_ini/es_ini.mod   -f tr  -d /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/plus_hmm.gff  -k -0.03  -o /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_7.out  /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/data/training/dna.fa_7
warning on: /mnt/bigdata/linuxhome/jwolters/packages/gmes_linux_64/gmhmme3  -m /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_ini/es_ini.mod   -f tr  -d /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/plus_hmm.gff  -k -0.03  -o /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_8.out  /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/data/training/dna.fa_8
concatenate predictions: /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1
training level ES_A: /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1
error, file not found /mnt/bigdata/linuxhome/jwolters/packages/gmes_linux_64/parse_set.pl: set.out
error on call: /mnt/bigdata/linuxhome/jwolters/packages/gmes_linux_64/parse_set.pl --section ES_A --cfg  /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run.cfg  --v 

```

**Comment by tomasbruna** [comment]
@JFWolters,

this warning is usually a symptom of using an old GeneMark `gmhmme3` binary on a new system. Did you try getting the "LINUX 64 kernel 4 - 5" version from http://exon.gatech.edu/GeneMark/license_download.cgi?

**Comment by JFWolters** [comment]
I wasn't really sure if I had so I just downloaded and set it up from that version with a new gm_key. There was no change in the output or errors.

**Comment by tomasbruna** [comment]
I see. What happens when you run one of the warning-producing commands directly? For example,

    /mnt/bigdata/linuxhome/jwolters/packages/gmes_linux_64/gmhmme3  -m /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_ini/es_ini.mod   -f tr  -d /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/plus_hmm.gff  -k -0.03  -o /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/run/ES_A_1/hmmout/dna.fa_8.out  /mnt/bigdata/linuxhome/jwolters/annotation_pipelines/BRAKER_v1/test_3/results/test/braker/GeneMark-ES/data/training/dna.fa_8

**Comment by JFWolters** [comment]
Alright, I think I have diagnosed the issue to something with my set up. I have been running it through a job scheduler since I'm integrating this into a larger pipeline.

Running the offending line outside of the pipeline completes normally, so I tried just running braker itself outside of the pipeline and it seems to be running okay.

I think what is happening is that although the bash script running everything correctly expands ~ to my home directory, for some reason when braker is executing it is not expanding it properly due to some kind of interaction with the job scheduler.

I'll do some digging on my end to see if its possible to diagnose the root issue and whether its some bad interaction with the job scheduler.

**Comment by ricardoi** [comment]
0k, while I was waiting for a reply, I updated BRAKER to version 2.1.6 and installed a new GeneMark with .gm_key -Linux 64 kernel 4-5. 
Then, as you suggested, I ran the test - and I was missing some `PATHs`, and apparently, it ran without problems on the test data (see test output below). Although, when I tested it on my data, I had the same problem: `expired or not present file ~/.gm_key!`

## Test output
#**********************************************************************************
#                               BRAKER CONFIGURATION                               
#**********************************************************************************
# BRAKER CALL: /home/microway/BRAKER-2.1.6/scripts/braker.pl --genome=../genome.fa --bam=../RNAseq.bam --softmasking --workingdir=test10 --cores
 8 --gm_max_intergenic 10000 --addUTR=on
# Mon May  2 15:32:22 2022: braker.pl version 2.1.6
# Mon May  2 15:32:22 2022: Creating directory /home/microway/BRAKER-2.1.6/example/tests/test10.
# Mon May  2 15:32:22 2022: Configuring of BRAKER for using external tools...
# Mon May  2 15:32:22 2022: Trying to guess $AUGUSTUS_BIN_PATH from $AUGUSTUS_CONFIG_PATH.
# Mon May  2 15:32:22 2022: Setting $AUGUSTUS_BIN_PATH to /home/microway/git_local/Augustus/bin/../config/../bin
# Mon May  2 15:32:22 2022: Trying to guess $AUGUSTUS_SCRIPTS_PATH from $AUGUSTUS_CONFIG_PATH.
# Mon May  2 15:32:22 2022: Setting $AUGUSTUS_SCRIPTS_PATH to /home/microway/git_local/Augustus/bin/../config/../scripts
# Mon May  2 15:32:22 2022: Did not find environment variable $PYTHON3_PATH
# Mon May  2 15:32:22 2022: Trying to guess $PYTHON3_PATH from location of python3 executable that is available in your $PATH
# Mon May  2 15:32:22 2022: Setting $PYTHON3_PATH to /usr/bin
# Mon May  2 15:32:22 2022: Did not find environment variable $JAVA_PATH
# Mon May  2 15:32:22 2022: Trying to guess $JAVA_PATH from location of java executable that is available in your $PATH
# Mon May  2 15:32:22 2022: Setting $JAVA_PATH to /usr/bin
# Mon May  2 15:32:22 2022: Did not find environment variable $GUSHR_PATH
# Mon May  2 15:32:22 2022: Trying to guess $GUSHR_PATH from location of gushr.py executable that is available in your $PATH
# Mon May  2 15:32:22 2022: Setting $GUSHR_PATH to /home/microway/git_local/GUSHR
# Mon May  2 15:32:22 2022: Did not find environment variable $GENEMARK_PATH  (either variable does not exist, or the path given in variable doe
s not exist). Will try to set this variable in a different way, later.
# Mon May  2 15:32:22 2022: Trying to guess $GENEMARK_PATH from location of gmes_petap.pl executable that is available in your $PATH
# Mon May  2 15:32:22 2022: Setting $GENEMARK_PATH to /home/microway/gmes_linux_64_4
# Mon May  2 15:32:22 2022: Did not find environment variable $BAMTOOLS_PATH (either variable does not exist, or the path given in variable does
 not exist). Will try to set this variable in a different way, later.
# Mon May  2 15:32:22 2022: Trying to guess $BAMTOOLS_BIN_PATH from location of bamtools executable that is available in your $PATH
# Mon May  2 15:32:22 2022: Setting $BAMTOOLS_BIN_PATH to /usr/bin
# Mon May  2 15:32:22 2022: Did not find environment variable $SAMTOOLS_PATH  (either variable does not exist, or the path given in variable doe
snot exist). Will try to set this variable in a different way, later.
# Mon May  2 15:32:22 2022: Trying to guess $SAMTOOLS_PATH from location of samtools executable in your $PATH
# Mon May  2 15:32:22 2022: Setting $SAMTOOLS_PATH to /usr/bin
# Mon May  2 15:32:22 2022: Did not find environment variable $DIAMOND_PATH
# Mon May  2 15:32:22 2022: Trying to guess $DIAMOND_PATH from location of diamond executable that is available in your $PATH
# Mon May  2 15:32:22 2022: Setting $DIAMOND_PATH to /usr/bin
# Mon May  2 15:32:22 2022: Did not find environment variable $CDBTOOLS_PATH
# Mon May  2 15:32:22 2022: Trying to guess $CDBTOOLS_PATH from location of cdbfasta executable that is available in your $PATH
# Mon May  2 15:32:22 2022: Setting $CDBTOOLS_PATH to /usr/bin
#*********
# IMPORTANT INFORMATION: no species for identifying the AUGUSTUS  parameter set that will arise from this BRAKER run was set. BRAKER will create an AUGUSTUS parameter set with name Sp_2. This parameter set can be used for future BRAKER/AUGUSTUS prediction runs for the same species. It is usually not necessary to retrain AUGUSTUS with novel extrinsic data if a high quality parameter set already exists.
#*********
#**********************************************************************************
#                               CREATING DIRECTORY STRUCTURE                       
#**********************************************************************************
# Mon May  2 15:32:22 2022: creating file that contains citations for this BRAKER run at /home/microway/BRAKER-2.1.6/example/tests/test10/what-t
o-cite.txt...
# Mon May  2 15:32:22 2022: create working directory /home/microway/BRAKER-2.1.6/example/tests/test10/GeneMark-ET.
mkdir /home/microway/BRAKER-2.1.6/example/tests/test10/GeneMark-ET
# Mon May  2 15:32:22 2022: create working directory /home/microway/BRAKER-2.1.6/example/tests/test10/species
mkdir /home/microway/BRAKER-2.1.6/example/tests/test10/species
# Mon May  2 15:32:22 2022: create working directory /home/microway/BRAKER-2.1.6/example/tests/test10/errors
mkdir /home/microway/BRAKER-2.1.6/example/tests/test10/errors
# Mon May  2 15:32:22 2022: changing into working directory /home/microway/BRAKER-2.1.6/example/tests/test10
cd /home/microway/BRAKER-2.1.6/example/tests/test10
# Mon May  2 15:32:22 2022: Creating parameter template files for AUGUSTUS with new_species.pl
# Mon May  2 15:32:22 2022: new_species.pl will create parameter files for species Sp_2 in /home/microway/git_local/Augustus/bin/../config/speci
es/Sp_2
perl /home/microway/git_local/Augustus/scripts/new_species.pl --species=Sp_2 --AUGUSTUS_CONFIG_PATH=/home/microway/git_local/Augustus/bin/../con
fig 1> /dev/null 2>/home/microway/BRAKER-2.1.6/example/tests/test10/errors/new_species.stderr
# Mon May  2 15:32:23 2022: check_fasta_headers(): Checking fasta headers of file /home/microway/BRAKER-2.1.6/example/tests/../genome.fa
#**********************************************************************************
#                               PROCESSING HINTS                                   
#**********************************************************************************
# Mon May  2 15:32:23 2022: Converting bam files to hints
# Mon May  2 15:32:23 2022: Checking bam headers
# Mon May  2 15:32:23 2022: create header file /home/microway/BRAKER-2.1.6/example/tests/test10/RNAseq_header.sam
/usr/bin/bamtools header -in /home/microway/BRAKER-2.1.6/example/tests/../RNAseq.bam > /home/microway/BRAKER-2.1.6/example/tests/test10/RNAseq_h
eader.sam
# Mon May  2 15:32:23 2022: Deleting SAM header file /home/microway/BRAKER-2.1.6/example/tests/test10/RNAseq_header.sam (will not be needed from
 here on)
# Mon May  2 15:32:23 2022: Deleting /home/microway/BRAKER-2.1.6/example/tests/test10/RNAseq_new_header.sam
# Mon May  2 15:32:23 2022: make hints from BAM file /home/microway/BRAKER-2.1.6/example/tests/../RNAseq.bam
/home/microway/git_local/Augustus/bin/../config/../bin/bam2hints --intronsonly --in=/home/microway/BRAKER-2.1.6/example/tests/../RNAseq.bam --ou
t=/home/microway/BRAKER-2.1.6/example/tests/test10/bam2hints.temp.0.gff 1> /home/microway/BRAKER-2.1.6/example/tests/test10/errors/bam2hints.0.s
tdout 2>/home/microway/BRAKER-2.1.6/example/tests/test10/errors/bam2hints.0.stderr
# Mon May  2 15:32:24 2022: add hints from BAM file /home/microway/BRAKER-2.1.6/example/tests/../RNAseq.bam to hints file
cat /home/microway/BRAKER-2.1.6/example/tests/test10/bam2hints.temp.0.gff >>/home/microway/BRAKER-2.1.6/example/tests/test10/hintsfile.temp.gff

## My data 
braker.pl --species Pillicis --genome=Pillicis.contigs_rn-sm.fasta --softmasking --hints=Phytophthora_db/prothint_augustus.gff 
# Mon May  2 15:55:42 2022: Log information is stored in file /home/microway/Documents/clade3P/03_annotation/braker/braker.log
ERROR in file /home/microway/BRAKER-2.1.6/scripts/braker.pl at line 6749
Failed to execute: perl /home/microway/gmes_linux_64_4/gmes_petap.pl --verbose --seq /home/microway/Documents/clade3P/03_annotation/braker/genome.fa --EP /home/microway/Documents/clade3P/03_annotation/braker/genemark_hintsfile.gff --cores=1  --gc_donor 0.001 --evidence /home/microway/Documents/clade3P/03_annotation/braker/genemark_evidence.gff  --soft_mask auto 1>/home/microway/Documents/clade3P/03_annotation/braker/GeneMark-EP.stdout 2>/home/microway/Documents/clade3P/03_annotation/braker/errors/GeneMark-EP.stderr
Failed to execute: perl /home/microway/gmes_linux_64_4/gmes_petap.pl --verbose --seq /home/microway/Documents/clade3P/03_annotation/braker/genome.fa --EP /home/microway/Documents/clade3P/03_annotation/braker/genemark_hintsfile.gff --cores=1  --gc_donor 0.001 --evidence /home/microway/Documents/clade3P/03_annotation/braker/genemark_evidence.gff  --soft_mask auto 1>/home/microway/Documents/clade3P/03_annotation/braker/GeneMark-EP.stdout 2>/home/microway/Documents/clade3P/03_annotation/braker/errors/GeneMark-EP.stderr
The most common problem is an expired or not present file ~/.gm_key!

**Comment by tomasbruna** [comment]
Hi @ricardoi,

thanks for running the test. So just to make sure, this is the error you are getting with your data in GeneMark:

```
error, output file is empty data/evidence.gff
error on call: /home/microway/gmes_linux_64/reformat_gff.pl --out data/evidence.gff  --trace info/dna.trace  --in /home/microway/Doc
uments/clade3P/03_annotation/braker/genemark_evidence.gff  --quiet

```

and no errors on the test set?

This looks like a problem with protein hints (the GM key error is just a generic error message). Can you share the `Phytophthora_db/prothint_augustus.gff` file? If you don't want to share it here, please contact me by email at bruna.tomas@gatech.edu.

Best,
Tomas

**Comment by ricardoi** [comment]
0k, and yes, that's the error message I am getting with GeneMark, the genemark_evidence.gff is empty. The test set ran without errors.  
I will contact you shortly, 
Thanks,
Ricardo I

**Comment by ricardoi** [comment]
Hello Tomas, 
I was able to debug a little bit more with the previous message and turn out that GeneMark did not recognize the format of the `.gff` file. A warning message indicated that start, stop, and intron are supported features.
So basically, I had to change the feature type from `start_codon` to `start` and `stop_codon` to `stop` on my `gff` file.

After that, it worked, but I got an independent ERROR message about an invalid source key that I am debugging.

Thanks, 
Ricardo I

**Comment by tomasbruna** [comment]
I see, I should have realized this. For this exact reason, ProtHint outputs a file called `prothint_augustus.gff` which is in the right format. Using this file might also solve your source key error.

**Comment by ricardoi** [comment]
Using the `prothint_augustus.gff` pointing to the same ~/.gm_key error
data/evidence.gff empty
```
# check before the run
# hard_mask is in the 'auto' mode. hard_mask was set to: 1000
# creat directories
# commit input data
error, output file is empty data/evidence.gff <--- EMPYT
error on call: /home/microway/gmes_linux_64_4/reformat_gff.pl --out data/evidence.gff  --trace info/dna.trace  --in /home/microw
ay/Documents/clade3P/03_annotation/braker/genemark_evidence.gff  --quiet
```

**Comment by tomasbruna** [comment]
Hi @ricardoi,

thanks for sharing the extra info. Based on that, it seems that there is a mismatch between contig names in ProtHint output and the contig names in the genome you supply to BRAKER. The names in the trace (e.g., `tig00000026`), should be identical to the first column in evidence (the `AOFI03000001.1` entry).

Is it possible that you used an assembly with different contig names when running ProtHint?

Tomas

**Comment by ricardoi** [comment]
I figured, yes, very likely. Running again with matching names, so far no problem. 
Thank you.

Ricardo I.
