### ISSUE TITLE
Braker for European Food Safety Authority and issue of gene names

### ISSUE THREAD

**Issue by iaconogi** [Gaius-Augustus/BRAKER#483]
Dear Developer,
we are trying to use Braker in our risk assessment pipelines at European Food Safety Authority.
So far, we managed to successfully run your tool in a newly created docker container.
When running in --esmode, we indeed noticed that indeed predicted genes consist in structural annotations (start, stop, acronyms such as g1, g2...) but no information on predicted gene name.
Is there any way, starting from the output of Braker, to add putative gene names to the predictions, or are we completely off-road, and we should have used an entirely different tool/approach (if so, which one?).
Best

**Comment by MarioStanke** [comment]
What you are looking for is called *functional* annotation. This is usually done after *structural* annotation (finding genes and their coordinates and protein sequences) and independently of it. Many perform a homology search against a protein database such as UniProt and copy names from (reciprocal) best hits.

**Comment by iaconogi** [comment]
Dear @MarioStanke thanks for your reply. I supposed something like that. And do I have to create myself the code for running blast, extracting reciprocal best hits and adding them to the annotations, or something like that already exists ?

**Comment by KatharinaHoff** [comment]
I think you might be looking for functional annotation. Interproscan can
for example provide clues on protein function.

iaconogi ***@***.***> schrieb am Di. 12. Apr. 2022 um 11:19:
