### ISSUE TITLE
Exception results after running "gmst2globalCoords.py"

### ISSUE THREAD

**Issue by abcyulongwang** [Gaius-Augustus/BRAKER#485]
Hello!
I used the process from "https://github.com/Gaius-Augustus/BRAKER/blob/master/docs/long_reads/long_read_protocol.md".

I used ”collapse_isoforms_by_sam.py“ to get the file "merge.combined.gtf", then I ran "stringtie2fa.py" to get the input file "cupcake.fa.mrna", this step works fine.

But when I run `gmst.pl --strand direct cupcake.fa.mrna --output gmst.out --format GFF`
The resulting file is 
![image](https://user-images.githubusercontent.com/93254434/163356628-5fce19ba-0e8d-41d4-8bce-67310b80b8a7.png)

And when I run `gmst2globalCoords.py -t cupcake.collapsed.gff -p gmst.out -o gmst.global.gtf -g genome.fa`
The final file "gmst.global.gtf" has a size of 0 and no error message
![image](https://user-images.githubusercontent.com/93254434/163357379-5a2c36e3-3b67-4ee6-863a-0953e4b8cb64.png)

I can't figure out what's going on, would appreciate some advice from you!

Best
yulong

**Comment by LarsGab** [comment]
Hi yulong,

a possible issue might be inconsistencies of transcript or gene IDs between `gmst.out` and `cupcake.collapsed.gff`. Can you check if they match, or can you share a few lines from each file so I can take a look?

Best, Lars

**Comment by abcyulongwang** [comment]
Dear Lars


Thank you for your reply！
As you said, the "gene_id" of the "gmst.out" and "cupcake.collapsed.gff" files are indeed different.








So what should I do next?


Best,Yulong






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gaius-Augustus/BRAKER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 下午3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Gaius-Augustus/BRAKER] Exception results after running "gmst2globalCoords.py" (Issue #485)





 
Hi yulong,
 
a possible issue might be inconsistencies of transcript or gene IDs between gmst.out and cupcake.collapsed.gff. Can you check if they match, or can you share a few lines from each file so I can take a look?
 
Best, Lars

**Comment by LarsGab** [comment]
Do you have the same gene ID issue as in https://github.com/Gaius-Augustus/BRAKER/issues/472? Then, a proper reinstallation of Cupcake might fix the problem.
Otherwise, can you give me some example IDs from `gmst.out`, `cupcake.fa.mrna`, and `cupcake.collapsed.gff`, so I can see the exact problem?
Best, Lars

**Comment by abcyulongwang** [comment]
I have solved the problem as you said, thank you very much
Best,yulong

**Comment by Flyase** [comment]
Hello, I am wondering if the pipeline involving stringtie2fa.py, gmst.pl, and gmst2globalCoords.py is suitable for GFF-type files that have not been generated by Cupcake with long reads. 
I have tested one such GFF file as input for stringtie2fa.py and it works fine. However, the next steps have issues similar to those listed at the top of the page, and the gene IDs in gmst.out have the same issue as described in #472. 
I would appreciate your response. Thank you very much.
