### ISSUE TITLE
Estimated diminishing returns of RNA-seq reads and TSEBRA 

### ISSUE THREAD

**Issue by SamCT** [Gaius-Augustus/BRAKER#486]
Hi team, having good success with running test data sets so far, great work. I've got two questions that relate to the RNA-seq .bam files within braker1 pipeline (using GeneMark-ET). I'm using a phased haplotype (hap1) genome, planning to annotate both hap1/hap2 -- combined are around 380 Mbp. 

First, I have a fairly large amount of RNA-seq data, nearly 150Gb raw. Some are tissues of the same organism from old Illumina platforms (~50% of data), others from related species tissues, produced by newer Illumina platforms (NCBI). It's briefly mentioned in the Github manual that there is a point of diminishing returns of adding more RNA-seq data. With regards to my genome size and rna data set, is there a rough number for the threshold for those diminishing returns on annotations? Should I stop at 70Gb of raw RNA-seq data for the same species?

Secondly, If I choose to continue using this large dataset, is it reasonable to run braker1 pipeline on each individual samples' set of paired-read bam files produced by hisat2, and then combine all the related .gff / .gtf files into one for the final TSEBRA merge of braker1 + my braker2 (GeneMark-EP) output? In other words, I imagine this would decrease the overall run time but would these combined files be compatible with the TSEBRA merge? Or would I need to stick with running the braker1 pipeline on a massive RNA-seq hisat2 bam file of multiple species' tissues? This may err into a question of RNA-seq experimental design, but I'm curious to hear thoughts on this.

Thank you,
Sam

**Comment by tomasbruna** [comment]
Hi Sam,

> With regards to my genome size and rna data set, is there a rough number for the threshold for those diminishing returns on annotations?

It is impossible to give a general answer, but I'd consider 70Gb of RNA-Seq data to be sufficient for a genome of this size. Especially if the data is coming from multiple different libraries.

As for the second question, BRAKER1 is designed for the second use case:

>  running the braker1 pipeline on a massive RNA-seq hisat2 bam file of multiple species' tissues`

If you run BRAKER1 individually for each RNA sample, you risk accumulating a lot of noise (false predictions). Using TSEBRA to combine all the BRAKER1 results should remove that noise, but we never tested such a strategy. Also, such an approach would probably not be faster. A single BRAKER1 run with _N_ combined libraries should be faster than _N_ BRAKER1 runs (each with a smaller library).

Best,
Tomas
