### ISSUE TITLE
intergenic regions

### ISSUE THREAD

**Issue by xyz0o** [Gaius-Augustus/BRAKER#487]
I have seen in papers that researchers usually categorize gene regions in exon, intron, upstream, downstream and intergenic regions. I don't know what is included in upstream and downstream but I guess it could be the sum of start-codon, stop-codon and -utr?

my second question is that how to extract intergenic regions from braker output?

**Comment by tomasbruna** [comment]
The output of BRAKER comes in the standard [gtf/gff formats](https://en.wikipedia.org/wiki/General_feature_format) -- intergenic regions are all regions between predicted genes.

If you are still confused, take a look at this paper https://www.nature.com/articles/nrg3174
