### ISSUE TITLE
Error Parallelizing Braker2 runs: Failed to create new species with new_species.pl, check write permissions

### ISSUE THREAD

**Issue by nitinra** [Gaius-Augustus/BRAKER#488]
Hello all,

I have to annotate about 100 genomes downloaded from NCBI. In order to save time, I am using GNU parallel to run multiple Braker runs at the same time. Here is my code that I am using:

`cat /my/path/testrun1.txt | parallel -j+0 \
braker.pl --genome={} \
--prot_seq=/my/path/odb10_arthropoda_proteins.fa --softmasking --species UniqueSpeciesName \
--cores=28 --workingdir=$your_working_dir/braker_results/{.}`

I get this error when I run it:
```
ERROR in file /work/nitinr/BRAKER-master/scripts/braker.pl at line 7157
Failed to create new species with new_species.pl, check write permissions in /work/nitinr/augustus_config/species directory! Command was perl /work/nitinr/software/Augustus/scripts/new_species.pl --species=UniqueSpeciesName --AUGUSTUS_CONFIG_PATH=/work/nitinr/augustus_config 1> /dev/null 2>/work/nitinr/ellaaa/Agrilus_planipennis_genome.softmasked/errors/new_species.stderr
# Fri Apr 29 21:50:29 2022: Log information is stored in file /work/nitinr/ellaaa/Anopheles_arabiensis_genome.softmasked/braker.log
```

I am assuming that it is because multiple runs are being run at the same time in the augustus_config and hence being overwritten. Is there any workaround for this where I can parallelize using GNU parallel?

**Comment by tomasbruna** [comment]
Hi @nitinra,

you need to make sure that the `UniqueSpeciesName` is different in each of the parallel runs. You could, for example, use the genome name, i.e. the `{}` variable: `... --species {}`

Best,
Tomas

**Comment by nitinra** [comment]
Working perfectly! Thanks!
