### ISSUE TITLE
¿Use of lncRNA as BRAKER RNAseq evidence?

### ISSUE THREAD

**Issue by V-JJ** [Gaius-Augustus/BRAKER#491]
Good afternoon, 

We would like to run BRAKER using both 1) protein and 2) RNA-seq evidence following the TSEBRA protocol.
But, before running BRAKER RNAseq pipeline we would like to know whether it is useful or harmful to include lncRNAseq data as evidence for genome annotation. 

Any comment or recommendation on this question would be helpful.
Thanks in advance,

**Comment by KatharinaHoff** [comment]
I would definitely discourage you from using lncRNAseq in the same way as
mRNAseq. BRAKER does not by default predict long noncoding RNAs, i.e.
BRAKER would treat it as evidence for protein coding genes if in any way
possible.

Best,

Katharina

**Comment by V-JJ** [comment]
Hello Katharina!

Understood. It is good to know. Many thanks for so fast reply!
Best regards,

Vadim
