### ISSUE TITLE
Unable to run braker using ProtHint-2.6.0

### ISSUE THREAD

**Issue by sunnyEV** [Gaius-Augustus/BRAKER#493]
Hi,
I rerun the braker with ProtHint.

**CMD**
`braker.pl --genome=Aventri.contigs.velvet.cdhit.fa --prot_seq=orthodball.fasta --species=Sp_1 --cores 8 --workingdir=Avelvet1_test --PROTHINT_PATH=/home/sun/data/softwares/evaluation/ProtHint-2.6.0/bin`

**It runs for some time, and this **error** pops up. If I run the example file, it runs smoothly.**

# Wed May 11 18:11:26 2022: Log information is stored in file /DATA/xxx/sun/softwares/BRAKER-2.1.6/scripts/Avelvet1_test/braker.log
#*********
# WARNING: Detected whitespace in fasta header of file /DATA/xxx/sun/softwares/BRAKER-2.1.6/scripts/orthodball.fasta. This may later on cause problems! The pipeline will create a new file without spaces or "|" characters and a genome_header.map file to look up the old and new headers. This message will be suppressed from now on!
#*********
#*********
# WARNING: in file /home/sun/data/softwares/BRAKER-2.1.6/scripts/braker.pl at line 1341
file /DATA/xxx/sun/softwares/BRAKER-2.1.6/scripts/Avelvet1_test/genome.fa contains a highly fragmented assembly (6614381 scaffolds). This may lead to problems when running AUGUSTUS via braker in parallelized mode. You set --cores=8. You should run braker.pl in linear mode on such genomes, though (--cores=1).
#*********
**ERROR in file /home/sun/data/softwares/BRAKER-2.1.6/scripts/braker.pl at line 6586**
Failed to execute: perl /home/sun/data/softwares/genemark/gmes_linux_64_4/gmes_petap.pl --verbose --cores=8 --ES --gc_donor 0.001 --sequence=/DATA/xxx/sun/softwares/BRAKER-2.1.6/scripts/Avelvet1_test/genome.fa  1>/DATA/xxx/sun/softwares/BRAKER-2.1.6/scripts/Avelvet1_test/GeneMark-ES.stdout 2>/DATA/xxx/sun/softwares/BRAKER-2.1.6/scripts/Avelvet1_test/errors/GeneMark-ES.stderr
The most common problem is an expired or not present file ~/.gm_key!

real    10m21.919s
user    8m43.984s
sys     1m34.519s

I don't really understand what's the problem, maybe it's because of fragment assembly (Illumina), suggestions please.

The whole genome sequenced by Illumina Next-seq-500, 151bp RL, PE library, estimate genome coverage -35X
I de novo assembled the genome using 3 assemblers, I check with the different assemblies, its shows same error.

Suggestions please, that I'd be great help.

Thanks
Sunny

**Comment by tomasbruna** [comment]
Hi Sunny,

sorry for the late reply. I see you opened some more recent issues, does it mean you solved this original problem? And also the one in #495?

Tomas

**Comment by sunnyEV** [comment]
Solved.
Best,
Sunny
