### ISSUE TITLE
No space on device in /tmp directory during optimize_augustus.pl command

### ISSUE THREAD

**Issue by marco91sol** [Gaius-Augustus/BRAKER#494]
The file ./braker/errors/optimize_augustus.stderr gives me the following output: 

How can I solve that? 

Error in tempdir() using /tmp/XXXXXXXXXX: Could not create directory /tmp/LEq6SDRWTp: No space left on device at 
/mnt/DATA/home/marcos/anaconda3/envs/maker/lib/site_perl/5.26.2/Parallel/ForkManager.pm line 48.

Can I change the tmpdir()?

**Comment by tomasbruna** [comment]
BRAKER does not have the option to change the tempdir() location.

However, based on [ForkManager's documentation](https://metacpan.org/pod/Parallel::ForkManager), it seems that you can adjust the location by setting the [TMPDIR](https://en.wikipedia.org/wiki/TMPDIR) env variable.
