### ISSUE TITLE
spaln error in BRAKER

### ISSUE THREAD

**Issue by cfz1998** [Gaius-Augustus/BRAKER#496]
When I run the example data. I get a error.

ERROR in file /home/chaofan/software/BRAKER/scripts/startAlign.pl at line 763
failed to execute: /home/chaofan/miniconda3/envs/EDTA/bin/spaln -Q7 -O0 /home/chaofan/software/BRAKER/example/test3/braker/tmp_spaln/genomeX4.fa proteins_addstop.fa > /home/chaofan/software/BRAKER/example/test3/braker/align_spaln/X4.spaln.aln 2>/home/chaofan/software/BRAKER/example/test3/braker/align_spaln/X4.spaln.stderr!

The cmdline is:  braker.pl --cores=32 --genome=../genome.fa --species=test --softmasking --prot_seq=../proteins.fa  --bam=../RNAseq.bam --prg=spaln

spaln version: SPALN version 2.4.0 <191118> 

But when I run "spaln -Q3 -O0 genomeX4.fa proteins_addstop.fa ", it's normal! 
Why? (if -Q[num] num < 3) = normal.  
 -Q#     0:DP; 1-3:HSP-Search; 4-7; Block-Search (3)

And the content in the file[braker/align_spaln/X1.spaln.stderr] is :
Gd:0 No:0 My:256 MS:0 Mb:18241 Tw:0 Tl:500141   0.00 100.00   0.00
: Block table may be destroyed !
![image](https://user-images.githubusercontent.com/60096719/169646032-dc94d058-93d8-47aa-8619-f38f0c815633.png)

**Comment by dcf774967** [comment]
Thank for your reply! 
 BEST!
 Chaofan Zhang

**Comment by fayjustin** [comment]
@cfz1998 Did you find a solution?
I have nearly the same problem: works with Q3 but not Q7.
spaln readme states: 4<=N<=7: Genome mapping and alignment. The genomic sequence must be formatted beforehand.
So, it appears that the genome isn't formatted.

**Comment by KatharinaHoff** [comment]
Please use ProtHint instead of other aligners.

fayjustin ***@***.***> schrieb am Mi. 1. Juni 2022 um 04:36:

**Comment by fayjustin** [comment]
Thanks, I will. I was able to get spaln to run with Q7 on its own, just not using the perl script.
