### ISSUE TITLE
Train a preexisting parameters

### ISSUE THREAD

**Issue by hiroshisuga** [Gaius-Augustus/BRAKER#497]
Is it possible to train a pre-existing parameters?

I am trying to train augustus with a protein hint starting from a pre-existing species (Trichoplax_adherens). For this end I employed "--species Trichoplax_adherens" together with "--useexisting". However, braker.pl seems to have skipped the Augustus training step (only copied the Trichoplax parameters and predict genes by using them). It did not create new parameter files as I expected.

However, the document reads:
"--useexisting: Use the present config and parameter files if they exist for 'species'; will overwrite original parameters if BRAKER performs an AUGUSTUS training."

How do I force braker.pl to perform the Augustus training starting from a preexisting species and overwrite the original parameters?

**Comment by KatharinaHoff** [comment]
Admittedly, we kind of changed course during the development of BRAKER. The --useexisting flag should probably be removed when one of us finds time to do this, but it's tricky in some places.

It makes not difference whether you start a fresh training or train on the basis of an already trained species. All the parameters will be overwritten by etraining. (The optimized metaparameters might not be overwritten if you skip optimize.)

Solution for now:

Rename the old parameters (https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/rename_species.pl), run a fresh training, and then copy the few parameters that you wanted to keep into the new parameter files, manually.
