### ISSUE TITLE
Recommended RNA-Seq coverage for BRAKER1

### ISSUE THREAD

**Issue by skagawa2** [Gaius-Augustus/BRAKER#499]
Hello! I haven't seen this question being asked, but if it has already been answered somewhere, I apologize.

I was wondering if there is a recommended coverage that we should aim for when planning an RNA-seq experiment for BRAKER1. Of course, if this depends on the organism, genome complexity, etc. we can also take that into consideration.

Thanks!

**Comment by KatharinaHoff** [comment]
GeneMark-ET uses all spliced alignments that have a multiplicity/coverage of 10. So having that baseline coverage for a large number of introns helps to get a good training gene set for BRAKER1. (AUGUSTUS will use all spliced alignments.)

Other than that, have a look at the VARUS paper. It does not directly answer your question, but shows examples of certain amounts of RNA-Seq data in context with intron accuracy (e.g. Fig 3).
