### ISSUE TITLE
 BRAKER error on call: parse_ET.pl 

### ISSUE THREAD

**Issue by Edison2021** [Gaius-Augustus/BRAKER#5]
I'm trying the BRAKER v2.1.0, but it stops at the GeneMark-ET step. 
Here's the exact error:
error, file not found ~/src/gm_et_linux_64/gmes_petap/parse_ET.pl: set.out
error on call: ~/src/gm_et_linux_64/gmes_petap/parse_ET.pl --section ET_A --cfg  ~/src/BRAKER2/BRAKER_v2.1.0/example/run.cfg  --v 
However, if i run ~/src/gm_et_linux_64/gmes_petap/parse_ET.pl, it will work. 

Any help or suggestions would be appreciated! 

PS: where can i downloade the BRAKER v1

**Comment by KatharinaHoff** [comment]
Please update to BRAKER 2.1.2 (https://github.com/Gaius-Augustus/BRAKER/releases/tag/v2.1.2)

The first BRAKER versions are still archieved at http://bioinf.uni-greifswald.de/augustus/binaries/old/ but I really don't recommend using old versions. The commands for calling tools from within BRAKER have changed over time. Also, the old versions contained numerous bugs that have long been fixed in the current version.

Do you observe the problem (in current version of BRAKER) when using the example data set, too?

**Comment by Edison2021** [comment]
I tried the BRAKER v2.1.0 using the example data set from current version of BRAKER. I will update and try again next Monday. I will let you know what will happen.

**Comment by Edison2021** [comment]
I tried the latest one and the previous error disappear. Thanks!

**Comment by Edison2021** [comment]
When i tried my own data, another error occurred. The output of bam2hints  --intronsonly is empty. I checked my bam file, which has 92% mapped ratio. Also i am very sure lots of introns in the genome.
Any help or suggestions would be appreciated!

**Comment by KatharinaHoff** [comment]
Excellent!

**Comment by tiramisutes** [comment]
Hi,
I use the latest BRAKER 2.1.2 and have the same stder in gmes.log file.

```
/public/hom/software/gm_et_linux_64/gmes_petap/gmes_petap.pl : [Mon Oct 22 10:17:59 2018] /public/home/software/gm_et_linux_64/gmes_petap/parse_ET.pl --section ET_A --cfg  /public/home/BRAKER2/GeneMark-ETP/run.cfg  --v
/public/home/software/gm_et_linux_64/gmes_petap/gmes_petap.pl : [Mon Oct 22 10:17:59 2018] error
```

**Comment by tiramisutes** [comment]
Hi,
I use the latest BRAKER 2.1.2 and have the same stder in gmes.log file.

```
/public/hom/software/gm_et_linux_64/gmes_petap/gmes_petap.pl : [Mon Oct 22 10:17:59 2018] /public/home/software/gm_et_linux_64/gmes_petap/parse_ET.pl --section ET_A --cfg  /public/home/BRAKER2/GeneMark-ETP/run.cfg  --v
/public/home/software/gm_et_linux_64/gmes_petap/gmes_petap.pl : [Mon Oct 22 10:17:59 2018] error
```

**Comment by KatharinaHoff** [comment]
Can you please give some more information? Your post does not contain the actual error, it does not contain the braker call.

**Comment by ersgupta** [comment]
Hi Katharina,

I get the same error using v2.1.2. Any help would be great.

```
concatenate predictions: /<path>/gene_prediction/braker/braker/<spec>/GeneMark-ET/run/ET_A_1
training level ET_A: /<path>/gene_prediction/braker/braker/<spec>/GeneMark-ET/run/ET_A_1
error, file not found /<path>/apps/genemark/gm_et_linux_64/gmes_petap/parse_ET.pl: set.out
error on call: /<path>/apps/genemark/gm_et_linux_64/gmes_petap/parse_ET.pl --section ET_A --cfg  /<path>/gene_prediction/braker/braker/<spec>/GeneMark-ET/run.cfg  --v
```

**Comment by ersgupta** [comment]
Got it sorted. There are no files in hmmout folder and upon inspecting a bit I found out that genemark's 400-day license period had ended.

**Comment by KatharinaHoff** [comment]
Ok, that's good to know. I will close this issue, then.
