### ISSUE TITLE
Random fails with multiple BAM files

### ISSUE THREAD

**Issue by gusevfe** [Gaius-Augustus/BRAKER#50]
I run BRAKER with multiple BAM files (separated forward and reverse strand) and protein evidence. Several times it printed with a message like this:
```
WARNING: Format of hintsfile /data2/results2/gusev/jellyfish/annotation/braker2/braker/genemark_hintsfile.gff is incorrect in the last column, possibly src=tag is missing!
```
And later GeneMark-ETP fails with this or similar message:
```
error, unexpected ID format found on line: scaffold_2158        b2h     intron  1173736 1173804 1       -       i=4;src=E      scaffold_2158   b2h     intron  1173736 1173804 998     -       .       mult=998;pri=4;src=E
```
Sometimes restarting from scratch helps, some times it does not.

It seems like some lines in `genemark_hintsfile.gff` are garbled on merge, because 
individual `bam2hints.temp.*.gff` seem to be correct.

I noticed that parallel processing in `make_rnaseq_hints` routine involves writting into the same file from different threads. See this line:
https://github.com/Gaius-Augustus/BRAKER/blob/e117150b8ad66ecf7cd5828c7f7fe476a4a8c191/scripts/braker.pl#L4504
After changing line 4473 from
```
 my $pj = new Parallel::ForkManager($CPU);
```
to
```
 my $pj = new Parallel::ForkManager(1);
```
the error goes away (however, I did not do any elaborate testing). Obvisously, this is a temporary fix and the error (if I am right about the cause) should be fixed in a different way.

Hope this helps someone.

**Comment by KatharinaHoff** [comment]
Thank you for spotting this problem. I always join my hints from multiple bam files prior running BRAKER and thus never noticed. I hope this issue is fixed with commit  https://github.com/Gaius-Augustus/BRAKER/commit/51155e5d67762e83314eaf95663d9666b4b28247 , which essentially takes the concatenation out of the parallel process.
