### ISSUE TITLE
Remove redundancy in braker.gtf

### ISSUE THREAD

**Issue by marco91sol** [Gaius-Augustus/BRAKER#501]
Hi, I launch BRAKER. Giving BUSCO analysis on the proteins deriving from braker.gtf , I noticed a strong duplication even due to redundancy. How can I remove it? An example is shown below in the picture. 

![image](https://user-images.githubusercontent.com/42739946/174249421-8bb8364b-078c-481b-81c2-ce570a2cbcb8.png)

Best regards,
Marco

**Comment by tomasbruna** [comment]
Hi Marco,

you can use `augustus.hints.gtf` as your main BRAKER output. More details here https://github.com/Gaius-Augustus/BRAKER#output-of-braker.

Any remaining perceived BUSCO redundancy may be caused by alternative isoforms.

Best,
Tomas
