### ISSUE TITLE
Long-Read Integration Using BRAKER, GeneMarkS-T and TSEBRA

### ISSUE THREAD

**Issue by amvarani** [Gaius-Augustus/BRAKER#502]
Hi there,
I'm trying to use the long-read integration but at the stringtie2fa.py stage the final mRNA file is empty, and I can't continue. Any idea? 

Here is the head of my cupcake.collapsed.gff file:

chr1	PacBio	transcript	67799	73573	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	67799	68278	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	68394	68487	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	68675	68755	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	68835	68880	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	69150	69235	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	69329	69556	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	69655	69693	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	69778	69867	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	70146	70208	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	70288	70357	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	70466	70512	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	70606	70668	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	70764	70814	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	70912	70995	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	71185	71249	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	71356	71412	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	71498	71615	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	71723	71773	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	71885	71971	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	72218	72297	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	72955	73111	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	exon	73288	73573	.	+	.	transcript_id "PB.1.1"; gene_id "PB.1";
chr1	PacBio	transcript	67801	73573	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	67801	68278	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	68394	68487	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	68675	68755	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	68835	68880	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	69150	69235	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	69329	69556	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	69752	69867	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	70146	70208	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	70288	70357	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	70466	70512	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	70606	70668	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	70764	70814	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";
chr1	PacBio	exon	70912	70995	.	+	.	transcript_id "PB.1.2"; gene_id "PB.1";

**Comment by KatharinaHoff** [comment]
I am sorry that we did not help you out on this. We have no idea why the file was empty. Sorry.
