### ISSUE TITLE
Does the Braker.pl works with translation_table 2?

### ISSUE THREAD

**Issue by sunnyEV** [Gaius-Augustus/BRAKER#503]
Hi ,

Can we run Braker.pl with translation_table = **2**, for annotating  fish genomes.

Suggestions please.

**Comment by KatharinaHoff** [comment]
No, please don’t. Changing translation table is not implemented for
GeneMark.

Kevin ***@***.***> schrieb am Do. 23. Juni 2022 um 20:02:

**Comment by sunnyEV** [comment]
Then how do I annotate the fish genomes ?

**Comment by KatharinaHoff** [comment]
I honestly think fish is a eukaryotic genome that has translation table 1.

Kevin ***@***.***> schrieb am Do. 23. Juni 2022 um 20:04:

**Comment by sunnyEV** [comment]
Its a vertebrate = translation table 2 ?

**Comment by KatharinaHoff** [comment]
Vertebrates are table 1.

Kevin ***@***.***> schrieb am Do. 23. Juni 2022 um 20:15:
