### ISSUE TITLE
[Execution error] Failed to execute: perl /home/gmes_linux_64_4/gmes_petap.pl

### ISSUE THREAD

**Issue by prawnseq** [Gaius-Augustus/BRAKER#504]
Hello, 

I tried to install braker2 and test run it using the example data `braker.pl --genome genome.fa --prot_seq proteins.fa --softmasking --cores 12` , it showed me this error:

> Use of uninitialized value $gLocus in hash element at /home/cml_server/BRAKER/scripts/braker.pl line 1327, <GENOME> line 1.
Use of uninitialized value $gLocus in hash element at /home/cml_server/BRAKER/scripts/braker.pl line 1327, <GENOME> line 1.
......
Use of uninitialized value $gLocus in hash element at /home/cml_server/BRAKER/scripts/braker.pl line 1330, <GENOME> line 305.
Use of uninitialized value $gLocus in hash element at /home/cml_server/BRAKER/scripts/braker.pl line 1330, <GENOME> line 305.
ERROR in file /home/cml_server/BRAKER/scripts/braker.pl at line 6595
Failed to execute: perl /home/cml_server/gmes_linux_64_4/gmes_petap.pl --verbose --cores=12 --ES --gc_donor 0.001 --sequence=/home/cml_server/Desktop/Nath/BRAKER2/braker/genome.fa  --soft_mask auto 1>/home/cml_server/Desktop/Nath/BRAKER2/braker/GeneMark-ES.stdout 2>/home/cml_server/Desktop/Nath/BRAKER2/braker/errors/GeneMark-ES.stderr
The most common problem is an expired or not present file ~/.gm_key!

I checked theGeneMark-ES.stderr and it had the following:

>error, unexpected letter found on line 135711

I installed all required softwares manually using conda environment for the Perl modules.
All of mandatory programs were able to execute separately.

So far I checked:
GeneMark-EX with `check_install.bash`, it passed
ProtHint with `prothint.py genome.fasta proteins.fasta --geneSeeds genemark.gtf --workdir test`, also passed

I tried to install it on another conda environment with conda's version of Braker2, it also did not work.

If anyone has any suggestions ,it would be very much appreciated.
Please let me know if there's any information needed to fix this issues.

Best regards,
Phongthana

**UPDATE**

I explored the issue further by running `perl gmes_petap.pl --verbose --cores=12 --ES --gc_donor 0.001 --sequence=genome.fa  --soft_mask auto` separately from Braker2. It also showed the same error of:
>error, unexpected letter found on line 135711

So, I looked at one of the output files `data/dna.fna`. There was unexpected letters at the line 135711 as follow:

> \>67645_dna
NTCAN\B0TNNNTNATACTNATTNNTNNN

I can't figure out where this `/B0` letters came from, but it seems to be the culprit.

**Comment by tomasbruna** [comment]
Interesting, I've never seen a problem like this. What is the system you are running the example on? Also, were you able to run BRAKER with your own genome?

**Comment by prawnseq** [comment]
Hello,
Thank you for the reply !! The issue seems to be fixed. I apologize for not giving the update.
As far as I know, the cause of this issue was either how I download the example file from Github, or some package related to text manipulation get updates.

My system is Lenovo Workstation operated on Ubuntu 20.04.

If this issue happens to anyone, try do the trial run on different .fa files (maybe redownloaded it in different way) or update all of the software/packages on your system !!

Best regards,
Phongthana

**Comment by tomasbruna** [comment]
Thanks for the update!
