### ISSUE TITLE
In the example, inconsistent Reference IDs between genome.fa and RNAseq.bam

### ISSUE THREAD

**Issue by methylome** [Gaius-Augustus/BRAKER#507]
I installed 2.1.6 and downloaded RNA-seq.bam from http://bioinf.uni-greifswald.de/bioinf/braker/RNAseq.bam.
File genome.fa and RNAseq.bam have different IDs.

grep '^>' genome.fa 
>X1
>X2
>X3
>X4
>X5
>X6
>X7
>X8

samtools view -h RNAseq.bam | h
@HD     VN:1.4
@SQ     SN:2R   LN:12000000
@PG     ID:STAR PN:STAR VN:STAR_2.5.4b  CL:STAR   --runThreadN 10   --genomeDir star_genome   --readFilesIn /nas-hs/projs/braker/topaz/storage3/braker/Drosophila_melanogaster/arx/SRR023505_1.fastq   /nas-hs/projs/braker/topaz/storage3/braker/Drosophila_melanogaster/arx/SRR023505_2.fastq   
@CO     user command line: STAR --genomeDir star_genome --readFilesIn /nas-hs/projs/braker/topaz/storage3/braker/Drosophila_melanogaster/arx/SRR023505_1.fastq /nas-hs/projs/braker/topaz/storage3/braker/Drosophila_melanogaster/arx/SRR023505_2.fastq --runThreadN 10
SRR023505.257023        99      2R      10133013        255     76M     =       10133122        185     CGAGAAGGGTGTGCCCTTCCGACTGCAAATTGAAACCTATATAGAAAACACAAACAGTGCCACCGCCAGCGGCTCG      BBB@BBBABA>B=BABBBBAAAABBABAACB@=BB?BCCCBCBABB@C@BACBB@@?6;>@B?A7?4=2:427>5#      NH:i:1  HI:i:1  AS:i:150        nM:i:0
SRR023505.257023        147     2R      10133122        255     76M     =       10133013        -185    AGCGGAAGCAGTGGCTCCGCTGCACCAGCATCTCCGGAACGGACACCCAGTGCCGGCAGCAATGGTAAACAGGCGG      ######################52038057;40;>@;=:6;:5588?;ABBA89ABBB?>BBBBBBBC@BCCCACB      NH:i:1  HI:i:1  AS:i:150        nM:i:0
SRR023505.257034        99      2R      8430781 3       76M     =       8430889 184     GGACTCCAGCCAGGCGACGGCGAGGGCGATGGCCTCTGGGATTGGAGGAGGAGTGGGGATCCAGGCTCCCGAGGGC      ABA>BBA@?A=AAA>?A6A==B=B?A=B=;7;44A6@=;77=AA>:=A4>:4=9202=9-,.:771>&..93916#    NH:i:2  HI:i:1    AS:i:146        nM:i:2
SRR023505.257034        147     2R      8430889 3       76M     =       8430781 -184    CTCTACGTGCTCGCCCTCGGGTGAGATCCAGCCGAAGTTGCCGTGGATGTTGCCATGGGCATCACCGCTGGCGGCC      ##################16+6997=5?A@5@<>A@9@A;9>;AA>A?AB@AB?<AAAABA@@BBBABBAABABA@    NH:i:2  HI:i:1    AS:i:146        nM:i:2
SRR023505.257034        355     2R      8430781 3       76M     =       8434235 3530    GGACTCCAGCCAGGCGACGGCGAGGGCGATGGCCTCTGGGATTGGAGGAGGAGTGGGGATCCAGGCTCCCGAGGGC      ABA>BBA@?A=AAA>?A6A==B=B?A=B=;7;44A6@=;77=AA>:=A4>:4=9202=9-,.:771>&..93916#    NH:i:2  HI:i:2    AS:i:145        nM:i:2

**Comment by methylome** [comment]
Got the right genome.fa from 2.1.2-tag1.

**Comment by tomasbruna** [comment]
@methylome, did you find the link to http://topaz.gatech.edu/GeneMark/Braker/RNAseq.bam in BRAKER's documentation, and if so, at which location?

The current documentation for v2.1.6 should link to http://topaz.gatech.edu/GeneMark/Braker/RNAseq.bam, which has the BAM with correct IDs.

**Comment by methylome** [comment]
@tomasbruna I tried to download it, but failed.

wget http://topaz.gatech.edu/GeneMark/Braker/RNAseq.bam
--2022-09-06 16:32:00--  http://topaz.gatech.edu/GeneMark/Braker/RNAseq.bam
Length: 171459517 (164M) [application/octet-stream]
Saving to: “RNAseq.bam”

45% [=======================================>                                                 ] 77,256,264  --.-K/s  eta 42s

**Comment by tomasbruna** [comment]
This is probably just a connection issue, try downloading again.

**Comment by methylome** [comment]
I've tried several times, but it didn't work.

**Comment by tomasbruna** [comment]
Strange, still works fine for me. I uploaded it here: https://www.dropbox.com/s/z8g4lp7a6caq5ym/RNAseq.bam?dl=0

**Comment by methylome** [comment]
I got it. Thanks a lot.
