### ISSUE TITLE
Error on running test1.sh

### ISSUE THREAD

**Issue by methylome** [Gaius-Augustus/BRAKER#508]
I ran test1.sh in the example and got core dumped.

```
>cat test1.log
# Fri Jul 29 10:58:50 2022: Log information is stored in file /ddn/work/cjh/test/braker-2.1.6/tests/test1/braker.log
sh: line 1: 126276 Segmentation fault      (core dumped) /app/redhat6/augustus/augustus-3.4.0/bin/etraining --species=Sp_1 --AUGUSTUS_CONFIG_PATH=/app/redhat6/augustus/augustus-3.4.0/config /ddn/work/cjh/test/braker-2.1.6/tests/test1/train.f.gb > /ddn/work/cjh/test/braker-2.1.6/tests/test1/gbFilterEtraining.stdout 2> /ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/gbFilterEtraining.stderr
ERROR in file /app/redhat6/BRAKER/BRAKER-2.1.6/scripts/braker.pl at line 7468
Failed to execute: /app/redhat6/augustus/augustus-3.4.0/bin/etraining --species=Sp_1 --AUGUSTUS_CONFIG_PATH=/app/redhat6/augustus/augustus-3.4.0/config /ddn/work/cjh/test/braker-2.1.6/tests/test1/train.f.gb 1> /ddn/work/cjh/test/braker-2.1.6/tests/test1/gbFilterEtraining.stdout 2>/ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/gbFilterEtraining.stderr

real  73m2.617s
user  20m38.514s
sys   295m9.583s
```

```
>cat test1/braker.log
#**********************************************************************************
#                               BRAKER CONFIGURATION                               
#**********************************************************************************
# BRAKER CALL: /app/redhat6/BRAKER/BRAKER-2.1.6/scripts/braker.pl --genome=../genome.fa --bam=../RNAseq.bam --softmasking --workingdir=test1 --cores 8 --gm_max_intergenic 10000
# Fri Jul 29 10:58:49 2022: braker.pl version 2.1.6
# Fri Jul 29 10:58:49 2022: Creating directory /ddn/work/cjh/test/braker-2.1.6/tests/test1.
# Fri Jul 29 10:58:49 2022: Configuring of BRAKER for using external tools...
# Fri Jul 29 10:58:49 2022: Found environment variable $AUGUSTUS_CONFIG_PATH. Setting $AUGUSTUS_CONFIG_PATH to /app/redhat6/augustus/augustus-3.4.0/config
# Fri Jul 29 10:58:49 2022: Found environment variable $AUGUSTUS_BIN_PATH. Setting $AUGUSTUS_BIN_PATH to /app/redhat6/augustus/augustus-3.4.0/bin
# Fri Jul 29 10:58:49 2022: Found environment variable $AUGUSTUS_SCRIPTS_PATH. Setting $AUGUSTUS_SCRIPTS_PATH to /app/redhat6/augustus/augustus-3.4.0/scripts
# Fri Jul 29 10:58:49 2022: Found environment variable $PYTHON3_PATH. Setting $PYTHON3_PATH to /app/redhat6/anaconda3/bin
# Fri Jul 29 10:58:49 2022: Found environment variable $GENEMARK_PATH. Setting $GENEMARK_PATH to /app/redhat6/gmes/GeneMark-4.64_lic
# Fri Jul 29 10:58:49 2022: Found environment variable $BAMTOOLS_PATH. Setting $BAMTOOLS_PATH to /app/redhat6/bamtools/bamtools-2.5.1/bin
# Fri Jul 29 10:58:49 2022: Found environment variable $SAMTOOLS_PATH. Setting $SAMTOOLS_PATH to /app/redhat6/samtools/samtools-1.14/bin
# Fri Jul 29 10:58:49 2022: Found environment variable $DIAMOND_PATH. Setting $DIAMOND_PATH to /app/redhat6/diamond/diamond-0.9.24
# Fri Jul 29 10:58:49 2022: Found environment variable $CDBTOOLS_PATH. Setting $CDBTOOLS_PATH to /app/redhat6/cdbfasta/cdbfasta-1.00
#*********
# IMPORTANT INFORMATION: no species for identifying the AUGUSTUS  parameter set that will arise from this BRAKER run was set. BRAKER will create an AUGUSTUS parameter set with name Sp_1. This parameter set can be used for future BRAKER/AUGUSTUS prediction runs for the same species. It is usually not necessary to retrain AUGUSTUS with novel extrinsic data if a high quality parameter set already exists.
#*********
#**********************************************************************************
#                               CREATING DIRECTORY STRUCTURE                       
#**********************************************************************************
# Fri Jul 29 10:58:50 2022: creating file that contains citations for this BRAKER run at /ddn/work/cjh/test/braker-2.1.6/tests/test1/what-to-cite.txt...
# Fri Jul 29 10:58:50 2022: create working directory /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET.
mkdir /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET
# Fri Jul 29 10:58:50 2022: create working directory /ddn/work/cjh/test/braker-2.1.6/tests/test1/species
mkdir /ddn/work/cjh/test/braker-2.1.6/tests/test1/species
# Fri Jul 29 10:58:50 2022: create working directory /ddn/work/cjh/test/braker-2.1.6/tests/test1/errors
mkdir /ddn/work/cjh/test/braker-2.1.6/tests/test1/errors
# Fri Jul 29 10:58:50 2022: changing into working directory /ddn/work/cjh/test/braker-2.1.6/tests/test1
cd /ddn/work/cjh/test/braker-2.1.6/tests/test1
# Fri Jul 29 10:58:50 2022: Creating parameter template files for AUGUSTUS with new_species.pl
# Fri Jul 29 10:58:50 2022: new_species.pl will create parameter files for species Sp_1 in /app/redhat6/augustus/augustus-3.4.0/config/species/Sp_1
perl /app/redhat6/augustus/augustus-3.4.0/scripts/new_species.pl --species=Sp_1 --AUGUSTUS_CONFIG_PATH=/app/redhat6/augustus/augustus-3.4.0/config 1> /dev/null 2>/ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/new_species.stderr
# Fri Jul 29 10:58:50 2022: check_fasta_headers(): Checking fasta headers of file /ddn/work/cjh/test/braker-2.1.6/tests/../genome.fa
#**********************************************************************************
#                               PROCESSING HINTS                                   
#**********************************************************************************
# Fri Jul 29 10:58:50 2022: Converting bam files to hints
# Fri Jul 29 10:58:50 2022: Checking bam headers
# Fri Jul 29 10:58:50 2022: create header file /ddn/work/cjh/test/braker-2.1.6/tests/test1/RNAseq_header.sam
/app/redhat6/bamtools/bamtools-2.5.1/bin/bamtools header -in /ddn/work/cjh/test/braker-2.1.6/tests/../RNAseq.bam > /ddn/work/cjh/test/braker-2.1.6/tests/test1/RNAseq_header.sam
# Fri Jul 29 10:58:50 2022: Deleting SAM header file /ddn/work/cjh/test/braker-2.1.6/tests/test1/RNAseq_header.sam (will not be needed from here on)
# Fri Jul 29 10:58:50 2022: Deleting /ddn/work/cjh/test/braker-2.1.6/tests/test1/RNAseq_new_header.sam
# Fri Jul 29 10:58:50 2022: make hints from BAM file /ddn/work/cjh/test/braker-2.1.6/tests/../RNAseq.bam
/app/redhat6/augustus/augustus-3.4.0/bin/bam2hints --intronsonly --in=/ddn/work/cjh/test/braker-2.1.6/tests/../RNAseq.bam --out=/ddn/work/cjh/test/braker-2.1.6/tests/test1/bam2hints.temp.0.gff 1> /ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/bam2hints.0.stdout 2>/ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/bam2hints.0.stderr
# Fri Jul 29 10:59:05 2022: add hints from BAM file /ddn/work/cjh/test/braker-2.1.6/tests/../RNAseq.bam to hints file
cat /ddn/work/cjh/test/braker-2.1.6/tests/test1/bam2hints.temp.0.gff >>/ddn/work/cjh/test/braker-2.1.6/tests/test1/hintsfile.temp.gff
# Fri Jul 29 10:59:05 2022: Checking for hints of src=C and with grp tags that should not be joined according to multiplicity
# Fri Jul 29 10:59:05 2022: Joining hints that are identical (& from the same source) into multiplicity hints (input file /ddn/work/cjh/test/braker-2.1.6/tests/test1/tmp_merge_hints.gff)
# Fri Jul 29 10:59:05 2022: sort hints of type rnaseq
cat /ddn/work/cjh/test/braker-2.1.6/tests/test1/tmp_merge_hints.gff | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -n -k 3,3 | sort -s -k 1,1 >/ddn/work/cjh/test/braker-2.1.6/tests/test1/hints.rnaseq.temp.sort.gff
# Fri Jul 29 10:59:05 2022: join multiple hints
perl /app/redhat6/augustus/augustus-3.4.0/scripts/join_mult_hints.pl </ddn/work/cjh/test/braker-2.1.6/tests/test1/hints.rnaseq.temp.sort.gff >/ddn/work/cjh/test/braker-2.1.6/tests/test1/tmp_merge_hints.gff 2>/ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/join_mult_hints.rnaseq.stderr
mv /ddn/work/cjh/test/braker-2.1.6/tests/test1/tmp_merge_hints.gff /ddn/work/cjh/test/braker-2.1.6/tests/test1/hintsfile.temp.gff
# Fri Jul 29 10:59:06 2022: filter introns, find strand and change score to 'mult' entry
perl /app/redhat6/BRAKER/BRAKER-2.1.6/scripts/filterIntronsFindStrand.pl /ddn/work/cjh/test/braker-2.1.6/tests/test1/genome.fa /ddn/work/cjh/test/braker-2.1.6/tests/test1/hintsfile.temp.gff --score 1>>/ddn/work/cjh/test/braker-2.1.6/tests/test1/hintsfile.gff 2>/ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/filterIntronsFindStrand.stderr
# Fri Jul 29 10:59:06 2022: rm /ddn/work/cjh/test/braker-2.1.6/tests/test1/hintsfile.temp.gff
# Fri Jul 29 10:59:06 2022: Preparing hints for running GeneMark
# Fri Jul 29 10:59:06 2022: Filtering intron hints for GeneMark from /ddn/work/cjh/test/braker-2.1.6/tests/test1/hintsfile.gff...
cat /ddn/work/cjh/test/braker-2.1.6/tests/test1/genemark_hintsfile.gff.rnaseq | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -k 3,3 | sort -s -k 1,1 | /app/redhat6/augustus/augustus-3.4.0/scripts/join_mult_hints.pl > /ddn/work/cjh/test/braker-2.1.6/tests/test1/genemark_hintsfile.gff.rnaseq.tmp
mv /ddn/work/cjh/test/braker-2.1.6/tests/test1/genemark_hintsfile.gff.rnaseq.tmp /ddn/work/cjh/test/braker-2.1.6/tests/test1/genemark_hintsfile.gff
#**********************************************************************************
#                              RUNNING GENEMARK-EX                                 
#**********************************************************************************
# Fri Jul 29 11:02:27 2022: Checking whether file /ddn/work/cjh/test/braker-2.1.6/tests/test1/genemark_hintsfile.gff contains enough hints and sufficient multiplicity information...
# Fri Jul 29 11:02:27 2022: Executing GeneMark-ET
# Fri Jul 29 11:02:27 2022: changing into GeneMark-ET directory /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET
cd /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET
# Fri Jul 29 11:02:27 2022: Executing gmes_petap.pl
perl /app/redhat6/gmes/GeneMark-4.64_lic/gmes_petap.pl --verbose --sequence=/ddn/work/cjh/test/braker-2.1.6/tests/test1/genome.fa --ET=/ddn/work/cjh/test/braker-2.1.6/tests/test1/genemark_hintsfile.gff --cores=8 --gc_donor 0.001 --soft_mask auto --max_intergenic=10000 1>/ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET.stdout 2>/ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/GeneMark-ET.stderr
# Fri Jul 29 12:11:46 2022: change to working directory /ddn/work/cjh/test/braker-2.1.6/tests/test1
cd /ddn/work/cjh/test/braker-2.1.6/tests/test1
# Fri Jul 29 12:11:46 2022: Filtering output of GeneMark for generating training genes for AUGUSTUS
# Fri Jul 29 12:11:46 2022: Checking whether hintsfile contains single exon CDSpart hints or start/stop hints
# Fri Jul 29 12:11:46 2022: sorting GeneMark predictions in /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.gtf
/app/redhat6/anaconda3/bin/python3 /app/redhat6/BRAKER/BRAKER-2.1.6/scripts/sortGeneMark.py /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.gtf > /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.gtf.sorted 2> /ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/sortGeneMark.err
mv /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.gtf.sorted /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.gtf
# Fri Jul 29 12:11:47 2022: filtering GeneMark genes by intron hints
perl /app/redhat6/BRAKER/BRAKER-2.1.6/scripts/filterGenemark.pl --genemark=/ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.gtf --hints=/ddn/work/cjh/test/braker-2.1.6/tests/test1/hintsfile.gff --randomSeed=1 1>/ddn/work/cjh/test/braker-2.1.6/tests/test1/filterGenemark.stdout 2>/ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/filterGenemark.stderr
# Fri Jul 29 12:11:47 2022: Ensuring at least 4000 genes in training file 
/app/redhat6/anaconda3/bin/python3 /app/redhat6/BRAKER/BRAKER-2.1.6/scripts/ensure_n_training_genes.py --goodGenes /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.f.good.gtf --badGenes /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.f.bad.gtf --N 4000 1>/ddn/work/cjh/test/braker-2.1.6/tests/test1/ensure_min_n_training_genes.stdout 2>/ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/ensure_min_n_training_genes.stderr
#Fri Jul 29 12:11:47 2022: downsampling good genemark genes according to poisson distribution with Lambda 2:
perl /app/redhat6/BRAKER/BRAKER-2.1.6/scripts/downsample_traingenes.pl --in_gtf=/ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.f.good.gtf --out_gtf=/ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.d.gtf --lambda=2 1> /ddn/work/cjh/test/braker-2.1.6/tests/test1/downsample_traingenes.log 2> /ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/downsample_traingenes.err
#**********************************************************************************
#                               TRAIN AUGUSTUS                                     
#**********************************************************************************
# Fri Jul 29 12:11:47 2022: training AUGUSTUS
# Fri Jul 29 12:11:47 2022: creating softlink from /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.gtf to /ddn/work/cjh/test/braker-2.1.6/tests/test1/traingenes.gtf.
ln -s /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.gtf /ddn/work/cjh/test/braker-2.1.6/tests/test1/traingenes.gtf
# Fri Jul 29 12:11:47 2022: Converting gtf file /ddn/work/cjh/test/braker-2.1.6/tests/test1/traingenes.gtf to genbank file
# Fri Jul 29 12:11:47 2022: Computing flanking region size for AUGUSTUS training genes
# Fri Jul 29 12:11:47 2022: create genbank file /ddn/work/cjh/test/braker-2.1.6/tests/test1/train.gb
perl /app/redhat6/augustus/augustus-3.4.0/scripts/gff2gbSmallDNA.pl /ddn/work/cjh/test/braker-2.1.6/tests/test1/traingenes.gtf /ddn/work/cjh/test/braker-2.1.6/tests/test1/genome.fa 1939 /ddn/work/cjh/test/braker-2.1.6/tests/test1/train.gb 2>/ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/traingenes.gtf_gff2gbSmallDNA.stderr
#*********
# INFORMATION: the size of flanking region used in this BRAKER run is 1939. You might need this value if you later add a UTR training on top of an already existing BRAKER run.
#*********
# Fri Jul 29 12:11:51 2022: Genbank format file /ddn/work/cjh/test/braker-2.1.6/tests/test1/train.gb contains 1028 genes.
#  Fri Jul 29 12:11:51 2022: concatenating good and downsampled GeneMark training genes to /ddn/work/cjh/test/braker-2.1.6/tests/test1/good_genes.lst.
cat /ddn/work/cjh/test/braker-2.1.6/tests/test1/GeneMark-ET/genemark.d.gtf > /ddn/work/cjh/test/braker-2.1.6/tests/test1/good_genes.lst
# Fri Jul 29 12:11:51 2022: Filtering train.gb for "good" mRNAs:
perl /app/redhat6/augustus/augustus-3.4.0/scripts/filterGenesIn_mRNAname.pl /ddn/work/cjh/test/braker-2.1.6/tests/test1/good_genes.lst /ddn/work/cjh/test/braker-2.1.6/tests/test1/train.gb > /ddn/work/cjh/test/braker-2.1.6/tests/test1/train.f.gb 2>/ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/filterGenesIn_mRNAname.stderr
# Fri Jul 29 12:11:52 2022: Genbank format file /ddn/work/cjh/test/braker-2.1.6/tests/test1/train.f.gb contains 702 genes.
# Fri Jul 29 12:11:52 2022: Running etraining to catch gene structure inconsistencies:
/app/redhat6/augustus/augustus-3.4.0/bin/etraining --species=Sp_1 --AUGUSTUS_CONFIG_PATH=/app/redhat6/augustus/augustus-3.4.0/config /ddn/work/cjh/test/braker-2.1.6/tests/test1/train.f.gb 1> /ddn/work/cjh/test/braker-2.1.6/tests/test1/gbFilterEtraining.stdout 2>/ddn/work/cjh/test/braker-2.1.6/tests/test1/errors/gbFilterEtraining.stderr

```
Could you let me know what the problem is?
Thanks in advance.

**Comment by KatharinaHoff** [comment]
Are you running the latest code from Github for both Braker and Augustus?
If not, please git clone, compile Augustus and try again.

Justin Choi ***@***.***> schrieb am Fr. 29. Juli 2022 um
08:02:

**Comment by piroyon** [comment]
I am encountering the same error.

braker.pl --genome=mygenome.fasta --species=My_species --bam=my.sorted.bam --workingdir=braker --softmasking --UTR=on --cores=40

This command creates a "My_species" directory in ${AUGUSTUS_CONFIG_PATH}/species.  But the directory is gone when the program stops.

> cat gbFilterEtraining.stderr 
Could not find the config file /home/XXX/augustus_config/species/My_species/My_species_parameters.cfg.
 Looking for My_species_parameters.cfg in the configuration directory instead ... not found.

> cat gbFilterEtraining.stdout 
Species-specific configuration files not found in /home/XXX/augustus_config/species/. Type "augustus --species=help" to see available species.

I am using Augustus and braker downloaded from Github on 14th Jul.
Thank you in advance.

**Comment by methylome** [comment]
@KatharinaHoff I used release 2.1.6. Should I use git clone?

**Comment by KatharinaHoff** [comment]
Yes, please use git clone for both Augustus and Braker to confirm.

Justin Choi ***@***.***> schrieb am Di. 2. Aug. 2022 um 02:41:

**Comment by methylome** [comment]
I used git clone for braker and augustus, but still got the error.

> cat test1.log
# Wed Aug 10 14:50:38 2022: Log information is stored in file /ddn/work/cjh/test/braker-20220128/tests/test1/braker.log
sh: line 1: 146169 Segmentation fault      (core dumped) /app/redhat6/augustus/augustus-20220316/bin/etraining --species=Sp_1 --AUGUSTUS_CONFIG_PATH=/app/redhat6/augustus/augustus-20220316/config /ddn/work/cjh/test/braker-20220128/tests/test1/train.f.gb > /ddn/work/cjh/test/braker-20220128/tests/test1/gbFilterEtraining.stdout 2> /ddn/work/cjh/test/braker-20220128/tests/test1/errors/gbFilterEtraining.stderr
ERROR in file /app/redhat6/BRAKER/BRAKER-20220128/scripts/braker.pl at line 7493
Failed to execute: /app/redhat6/augustus/augustus-20220316/bin/etraining --species=Sp_1 --AUGUSTUS_CONFIG_PATH=/app/redhat6/augustus/augustus-20220316/config /ddn/work/cjh/test/braker-20220128/tests/test1/train.f.gb 1> /ddn/work/cjh/test/braker-20220128/tests/test1/gbFilterEtraining.stdout 2>/ddn/work/cjh/test/braker-20220128/tests/test1/errors/gbFilterEtraining.stderr

real  5m44.471s
user  19m30.830s
sys   0m23.691s

**Comment by methylome** [comment]
@KatharinaHoff Could you have time to guide me how to resolve this issue?

**Comment by MarioStanke** [comment]
This appears to be an error in AUGUSTUS.
If you could upload the input files to the command that crashes:
 /app/redhat6/augustus/augustus-20220316/bin/etraining --species=Sp_1
--AUGUSTUS_CONFIG_PATH=/app/redhat6/augustus/augustus-20220316/config
/ddn/work/cjh/test/braker-20220128/tests/test1/train.f.gb
and I can reproduce the segmentation fault, then I should be able to
diagnose it and fix it.
Please make sure to include the (gzipped)
folder /app/redhat6/augustus/augustus-20220316/config/species/Sp_1

Am Mi., 10. Aug. 2022 um 08:07 Uhr schrieb Justin Choi <
***@***.***>:

**Comment by methylome** [comment]
@MarioStanke Thanks a lot for your reply.
While preparing a file, there is no Sp_1 in /app/redhat6/augustus/augustus-20220316/config/species/. Is that the problem?

**Comment by methylome** [comment]
As shown in braker.log, Sp_1 was created using new_species.pl, but removed somehow before running etraining. So I ran etraining after running new_species.pl, but etraing was failed again.

**Comment by KatharinaHoff** [comment]
Please check whether
` perl /app/redhat6/augustus/augustus-3.4.0/scripts/new_species.pl --species=Sp_1 --AUGUSTUS_CONFIG_PATH=/app/redhat6/augustus/augustus-3.4.0/config`
throws an error on your system. Possibly, you don't have writing permissions in your /app/redhat6/augustus/augustus-3.4.0/config directory?

**Comment by methylome** [comment]
No. The directory was created.

**Comment by qmpotential** [comment]
# Tue Jan 17 10:06:00 2023: Log information is stored in file /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test1/braker.log
sh: line 1: 17338 Segmentation fault      /ddnA/work/sam09/Programs/Admin/Augustus/bin/../config/../bin/etraining --species=Sp_2 --AUGUSTUS_CONFIG_PATH=/ddnA/work/sam09/Programs/Admin/Augustus/bin/../config /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test1/train.f.gb > /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test1/gbFilterEtraining.stdout 2> /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test1/errors/gbFilterEtraining.stderr
ERROR in file /ddnA/project/maheshid/sam09/Tools/BRAKER/scripts/braker.pl at line 7493
Failed to execute: /ddnA/work/sam09/Programs/Admin/Augustus/bin/../config/../bin/etraining --species=Sp_2 --AUGUSTUS_CONFIG_PATH=/ddnA/work/sam09/Programs/Admin/Augustus/bin/../config /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test1/train.f.gb 1> /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test1/gbFilterEtraining.stdout 2>/ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test1/errors/gbFilterEtraining.stderr

**Comment by qmpotential** [comment]
Augustus and braker were installed from the github

**Comment by qmpotential** [comment]
Running test2

**Comment by qmpotential** [comment]
[Tue Jan 17 10:25:55 2023] Enqueueing pair 5756/5767 (99.8%)
[Tue Jan 17 10:25:55 2023] Enqueueing pair 5762/5767 (99.9%)
[Tue Jan 17 10:26:09 2023] 5767/5767 (100%) pairs aligned
[Tue Jan 17 10:26:09 2023] Alignment of pairs finished
[Tue Jan 17 10:26:09 2023] Translating coordinates from local pair level to contig level
[Tue Jan 17 10:26:09 2023] Finished spliced alignment
[Tue Jan 17 10:26:09 2023] Flagging top chains
[Tue Jan 17 10:26:10 2023] Processing the output
[Tue Jan 17 10:26:12 2023] Output processed
[Tue Jan 17 10:26:12 2023] ProtHint finished.
sh: line 1: 28266 Segmentation fault      /ddnA/work/sam09/Programs/Admin/Augustus/bin/../config/../bin/etraining --species=Sp_2 --AUGUSTUS_CONFIG_PATH=/ddnA/work/sam09/Programs/Admin/Augustus/bin/../config /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test2/train.f.gb > /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test2/gbFilterEtraining.stdout 2> /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test2/errors/gbFilterEtraining.stderr
ERROR in file /ddnA/project/maheshid/sam09/Tools/BRAKER/scripts/braker.pl at line 7493
Failed to execute: /ddnA/work/sam09/Programs/Admin/Augustus/bin/../config/../bin/etraining --species=Sp_2 --AUGUSTUS_CONFIG_PATH=/ddnA/work/sam09/Programs/Admin/Augustus/bin/../config /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test2/train.f.gb 1> /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test2/gbFilterEtraining.stdout 2>/ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test2/errors/gbFilterEtraining.stderr

**Comment by qmpotential** [comment]
May I ask you guys to help me with this issue?

**Comment by qmpotential** [comment]
The same thing with the test3

**Comment by KatharinaHoff** [comment]
Did you compile Augustus and etraining on the machine where you are
executing?

Oleg ***@***.***> schrieb am Di. 17. Jan. 2023 um 17:36:

**Comment by qmpotential** [comment]
Good morning Katharina!

Yes, I am actually trying to reinstall the BAKER,
to be honest the installation procedure in README file
is a little bit confusing.

I will keep you updated, thank you for such a quick response.

**Comment by qmpotential** [comment]
My question is 
Do I need to instal augustus in conda environment?

**Comment by KatharinaHoff** [comment]
It doesn’t sound like a BRAKER problem. It sounds like an
Augustus/etraining issue. This might happen if you execute binaries that
were compiled on a different system.

We provide a container for singularity in the braker3 branch on github. It
works with braker1  & braker2 if you use GeneMark-EP. Braker3 might not
work yet unless Georgia Tech gas made GeneMark-ETP available for download
in the meantime.

Oleg ***@***.***> schrieb am Di. 17. Jan. 2023 um 18:11:

**Comment by qmpotential** [comment]
Thank you so much!

**Comment by Weihankk** [comment]
> [Tue Jan 17 10:25:55 2023] Enqueueing pair 5756/5767 (99.8%) [Tue Jan 17 10:25:55 2023] Enqueueing pair 5762/5767 (99.9%) [Tue Jan 17 10:26:09 2023] 5767/5767 (100%) pairs aligned [Tue Jan 17 10:26:09 2023] Alignment of pairs finished [Tue Jan 17 10:26:09 2023] Translating coordinates from local pair level to contig level [Tue Jan 17 10:26:09 2023] Finished spliced alignment [Tue Jan 17 10:26:09 2023] Flagging top chains [Tue Jan 17 10:26:10 2023] Processing the output [Tue Jan 17 10:26:12 2023] Output processed [Tue Jan 17 10:26:12 2023] ProtHint finished. sh: line 1: 28266 Segmentation fault /ddnA/work/sam09/Programs/Admin/Augustus/bin/../config/../bin/etraining --species=Sp_2 --AUGUSTUS_CONFIG_PATH=/ddnA/work/sam09/Programs/Admin/Augustus/bin/../config /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test2/train.f.gb > /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test2/gbFilterEtraining.stdout 2> /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test2/errors/gbFilterEtraining.stderr ERROR in file /ddnA/project/maheshid/sam09/Tools/BRAKER/scripts/braker.pl at line 7493 Failed to execute: /ddnA/work/sam09/Programs/Admin/Augustus/bin/../config/../bin/etraining --species=Sp_2 --AUGUSTUS_CONFIG_PATH=/ddnA/work/sam09/Programs/Admin/Augustus/bin/../config /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test2/train.f.gb 1> /ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test2/gbFilterEtraining.stdout 2>/ddnA/project/maheshid/sam09/Tools/BRAKER2_EX/example/tests/test2/errors/gbFilterEtraining.stderr

I meet the same issue, I clone the newest BRAKER3 and Augustus from github and complie them normaly withour any warning. Is there any solution?
