### ISSUE TITLE
ProtHint error (no stop_codon found in Spaln/spaln.gff)

### ISSUE THREAD

**Issue by Ziwei-Liu** [Gaius-Augustus/BRAKER#509]
I am running braker2.1.5 in --etpmode --softmasking with rna-seq evidence and orthodb proteins as protein evidence. The run crashes with the following error:

`/bin/sh: 1: [[: not found`
`error: ProtHint exited due to an error in command: grep stop_codon Spaln/spaln.gff > stops.gff || [[ $? == 1 ]]`

And my command line:

`nohup braker.pl --cores 40 --genome=Lv.genome.fasta.masked \`
`--bam=Lv.merged.sorted.bam --etpmode --softmasking \`
`--prot_seq=refseq_db.faa --gff3 --prg=ph &`

My braker2.1.5 is built and run in conda environment, though i don't think it to be a conda environment error. Any tips?

**Comment by tomasbruna** [comment]
Hi @Ziwei-Liu,

I suspect this is caused by using an older BRAKER2 and ProtHint versions since this issue was patched in ProtHint a while ago (see https://github.com/gatech-genemark/ProtHint/issues/18). Please update both tools to the latest releases (braker 2.1.6 and ProtHint 2.6.0) and try again.

You can test BRAKER2 on [test3.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3.sh) once you update to see whether everything works.

Best,
Tomas

**Comment by Ziwei-Liu** [comment]
Thank you @tomasbruna , it can go through this step after I updated braker2 to 2.1.6 and prothint to 2.6.0. But then a new error happened, which looks as follows in file `GeneMark-ETP.stdout`:

`check before run
create directories
commit input data
soft_mask is in the 'auto' mode. soft_mask was set to: 100
error, output file is empty data/evidence.gff
error on call: /share/data/local/gmes_linux_64/reformat_gff.pl --out data/evidence.gff  --trace info/dna.trace  --in /share/user/liuziwei/Penaeus_Vannamei/01_assembly/02_transcriptome/03_braker2/braker/genemark_evidence.gff  --quiet`

I checked former issue #290 which has a similar problem as i do, but I did not use a '--prothint' command as they did, and my command lines are as follow:

`nohup braker.pl --cores 40 --genome=../../01_genome/01_repeat/RepeatMasker/repeat_result/Lv.genome.fasta.masked \
--bam=Lv.merged.sorted.bam --etpmode --softmasking \
--prot_seq=refseq_db.faa --gff3 &`

Any tips?

p.s. My braker2.1.6 was built under a conda environment, and i can't tell how to run test3 in this conda environment, for there's not such a test3.sh file in the installed conda folder. Fortunately it is not a big problem.

**Comment by tomasbruna** [comment]
It will be easier to debug this on [test3.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3.sh) to figure out whether the issue is with your installation or your input data.

You can find the test files here on GitHub: https://github.com/Gaius-Augustus/BRAKER/tree/master/example and a description of the text examples here: https://github.com/Gaius-Augustus/BRAKER#example-data

**Comment by Ziwei-Liu** [comment]
> It will be easier to debug this on [test3.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3.sh) to figure out whether the issue is with your installation or your input data.
> 
> You can find the test files here on GitHub: https://github.com/Gaius-Augustus/BRAKER/tree/master/example and a description of the text examples here: https://github.com/Gaius-Augustus/BRAKER#example-data

Thank you, I tested the test3.sh, and it works properly. It seems that it's my input file that results in the error. It's strange that my genome performances poorly on Homology Comparison through the diamond process, which produces a extremly small diamond result with only 47 hits of my genome to the whole orthodb arthropoda protein database. It may result in the empty evidence.gff and thus makes the program corrupt.

**Comment by tomasbruna** [comment]
The low number of DIAMOND is almost certainly causing the error.

OrthoDB seems to be very sparse around _Penaeus Vannamei_ (no proteins in the same taxonomic order, only one species in the same class)---this might be causing the issue. Did you have any luck with running BRAKER1 using RNA-Seq only?

**Comment by Ziwei-Liu** [comment]
> The low number of DIAMOND is almost certainly causing the error.
> 
> OrthoDB seems to be very sparse around _Penaeus Vannamei_ (no proteins in the same taxonomic order, only one species in the same class)---this might be causing the issue. Did you have any luck with running BRAKER1 using RNA-Seq only?

Yes, I'm just running a project with only RNA-seq data, and it works correctly till now. Maybe I should do a protein-based homology annotation by some other means. Thank you for your attention, and sorry for bothering you not for a programming bug but in fact an unexpected input error of my own files.

**Comment by tomasbruna** [comment]
You can also try looking for more closely related protein sets (outside of OrthoDB). We are recommending OrthoDB because it covers most species pretty well, but BRAKER will work with any protein files on input.

**Comment by Ziwei-Liu** [comment]
> You can also try looking for more closely related protein sets (outside of OrthoDB). We are recommending OrthoDB because it covers most species pretty well, but BRAKER will work with any protein files on input.

Thank you, I'll try some annotated crustacean proteins later.

**Comment by KatharinaHoff** [comment]
If you have proteins of a closely related species, you could try running GALBA instead of BRAKER... https://github.com/Gaius-Augustus/GALBA
