### ISSUE TITLE
No BRAKER output after finishing ProtHint and the analysis stops pre-emptively

### ISSUE THREAD

**Issue by nitinra** [Gaius-Augustus/BRAKER#510]
Hello,

I ran braker2 using GNU Parallel with the following command.
`cat /my/path/run1.txt | parallel -j+0 \ braker.pl --genome={} \ --prot_seq=/my/path/odb10_arthropoda_proteins.fa --softmasking --species {.} \ --cores=28 --workingdir=/mypathr/results/braker_annotation/{.}`

<img width="1153" alt="Screen Shot 2022-08-11 at 8 39 49 PM" src="https://user-images.githubusercontent.com/70153351/184264742-0faa53f6-fc83-4e46-af73-95317dedc088.png">

Here is the [braker_script.txt](https://github.com/Gaius-Augustus/BRAKER/files/9312956/braker_script.txt) , [braker.log](https://github.com/Gaius-Augustus/BRAKER/files/9312958/braker.log) , [braker_error.log](https://drive.google.com/file/d/1ITMnUxkK84hAdJRHoG6DDqyEXumxdxjp/view?usp=sharing). 

Where is the analysis messing up? Thank you so much!

I ran the test2.sh and it ran without any issues.

**Comment by tomasbruna** [comment]
Are all of the runs failing or just some?

From braker.log, it seems that BRAKER exits while running `etraining`. Are there any error messages in `/work/nitinr/running/gustatory_evolution/results/braker_annotation/Abscondita_terminalis_genome.softmasked/errors/gbFilterEtraining.stderr` or log messages in `/work/nitinr/running/gustatory_evolution/results/braker_annotation/Abscondita_terminalis_genome.softmasked/gbFilterEtraining.stdout `?

**Comment by e-dort** [comment]
Was this issue ever resolved? I think I am having a similar issue: I ran braker.pl on 195 genomes and it has worked no problem with 193 of them (I get braker.gtf file and the pipeline finishes normally). However, two of the genomes seem to be stuck on ProtHint. There are no obvious errors and they are just sitting on the compute cluster for days, but nothing is happening. I tried re-running them with double the cores, but that has resulted in the same issue. 

Here is the [braker.log](https://github.com/Gaius-Augustus/BRAKER/files/9725509/braker.log), and here is the stdout/stderr file: [braker.out.txt](https://github.com/Gaius-Augustus/BRAKER/files/9725631/braker.out.txt). Below is a screen shot of the braker directory contents for one of the two failed genomes: 
<img width="828" alt="Screen Shot 2022-10-06 at 10 14 33 AM" src="https://user-images.githubusercontent.com/115166245/194336281-338105d2-cfab-481b-b578-679a75aeeac9.png">

And here is what the directory from one of the successful braker runs looks like:
<img width="920" alt="Screen Shot 2022-10-06 at 10 17 01 AM" src="https://user-images.githubusercontent.com/115166245/194336884-5d877fab-d508-4c9b-b896-280eb90a7377.png">

Does anyone know what's going on here? I would appreciate any insight you have - thank you!

**Comment by ypchan** [comment]
> Was this issue ever resolved? I think I am having a similar issue: I ran braker.pl on 195 genomes and it has worked no problem with 193 of them (I get braker.gtf file and the pipeline finishes normally). However, two of the genomes seem to be stuck on ProtHint. There are no obvious errors and they are just sitting on the compute cluster for days, but nothing is happening. I tried re-running them with double the cores, but that has resulted in the same issue.
> 
> Here is the [braker.log](https://github.com/Gaius-Augustus/BRAKER/files/9725509/braker.log), and here is the stdout/stderr file: [braker.out.txt](https://github.com/Gaius-Augustus/BRAKER/files/9725631/braker.out.txt). Below is a screen shot of the braker directory contents for one of the two failed genomes: <img alt="Screen Shot 2022-10-06 at 10 14 33 AM" width="828" src="https://user-images.githubusercontent.com/115166245/194336281-338105d2-cfab-481b-b578-679a75aeeac9.png">
> 
> And here is what the directory from one of the successful braker runs looks like: <img alt="Screen Shot 2022-10-06 at 10 17 01 AM" width="920" src="https://user-images.githubusercontent.com/115166245/194336884-5d877fab-d508-4c9b-b896-280eb90a7377.png">
> 
> Does anyone know what's going on here? I would appreciate any insight you have - thank you!

Hi @e-dort， I also encountered this, do you solve it, thanks.
![image](https://user-images.githubusercontent.com/33273919/198231240-bcbc3da7-6604-41a9-a67e-c9999022c2f5.png)

kind regards,
yanpeng

**Comment by ypchan** [comment]
Dear @e-dort, please check this https://github.com/gatech-genemark/ProtHint/issues/14

**Comment by e-dort** [comment]
Hi @ypchan, unfortunately, no I never resolved this issue. I'm sorry to hear that you are also having issues. Thank you for forwarding the link, I will see if I can find a similar solution.

**Comment by ypchan** [comment]
@e-dort, the solution in the link works, please try it. Good luck.
