### ISSUE TITLE
error on call: /probuild --reformat_fasta --uppercase --allow_x  

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [Gaius-Augustus/BRAKER#511]
![image](https://user-images.githubusercontent.com/101324838/184265811-c6d53085-3ae5-4f80-826a-de2fee65e6d0.png)
error on call: /public/home/software/opt/bio/software/GeneMark_ET/2019/probuild --reformat_fasta --uppercase --allow_x --letters_per_line 60 --out data/dna.fna --label _dna --trace info/dna.trace --in /public/home/zhaoli/dama/index/hap1.last_w200.final.fasta  
	(in cleanup) 	(in cleanup)  at /public/home/software/opt/bio/software/Perl/5.26.1/lib/perl5/site_perl/5.26.1/Object/InsideOut.pm line 1953 during global destruction.

**Comment by Jiangjiangzhang6** [comment]
Dear my friend, I run the command "gmes_petap.pl  --ET hints.gff --et_score 10  --sequence ../../../index/hap1.last_w200.final.fasta", sadly, it always show the error on when it use the "probuild " .
Thank you

**Comment by tomasbruna** [comment]
Hi @Jiangjiangzhang6,

are you using the latest GeneMark version from http://exon.gatech.edu/GeneMark/license_download.cgi?

The "(in cleanup) error" was fixed already in recent releases, that's why I'm asking...

Best,
Tomas
