### ISSUE TITLE
Too many genes are predicted.

### ISSUE THREAD

**Issue by ZhaoHang-bio** [Gaius-Augustus/BRAKER#513]
Hi,
I am working for some Asteraceae genomes annotation using BRAKER2 v2.1.6. I used softmasked genome and RNA-BAM file as input. The command line is as follows:
braker.pl 
            --genome=$genome \
            --species=$species \
            --softmasking \
            --workingdir=$dir \
            --bam=$bam \
            --cores=20 \
            --nocleanup \
            --gff3

The final gff file predicted more than 100k genes in each species. However, we known the numbers of genes are impossible. 

And I got a summary in filterGenemark.stdout file:
Number of cds hints is 0
Average gene length: 2981
Average number of introns: 2.34110932105869
Good gene rate: 0.107682393555811
Number of genes: 120202
Number of complete genes: 108625
Number of good genes: 11697
Number of one-exon-genes: 28977
Number of bad genes: 108505
Good intron rate: 0.428295440952262
One exon gene rate (of good genes): 0.241087458322647
One exon gene rate (of all genes): 0.241069200179698

The file shown that too many bad genes are predicted, but few good genes.

I don't know which step is wrong, sincerely hope to get your advice!
Looking forward to your reply!

**Comment by tomasbruna** [comment]
The `good` and `bad` names are a bit misleading---they only refer to how suitable the genes are for AUGUSTUS training.

The high number of predicted genes is likely caused by large genome size which leads to overpredicting in long intergenic regions. You could filter out the least reliable predictions (without support by extrinsic evidence) to reduce the number of predictions. This can be achieved, e.g., with [TSEBRA](https://github.com/Gaius-Augustus/TSEBRA).

**Comment by ZhaoHang-bio** [comment]
Dear tomasbruna,
Thanks for your rely!
I tried to input the AUGUSTUS and Genemark models that Braker had trained into Maker3, but prediction models annotated with so many genes were not available. I would like to know how to solve the overpredicting problem. Can I solve the long intergenic regions problem by adjusting the parameters of Braker?

**Comment by tomasbruna** [comment]
> Can I solve the long intergenic regions problem by adjusting the parameters of Braker

Not really, at least not easily. The best solution is, as I suggested, to filter out the "extra " genes in a post-processing step. If you don't want to do this with TSEBRA, I also provided some alternative instructions here https://github.com/Gaius-Augustus/BRAKER/issues/319

**Comment by KatharinaHoff** [comment]
These gene stats are obviously not good.

I recommend that you load the predictions into a genome browser to inspect
them in context with the extrinsic data and repeat masking information. You
may for example find that there is a problem that genes get split despite
evidence, or that the genome has not been masked for repeats, properly (the
latter can also be confirmed by a all v.s. all search in predicted
proteins... if a protein has many hits, then it's probably a repeat
product, and these loci should be masked). How to fix... depends a lot on
the actual problem, which cannot be seen from gene stats alone.

Best,

Katharina

**Comment by KatharinaHoff** [comment]
If you have a  protein set from a closely related species, GALBA might be an option. It usually produces lower gene counts... you can use a GALBA trained parameter set to run BRAKER1 without training to incorporate RNA-Seq data. https://github.com/Gaius-Augustus/GALBA
