### ISSUE TITLE
BRAKER protein file has overlapping proteins

### ISSUE THREAD

**Issue by kelvenr** [Gaius-Augustus/BRAKER#516]
Hello, I ran BRAKER and converted the GTF file to an amino acid file using the getAnnoFastaFromJoingenes.py script. However, upon closer inspection, I realized that the file had overlapping proteins, meaning 2 proteins from the same transcript but with different open reading frames were recognized as 2 different proteins. Here is an example of 2 "different" proteins:

This is the longer protein:
```
MMFLACMFSYMIRTNLSIIIVA*MTIPATSNTITNSTTLNSSISTSIIIHSNIIESSITKS
SFNNSNSNSSSISKSIINGSSNIFNSSIGRSNITNSQINNSCIFNSTISNNTFNNATNYV
FNNVSICNNVKCEYSICMNNTGLKTEKVAACGATINSTVKENNIMDEQYSWSQNIQGVLL...EDEENERL*
```
This is the shorter protein:
```
MTIPATSNTITNSTTLNSSISTSIIIHSNIIESSITKSSFNNSNSNSSSISKSIINGSSN
IFNSSIGRSNITNSQINNSCIFNSTISNNTFNNATNYVFNNVSICNNVKCEYSICMNNTG
LKTEKVAACGATINSTVKENNIMDEQYSWSQNIQGVLL...EDEENERL
```
As you can see, the sequence in between the asterisks ** is identical to the entire shorter protein sequence, however they're identified as different proteins with different headers.

To generate this file, I ran BRAKER1 and BRAKER2 then joined the results using TSERBA. The final GTF file was converted to an amino acid file using the abovementioned script. I found the first (longer) protein sequence in the GTF file of BRAKER1, and the second (shorter) in that of BRAKER2. The problem seems to be when joining with TSEBRA; the program is recognizing them as different proteins since (I'm assuming) they have different headers.
I'm running OrthoMCL and the program is identifying these "different" proteins as paralogs, which is not true.
How do I fix this? Is there an in-built script for it? I tried searching but couldn't find anything.

Additionally, this is unrelated but my proteins include a lot of "X" amino acids, as well as many proteins that don't start with a methionine. The problem seems to have arisen from BRAKER and not TSEBRA, but I don't understand if this is a normal occurrence. I have around 7500 sequences that include an "X", and 7900 that don't start with a methionine. Is this expected or should I remove these sequences?

**Comment by tomasbruna** [comment]
Are these different transcripts (and the resulting translated proteins) part of the same gene, i.e., do they have the same gene ID assigned by TSEBRA? If so, this would be a correct prediction of alternative isoforms and if you want only one isoform/protein per gene, you can use [this script](https://github.com/gatech-genemark/ProtHint/blob/master/bin/print_longest_isoform.py) and then translate the GTF file. The script selects the longest coding isoform per each gene.

The sequences starting with X or not M indicate incomplete gene predictions. This can happen, e.g., when a gene is split between two contigs in the assembly. Thus, a high number of incomplete predictions often arises when the assembly is fragmented---is that the case?

Also, BRAKER outputs a file called `augustus.hints.aa`. Are the 'Xs' already present there? I want to rule out some error during translation...

Best,
Tomas

**Comment by kelvenr** [comment]
Thank you for your response. The script you linked is quite helpful and seems to have removed the isoforms.
I suspect my assembly is quite fragmented as my N50 value is relatively low. What can I do in such a case? Can the incomplete gene predictions contain valuable information or would ignoring them not much affect my results?
Also to answer your last question yes my `augustus.hints.aa` file does contain many 'Xs'.

I recently found a potential solution you suggested in #319 which was to run the `selectSupportedSubsets.py` script. I did so (individually on BRAKER1 and BRAKER2 output then combined using TSEBRA) and only used the "ANYSUPPORT" file, and got a much lower number of proteins that include an 'X' or don't start with an 'M'. However I'm worried that by ignoring the "NOSUPPORT" group I'm missing some important proteins, especially that the genome and proteome I'm assembling are those of a novel species that hasn't been sequenced yet. Is there a way to filter the "NOSUPPORT" group to extract some potential proteins? I saw someone suggest using InterProScan or Blast searching, but I'm not sure how exactly I'd go about doing that. If I ran InterProScan, on which basis should I make the selection? Is there some script that can filter the proteins based on the result of InterProScan or some pre-defined cutoff for hits?

Many thanks in advance.

Kelven

**Comment by tomasbruna** [comment]
Hi Kelven,

> Can the incomplete gene predictions contain valuable information

Probably. With the fragmented assembly, incomplete predictions might be the best result you can get.

> If I ran InterProScan, on which basis should I make the selection?

I would start by keeping all predictions that result in a hit. Only if that gives too many predictions, I'd try to filter further.

Best,
Tomas
