### ISSUE TITLE
WARNING:  # The hints file(s) for GeneMark-EX contain less than 1000 introns.

### ISSUE THREAD

**Issue by BioHlT** [Gaius-Augustus/BRAKER#517]
Hello, 
I am running Braker on XSEDE using batch. I encountered an issue with the braker pipeline; I have used the same command for previous jobs with similar data sets and never had a problem with it. I have the up-to-date gm_key and genemark program installed on XSEDE. I am using a genome fasta to run braker analysis(The command I used is below). The issue is still persistent after I reinstalled genemark, and the key

**JOB**
#!/bin/bash 
#SBATCH -N 1
#SBATCH -p RM-512 
#SBATCH --ntasks-per-node 128
#SBATCH -t 36:00:00 
#SBATCH --job-name="Cmari_BRAKER"
#SBATCH -o slurm.%N.%j.out #STDOUT
#SBATCH -e slurm.%N.%j.err #STDERR
 set -x # 
PATH=/ocean/projects/tra180030p/ytekle/Software/BRAKER/scripts/:$PATH
export PATH
braker.pl --genome=Cmari_polished_genome_edited_v1.fasta \
--hints=prothint_augustus.gff \
--epmode --min_contig=1000 \
--cores=8 \

**Error** 
ERROR in file /ocean/projects/tra180030p/ytekle/Software/BRAKER/scripts/braker.pl at line 6747
Failed to execute: perl /ocean/projects/tra180030p/ytekle/Software/gmes_linux_64/gmes_petap.pl

**Braker.log**
# WARNING: 
# The hints file(s) for GeneMark-EX contain less than 1000 introns. (In total, 557 unique introns are contained.)
# Genemark-EX might fail due to the low number of hints.
# WARNING: 
# The hints file(s) for GeneMark-EX contain less than 150 introns with multiplicity >= 4! (In total, 557 unique introns are contained. 1 have a multiplicity >= 4.)
# Possibly, you are trying to run braker.pl on data that does not provide sufficient multiplicity information. This will e.g. happen if you try to use introns generated from assembled RNA-Seq transcripts; or if you try to run braker.pl in epmode with mappings from proteins without sufficient hits per locus. Or if you use the example data set.
# A low number of intron hints with sufficient multiplicity may result in a crash of GeneMark-EX (it should not crash with the example data set).

I am unsure how to address this problem, but I would appreciate any response on resolving this issue.
Thank you!

**Comment by tomasbruna** [comment]
Based on the warning, there seems to be insufficient protein support. What protein database are you using?

Please also share the contents of the `GeneMark*.stdout` file---that will give us more clues about what's causing the error.

**Comment by BioHlT** [comment]
**Hello, here is the GeneMark-EP.stdout.** 
# check before the run
# hard_mask is in the 'auto' mode. hard_mask was set to: 1000
# creat directories
# commit input data
# prepare input data report
# commit training data
# prepare training data report
# prepare initial model
# find GC of sequence
GC 35
# build initial EP model
error on call: /ocean/projects/tra180030p/ytekle/Software/gmes_linux_64/parse_by_introns.pl  --section EP_ini  --cfg  /ocean/projects/tra180030p/ytekle/htefera/Cmari_Annotation/01_Braker/braker/GeneMark-EP/run.cfg  --parse_dir /ocean/projects/tra180030p/ytekle/htefera/Cmari_Annotation/01_Braker/braker/GeneMark-EP/run/EP_ini

**Comment by tomasbruna** [comment]
Would you mind sharing your input files with me? You can send them to my e-mail, bruna.tomas@gmail.com, if you don't want to share here. I will try to run the code myself and reproduce the error, it will be the fastest way to figure out what's wrong.

**Comment by BioHlT** [comment]
I have shared the Data with you; let me know if you figure out the issue, and be on the lookout for an email from tefera.hanna11@gmail.com.

Thank you

**Comment by tomasbruna** [comment]
Hi @BioHlT,

thanks for sharing. I was able to successfully run the code using your input, at least past the point in which your attempt failed. I used the same command as you had in your first comment:

    braker.pl --genome=Cmari_polished_genome_edited_v1.fasta
        --hints=prothint_augustus.gff \
        --epmode --min_contig=1000 \
        --cores=8 \

Perhaps you'll have more luck when you use locally installed BRAKER (as you mentioned in the email). Let me know.

Best,
Tomas

**Comment by tomasbruna** [comment]
Also, please take a look at https://github.com/Gaius-Augustus/BRAKER/issues/225 and https://github.com/Gaius-Augustus/BRAKER/issues/179 issues. They both describe errors with a message similar to yours. You might have the same problem.

**Comment by KatharinaHoff** [comment]
Possibly using our singularity container might also solve the problem:

```
singularity build braker.sif docker://katharinahoff/braker-notebook:devel
singularity exec braker.sif braker.pl
```

Currently, you still have to manually install GeneMark and the license key into your home directory on the executing host.
