### ISSUE TITLE
The lateset version of braker2 is installed. but still  find "core.XXX" file in the outputfile after running it.

### ISSUE THREAD

**Issue by 17863952296** [Gaius-Augustus/BRAKER#518]
many errors like the following:
/apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/aug_hints_316: line 3: 12402 Segmentation fault      (core dumped) /usr/local/augustus/config/../bin/augustus --species=Cyclidium --AUGUSTUS_CONFIG_PATH=/usr/local/augustus/config --extrinsicCfgFile=/usr/local/braker/scripts/cfg/rnaseq.cfg --alternatives-from-evidence=true --UTR=off --exonnames=on --codingseq=on --allow_hinted_splicesites=gcag,atac --hintsfile=/apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/augustus_tmp/307.001.tig00002306_pilon_pilon_pilon.fa.1..251029.hints --predictionStart=1 --predictionEnd=251029 /apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/genome_split/tig00002306_pilon_pilon_pilon.fa --outfile=/apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/augustus_tmp/307.001.tig00002306_pilon_pilon_pilon.fa.1..251029.gff --errfile=/apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/augustus_tmp/307.001.tig00002306_pilon_pilon_pilon.fa.1..251029.err
/apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/aug_hints_307: line 3: 12379 Segmentation fault      (core dumped) /usr/local/augustus/config/../bin/augustus --species=Cyclidium --AUGUSTUS_CONFIG_PATH=/usr/local/augustus/config --extrinsicCfgFile=/usr/local/braker/scripts/cfg/rnaseq.cfg --alternatives-from-evidence=true --UTR=off --exonnames=on --codingseq=on --allow_hinted_splicesites=gcag,atac --hintsfile=/apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/augustus_tmp/299.002.tig00002229_pilon_pilon_pilon.fa.1247501..1285382.hints --predictionStart=1247501 --predictionEnd=1285382 /apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/genome_split/tig00002229_pilon_pilon_pilon.fa --outfile=/apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/augustus_tmp/299.002.tig00002229_pilon_pilon_pilon.fa.1247501..1285382.gff --errfile=/apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/augustus_tmp/299.002.tig00002229_pilon_pilon_pilon.fa.1247501..1285382.err
/apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/aug_hints_322: line 3: 12500 Segmentation fault      (core dumped) /usr/local/augustus/config/../bin/augustus --species=Cyclidium --AUGUSTUS_CONFIG_PATH=/usr/local/augustus/config --extrinsicCfgFile=/usr/local/braker/scripts/cfg/rnaseq.cfg --alternatives-from-evidence=true --UTR=off --exonnames=on --codingseq=on --allow_hinted_splicesites=gcag,atac --hintsfile=/apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/augustus_tmp/313.001.tig00001064_pilon_pilon_pilon.fa.1..5607.hints --predictionStart=1 --predictionEnd=5607 /apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/genome_split/tig00001064_pilon_pilon_pilon.fa --outfile=/apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/augustus_tmp/313.001.tig00001064_pilon_pilon_pilon.fa.1..5607.gff --errfile=/apps/users/class00/dzg/Cyclidium/RNAseq/Braker2/braker/augustus_tmp/313.001.tig00001064_pilon_pilon_pilon.fa.1..5607.err
how to solve the problem?

**Comment by tomasbruna** [comment]
Seems like a problem with AUGUSTUS. Can you replicate the issue using a small input example? I'd suggest opening an issue (together with the example) at https://github.com/Gaius-Augustus/Augustus

**Comment by 17863952296** [comment]
> Seems like a problem with AUGUSTUS. Can you replicate the issue using a small input example? I'd suggest opening an issue (together with the example) at https://github.com/Gaius-Augustus/Augustus
Thank you for your reply. I will show you my input data for the following: 
braker.pl --cores=16 --species=Cyclidium --genome=Cy_Canu.filter.fasta --bam=Cy_hisat2.sort.bam --hints=Cy_stringtie.gff3
at the same time, I will send this problem to the web https://github.com/Gaius-Augustus/Augustus.

**Comment by KatharinaHoff** [comment]
Did you compile the most recent Augustus from github on the
machine/architecture where you are executing?

**Comment by 17863952296** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    yes, I haved compiled the most recent Braker from github on the machine.Best,Dengziguang
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Katharina ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/11/2022 16:54
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [Gaius-Augustus/BRAKER] The lateset version of braker2 is installed. but still find "core.XXX" file in the outputfile after running it. (Issue #518)
        
      
    
  
  

Did you compile the most recent Augustus from github on the

machine/architecture where you are executing?



On Wed, Aug 31, 2022 at 3:40 AM 17863952296 ***@***.***>

wrote:

**Comment by KatharinaHoff** [comment]
We never really resolved this issue but a very large number of changes has happened in BRAKER. I recommend using the Singularity/Docker image of the current version of BRAKER.
