### ISSUE TITLE
AUGUSTUS_CONFIG_PATH/species (in this case /.../.../somewhere) is not writeable.

### ISSUE THREAD

**Issue by EricDeveaud** [Gaius-Augustus/BRAKER#520]
Hello, 

after a fresh installation of BRAKER on ou cluster on. a centralised NFS read-only volume we had some problems running BRAKER/2.1.6

problem was with `$AUGUSTUS_CONFIG_PATH/species` not writable related to #47 and #23 

as a quick workaround I copied the whole $AUGUSTUS_CONFIG_PATH to some location I have write permissions
`cp -r $AUGUSTUS_CONFIG_PATH ~/augustus_data`

then ran BRAKER after having `export AUGUSTUS_CONFIG_PATH=~/augustus_data`
provide a working solution.

BUT, yes there's a BUT ;-)

seems to me that the requirement for the write permissin is to be abble to generate `species/Sp_*` 
it sound possible to generate those files and refer to it in a temporary folder or in current working directory ?

what do you think ?

regards

Eric

**Comment by EricDeveaud** [comment]
seems to me, with my poor skills in perl that this is possible.
it implies a modification to a script from `augustus`, `new_species.pl` in order to be abble to take in account an ouput directory where to create the `Sp_*/` files,  eg: `Sp_1_parameters.cfg`, `Sp_1_weightmatrix.txt`, `Sp_1_metapars.cfg`, Sp_1_metapars.utr.cfg`, `Sp_1_metapars.cgp.cfg`, `Sp_1_ovlp_len.pbl`, `Sp_1__trans_shadow_bacterium.pbl` when required.

so read "templates" from `$configdir/species` where `$configdir` is pointed by `$AUGUSTUS_CONFIG_PATH` 

and then of course adapt BRAKER code to read thoose files from the above specified output_dir.

what do you think ?

regards

Eric

**Comment by KatharinaHoff** [comment]
The handling of species parameters is supposed to be changed on Augustus
level. That’s why we are currently not touching this in Braker.

An easy workaround for now is to copy the config folder to a writable
location and change the AUGUSTUS CONFIG PATH.

Eric Deveaud ***@***.***> schrieb am Fr. 2. Sept. 2022 um
17:02:

**Comment by EricDeveaud** [comment]
OK 

So Iwon't push further my tentative to propose a patch for this solution.

regards

Eric

**Comment by KatharinaHoff** [comment]
Since this is taking "forever" on the augustus end, we have fixed this in BRAKER3. (It's already available in the braker3 branch, but not in the master branch, yet).
