### ISSUE TITLE
BRAKER fails with GeneMark-ET

### ISSUE THREAD

**Issue by V-JJ** [Gaius-Augustus/BRAKER#521]
Hello!

I tried to run BRAKER using the pipeline that takes as input both proteins and mRNA bam file. It run successfully, but the BUSCOs went from roughly ~90% (at genome level) to ~0 % !! although no errors were detected. 

- Given this unexpected result, I tried to run BRAKER (but now following the TSEBRA protocol) using only:
    - a soft-masked genome (~4 Gb) and 
    - a RNAseq derived BAM file (sorted) (~30Gb). My job failed with the errors described below. 

What surprised me the most is that another job, run as control case, finished successfully (with both BRAKER protocols). 

I also checked whether the input BAM file is corrupted somehow (it is not). It has been obtained with STAR, by mapping good quality RNAseq data (trimmed and quality checked) to the input soft-masked genome. RNAseq data from several tissues and both sexes was used.

This problem is somehow similar to that issue #385, and I tried the same solutions (update .gm_key and change perl paths) with no resullt. I even tried to reinstall GeneMark.
- Today, I have found that this script (`hc_exons2hints.pl`) from GeneMark has not had it perl path changed since it is not specified in `change_path_in_perl_scripts.pl`. So, I have changed it manually to my conda path and now, a test is running.

Here you have the last messages from stderr file,  `braker.log` file and `GeenMark-ET.stderr` error file. 

- stderr file
```
ERROR in file /users-d3/vadim.pisarenco/Programs_V/BRAKER-2.1.6/scripts/braker.pl at line 6666
Failed to execute: perl /users-d3/vadim.pisarenco/Programs_V/gmes_linux_64_4//gmes_petap.pl --verbose --sequence=/users-d3/vadim.pisarenco/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/genome.fa --ET=/users-d3/vadim.pisarenco/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/genemark_hintsfile.gff --cores=48 --gc_donor 0.001 --soft_mask auto 1>/users-d3/vadim.pisarenco/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/GeneMark-ET.stdout 2>/users-d3/vadim.pisarenco/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/errors/GeneMark-ET.stderr
Failed to execute: perl /users-d3/vadim.pisarenco/Programs_V/gmes_linux_64_4//gmes_petap.pl --verbose --sequence=/users-d3/vadim.pisarenco/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/genome.fa --ET=/users-d3/vadim.pisarenco/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/genemark_hintsfile.gff --cores=48 --gc_donor 0.001 --soft_mask auto 1>/users-d3/vadim.pisarenco/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/GeneMark-ET.stdout 2>/users-d3/vadim.pisarenco/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/errors/GeneMark-ET.stderr
The most common problem is an expired or not present file ~/.gm_key!
```

- Last lines from `braker.log` file
```
**********************************************************************************
#                              RUNNING GENEMARK-EX                                 
#**********************************************************************************
# Sun Sep  4 12:58:54 2022: Checking whether file /users/myuser/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/genemark_hintsfile.gff contains enough hints and sufficient multiplicity information...
# Sun Sep  4 12:58:54 2022: Executing GeneMark-ET
# Sun Sep  4 12:58:54 2022: changing into GeneMark-ET directory /users/myuser/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/GeneMark-ET
cd /users/myuser/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/GeneMark-ET
# Sun Sep  4 12:58:54 2022: Executing gmes_petap.pl
perl /users/myuser/Programs_V/gmes_linux_64_4//gmes_petap.pl --verbose --sequence=/users/myuser/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/genome.fa --ET=/users/myuser/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/genemark_hintsfile.gff --cores=48 --gc_donor 0.001 --soft_mask auto 1>/users/myuser/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/GeneMark-ET.stdout 2>/users/myuser/9_Altres/Sara_BRAKER_vtest/TSEBRA/BR1_mRNA/braker1_out/errors/GeneMark-ET.stderr

```

- `GeneMark-ET.stderr` error messages
```
Use of uninitialized value $ph1 in addition (+) at /users/myuser/Programs_V/gmes_linux_64_4/parse_ET.pl line 102.
Use of uninitialized value $ph1 in division (/) at /users/myuser/Programs_V/gmes_linux_64_4/parse_ET.pl line 106.
Use of uninitialized value $ph1 in division (/) at /users/myuser/Programs_V/gmes_linux_64_4/parse_ET.pl line 108.
Use of uninitialized value $ph1 in division (/) at /users/myuser/Programs_V/gmes_linux_64_4/parse_ET.pl line 109.
Use of uninitialized value $ph1 in division (/) at /users/myuser/Programs_V/gmes_linux_64_4/parse_ET.pl line 109.
Use of uninitialized value $ph1 in division (/) at /users/myuser/Programs_V/gmes_linux_64_4/parse_ET.pl line 110.
Use of uninitialized value $ph1 in division (/) at /users/myuser/Programs_V/gmes_linux_64_4/parse_ET.pl line 112.
Use of uninitialized value $ph1 in division (/) at /users/myuser/Programs_V/gmes_linux_64_4/parse_ET.pl line 116.
```

Any advice would be appreciated,
Many thanks,

**Comment by tomasbruna** [comment]
Hi @V-JJ,

I've never seen this GeneMark error, it might be related to some recent GeneMark updates. Please contact Alex Lomsadze (his email is at http://exon.gatech.edu/GeneMark/contact.html), he's actively working on the latest GeneMark releases.

Best,
Tomas

**Comment by V-JJ** [comment]
Hello @tomasbruna 

Understood. I'll contact him.

One more question, do you think that the use of many input mRNA seq data files at the same time might cause some problems? 
Perhaps I should separate my data in half, create two different BAM files, run BRAKER twice and then combine them with TSEBRA? 

Thank you

**Comment by tomasbruna** [comment]
Hi @V-JJ,

I'm honestly not sure. You could try doing the "separate + combine" strategy and I'd be interested whether that worked to fix the issue.

Best,
Tomas

**Comment by tomasbruna** [comment]
Thanks for the update!
