### ISSUE TITLE
Too many genes perdict by Braker

### ISSUE THREAD

**Issue by JianMingLuo** [Gaius-Augustus/BRAKER#522]
Thanks for your great software!
I used Braker to predict a Citrus genome.I used the transcriptome of multi tissue mixing, the transcriptome of leaves treated with different diseases and other citrus proteins to predict genes

Even if TESBRA is used to filter the results, nearly 70000 genes are still predicted.
I use selectSupportedSubsets.py to check my Prediction after Braker:

fullSupport:
# Chr  Num:10
# Gene Num:12432
# mRNA Num:13444
anySupport:
# Chr  Num:10
# Gene Num:19143
# mRNA Num:21312
noSupport:
# Chr  Num:10
# Gene Num:73800
# mRNA Num:74812

**My expectation is to predict about 30000 genes. How can I get better results?**

**Comment by tomasbruna** [comment]
See https://github.com/Gaius-Augustus/BRAKER/issues/242. You can do functional annotation of the "noSupport" set and keep only genes that were assigned a putative function.

**Comment by JianMingLuo** [comment]
> See #242. You can do functional annotation of the "noSupport" set and keep only genes that were assigned a putative function.

Thanks for you reply!

I wonder why this is happening? Because I previously used Braker for gene annotation on the same genome at the contig level.It seems normal.

JianMingLuo

**Comment by tomasbruna** [comment]
Repeat masking (the lack of) could cause the elevated number of predictions.

**Comment by KatharinaHoff** [comment]
Simple repeat proteins (those that consist of k-mers) can be screened with
findRepetitiveProtSeqs.py  in Augustus/scripts. This does not find other
repeat proteins. (Please do not simply discard all proteins found by that
script. But if it reveals thousands of proteins that are 90% repetitive,
that’s a strong indicator for undermasking. )

Other kinds of repeat proteins can be found by all vs all sequence
similarity search.

Tomáš Brůna ***@***.***> schrieb am Mi. 7. Sept. 2022 um
20:52:

**Comment by JianMingLuo** [comment]
Thank you so much for you reply.I check my genome after mask by RepeatMasker,it only mask 2% repeat sequence.
I use RepeatModeler&RepeatMask to mask my genome again .Now,it mask 60% repeat sequence.
But Braker predicted that the number of genes was less than expected, almost half of the expected number.
When I use the -gth parameter, the number of genes predicted by braker will be relatively normal.Is this reliable?
This is my cmd:
>nohup braker.pl --cores 15 --species=JYC05v2.1-rnaProtGTH \
         --genome=/datadisk/stu_lab/ma_lab/ljm/JYC05-denovo/3-annotation/1-RPM/xsmall/JYC05-3dDNA-rename-2.fasta.masked \
         --softmasking \
         --bam=/datadisk/stu_lab/ma_lab/ljm/JYC05-denovo/3-annotation/2-Star/REF_C05_mask_mixAligned.sortedByCoord.out.bam,/datadisk/stu_lab/ma_lab/ljm/JYC05-denovo/3-annotation/2-Star/REF_C05_mask_CKAligned.sortedByCoord.out.bam,/datadisk/stu_lab/ma_lab/ljm/JYC05-denovo/3-annotation/2-Star/REF_C05_mask_xcc2dAligned.sortedByCoord.out.bam,/datadisk/stu_lab/ma_lab/ljm/JYC05-denovo/3-annotation/2-Star/REF_C05_mask_xcc4dAligned.sortedByCoord.out.bam,/datadisk/stu_lab/ma_lab/ljm/JYC05-denovo/3-annotation/2-Star/REF_C05_mask_xcc6dAligned.sortedByCoord.out.bam,/datadisk/stu_lab/ma_lab/ljm/JYC05-denovo/3-annotation/2-Star/REF_C05_mask_xcc8dAligned.sortedByCoord.out.bam,/datadisk/stu_lab/ma_lab/ljm/JYC05-denovo/3-annotation/2-Star/REF_C05_mask_xoo2dAligned.sortedByCoord.out.bam \
         --prot_seq=/datadisk/stu_lab/ma_lab/ljm/JYC05-denovo/3-annotation/ref/all-citrus-prot.fasta \
         --prg=gth --trainFromGth --workingdir=./braker-allrna-allCItrusProt \
         --gff3 &

**Comment by KatharinaHoff** [comment]
If your goal is mapping protein sequences of the target to a target genome, and not de novo annotation where that evidence does not exist, then GenomeThreader (or also other spliced aligners for protein to genome alignment tools) might be a good choice at this point in time.

**Comment by KatharinaHoff** [comment]
Or use GALBA: https://github.com/Gaius-Augustus/GALBA
