### ISSUE TITLE
asterisk * at the end of protein sequences 

### ISSUE THREAD

**Issue by ardy20** [Gaius-Augustus/BRAKER#523]
Hello 

I used Braker2 through singularity but noticed that it puts asterisk * symbol at the end of every and each sequence. It hinders Interproscan search and it rejects the augustus.hint.aa (protein) file.

Has anyone encountered such a problem?

**Comment by KatharinaHoff** [comment]
Yes, it always a problem.

cat prot.fa | perl -pe ‘s/\*//;’ > prot_iprsc.fa


ardy20 ***@***.***> schrieb am Mi. 7. Sept. 2022 um 13:37:

**Comment by ardy20** [comment]
Hello
Unfortunately, it did not work and I got this error:

Unrecognized character \xE2; marked by <-- HERE after <-- HERE near column 1 at -e line 1.
cat: write error: Broken pipe
-bash: $'\342\200\231': command not found

**Comment by KatharinaHoff** [comment]
I typed this on my phone. You probably have to replace the upper quotation marks by proper upper quotation marks because the iPhone keyboard may have inserted some other similar looking quotation mark.

`cat prot.fa | perl -pe 's/\*//;' > prot_iprsc.fa`

**Comment by ardy20** [comment]
Hi Katrina

I changed it as following and it worked. Thanks. The correct script is:
cat prot.aa.fasta | perl -pe "s/\*//;" > prot.standard.aa.fasta
