### ISSUE TITLE
redirecting output

### ISSUE THREAD

**Issue by tbazilegith** [Gaius-Augustus/BRAKER#527]
Hello Gaius,
Which flag allows to redirect the output of Braker?
Thanks!
TJ

**Comment by KatharinaHoff** [comment]
What would your like to redirect? 
STDOUT redirects generally with `>`
STDERR redirects with `2>`
... but both are only logging and error infos.
The output folder for all files can be set with `--workingdir=/path/to/wd/ `

**Comment by tbazilegith** [comment]
Thanks!
This "--workingdir=/path/to/wd/" was exactly what I wanted.
TJ
