### ISSUE TITLE
braker error: The most common problem is an expired or not present file ~/.gm_key!

### ISSUE THREAD

**Issue by xyz0o** [Gaius-Augustus/BRAKER#529]
I am running braker as a container
I have updated the .gm_key but I still receive the same message, 
is it possible to update the GeneMark-ES inside the container?

**Comment by KatharinaHoff** [comment]
I assume that you built the container, yourself, because we don't distribute GeneMark in a container (license problem). You can then re-compile your container with an updated version of GeneMark.

**Comment by xyz0o** [comment]
ok then I have to ask our admin, it was installed for me, thanks for the response.
