### ISSUE TITLE
Error on running test2.sh

### ISSUE THREAD

**Issue by methylome** [Gaius-Augustus/BRAKER#530]
In the examples directory, test2.sh was failed. To resolve this problem, I downloaded a license key and saved to ~/.gm_key. However if failed again.

```
./test2.sh &> test2.log

[Fri Sep 16 17:17:14 2022] ProtHint finished.
#*********
# WARNING: 
# The hints file(s) for GeneMark-EX contain less than 1000 introns. (In total, 32 unique introns are contained.)
# Genemark-EX might fail due to the low number of hints.
#*********
#*********
# WARNING: 
# The hints file(s) for GeneMark-EX contain less than 150 introns with multiplicity >= 4! (In total, 32 unique introns are contained. 27 have a multiplicity >= 4.)
# Possibly, you are trying to run braker.pl on data that does not provide sufficient multiplicity information. This will e.g. happen if you try to use introns generated from assembled RNA-Seq transcripts; or if you try to run braker.pl in epmode with mappings from proteins without sufficient hits per locus. Or if you use the example data set.
# A low number of intron hints with sufficient multiplicity may result in a crash of GeneMark-EX (it should not crash with the example data set).
#*********
ERROR in file /app/redhat6/BRAKER/BRAKER-20220128/scripts/braker.pl at line 6758
Failed to execute: perl /app/redhat6/gmes/GeneMark-4.64_lic/gmes_petap.pl --verbose --seq /ddn/work/cjh/test/braker-20220128/tests/test2/genome.fa --EP /ddn/work/cjh/test/braker-20220128/tests/test2/genemark_hintsfile.gff --cores=8  --gc_donor 0.001 --evidence /ddn/work/cjh/test/braker-20220128/tests/test2/genemark_evidence.gff  --soft_mask auto --max_intergenic=10000 1>/ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP.stdout 2>/ddn/work/cjh/test/braker-20220128/tests/test2/errors/GeneMark-EP.stderr
Failed to execute: perl /app/redhat6/gmes/GeneMark-4.64_lic/gmes_petap.pl --verbose --seq /ddn/work/cjh/test/braker-20220128/tests/test2/genome.fa --EP /ddn/work/cjh/test/braker-20220128/tests/test2/genemark_hintsfile.gff --cores=8  --gc_donor 0.001 --evidence /ddn/work/cjh/test/braker-20220128/tests/test2/genemark_evidence.gff  --soft_mask auto --max_intergenic=10000 1>/ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP.stdout 2>/ddn/work/cjh/test/braker-20220128/tests/test2/errors/GeneMark-EP.stderr
The most common problem is an expired or not present file ~/.gm_key!

real  312m8.033s
user  31m58.409s
sys   934m37.126s
```

```
ll ~/.gm_key 
-rw-r--r-- 1 cjh info 91 Sep 16 11:29 /home/cjh/.gm_key
```

**Comment by tomasbruna** [comment]
What's in the `/ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP.stdout` and `/ddn/work/cjh/test/braker-20220128/tests/test2/errors/GeneMark-EP.stderr` files?

**Comment by KatharinaHoff** [comment]
There was no answer to the question of Tomas. I guess this issue resolved on its own. Closing.

**Comment by methylome** [comment]
GeneMark-EP.stdout
'''
Summary of my perl5 (revision 5 version 10 subversion 1) configuration:
   
  Platform:
    osname=linux, osvers=2.6.18-412.el5, archname=x86_64-linux-thread-multi
    uname='linux x86-041.build.eng.bos.redhat.com 2.6.18-412.el5 #1 smp mon aug 1 08:07:14 edt 2016 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Doptimize=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DDEBUGGING=-g -Dversion=5.10.1 -Dmyhostname=localhost -Dperladmin=root@localhost -Dcc=gcc -Dcf_by=Red Hat, Inc. -Dprefix=/usr -Dvendorprefix=/usr -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl5 -Dsitearch=/usr/local/lib64/perl5 -Dprivlib=/usr/share/perl5 -Darchlib=/usr/lib64/perl5 -Dvendorlib=/usr/share/perl5/vendor_perl -Dvendorarch=/usr/lib64/perl5/vendor_perl -Dinc_version_list=5.10.0 -Darchname=x86_64-linux-thread-multi -Dlibpth=/usr/local/lib64 /lib64 /usr/lib64 -Duseshrplib -Dusethreads -Duseithreads -Duselargefiles -Dd_dosuid -Dd_semctl_semun -Di_db -Ui_ndbm -Di_gdbm -Di_shadow -Di_syslog -Dman3ext=3pm -Duseperlio -Dinstallusrbinperl=n -Ubincompat5005 -Uversiononly -Dpager=/usr/bin/less -isr -Dd_gethostent_r_proto -Ud_endhostent_r_proto -Ud_sethostent_r_proto -Ud_endprotoent_r_proto -Ud_setprotoent_r_proto -Ud_endservent_r_proto -Ud_setservent_r_proto -Dscriptdir=/usr/bin -Dusesitecustomize'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.4.7 20120313 (Red Hat 4.4.7-17)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -fstack-protector'
    libpth=/usr/local/lib64 /lib64 /usr/lib64
    libs=-lresolv -lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc
    perllibs=-lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=/lib/libc-2.11.1.so, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.12'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic'


Characteristics of this binary (from libperl): 
  Compile-time options: MULTIPLICITY PERL_DONT_CREATE_GVSV
                        PERL_IMPLICIT_CONTEXT PERL_MALLOC_WRAP USE_64_BIT_ALL
                        USE_64_BIT_INT USE_ITHREADS USE_LARGE_FILES
                        USE_PERLIO USE_REENTRANT_API USE_SITECUSTOMIZE
  Built under linux
  Compiled at Nov  3 2016 11:31:06
  %ENV:
    PERL5LIB="/app/redhat6/gmes/GeneMark-4.64_lic/lib/perl5:/app/redhat6/BRAKER/BRAKER-20220128/lib/perl5:/home/cjh/lib/perl"
  @INC:
    /app/redhat6/gmes/GeneMark-4.64_lic/lib/perl5/x86_64-linux-thread-multi
    /app/redhat6/gmes/GeneMark-4.64_lic/lib/perl5
    /app/redhat6/BRAKER/BRAKER-20220128/lib/perl5/x86_64-linux-thread-multi
    /app/redhat6/BRAKER/BRAKER-20220128/lib/perl5
    /home/cjh/lib/perl
    /usr/local/lib64/perl5
    /usr/local/share/perl5
    /usr/lib64/perl5/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib64/perl5
    /usr/share/perl5
    .
# check before the run
# hard_mask is in the 'auto' mode. hard_mask was set to: 1000
# creat directories
# commit input data
# prepare input data report
# commit training data
# prepare training data report
# prepare initial model
# find GC of sequence
GC 37
# build initial EP model
running step EP_A
running gm.hmm on local multi-core system
8 contigs in list
concatenate predictions: /ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP/run/EP_A_1
training level EP_A: /ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP/run/EP_A_1
From 1619 loaded 1105 and ignored dublications 0
exon	no_match	match_one	match_two
Initial	20	171	0
Internal	38	34	800
Terminal	25	171	0
Single	64	0	0
CDS_no_match	all	short	long	seq_short	seq_long
CDS_no_match	147	105	42	28411	59153
Intergenic	all	between_match	seq_match
Intergenic:	261	114	218667
running step EP_B
running gm.hmm on local multi-core system
8 contigs in list
concatenate predictions: /ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP/run/EP_B_1
training level EP_B: /ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP/run/EP_B_1
From 1619 loaded 1105 and ignored dublications 0
exon	no_match	match_one	match_two
Initial	31	177	0
Internal	76	31	808
Terminal	35	176	0
Single	64	0	0
CDS_no_match	all	short	long	seq_short	seq_long
CDS_no_match	206	163	43	36194	61280
Intergenic	all	between_match	seq_match
Intergenic:	278	112	207229
running step EP_C
running gm.hmm on local multi-core system
8 contigs in list
concatenate predictions: /ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP/run/EP_C_1
training level EP_C: /ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP/run/EP_C_1
From 1619 loaded 1105 and ignored dublications 0
exon	no_match	match_one	match_two
Initial	40	176	0
Internal	103	40	813
Terminal	44	174	0
Single	85	0	0
CDS_no_match	all	short	long	seq_short	seq_long
CDS_no_match	272	229	43	43493	61330
Intergenic	all	between_match	seq_match
Intergenic:	306	99	170880
SvsM  0.195530726256983 vs 0.804469273743017
genes in IvsT all and selected: 1029 124
1, -1.8758425864386
2, -1.60140574073684
3, -1.72923911224672
4, -2.2553322081435
5, -2.42238629280667
7, -2.51769647261099
8, -2.33537491581704
9, -2.33537491581704
# estimate 1: 0.838678328474247
# estimate 2: 0.910878975991114
# value: 0.910878975991114
IvsT  0.910878975991114 vs 0.0891210240088862
running gm.hmm on local multi-core system
8 contigs in list
concatenate predictions: /ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP/run/EP_C_2
training level EP_C: /ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP/run/EP_C_2
From 1619 loaded 1105 and ignored dublications 0
exon	no_match	match_one	match_two
Initial	48	173	0
Internal	119	32	829
Terminal	50	175	0
Single	82	0	0
CDS_no_match	all	short	long	seq_short	seq_long
CDS_no_match	299	256	43	45904	61332
Intergenic	all	between_match	seq_match
Intergenic:	307	98	164977
SvsM  0.19047619047619 vs 0.80952380952381
genes in IvsT all and selected: 1054 117
1, -1.81773495563132
2, -1.62667971886861
3, -1.67113148143944
4, -2.1231166051825
5, -2.1231166051825
8, -2.19722457733622
9, -2.27726728500976
# estimate 1: 0.840607210626186
# estimate 2: 0.927991483688635
# value: 0.927991483688635
IvsT  0.927991483688635 vs 0.0720085163113646
running gm.hmm on local multi-core system
8 contigs in list
concatenate predictions: /ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP/run/EP_C_3
training level EP_C: /ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP/run/EP_C_3
From 1619 loaded 1105 and ignored dublications 0
exon	no_match	match_one	match_two
Initial	47	173	0
Internal	122	32	829
Terminal	49	175	0
Single	83	0	0
CDS_no_match	all	short	long	seq_short	seq_long
CDS_no_match	301	258	43	46180	61332
Intergenic	all	between_match	seq_match
Intergenic:	307	98	164977
SvsM  0.19047619047619 vs 0.80952380952381
genes in IvsT all and selected: 1056 116
1, -1.80915121193992
2, -1.61809597517721
3, -1.66254773774805
4, -2.11453286149111
5, -2.11453286149111
8, -2.18864083364483
9, -2.35569491830799
# estimate 1: 0.840909090909091
# estimate 2: 0.921358070662081
# value: 0.921358070662081
IvsT  0.921358070662081 vs 0.0786419293379194
running gm.hmm on local multi-core system
8 contigs in list
concatenate predictions: /ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP/run/EP_C_4
training level EP_C: /ddn/work/cjh/test/braker-20220128/tests/test2/GeneMark-EP/run/EP_C_4
From 1619 loaded 1105 and ignored dublications 0
exon	no_match	match_one	match_two
Initial	47	173	0
Internal	119	32	829
Terminal	49	175	0
Single	83	0	0
CDS_no_match	all	short	long	seq_short	seq_long
CDS_no_match	298	255	43	46219	61332
Intergenic	all	between_match	seq_match
Intergenic:	307	98	164977
SvsM  0.19047619047619 vs 0.80952380952381
genes in IvsT all and selected: 1053 116
1, -1.80915121193992
2, -1.57553636075842
3, -1.66254773774805
4, -2.11453286149111
5, -2.18864083364483
8, -2.18864083364483
9, -2.35569491830799
# estimate 1: 0.84045584045584
# estimate 2: 0.918939263119236
# value: 0.918939263119236
IvsT  0.918939263119236 vs 0.0810607368807644
# predict final gene set
running gm.hmm on local multi-core system
8 contigs in list
8 contigs in list
'''


No content in GeneMark-ET.stderr.

**Comment by KatharinaHoff** [comment]
Have you updated braker & genemark-etp?

The key dependency was recently removed.
