### ISSUE TITLE
file not found data/training.fna

### ISSUE THREAD

**Issue by fraca** [Gaius-Augustus/BRAKER#535]
Hi,
I'm running braker with a bam file mapped with [star](https://github.com/alexdobin/STAR):

`braker.pl --genome_soft.fasta --bam Bud1Aligned.sortedByCoord.out.bam --softmasking --cores 4 --workingdir=prova`

The genome is softmasked based on [RepeatMasker/RepeatModeller](https://www.repeatmasker.org/) and it is composed of 10 big scaffolds (> 35Mbp) and 5 small (around 1000 bp). When I run it I get this error:
` ERROR in file /sw/bioinfo/braker/2.1.6/rackham/scripts/braker.pl at line 6666
Failed to execute: perl /sw/bioinfo/GeneMark/4.68-es/rackham/gmes_petap.pl --verbose --sequence=/crex/proj/uppstore2019057/nobackup/anno_braker2/prova2/genome.fa --ET=/crex/proj/uppstore2019057/nobackup/anno_braker2/prova2/genemark_hintsfile.gff --cores=4 --gc_donor 0.001 --soft_mask auto 1>/crex/proj/uppstore2019057/nobackup/anno_braker2/prova2/GeneMark-ET.stdout 2>/crex/proj/uppstore2019057/nobackup/anno_braker2/prova2/errors/GeneMark-ET.stderr
Failed to execute: perl /sw/bioinfo/GeneMark/4.68-es/rackham/gmes_petap.pl --verbose --sequence=/crex/proj/uppstore2019057/nobackup/anno_braker2/prova2/genome.fa --ET=/crex/proj/uppstore2019057/nobackup/anno_braker2/prova2/genemark_hintsfile.gff --cores=4 --gc_donor 0.001 --soft_mask auto 1>/crex/proj/uppstore2019057/nobackup/anno_braker2/prova2/GeneMark-ET.stdout 2>/crex/proj/uppstore2019057/nobackup/anno_braker2/prova2/errors/GeneMark-ET.stderr
The most common problem is an expired or not present file ~/.gm_key!`
The gm_key is not a problem, I can run the example without problem.
 In the error directory the only file with something is `GeneMark-ET.stderr`, that contains:
`error, file not found: data/training.fna`

This is the `gmes.log`:

`/sw/bioinfo/GeneMark/4.68-es/rackham/gmes_petap.pl : [Tue Oct  4 15:38:36 2022] /sw/bioinfo/GeneMark/4.68-es/rackham/probuild --reformat_fasta --uppercase --allow_x --letters_per_line 60 --out data/dna.fna --label _dna --trace info/dna.trace --in /crex/proj/uppstore2019057/nobackup/anno_braker2/prova/genome.fa  --mask_soft 100 --mask_margin 10 --low2gff data/in_mask.gff 
/sw/bioinfo/GeneMark/4.68-es/rackham/gmes_petap.pl : [Tue Oct  4 15:38:38 2022] /sw/bioinfo/GeneMark/4.68-es/rackham/reformat_gff.pl --out data/et.gff  --trace info/dna.trace  --in /crex/proj/uppstore2019057/nobackup/anno_braker2/prova/genemark_hintsfile.gff  --quiet
/sw/bioinfo/GeneMark/4.68-es/rackham/gmes_petap.pl : [Tue Oct  4 15:38:38 2022] cat  in_mask.gff   >> plus.gff
/sw/bioinfo/GeneMark/4.68-es/rackham/gmes_petap.pl : [Tue Oct  4 15:38:51 2022] /sw/bioinfo/GeneMark/4.68-es/rackham/probuild  --seq data/dna.fna  --allow_x  --stat info/dna.general  --details
/sw/bioinfo/GeneMark/4.68-es/rackham/gmes_petap.pl : [Tue Oct  4 15:39:06 2022] /sw/bioinfo/GeneMark/4.68-es/rackham/probuild  --seq data/dna.fna  --allow_x  --stat_fasta info/dna.multi_fasta
/sw/bioinfo/GeneMark/4.68-es/rackham/gmes_petap.pl : [Tue Oct  4 15:39:13 2022] /sw/bioinfo/GeneMark/4.68-es/rackham/probuild  --seq data/dna.fna  --allow_x  --substring_n_distr info/dna.gap_distr
/sw/bioinfo/GeneMark/4.68-es/rackham/gmes_petap.pl : [Tue Oct  4 15:39:26 2022] /sw/bioinfo/GeneMark/4.68-es/rackham/gc_distr.pl --in data/dna.fna  --out info/dna.gc.csv  --w 1000,8000
/sw/bioinfo/GeneMark/4.68-es/rackham/gmes_petap.pl : [Tue Oct  4 15:39:40 2022] /sw/bioinfo/GeneMark/4.68-es/rackham/probuild  --seq /crex/proj/uppstore2019057/nobackup/anno_braker2/prova/GeneMark-ET/data/dna.fna  --split dna.fa  --max_contig 5000000 --min_contig 50000 --letters_per_line 100 --split_at_n 5000 --split_at_x 5000 --allow_x --x_to_n  --trace ../../info/training.trace`
Any help would be appreciate,

Marco

**Comment by fraca** [comment]
Hi, the problem was related to my reference that was masked in a wrong way. It was mostly in lower case, so I think that gmes_petap.pl was not able to find any region. I corrected the genome and it works

**Comment by woojunbang** [comment]
> Hi, the problem was related to my reference that was masked in a wrong way. It was mostly in lower case, so I think that gmes_petap.pl was not able to find any region. I corrected the genome and it works

Hello. How did you correct your genomes? I have a same problem. Thank you.
I used low-coverage genomes with windowmask program.
Thank you.

**Comment by fraca** [comment]
Hi, my problem was that the initial genome `genome_old.fasta` was  a mix of lower and uppercase letters, so when I softmasked it there were too few genomic regions. Down the commands that i used:
`awk '{print $1"\t"$4"\t"$5}' output_file_from_RepeatMasker.gff > X_soft.BED`
`sed 's/a/A/g' genome_old.fasta | sed 's/t/T/g'  | sed 's/c/C/g'  | sed 's/g/G/g' | sed 's/Chr_/chr_/g' > pro.fa` 
`bedtools maskfasta -soft -fi pro.fa -bed X_soft.BED -fo genome_new.fasta`   
So I think that you should be less stringent with the windowmask program.
