### ISSUE TITLE
ERROR in braker.pl at line 7009, failed to execute: ensure_n_training_genes.py

### ISSUE THREAD

**Issue by joleneyue** [Gaius-Augustus/BRAKER#539]
Dear developer,

i want to use the Tesebra to combine the braker 1 and braker2. 
Braker1 running with RNA bam files does not have any problems. braker 1 is conda version.
however, braker 2 run for the protein.fasta from ORthoDB is problematic. braker 2 is outside conda.
The augustus is conda version too. 

 conda activate base
  
  export AUGUSTUS_BIN_PATH=/home/ubuntu/miniconda3/bin/
  export AUGUSTUS_CONFIG_PATH=/home/ubuntu/miniconda3/config/
  export AUGUSTUS_SCRIPTS_PATH=/home/ubuntu/miniconda3/bin/
  export PYTHON3_PATH=/home/ubuntu/miniconda3/bin/
  export CDBTOOLS_PATH=/home/ubuntu/miniconda3/bin/
  export SAMTOOLS_PATH=/home/ubuntu/miniconda3/bin/
  export BAMTOOLS_PATH=/home/ubuntu/miniconda3/bin/
  export DIAMOND_PATH=/home/ubuntu/miniconda3/bin/
  export PROTHINT_PATH=/home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/ProtHint/bin
  export ALIGNMENT_TOOL_PATH=/home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/gth-1.7.3-Linux_i386-32bit/bin/
  export GENEMARK_PATH=/home/ubuntu/storage2/Yuling/Blasia_starvation_RNAseq_31Aug2021_Novogene/Raw_data_NOVOGENE/braker/gmes_linux_64/
# add to ~/.bashrc to include BRAKER dir into PATH
  export PATH=/home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/BRAKER/scripts:$PATH

braker.pl --genome=./fasta_files/assembly.fasta.PolcaCorrected.FINAL.fasta.masked --prot_seq=proteins.fasta --softmasking --species=Blasiapusilla --epmode 

this is the error occurred: 

ERROR in file /home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/BRAKER/scripts/braker.pl at line 7009 Failed to execute: /home/ubuntu/miniconda3/bin//python3 /home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/BRAKER/scripts/ensure_n_training_genes.py --goodGenes /home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/braker/GeneMark-EP/genemark.f.good.gtf --badGenes /home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/braker/GeneMark-EP/genemark.f.bad.gtf --N 4000 1>/home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/braker/ensure_min_n_training_genes.stdout 2>/home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/braker/errors/ensure_min_n_training_genes.stderr

Could you let me know why this problem happen?

Thanks a lot!
Cheers,
Yuling

**Comment by KatharinaHoff** [comment]
Is there any content in the file
/home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/braker/errors/ensure_min_n_training_genes.stderr
?

**Comment by joleneyue** [comment]
Dear Katharina,

thanks for your reply.

this is  the content of the file:

 ensure_min_n_training_genes.stderr:

Traceback (most recent call last):
  File "/home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/BRAKER/scripts/ensure_n_training_genes.py", line 135, in <module>
    main()
  File "/home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/BRAKER/scripts/ensure_n_training_genes.py", line 101, in main
    goodGenes = loadGenes(args.goodGenes)
  File "/home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/BRAKER/scripts/ensure_n_training_genes.py", line 62, in loadGenes
    for row in csv.reader(open(genesFile), delimiter='\t'):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/Yuling_20June2022/Blasia_genome_annotation/Polca_braker/braker/GeneMark-EP/genemark.f.good.gtf'

it seems there is no genmark.f.good.gtf file .

what could be the problem now? genmark?

Cheers,
Yuling

**Comment by joleneyue** [comment]
This is the filterGenemark.stderr:

Unknown option: hints
Unknown option: randomseed
Rate of good introns cannot be computed since there are no 'mult' entries.
Rate of one exon genes (of good genes) cannot be computed since only complete genes can be 'goood'.
Rate of one exon genes (of all genes) cannot be computed because there are no genes in the input file with the correct format.
~                                                                                                                                                         
~

**Comment by joleneyue** [comment]
@KatharinaHoff 

Dear Katharina,

i solved this problem by removing a filterGenemark.pl script under augustus scripts directory. i do not know why braker did not call this script under braker path. 

now braker 2 finished well,  however, it spit out an errror file : gbFilterEtraining.stderr

gene 61_t transcr. 1 in sequence X2_121043-125100: Terminal exon doesn't end in stop codon. Variable stopCodonExcludedFromCDS set right?
gene 128_t transcr. 1 in sequence X4_121733-125100: Initial exon does not begin with start codon but with gta
gene 161_t transcr. 1 in sequence X5_123062-125100: Terminal exon doesn't end in stop codon. Variable stopCodonExcludedFromCDS set right?
gene 162_t transcr. 1 in sequence X6_1-1543: Initial exon does not begin with start codon but with gac
gene 189_t transcr. 1 in sequence X6_121111-125100: Terminal exon doesn't end in stop codon. Variable stopCodonExcludedFromCDS set right?
gene 190_t transcr. 1 in sequence X7_1-1728: Initial exon does not begin with start codon but with gaa
~                                                                                                                                           
I wondered if this is normal , or something went wrong? i check the *parameters.cfg file, the stopCodonExcludedFromCDS false, is this a problem or not a big deal?

Thanks a lot for your help!
Cheers,
Yuling
