### ISSUE TITLE
Transcripts output

### ISSUE THREAD

**Issue by mictadlo** [Gaius-Augustus/BRAKER#54]
Hi,
I found the below pipeline and I just wonder which one is Braker's transcripts output?

![image](https://user-images.githubusercontent.com/588297/60805022-4e3f2800-a1c2-11e9-9fc7-cd2113092990.png)

Thank you in advance,

Best wishes,

Michal

**Comment by KatharinaHoff** [comment]
It's most likely the augustus.hints.* ... if it goes into e.g. BUCSO or
InterProScan, it's the augustus.hints.aa file, if it is about gene
structure, it's either *.gtf, *.gff, or *.gff3 file (which all contain the
same gene structure information in different formats).

**Comment by mictadlo** [comment]
Thank you.
