### ISSUE TITLE
Format for protein-to-genome alignment

### ISSUE THREAD

**Issue by lh3** [Gaius-Augustus/BRAKER#540]
I developed [miniprot](https://github.com/lh3/miniprot) with preprint [here](https://arxiv.org/abs/2210.08052). A user wants to use miniprot with Braker. She told me that Braker only works with GenomeThreader, exonerate and spaln but not with the miniprot gff3 output. Does Braker work with generic gff3? If so, what specific features or attributes does Braker look for in gff? I may add a Braker-style gff3 output to miniprot if you may provide the specifics. Thank you.

**Comment by KatharinaHoff** [comment]
Actually, we are internally already playing with miniprot for generating
AUGUSTUS hints, at the moment (not for generating training genes, it's not
exactly part of the BRAKER project). @nvnenasheva , please keep this issue
in mind. There are synergistic effects with your current experiments. Here,
we do not need CDSpart hints, but the original CDS features. It might be
helpful for you to get in touch with Heng Li if you have not finished
writing the parser, yet.

The GenomeThreader functionalities will be completely removed from BRAKER
in the next release. Therefore, it is unlikely that miniprot training will
end up being included in BRAKER. We may release a differently named
pipeline for these purposes. Timeline: currently unknown, but not much
development needed. We should stay in touch.

**Comment by KatharinaHoff** [comment]
This issue resulted in the development of GALBA: https://github.com/Gaius-Augustus/GALBA
