### ISSUE TITLE
Annotation score is >90% BUT Gene Number is very high , almost double 

### ISSUE THREAD

**Issue by vinitamehlawat** [Gaius-Augustus/BRAKER#541]
Hi,

I am working on vertebrates, I have annotated (BRAKER2) a novel genome with distantly related species because near species are not annotated. I used following command: 
` braker.pl --genome=/path/genome.fa  --prot_seq=/path/ref-protein seq.faa --softmasking --core 40`

I got output braker.gtf and counted the gene number which are almost ~42000 but in my Ref genome there are ~21000 genes. Could you please help me to understand this issue.

(I haven,t mask my genome, is this the only reason that I am getting very high number of genes), Do I need to Mask this genome before running BRAKER2.

Looking forward to your reply!

Thanks
Vinita

**Comment by vinitamehlawat** [comment]
Hi, 

I am explaining in detail here where I am confused actually:

I counted the fasta seq in ref genome protein files which are ` 47030 ` and then I counted the sequnces in ` augustus.hints.aa` and ` augustus.hints.codingseq` which are ` 481451` . Is there something going wrong. It would be grate if you could explain this to me wether this is right or wrong.

**Comment by vinitamehlawat** [comment]
Hi @KatharinaHoff 

Thank you so much for your promt response. Did you mean that No need to Masking of genome and I can consider these results, OR what exactly your mean t ' Human Parameter ' .  Sorry to bother you again But I am very newbie to this field.

**Comment by KatharinaHoff** [comment]
A vertebrate genome should definitely be repeat masked.

Do not use Braker to train vertebrate parameters. The existing human
parameters work better for vertebrates.

vinitamehlawat ***@***.***> schrieb am Do. 27. Okt. 2022 um
17:59:
