### ISSUE TITLE
run test1 error

### ISSUE THREAD

**Issue by Henry-Ding** [Gaius-Augustus/BRAKER#545]
hi,
I installed Augustus 3.5.0, but when I try to run test1.sh the program not called finished like others. error in file ensure_min_n_training_genes.stderr, although it looks just a warning.
`ensure_n_training_genes.py: warning: File with "bad" genes does not have enough genes to ensure 4000 genes. Adding all "bad" genes to the "good" gene set.`
looking forward to the answer.
best wish.
Ding

**Comment by KatharinaHoff** [comment]
In a test run, this is not a problem. In a real run, you should be careful with the results. Our test data set is small.
