### ISSUE TITLE
Tesebra gene predictions are very low 

### ISSUE THREAD

**Issue by joleneyue** [Gaius-Augustus/BRAKER#548]
Dear Developer,

I use the tesebra to combine braker 1 and braker 2. 

braker 1 i run 👍 

braker.pl --genome=./fasta_files/ISAR.hipmer.final_assembly.FINAL.fasta.masked  --species=4  --bam=./bam_files/Cday1_1.bam,./bam_files/Cday1_2.bam,./bam_files/Cday1_3.bam,./bam_files/Cday2_1.bam,./bam_files/Cday2_2.bam,./bam_files/Cday2_3.bam,./bam_files/Cday3_3.bam,./bam_files/Cday3_1.bam,./bam_files/Cday3_2.bam,./bam_files/Cday7_1.bam,./bam_files/Cday7_2.bam,./bam_files/Cday7_3.bam,./bam_files/Cday8_1.bam,./bam_files/Cday8_2.bam,./bam_files/Cday8_3.bam,./bam_files/Cday9_1.bam,./bam_files/Cday9_2.bam,./bam_files/Cday9_3.bam,./bam_files/Cday10_1.bam,./bam_files/Cday10_2.bam,./bam_files/Cday10_3.bam,./bam_files/Sday1_1.bam,./bam_files/Sday1_2.bam,./bam_files/Sday1_3.bam,./bam_files/Sday2_1.bam,./bam_files/Sday2_2.bam,./bam_files/Sday2_3.bam,./bam_files/Sday3_1.bam,./bam_files/Sday3_2.bam,./bam_files/Sday3_3.bam,./bam_files/Sday7_1.bam,./bam_files/Sday7_2.bam,./bam_files/Sday7_3.bam,./bam_files/Sday8_1.bam,./bam_files/Sday8_2.bam,./bam_files/Sday8_3.bam,./bam_files/Sday9_1.bam,./bam_files/Sday9_2.bam,./bam_files/Sday9_3.bam,./bam_files/Sday10_1.bam,./bam_files/Sday10_2.bam,./bam_files/Sday10_3.bam --softmasking   

braker 2 i run:

braker.pl --genome=./fasta_files/ISAR.hipmer.final_assembly.FINAL.fasta.masked --prot_seq=proteins.fasta --softmasking --species=blasia_feywei_9sca --epmode 

then i run tesebra:

./TSEBRA/bin/tsebra.py -g braker1/augustus.hints.gtf,braker2/augustus.hints.gtf -c TSEBRA/config/default.cfg -e braker1/hintsfile.gff,braker2/hintsfile.gff -o braker1+2_combined.gtf

then i run 
./get_general_stats.pl -g braker1.gtf > eval_general_stats
./get_general_stats.pl -g braker1.gtf > eval_general_stats
./get_general_stats.pl -g braker1+2_combined.gtf > eval_general_stats

It turns out that braker 1 predicted 20k or so genes, and braker 2 predicted 15k genes, but after combining, the genes predicted is only 11k.

previously i used trinity with pasa pipeline  to de denovo assemble the transcriptomes with genome guided. it has 22k genes.

Now this 11k is too low in my case. as i works with bryophytes species, it usually has around 20-30k genes.

It will be great that you can return to me.Thanks  a lot!

Cheers,
Yuling

**Comment by KatharinaHoff** [comment]
TSEBRA by default discards genes without evidence. You can force TSEBRA to keep genes without evidence from one of the gene sets. Should be described somehwere in the TSEBRA respository. @LarsGab
