### ISSUE TITLE
How similar have to be two organisms to be considered 'short evolutionary distance'?

### ISSUE THREAD

**Issue by lpereira89** [Gaius-Augustus/BRAKER#549]
I would like to use BRAKER2 to annotate a genome from a grass species from the family Aristidoideae. There are no genome available for this family, so I do not have a protein fasta file to use. There are some RNA-seq data, but I am not sure whether the quality will be enough, and these sequences are obtained only from leaf tissue.

Could I also use proteins from any other species from a PACMAD clade, or a combination of all of them, considering them 'short evolutionary distance'? If not, would you recommend to use these proteins as 'longer evolutionary distance' and also the RNA-seq data in two different runs? Is there a way to combine the results to improve accuracy?

Thank you!

**Comment by KatharinaHoff** [comment]
Please use BRAKER2 with the OrthoDB Plants partition. You can add whatever
proteins of a close relative you have at hand to the OrthoDB fasta file
(but it likely doesn't make much of a difference if you add anything).

Please use BRAKER1 with the RNA-Seq data that you have.

If both runs are successful, you can combine them with TSEBRA.

Using BRAKER2 with a large protein database is in the vast majority of
cases superior to using proteins of one close relative for generating
training genes for AUGUSTUS.
