### ISSUE TITLE
Improving gene prediction by filtering BAM files

### ISSUE THREAD

**Issue by mictadlo** [Gaius-Augustus/BRAKER#55]
Hi,
At the moment I have filtered BAM files in the following way: 

`> sambamba view -h -t 2 -F "not (unmapped or secondary_alignment) and mapping_quality >= 30" SRR1043177.fastp.fastq.gz-hisat2.sorted.bam | samtools view -f 0x2 - `

Should I also add `mapping_quality >= 30` and do you have any recommendations for filtering BAM files to improve gene prediction?

Thank you in advance,

Michal

**Comment by KatharinaHoff** [comment]
No, I usually don't filter BAM files.

Katharina
