### ISSUE TITLE
The provided input data is not sufficient for running braker.pl!

### ISSUE THREAD

**Issue by abcyulongwang** [Gaius-Augustus/BRAKER#550]
Hello!
I ran the braker with the bam file I got from the RNA evidence, but the braker.log file gave this error.
![image](https://user-images.githubusercontent.com/93254434/202831146-76f2183a-31e1-4a82-a8a6-572f85e34f36.png)

In fact, I used hisat2 to align the transcriptome data with the reference genome, the bam as the braker input file was obtained by extracting the unaligned sequences above using samtools, and My purpose is to use these RNA evidences to annotate sequences outside the reference genome of this species. I don't know if the braker can predict this.

Looking forward to hearing from you!
Best 
yulong

**Comment by KatharinaHoff** [comment]
That looks like you have hardly any spliced alignments. You can't run BRAKER1 with that data set. Try running BRAKER2, instead.
