### ISSUE TITLE
The Useexisting parameter of BRAKER when turned on will ignore the hints generated previously from proteins and rna-seq during the training of augustus?

### ISSUE THREAD

**Issue by nle202** [Gaius-Augustus/BRAKER#551]
I am using BRAKER to predict genes for a non-model fish. To generate hints, I used its rna-seq data and the vertebrate proteins, while also switching on the trained parameters for zebrafish (--species=zebrafish --useexisting). The log file of BRAKER shows that it still processed hints from my protein and rna-seq.bam files, but unlike when I didn't use the zebrafish parameters, etraining was not run at all, which I understand to mean despite the hints generated, in the end BRAKER only used the zebrafish model to operate augustus. Is this understanding correct?

This issue #497 is relevant to mine, but I don't quite understand what you meant by "All the parameters will be overwritten by etraining", especially when I didn't see etraining ran when I specified a pre-existing set of parameters. In my case, it seems more like etraining was superseded by the pre-existing model of zebrafish.

Thanks,
Ninh

**Comment by KatharinaHoff** [comment]
--useexisting is too confusing. We will remove this option. --skipAllTraining skips training - and people understand that option ;-)
