### ISSUE TITLE
Gene number predicted in Braker.gtf is the same as Augustus.hints.gtf/gff.

### ISSUE THREAD

**Issue by yangkaiyanyangkaiyan** [Gaius-Augustus/BRAKER#552]
Prediction have successfully finished by braker, and i get several output files from braker, but i found that the number of gene in braker.gtf is the same as Augustus.hints.gtf/gff. i do not known is there any poblems? 
i used genome with soft masking and 6 RNAseq data, merged several homologous protein files into one. The command line is as follows:
braker.pl --cores 40 --species=myspecies
--genome=myspecies.fa --softmasking 
--bam=./RNA_seq_prediction/mapping/T01_RNAseq.sort.bam,
./RNA_seq_prediction/mapping/T02_RNAseq.sort.bam,
./RNA_seq_prediction/mapping/T03_RNAseq.sort.bam,
./RNA_seq_prediction/mapping/T04_RNAseq.sort.bam,
./RNA_seq_prediction/mapping/T05_RNAseq.sort.bam,
./RNA_seq_prediction/mapping/T06_RNAseq.sort.bam 
--gff3 --prot_seq=./homo_pr.faa --prg=exonerate &

**Comment by KatharinaHoff** [comment]
Please do not run BRAKER like this. We will soon release BRAKER3, which will support the RNA-Seq and protein input, simultaneously. Until then, please run

1. BRAKER1 with the RNA-Seq data
2. GALBA with your proteins from a close relative
3. TSEBRA to combine the two gene sets

Once BRAKER3 is available, please concatenate a suitable OrthoDB partition with your protein file before using BRAKER3.
