### ISSUE TITLE
Clarification on BAM files used in BRAKER

### ISSUE THREAD

**Issue by Jokendo-collab** [Gaius-Augustus/BRAKER#554]
I am new in annotation and I have the following types of data:

1. PacBio HiFi reads
2. Illumina short reads

I understand tha BRAKER needs the bam files as input. Do I use the bam files from the long or short reads? I am confused here.

**Comment by KatharinaHoff** [comment]
Use the short read data to run BRAKER1.

Follow the protocol https://github.com/Gaius-Augustus/BRAKER/blob/master/docs/long_reads/long_read_protocol.md to integrate long read information. It may or may not improve results.
