### ISSUE TITLE
ERROR in file ~/braker.pl at line 6586  ;  gmes_petap.pl line 1946.

### ISSUE THREAD

**Issue by lyh-bio** [Gaius-Augustus/BRAKER#555]
ERROR in file /mnt/label/home/home/yuanhao/software/BRAKER-2.1.6/scripts/braker.pl at line 6586
Failed to execute: perl /mnt/label/home/home/yuanhao/software/gmes_linux_64/gmes_petap.pl --verbose --cores=58 --ES --gc_donor 0.001 --sequence=/mnt/label/home/home/yuanhao/基因组组装/braker2/braker/genome.fa  --soft_mask auto 1>/mnt/label/home/home/yuanhao/基因组组装/braker2/braker/GeneMark-ES.stdout 2>/mnt/label/home/home/yuanhao/基因组组装/braker2/braker/errors/GeneMark-ES.stderr
The most common problem is an expired or not present file ~/.gm_key!

GeneMark-ES.stderr
Use of uninitialized value $name in open at /mnt/label/home/home/yuanhao/software/gmes_linux_64/gmes_petap.pl line 1946.
Use of uninitialized value $name in concatenation (.) or string at /mnt/label/home/home/yuanhao/software/gmes_linux_64/gmes_petap.pl line 1946.
error on creating file : No such file or directory

How do I solve this problem?
Thanks！

**Comment by zhangjie763** [comment]
I met the same problem.
 Have you solved it?
thanks。

**Comment by lyh-bio** [comment]
I failed to run the manual installation and later used conda to install it.
---- Replied Message ----
| From | ***@***.***> |
| Date | 07/26/2023 13:36 |
| To | Gaius-Augustus/BRAKER ***@***.***> |
| Cc | lyh-bio ***@***.***>,
State ***@***.***> |
| Subject | Re: [Gaius-Augustus/BRAKER] ERROR in file ~/braker.pl at line 6586 ; gmes_petap.pl line 1946. (Issue #555) |

I met the same problem.
Have you solved it?
thanks。

**Comment by zhangjie763** [comment]
I refer to the following two links and， also use conda to install braker2.

https://www.jianshu.com/p/69e80194783c
https://www.jianshu.com/p/047216b469e7

But in the end, the error message about gmes_petap.pl  appeared again. 

Have you successfully completed the genome structure annotation?

**Comment by zhangjie763** [comment]
If possible, I hope to communicate with you further by using qq,
 1448330377. This is my contact method. 
Looking forward to your reply，thank you.

**Comment by lyh-bio** [comment]
QQ 联系。
---- Replied Message ----
| From | ***@***.***> |
| Date | 07/26/2023 14:35 |
| To | Gaius-Augustus/BRAKER ***@***.***> |
| Cc | lyh-bio ***@***.***>,
State ***@***.***> |
| Subject | Re: [Gaius-Augustus/BRAKER] ERROR in file ~/braker.pl at line 6586 ; gmes_petap.pl line 1946. (Issue #555) |

I refer to the following two links and， also use conda to install braker2.

https://www.jianshu.com/p/69e80194783c
https://www.jianshu.com/p/047216b469e7

But in the end, the error message about gmes_petap.pl appeared again.

Have you successfully completed the genome structure annotation?
