### ISSUE TITLE
File gmhmme3 is not an executable or does not exist

### ISSUE THREAD

**Issue by DiegoSafian** [Gaius-Augustus/BRAKER#558]
Hi,

I am running the check_install.bash script and I am getting the following error:

Checking GeneMark-ES installation
Checking Perl setup
All required Perl modules were found
Checking GeneMark.hmm setup
File gmhmme3 is not an executable or does not exist

The problem is that gmhmme3 does exist and it is executable.
-rwxrwx---+ 1 user domain users 1742336 Oct 23 04:18 gmhmme3

I just downloaded the last version GeneMark-ES/ET/EP ver 4.71_lic LINUX 64 kernel 2.6 - 4 from http://topaz.gatech.edu/GeneMark/license_download.cgi

I have also used the change_path_in_perl_scripts.pl as I am using an anaconda environment

Help please!

**Comment by KatharinaHoff** [comment]
Did you solve this problem?

**Comment by KatharinaHoff** [comment]
I assume that this problem was solved. Please re-open if it persists.
