### ISSUE TITLE
Adding functional annotation and meta-data in braker.gtf

### ISSUE THREAD

**Issue by Jokendo-collab** [Gaius-Augustus/BRAKER#560]
I have the `braker.gtf` and I want to add the actual gene symbols instead of `transcript_id "file_1_file_1_g38303.t1"; gene_id "file_1_file_1_g38303"` . IS there a way this can be achieved?

**Comment by KatharinaHoff** [comment]
You mean functional annotation? We do not perform any kind of functional annotation in BRAKER (and are not planning to add this).
