### ISSUE TITLE
How to add more weight to RNA-Seq data when predicting with Braker 

### ISSUE THREAD

**Issue by jcniabemr** [Gaius-Augustus/BRAKER#563]
I have noticed after running Braker with a .bam alignment file produced using STAR with a ref genome and RNA-Seq data that in the Braker gene predictions, multiple genes are missing some of which have 1000+ supporting reads that can be seen when viewing the .bam alignment file. 

I have seen that it is possible to add more weight to external evidence such as RNA-Seq data by increasing the value following 1 after "E". However it seems that there are multiple files such as "extrinsic.cfg" and "extrinsic.E.cfg". I'm not sure which file I should be editing to increase the weight of RNA-Seq data as evidence?

**Comment by arslan9732** [comment]
Hi, @jcniabemr 
braker is using the following `rnaseq.cfg` file while running Augustus:
`https://github.com/Gaius-Augustus/BRAKER/blob/master/scripts/cfg/rnaseq.cfg` 
You can see that the value is 1 after E.

**Comment by KatharinaHoff** [comment]
It's not 1... it's 1e6 . I mean, yes, there is a 1 after the E. But that
indicates the number of gradients. The 1e6 is what you want to modify if
you modify something. Most likely.
