### ISSUE TITLE
How to continue braker where it failed?

### ISSUE THREAD

**Issue by arslan9732** [Gaius-Augustus/BRAKER#564]
Hi,
I tried to run braker2 on my dataset (genome size is 3.1G with 10 Illumina RNASeq and 2 ISOseq), but it failed at `TRAINING AUGUSTUS UTR PARAMETERS` step while it was running `bamtools merge` due to the memory issue. Is it possible to run it where it failed?

The command I am using is the following:
```
braker.pl --cores=${NSLOTS} \
--species=Test.sc \
--genome=${GENOME} \
--softmasking \
--UTR=on \
--bam=${ALL_BAM} \
--gff3 \
--workingdir=Braker_Test
```

**Comment by KatharinaHoff** [comment]
I recommend to not train UTR parameters. Start a run without UTR parameter training.

[BRAKER is not cleanly designed to restart at that particular point.]
