### ISSUE TITLE
braker3 - no etp_release.pl 

### ISSUE THREAD

**Issue by Thamos** [Gaius-Augustus/BRAKER#565]
Hi, when running braker3 I had the error that "etp_release.pl" wasn't anywhere to be found in GeneMark-ETP/bin/ and so the tests (test1.sh, test2.sh, test3.sh) didn't work.
I downloaded GeneMark-ETP from https://github.com/gatech-genemark/GeneMark-ETP

I think I solved the problem by creating a symbolic link of the script gmetp.pl, naming it etp_release.pl. It's running now with real data and I'm eagerly awaiting the first results. :)

If somebody else has problems running braker3 I recommed also looking at my issue at GeneMark-ETP
https://github.com/gatech-genemark/GeneMark-ETP/issues/1

**Comment by KatharinaHoff** [comment]
The problem is that you need GeneMark-ETP. It is not available at
http://topaz.gatech.edu/genemark/license_download.cgi at the moment. You
have to wait until it is available.

Thamos ***@***.***> schrieb am Mi. 18. Jan. 2023 um 00:26:

**Comment by Thamos** [comment]
Readme says 

"Download GeneMark-ETP from https://github.com/gatech-genemark/GeneMark-ETP or https://topaz.gatech.edu/GeneMark/etp.for_braker.tar.gz. Unpack and install GeneMark-ETP as described in GeneMark-ETP’s README file."

so that's why I downloaded it from github. Anyway with the changes tests ran successfully now and I'm trying with real data.

**Comment by KatharinaHoff** [comment]
Then we need to change the docs probably. @LarsGab we are apparently providing conflicting information?

**Comment by Thamos** [comment]
Is there a reason to not use the version on github? Because if e.g. there are problems with the results I'll cancel the run and won't use braker3 for now.

**Comment by KatharinaHoff** [comment]
We are not sure. I was not allowed to put it into the container because
they said sth was not optimal with the code. Unless sth changed on Github
during PAG.

Thamos ***@***.***> schrieb am Mi. 18. Jan. 2023 um 02:40:

**Comment by KatharinaHoff** [comment]
Ok, they did change sth. Maybe that’s what they will release. I am not at
PAG, so nobody told me. We will adapt documentation.

Katharina Hoff ***@***.***> schrieb am Mi. 18. Jan. 2023 um
02:43:

**Comment by Thamos** [comment]
Ah well then I will just let it run and check when it's finished or there's an error.
Btw really nice that there's the container now. I remember setting up braker2 took a bit of time, now it's just one command :)

**Comment by kashiff007** [comment]
Hi Braker3 Team, I am trying to use the braker3 but facing the problem of missing file etp_release.pl.
I am also unable to find this file in https://github.com/gatech-genemark/GeneMark-ETP. 

I am wondering the braker3 is available to use?

**Comment by KatharinaHoff** [comment]
Regrettably we all need to remain patient. ETP availability is out of our
hands. Hang in there and wait with us…

Kashif Nawaz ***@***.***> schrieb am Di. 31. Jan. 2023 um
14:40:

**Comment by Thamos** [comment]
@kashiff007
Just do what I described in the first post of this issue, the etp repository didn't get changed except for bugfixes.
So in commands it would be
"ln -s gmetp.pl etp_release.pl" from inside the etp bin folder.

**Comment by kashiff007** [comment]
@Thamos, its working. Thank you

**Comment by KatharinaHoff** [comment]
It is currently NOT working properly (as expected) for larger genomes.
That’s why we are waiting for a fix on the ETP side.


Kashif Nawaz ***@***.***> schrieb am Mi. 1. Feb. 2023 um
08:12:

**Comment by kashiff007** [comment]
@KatharinaHoff Thanks for the clarification. I am running multiple annotators and will compare them.

**Comment by sqwwww** [comment]
Hi,  I am trying to use the braker3 and met the same problem, I download GeneMark-ES/ET/EP ver 4.71_lic from http://topaz.gatech.edu/GeneMark/license_download.cgi, there is no etp_release.pl, and no gmetp.pl mentioned above. Is there a way to figure it out?
I show what I have download in the picture.
![image](https://user-images.githubusercontent.com/98629662/220269114-d583813e-00ac-4168-9de4-f6fddad0ee1d.png)

**Comment by mericl** [comment]
I have the exact same issue "WARNING: Couldn't find etp_release.pl" after following the directions to "git clone https://github.com/gatech-genemark/GeneMark-ETP.git" and setting my ETP path correctly (using both $GENEMARK_PATH and $ETP), is there any update on this issue?

**Comment by sqwwww** [comment]
> I have the exact same issue "# WARNING: Couldn't find" after following the directions to "git clone https://github.com/gatech-genemark/GeneMark-ETP.git" and setting my ETP path correctly (using both $GENEMARK_PATH and $ETP), is there any update on this issue?

I'm also confused about it, it seems that GeneMark changed a lot, and braker doesn't adapt to the new changes. I turned to funannotate and some other tools for gene annotation.

**Comment by KatharinaHoff** [comment]
Some of us are out of office. You need to wait until we are back. Sorry.
Update will definitely happen.

sqwwww ***@***.***> schrieb am Fr. 24. Feb. 2023 um 03:59:

**Comment by KatharinaHoff** [comment]
The container has today been updated to contain GeneMark-ETP. You still have to install the license key file in your home directory (license key of GeneMark-ES/ET/EP works) as file ~/.gm_key. Otherwise, it should be very easy to run, now.

**Comment by Thamos** [comment]
Are the dependencies for UTR prediciton included too? I think in the last version they weren't.

**Comment by KatharinaHoff** [comment]
No.

Thamos ***@***.***> schrieb am Do. 2. März 2023 um 20:20:
