### ISSUE TITLE
My  long read RNA-Seq was from Nanopore, I was wondering how can i run braker with it.

### ISSUE THREAD

**Issue by Catherine9826** [Gaius-Augustus/BRAKER#567]
I only saw the protocol for integration of assembled subreads from PacBio ccs sequencing in combination with short read Illumina RNA-Seq and protein database, i don't know whether it can works with my nanopore RNA-seq. Or can i list short read Illumina RNA-Seq and  long read RNA-Seq together liike: --bam=shortread.bam,longread.bam?

  Thanks for your answer.

**Comment by KatharinaHoff** [comment]
You can of course provide the combined list of bam files. However, this
uses only the intron information from RNA-Seq. Whether it makes sense to
call genes in the assembled transcripts probably depends on the sequencing
error rate. If it's low error rate, it will probably work very well. If not
-> not. There were several recent updates by Oxford Nanopore, so I am not
sure how your error rate is...
