### ISSUE TITLE
miniprot instead of GenomeThreader

### ISSUE THREAD

**Issue by arslan9732** [Gaius-Augustus/BRAKER#568]
Hi,
Is it possible to use miniprot alignment output instead of GenomeThreader or Exonerate. Because miniprot is very fast as compare to both of these?

**Comment by KatharinaHoff** [comment]
https://github.com/Gaius-Augustus/GALBA

Use GALBA 😉

Arslan Tariq ***@***.***> schrieb am Fr. 3. Feb. 2023 um
16:46:

**Comment by arslan9732** [comment]
Thank you. I will try it.

**Comment by arslan9732** [comment]
I have trained model with braker. Now I tried to use proteome data with the trained model, but GALBA give error:
```
# Fri Feb  3 17:51:16 2023: ERROR: in file GALBA/scripts/galba.pl at line 2790
Augustus-3.5.0/config/species/SP already exists. Choose another species name, delete this directory, or use the existing species with the option --useexisting. Be aware that existing parameters will then be overwritten during training.
```
But when I use `--useexisting` flag galba failed with this error.
```
Unknown option: useexisting
Error in command line arguments
```

**Comment by KatharinaHoff** [comment]
Try —skipAllTraining instead

Arslan Tariq ***@***.***> schrieb am Fr. 3. Feb. 2023 um
17:54:

**Comment by KatharinaHoff** [comment]
Leave this open. I will fix this end of February

Katharina Hoff ***@***.***> schrieb am Fr. 3. Feb. 2023 um
18:58:
