### ISSUE TITLE
"error: Alignment is missing after header "

### ISSUE THREAD

**Issue by vpymerel** [Gaius-Augustus/BRAKER#569]
Hello,

Using braker2 with odb10 as protein evidence, I got a few of these error messages: "error: Alignment is missing after header " (coming from ProtHint ?),

Do you know why this error occurs ?

Thank you,
V

**Comment by tomasbruna** [comment]
This can be safely ignored, as long as BRAKER2 finishes without other issues.

**Comment by vpymerel** [comment]
Thank you !
