### ISSUE TITLE
BRAKER miss some genes

### ISSUE THREAD

**Issue by mictadlo** [Gaius-Augustus/BRAKER#57]
Hi,
I ran `braker.pl --UTR=on --genome=$1 --bam=$2 --species=$3 --cores 20 --softmasking --gff3` but in few cases, Braker did not predict any genes where there is RNA-Seq alignment.

Is there a way to get still gene predictions in those areas?

Thank you in advance,

Michal

**Comment by KatharinaHoff** [comment]
You can try re-running AUGUSTUS outside of BRAKER in the region in question (local prediction, augustus has parameters for predictionStart and predictionEnd) with the evidence, maybe play with the extrinsic configuration parameters for these separate runs.
