### ISSUE TITLE
Gene ID is not unique

### ISSUE THREAD

**Issue by awesomedeer** [Gaius-Augustus/BRAKER#571]
Hello BRAKER group
I successfully ran the BRAKER2(v 2.1.6) pipeline using one of my genome assembly, although it is a bit different from previous runs with other genomes(lack of augustus.gtf but keep braker.gtf).
The major point is I have same gene ids in two diffenrent chromosomes and I only notice this when I run the script (rename_gtf.py)
`Chr7D	GeneMark.hmm3	start_codon	33684510	33684512	.	+	0	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t";
Chr7D	GeneMark.hmm3	CDS	33684510	33684894	.	+	0	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t"; cds_type "file_1_file_2_Initial"; count "file_1_file_2_1_3";
Chr7D	GeneMark.hmm3	exon	33684510	33684894	0	+	.	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t"; cds_type "file_1_file_2_Initial"; count "file_1_file_2_1_3";
Chr7D	GeneMark.hmm3	CDS	33685600	33685650	.	+	2	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t"; cds_type "file_1_file_2_Internal"; count "file_1_file_2_2_3";
Chr7D	GeneMark.hmm3	exon	33685600	33685650	0	+	.	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t"; cds_type "file_1_file_2_Internal"; count "file_1_file_2_2_3";
Chr7D	GeneMark.hmm3	CDS	33685976	33686091	.	+	2	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t"; cds_type "file_1_file_2_Terminal"; count "file_1_file_2_3_3";
Chr7D	GeneMark.hmm3	exon	33685976	33686091	0	+	.	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t"; cds_type "file_1_file_2_Terminal"; count "file_1_file_2_3_3";
Chr7D	GeneMark.hmm3	stop_codon	33686089	33686091	.	+	0	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t";
Chr8A	GeneMark.hmm3	stop_codon	2331991	2331993	.	-	0	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t";
Chr8A	GeneMark.hmm3	CDS	2331991	2332489	.	-	1	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t"; cds_type "file_1_file_2_Terminal"; count "file_1_file_2_2_2";
Chr8A	GeneMark.hmm3	exon	2331991	2332489	0	-	.	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t"; cds_type "file_1_file_2_Terminal"; count "file_1_file_2_2_2";
Chr8A	GeneMark.hmm3	CDS	2334027	2334415	.	-	0	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t"; cds_type "file_1_file_2_Initial"; count "file_1_file_2_1_2";
Chr8A	GeneMark.hmm3	exon	2334027	2334415	0	-	.	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t"; cds_type "file_1_file_2_Initial"; count "file_1_file_2_1_2";
Chr8A	GeneMark.hmm3	start_codon	2334413	2334415	.	-	0	gene_id "file_1_file_2_113233_g"; transcript_id "file_1_file_2_113233_t";
`
I have no idea why this happen and how to solve it.

Best regards
Song

**Comment by LarsGab** [comment]
Hi,

in BRAKER v2.1.6, the output `braker.gtf` can have problems with their geneIDs. We recommend in the older versions (before 3.0.0) to use `augustus.hints.gtf` as BRAKER output. However, you can fix the geneIDs with [this](https://github.com/Gaius-Augustus/TSEBRA/blob/main/bin/fix_gtf_ids.py) script.
After BRAKER 3.0.0, this bug has been fixed and `braker.gtf` can be used safely.

Best, 
Lars
