### ISSUE TITLE
The hints file(s) for GeneMark-EX contain less than 150 introns with multiplicity >= 4!

### ISSUE THREAD

**Issue by amvarani** [Gaius-Augustus/BRAKER#572]
Hi there, 

I'm trying to annotate a Myrtaceae genome, and BRAKER (epmode) got stuck on this message below
I'm using as a reference the OrthoDB plants for proteins models

I got the same error message even after adding on the  OrthoDB plants proteins sequence for a very close related species

The pipeline is using ProtHint Version 2.6.0

for other plant genomes the braker epmode runs well

help, please! :) 

#**********************************************************************************
#                              RUNNING GENEMARK-EX                                 
#**********************************************************************************
# Fri Feb 10 09:43:26 2023: Preparing genemark_evidence file hints from manual hints...
# Fri Feb 10 09:43:26 2023: Checking whether file /home/amvarani/Feijoa-Goiaba/Goiaba/ANNOT/BRAKER/guava-Bprotein_out/genemark_hintsfile.gff contains enough hints and sufficient multiplicity information...
#*********
# WARNING: 
# The hints file(s) for GeneMark-EX contain less than 150 introns with multiplicity >= 4! (In total, 1313 unique introns are contained. 19 have a multiplicity >= 4.)
# Possibly, you are trying to run braker.pl on data that does not provide sufficient multiplicity information. This will e.g. happen if you try to use introns generated from assembled RNA-Seq transcripts; or if you try to run braker.pl in epmode with mappings from proteins without sufficient hits per locus. Or if you use the example data set.
# A low number of intron hints with sufficient multiplicity may result in a crash of GeneMark-EX (it should not crash with the example data set).
#*********

**Comment by KatharinaHoff** [comment]
This problem arises if there is insufficient extrinsic evidence for running BRAKER. The situation can possibly be improved by genome assembly improvement, or by adding more proteins from closely related species to the OrthDB partition.
