### ISSUE TITLE
Can memory usage be reduced?

### ISSUE THREAD

**Issue by S-111** [Gaius-Augustus/BRAKER#573]
Now I am predicting genes on 1.5Gb genome using the protein sets from OrthoDB.
command
```
braker.pl --genome=genome.fasta.masked \
    --prot_seq proteins.fasta --softmasking --cores 48
```
Checking the logs showed that a large amount of memory (2244.3GB) was being used, and braker2 was stopped by out of memory.
Can memory usage be reduced?

**Comment by KatharinaHoff** [comment]
Using fewer threads may help if the memory issue occured during augustus with hints predictions. (e.g. run with only 4 threads)
