### ISSUE TITLE
gmes_petap.pl fails to execute when called from braker.pl

### ISSUE THREAD

**Issue by ryan-preble** [Gaius-Augustus/BRAKER#575]
I have genemark installed and have set all environment variables such that braker.pl knows where to find genemark scripts. A few hours into execution, I get the following error message:
`ERROR in file /home/rsp98/programs/BRAKER/braker.pl at line 6675
Failed to execute: perl /home/rsp98/programs/GeneMark/gmes_linux_64/gmes_petap.pl --verbose --sequence=/data/home/rsp98/calochortus/albus/braker/genome.fa --ET=/data/home/rsp98/calochortus/albus/braker/genemark_hintsfile.gff --cores=20 --gc_donor 0.001 --soft_mask auto 1>/data/home/rsp98/calochortus/albus/braker/GeneMark-ET.stdout 2>/data/home/rsp98/calochortus/albus/braker/errors/GeneMark-ET.stderr
Failed to execute: perl /home/rsp98/programs/GeneMark/gmes_linux_64/gmes_petap.pl --verbose --sequence=/data/home/rsp98/calochortus/albus/braker/genome.fa --ET=/data/home/rsp98/calochortus/albus/braker/genemark_hintsfile.gff --cores=20 --gc_donor 0.001 --soft_mask auto 1>/data/home/rsp98/calochortus/albus/braker/GeneMark-ET.stdout 2>/data/home/rsp98/calochortus/albus/braker/errors/GeneMark-ET.stderr
The most common problem is an expired or not present file ~/.gm_key!`

Note that I am able to execute gmes_petap.pl outside of braker with no trouble, and the license key is correctly installed as far as I can tell. 

Edit: I should also note that some of the braker dependencies come from an anaconda environment, and I am attempting to run braker through nohup. I think the PATH variable should still be carried over from the anaconda environment to the nohup process, but I could be wrong.

Another Edit: I discovered that I had an old version of parallel::forkmanager in my environment, I will update that and close the issue if the problem is resolved.

Another another edit: updating parallel::forkmanager did not make it work. As it stands, I cannot run braker despite a working installation of genemark.

**Comment by KatharinaHoff** [comment]
The container has today been updated to contain GeneMark-ETP. You still have to install the license key file in your home directory (license key of GeneMark-ES/ET/EP works) as file ~/.gm_key. Otherwise, it should be very easy to run, now.

**Comment by ryan-preble** [comment]
> The container has today been updated to contain GeneMark-ETP. You still have to install the license key file in your home directory (license key of GeneMark-ES/ET/EP works) as file ~/.gm_key. Otherwise, it should be very easy to run, now.

I looked back at it and the issue was that braker was looking for perl dependencies in my home directory instead of in my anaconda environment. I had all the correct dependencies installed through anaconda, but gmes_petap.pl only ran when I had the perl modules installed in my home directory. Also note that I had not set PERL5LIB, so the anaconda environment should have had the default perl library.
