### ISSUE TITLE
braker3: --softmasking disables softmasking

### ISSUE THREAD

**Issue by Thamos** [Gaius-Augustus/BRAKER#580]
Hi, just looked at the new version and noticed two things (although the softmasking thing was already in the previous version aswell) - 

1) I think in braker2 "--softmasking" enabled softmasking - in braker3 it disables softmasking. This should be mentioned somewhere because I for example thought it would be the same in braker2 and used it in my first runs (still on the first braker3 version though). Also there are error messages that still reflect the old behaviour, e.g. line 3250 in braker.pl

Other than that I'll start a full run with the new version soon and I'm excited for the results.

EDIT: removed the second thing as that was an error on my part, and I just realized that "--softmasking" disabled softmasking in braker2 too, so the behaviour didn't actually change and I guess I always used it wrong and had just assumed from the mentioned error message (and maybe I read it somewhere else too) that "--softmasking" enables softmasking.

EDIT2: I got things mixed up (my first EDIT) because the main branch is braker3 now and I didn't realize this. So ignore my first EDIT, I think in braker2 it worked as I had originally thought. 
At first I was reporting two errors here, there are differences between the main branch braker.pl and the braker3 branch braker.pl., the second error exists only in the "main" branch braker.pl on line 1890 - there is a semicolon at the end that shouldn't be there.

**Comment by JohnUrban** [comment]
Yeah - I ran into this same issue. I was at first using `--softmasking` as in Braker1/Braker2, but kept getting a message about softmasking needing to be turned on. Looking at the new code showed that `--softmasking` option has now become `--softmasking_off` -- and I guess just using the prefix `--softmasking` alone was enough to trigger that option rather than raise an error.

Also `--cores` has become `--threads`.

**Comment by KatharinaHoff** [comment]
Yes, we changed this. Softmasking almost always returns better results. So we decided to make it the default. Also, --cores was changed to --threads because people imagine something else of a core than we originally did. I put it into the release notes of v3.0.1.

**Comment by KatharinaHoff** [comment]
The semicolon was fixed.

**Comment by Thamos** [comment]
Yeah I agree that it should be enabled by default. I just think it's weird that "--softmasking" disables softmasking and think this should be documented somewhere (for people coming from braker2) or changed to only get disabled when the option is "--softmasking_off" and ignore "--softmasking".

**Comment by BenAawf** [comment]
This is just a curious question for you guys, @Thamos, How could you manage to run Braker3 without the GeneMark ETP issue?

**Comment by Thamos** [comment]
@BenAawf Those issues should be fixed as of the new version.
