### ISSUE TITLE
Total Gene Count

### ISSUE THREAD

**Issue by kcl58759** [Gaius-Augustus/BRAKER#581]
Is there a way for me to simply see an output of total genes found? I have done grep "gene" | wc -l but the count is wayyyyyy too high.

**Comment by arslan9732** [comment]
If you are asking to count genes from the output gff file, then use the following line:

`grep -v "^#" augustus.gff3 | awk '$3 == "gene"' | wc -l`

**Comment by kcl58759** [comment]
> If you are asking to count genes from the output gff file, then use the following line:
> 
> `grep -v "^#" augustus.gff3 | awk '$3 == "gene"' | wc -l`

Ok thanks! Does that count every gene only once? i.e. are genes reported for both forward and reverse strands in this file?

**Comment by arslan9732** [comment]
> > If you are asking to count genes from the output gff file, then use the following line:
> > `grep -v "^#" augustus.gff3 | awk '$3 == "gene"' | wc -l`
> 
> Ok thanks! Does that count every gene only once? i.e. are genes reported for both forward and reverse strands in this file?

Yes, it will count genes only once.

**Comment by kcl58759** [comment]
Last question! is Augustus.hints.gtf the same? BRAKER didn't output augustus.gff3.

**Comment by arslan9732** [comment]
No, it is not the same, `augustus.hints.gtf ` is made from augustus.gff3 during training. There are some filtrations which have been applied on augustus.gff3.
But this command is applicable for both of them.
