### ISSUE TITLE
Failed to execute etraining, but train.f.bg file not empty

### ISSUE THREAD

**Issue by mjosmurphy** [Gaius-Augustus/BRAKER#586]
I am running BRAKER2 from my institution's server. I was able to successfully run BRAKER2 with the example .fna file and no extrinsic evidence, as well as run BRAKER2 with the example .fna and example protein database.

However, I am having difficulty running BRAKER2 with my own data. Specifically, I found in the errors directory, in optimize_augustus_stderr the following:

> failed to execute: /share/apps/python/anaconda-3.10/envs/braker2tabix-3.10/bin/etraining --species=Sp_11 --AUGUSTUS_CONFIG_PATH=/home/mjm052/Augustus_stuff/config/  --/Constant/dss_end=4 --/Constant/dss_start=1 --/Constant/ass_start=3 --/Constant/ass_end=2 --/Constant/ass_upwindow_size=25 --/IntronModel/d=525 --/IntronModel/ass_motif_memory=3 --/IntronModel/ass_motif_radius=3 --/ExonModel/tis_motif_memory=3 --/ExonModel/tis_motif_radius=2 --/Constant/trans_init_window=20 --/Constant/init_coding_len=15 --/ExonModel/patpseudocount=5.0 --/ExonModel/etpseudocount=3 --/ExonModel/etorder=2 --/Constant/intterm_coding_len=5 --/ExonModel/slope_of_bandwidth=0.3 --/ExonModel/minwindowcount=10 --/IGenicModel/patpseudocount=5.0 --/IntronModel/patpseudocount=5.0 --/IntronModel/slope_of_bandwidth=0.4 --/IntronModel/minwindowcount=4 --/IntronModel/asspseudocount=0.00266 --/IntronModel/dsspseudocount=0.0005 --/IntronModel/dssneighborfactor=0.00173 --/ExonModel/minPatSum=233.3 --/Constant/probNinCoding=0.23 --/Constant/decomp_num_steps=1  --/augustus/verbosity=0 --/ExonModel/verbosity=0 --/IGenicModel/verbosity=0 --/IntronModel/verbosity=0 --/UtrModel/verbosity=0 --/genbank/verbosity=0  --/ExonModel/outfile=exon-tmp27.pbl --/IntronModel/outfile=intron-tmp27.pbl --/IGenicModel/outfile=igenic-tmp27.pbl --/UtrModel/outfile=utr-tmp27.pbl tmp_opt_Sp_11/curtrain-27

Unlike Issue #34 and Issue #62, my train.f.gb file is not empty. The first 20 lines of the file look like this:

> LOCUS       OU860780.1_Heliconius_sara_genome_assembly,_chromosome:_1_1769-7166   5398 bp  DNA
FEATURES             Location/Qualifiers
     source          1..5398
     mRNA            complement(2993..5383)
                     /gene="2017_t"
     CDS             complement(join(2993..3068,3323..3506,3578..3829,4549..5101
                     ,5127..5254,5338..5383))
                     /gene="2017_t"
BASE COUNT     1533 a   1162 c  1024 g   1679 t
ORIGIN
        1 ctgtcaatat tgtcacatca atcaactaag acgactcaac aaataagtca acatcaattt
       61 aaaatattgt tttatatttg tttgtatatt tttgtaaaat tttagttttc tgtttaagta
      121 aaaaaaacaa aagaatttga tatttttgta ctcaaacaaa aaatgttgat tcgtgatcct
      181 ctggctcgct ctaaaattaa tttgtccaca aattacaata tcatggtcca tattgtatac
      241 tttttaaaat attgttttca tattttatat ctcgaaataa acattcaaac tatcggtctt
      301 ttatttacct tcaacctaca acaataaaat gtcaaacaac tagcgacatc tgtagaactc
      361 cttaatcttt ggaaattgtc tctattgaga taggttatag aatgattaaa taaatattct
      421 atattggcga ggacttacgc acatttttgt aacatatgca tatgacttac acatataata
      481 tattctaatc aaggcctgta atatctctgg ccataaatgg ttttgttaag tttgtaattc
      541 tattaaataa ataaaatata cggctataaa aatatgaaac ataaaactgt tgctgataat

Do you happen to know what could cause this specific problem?
I have included my full log file as an attachment.

Thanks for your consideration!

Sincerely,

Matthew Murphy
[braker-log_troubleshooting.txt](https://github.com/Gaius-Augustus/BRAKER/files/10903641/braker-log_troubleshooting.txt)

**Comment by LarsGab** [comment]
Hi,

there can be several reasons for this issue. Would you mind running it again with the current versions of BRAKER and AUGUSTUS? You can do this by either using our Singularity container or by manually updating them from GitHub.

Best, 
Lars

**Comment by mjosmurphy** [comment]
I should mention, I used the Singularity container to run the program.

**Comment by yaoxkkkkk** [comment]
Hi, I am using the singularity container braker3 on HPC and also meet the same problem that the pipeline stop at `etraining` step and the train.f.bg contained about 12k genes, have you solved the problem?
