### ISSUE TITLE
key file not recognized

### ISSUE THREAD

**Issue by BioLaFu** [Gaius-Augustus/BRAKER#597]
Dear Team, 
I tried to install BRAKER3 on the BRAIN Cluster, but the Genemark_ETP key file does not seem to get recognized. 
What I did:

singularity build braker3.sif docker://teambraker/braker3:latest
singularity exec braker3.sif print_braker3_setup.py

Setup Instructions for BRAKER3 with Singularity

------------------------------------------------
Dear BRAKER3 user,

the following steps are required before you can run BRAKER3 with Singularity:

  1) Please go to the website
     https://github.com/gatech-genemark/GeneMark-ETP
     and read the linked license agreement. You directly find the License text at:
     https://github.com/gatech-genemark/GeneMark-ETP/blob/main/GeneMark_Software_License.txt
     Only proceed if you agree to the license terms. If you are a commercial user or have
     other questions concerning this license, please contact Mark Bordovsky and Alexandre Lomsadze
     at GeorgiaTech to inquire details (contact details at
     http://topaz.gatech.edu/genemark/contact.html).
  2) Download the license key (not the software) for  GeneMark-ES/ET/EP ver 4.71_lic , it's a file
     called gm_key_64.gz.
  3) Unzip the file with:
     gunzip gm_key_64.gz
  4) Move the file to it's final location:
     mv gm_key_64 ~/.gm_key
You are now ready to use the Singularity container for BRAKER3 with GeneMark-ETP.

gunzip gm_key_64.gz
mv gm_key_64 ~/.gm_key

#When I try to run the exec command again I get the same error message, telling me to download the key file... which I already did. Where am I going wrong? I appreciate all the help you can offer.

**Comment by KatharinaHoff** [comment]
This issue has been solved. It was more of a usage problem.
