### ISSUE TITLE
example files missing or test commands wrong

### ISSUE THREAD

**Issue by maleasy** [Gaius-Augustus/BRAKER#6]
I was trying to test my BRAKER installation using `test1.sh` in directory `example/tests`. The braker command is

```sh
braker.pl --genome=../genome.fa --bam=../RNAseq.bam --softmasking --workingdir=$wd
```

however, there is no file `RNAseq.bam` in the `example` directory.  Should it perhaps be

```sh
braker.pl --genome=../genome.fa --hints=../RNAseq.hints --softmasking --workingdir=$wd
```
?

Also, the documentation says there should be a result file called `augustus.gff` and `augustus.gtf`. Directory `example/results/test?` only contain files `augustus.hints.gtf`.  Is this the same as `augustus.gtf`, i.e. the final resulting predictions of augustus?

Thanks for your help!

**Comment by KatharinaHoff** [comment]
The example file is hosted externally, as stated in the documentation. You can obtain it, e.g. using wget command line tool: 

cd BRAKER/example
wget http://bioinf.uni-greifswald.de/bioinf/braker/RNAseq.bam

I fixed the output file names in the userguide.pdf (they had gotten lost during the tex2markdown conversion. I searched for the position where we are still talking about augustus.gtf and augustus.gff. Where did you spot it?

**Comment by KatharinaHoff** [comment]
Since we did not receive any further report on this issue, I will mark it as closed.
