### ISSUE TITLE
Stranded BAM with paired-end reads

### ISSUE THREAD

**Issue by apredeus** [Gaius-Augustus/BRAKER#60]
Dear Katharina, 

I was wondering how should one prepare "plus" and "minus" BAM files in case of paired-end reads. It seems counter-intuitive to simply split them by flag, since in each pair, one read would align to the "+" strand and another one to the "-". Would the library prep (and corresponding R1/R2 orientation with regard to the gene) matter? Thank you!

**Comment by KatharinaHoff** [comment]
I reference this issue: https://github.com/Gaius-Augustus/BRAKER/issues/7 A link there shows how to split the data.
However, using BRAKER with stranded RNA-Seq for UTR training is a highly experimental feature that might just fail.
