### ISSUE TITLE
Using prothint with BRAKER

### ISSUE THREAD

**Issue by kdarragh1994** [Gaius-Augustus/BRAKER#602]
Hi,

I am trying to run BRAKER2 with both proteins and RNA information. I am struggling to get prothint to run as the alignment tool. 
I immediately get an error:

WARNING: in file /global/home/groups/consultsw/sl-7.x86_64/modules/braker2/2.1.0/braker.pl at line 2965
No alignment tool was specified for aligning protein sequences against genome. Setting GenomeThreader as default alignment tool.

It then fails as it cant find GenomeThreader. 

How can I direct BRAKER to use prothint instead? 

This is what I am running:

module load braker2/2.10
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/global/home/groups/consultsw/sl-7.x86_64/modfiles/bamtools/2.4.0"
export PYTHON3_PATH=/global/software/sl-7.x86_64/modules/langs/python/3.8.8/bin/python
export GENEMARK_PATH=/global/scratch/users/kdarragh/prothint/ProtHint/dependencies/GeneMarkES
export AUGUSTUS_BIN_PATH=/global/home/groups/consultsw/sl-7.x86_64/modules/augustus/3.3/bin
export PROTHINT_PATH=/global/scratch/users/kdarragh/prothint/ProtHint/bin
braker.pl  BAMTOOLS_PATH=/global/home/groups/consultsw/sl-7.x86_64/modfiles/bamtools/2.4.0 --species=gongoraboth --genome=Gongorav1.fa.masked --bam=A_chemotype_secondmapping_Aligned.sortedByCoord.out.bam --prot_seq plant_proteins_red.fasta --workingdir=gongora_both --etpmode --softmasking

**Comment by KatharinaHoff** [comment]
Please update to BRAKER3. The calls are documented in our Readme.md page on GitHub, and they are documented in the test scripts.
