### ISSUE TITLE
Failed to create direcotry

### ISSUE THREAD

**Issue by mabh5** [Gaius-Augustus/BRAKER#608]
This is (hopefully) a simple fix but I am not familiar enough with coding to solve it. 

I am trying to run BRAKER with with protein data and used the given code in the instructions: 
`
braker.pl --genome=genome.fa --prot_seq=proteins.fa`

however immediately I am met with this error: 

> ERROR in file /home/mh/BRAKER/scripts/braker.pl at line 1210

> Failed to create direcotry /home/mh/braker/GeneMark-ES!

The version of GeneMark I have installed is gmes_linux_64 (GeneMark-ES/ET/EP+ ver 4.71_lic) and I followed the installations as instructed in  'https://math-inf.uni-greifswald.de/storages/uni-greifswald/fakultaet/mnf/mathinf/stanke/BRAKER-manuscript.pdf'

advice on how to address this error is welcome.

**Comment by mixle18** [comment]
Hi, I am having the same issue. Can you help how did you resolve this issue?
