### ISSUE TITLE
braker3 singularity: augustus cannot create new species

### ISSUE THREAD

**Issue by SwiftSeal** [Gaius-Augustus/BRAKER#609]
I'm running a build of the latest container. Command is:

` singularity exec --bind /mnt/shared:/mnt/shared:rw $APPS/braker3.sif braker.pl --genome=myspecies.fa --species=myspecies --prot_seq=odb10_plants.fasta`

However when I run this I get the error:

`ERROR in file /opt/BRAKER/scripts/braker.pl at line 5891
Failed to create new species with new_species.pl, check write permissions in /usr/share/augustus/config//species directory! Command was /usr/bin/perl /usr/share/augustus/scripts/new_species.pl --species=myspecies --AUGUSTUS_CONFIG_PATH=/usr/share/augustus/config/ 1> /dev/null 2>/path/to/pwd/braker/errors/new_species.stderr`

I also tried running `new_species.pl` manually in the container and it experiences a similar error, saying it may not have write permissions to the augustus conf directory.

Any ideas what might be happening here? I had issues with binding $PWD with our systems file structure, so had to opt for `--bind /mnt/shared:/mnt/shared:rw`

Thanks in advance

**Comment by SwiftSeal** [comment]
As a workaround I copied the containers `usr/share` to a writeable location and mounted that to the singularity container. This prevented the augustus error but broke more things down the line, so probably not the way to go!

**Comment by KatharinaHoff** [comment]
You need to mount the user home.

Moray Smith ***@***.***> schrieb am Do. 6. Apr. 2023 um 10:34:

**Comment by KatharinaHoff** [comment]
Or export an AUGUSTUS_CONFIG_PATH in a writable location. Put that in a
bash script with the braker.pl call and executive with bash in the
singularity container

Katharina Hoff ***@***.***> schrieb am Do. 6. Apr. 2023 um
10:50:

**Comment by SwiftSeal** [comment]
Thanks for your response! I initially tried mounting the home dir, but it sym links seemed to be causing issues. I set AUGUSTUS_CONFIG_PATH in a writable location and executed that in the container - this avoided the error, but I then had a gm_key error, seems to be due to: `no valid sequences were found`. If I check the writeable augustus location, nothing has been written.

**Comment by SamCT** [comment]
Also having this issue. I don't have much experience using Singularity, but it seems like it is something in the braker.pl script... 
We do have an old version of Augustus on the cluster (3.3.0). I have successfully installed the new one (3.5.0) and provided full paths to the /bin and /scripts, and config, but it seems focused on redirecting the config path to my home usr path. Maybe that old version is messing with something? 

# Sun May  7 08:51:45 2023: Found command line argument $AUGUSTUS_CONFIG_PATH.
# Sun May  7 08:51:45 2023: Checking /cluster/LAB_HOME/usr/bin/Augustus/config as potential path for $AUGUSTUS_CONFIG_PATH.
#*********
# WARNING: /cluster/LAB_HOME/usr/bin/Augustus/config is not a directory. Will not set $AUGUSTUS_CONFIG_PATH to /cluster/LAB_HOME/usr/bin/Augustus/config!
#*********
# Sun May  7 08:51:45 2023: Found environment variable $AUGUSTUS_CONFIG_PATH.
# Sun May  7 08:51:45 2023: Checking /usr/share/augustus/config/ as potential path for $AUGUSTUS_CONFIG_PATH.
# Sun May  7 08:51:45 2023: Success! Setting $AUGUSTUS_CONFIG_PATH to /usr/share/augustus/config/!

**Comment by KatharinaHoff** [comment]
Braker should issue that warning but proceed to solve the problem on its
own.

If you want to export a variable and make singularity see it, you write a
small script (e.g. line 1: export variable, line 2: call braker) and have
singularity execute the script with bash. It will then see the variable.

Sam Talbot ***@***.***> schrieb am So. 7. Mai 2023 um 22:14:

**Comment by splaisan** [comment]
I also do not like braker saving the augustus data in my home folder and would prefer to have it on a shared spot 
would a combination of **-B** and **-E** calls work? (i am new to singularity, be kind ;-)

```
SIFFILES=/opt/sif_files
thr=24

# where my server has its config folder (writable)
AUGUSTUS_CONFIG_PATH=/opt/biotools/Augustus/config

singularity exec \
  -B ${PWD}:/data \
  -B ${ORTHODB}:/orthodb \
  -B ${AUGUSTUS_CONFIG_PATH}:/augustus_cfg \
  -E AUGUSTUS_CONFIG_PATH="/augustus_cfg" \
  ${SIFFILES}/braker3.sif braker.pl \
  --species="some_monster" \
  --genome="/data/monster.fa" \
  --prot_seq="/orthodb/Vertebrata.fa" \
  --workingdir="/data/braker_out" \
  --threads="${thr}"
```

**Comment by SamCT** [comment]
> 

Got it, thank you Dr. Hoff.

By specifying in the singularity exec `-B $PWD,/cluster/home/annotation/augustus_config` I was able to tell Singularity that this augustus_config_path existed. 

I also had to specify that in the braker.pl command as well, --AUGUSTUS_CONFIG_PATH=/cluster/home/annotation/augustus_config

**Comment by SwiftSeal** [comment]
I'm still not getting the behaviour I'm expecting. Currently running as:

```
#!/bin/bash

export AUGUSTUS_CONFIG_PATH=/mnt/shared/scratch/yadayada/config

singularity exec -B /mnt/shared/,$HOME,$AUGUSTUS_CONFIG_PATH $APPS/braker3.sif braker.pl \
--genome=contigs.fa \
--species=myspecies \
--prot_seq=Viridiplantae.fa \
--AUGUSTUS_CONFIG_PATH=$AUGUSTUS_CONFIG_PATH
```

Augustus config is copied from a working version of augustus. I'm no longer gettting augustus writeable errors, but now seems to be failing on ProtHint:

```
#**********************************************************************************
#                               PROCESSING HINTS                                   
#**********************************************************************************
# Tue May  9 11:40:28 2023: Running ProtHint to produce hints from protein sequence file (this may take a couple of hours)...
# Tue May  9 11:40:39 2023: Running Genemark-ES for ProtHint...
# Tue May  9 11:40:39 2023: Executing GeneMark-ES
# Tue May  9 11:40:39 2023: changing into GeneMark-ES directory /mnt/shared/scratch/yadayada/braker/GeneMark-ES
cd /mnt/shared/scratch/yadayada/braker/GeneMark-ES
# Tue May  9 11:40:39 2023: Executing gmes_petap.pl
/usr/bin/perl /opt/ETP/bin/gmes//gmes_petap.pl --verbose --cores=1 --ES --gc_donor 0.001 --sequence=/mnt/shared/scratch/yadayada/braker/genome.fa  --soft_mask auto 1>/mnt/shared/scratch/yadayada/braker/GeneMark-ES.stdout 2>/mnt/shared/scratch/yadayada/braker/errors/GeneMark-ES.stderr
!ends here!
```

The only informative errors I can find are in GeneMark-ES.stderr:

```
# check before the run
# hard_mask is in the 'auto' mode. hard_mask was set to: 1000
# creat directories
# commit input data
# warning, PLUS file is empty
# prepare input data report
# commit training data
# prepare training data report
# prepare initial model
# find GC of sequence
GC 35
# build initial ES model
running step ES_A
running gm.hmm on local system
2 contigs in list
concatenate predictions: /mnt/shared/scratch/yadayada/braker/GeneMark-ES/run/ES_A_1
training level ES_A: /mnt/shared/scratch/yadayada/braker/GeneMark-ES/run/ES_A_1
Initial 5
Internal        17
Terminal        5
Single  0
Intron: 22      49363
Intergenic:     2       6025
error, no valid sequences were found
error on call: /opt/ETP/bin/gmes/make_nt_freq_mat.pl --cfg /mnt/shared/scratch/yadayada/braker/GeneMark-ES/run.cfg --section stop_TAG    --format TERM_TAG
```

Protein and genome file look fine, can't see any formatting errors there. gm_key is also present in home.

**Comment by ardy20** [comment]
Hello All
Sorry to reopening this again. It is not really clear how you have solved this "cannot create new species" problem. Could you please explain which file should be edited and where?

**Comment by najoshi** [comment]
Here's how I got it to work:

First git clone Augustus:

git clone https://github.com/Gaius-Augustus/Augustus.git

You just need to copy the "config" directory (in the Augustus directory) your analysis directory, the rest you can delete.

Run singularity like this (from the test file):

`singularity exec -B <path to analysis dir> braker3.sif braker.pl --AUGUSTUS_CONFIG_PATH=<path to analysis dir>/config --genome=/opt/BRAKER/example/genome.fa --prot_seq=/opt/BRAKER/example/proteins.fa --bam=/opt/BRAKER/example/RNAseq.bam --softmasking --workingdir=<path to analysis dir> --GENEMARK_PATH=${ETP}/gmes --threads 8 --gm_max_intergenic 10000 --skipOptimize`

This worked for me.

**Comment by gdalba** [comment]
@najoshi you are a lifesaver! Took me a good while to figure this one out. Many thanks for your input. :)

All three tests passed with no hiccups.

**Comment by ckeeling** [comment]
Following up on @najoshi comment: in case Augustus on GitHub is updated and is not the same version as in the braker3.sif, you can instead copy the config folder from within the braker3.sif to avoid potential issues.

e.g. (with apptainer or singularity)
```bash
apptainer exec --cleanenv braker3_latest.sif cp -r /usr/share/augustus/config .
chmod -R 777 ./config
```

**Comment by splaisan** [comment]
[like]  Stéphane Plaisance reacted to your message:
________________________________

**Comment by emgiles** [comment]
Is the config folder now in a different location in the container? 
When I use: singularity exec --cleanenv braker3.sif cp -r /usr/share/augustus/config .
I get the following error: cp: cannot stat '/usr/share/augustus/config': No such file or directory

**Comment by emilpaulitz** [comment]
I also had this issue and found the solution in this thread after trying other things for an hour. Could you maybe link to this thread in the Readme? There is something about AUGUSTUS_CONFIG_PATH but I am not using Nextflow and did not understand what "manually copy the AUGUSTUS_CONFIG_PATH contents to a writable location" means until I read this thread. Thanks!
