### ISSUE TITLE
"Illegal instruction" error in "aa2nonred.stderr"

### ISSUE THREAD

**Issue by SvitlanaLukicheva** [Gaius-Augustus/BRAKER#61]
Hello,

I am trying to annotate an insect genome with BRAKER, my command line is:
`braker.pl --cores 16 --species=gq --genome=genome.fa --softmasking --bam=rna_seq.bam --hints=hints.gff --etpmode`.

At the end of the run, the `error` folder contains four following files:
```
-rw-rw-r-- 1 slukiche slukiche     8871 Jul 27 22:00 aa2nonred.stderr
-rw-rw-r-- 1 slukiche slukiche   218092 Jul 27 14:57 filterIntronsFindStrand_userHints_0.stderr
-rw-rw-r-- 1 slukiche slukiche 13203288 Jul 27 21:52 GeneMark-ETP.stderr
-rw-rw-r-- 1 slukiche slukiche      192 Jul 28 22:52 getAnnoFastaJoingenes.augustus.hints.stderr
```
and I am wondering if I can just ignore them.

`aa2nonred.stderr` contains several entries with the following error:
`sh: line 1:  8190 Illegal instruction     /home/ulb/ebe/slukiche/conda/miniconda3/envs/braker/bin/blastp -query /mnt/fhgfs/users/s/l/slukiche/genome_annotation/braker/colorado_hints/braker/gonioctenaQuinquepunctataColoradoHints/traingenes.good.fa.nonreddb -db /mnt/fhgfs/users/s/l/slukiche/genome_annotation/braker/colorado_hints/braker/gonioctenaQuinquepunctataColoradoHints/traingenes.good.fa.nonreddb > /mnt/fhgfs/users/s/l/slukiche/genome_annotation/braker/colorado_hints/braker/gonioctenaQuinquepunctataColoradoHints/split_blast/split_14.fa.blastout`

`filterIntronsFindStrand_userHints_0.stderr` contains several entries with the following error:
`substr outside of string at /CECI/home/ulb/ebe/slukiche/genome_annotation/braker/BRAKER-2.1.2/scripts/filterIntronsFindStrand.pl line 159, <INTRONS> line 219.`

`GeneMark-ETP.stderr` contains several entries with the following error:
`(in cleanup) Can't call method "FETCH" on an undefined value at /home/ulb/ebe/slukiche/perl5/lib/perl5/Object/InsideOut.pm line 1953 during global destruction.`

And finally `getAnnoFastaJoingenes.augustus.hints.stderr` contains the following entry:
`/CECI/home/users/s/l/slukiche/tools/augustus/hmem/Augustus/scripts/getAnnoFastaFromJoingenes.py:97: DeprecationWarning: 'U' mode is deprecated
  with open(args.genome, "rU") as genome_handle:`

I suppose that the content of the two last files can be ignored, but what should I do with the errors in the first two files?

Thank you in advance for your help!

**Comment by KatharinaHoff** [comment]
I am still trying to reproduce the first error (aa2nonred.stderr).

I hope the second error has been fxed by commit https://github.com/Gaius-Augustus/BRAKER/commit/01fdaf37cc4193a81744be25be16123b305ba70f

The GeneMark-ETP error must be fixed by GeneMark developers, please contact Mark Borodovsky at Georgia Tech.

The getAnnoFastaJoingenes.py error is fixed with commit https://github.com/Gaius-Augustus/Augustus/commit/b7d5761f97165c030044c555b70aa43da7cb53e4

**Comment by SvitlanaLukicheva** [comment]
Thank you for your reply and your commits! The first error was fixed by reinstalling blast.

**Comment by KatharinaHoff** [comment]
Ok, then all problems (except for the GeneMark-ES/ET issue which I have no control over) seem to be solved and I'll close the issue.

Katharina
