### ISSUE TITLE
braker3 singularity: cannot create new species

### ISSUE THREAD

**Issue by mundoctor** [Gaius-Augustus/BRAKER#610]
hello, I run into a problem when I use singularity to run braker
I install the braker following the tutorial of https://github.com/Gaius-Augustus/BRAKER.
that build it using command:
singularity build braker3.sif docker://teambraker/braker3:latest
in my folder: $HOME/software/braker.

and then execute:
singularity exec braker3.sif print_braker3_setup.py
singularity exec braker3.sif braker.pl

and then download gm_key_64.gz, gunzip it, and place it in both $HOME and $HOME/software/braker with the rename of ".gm_key:.

and I test braker with test1: (in $HOME/software/braker)
singularity exec -B $PWD:$PWD braker3.sif cp /opt/BRAKER/example/singularity-tests/test1.sh .
export BRAKER_SIF=$HOME/software/braker/braker3.sif
bash test1.sh

but I receive the error message when execute the command "bash test1.sh":
ERROR in file /opt/BRAKER/scripts/braker.pl at line 5891
Failed to create new species with new_species.pl, check write permissions in /usr/share/augustus/config//species directory! Command was /usr/bin/perl /usr/share/augustus/scripts/new_species.pl --species=Sp_1 --AUGUSTUS_CONFIG_PATH=/usr/share/augustus/config/ 1> /dev/null 2>$HOME/software/braker3/test2/errors/new_species.stderr
INFO:    Cleaning up image...

I checked the authority of the folder /usr/share/augustus/config/species, which is inside the braker3.sif, and it is writable for me. also the $HOME/software/braker in my host system is writable.

so why I have this error? could anyone help me, appreciate it!

**Comment by gushiro** [comment]
same issue for me

**Comment by SwiftSeal** [comment]
Could be similar to https://github.com/Gaius-Augustus/BRAKER/issues/609?

**Comment by mundoctor** [comment]
> 

no, my $AUGUSTUS_CONFIG_PATH has been writable.

**Comment by ardy20** [comment]
Hello
I also have the same error using braker3.sif. Could you please explain how to solved this error when we are using singiularity (braker3.sif)?

**Comment by jiangqiuqiuu** [comment]
I am having the same issue here! Would be great if I can get some clarification!

**Comment by SwiftSeal** [comment]
Yeah pretty sure they were linked issues, I ended up copying everything into an analysis directory for simplicity:

```
BAM=merged.bam
GENOME=masked_genome.fa

mkdir -p BRAKER3
ANALYSIS_DIR=$(realpath BRAKER3)
cp -r $APPS/Augustus/config BRAKER3/
cp "$(realpath "$BAM")" BRAKER3/
cp "$(realpath "$GENOME")" BRAKER3/
wget https://bioinf.uni-greifswald.de/bioinf/partitioned_odb11/Viridiplantae.fa.gz "$ANALYSIS_DIR"
gunzip "$ANALYSIS_DIR"/Viridiplantae.fa.gz

singularity exec -B "$ANALYSIS_DIR" "$APPS/braker3.sif" braker.pl \
--AUGUSTUS_CONFIG_PATH="$ANALYSIS_DIR/config" \
--genome="$ANALYSIS_DIR/$( basename "$GENOME")" \
--prot_seq="$ANALYSIS_DIR"/Viridiplantae.fa \
--bam="$ANALYSIS_DIR/$BAM" \
--workingdir="$ANALYSIS_DIR" \
--threads 16
```

where `$APPS/Augustus/` was a git clone of the AUGUSTUS repo

**Comment by KatharinaHoff** [comment]
I hope this problem was solved. Please re-open if it persists.
