### ISSUE TITLE
Braker.gff3 vs braker.aa and braker.codingseq

### ISSUE THREAD

**Issue by joscarhuguet** [Gaius-Augustus/BRAKER#614]
I run braker and try to compare the number of genes and proteins in the ggf3, the aa and the codingseq.
I found that the gff3 is missing some IDs that are present in the aa and codingseq files.
 For example in a simple run I found 340 genes in the gff3.
However the aa file contains 341 proteins. First I assumed that there was an alternative isoform (t1 and t2), but actually One ID in the aa file (g219) is not presente in the ggf3 file.
I wonder how the braker.gff3 is created. 

Thanks
Jose

**Comment by KatharinaHoff** [comment]
@LarsGab can you confirm this from any of our benchmark genomes?

**Comment by SaiReddy-A** [comment]
I am facing the same issue, the braker.gtf and braker.aa files have more gene IDs than the braker.gff3 file. All the missing gene ids from gff3 have "GeneMark.hmm3" as source in gtf. Only the gene ids with "AUGUSTUS" as the source in gft are converted to gff3.

**Comment by LarsGab** [comment]
Hi,

We fixed the problem with converting gtf to gff3 format in the latest release (v3.0.4) of BRAKER. If you have downloaded BRAKER from GitHub, please make sure that you also update your TSEBRA version.

Best regards,
Lars
