### ISSUE TITLE
Output protein.fa not generated

### ISSUE THREAD

**Issue by AkshitaJain2709** [Gaius-Augustus/BRAKER#615]
I am trying to run Braker on a fragmented assembly and it's not giving the protein.fa file as the output, --skipGetAnnoFromFasta is not set as well. Could you please me help me figure out. It outputs the following extension files:
augustus.ab_initio.codingseq
augustus.ab_initio.aa
augustus.ab_initio.gff3
braker.gff3
genome.fa
braker.gtf

**Comment by KatharinaHoff** [comment]
@LarsGab is getAnnoFastaFromJoingenes.py actually executed to extract the aa file from braker3.gtf in the end of BRAKER3? If not, that needs to be added.

@AkshitaJain2709 you can produce the missing file as follows:

```
getAnnoFastaFromJoingenes.py -g genome.fa -o braker -f braker.gtf
```

This will produce braker.aa (and braker.codingseq)

**Comment by AkshitaJain2709** [comment]
Thanks for your reply, which genome.fa file do we use here, the initial assembly we put for annotation?

**Comment by KatharinaHoff** [comment]
Use the genome file that you ran braker with. Exception: if BRAKER had to change the fasta headers due to complexity. Then use the modified version.
