### ISSUE TITLE
Braker3 gff3 output

### ISSUE THREAD

**Issue by RenscoHogers** [Gaius-Augustus/BRAKER#617]
Hello,

I have been able to run braker3 successfully, however, the braker3.gff3 output seems a bit off. There is not a single "gene" feature in the entire .gff3, I have checked the Augustus.hints.gtf file and that one does include "gene" features. Is there a reason why these are left out of the braker3.gff3 file?

It seems to be that all gene annotations found in the augustus hint file, are placed in the braker.unsupported.gtf file, namely 22 373/23 914. Where the remaining gene feature are, I do not know,

I would like to combine the braker.gff3 file with GenomeThreader and transdecoder using evidencemodeler, and to me it seems that the gene features are needed. Any thoughts?

Thanks in advance!

**Comment by LarsGab** [comment]
Hi,

this should be fixed in BRAKER v3.0.3

Best, 
Lars
