### ISSUE TITLE
Failed to execute etraining step

### ISSUE THREAD

**Issue by MengyuanAuu** [Gaius-Augustus/BRAKER#62]
When predicting gene with RNA-seq file. I met the following error:

ERROR in file /exports/eddie3_homes_local/s1812756/BRAKER/scripts/braker.pl at line 6251
Failed to execute: /exports/eddie3_homes_local/s1812756/Augustus/bin/etraining --species=Sp_6 --AUGUSTUS_CONFIG_PATH=/exports/eddie3_homes_local/s1812756/Augustus/config /exports/eddie/scratch/s1812756/geneprediction_rnaseq/braker/train.f.gb 1> /exports/eddie/scratch/s1812756/geneprediction_rnaseq/braker/gbFilterEtraining.stdout 2>/exports/eddie/scratch/s1812756/geneprediction_rnaseq/braker/errors/gbFilterEtraining.stderr

What should I do>

**Comment by MengyuanAuu** [comment]
The file "genemark.f.good.gtf" is empty, and the bug reporting says that "something
went wrong during filtering GeneMark-ET genes for training AUGUSTUS"

So what can I do to fix it?

**Comment by KatharinaHoff** [comment]
This issue is closely related to https://github.com/Gaius-Augustus/BRAKER/issues/34 where the problem has been discussed and parts of the code have been improved. I am closing this issue.
