### ISSUE TITLE
No gene feature in braker.gtf of ETP/braker3 output

### ISSUE THREAD

**Issue by tinyfallen** [Gaius-Augustus/BRAKER#622]
Hi dear developers,

I have run the braker3 pipeline ended by BRAKER RUN FINISHED in the log. However there were only CDS, intron, and codon features in the braker.gtf. I looked into the braker.log and found strange running records showed below.

$ sed -n 1927,1936p braker.log (/path/to was used to represent braker working directory)

/export/home/ydn/yty/software/links/**tsebra.py** --gtf /path/to/augustus.hints.gtf,/path/to/GeneMark-ETP/genemark.gtf --keep_gtf /path/to/GeneMark-ETP/training.gtf --hintfiles /path/to/hintsfile.gff --cfg /path/to/tsebra/braker3.cfg --out /path/to/**braker.gtf** -q 2>/path/to/errors/tsebra.stderr
**mv** /path/to/**braker.gtf** /path/to/**braker.gtf_temp**
\# Thu Apr 20 06:11:41 2023: move TSBERA output /path/to/braker.gtf to /path/to/braker.unsupported.gtf
**mv** /path/to/**braker.gtf** /path/to/**braker.unsupported.gtf**
\# Thu Apr 20 06:11:41 2023: Filter TSEBRA result:
/export/home/ydn/yty/software/GeneMark-ETP/bin/**selectSupportedSubsets.py** /path/to/braker.unsupported.gtf /path/to/hintsfile.gff --fullSupport /dev/null --anySupport /path/to/**braker.gtf** --noSupport /dev/null 1> /path/to/selectSupportedSubsets.stdout 2> /path/to/errors/selectSupportedSubsets.stderr

As the logs showed, first tsebra generated the braker.gtf and subsequently the file name was **mv** to **braker.gtf_temp** which was never mentioned until being deleted as a tmp file;

Then **mv** was employed again to rename **braker.gtf** (which should not exist after the command in the previous line) to **braker.unsupported.gtf** which was retained in the directory;

Finally **selectSupportedSubsets.py** was called to take the **braker.unsupported.gtf** as input to generate the final **braker.gtf** which has no gene or transcript features.

I was confused about this situation and decided to use **braker.unsupported.gtf** or Augustus/augustus.hints.gtf as final result...
Or could you please give me any suggestion to get a right braker.gtf?  Many thanks!

Here is the orignal logs
![image](https://user-images.githubusercontent.com/37066354/233818841-5b9c9e40-6984-4452-9233-a4a975813447.png)

**Comment by LarsGab** [comment]
Hi,

This issue should be fixed in the latest release (v3.0.4) of BRAKER. If you have downloaded BRAKER from GitHub, please make sure that you also update your TSEBRA version.

Best regards,
Lars

**Comment by tinyfallen** [comment]
> Hi,
> 
> This issue should be fixed in the latest release (v3.0.4) of BRAKER. If you have downloaded BRAKER from GitHub, please make sure that you also update your TSEBRA version.
> 
> Best regards, Lars

Thanks for the reply! But the github version now is 3.0.3 at Apr 26, will it be updated in the near future? Or does it have fixed in the 3.0.3 version?

best ~

**Comment by LarsGab** [comment]
I'm so sorry, I meant version 3.0.3 of BRAKER on GitHub and v.1.0.4. of the Singularity container.

**Comment by tinyfallen** [comment]
never mind, many thanks for your timely reply !

best ~
