### ISSUE TITLE
Issue with hints and proteins

### ISSUE THREAD

**Issue by methylome** [Gaius-Augustus/BRAKER#625]
The following command was failed because of running GeneMark-ETP without bam files.

singularity exec -B /dgp:/dgp braker3.sif braker.pl --useexisting --threads=24 --alternatives-from-evidence=true --AUGUSTUS_ab_initio --gff3 --species=Rhodella_violacea --workingdir=. --genome=/dgp/assembly.fa --hints=/dgp/full_LR.E.gff --prot_seq=/dgp/proteins.faa --softmasking

```
AUGUSTUS_CONFIG_PATH/species (in this case /usr/share/augustus/config//species) is not writeable. BRAKER will try to copy the AUGUSTUS config directory to a writeable location.                                                                          
# Wed Apr 26 13:23:59 2023: Log information is stored in file /dgp/braker/braker.log                                 
ERROR in file /opt/BRAKER/scripts/braker.pl at line 5351                         
Failed to find RNA-Seq data for GeneMark-ETP.                       
```

**Comment by KatharinaHoff** [comment]
BRAKER should attempt to copy the entire folder /usr/share/augustus/config//species to ${HOME}/.augustus and use that copy. On our HPC, home is automatically mounted and writable. Maybe it helps if you specify the additional mounting in your singularity call: -B /home/yourusername:/home/yourusername ?

**Comment by haessar** [comment]
I'm facing exactly the same issue. Just to expand, it is happening even when I attempt to run /opt/BRAKER/example/singularity-tests/test3.sh, which I have modified to change the --bam option with --hints=/opt/BRAKER/example/RNAseq.hints (as suggested in the /opt/BRAKER/example/tests/test3.sh documation).

Running singularity with -B <my-home-dir>:<my-home-dir> as you suggested, which is writable.

**Comment by haessar** [comment]
@KatharinaHoff any updates on this?

**Comment by methylome** [comment]
I installed V3.0.6 and successfully ran test1, test2 and test3 without adding -B /home/cjh:/home/cjh.
