### ISSUE TITLE
Braker doesn't recognize YAML, Hash::Merge, Logger Simple in Anaconda environment

### ISSUE THREAD

**Issue by SilenzCS** [Gaius-Augustus/BRAKER#63]
Hi all,

I'm havign trouble setting up Braker in anaconda. I downloaded everything according to:

wget https://repo.anaconda.com/archive/Anaconda3-2018.12-Linux-x86_64.sh
bash bin/Anaconda3-2018.12-Linux-x86_64.sh # do not install VS (needs root privileges)
conda install -c anaconda perl
conda install -c bioconda perl-app-cpanminus
conda install -c bioconda perl-hash-merge
conda install -c bioconda perl-parallel-forkmanager
conda install -c bioconda perl-scalar-util-numeric
conda install -c bioconda perl-yaml
conda install -c bioconda perl-class-data-inheritable
conda install -c bioconda perl-exception-class
conda install -c bioconda perl-test-pod
conda install -c anaconda biopython
conda install -c bioconda perl-file-homedir
conda install -c bioconda perl-file-which # skip if you are not comparing to reference annotation
cpanm `Logger::Simple``
conda install -c bioconda braker
conda install -c bioconda braker2

I noticed gene mark was missing so I installed it:

conda install -c thiesgehrmann genemark_es

Is the order of download important? I somehow have the feeling genemark installation did turn things upside down.

Installing manually like sudo cpanm Module::Name worked, but it's still not reconized.

Thank you in advance!

Cheers,

Silenz

**Comment by SilenzCS** [comment]
Had to install with sudo for the yaml, etc., but now it doesn't recognize augustus.

**Comment by KatharinaHoff** [comment]
This should probably be posted/noted as an Anaconda receipe issue at
https://github.com/bioconda/bioconda-recipes/tree/b8e30dd6e2fd9c8d44fb5f56e44cc528e5f46859/recipes/braker2

**Comment by KatharinaHoff** [comment]
I am not sure whether a conda GeneMark install is legal... they have a license agreement that requires you enter your contact data etc....

**Comment by SilenzCS** [comment]
Ok, thank you. It works now. Yeah I deleted the conda GeneMark.
