### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by hcsun1** [Gaius-Augustus/BRAKER#630]
Hello, 

I encountered the following error while running Braker. I kindly request your assistance.

# Fri May 26 10:49:52 2023:Both protein and RNA-Seq data in input detected. BRAKER will be executed in ETP mode (BRAKER3).
#*********
sh: -c:行0: 寻找匹配的 `"' 是遇到了未预期的文件结束符
sh: -c:行1: 语法错误: 未预期的文件结尾
Failed to execute: java -version 2>&1 | grep "openjdk version" | awk -F[".] -v OFS=. '{print $2,$3}' at /home/wli1/software/BRAKER-3.0.3/scripts/braker.pl line 2299.

Thank you!

**Comment by hcsun1** [comment]
Hello,

I found that adding this parameter '--UTR=on' or '--addUTR=on' resulted in an error.
Below is my running command.

/home/wli1/software/BRAKER-3.0.3/scripts/braker.pl --species=$species \
    --genome=$genome \
    --softmasking \
    --bam=./rnaseq.bam\
    --threads=$threads \
    --AUGUSTUS_CONFIG_PATH=/data/lilab/wli1/workspace/01.Pan/11.Braker/Augustus-3.4.0/config \
    --BAMTOOLS_PATH=/data/lilab/zjwang1/software/bamtools/bin \
    --SAMTOOLS_PATH=/data/lilab/zjwang1/software/samtools \
    --TSEBRA_PATH=/home/wli1/software/TSEBRA/bin \
    --GENEMARK_PATH=/home/wli1/software/GeneMark-ETP/bin \
    --CDBTOOLS_PATH=/data/lilab/zjwang1/software/cdbfasta \
    --augustus_args="--genemodel=complete" \
    --UTR=on \
    --addUTR=on \
    --gff3 \
    --useexisting

**Comment by Yongli-Qi** [comment]
Please change it to:
 $cmdString = "java -version 2>&1 | grep \"openjdk version\" | awk -F['\"''\.'] -v OFS=. '{print \$2,\$3}'";

**Comment by VZJP2022** [comment]
You can change braker.pl  line 2298:
$cmdString = "java -version 2>&1 | grep \"openjdk version\" | awk -F['\"''.'] -v OFS=. '{print \$2,\$3}'";

**Comment by KatharinaHoff** [comment]
I did commit your suggested change. However, I warn that the stability of this UTR part of the pipeline is unstable, which is why we are currently not investing time and energy into debugging it, on our end. I recommend to either not use, or very carefully investigate results. Results are sometimes good, and sometimes, not good at all. UTR training may destroy your gene models in unexpected ways.

**Comment by KatharinaHoff** [comment]
Concerning UTR decoration, see my comment in https://github.com/Gaius-Augustus/BRAKER/issues/638

**Comment by YuzhouGong** [comment]
Hello, everyone, I have got the same issue here, when I run with --addUTR=on, the error comes like:

sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
Failed to execute: java -version 2>&1 | grep "openjdk version" | awk -F[".] -v OFS=. '{print $2,$3}' at /home/yzgong/miniforge3/bin/braker.pl line 2299.

Just as hcsun1 posted here.

But if I change the line 2298 of braker.pl into 
$cmdString = "java -version 2>&1 | grep "openjdk version" | awk -F['"''.'] -v OFS=. '{print $2,$3}'";
like Yongli-Qi and VZJP2022 suggested, here comes another error message:

Bareword found where operator expected at /home/yzgong/miniforge3/bin/braker.pl line 2299, near ""java -version 2>&1 | grep "openjdk"
	(Missing operator before openjdk?)
String found where operator expected at /home/yzgong/miniforge3/bin/braker.pl line 2299, near "" | awk -F['"''"
	(Missing operator before ''?)
String found where operator expected at /home/yzgong/miniforge3/bin/braker.pl line 2319, near "my @required_files = ('"
  (Might be a runaway multi-line '' string starting on line 2299)
	(Missing semicolon on previous line?)
Bareword found where operator expected at /home/yzgong/miniforge3/bin/braker.pl line 2319, near "my @required_files = ('gushr"
	(Do you need to predeclare my?)
syntax error at /home/yzgong/miniforge3/bin/braker.pl line 2299, near ""java -version 2>&1 | grep "openjdk version"
syntax error at /home/yzgong/miniforge3/bin/braker.pl line 2319, near "my @required_files = ('gushr"
Bad name after py' at /home/yzgong/miniforge3/bin/braker.pl line 2319.

Any suggestion that what I should revise to make it work?
