### ISSUE TITLE
Gene count issue

### ISSUE THREAD

**Issue by hcsun1** [Gaius-Augustus/BRAKER#631]
Hello

I integrated protein sequence evidence (non-redundant plant protein sequences from Uniprot and protein sequences from six published closely related species) and RNA-seq evidence to run BRAKER3. However, I'm facing some issues with the gene count. The braker.gff3 file contains 43,824 genes, while the augustus.hints.gff3 file contains 68,999 genes. However, the gene count in the published closely related species ranges from around 45,000 to 50,000. Could you please advise me on how to address this problem?

braker.pl --species=$species --genome=$genome --softmasking --bam=./rnaseq.bam --threads=$threads --prot_seq=./pep.fa --augustus_args="--genemodel=complete" --gff3 --useexisting

**Comment by LarsGab** [comment]
Hi,

in the last step of BRAKER3, TSEBRA selects the most reliable transcripts from the gene sets generated by AUGUSTUS and GeneMark-ETP. In some cases, TSEBRA filters too strictly and does not select enough transcripts. I suggest that you consider using the AUGUSTUS prediction as output, located at `Augustus/augustus.hints.gtf` in the working directory. 

Best,
Lars
