### ISSUE TITLE
Can't exec "/opt/ETP/bin/gmes/gmhmme3" + "The most common problem is an expired or not present file ~/.gm_key"

### ISSUE THREAD

**Issue by em255** [Gaius-Augustus/BRAKER#633]
I keep getting this error when trying to run BRAKER (through SIF container built on 5-26-23).  I was able to run it successfully a month or so ago, but I keep getting this error:

`The most common problem is an expired or not present file ~/.gm_key!`

I checked the `GeneMark-ES.stderr` and see repeated error

`Can't exec "/opt/ETP/bin/gmes/gmhmme3": No such file or directory at /opt/ETP/bin/gmes//gmes_petap.pl line 1323.`

I have redownloaded GENEMARK license many.. . many times.  Tried different versions of GENEMARK.  Tried having the key anywhere in addition to my home directory.  

There must be something stupid I'm doing, but I just can't see what's going wrong.

my command:
`singularity exec -B ${PWD}:${PWD} braker3_5-24-23.sif braker.pl --genome=${Genome}_reragged.chr.hap1.fa.masked --prot_seq=Plants.fasta  --workingdir=${Genome}_BRAKER3 --threads 30 --AUGUSTUS_CONFIG_PATH augustus/config/ --species ${Genome}hap1
`

**Comment by KatharinaHoff** [comment]
The key is now in the container. So the key can't be the problem when you use our most recent container. There must be some other error happening.

**Comment by ckeeling** [comment]
Hello @KatharinaHoff 

I notice that the information for [this container on Docker Hub](https://hub.docker.com/r/teambraker/braker3) still mentions needing to install this key. Starting at which version is the key in the container used?

I am getting the same error although the key has been placed in home, wd, and submitting directory too. However, I also notice the following error in GeneMark-ES.stdout:

```
# check before the run
# hard_mask is in the 'auto' mode. hard_mask was set to: 1000
# creat directories
# commit input data
error, input sequence size is too small data/dna.fna: 0
```

However, to me the input protein and genome files look correct. However, some (but not many) of the scaffolds appear to be fully softmasked (lowercase) after RepeatMasker. Could this be causing the problem? I.e. length of 0 when considering unmasked length?

Thanks!
Chris

**Comment by ckeeling** [comment]
Nope, I removed all the sequences that were fully softmasked, and I still get the same error. This phrase, "error, input sequence size is too small", originates from line 1602 of gmes_petap.pl. It is true, the GeneMark-ES/data/dna.fna is empty. This file is prepared by ProtHint, but I don't see any errors relating to that. Any suggestions?

**Comment by em255** [comment]
Sorry coming back to report on this.  My BRAKER is now running (not very well, producing ~0.5% BUSCO genes), but still I fixed this issue by addressing my singularity install/usage.  I think the directory mounting was not working properly.

**Comment by KatharinaHoff** [comment]
The key dependency has been removed because GeneMark-ETP no longer requires the key. GeneMark-ETP stability was also improved. Maybe you could try again with the most recent versions of GeneMark-ETP and BRAKER?

**Comment by em255** [comment]
My issue was with failed Masking of my genomes.  Thanks for all the help.  All is good now!
