### ISSUE TITLE
RNASeq + Proteins drop the number of predicted CDS

### ISSUE THREAD

**Issue by jeankeller** [Gaius-Augustus/BRAKER#634]
Hi,
I am using BRAKER to annotate genomes on a certain species I found out huge differences between run with only protein from relative species (around 30K CDS predicted) and from protein relatives+RNASeq data (only 15K so twice less). I agree that the RNASeq narrow down the number of predicted CDS to the most supported ones but the gap seems enormous. In addition both augustus.hints.gff and genemark.gtf file contains around 20K hints which is more consistent than the 15K finally predicted. 
I think the difference comes from the TSEBRA merging of the different hits and I wonder if it is possible to precise an option like "anySupport"?
I am using the Singularity container (pulled in march 2023, braker v3.0.2). 

In addition I got the following warnings: "Assuming this is not a DNA fasta file " and "Assuming this is not a protein fasta file" but I am sure that all my input files do not contain any not accepted characters. 

Thank you

**Comment by jeankeller** [comment]
Additional details: BUSCO completion on the predictions with protein only: 97%, BUSCO; completion with protein+RNASeq: 90%
I tried other species and had this huge (more than 10K protein less in RNASeq + Proteins) discrepancy between RNASeq + Proteins vs Proteins only 
Any thoughts?

**Comment by LarsGab** [comment]
Hi, 

TSEBRA selects the most reliable transcripts from the gene sets generated by AUGUSTUS and GeneMark-ETP. In some cases, TSEBRA filters too strictly and does not select enough transcripts. I suggest that you take a look at the AUGUSTUS prediction, located at Augustus/augustus.hints.gtf in the working directory. It should include more genes but at the expense of also including more false positives. However, this might be more suitable for your runs.

Best, 
Lars

**Comment by jeankeller** [comment]
Hi,
Thanks for the answer. As I indicated the augustus.hints.gff contains around 20K predicted genes which is close to the expectation.
Only considering the Augustus output was something I was thinking about, but then, the GeneMark-ETP step is only used for Augustus training and not anymore for gene prediction right?

**Comment by LarsGab** [comment]
The GeneMark-ETP step in regards to AUGUSTUS is used for generating a set of training genes (`GeneMark-ETP/training.gtf`) to train AUGUSTUS and to generate hints from RNA-Seq+proteins that are used in the prediction step of AUGUSTUS (`hintsfile.gff`). 
The training genes are a highly accurate set of genes. If you find that the AUGUSTUS prediciton is still missing some genes, you can merge the AUGUSTUS and the training genes together, for example with TSEBRA:

`tsebra.py -k Augustus/augustus.hints.gtf,GeneMark-ETP/training.gtf -o augustus+training.gtf`

**Comment by jeankeller** [comment]
thanks for the information. On the different runs I've made so far, when number of predicted genes dropped of more than 10K between augustus hints and the braker.gff output, the augustus hints were consistent with the expectation. 
The problem is to define a threshold above which it is better to keep the Augustus over the braker final predictions.

**Comment by KatharinaHoff** [comment]
I will assign a task to solve this problem to my students in a programming
class, soon. We might have a solution within July (unless this goes
horribly wrong 🤣).

Jean Keller ***@***.***> schrieb am Fr. 16. Juni 2023 um
15:45:

**Comment by jeankeller** [comment]
That's indeed a good subject!
Frokm what I saw, the quantity of the RNASeq data seems to have a huge impact on the final prediction and tends to take over the homology-based predictions, but this not true for all species even if simialr amount/diversity of RNASeq was used, 
I'm curious to see how you'll improve this step :) maybe a way to assess the hints from the different sources (RNASeq/proteins homology) and then adapt the TSEBRA parameters?

**Comment by KatharinaHoff** [comment]
No we will do it much easier: run Busco and make a simple rule… it’s about
automating this post processing step…

Jean Keller ***@***.***> schrieb am Fr. 16. Juni 2023 um
17:49:

**Comment by jeankeller** [comment]
I see. In my example, BUSCO on prediction with 20K genes (Augustus) => 97% and 90% on the post-TSEBRA prediction that only have 12K gene predicted, which makes me think about the BUSCO relevance in this case ^^

**Comment by KatharinaHoff** [comment]
I don't see how that makes BUSCO scores less relevant. That's exactly what we want to automatically detect. 7% difference is a lot.

**Comment by jeankeller** [comment]
I completly agree, this is what I meant sorry => BUSCO is a relevant solution

**Comment by MCH74** [comment]
Hi Katharina,
Have you found a solution for this as we are experiencing similar issues: 97.4% completeness with proteins; 89.0% with proteins+RNAseq
Thanks,
Mark

**Comment by KatharinaHoff** [comment]
Yes, we have presented a possible solution at PAG this year. You find a poster on this here: https://github.com/Gaius-Augustus/BRAKER/blob/master/docs/posters/poster_PAG2024.pdf
