### ISSUE TITLE
--softmasking has not been enabled

### ISSUE THREAD

**Issue by Yongli-Qi** [Gaius-Augustus/BRAKER#635]
This is my command:

braker.pl --genome=purged_masked.fa \
--softmasking --bam=/home/yqi/scratch/luxurians_genome_anno/05samtools/V350118580_L04_71_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350118580_L04_71_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L03_103_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L03_103_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L03_104_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L03_104_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L03_121_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L03_121_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L04_122_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L04_122_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L04_123_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L04_123_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L04_124_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L04_124_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L04_125_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L04_125_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350118580_L04_72_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350118580_L04_72_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L04_127_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350110272_L04_127_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350118580_L04_73_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350118580_L04_73_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/E100053253_L01_95_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/E100053253_L01_95_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350111032_L02_96_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350111032_L02_96_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350111032_L01_77_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350111032_L01_77_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350111032_L01_78_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350111032_L01_78_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350111032_L02_97_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350111032_L02_97_
minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350111032_L01_79_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350111032_L01_79_minus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350111032_L01_80_plus.bam,/home/yqi/scratch/luxurians_genome_anno/05samtools/V350111032_L01_80_minus.bam  \
--stranded=+,-,+,-,+,-,+,-,+,-,+,-,+,-,+,-,+,-,+,-,+,-,+,-,+,-,+,-,+,-,+,-,+,-,+,- \
--UTR=on \
--gff3 \
--threads=8 \
--crf

Why there is an ERROR: in file /home/yqi/scratch/luxurians_genome_anno/06braker/braker.pl at line 3254
--UTR=on has been set but --softmasking has not been enabled. A softmasked genome file and the option --softmasking and a bam file must be provided in order to run --UTR=on (in contrast to other modes, where a hints file can replace the alignment file, the bam file is strictly required for UTR training).
I have already set the --softmasking

**Comment by Yongli-Qi** [comment]
After changing "'softmasking_off!' => \$soft_off" to "'softmasking!'  => \$soft_mask" in the GetOptions(), it seemed to have worked.

**Comment by KatharinaHoff** [comment]
We need to fix this at some point in time (but not with the suggested solution) if we don't delete UTR support from BRAKER... regrettably low on the priorities list because we have too many other tasks.

**Comment by KatharinaHoff** [comment]
I fixed the error message in commit https://github.com/Gaius-Augustus/BRAKER/commit/35d83f6c598b9c22745e029b5bbd3108acbf2261

Thank you for reporting this issue.
