### ISSUE TITLE
Issue running braker3 with docker

### ISSUE THREAD

**Issue by marco91sol** [Gaius-Augustus/BRAKER#637]
Hi, I launched the test for braker3 but it provided me the following errors (attached you will find the output *err and *log files).
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/11650878/braker.log)
[find_python3_biopython.err.txt](https://github.com/Gaius-Augustus/BRAKER/files/11650879/find_python3_biopython.err.txt)
[find_python3_re.err.txt](https://github.com/Gaius-Augustus/BRAKER/files/11650880/find_python3_re.err.txt)
[gc_content.stderr.txt](https://github.com/Gaius-Augustus/BRAKER/files/11650881/gc_content.stderr.txt)
[test3.log](https://github.com/Gaius-Augustus/BRAKER/files/11650882/test3.log)

How can I solve that?
Marco

**Comment by LarsGab** [comment]
Hello Marco,

this might be due to your Docker version. Can you upgrade Docker or can you use Singularity?

Best,
Lars

**Comment by KatharinaHoff** [comment]
I assume that the issue was solved.
