### ISSUE TITLE
Braker3 sorted bam needed.?

### ISSUE THREAD

**Issue by ABDULLAHGUJJAR** [Gaius-Augustus/BRAKER#639]
For Braker2 we were using Hisat2 alignment 
1)	Sam to bam 
2)	Bam to sorted-bam. For Braker2
For Braker3 I am trying Hisat2 alignment with –dta option.
1)	Sam to bam
2)	Bam to sorted-bam. Needed?
Or I can used bam file directly without sorted.
Please guide me. Thanks

**Comment by LarsGab** [comment]
Hi,

BRAKER3 sorts the BAM files, you don't need to sort them before running BRAKER3.

Best, 
Lars
