### ISSUE TITLE
BRAKER3 fails

### ISSUE THREAD

**Issue by francicco** [Gaius-Augustus/BRAKER#642]
Hi @KatharinaHoff, 

For some reason Braker fails to run these commands
```
ERROR in file /user/work/tk19812/software/BRAKER-3.0.3/scripts/braker.pl at line 7685
Failed to execute: /user/work/tk19812/AntSpringtail/Kklo.BRAKER3.Annotation/Kklo.Ref.Kaylathalia_klovstadi.BRAKER_prediction/aug_ab_initio_106!
```
which returned:
```
/user/work/tk19812/software/Augustus/bin/augustus: ERROR
        Invalid nucleotide '<B8>' encountered.
```

Although at the end a gtf is returned, there are only 3700 genes. Something goes wrong.
Here I attached the log file.
[BRAKER.log](https://github.com/Gaius-Augustus/BRAKER/files/11817251/BRAKER.log)

Also `filterGenemark.stderr` contains a lot of
`Argument "." isn't numeric in addition (+) at /user/work/tk19812/software/BRAKER-3.0.3/scripts/filterGenemark.pl line 308, <INTRONS> line 533.`

Thanks a lot
Francesco

**Comment by KatharinaHoff** [comment]
I have tried to reproduce the problem but sadly, I can't reproduce it, which makes fixing it difficult to impossible. First, the species parameters that you sent contained renamed parameter files (ending on .HMM, so I changed to name back to removing the .HMM, but that was not the cause of your original problem), then I ran:

```
augustus --species=Kaylathalia_klovstadi --UTR=off  --exonnames=on --codingseq=on  --predictionStart=7485001 --predictionEnd=7823614 Scf0000008.fa --outfile=67.004.Scf0000008.fa.7485001..7823614.gff
```

It completed without problems. I ran Augustus 3.5.0. Possibly you need to update your augustus, or re-compile (in case you installed a pre-compiled binary)?

**Comment by francicco** [comment]
Hi @KatharinaHoff 

Thanks a lot for looking into it. Yeah, I thought about updating my Augustus, which is now 3.4.0, but I'm getting compilation errors for the new one, 3.5.0. I'll ask some help!

Thanks a lot!
F

**Comment by francicco** [comment]
Hi Katharina,

Apparently `etraining` generates a lot of 
`Argument "." isn't numeric in addition (+) at /user/work/tk19812/software/BRAKER-3.0.3/scripts/filterGenemark.pl line 308, <INTRONS> line 546`

:(
F

**Comment by francicco** [comment]
Apparently `etraining` has a segmentation fault

```
sh: line 1: 14816 Segmentation fault      /user/work/tk19812/software/Augustus-3.5.0/bin/etraining --species=Kaylathalia_klovstadi --AUGUSTUS_CONFIG_PATH=/user/work/tk19812/software/Augustus-3.5.0/config /user/work/tk19812/AntSpringtail/Kklo.BRAKER3.Annotation/Kklo.Ref.Kaylathalia_klovstadi.BRAKER_prediction/train.f.gb > /user/work/tk19812/AntSpringtail/Kklo.BRAKER3.Annotation/Kklo.Ref.Kaylathalia_klovstadi.BRAKER_prediction/gbFilterEtraining.stdout 2> /user/work/tk19812/AntSpringtail/Kklo.BRAKER3.Annotation/Kklo.Ref.Kaylathalia_klovstadi.BRAKER_prediction/errors/gbFilterEtraining.stderr
ERROR in file /user/work/tk19812/software/BRAKER-3.0.3/scripts/braker.pl at line 6172
```

**Comment by francicco** [comment]
Hi @KatharinaHoff,
This is the training file. it runs for a little then throws a segmental fault

[train.gb.train.gz](https://github.com/Gaius-Augustus/BRAKER/files/11866409/train.gb.train.gz)

Cheers
F

**Comment by KatharinaHoff** [comment]
Dear Francesco

I tested this and can't reproduce the problem with the file that you
provided, but it was possibly not the correct file. Your job fails with an
input train.f.gb, but you gave me train.gb.train. (That one completes fine).

```
etraining --species=Kaylathalia_klovstadi train.gb.train
# Read in 2668 genbank sequences.
Quantiles of the GC contents in the training set:
0% 0.266
5% 0.291 10% 0.297
15% 0.3 20% 0.303
25% 0.306 30% 0.308
35% 0.311 40% 0.312
45% 0.314 50% 0.317
55% 0.319 60% 0.321
65% 0.324 70% 0.326
75% 0.329 80% 0.332
85% 0.337 90% 0.343
95% 0.355 100% 0.55
HMM-training the parameters...
i= 0 bc= (0.237, 0.263, 0.263, 0.237)
 ** building model for exons *EXON*
start codon frequencies: ATG(2668)
# admissible start codons and their probabilities: ATG(1), CTG(0), TTG(0)
 number of bases in the reading frames: 1025439 1026860 1025390
--- frame = 0 ---    minPatSum = 233
--- frame = 1 ---    minPatSum = 233
--- frame = 2 ---    minPatSum = 233
--- initial frame = 0 ---    minPatSum = 233
--- initial frame = 1 ---    minPatSum = 233
--- initial frame = 2 ---    minPatSum = 233
--- internal exon terminal frame = 0 ---    minPatSum = 233
--- internal exon terminal frame = 1 ---    minPatSum = 233
--- internal exon terminal frame = 2 ---    minPatSum = 233
single, initial, internal, terminal mean exon lengths :
942 147 199 267
single exon : 55
initial exon 0 : 1157
initial exon 1 : 936
initial exon 2 : 520
internal exon 0 : 4286
internal exon 1 : 3284
internal exon 2 : 2216
terminal exon : 2613
Frequency of stop codons:
tag:  417 (0.156)
taa: 1692 (0.634)
tga:  559 (0.21)
end *EXON*
Storing parameters to file...
Writing exon model parameters [1] to file
/home/katharina/git/Augustus/config/species/Kaylathalia_klovstadi/Kaylathalia_klovstadi_exon_probs.pbl.

```

**Comment by francicco** [comment]
The command that gives me segmentation fault is this one:

`etraining --species=Kaylathalia_klovstadi --CRF=1 --AUGUSTUS_CONFIG_PATH=/user/work/tk19812/software/Augustus/config /user/work/tk19812/AntSpringtail/Kklo.BRAKER3.Annotation/Kklo.Ref.Kaylathalia_klovstadi.BRAKER_prediction/train.gb.train 1>/user/work/tk19812/AntSpringtail/Kklo.BRAKER3.Annotation/Kklo.Ref.Kaylathalia_klovstadi.BRAKER_prediction/crftraining.stdout 2>/user/work/tk19812/AntSpringtail/Kklo.BRAKER3.Annotation/Kklo.Ref.Kaylathalia_klovstadi.BRAKER_prediction/errors/crftraining.stderr`

If I run the same command without `--CRF=1` it returns no error.

Is it possible that there's something to do with memory or something missing in the nodes of the cluster where I run it?

Cheers
F

**Comment by francicco** [comment]
Hi @KatharinaHoff,

I took `etraining` from Augustus 3.4.0 and it worked. Unfortunately still only 3k genes. I think the problem is `filterGenemark.pl`. It discards to many annotations:

This is `filterGenemark.stdout`
```
Number of cds hints is 0
Average gene length: 3080
Average number of introns: 5.18243589146926
Good gene rate: 0.189230697631126
Number of genes: 21576
Number of complete genes: 21487
Number of good genes: 4066
Number of one-exon-genes: 1856
Number of bad genes: 17510
Good intron rate: 0.39314676527276
One exon gene rate (of good genes): 0.0860796851942942
One exon gene rate (of all genes): 0.0860215053763441
```

F

**Comment by KatharinaHoff** [comment]
Well, then it's a problem of insufficient evidence. The number of training genes looks like you should be able to complete a BRAKER run, though.

**Comment by francicco** [comment]
But the ab initio assembly finds more than 14k genes, and the coverage is quite high. I also have protein aligned with miniprot. How it doesn't have enough evidences?
F

**Comment by KatharinaHoff** [comment]
Just to be clear: we are talking about number of training genes for
Augustus, not about total predicted genes, right?

**Comment by francicco** [comment]
What I'm saying is that there should be enough evidence. I don't understand why the `Number of bad genes: 17510` is so high.

**Comment by francicco** [comment]
Dear @KatharinaHoff,

Here again. :) So, I'm running BRAKER3 on a completely different genome using illumina reads and a lot of proteins aligned with miniprot and gave to BRAKER with `--hints=GFF3`.
The job goes and finishes with only 3835 predicted genes, just like in the previous run. I'm guessing there is something wrong here, and I don't think it's the data.

I'm going to run the same analysis with BRAKER2, and see if there's any difference.

My bet is that there's something wrong in the model that is generated for the Augustus predictions...

Best,
F

**Comment by KatharinaHoff** [comment]
Yes, it sounds like something went wrong here. I still have no idea what went wrong, though. What happened with your BRAKER2 results?

**Comment by francicco** [comment]
Hi Kathaina,

I've figured it out, basically BRAKER found another species model and that was conflicting with the one it was about to create. I deleted the copy present and it worked perfectly! ;)

Cheers
F
