### ISSUE TITLE
low number of intron hints with sufficient multiplicity

### ISSUE THREAD

**Issue by imu93** [Gaius-Augustus/BRAKER#644]
Hi,
I'm trying to run braker3 with a chromosome-level assembly of ~654 Mb using just proteins. I'm using a set of predicted proteomes of 6 closely related species as input, however, I got the next error: 

`braker.pl --genome=$genomeFile --prot_seq=$proteoFile --species=$species--GENEMARK_PATH=$gmkPath --threads 32 --gff3 --min_contig=15000 --workingdir=02_braker_test`

```
#*********
# WARNING:
# The hints file(s) for GeneMark-EX contain less than 1000 introns. (In total, 57 unique introns are contained.)
# Genemark-EX might fail due to the low number of hints.
#*********
#*********
# WARNING:
# The hints file(s) for GeneMark-EX contain less than 150 introns with multiplicity >= 4! (In total, 57 unique introns are contained. 10 have a multiplicity >= 4.)
# Possibly, you are trying to run braker.pl on data that does not provide sufficient multiplicity information. This will e.g. happen if you try to use introns generated from assembled RNA-Seq transcripts; or if you try to run braker.pl in epmode with mappings from proteins without sufficient hits per locus. Or if you use the example data set.
# A low number of intron hints with sufficient multiplicity may result in a crash of GeneMark-EX (it should not crash with the example data set).
#*********
ERROR in file /ceph/users/imartinez/.mambaforge/envs/braker3/bin/braker.pl at line 5310
Failed to execute: /ceph/users/imartinez/.mambaforge/envs/braker3/bin/perl /ceph/users/imartinez/software/ETP/bin/gmes/gmes_petap.pl --verbose --seq /data/abreu/worms/analyses/isaac/genomes/braker/Hb/02_braker_test/genome.fa --min_contig=15000 --EP /data/abreu/worms/analyses/isaac/genomes/braker/Hb/02_braker_test/genemark_hintsfile.gff --cores=32  --gc_donor 0.001 --evidence /data/abreu/worms/analyses/isaac/genomes/braker/Hb/02_braker_test/genemark_evidence.gff  --soft_mask auto 1>/data/abreu/worms/analyses/isaac/genomes/braker/Hb/02_braker_test/GeneMark-EP.stdout 2>/data/abreu/worms/analyses/isaac/genomes/braker/Hb/02_braker_test/errors/GeneMark-EP.stderr
Failed to execute: /ceph/users/imartinez/.mambaforge/envs/braker3/bin/perl /ceph/users/imartinez/software/ETP/bin/gmes/gmes_petap.pl --verbose --seq /data/abreu/worms/analyses/isaac/genomes/braker/Hb/02_braker_test/genome.fa --min_contig=15000 --EP /data/abreu/worms/analyses/isaac/genomes/braker/Hb/02_braker_test/genemark_hintsfile.gff --cores=32  --gc_donor 0.001 --evidence /data/abreu/worms/analyses/isaac/genomes/braker/Hb/02_braker_test/genemark_evidence.gff  --soft_mask auto 1>/data/abreu/worms/analyses/isaac/genomes/braker/Hb/02_braker_test/GeneMark-EP.stdout 2>/data/abreu/worms/analyses/isaac/genomes/braker/Hb/02_braker_test/errors/GeneMark-EP.stderr
The most common problem is an expired or not present file ~/.gm_key!   
```     

I have tried to reduce --min_contig=15000  to --min_contig=10000 but I have the same result.
Now when I use the same input database but with a smaller "control" genome (250 Mb) braker worked perfectly, so I wonder if this is something related to the configuration for this particular genome. 

Any comments or suggestions will be appreciated.
Thanks!

**Comment by KatharinaHoff** [comment]
What are you using as protein database?

**Comment by imu93** [comment]
Hi @KatharinaHoff 
I'm using a concatenated file of 6 proteomes obtained from wormBase ParaSite (https://ftp.ebi.ac.uk/pub/databases/wormbase/parasite/releases/WBPS18/species/) since these are nematode genomes. But perhaps this isn't the expected input, right? After reading a bit more perhaps I should start using orthodb-clades, isn't it? 

Many thanks for your help! 
Regards

**Comment by KatharinaHoff** [comment]
Yes, I recommend that you concatenate your local protein set to the Metazoa OrthoDB partition and retry. What you observe is a "lack of extrinsic data issue", that can either we raised by an actual lack of extrinsic data, or by the genome assembly simply not containing sufficient data to align the proteins to.
