### ISSUE TITLE
Braker3 start and stop codons

### ISSUE THREAD

**Issue by uqunakan** [Gaius-Augustus/BRAKER#645]
Hi,
I have been using Braker3 and got the output files successfully. Braker.gtf files have genes predicted by both AUGUSTUS and GeneMark.hmm3. For most of the genes predicted by both AUGUSTUS and GeneMark.hmm3, the stop codons come first and the start codons come later. Please see below. I think that is not correct. The name stop codon (which is actually a start codon) and vice versa have been given wrongly I guess. For some other genes, start codons come first and stop codons come later which is correct. Could you please let me know whether we can fix this issue?

C.aust_Rainbow_01	AUGUSTUS	gene	27268383	27272075	.	-	.	g2931
C.aust_Rainbow_01	AUGUSTUS	transcript	27268383	27272075	0.5	-	.	g2931.t1
C.aust_Rainbow_01	AUGUSTUS	stop_codon	27268383	27268385	.	-	0	transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01	AUGUSTUS	CDS	27268383	27269228	1	-	0	transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01	AUGUSTUS	exon	27268383	27269228	.	-	.	transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01	AUGUSTUS	intron	27269229	27270707	1	-	.	transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01	AUGUSTUS	CDS	27270708	27271210	0.69	-	2	transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01	AUGUSTUS	exon	27270708	27271210	.	-	.	transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01	AUGUSTUS	intron	27271211	27272032	0.69	-	.	transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01	AUGUSTUS	CDS	27272033	27272075	0.5	-	0	transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01	AUGUSTUS	exon	27272033	27272075	.	-	.	transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01	AUGUSTUS	start_codon	27272073	27272075	.	-	0	transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01	AUGUSTUS	transcript	27268383	27271262	0.67	-	.	g2931.t2
C.aust_Rainbow_01	AUGUSTUS	stop_codon	27268383	27268385	.	-	0	transcript_id "g2931.t2"; gene_id "g2931";
C.aust_Rainbow_01	AUGUSTUS	CDS	27268383	27269228	0.99	-	0	transcript_id "g2931.t2"; gene_id "g2931";
C.aust_Rainbow_01	AUGUSTUS	exon	27268383	27269228	.	-	.	transcript_id "g2931.t2"; gene_id "g2931";

**Comment by KatharinaHoff** [comment]
I don't think it's wrong. You can sort the gtf file differently, if you like, but I don't see an error in the codons.

**Comment by uqunakan** [comment]
Hi Katharina,
But a gene should start with a start codon and a stop codon, isn’t it? Here in the following example, transcript t1 starts with the stop codon and ends with start codon (according to the coordinates). Although there is nothing wrong with the codons, I have the question regarding the names of start and stop codons. Previously when I used Braker2, I didn’t have this problem.

C.aust_Rainbow_01 AUGUSTUS gene 27268383 27272075 . - . g2931
C.aust_Rainbow_01 AUGUSTUS transcript 27268383 27272075 0.5 - . g2931.t1
C.aust_Rainbow_01 AUGUSTUS stop_codon 27268383 27268385 . - 0 transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01 AUGUSTUS CDS 27268383 27269228 1 - 0 transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01 AUGUSTUS exon 27268383 27269228 . - . transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01 AUGUSTUS intron 27269229 27270707 1 - . transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01 AUGUSTUS CDS 27270708 27271210 0.69 - 2 transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01 AUGUSTUS exon 27270708 27271210 . - . transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01 AUGUSTUS intron 27271211 27272032 0.69 - . transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01 AUGUSTUS CDS 27272033 27272075 0.5 - 0 transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01 AUGUSTUS exon 27272033 27272075 . - . transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01 AUGUSTUS start_codon 27272073 27272075 . - 0 transcript_id "g2931.t1"; gene_id "g2931";
C.aust_Rainbow_01 AUGUSTUS transcript 27268383 27271262 0.67 - . g2931.t2
C.aust_Rainbow_01 AUGUSTUS stop_codon 27268383 27268385 . - 0 transcript_id "g2931.t2"; gene_id "g2931";
C.aust_Rainbow_01 AUGUSTUS CDS 27268383 27269228 0.99 - 0 transcript_id "g2931.t2"; gene_id "g2931";
C.aust_Rainbow_01 AUGUSTUS exon 27268383 27269228 . - . transcript_id "g2931.t2"; gene_id "g2931";


Thanks and regards,

Ms Upuli Nakandala | PhD student
Robert Henry’s Lab
Queensland Alliance for Agriculture & Food Innovation
Level 6 Hartley Teakle Building [609]
The university of Queensland, St Lucia QLD 4072
Email: ***@***.******@***.***>
Mobile: +61480385195
Website: www.qaafi.uq.edu.au<http://www.qaafi.uq.edu.au>

**Comment by webbchen** [comment]
Dear Upuli

They appear back to front because they're annotated on the "-" strand of the sequence. All the ones on the "+" strand are listed from start to stop. Katharina is right.

**Comment by uqunakan** [comment]
Thank you, Anne.

Best regards,

Ms Upuli Nakandala | PhD student
Robert Henry’s Lab
Queensland Alliance for Agriculture & Food Innovation
Level 6 Hartley Teakle Building [609]
The university of Queensland, St Lucia QLD 4072
Email: ***@***.******@***.***>
Mobile: +61480385195
Website: www.qaafi.uq.edu.au<http://www.qaafi.uq.edu.au>
