### ISSUE TITLE
GeneMark issue: Died at /opt/ETP/bin/format_back.pl line 14.

### ISSUE THREAD

**Issue by CamilaFioriPereira** [Gaius-Augustus/BRAKER#648]
Hi,

I am annotating genomes using BRAKER3.0.2 from the Singularity container with both RNASeq (mapped with HISAT2 and the --dta option enabled) and protein from relative species (obtained from the database generated by T. Bruna). 
On some of them, I obtained the following error message that looks like related to GeneMark (**even if BRAKER run is complete and produced the expected output**):

> substr outside of string at /opt/ETP/bin/gmes/parse_set.pl line 681, <$PARSE> line 7141.
Use of uninitialized value $value in substitution (s///) at /opt/ETP/bin/gmes/parse_set.pl line 682, <$PARSE> line 7141.
Use of uninitialized value $value in substitution (s///) at /opt/ETP/bin/gmes/parse_set.pl line 683, <$PARSE> line 7141.
Use of uninitialized value $value in concatenation (.) or string at /opt/ETP/bin/gmes/parse_set.pl line 685, <$PARSE> line 7141.
substr outside of string at /opt/ETP/bin/gmes/parse_set.pl line 681, <$PARSE> line 146562.
Use of uninitialized value $value in substitution (s///) at /opt/ETP/bin/gmes/parse_set.pl line 682, <$PARSE> line 146562.
Use of uninitialized value $value in substitution (s///) at /opt/ETP/bin/gmes/parse_set.pl line 683, <$PARSE> line 146562.
Use of uninitialized value $value in concatenation (.) or string at /opt/ETP/bin/gmes/parse_set.pl line 685, <$PARSE> line 146562.
error on open file /opt/ETP/bin/gmes/build_mod.pl: TAG.mat
sed: can't read output.mod: No such file or directory
28-Jun-23 12:50:36 - INFO: Finding masking penalty maximizing the number of correctly predicted reliable exons in range from 0 to 0.2 with step 0.04
28-Jun-23 12:50:36 - INFO: Running prediction with masking penalty = 0
error: Program exited due to an error in command: /opt/ETP/bin/gmes/gmes_petap.pl --seq /home/braker/Sp1/GeneMark-ETP/proteins.fa/penalty/contigslqn22hqv.fasta --soft_mask 1000 --max_mask 40000  --predict_with home/braker/Sp1/GeneMark-ETP/proteins.fa/model/output.mod --cores 8 --mask_penalty 0
error, file not found: option --f1 prothint/prothint.gff
grep: prothint/evidence.gff: No such file or directory
grep: prothint/evidence.gff: No such file or directory
Traceback (most recent call last):
  File "/opt/ETP/bin/printRnaAlternatives.py", line 353, in <module>
    main()
  File "/opt/ETP/bin/printRnaAlternatives.py", line 289, in main
    candidates = loadIntrons(args.genemark)
  File "/opt/ETP/bin/printRnaAlternatives.py", line 193, in loadIntrons
    for row in csv.reader(open(inputFile), delimiter='\t'):
FileNotFoundError: [Errno 2] No such file or directory: 'pred_m/genemark.gtf'
error, file not found: option --f1 prothint/prothint.gff
grep: prothint/evidence.gff: No such file or directory
grep: prothint/evidence.gff: No such file or directory
Died at /opt/ETP/bin/format_back.pl line 14.
Died at /opt/ETP/bin/format_back.pl line 14.
substr outside of string at /opt/ETP/bin/gmes/parse_set.pl line 681, <$PARSE> line 51099.
Use of uninitialized value $value in substitution (s///) at /opt/ETP/bin/gmes/parse_set.pl line 682, <$PARSE> line 51099.
Use of uninitialized value $value in substitution (s///) at /opt/ETP/bin/gmes/parse_set.pl line 683, <$PARSE> line 51099.
Use of uninitialized value $value in concatenation (.) or string at /opt/ETP/bin/gmes/parse_set.pl line 685, <$PARSE> line 51099.
substr outside of string at /opt/ETP/bin/gmes/parse_set.pl line 681, <$PARSE> line 108162.
Use of uninitialized value $value in substitution (s///) at /opt/ETP/bin/gmes/parse_set.pl line 682, <$PARSE> line 108162.
Use of uninitialized value $value in substitution (s///) at /opt/ETP/bin/gmes/parse_set.pl line 683, <$PARSE> line 108162.
Use of uninitialized value $value in concatenation (.) or string at /opt/ETP/bin/gmes/parse_set.pl line 685, <$PARSE> line 108162.
error on open file /opt/ETP/bin/gmes/build_mod.pl: TAG.mat
sed: can't read output.mod: No such file or directory
error, file not found: option --f1 prothint/prothint.gff
grep: prothint/evidence.gff: No such file or directory
grep: prothint/evidence.gff: No such file or directory
Died at /opt/ETP/bin/format_back.pl line 14.
Died at /opt/ETP/bin/format_back.pl line 14.

I saw this error reported by other but the cause couldn't be stop codon since I used the formated database from T. Bruna.
However BRAKER found whitespace in the header of the protein database, but the sanity check I've done didn't find any. I also got the following warnings:

> Wed Jun 28 11:34:08 2023: Assuming that this is not a DNA fasta file because other characters than A, T, G, C, N, a, t, g, c, n were contained. If this is supposed to be a DNA fasta file, check the content of your file! If this is supposed to be a protein fasta file, please ignore this message!
 Wed Jun 28 11:34:08 2023: Assuming that this is not a protein fasta file because other characters than AaRrNnDdCcEeQqGgHhIiLlKkMmFfPpSsTtWwYyVvBbZzJjOoUuXx were contained. If this is supposed to be DNA fasta file, please ignore this message.

But the search for any character different from AaRrNnDdCcEeQqGgHhIiLlKkMmFfPpSsTtWwYyVvBbZzJjOoUuXx in the protein database didn't return any result. Could it be a cause of the error? (I used this database successfully on other genomes)
 
Do you have an idea about what's going on?

Thank you!

**Comment by KatharinaHoff** [comment]
Please get in touch with Alexandre Lomsadze and Mark Borodovsky at Georgia Tech. I am never sure whether they keep an eye on our GitHub issues, and this is an ETP issue.

**Comment by alexlomsadze** [comment]
Hello,

I will start with some general comments, which may be useful for users dealing with fatal errors from GeneMark-ETP runs.

The error handling sub-system in GeneMark-ETP is still under development. Some unexpected conditions in the code may lead to a fatal error much later in the code. Such “late” error messages generated by GeneMark-ETP are not very useful for diagnostic purposes. The GeneMark-ETP code worked without errors on all the genomes we tested. Errors observed by users are usually input data specific.
To find an error, we frequently need access to your data. Input files and GeneMark-ETP temporary files are quite large, which makes data sharing complicated. Even if you share input data with us, running GeneMark-ETP on your data on our local system takes time and $ for CPU-storage.

The fastest way to get help is to provide us with “read” access to the folder with the GeneMark-ETP run.

In regard to issue #648 :
GeneMart-ETP reported an error while the code was building HMM model from files “model/training.gtf” and “data/genome.fasta”.
Is it possible to share these files with us so we can determine the source of error? 
Please use email for sharing the data access instructions.

Best,
Alex

**Comment by alexlomsadze** [comment]
Hello,

My apologies.
I received a request for support via email the next day after this issue was opened on GitHub.
I was distracted by other obligations and have not finished the support request.
This is a lousy excuse for breaking the support communication from my side.

I found and fixed the error in the ETP code.
This fix solves the following warning message:
"Use of uninitialized value $value in substitution (s///) at /opt/ETP/bin/gmes/parse_set.pl "

Please update GeneMark-ETP to the latest GitHub version 1.02.

The fixed version of the BRAKER3 container will be uploaded soon.

Alex

**Comment by KatharinaHoff** [comment]
The container has been updated.
