### ISSUE TITLE
braker.gff3 does not match braker.gtf on braker3 prediction using illumina data only

### ISSUE THREAD

**Issue by remkv6** [Gaius-Augustus/BRAKER#649]
Hi Braker Folks,

I noticed that when braker3 finishes, I get all of the normal files.  However I've noticed an inconsistency between the braker.gtf and braker.gff3.   Particularly that some genes are missing from the gff3 that are present in the gtf, braker.codingseq, and braker.aa.   The genes that are missing form the gff3 are formatted differently in the gtf as well. This is the gene g5.t2 is the one missing from my gff3 output, and here is what it looks like in the gtf:

HiC_scaffold_1  AUGUSTUS        intron  120605  120682  0.54    -       .       transcript_id "g5.t1"; gene_id "g5";
HiC_scaffold_1  AUGUSTUS        CDS     120683  120760  0.55    -       0       transcript_id "g5.t1"; gene_id "g5";
HiC_scaffold_1  AUGUSTUS        exon    120683  120760  .       -       .       transcript_id "g5.t1"; gene_id "g5";
HiC_scaffold_1  AUGUSTUS        start_codon     120758  120760  .       -       0       transcript_id "g5.t1"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   transcript      116680  120943  .       -       .       g5.t2
HiC_scaffold_1  GeneMark.hmm3   stop_codon      116680  116682  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   CDS     116680  116738  .       -       2       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   exon    116680  116738  0       -       .       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   intron  116739  116782  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   CDS     116783  116882  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   exon    116783  116882  0       -       .       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   intron  116883  116978  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   CDS     116979  117137  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   exon    116979  117137  0       -       .       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   intron  117138  117244  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   CDS     117245  117394  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   exon    117245  117394  0       -       .       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   intron  117395  118642  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   CDS     118643  118819  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   exon    118643  118819  0       -       .       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   intron  118820  118971  .       -       1       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   CDS     118972  119068  .       -       1       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   exon    118972  119068  0       -       .       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   intron  119069  119387  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   CDS     119388  119485  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   exon    119388  119485  0       -       .       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   intron  119486  119546  .       -       1       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   CDS     119547  119610  .       -       1       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   exon    119547  119610  0       -       .       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   intron  119611  119804  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   CDS     119805  120085  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   exon    119805  120085  0       -       .       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   intron  120086  120448  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   CDS     120449  120604  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   exon    120449  120604  0       -       .       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   intron  120605  120662  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   CDS     120663  120800  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   exon    120663  120800  0       -       .       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   intron  120801  120916  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   CDS     120917  120943  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   exon    120917  120943  0       -       .       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  GeneMark.hmm3   start_codon     120941  120943  .       -       0       transcript_id "g5.t2"; gene_id "g5";
HiC_scaffold_1  AUGUSTUS        gene    124143  125600  .       +       .       g6
HiC_scaffold_1  AUGUSTUS        transcript      124143  125600  0.24    +       .       g6.t1
HiC_scaffold_1  AUGUSTUS        start_codon     124143  124145  .       +       0       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        CDS     124143  124207  0.44    +       0       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        exon    124143  124207  .       +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        intron  124208  124258  1       +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        CDS     124259  124318  1       +       1       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        exon    124259  124318  .       +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        intron  124319  124368  1       +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        CDS     124369  124445  1       +       1       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        exon    124369  124445  .       +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        intron  124446  124495  1       +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        CDS     124496  124599  0.98    +       2       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        exon    124496  124599  .       +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        intron  124600  124949  0.98    +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        CDS     124950  124972  0.59    +       0       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        exon    124950  124972  .       +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        intron  124973  125019  0.59    +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        CDS     125020  125038  0.88    +       1       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        exon    125020  125038  .       +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        intron  125039  125432  1       +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        CDS     125433  125600  0.71    +       0       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        exon    125433  125600  .       +       .       transcript_id "g6.t1"; gene_id "g6";
HiC_scaffold_1  AUGUSTUS        stop_codon      125598  125600  .       +       0       transcript_id "g6.t1"; gene_id "g6";

Thank you

Rick

**Comment by jeankeller** [comment]
Hi,
I also found this error. It appears that all genes predicted by GeneMark.hmm3 are not properly converted from GTF to GFF.
To get the complete GFF, I ran: cat braker.gtf | perl -ne 'if(m/\tAUGUSTUS\t/
 or m/\tGeneMark\.hmm\t/ or m/\tGeneMark\.hmm3\t/ or m/\tgmst\t/) {print $_;}' | perl gtf2gff.pl --gff3 --out=
test.gff3
The perl script gtf2gff.pl is located in the AUGUSTUS_SCRIPT_PATH (something like /
usr/share/augustus/scripts/gtf2gff.pl in the singularity container).
Note that I am not sure yet that the this command really ouput the full GFF3, I am still checking it.

Best
Jean

**Comment by LarsGab** [comment]
Hi, 
which version of BRAKER did you use? This issue should have been resolved in BRAKER v3.0.3.
Best,
Lars

**Comment by jeankeller** [comment]
Hi,
I'm on the 3.0.2, I've downloaded the singularity container for the 3.0.3 and I'll give it a shot later on. 
Best,
Jean
