### ISSUE TITLE
brake.pl error

### ISSUE THREAD

**Issue by lufuhao** [Gaius-Augustus/BRAKER#650]
$./braker.pl

---------------------------------------------- Error log-----------------------------
Bareword found where operator expected at ./braker.pl line 2298, near ""java -version 2>&1 | grep "openjdk"

	(Missing operator before openjdk?)

String found where operator expected at ./braker.pl line 2298, near "" | awk -F['"''"

	(Missing operator before ''?)

String found where operator expected at ./braker.pl line 2318, near "my @required_files = ('"

  (Might be a runaway multi-line '' string starting on line 2298)

	(Missing semicolon on previous line?)

Bareword found where operator expected at ./braker.pl line 2318, near "my @required_files = ('gushr"

	(Do you need to predeclare my?)

syntax error at ./braker.pl line 2298, near ""java -version 2>&1 | grep "openjdk version"

syntax error at ./braker.pl line 2318, near "my @required_files = ('gushr"

Bad name after py' at ./braker.pl line 2318.

Error: failed to install braker-v3.0.3-cf8396b
----------------------------------------------------------

This is caused by the line 2298 in braker.pl

`$cmdString = "java -version 2>&1 | grep "openjdk version" | awk -F['"''.'] -v OFS=. '{print $2,$3}'";`

there should be a slash before the 2nd, 3rd and 4th quote mark

`$cmdString = "java -version 2>&1 | grep \"openjdk version\" | awk -F['\"''.'] -v OFS=. '{print $2,$3}'";`

**Comment by KatharinaHoff** [comment]
This was fixed here: https://github.com/Gaius-Augustus/BRAKER/commit/b76e9b39ea93e21e398e13a50d39722025623a9f
