### ISSUE TITLE
Samtools sort can be redundant and does not use multiple threads for Genemark-ETP data

### ISSUE THREAD

**Issue by brantfaircloth** [Gaius-Augustus/BRAKER#655]
Hello,

First - thank you for building and maintaining Braker!

I'm using the v3.0.3 container and have noticed that during the initial processing of RNA-seq BAM files, those files are sorted (even if they are already sorted) and the sorting does not take advantage of the `--threads` option in samtools (while mulitple threads *are* used for other `samtools sort` operations in `braker.pl`.

It seems like the `SO` flag in the first line of the header could/should be checked for (desired) sort order before sorting, and (as in other uses of `samtools sort`), the `-@` flag could be added here (I think...):

https://github.com/Gaius-Augustus/BRAKER/blob/master/scripts/braker.pl#L5396-L5397

Thanks again,
-b

**Comment by LarsGab** [comment]
Hi,

the missing multithreading for `samtools sort` was added in BRAKER v3.0.4 .

Best,
Lars

**Comment by brantfaircloth** [comment]
Thank you!
