### ISSUE TITLE
How to convert Braker3's genemark_supported.gtf to GFF3 format for EVM?

### ISSUE THREAD

**Issue by yweii** [Gaius-Augustus/BRAKER#658]
I'm using Braker3 for genome annotation and have obtained the genemark_supported.gtf file, which contains gene annotation information predicted by genemark-ETP. I would like to know how to convert this file to GFF3 format to use it in EVM (EvidenceModeler). GFF3 format is commonly used for genome annotation and can be correctly parsed and processed by EVM.

Additionally, I would like to confirm if genemark_supported.gtf is the main output file of genemark-ETP. I want to ensure that I am working with the correct file and can properly integrate and analyze the gene prediction results in EVM.

Any guidance or suggestions on how to convert genemark_supported.gtf to GFF3 format and clarification on genemark_supported.gtf as the main output file of genemark-ETP would be greatly appreciated.

Thank you!

**Comment by KatharinaHoff** [comment]
@LarsGab can you help in this case?

**Comment by LarsGab** [comment]
Hi,

the main output file for the current version of GeneMark-ETP is the `genemark.gtf `file.

You can convert it to a GFF3 file that is compatible with EVM with a script from the EVM repository ([GeneMarkHMM_GTF_to_EVM_GFF3.pl](https://github.com/EVidenceModeler/EVidenceModeler/blob/master/EvmUtils/misc/GeneMarkHMM_GTF_to_EVM_GFF3.pl))., e.g.
`GeneMarkHMM_GTF_to_EVM_GFF3.pl genemark.gtf > genemark.gff3`

Best, 
Lars

**Comment by LarsGab** [comment]
The `genemark_supported.gtf` file is a subset of transcripts from `genemark.gtf`. It includes all transcripts where at least one intron or start/stop-codon is supported by RNA-Seq or protein evidence. 

The format of the GenMark-ETP output may differ to other GeneMark versions, as it integrates the outputs of GeneMarkS-T and GeneMark.hmm (@alexlomsadze please feel free to correct any inaccuracies). In your situatioin, the conversion might work with [braker_GTF_to_EVM_GFF3.pl](https://github.com/EVidenceModeler/EVidenceModeler/blob/master/EvmUtils/misc/braker_GTF_to_EVM_GFF3.pl). 
A different workaround might be to first reformat the `genemark.gtf` to the format of the BRAKER output with [rename_gtf.py](https://github.com/Gaius-Augustus/TSEBRA/blob/main/bin/rename_gtf.py) and then apply the mentioned conversion script.
