### ISSUE TITLE
fix perl paths

### ISSUE THREAD

**Issue by michaelkarlcoleman** [Gaius-Augustus/BRAKER#66]
Hi,

Some of the Perl scripts use
```
#!/usr/bin/env perl
```
and some do not.  It'd be great if they all did.

Cheers,
Mike

**Comment by KatharinaHoff** [comment]
Thank you for spotting this. It has been fixed in commit https://github.com/Gaius-Augustus/BRAKER/commit/e7d0d4a7b3534e7006c774fd8d8bae7dfaabcf1f .

Best,
Katharina
