### ISSUE TITLE
High level of duplicates

### ISSUE THREAD

**Issue by Harper75** [Gaius-Augustus/BRAKER#664]
Hello,

I used Braker2 to annotate several sofmasqued genomes of lepidoptera. As I do not have RNAseq data, I used the Arthropoda db from OrthoDB. I ran every species with the following commands:

`braker.pl --cores 8 --genome=softmasked_genome.fa --prot_seq=proteins_complete.fasta --augustus_args="--stopCodonExcludedFromCDS=False" –softmasking`

The number of genes predicted is very high, much higher than the results we obtained using Maker. For example, braker predicts more than 33,000 genes for one species while MAKER recovers around 12,000 for that same species, which is similar to what is found for other phylogenetically close species. Busco results show high levels of duplication

 
<img width="1315" alt="Screenshot 2023-08-29 at 14 25 38" src="https://github.com/Gaius-Augustus/BRAKER/assets/96175710/267583bb-3bfd-4a7d-a4f0-4e529537d8f9">

Do you know what could be happening? 

Thanks in advance!

**Comment by KatharinaHoff** [comment]
They could be incorrectly handled alternative transcripts. For all methods,
remove alternatives, and run again.

Harper75 ***@***.***> schrieb am Di. 29. Aug. 2023 um 14:30:

**Comment by Harper75** [comment]
Thanks for your quick reply. You mean remove the  --augustus_args?

Thanks again

**Comment by KatharinaHoff** [comment]
No, filter the gene sets. Keep only one isoform per locus.

Harper75 ***@***.***> schrieb am Di. 29. Aug. 2023 um 15:35:

**Comment by Harper75** [comment]
Perfect, thank you very much.

**Comment by KatharinaHoff** [comment]
It’s only to remove the isoform problem from the BUSCO analysis to check
whether there really are too many duplicates.

Harper75 ***@***.***> schrieb am Di. 29. Aug. 2023 um 15:43:

**Comment by Harper75** [comment]
What is surprising for me is that before the busco analysis showing the duplicates, my Braker results gave more than twice the number of proteins than what is found by maker. 
I do not know if the fact that I use of Arthropoda db from OrthoDB instead of the proteins from a close species (as we did for maker) is giving the differences?
I will check the isoforms.
Thank you.

**Comment by Harper75** [comment]
As you suggested, I removed isoforms from my BRAKER files and this significantly reduced the percentage of duplicates in BUSCO.
Thanks again for all your help.
