### ISSUE TITLE
mv: cannot stat  genemark_hintsfile.gff.rnaseq.tmp': No such file or directory

### ISSUE THREAD

**Issue by kinoppyi** [Gaius-Augustus/BRAKER#665]
Hello,
I am trying to run Braker2 annotation.
The software seems to work fine with the test data, but when I run the analyses on my files, I keep having this problem:

[edoardoscali@ln001 prothint_test]$ braker.pl --genome=../234_genome_2.fasta.masked --hint=prova_filtraggio.gff

Tue Aug 29 13:30:19 2023: Logfile: /global/scratch/users/edoardoscali/S_cupressi_234/annotation/prothint_test/braker/Sp_5/braker.log!
mv: cannot stat '/global/scratch/users/edoardoscali/S_cupressi_234/annotation/prothint_test/braker/Sp_5/genemark_hintsfile.gff.rnaseq.tmp': No such file or directory
ERROR in file /global/home/groups/consultsw/sl-7.x86_64/modules/braker2/2.1.0/braker.pl at line 4248
Failed to execute: mv /global/scratch/users/edoardoscali/S_cupressi_234/annotation/prothint_test/braker/Sp_5/genemark_hintsfile.gff.rnaseq.tmp /global/scratch/users/edoardoscali/S_cupressi_234/annotation/prothint_test/braker/Sp_5/genemark_hintsfile.gff

Pleas, could someone help me with this?
Thank you so much!

**Comment by KatharinaHoff** [comment]
Can you please post the full log?

**Comment by kinoppyi** [comment]
Sure, 

Here is the error message I got:
[edoardoscali@ln002 annotation]$ braker.pl --genome=234_genome.fasta --hints=prothint_test/prova_filtraggio.gff  --workingdir=braker2
# Wed Aug 30 12:15:07 2023: Logfile: /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/braker.log!
mv: cannot stat '/global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/genemark_hintsfile.gff.rnaseq.tmp': No such file or directory
ERROR in file /global/home/groups/consultsw/sl-7.x86_64/modules/braker2/2.1.0/braker.pl at line 4248
Failed to execute: mv /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/genemark_hintsfile.gff.rnaseq.tmp /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/genemark_hintsfile.gff


Here is the log file:
# Wed Aug 30 12:15:07 2023: Configuring of BRAKER for using external tools...
# Wed Aug 30 12:15:07 2023: Found environment variable $BLAST_PATH. Setting $BLAST_PATH to /global/scratch/users/edoardoscali/MAKER/exe/rmblast# Wed Aug 30 12:15:07 2023: Found environment variable $AUGUSTUS_CONFIG_PATH. Setting $AUGUSTUS_CONFIG_PATH to /global/scratch/users/edoardoscali/lavoro_genomi_seiridium/config/
# Wed Aug 30 12:15:07 2023: Found environment variable $AUGUSTUS_BIN_PATH. Setting $AUGUSTUS_BIN_PATH to /global/home/groups/consultsw/sl-7.x86_64/modules/augustus/3.3//bin
# Wed Aug 30 12:15:07 2023: Found environment variable $AUGUSTUS_SCRIPTS_PATH. Setting $AUGUSTUS_SCRIPTS_PATH to /global/home/groups/consultsw/sl-7.x86_64/modules/augustus/3.3//scripts
# Wed Aug 30 12:15:07 2023: Found environment variable $GENEMARK_PATH. Setting $GENEMARK_PATH to /global/home/groups/consultsw/sl-7.x86_64/modules/genemark-es-et/4.33# Wed Aug 30 12:15:07 2023: Found environment variable $BAMTOOLS_PATH. Setting $BAMTOOLS_PATH to /global/home/groups/consultsw/sl-7.x86_64/modules/bamtools/2.5.1/bin/
# Wed Aug 30 12:15:07 2023: Found environment variable $SAMTOOLS_PATH. Setting $SAMTOOLS_PATH to /global/home/groups/consultsw/sl-7.x86_64/modules/samtools/1.14/bin/
# Wed Aug 30 12:15:07 2023: Found environment variable $BLAST_PATH. Setting $BLAST_PATH to /global/scratch/users/edoardoscali/MAKER/exe/rmblast-2.14.0/bin/
# Wed Aug 30 12:15:07 2023: Configuration of BRAKER for using external tools is complete!

# Wed Aug 30 12:15:07 2023: Checking if input file /global/scratch/users/edoardoscali/S_cupressi_234/annotation/prothint_test/prova_filtraggio.gff is in gff format
cd /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2
# Wed Aug 30 12:15:07 2023: Checking whether hints from RNA-Seq and/or proteins are present in hintsfile
# Wed Aug 30 12:15:07 2023: No species was set. Program will use Sp_6.STUS with new_species.pl
braker.log
# Wed Aug 30 12:15:07 2023: changing into working directory /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2
cd /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2

# Wed Aug 30 12:15:07 2023: Creating parameter template files for AUGUSTUS with new_species.pl

# Wed Aug 30 12:15:07 2023: new_species.pl will create parameter files for species Sp_6 in /global/scratch/users/edoardoscali/lavoro_genomi_seiridium/config//species/Sp_6
perl /global/home/groups/consultsw/sl-7.x86_64/modules/augustus/3.3/scripts/new_species.pl --species=Sp_6 --AUGUSTUS_CONFIG_PATH=/global/scratch/users/edoardoscali/lavoro_genomi_seiridium/config/ 1> /dev/null 2>/global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/errors/new_species.stderr

# Wed Aug 30 12:15:07 2023: check_fasta_headers(): Checking fasta headers of file /global/scratch/users/edoardoscali/S_cupressi_234/annotation/234_genome.fasta

# Wed Aug 30 12:15:10 2023: Adding other user provided hints to hintsfile
# Wed Aug 30 12:15:10 2023: filter introns, find strand and change score to 'mult' entry
perl /global/home/groups/consultsw/sl-7.x86_64/modules/braker2/2.1.0/filterIntronsFindStrand.pl /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/genome.fa /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/replaced_hints_0.gff --score 1> /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/filtered_hints_0.gff 2>/global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/errors/filterIntronsFindStrand_userHints_0.stderr


# Wed Aug 30 12:15:11 2023: adding hints from file /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/filtered_hints_0.gff to /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/hintsfile.gff
cat /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/filtered_hints_0.gff >> /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/hintsfile.gff


# Wed Aug 30 12:15:11 2023: deleting file /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/filtered_hints_0.gff

# Wed Aug 30 12:15:11 2023: deleting file /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/replaced_hints_0.gff
# Wed Aug 30 12:15:11 2023: Joining hints that are identical (& from the same source) into multiplicity hints (input file /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/hintsfile.gff)

# Wed Aug 30 12:15:11 2023: sort hints of type all
cat /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/hintsfile.gff | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -n -k 3,3 | sort -s -k 1,1 >/global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/hints.all.temp.sort.gff

# Wed Aug 30 12:15:11 2023: join multiple hints
perl /global/home/groups/consultsw/sl-7.x86_64/modules/augustus/3.3/scripts/join_mult_hints.pl </global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/hints.all.temp.sort.gff >/global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/hintsfile.gff 2>/global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/errors/join_mult_hints.all.stderr

# Wed Aug 30 12:15:12 2023: Preparing hints for running GeneMark

# Wed Aug 30 12:15:12 2023: Filtering intron hints for GeneMark from /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/hintsfile.gff...
cat /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/genemark_hintsfile.gff.prot | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -k 3,3 | sort -s -k 1,1 | /global/home/groups/consultsw/sl-7.x86_64/modules/augustus/3.3/scripts/join_mult_hints.pl > /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/genemark_hintsfile.gff.prot.tmp
mv /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/genemark_hintsfile.gff.rnaseq.tmp /global/scratch/users/edoardoscali/S_cupressi_234/annotation/braker2/genemark_hintsfile.gff


Thank you so much for your help, 
E

**Comment by KatharinaHoff** [comment]
How did you generate the hints file?

**Comment by kinoppyi** [comment]
No, 
It is a protein file from Genemark-ES. 
I assume that that's the wrong file tho. 

So should I run prothint.py with an OrthoDB clade protein set 

prothint.py 234_genome.fasta ORTHO_DB.fasta --geneSeed genemark.gtf --workdir prothint_test

and then use the output as hint? 

I am sorry if I ask this very basic question but I was not able to find a tutorial or a training for very beginner users like me! 

Thank you so much for your help!

**Comment by KatharinaHoff** [comment]
Yes, you need to provide a protein file that contains proteins of a high
degree of redundancy from many species. This can be an OrthoDB partition or
a custom created file.

**Comment by kinoppyi** [comment]
Do you suggest a method in particular in order to prepare a OrthoDB custom file that works as an input for Braker?

I was not able to find a good guide for that and I was wondering if you have a method that works particularly good. 

So far I tryed orthoset_construction and manual download from the website, but It seems that it doesen't works fine for me! 

Thank you so much for your help!

**Comment by KatharinaHoff** [comment]
We provide OrthoDB partitions at https://bioinf.uni-greifswald.de/bioinf/partitioned_odb11/ . If you need a different clade, let me know.
