### ISSUE TITLE
fileparse(): need a valid pathname at /local/cluster/BRAKER/bin/braker.pl line 1809.

### ISSUE THREAD

**Issue by guptapa** [Gaius-Augustus/BRAKER#67]
need help

**Comment by KatharinaHoff** [comment]
https://github.com/Gaius-Augustus/BRAKER/issues/58

**Comment by KatharinaHoff** [comment]
The current code in line 1809 is:

```
$prtStr
            = "\# "
            . (localtime)
            . ": Did not find environment variable \$BAMTOOLS_PATH "
            . "(either variable does not exist, or the path given in "
            . "variable does not exist). Will try to set this variable in a "
            . "different way, later.\n";
```

I therefore assume that you are not using the latest github code. Please update your braker (git clone...). I believe this problem has been fixed.

**Comment by guptapa** [comment]
Thanks Katharina. Can you please send me the link of latest git clone? I guess I have the updated one.
 Parul

**Comment by KatharinaHoff** [comment]
Instructions for example at: https://checkmarx.atlassian.net/wiki/spaces/KC/pages/131432811/GitHub+-+Tips+on+Finding+Git+GitHub+Repository+URLs
