### ISSUE TITLE
BRAKER seems to be stuck at step "Making a gtf file"

### ISSUE THREAD

**Issue by kdarragh1994** [Gaius-Augustus/BRAKER#670]
Hi, 

I ran BRAKER3 using singularity (which I have done before with different data) and the run timed out. When I checked the braker.log file it has been at the "Making a gtf file" step for 2 days. The last time I ran braker this step took only a few minutes. The gtf output file is not present. 

I have started a clean run to see if it happens again but as it takes 10 days to run I hope to work out what the issue is. Any idea what is going on here?

Is there any way to use the output from the previous step and manually run this step to get the gtf output file?

**Comment by KatharinaHoff** [comment]
It's difficult to restart BRAKER on a previous run. It looks odd that it would take 2 days to make a gtf file, though. Is your genome extremely large or highly fragmented?

**Comment by KatharinaHoff** [comment]
Haven't heard from this issue, again. Probably can't fix it with the given information, closing.
