### ISSUE TITLE
Long-Read Protocol: Using isoseq3 collapsed output instead of minimap2 output

### ISSUE THREAD

**Issue by jkmh2** [Gaius-Augustus/BRAKER#672]
Hi there,

I am following the long-read protocol for BRAKER (https://github.com/Gaius-Augustus/BRAKER/blob/master/docs/long_reads/long_read_protocol.md).  Under the section titled "GeneMarkS-T protocol" it states that you should use Minimap2 and Cupcake to create the collapsed isoform file "cupcake.collapsed.gff".  Instead of using "cupcake.collapsed.gff", can I use the IsoSeq Collapse feature of the IsoSeq pipeline (https://isoseq.how/classification/isoseq-collapse.html)?  IsoSeq Collapse also gives "collapsed.gff" as an output file.  

If so, I would be able to substitute my IsoSeq Collapse "collapsed.gff" for "cupcake.collapsed.gff" in the following line of code:

stringtie2fa.py -g genome.fa -f cupcake.collapsed.gff -o cupcake.fa

Thank you very much for any help you can provide me.

**Comment by KatharinaHoff** [comment]
If the file format is the same, this should work. I have not seen an example of the new file.

**Comment by jkmh2** [comment]
Great. Thank you.  Here is what the collapsed.gff file looks like:

##pacbio-collapse-version 1.0
##date Mon Jul 31 18:28:53 2023 UTC
NC_048565.1	PacBio	transcript	409690	421210	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
NC_048565.1	PacBio	exon	409690	409749	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
NC_048565.1	PacBio	exon	410172	410379	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
NC_048565.1	PacBio	exon	415458	415592	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
NC_048565.1	PacBio	exon	415820	415927	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
NC_048565.1	PacBio	exon	416317	416433	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
NC_048565.1	PacBio	exon	416922	417019	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
NC_048565.1	PacBio	exon	418008	418130	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
NC_048565.1	PacBio	exon	419682	421210	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
NC_048565.1	PacBio	transcript	415508	421210	.	+	.	gene_id "PB.1"; transcript_id "PB.1.2";
NC_048565.1	PacBio	exon	415508	415592	.	+	.	gene_id "PB.1"; transcript_id "PB.1.2";
NC_048565.1	PacBio	exon	415820	415927	.	+	.	gene_id "PB.1"; transcript_id "PB.1.2";
NC_048565.1	PacBio	exon	416317	416433	.	+	.	gene_id "PB.1"; transcript_id "PB.1.2";
NC_048565.1	PacBio	exon	416922	417019	.	+	.	gene_id "PB.1"; transcript_id "PB.1.2";
NC_048565.1	PacBio	exon	418008	418130	.	+	.	gene_id "PB.1"; transcript_id "PB.1.2";
NC_048565.1	PacBio	exon	419682	421210	.	+	.	gene_id "PB.1"; transcript_id "PB.1.2";
NC_048565.1	PacBio	transcript	416367	421213	.	+	.	gene_id "PB.1"; transcript_id "PB.1.3";
NC_048565.1	PacBio	exon	416367	416433	.	+	.	gene_id "PB.1"; transcript_id "PB.1.3";
NC_048565.1	PacBio	exon	416922	417019	.	+	.	gene_id "PB.1"; transcript_id "PB.1.3";
NC_048565.1	PacBio	exon	418008	418130	.	+	.	gene_id "PB.1"; transcript_id "PB.1.3";
NC_048565.1	PacBio	exon	419682	421213	.	+	.	gene_id "PB.1"; transcript_id "PB.1.3";
NC_048565.1	PacBio	transcript	416984	421213	.	+	.	gene_id "PB.1"; transcript_id "PB.1.4";
NC_048565.1	PacBio	exon	416984	417019	.	+	.	gene_id "PB.1"; transcript_id "PB.1.4";
NC_048565.1	PacBio	exon	418008	418130	.	+	.	gene_id "PB.1"; transcript_id "PB.1.4";
NC_048565.1	PacBio	exon	419682	421213	.	+	.	gene_id "PB.1"; transcript_id "PB.1.4";
NC_048565.1	PacBio	transcript	418110	421213	.	+	.	gene_id "PB.1"; transcript_id "PB.1.5";
NC_048565.1	PacBio	exon	418110	418130	.	+	.	gene_id "PB.1"; transcript_id "PB.1.5";
NC_048565.1	PacBio	exon	419682	420672	.	+	.	gene_id "PB.1"; transcript_id "PB.1.5";
NC_048565.1	PacBio	exon	420679	421213	.	+	.	gene_id "PB.1"; transcript_id "PB.1.5";
NC_048565.1	PacBio	transcript	419797	421213	.	+	.	gene_id "PB.1"; transcript_id "PB.1.6";
NC_048565.1	PacBio	exon	419797	420672	.	+	.	gene_id "PB.1"; transcript_id "PB.1.6";
NC_048565.1	PacBio	exon	420679	421213	.	+	.	gene_id "PB.1"; transcript_id "PB.1.6";
NC_048565.1	PacBio	transcript	420121	421213	.	+	.	gene_id "PB.1"; transcript_id "PB.1.7";
NC_048565.1	PacBio	exon	420121	421213	.	+	.	gene_id "PB.1"; transcript_id "PB.1.7";
NC_048565.1	PacBio	transcript	499377	501148	.	+	.	gene_id "PB.2"; transcript_id "PB.2.1";
NC_048565.1	PacBio	exon	499377	499682	.	+	.	gene_id "PB.2"; transcript_id "PB.2.1";
NC_048565.1	PacBio	exon	499874	501148	.	+	.	gene_id "PB.2"; transcript_id "PB.2.1";
NC_048565.1	PacBio	transcript	499845	500796	.	+	.	gene_id "PB.2"; transcript_id "PB.2.2";
NC_048565.1	PacBio	exon	499845	500796	.	+	.	gene_id "PB.2"; transcript_id "PB.2.2";
NC_048565.1	PacBio	transcript	499862	501148	.	+	.	gene_id "PB.2"; transcript_id "PB.2.3";
NC_048565.1	PacBio	exon	499862	501148	.	+	.	gene_id "PB.2"; transcript_id "PB.2.3";
NC_048565.1	PacBio	transcript	631935	632592	.	-	.	gene_id "PB.3"; transcript_id "PB.3.1";
NC_048565.1	PacBio	exon	631935	632592	.	-	.	gene_id "PB.3"; transcript_id "PB.3.1";
NC_048565.1	PacBio	transcript	702529	704479	.	-	.	gene_id "PB.4"; transcript_id "PB.4.1";
NC_048565.1	PacBio	exon	702529	702653	.	-	.	gene_id "PB.4"; transcript_id "PB.4.1";
NC_048565.1	PacBio	exon	702661	702793	.	-	.	gene_id "PB.4"; transcript_id "PB.4.1";
NC_048565.1	PacBio	exon	702866	703043	.	-	.	gene_id "PB.4"; transcript_id "PB.4.1";
NC_048565.1	PacBio	exon	703068	703342	.	-	.	gene_id "PB.4"; transcript_id "PB.4.1";
NC_048565.1	PacBio	exon	703351	704451	.	-	.	gene_id "PB.4"; transcript_id "PB.4.1";
NC_048565.1	PacBio	exon	704458	704479	.	-	.	gene_id "PB.4"; transcript_id "PB.4.1";
NC_048565.1	PacBio	transcript	702529	703980	.	-	.	gene_id "PB.4"; transcript_id "PB.4.2";

**Comment by Chrizzy23** [comment]
Hello! I also want to run Braker with long reads. Cupcake says that they recommend using Isoseq instead.
Did it work for you in the end @jkmh2 ?
Also, the long read protocol says that long reads and short reads shall both be used. Would it also work if I only have long reads?

**Comment by jkmh2** [comment]
Hi @Chrizzy23,

As I understand it, the long-read protocol is broken into four different parts:
1. BRAKER1 - for short-read RNA
2. BRAKER2 - for protein data
3. GeneMarkS-T protocol - for long-read RNA
4. TSEBRA - combines the three gene sets from parts 1-3 (BRAKER1, BRAKER2, and GeneMarkS-T protocol) to create a final gene set.  

I believe if you only had long reads, you would only complete part 3 (GeneMarkS-T protocol).  Is my understanding correct, @KatharinaHoff?

Regarding the long-read section of the protocol (GeneMarkS-T), what I did was use the IsoSeq CLI workflow instead of the cupcake script.  Here is the page I followed:
https://isoseq.how/classification/workflow.html

I started with my PacBio consensus reads (ccs.bam) and aligned them to the reference genome using pbmm2. I did this independently with each sequencing pool.  Then, I merged the aligned .bam files using "bamtools merge". Next, I used the command for "Bulk Iso-Seq" to collapse the .bam file into a .gff file.  Finally, I sorted the .gff file using pigeon.  I used this sorted .gff file as input the stringtie step.  Starting with the stringtie step, I simply followed the GeneMartS-T protocol as presented (https://github.com/Gaius-Augustus/BRAKER/blob/master/docs/long_reads/long_read_protocol.md). I was able to get a "gmst.global.gtf" file.  


The cupcake script has not been updated since August 2022.  I tried getting it to work initially but kept running into problems.  The IsoSeq CLI Workflow is definitely the method to use.  Hopefully, you get it to work on your end!

**Comment by Chrizzy23** [comment]
Thank you for your reply @jkmh2 !
I started the IsoSeq CLI workflow as well already. However, there I got stuck between isoseq collapse and pigeon sort since I do not have an annotation file which is prerequisite for the pigeon sort step if I understood it correctly... I'd like to get my annotation with BRAKER though ... am I missing something obvious? I am still quite new to bioinformatics...

**Comment by jkmh2** [comment]
Hi @Chrizzy23,

Wow!  They must have just updated the webpage in the last hour.  When I sent you the link it had a section about pigeon sort using this command:

pigeon sort collapsed.gff -o sorted_longread.gff

According to the new webpage, "pigeon prepare" has replaced "pigeon sort".  However, the new command looks fairly simple:

pigeon prepare <collapsed.gff>

I would try "pigeon prepare your_collapsed.gff" and see if that sorts the file.  I would make a copy of the original collapsed.gff for comparison.  It looks like "pigeon prepare" will sort the file you give it, instead of creating a new file that is sorted.  If you have a copy of the original, you can compare it with the output of "pigeon prepare" just to make sure that it actually sorted the file.  Good luck!  Let me know if you get it to work.

**Comment by KatharinaHoff** [comment]
Yes, you are correct, in this kind of procedure, you can simply skip
merging one gene set with TSEBRA (e.g. the short read gene set).
Please note that the protocol is outdated. It might (if you have short
reads) lead to higher accuracy if you ran BRAKER3 with short read and
protein data, and then merged with the long reads gene set.

**Comment by jkmh2** [comment]
Hi @KatharinaHoff,

Thank you for the update about the protocol.  I will run the long-read protocol the old way (BRAKER1 + BRAKER2 + GeneMarkS-T + TSEBRA) and the new way (BRAKER3 + GeneMarkS-T + TSEBRA) to see if there is any difference in accuracy.  Thank you so much for the insight.

**Comment by jkmh2** [comment]
Hi @KatharinaHoff,

I finished running TSEBRA with two datasets: 
1.  BRAKER1+BRAKER2+GeneMarkS-T
2. BRAKER3+GeneMarkS-T

Is there a way in BRAKER to compare the accuracy of the two methods?

Thank you for your help.

**Comment by KatharinaHoff** [comment]
If you have a high quality reference annotation: yes. But I assume that’s
not the case. We do manual inspection in a genome browser, and we run busco
& omark. Also descriptive statistics may be helpful.

jkmh2 ***@***.***> schrieb am Mo. 13. Nov. 2023 um 23:26:

**Comment by jkmh2** [comment]
Thank you for the quick reply.  I will run BUSCO and OMArk and report back what I find.

**Comment by jkmh2** [comment]
Hi again.  I checked and I believe that I have a high quality reference annotation.  How can I use it to check the accuracy of the BRAKER output?  Thank you.

**Comment by jkmh2** [comment]
Hi @KatharinaHoff,

I was able to compare the accuracy between BRAKER1+BRAKER2+GeneMarkS-T+TSEBRA and BRAKER3+GeneMarkS-T+TSEBRA with GffCompare.  You were correct that using BRAKER3 resulted in higher accuracy!  Thank you for the insight.  From now on, I will use BRAKER3 for short-read RNA and protein data when running the long-read protocol.

Thanks.
