### ISSUE TITLE
Installing BRAKER3

### ISSUE THREAD

**Issue by DiegoSafian** [Gaius-Augustus/BRAKER#673]
Hi,

I just want to know how to install braker3. On the information page, it says "Install as usual". This might be a naive question but,, what do you mean by "as usual"?? is it make, pip??

Thanks
Diego

**Comment by KatharinaHoff** [comment]
Apologies for poor phrasing. We mean: after setting up the conda environment, go through the steps of manual depedency installation that are described in our README.md.

**Comment by DiegoSafian** [comment]
"problem" solved. many thanks
Diego
