### ISSUE TITLE
samtools sort single threaded 

### ISSUE THREAD

**Issue by sadikmu** [Gaius-Augustus/BRAKER#675]
Hi thank you for developing fantastic braker3!

I have noticed that sorting bam files is quite slow and appears to be single threaded (default). This is particularly a bit challenging when dealing with large genomes and it puts a considerable computational loads.  

https://github.com/Gaius-Augustus/BRAKER/blob/a22c638b9404e9762ba178bf63d0add9124dccae/scripts/braker.pl#L5396

Though threading flag could be added but I'm not sure whether this is intended or something that could be fixed. 

Cheers

**Comment by KatharinaHoff** [comment]
Thank you for noticing. That's a mistake, it can easily be multithreaded. I think I fixed it in commit https://github.com/Gaius-Augustus/BRAKER/commit/ca38908eef9a0b78041b3e582d172b7712114298
