### ISSUE TITLE
Script startAlign.pl

### ISSUE THREAD

**Issue by silviaprietob** [Gaius-Augustus/BRAKER#678]
Hello,

I am looking for a script called "startAlign.pl" that is supposed to be in BRAKER/scripts (Hoff and Stanke, 2019) but I can't find it anywhere. Has it been substituted for ProtHint? Is the original script for genome threader still available somewhere?
I am trying to predict with Augustus using protein files (as in Alternate Protocol 2).

Thank you very much!

Silvia

**Comment by LarsGab** [comment]
Hi,

BRAKER doesn't support the use of GenomeThreader anymore and the repository doesn't contain the startAlign.pl script anymore.

If you want to annotate a genome using only protein data. I recommend using the BRAKER2 protocol if you have a large protein database (e.g. from OrthoDB). Or you can use the BRAKER adjacent pipeline [GALBA](https://github.com/Gaius-Augustus/GALBA) if you have proteins from only a few closely related species. 

In case you only need the script, it should be contained in older releases of BRAKER , e.g. [v2.1.6 ](https://github.com/Gaius-Augustus/BRAKER/releases/tag/v2.1.6).

Best,
Lars

**Comment by KatharinaHoff** [comment]
To gain maximal accuracy, please refrain from using the GenomeThreader protocols. As @LarsGab said, the script has been moved to GALBA, but I highly recommend to use miniprot instead of GenomeThreader.

If your goals is to run BRAKER with RNA-Seq and protein input, please run BRAKER3.

**Comment by silviaprietob** [comment]
Thank you both!
