### ISSUE TITLE
The generated gtf file has incorrect gene annotation

### ISSUE THREAD

**Issue by XK4959** [Gaius-Augustus/BRAKER#679]
Hello, while using Brkaer2 and Braker3, I encountered the same problem:
I got the gene annotation file GTF, and there were problems with the annotation of some genes

On the one hand, a large number of errors are reported when submitting to NCBI, such as:
1. In annotation file, the codon_start value for first CDS should be 0 except a partial gene. Those first CDSs' codon_start values are invalid:
4. In annotation file, the CDS length of a transcript should be a multiple of 3. Those CDS features should be fixed for no-triple of CDS length, please fixed them:
5. The following CDS sequence features contain illegal start codon. Please check and fix them:
6. The following CDS sequence features contain illegal stop codon. Please check and fix them:
7. The following CDS sequence features contain internal stop codon. Please check and fix them:

On the other hand, protein and CDS sequences generated using gffread software based on genome and GTF annotations do not begin with a start codon or end with a stop codon. After my observation, the position of the CDS is usually staggered a few places from the correct position. In Brkaer3, proteomes and amino acid groups are generated, and these sequences are fine, with start codons and stop codons. But apparently there was something wrong with their genetic structure annotation!!

You can see that most of the CDS I generate from GTF do not start with a start codon:
![image](https://github.com/Gaius-Augustus/BRAKER/assets/74860841/62fa41a0-3da5-49c9-a2df-cdb8e5d62e18)

Take the first sequence:
> I used gffread to generate based on GTF
GGGATGAACCAGAAGCGGNGTTATGGTGCCAAACTGCGCGCTAACCTAGATCCCACAAAGGGTGTTGGTCGATTAAACNAGCAGCGCGGTGGTCATGGAAGTCGAAATCCGCTAAGGTAGGAGGGCGCGGCGGTTGCTGCAAAACCTTGGGTCNGATCCTGGGCGGAGCGGCCGTTGATGCAGATCTTGGTGGTAGTAGCAAATATTCGAAGANGAACTTTGAAGGCTGAAGAGGAGACACATGGGTTAGTCGATCCTAAGGGTCGGGGGACCNCTGACAGA
>Braker software output CDS
ATGAACCAGAAGCCGGGTTATGGTGCCAAACTGCGCGCTAACCTAGATCCCACAAAGGGT
GTTGGTCGATTAAGACAGCAGCGCGGTGGTCATGGAAGTCGAAATCCGCTAAGGAGTGAG
GGCGCGGCGGTTGCTGCAAAACCTTGGGCTCGATCCTGGGCGGAGCGGCCGTTGATGCAG
ATCTTGGTGGTAGTAGCAAATATTCGAATGAGAACTTTGAAGGCTGAAGAGGAGACACAT
GGGTTAGTCGATCCTAAGGGTCGGGGGAACCCTGACAGATAG

The following are the multiple sequence alignments of the two sequences:
![image](https://github.com/Gaius-Augustus/BRAKER/assets/74860841/add18c93-50cf-459e-bc4b-6e7cffb6c9e6)

**Comment by maol-corteva** [comment]
I had a similar issue, but in my case it was with the GFF v3 output files.  

Apparently the GTF format does not represent the STOP codon as part of the CDS but the GFFv3 spec does (see  https://www.biostars.org/p/206362/  , http://mblab.wustl.edu/GTF22.html and https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md ) .  Both specs want the START codon to be included in the CDS coordinates

I filed [a separate issue](https://github.com/Gaius-Augustus/BRAKER/issues/683) for the GFF and then realized you reported a similar issue for the case of GTF files

**Comment by XK4959** [comment]
Do you know how the problem occurred and how to solve it?

**Comment by KatharinaHoff** [comment]
For stop codon, there are two different definitions: one is including the stop codon in the CDS, the other is excluding the stop codon from CDS. BRAKER sets this option for AUGUSTUS on the basis of the training genes (that come from GeneMark). There's no right or wrong, it's just two different definitions.

Maybe such a different definition exists for start codons, too. I am not sure. @MarioStanke @LarsGab : are you aware of this? gffread seems to use a different start codon definition. Weird.

I usually get errors from NCBI when trying to submit an incomplete gene structure. It can probably fixed by adding some tag to the last column, but I usually simply delete the incomplete gene structures because I never figured out how to do this, correctly.

**Comment by XK4959** [comment]
Hello, after my observation, I basically ruled out the problem of Gffread, which may be the problem of Braker3:

The location information of the specified gene can be obtained by comparing the aa output by Braker3 and the coding sequence to the genome. After obtaining the location information of the gene in question, we compared it to the location in the annotation file generated by Braker3, and found that the location was off by about 2-10 bases, but the total length was fine.

The above phenomenon shows that there is no problem with the length of gene annotation in GFF/GTF, but there is a certain deviation in the position.

The phenomenon can be seen in this diagram, where the I_used_gffrea sequence is generated based on GFF/GTF, and the Braker_softwa sequence is the encoding sequence output by the Braker software. As you can see, the position of the I_used_gffrea sequence is three digits ahead, resulting in no start and stop codons!!
![image](https://github.com/Gaius-Augustus/BRAKER/assets/74860841/f6d5bc52-b9c1-42f9-843b-ddf75cf2cd5b)

**Comment by KatharinaHoff** [comment]
I double checked what getAnnoFastaFromJoingenes.py does (the script that generates the codingseq and aa output of BRAKER & GALBA) and I continue to think that there is nothing wrong with it. 

The linked issue was also addressing the topic of in-frame-stop codons. We are trying to fix them within BRAKER by running AUGUSTUS in a different mode on questionable loci (fix_in_frame_stop_codon_genes.py) 

The coordinates are fine. I assume that also the stop codon issue issue is resolved if you update BRAKER to the most recent version. If problems with the most recent version persist, feel free to reopen.
