### ISSUE TITLE
stderror message: initial exon has length < 3!

### ISSUE THREAD

**Issue by silulinlulu** [Gaius-Augustus/BRAKER#681]
Hello

I ran braker3 on pacbio hifi reads, and the pipeline has finished successfully. However, when i check the error folder, some messages reported : initial exon has length < 3! or
Terminal exon doesn't end in stop codon. Variable stopCodonExcludedFromCDS set right?

could you please shed a light on whether  these messages should be of concerns? and if so, how can i fix it? 

Thank you very much and i am looking forward to your replies.

Silu

**Comment by KatharinaHoff** [comment]
These messages are thrown by etraining. The original "training gene structures" contain errors. We intentionally run etraining within BRAKER to detect these messages and then discard the error causing training gene structures. Everything is well with your BRAKER run unless the final number of training genes resulting from the procedure was very low.

**Comment by silulinlulu** [comment]
Dear Ms Hoff,

Thanks very much for your reply, it helps a lot!

Best regards
Silu
