### ISSUE TITLE
Mamba install problems with Spaln

### ISSUE THREAD

**Issue by ValeroGracia** [Gaius-Augustus/BRAKER#686]
Greetings,

I am trying to use the mamba installation, but it's giving me the following error message:

```
Encountered problems while solving:
- package braker3-3.0.3-hdfd78af_0 requires spaln >=2.4.8, but none of the providers can be installed
```

I already installed Spaln and it is working in the version 2.4.12 <220720>. Could you help me, please?

Thank you in advance. Best regards,

AVG

**Comment by KatharinaHoff** [comment]
We do not maintain the conda recipe ourselves... I  do not know how to do that. You could try running our docker container in singularity, instead.

**Comment by ValeroGracia** [comment]
Thank you :)
