### ISSUE TITLE
ERROR in file bin/braker.pl at line 7852

### ISSUE THREAD

**Issue by mloberme** [Gaius-Augustus/BRAKER#687]
Hey,
I was running Braker3 and got an error at the Augustus gene calling step. 

ERROR in file /DATA_RAID/mlobermeier/data/.snakemake/conda/37f04191d5c028db1d074ffa2a16db0c_/bin/braker.pl at line 7852
Failed to execute: /DATA_RAID/mlobermeier/data/.snakemake/conda/37f04191d5c028db1d074ffa2a16db0c_/bin//augustus --species=Verticilliumstrains --AUGUSTUS_CONFIG_PATH=/DATA_RAID/mlobermeier/data/.snakemake/conda/37f04191d5c028db1d074ffa2a16db0c_/config/ --extrinsicCfgFile=/DATA_RAID/mlobermeier/data/.snakemake/conda/37f04191d5c028db1d074ffa2a16db0c_/bin/cfg/etp.cfg --alternatives-from-evidence=true --hintsfile=/DATA_RAID/mlobermeier/data/Pacbio/Verticillium_dahliae_85S_PacBio/braker/hintsfile.gff --UTR=off --exonnames=on --codingseq=on --allow_hinted_splicesites=gcag,atac --softmasking=1 /DATA_RAID/mlobermeier/data/Pacbio/Verticillium_dahliae_85S_PacBio/braker/genome.fa 1>/DATA_RAID/mlobermeier/data/Pacbio/Verticillium_dahliae_85S_PacBio/braker/augustus.hints.gff 2>/DATA_RAID/mlobermeier/data/Pacbio/Verticillium_dahliae_85S_PacBio/braker/errors/augustus.hints.stderr!

The Augustus hints.gff contains this:

# reading in the file /DATA_RAID/mlobermeier/data/Pacbio/Verticillium_dahliae_85S_PacBio/braker/hintsfile.gff ...
# Have extrinsic information about 53 sequences (in the specified range). 
# Initializing the parameters using config directory /DATA_RAID/mlobermeier/data/.snakemake/conda/37f04191d5c028db1d074ffa2a16db0c_/config/ ...
# Verticilliumstrains version. Using default transition matrix.

I successfully run Braker3 on other genomes, assembled with the same pipeline, but am stuck with this.

Would love some help.

**Comment by LarsGab** [comment]
Hi,

what version of BRAKER3 are you running? What is the content of `errors/augustus.hints.stderr`?

Best, 
Lars

**Comment by mloberme** [comment]
I am running Braker3 3.0.3. 
/DATA_RAID/mlobermeier/data/.snakemake/conda/37f04191d5c028db1d074ffa2a16db0c_/bin//augustus: ERROR
	ExonModel: Couldn't open file /DATA_RAID/mlobermeier/data/.snakemake/conda/37f04191d5c028db1d074ffa2a16db0c_/config/species/Verticilliumstrains/Verticilliumstrains_exon_probs.pbl

**Comment by wuyh0328** [comment]
I also encountered the same problem. Have you solved it？
