### ISSUE TITLE
Incorporating PacBio Isoseq data into BREAKER resulting higher gene duplicate%. 

### ISSUE THREAD

**Issue by ko0000** [Gaius-Augustus/BRAKER#690]
Hi there,

I was following the long-read protocol for BRAKER/TESBRA (https://github.com/Gaius-Augustus/BRAKER/blob/master/docs/long_reads/long_read_protocol.md) to incorporate my Iso-seq result along with BRAKER-RNAseq and BRAKER-Protein for genome structural annotation. 

However, when I ran a BUSCO annotation test of my annotation, there was no change on overall BUSCO score but a higher %duplication compared to only using BRAKER-RNAseq and BRAKER-Protein. I also found several genes of my interest appear redundantly in the annotation. 

**I was wondering if changing the weight in TSEBRA config will help to improve the annotation result? Would you have any suggestion to reduce the number of gene annotation duplication?** 

I used the following configuration for TSEBRA. ( I weight more on my RNAseq data since my protein dataset derive from related species. )

```
# Weight for each hint source
# Values have to be >= 0
P 3
E 3
C 15
M 1
L 1
# Required fraction of supported introns or supported start/stop-codons for a transcript
# Values have to be in [0,1]
intron_support 1
stop_support 1
start_support 2
# Allowed difference for each feature 
# Values have to be in [0,1]
e_1 0
e_2 1
e_3 1
# Values have to be >0
e_4 300
e_5 50
e_6 20
```

Many thanks, 

Ko

**Comment by KatharinaHoff** [comment]
BUSCO generally does not handle alternative transcripts correctly. Most
duplicates reported will be alternative transcript isoforms, which are
mostly not a real problem. You can select one isoform per gene (you can
decide e.g. always the first one, or the longest, whatever you prefer) to
reduce duplicates.

**Comment by ko0000** [comment]
Thanks for the explanation!
