### ISSUE TITLE
stringtie2utr.py  error

### ISSUE THREAD

**Issue by 1039931841** [Gaius-Augustus/BRAKER#692]
Hello,
I would like to use [stringtie2utr.py](https://github.com/Gaius-Augustus/BRAKER/blob/utr_from_stringtie/scripts/stringtie2utr.py) to decorate a braker.gtf, with UTRs from a stringtie.gff file. Intervaltree has been installed. But I am getting a error.

```
(base) [ming@hiplots utr]$ python3 stringtie2utr.py -g braker.gtf -s transcripts_merged.gff -o braker_with_utrs.gtf
  File "/ming/test/TE/utr/stringtie2utr.py", line 366
    if strand == "+" and not seen_cds:setfacl -R -m u:gabriell:rwx /home/nas-hs/projs/
                                                    ^
SyntaxError: invalid syntax
```

How can I get the script working?
Thanks

**Comment by KatharinaHoff** [comment]
Thank you for reporting this. I sometimes accidentally press middle mouse button in the wrong window... this was an accidental paste that was supposed to end up in a terminal window. It is fixed.

Please note that we will not keep the script in the BRAKER repository. It will most likely soon be migrated to TSEBRA or Augustus.

Best,

Katharina

**Comment by ChuanzhengWei** [comment]
I did not find GeneMark-ETP/rnaseq/stringtie/transcripts_merged.gff, so I need to reuse stringtie to obtain a new gff file, and then merge the stringtie.gff and braker.gtf files through stringtie2utr.py?

**Comment by 1039931841** [comment]
> I did not find GeneMark-ETP/rnaseq/stringtie/transcripts_merged.gff, so I need to reuse stringtie to obtain a new gff file, and then merge the stringtie.gff and braker.gtf files through stringtie2utr.py?

Braker3 will delete transcripts_merged.gff after running, you need to view the braker3 run log and save transcripts_merged.gff before the end. Using stringtie alone to obtain a new gff file does not seem to work, and it must use the gff generated by stringtie that is called by the braker3 runtime. It may be caused by the inconsistent parameter settings between stringtie and braker3 when I tried to generate gff with stringtie. Without using singularity, installing brake3 locally and adding the –addUTR=on parameter can also successfully add utr information. I hope my reply is helpful to you.

**Comment by ChuanzhengWei** [comment]
It is a pity that I did not successfully complete the installation of braker3 locally.
