### ISSUE TITLE
Trying to execute an non executable script

### ISSUE THREAD

**Issue by gkanogiannis** [Gaius-Augustus/BRAKER#693]
Hi BRAKER developers,

In `sub run_augustus_jobs` of `braker.pl`, various augustus bash scripts are run by `system("$cmdString")`.
These bash script files have been previously generated by `createAugustusJoblist.pl` and haven been given executable permissions with `system("chmod +x $jobname")`.

Unfortunately in some file systems, the executable bit is not set and these files remain without exec rights and hence `run_augustus_jobs` fails at that point (loine 7684 of `braker.pl` in this case). Most probably there are other points where `system("$cmdString")` will fail.

As a workaround, I replaced `system("$cmdString")` with `system("bash $cmdString")`, unless you have another proposal or workaround.

Best regards,

Anestis

**Comment by KatharinaHoff** [comment]
Thank you for the suggestion. I have addressed it in commit https://github.com/Gaius-Augustus/BRAKER/commit/7729e4f288d5ef7b0f53106c40366cbd861b388e (currently in a branch, but soon merged to master)
