### ISSUE TITLE
allow RNAseq data gzip

### ISSUE THREAD

**Issue by sravel** [Gaius-Augustus/BRAKER#694]
Hello, I am surprised because Breaker downloaded my RNAseq data despite my input path.
Looking at the code I see that it does not take gzip files into account!!!!!
Why no gzip?
I currently have 26GB of fastq RNA-seq Gzip data
Braker downloaded 126GB of unzipped data to me.
Except that, I run an annotation workflow which launches on 6 genomes, therefore which downloads 126 GB 6 times.... !!!!
So is it possible to support fastq gzip files for RNA-seq

**Comment by KatharinaHoff** [comment]
The file download is to my knowledge handled in GeneMark-ETP. Please open an issue in their repository, or send an E-Mail to Alexandre Lomsadze and Mark Borodovsky.

**Comment by sravel** [comment]
No It's Braker who check data
https://github.com/Gaius-Augustus/BRAKER/blob/master/scripts/braker.pl#L2850

**Comment by sravel** [comment]
Thanks lot for your reactivity !!!
