### ISSUE TITLE
BRAKER3 - source RM must be specified in the extrinsic config file

### ISSUE THREAD

**Issue by JiyangChang** [Gaius-Augustus/BRAKER#695]
Hi,

Thanks for the great tool! I've tried to switch from BRAKER2 to BRAKER3, however I met some issues I never met with BRAKER2 (with "--softmasking").

```
ERROR in file /software/shared/apps/x86_64/braker/3.0.3/scripts/braker.pl at line 6708
Failed to execute: /software/shared/apps/x86_64/augustus/3.5.0/bin/augustus --species=Gr4362_draft_braker3 --AUGUSTUS_CONFIG_PATH=/group/annot/usr/augustus/config /scratch/Analysis/Test/Braker3/train.gb.test 1>/scratch/Analysis/Test/Braker3/firsttest.stdout 2>/scratch/Analysis/Test/Braker3/errors/firsttest.stderr!
```

and the detail message in the stderr file is

```
When the softmasking option is turned on, the source RM must be specified in the extrinsic config file.

Could not read in file with the configuration of hints: /group/annot/usr/augustus/config/extrinsic/extrinsic.cfg

/software/shared/apps/x86_64/augustus/3.5.0/bin/augustus: ERROR
	When the softmasking option is turned on, the source RM must be specified in the extrinsic config file.
```

I don't know whether I should use the `--extrinsicCfgFiles` parameter as I don't use it with BRAKER2, could you kindly give me some suggestions about this issue?

BRs,
Jiyang

**Comment by KatharinaHoff** [comment]
Somewhere in between versions, it changed how AUGUSTUS handles soft masked repeats. In the BRAKER container, we use augustus 3.4.0 from debian. Maybe using that exact version will solve your problem.
