### ISSUE TITLE
Can't get past .gm_key issue

### ISSUE THREAD

**Issue by Eigne85** [Gaius-Augustus/BRAKER#696]
GeneMark-ES/ET/EP+ ver 4.72_lic
LINUX 64 kernel 3.10 - 5
I am downloading the above key, moving it to the server and unzipping it then renaming it .gm_key (I have put it in my home directory and copied it to the working directory.
I am using the following script and am still getting the following error. One concern is that I have braker installed and when I call braker in the singularity it is calling braker outside the container. I am not sure if this is a potential problem for the error I am getting. I have had issues uninstalling braker from the system.

```
# Tue Nov  7 04:43:16 2023:Both protein and RNA-Seq data in input detected. BRAKER will be executed in ETP mode (BRAKER3).
#*********
# Tue Nov  7 04:43:17 2023: Log information is stored in file /home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/braker/braker.log
#*********
# WARNING: Detected whitespace in fasta header of file /home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/hsandwicensis_assembly_final.fasta. This may late
r on cause problems! The pipeline will create a new file without spaces or "|" characters and a genome_header.map file to look up the old and new headers. This
 message will be suppressed from now on!
#*********
#*********
# WARNING: Detected whitespace in fasta header of file /home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/lingfei_prot.pep. This may later on cause problem
s! The pipeline will create a new file without spaces or "|" characters and a genome_header.map file to look up the old and new headers. This message will be s
uppressed from now on!
#*********
[cmiller@n19-32-192-drax MyBRAKER]$ more slurm-8983834.out 
# Tue Nov  7 04:43:16 2023:Both protein and RNA-Seq data in input detected. BRAKER will be executed in ETP mode (BRAKER3).
#*********
# Tue Nov  7 04:43:17 2023: Log information is stored in file /home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/braker/braker.log
#*********
# WARNING: Detected whitespace in fasta header of file /home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/hsandwicensis_assembly_final.fasta. This may late
r on cause problems! The pipeline will create a new file without spaces or "|" characters and a genome_header.map file to look up the old and new headers. This
 message will be suppressed from now on!
#*********
#*********
# WARNING: Detected whitespace in fasta header of file /home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/lingfei_prot.pep. This may later on cause problem
s! The pipeline will create a new file without spaces or "|" characters and a genome_header.map file to look up the old and new headers. This message will be s
uppressed from now on!
#*********
ERROR in file /opt/BRAKER/scripts/braker.pl at line 5473
Failed to execute: /usr/bin/perl /opt/ETP/bin/gmetp.pl --cfg /home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/braker/GeneMark-ETP/etp_config.yaml --workd
ir /home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/braker/GeneMark-ETP --bam /home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/braker/GeneMark-ETP/
etp_data/ --cores 1 --softmask  1>/home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/braker/errors/GeneMark-ETP.stdout 2>/home/cmiller/scratch/Braker3Annot
ationsHille/MyBRAKER/braker/errors/GeneMark-ETP.stderr
Failed to execute: /usr/bin/perl /opt/ETP/bin/gmetp.pl --cfg /home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/braker/GeneMark-ETP/etp_config.yaml --workd
ir /home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/braker/GeneMark-ETP --bam /home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/braker/GeneMark-ETP/
etp_data/ --cores 1 --softmask  1>/home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER/braker/errors/GeneMark-ETP.stdout 2>/home/cmiller/scratch/Braker3Annot
ationsHille/MyBRAKER/braker/errors/GeneMark-ETP.stderr
The most common problem is an expired or not present file ~/.gm_key or that GeneMark-ETP didn't receive enough evidence from the input data, in this case, see 
errors/GeneMark-ETP.stderr!


[cmiller@n19-32-192-drax MyBRAKER]$ more BRAKER3Slack.sh 
#!/bin/bash
#SBATCH --job-name=13braker
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=cmiller@rbge.org.uk
#SBATCH --partition=long
#SBATCH --cpus-per-task=16
#SBATCH --mem=40G

singularity exec -H $PWD $APPS/braker3.sif braker.pl \
	--AUGUSTUS_CONFIG_PATH=$PWD/Augustus/config \
	--genome=hsandwicensis_assembly_final.fasta \
	--bam=H01.bam \
	--prot_seq=lingfei_prot.pep


[cmiller@n19-32-192-drax MyBRAKER]$ pwd
/home/cmiller/scratch/Braker3AnnotationsHille/MyBRAKER

[cmiller@n19-32-192-drax MyBRAKER]$ ls
Augustus            MyBRAKERinstalled.sh  
BRAKER311_05.sh     braker                              
BRAKER3HilleNew.sh  braker3.sif  
BRAKER3Slack.sh     config                              
H01.bam             hsandwicensis_assembly_final.fasta
```

**Comment by KatharinaHoff** [comment]
The requirement for a genemark key file luckily no longer exists. I updated documentation and the docker container, today. This may or may not solve your problem... but maybe you are lucky ;-) Just pull the latest container, once more, and try, again.

**Comment by Eigne85** [comment]
> The requirement for a genemark key file luckily no longer exists. I updated documentation and the docker container, today. This may or may not solve your problem... but maybe you are lucky ;-) Just pull the latest container, once more, and try, again.

Ok thank you! Does this apply to singularity as well?

**Comment by Eigne85** [comment]
> > The requirement for a genemark key file luckily no longer exists. I updated documentation and the docker container, today. This may or may not solve your problem... but maybe you are lucky ;-) Just pull the latest container, once more, and try, again.
> 
> Ok thank you! Does this apply to singularity as well?

I am also seeing that I have these errors in the output /errors directory. I am not sure what to do since I dont have a file in my working directory that is called either of those files.

[cmiller@gruffalo errors]$ more GeneMark-ETP.stderr
ln: failed to create symbolic link ‘mapping_H01.bam’: File exists
error
error, file/folder not found: transcripts_merged.fasta.gff
[cmiller@gruffalo errors]$ more GeneMark-ETP.stdout
GeneMarkS: error on last system call, error code 256
Abort program!!!

**Comment by KatharinaHoff** [comment]
yes, I also updated the docker container that you use with singularity. If you pull the latest image, once more, you'll have the current versions of GeneMark-ETP and BRAKER. 

I tested the latest container on our small test files. That does not cover all possible application scenarios. The error that you report may or may not have been fixed by the GeneMark-ETP update, I am not sure. It could also be a file system problem. Some file systems do not allow the creation of symbolic links.

Before running a job with your own data, please use the test data that we provide to confirm that everything runs properly on your system.
