### ISSUE TITLE
braker.gff3 and braker.gtf

### ISSUE THREAD

**Issue by woodoo46** [Gaius-Augustus/BRAKER#700]
Hi there,

When we run the pipeline with --gff3 is specified, the number of lines in file braker.giff3 and braker.gtf are supposed to be the same?
In my case, the number of lines do not match

  1689657 braker.gff3
  1738870 braker.gtf

For example, in the gff3 file, we are missing this line in gtf file.

tig000001	GeneMark.hmm3	transcript	22093	23471	.	+	.	g1.t2

I checked the files, the difference coming from lines whose feature is "mRNA" or "transcript". So I guess this is not very important?

Thanks!

George

**Comment by LarsGab** [comment]
Hi,

the number of lines between the formats might differ slightly. Despite this, the content of the files is the same.
Note that we fixed some issues with the gff3 format, so please make sure that you are using the latest version of BRAKER.

Best, 
Lars
