### ISSUE TITLE
braker3 failed when running with --prot_seq

### ISSUE THREAD

**Issue by woodoo46** [Gaius-Augustus/BRAKER#703]
Hi, there,

I am running braker3 with --prot_seq option. Any idea of what is going? 

[Tue Nov 14 00:31:01 2023] 96827/96827 (100%) pairs aligned
[Tue Nov 14 00:31:01 2023] Alignment of pairs finished
[Tue Nov 14 00:31:01 2023] Translating coordinates from local pair level to contig level
[Tue Nov 14 00:31:07 2023] Finished spliced alignment
[Tue Nov 14 00:31:07 2023] Flagging top chains
[Tue Nov 14 00:31:13 2023] Processing the output
[Tue Nov 14 00:31:34 2023] Output processed
[Tue Nov 14 00:31:34 2023] ProtHint finished.
sort: cannot create temporary file in '/localhd/6566873': No such file or directory
ERROR in file /opt/BRAKER/scripts/braker.pl at line 5302
Failed to execute: /usr/bin/perl /opt/ETP/bin/gmes/gmes_petap.pl --verbose --seq

**Comment by KatharinaHoff** [comment]
sort will attempt to create temporary files when sth is too large to sort
in memory. I assume that this is the cause of the problem, here. Not really
sure why sort would not be able to create that file, though. Are you using
a container?

**Comment by woodoo46** [comment]
Yes. I am using a container, I did not bind /localhd.

**Comment by dmacguigan** [comment]
I am having this same issue. @woodoo46, what was your solution?

**Comment by woodoo46** [comment]
If you are using singularity, you need to bind the proper directory through -B option. I forgot that last time. Hopefully, this helps.

**Comment by dmacguigan** [comment]
Would you mind providing an example? I'm a bit confused because `/scratch/14487641` does not exist on my system.

**Comment by woodoo46** [comment]
singularity exec -B /data -B /localhd ${container} braker.pl --gff3 --genome=${genome} --species ${species} --threads ${threads} --workingdir=${workdir}  ${other}

here, $other is other parameters can be passed to braker3. If you do not have "/scratch/14487641", you may need to create by yourself. On our older system, we need to create it by ourself.
