### ISSUE TITLE
About BRAKER results are converted to Ensemble format

### ISSUE THREAD

**Issue by ld9866** [Gaius-Augustus/BRAKER#707]
Dear developer:
We are wondering if there is any way to convert BRAKER and TSEBRA results into comment files for NCBI or Ensemble commits? If we have this function, I think we can perform the following operations very conveniently.
Best day!

**Comment by KatharinaHoff** [comment]
We do not provide such a converter. One reason is that BRAKER/TSEBRA do not add function annotation to genes, and also, we do not capture a number of possible issues that may arise during submission. 

There's an independent tool https://github.com/NBISweden/EMBLmyGFF3 that I personally never used, but you may find it useful.

EBI/NCBI are planning to create a novel way to easily tag structural genome annotations. Therefore, we will not work on streamlining NCBI or Ensemble submissions. I will close, here.
