### ISSUE TITLE
Braker GeneMark-ES failing

### ISSUE THREAD

**Issue by Zazzyre** [Gaius-Augustus/BRAKER#709]
Hi,
Running with protein data ProtHint finished successfully and then I hit an error:

ERROR in file ./braker.pl at line 6758
Failed to execute: perl /Desktop/gmes_linux_64_4/gmes_petap.pl --verbose --seq /Documents/BRAKER-master/braker/genome.fa --EP /Documents/BRAKER-master/braker/genemark_hintsfile.gff --cores=4  --gc_donor 0.001 --evidence /Documents/BRAKER-master/braker/genemark_evidence.gff  1>/Documents/BRAKER-master/braker/GeneMark-EP.stdout 2>/Documents/BRAKER-master/braker/errors/GeneMark-EP.stderr
Failed to execute: perl /Desktop/gmes_linux_64_4/gmes_petap.pl --verbose --seq /Documents/BRAKER-master/braker/genome.fa --EP /Documents/BRAKER-master/braker/genemark_hintsfile.gff --cores=4  --gc_donor 0.001 --evidence /Documents/BRAKER-master/braker/genemark_evidence.gff  1>/Documents/BRAKER-master/braker/GeneMark-EP.stdout 2>/Documents/BRAKER-master/braker/errors/GeneMark-EP.stderr
The most common problem is an expired or not present file ~/.gm_key!

The stderr file output is:
cat: /braker/GeneMark-EP/output/gmhmm/dna.fa_507.out: Input/output error

and it looks like every other file wrote correctly except the one:

![Screenshot from 2023-11-26 17-09-44](https://github.com/Gaius-Augustus/BRAKER/assets/78663576/284a4a1d-4ee3-4043-b700-8fe2e11208fc)

What would cause the Input/output error and should I just try a rerun or does it indicate my protein file needs some modification?

**Comment by KatharinaHoff** [comment]
Please update to the latest versions of GeneMark-ETP and BRAKER and retry.

Zazzyre ***@***.***> schrieb am Mo. 27. Nov. 2023 um 01:16:

**Comment by Zazzyre** [comment]
After updating GeneMark and BRAKER I'm still running into an error after ProtHint has finished:

ERROR in file ./braker.pl at line 6355
Failed to execute: /home/zazzy/anaconda3/bin/perl /usr/share/augustus/scripts/aa2nonred.pl /home/zazzy/Documents/BRAKER3-master/braker/traingenes.good.fa /home/zazzy/Documents/BRAKER3-master/braker/traingenes.good.nr.fa --DIAMOND_PATH=/home/zazzy/Documents/ProtHint-master/bin --cores=1 --diamond 1> /home/zazzy/Documents/BRAKER3-master/braker/aa2nonred.stdout 2>/home/zazzy/Documents/BRAKER3-master/braker/errors/aa2nonred.stderr

aa2nonred.stderr
ERROR in file /usr/share/augustus/scripts/aa2nonred.pl at line 185
Failed to execute: /home/zazzy/Documents/ProtHint-master/bin/diamond makedb --in /home/zazzy/Documents/BRAKER3-master/braker/traingenes.good.fa.nonreddb -d /home/zazzy/Documents/BRAKER3-master/braker/traingenes.good.fa.nonreddb --threads 1!

**Comment by KatharinaHoff** [comment]
I can imagine two reasons for this problem: an empy file traingenes.good.fa , or a writing permissions problem.
