### ISSUE TITLE
Using viridiplantae database directly 

### ISSUE THREAD

**Issue by ardy20** [Gaius-Augustus/BRAKER#712]
Hi
Can we directly use a downloaded Viridiplantae database in --prot_seq=proteins.fa option?

We downloaded it from OrthoDB 11: https://bioinf.uni-greifswald.de/bioinf/partitioned_odb11/
Regards

**Comment by KatharinaHoff** [comment]
Yes, you can. You can consider simplifying the FASTA headers with https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/simplifyFastaHeaders.pl (BRAKER may complain about the whitespaces in the headers, it's not killing the pipeline though).
