### ISSUE TITLE
Fixing Duplicated BUSCOs

### ISSUE THREAD

**Issue by SaelinB** [Gaius-Augustus/BRAKER#713]
Hello, 

I am annotating a lot of new chlorophyta genomes from an order that is distantly related to anything sequenced. Many don't have RNA data, so I am aligning RNA with the closest related species I can find (and from multiple related species, not just one) using less stringent mapping (hisat2 --score-min L,0,-1). I have also enriched the Viridiplantae_odb10 database with proteomes available for this order. I am using BRAKER1 and BRAKER2 and then TSEBRA to combine results. This seems to work well in most cases. My goal is to use selected genes for phylogenetics, so I am not too worried about false positives currently, although down the line I will be using BRAKER/TSEBRA on other genomes to examine the entire coding capacity.

I've noticed there are a lot of duplicated BUSCOS using intron support of 0.8 and 0.5 with TSEBRA. When I decrease intron support to 0.3, the number of BUSCOS found increases drastically (sometimes by 50%), but also greatly increases duplicated BUSCOS. At all intron supports, these duplicated BUSCOs appear to just be overlapping gene annotations, for example as anno1 and anno2 that have the same start and stop codon but differ by an intron, or have the same start codon and different stop, etc. 

I was wondering if there was a way to go about selecting the best annotation per region to decrease duplicates. I was thinking for overlapping annotations, take the annotation that was found at higher intron support, but this would only fix a fraction of duplicates. Maybe this is just an inherent trade off in intron support thresholds, and I should just take the longest gene as the annotation. 

Thanks for your input!

update: For one genome, I tried taking all annotations that shared a start or stop codon, and selecting the longest protein of those - this decreased duplicated BUSCOs from 24% to 5%, and decreased the number of genes from 14,997 to 10,725. I also lost 10 BUSCOs, which I'll look into. I think I'll go about this method, unless there is anything important I'm overlooking.

**Comment by KatharinaHoff** [comment]
See https://github.com/Gaius-Augustus/BRAKER/issues/690 https://github.com/Gaius-Augustus/BRAKER/issues/664

Also helpful might be a look at the GeMoMa manual containing BUSCO recomputer: https://www.jstacs.de/images/c/c6/GeMoMa-manual.pdf

Or use OMArk instead of BUSCO. OMArk allows you to pass a file with the alternative transcript organization.
