### ISSUE TITLE
gtf gff

### ISSUE THREAD

**Issue by pengyan19** [Gaius-Augustus/BRAKER#725]
When i run the braker, i just obtain the gtf file,but i didn't get the braker.gff3
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/13694900/braker.log)

**Comment by KatharinaHoff** [comment]
You are using a very old version of braker that won't fix, anymore. Function-wise a lot of that old version has been migrated to GALBA https://github.com/Gaius-Augustus/GALBA but we only support miniprot, now, and this will not support bam input.

You can create the gff3 from the gtf file as described in https://github.com/Gaius-Augustus/BRAKER/issues/640

**Comment by pengyan19** [comment]
hello,
I allow the braker to be an option with gff3 added but it just doesn't output. I'm guessing Auguest isn't running. I used the latest version of Singularity, but why is there no new version, why is there no option to add this exonerate software?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gaius-Augustus/BRAKER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月18日(星期一) 晚上8:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Gaius-Augustus/BRAKER] gtf gff (Issue #725)





 
You are using a very old version of braker that we won't fix, anymore. Function-wise a lot of that old version has been migrated to GALBA https://github.com/Gaius-Augustus/GALBA but we only support miniprot, now, and this will not support bam input.
 
You can create the gff3 from the gtf file as described in #640

**Comment by KatharinaHoff** [comment]
In BRAKER, gff3 is generated by running gff2gff.pl (as in issue 640). Something is buggy in the old braker.pl version that you are using. We won't fix it though, because we dropped exonerate a long time ago (due to runtime and accuracy).

**Comment by pengyan19** [comment]
When i used the "singularity&nbsp;braker.pl",&nbsp;I was very surprised at his speed, 10 threads in one night can come out with results.&nbsp;Compared to the old version, we don't get the augustus.hints.* file.&nbsp;Is this normal?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gaius-Augustus/BRAKER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月18日(星期一) 晚上9:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Gaius-Augustus/BRAKER] gtf gff (Issue #725)





 
In BRAKER, gff3 is generated by running gff2gff.pl (as in issue 640). Something is buggy in the old braker.pl version that you are using. We won't fix it though, because we dropped exonerate a long time ago (due to runtime and accuracy).

**Comment by KatharinaHoff** [comment]
Yes, the new output of all BRAKER modes is called
braker.gtf/braker.codingseq/braker.aa It's all output of TSEBRA instead of
augustus.hints.*

**Comment by lalalagartija** [comment]
Hi, I got the same error but with the latest version of braker ran with singularity. 

Is it possible that the issue has not resolved yet? Is there another way to get the gff file? 

Thanks

[braker.log](https://github.com/user-attachments/files/20224501/braker.log)

**Comment by lalalagartija** [comment]
Hi, I got the same error but with the latest version of braker ran with singularity.

Is it possible that the issue has not resolved yet? Is there another way to get the gff file?

Thanks

[braker.log](https://github.com/user-attachments/files/20224501/braker.log)
