### ISSUE TITLE
In braker annotation what are sequence ids start with jg, g and m1-g?

### ISSUE THREAD

**Issue by mudithekanayake** [Gaius-Augustus/BRAKER#726]
Hi,
I have annotated a genome and I have the gtf file. Most of the ids start with jg but there are few sequence ids which start with g and m1-g. I tried find what they are but I could not. Can someone explain why there are differences like that in the gtf file. Thank you.

**Comment by KatharinaHoff** [comment]
The question indicates that you are using a very old version of BRAKER. Please update BRAKER.

The different name stems of genes in that old version indicate the origin of the gene structure. The current BRAKER unifies names (and also merges the transcript sets differently and better.)
