### ISSUE TITLE
the genome and the RNA-seq file do not belong together

### ISSUE THREAD

**Issue by semarpetrus** [Gaius-Augustus/BRAKER#73]
Hi,

I ran into this issue which I also found in the FAQ. I modified my files where genome file headers are now: Node_1, Node_2,...etc and protein file headers are: prot_1, prot_2...etc
but I was still seeing this error. After investigating it, I tracked the problem to the `check_fasta_headers` function in braker.pl. This function is being used to check both the genome file (braker.pl:1164) and each protein file (braker.pl:1168).
However, in all cases it writes the output to "genome.fa" (braker.pl:4295) and assigns `$genome` to that path. Since this function is being called for proteins after the genome, the `$genome` ends up pointing to the protein file and not the genome file. This causes the RNAseq Bam file and the "genome" (which is now the protein file) to "not belong together."

Thank you

**Comment by KatharinaHoff** [comment]
Thank you for reporting this! This went unnoticed for a long time... sorry!

I hope it is fixed with commit https://github.com/Gaius-Augustus/BRAKER/commit/62140de8100653998b4bfcebe560ef7508f8d16d .

Katharina
