### ISSUE TITLE
Error for transcript ID is not unique

### ISSUE THREAD

**Issue by YouxinZhao** [Gaius-Augustus/BRAKER#731]
My job always interrupts due to "Transcript ID is not unique". However, when annotating the genome of chromosomes with fewer scaffolds, this error usually does not occur.

![image](https://github.com/Gaius-Augustus/BRAKER/assets/95477328/e760e994-35f5-49f6-9b73-7c5d4e7aefe0)

The feature of g25.t1 appeared on two contigs.
![image](https://github.com/Gaius-Augustus/BRAKER/assets/95477328/a219fb5c-eef3-476a-b3cf-ace851bf2cc8)

**Comment by KatharinaHoff** [comment]
Can you tell us the version of BRAKER?

YouxinZhao ***@***.***> schrieb am Mo. 25. Dez. 2023 um 06:44:

**Comment by YouxinZhao** [comment]
braker.pl version 3.0.3

**Comment by KatharinaHoff** [comment]
Can you update to 3.0.6. and report whether the problem persists? Maybe it was solved in the meantime.

**Comment by YouxinZhao** [comment]
Thank you very much. The problem was solved.

**Comment by WHEREISSHE** [comment]
> Can you update to 3.0.6. and report whether the problem persists? Maybe it was solved in the meantime.

I am running version 3.0.8, but with the same error occurred.
