### ISSUE TITLE
docker error: bamtools not installed.

### ISSUE THREAD

**Issue by leon945945** [Gaius-Augustus/BRAKER#732]
Hi, I ran BRAKER with docker, but an error was occurred. Here are the run logs:

> [WARN  tini (101094)] Tini is not running as PID 1 and isn't registered as a child subreaper.
> Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
> To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
>  Sat Dec 30 05:22:41 2023:Both protein and RNA-Seq data in input detected. BRAKER will be executed in ETP mode (BRAKER3).
> *********
> **********************************************************************************
>                                BRAKER CONFIGURATION
> **********************************************************************************
>  BRAKER CALL: /opt/BRAKER/scripts/braker.pl --species=WFhap1 --gff3 --threads=8 --genome=/gDir/WFhap1.simple_mask.soft.complex_mask.hard.fasta --bam=/tDir/WFhap1.CF.mask.sort.bam,/tDir/WFhap1.mask.sort.bam --prot_seq=/pDir/citrus_prot.fa
>  Sat Dec 30 05:22:41 2023: braker.pl version 3.0.6
>  Sat Dec 30 05:22:41 2023:Both protein and RNA-Seq data in input detected. BRAKER will be executed in ETP mode (BRAKER3).
> *********
>  Sat Dec 30 05:22:41 2023: Configuring of BRAKER for using external tools...
>  Sat Dec 30 05:22:41 2023: Trying to set $AUGUSTUS_CONFIG_PATH...
>  Sat Dec 30 05:22:41 2023: Found environment variable $AUGUSTUS_CONFIG_PATH.
>  Sat Dec 30 05:22:41 2023: Checking /usr/share/augustus/config/ as potential path for $AUGUSTUS_CONFIG_PATH.
>  Sat Dec 30 05:22:41 2023: Success! Setting $AUGUSTUS_CONFIG_PATH to /usr/share/augustus/config/!
>  Sat Dec 30 05:22:41 2023: Trying to set $AUGUSTUS_BIN_PATH...
>  Sat Dec 30 05:22:41 2023: Found environment variable $AUGUSTUS_BIN_PATH.
>  Sat Dec 30 05:22:41 2023: Checking /usr/bin/ as potential path for $AUGUSTUS_BIN_PATH.
>  Sat Dec 30 05:22:41 2023: Success! Setting $AUGUSTUS_BIN_PATH to /usr/bin/!
>  Sat Dec 30 05:22:41 2023: Trying to set $AUGUSTUS_SCRIPTS_PATH...
>  Sat Dec 30 05:22:41 2023: Found environment variable $AUGUSTUS_SCRIPTS_PATH.
>  Sat Dec 30 05:22:41 2023: Checking /usr/share/augustus/scripts/ as potential path for $AUGUSTUS_SCRIPTS_PATH.
>  Sat Dec 30 05:22:41 2023: Success! Setting $AUGUSTUS_SCRIPTS_PATH to /usr/share/augustus/scripts/!
>  Sat Dec 30 05:22:41 2023: Trying to set $PYTHON3_PATH...
>  Sat Dec 30 05:22:41 2023: Did not find environment variable $PYTHON3_PATH.
>  Sat Dec 30 05:22:41 2023: Trying to guess PYTHON3_PATH from location of python3 executable that is available in your $PATH
>  Sat Dec 30 05:22:41 2023: Checking /opt/conda/bin as potential path for $PYTHON3_PATH.
>  Sat Dec 30 05:22:41 2023: Success! Setting $PYTHON3_PATH to /opt/conda/bin!
>  Sat Dec 30 05:22:41 2023: Trying to set $GENEMARK_PATH...
>  Sat Dec 30 05:22:41 2023: Found environment variable $GENEMARK_PATH.
>  Sat Dec 30 05:22:41 2023: Checking /opt/ETP/bin as potential path for $GENEMARK_PATH.
>  Sat Dec 30 05:22:41 2023: Success! Setting $GENEMARK_PATH to /opt/ETP/bin!
>  Sat Dec 30 05:22:41 2023: Trying to set $BAMTOOLS_PATH...
>  Sat Dec 30 05:22:41 2023: Did not find environment variable $BAMTOOLS_PATH.
>  Sat Dec 30 05:22:41 2023: Trying to guess BAMTOOLS_PATH from location of bamtools executable that is available in your $PATH
>  Sat Dec 30 05:22:41 2023: Checking /usr/bin as potential path for $BAMTOOLS_PATH.
>  Sat Dec 30 05:22:41 2023: Success! Setting $BAMTOOLS_PATH to /usr/bin!
>  Sat Dec 30 05:22:41 2023: Trying to set $SAMTOOLS_PATH...
>  Sat Dec 30 05:22:41 2023: Did not find environment variable $SAMTOOLS_PATH.
>  Sat Dec 30 05:22:42 2023: Trying to guess SAMTOOLS_PATH from location of samtools executable that is available in your $PATH
>  Sat Dec 30 05:22:42 2023: Checking /usr/bin as potential path for $SAMTOOLS_PATH.
>  Sat Dec 30 05:22:42 2023: Success! Setting $SAMTOOLS_PATH to /usr/bin!
>  Sat Dec 30 05:22:42 2023: Trying to set $DIAMOND_PATH...
>  Sat Dec 30 05:22:42 2023: Did not find environment variable $DIAMOND_PATH.
>  Sat Dec 30 05:22:43 2023: Trying to guess DIAMOND_PATH from location of diamond executable that is available in your $PATH
>  Sat Dec 30 05:22:43 2023: Checking /opt/ETP/tools as potential path for $DIAMOND_PATH.
>  Sat Dec 30 05:22:43 2023: Success! Setting $DIAMOND_PATH to /opt/ETP/tools!
>  Sat Dec 30 05:22:43 2023: Trying to set $PROTHINT_PATH...
>  Sat Dec 30 05:22:43 2023: Did not find environment variable $PROTHINT_PATH.
>  Sat Dec 30 05:22:43 2023: Trying to guess PROTHINT_PATH from location of prothint.py executable that is available in your $PATH
>  Sat Dec 30 05:22:43 2023: Checking /opt/ETP/bin/gmes/ProtHint/bin as potential path for $PROTHINT_PATH.
>  Sat Dec 30 05:22:43 2023: Success! Setting $PROTHINT_PATH to /opt/ETP/bin/gmes/ProtHint/bin!
>  Sat Dec 30 05:22:43 2023: Trying to set $TSEBRA_PATH...
>  Sat Dec 30 05:22:43 2023: Did not find environment variable $TSEBRA_PATH.
>  Sat Dec 30 05:22:43 2023: Trying to guess TSEBRA_PATH from location of tsebra.py executable that is available in your $PATH
>  Sat Dec 30 05:22:43 2023: Checking /opt/TSEBRA/bin as potential path for $TSEBRA_PATH.
>  Sat Dec 30 05:22:43 2023: Success! Setting $TSEBRA_PATH to /opt/TSEBRA/bin!
>  Sat Dec 30 05:22:43 2023: Trying to set $CDBTOOLS_PATH...
>  Sat Dec 30 05:22:43 2023: Did not find environment variable $CDBTOOLS_PATH.
>  Sat Dec 30 05:22:43 2023: Trying to guess CDBTOOLS_PATH from location of cdbfasta executable that is available in your $PATH
>  Sat Dec 30 05:22:43 2023: Checking /opt/cdbfasta as potential path for $CDBTOOLS_PATH.
>  Sat Dec 30 05:22:43 2023: Success! Setting $CDBTOOLS_PATH to /opt/cdbfasta!
>  Sat Dec 30 05:22:56 2023: ERROR: in file /opt/BRAKER/scripts/braker.pl at line 2544
> bamtools not installed. Please install it first.
> Warning: this container exposes TCP/IP ports
> 
>  ******************************************************************************
>  *                                                                            *
>  *               STARTING 7a6aaf49-d7df-3595-9e64-d822aab2f3b5                *
>  *                                                                            *
>  ******************************************************************************
>  executing: tini

How to fix it, please give me some suggestions. Thanks very much.

**Comment by KatharinaHoff** [comment]
bamtools are in the container installed at /usr/bin/bamtools . I am surprised that this is not automatically detected. I am routinely running the container in Singularity and never had this problem. 
set the braker.pl option --BAMTOOLS_PATH=/usr/bin/

**Comment by leon945945** [comment]
Thanks for your solution, I'll set the option and try again.

**Comment by leon945945** [comment]
Hi, I added the --BAMTOOLS_PATH parameter, but still coccurred the same error. Bamtools not found.

**Comment by leon945945** [comment]
Hi, I have tried to run `braker` with `singularity`, it runs OK at present.

A little confused question is that I have assigned the parameter `--workingdir` a certain directory, but `braker`outputs intermediate results to `~/braker`. Under this situation, what makes me worried is that if I run another `braker` program with `singularity`, it still outputs intermediate results to `~/braker`, the results of previous `braker` program will be covered and influenced. How can I run anther `braker` program with `singularity`.

**Comment by leon945945** [comment]
I found the reason that `braker` outputs results to ~/braker, the `--workingdir` I mounted to container that `braker` can not find, I changed the mounted directory to the same path name with host directory, then `braker` could output results to `--workingdir`.

**Comment by KatharinaHoff** [comment]
I assume that this issue is solved. I confirmed that bamtools is installed and available in the latest docker container.
