### ISSUE TITLE
aug_ab_initio error!

### ISSUE THREAD

**Issue by sunnycqcn** [Gaius-Augustus/BRAKER#736]
Hello Developer,
When I run my command, I met an aug_ab_initio error. I still can get the results.
my command as following:
`braker.pl --genome=./${line}.mask.fa --prot_seq=Eukaryota.fa --softmasking \
          --threads=80 --species=striga --crf --useexisting --AUGUSTUS_ab_initio --gff3 --overwrite --nocleanup --eval_pseudo=pseudo.gff3 \
          --bam=./ST.bam --addUTR=on && touch  ${line}.braker.addUTR.successfully`

Failed to execute: /isilon/projects/J-002571_clubroot_src_chen/fuf/StGenome/genome/annotation/braker/aug_ab_initio_417!
ERROR in file /isilon/projects/J-002571_clubroot_src_chen/fuf/miniconda/envs/braker3/bin/braker.pl at line 7686
Thanks,
Fuyou

**Comment by jwli-code** [comment]
Hi, I was wondering - does the eval parameter refer to adding a gff file of a related reference species for homology annotation? And what does the --eval_pseudo parameter refer to and what does it do, the help documentation is not clear, thank you

**Comment by sunnycqcn** [comment]
Hello,
Thanks for your reply.
You mean I need to refer a related reference species for using --AUGUSTUS_ab_initio. If I did not refer one, I do not need to use it.
Fuyou

> Hi, I was wondering - does the eval parameter refer to adding a gff file of a related reference species for homology annotation? And what does the --eval_pseudo parameter refer to and what does it do, the help documentation is not clear, thank you

**Comment by sunnycqcn** [comment]
Thanks,
I will try more.
