### ISSUE TITLE
RNAseq.bam not present in example directory, test1.sh fails

### ISSUE THREAD

**Issue by mathog** [Gaius-Augustus/BRAKER#74]
Title pretty much says it all.  The bam file is not present in the github directory even though the README file suggests that it should be.  The failure for test1.log file ends like this:

```
# Fri Sep 20 11:05:04 2019: ERROR: in file /usr/common/modules/el7/x86_64/software/braker/3.0-CentOS-vanilla/bin/braker.pl at line 3820
BAM file /home/u2/beowulf/src/BRAKER/example/tests/../RNAseq.bam does not exist.
```

**Comment by KatharinaHoff** [comment]
This is not a bug. The file must be downloaded separately as documented in
README.md.

**Comment by mathog** [comment]
Yes, I'm guilty as charged of not reading all the documents carefully.  That said, perhaps test1.sh could add an extra line or two to the log file when that specific file is missing:

```
Probably you forgot to do
   wget http://bioinf.uni-greifswald.de/bioinf/braker/RNAseq.bam
in the example directory before running this test.
```

**Comment by KatharinaHoff** [comment]
Good suggestion, I added a comment in the test file. Commit https://github.com/Gaius-Augustus/BRAKER/commit/c6af38ade5645dc3da8c1d18ed1780861274680b
