### ISSUE TITLE
Augustus/bin/augustus not executable on this machine

### ISSUE THREAD

**Issue by ld9866** [Gaius-Augustus/BRAKER#742]
Dear developer:
We are using braker to run annotated genomes, but we ran into some problems when we executed it, indicating that our augustus was unreadable, but in fact it worked perfectly and we also used absolute paths, wondering how you can correct this.
code:
singularity exec /home/test/Software/braker3.sif braker.pl --genome=Ossabaw.fasta.masked --species=Ossabaw --prot_seq=all.fa --min_contig=10000 --softmasking --threads 60 --AUGUSTUS_CONFIG_PATH==/home/test/Software/Augustus/config --AUGUSTUS_BIN_PATH=/home/test/Software/Augustus/bin --AUGUSTUS_SCRIPTS_PATH=/home/test/Software/Augustus/scripts
log:
Sun Jan 14 22:17:18 2024: braker.pl version 3.0.6
Sun Jan 14 22:17:18 2024: Only Protein input detected, BRAKER will be executed in EP mode (BRAKER2).
Sun Jan 14 22:17:18 2024: Configuring of BRAKER for using external tools...
Sun Jan 14 22:17:18 2024: Trying to set $AUGUSTUS_CONFIG_PATH...
Sun Jan 14 22:17:18 2024: Found command line argument $AUGUSTUS_CONFIG_PATH.
Sun Jan 14 22:17:18 2024: Checking =/home/test/Software/Augustus/config as potential path for $AUGUSTUS_CONFIG_PATH.
#*********
WARNING: =/home/test/Software/Augustus/config is not a directory. Will not set $AUGUSTUS_CONFIG_PATH to =/home/test/Software/Augustus/config!
#*********
Sun Jan 14 22:17:18 2024: Found environment variable $AUGUSTUS_CONFIG_PATH.
Sun Jan 14 22:17:18 2024: Checking /usr/share/augustus/config/ as potential path for $AUGUSTUS_CONFIG_PATH.
Sun Jan 14 22:17:18 2024: Success! Setting $AUGUSTUS_CONFIG_PATH to /usr/share/augustus/config/!
Sun Jan 14 22:17:18 2024: Trying to set $AUGUSTUS_BIN_PATH...
Sun Jan 14 22:17:18 2024: Found command line argument $AUGUSTUS_BIN_PATH.
Sun Jan 14 22:17:18 2024: Checking /home/test/Software/Augustus/bin as potential path for $AUGUSTUS_BIN_PATH.
Sun Jan 14 22:17:18 2024: Success! Setting $AUGUSTUS_BIN_PATH to /home/test/Software/Augustus/bin!
Sun Jan 14 22:17:18 2024: Trying to set $AUGUSTUS_SCRIPTS_PATH...
Sun Jan 14 22:17:18 2024: Found command line argument $AUGUSTUS_SCRIPTS_PATH.
Sun Jan 14 22:17:18 2024: Checking /home/test/Software/Augustus/scripts as potential path for $AUGUSTUS_SCRIPTS_PATH.
Sun Jan 14 22:17:18 2024: Success! Setting $AUGUSTUS_SCRIPTS_PATH to /home/test/Software/Augustus/scripts!
Sun Jan 14 22:17:18 2024: Trying to set $PYTHON3_PATH...
Sun Jan 14 22:17:18 2024: Did not find environment variable $PYTHON3_PATH.
Sun Jan 14 22:17:18 2024: Trying to guess PYTHON3_PATH from location of python3 executable that is available in your $PATH
Sun Jan 14 22:17:18 2024: Checking /opt/conda/bin as potential path for $PYTHON3_PATH.
Sun Jan 14 22:17:18 2024: Success! Setting $PYTHON3_PATH to /opt/conda/bin!
Sun Jan 14 22:17:18 2024: Trying to set $GENEMARK_PATH...
Sun Jan 14 22:17:18 2024: Found environment variable $GENEMARK_PATH.
Sun Jan 14 22:17:18 2024: Checking /opt/ETP/bin as potential path for $GENEMARK_PATH.
#*********
WARNING: Couldn't find gmes_petap.pl in /opt/ETP/bin. Will not set $GENEMARK_PATH to /opt/ETP/bin!
#*********
Sun Jan 14 22:17:18 2024: Trying to guess GENEMARK_PATH from location of gmes_petap.pl executable that is available in your $PATH
Sun Jan 14 22:17:18 2024: Checking /opt/ETP/bin/gmes as potential path for $GENEMARK_PATH.
Sun Jan 14 22:17:18 2024: Success! Setting $GENEMARK_PATH to /opt/ETP/bin/gmes!
Sun Jan 14 22:17:18 2024: Trying to set $DIAMOND_PATH...
Sun Jan 14 22:17:18 2024: Did not find environment variable $DIAMOND_PATH.
Sun Jan 14 22:17:18 2024: Trying to guess DIAMOND_PATH from location of diamond executable that is available in your $PATH
Sun Jan 14 22:17:18 2024: Checking /opt/ETP/tools as potential path for $DIAMOND_PATH.
Sun Jan 14 22:17:18 2024: Success! Setting $DIAMOND_PATH to /opt/ETP/tools!
Sun Jan 14 22:17:18 2024: Trying to set $PROTHINT_PATH...
Sun Jan 14 22:17:18 2024: Did not find environment variable $PROTHINT_PATH.
Sun Jan 14 22:17:18 2024: Trying to guess PROTHINT_PATH from location of prothint.py executable that is available in your $PATH
Sun Jan 14 22:17:18 2024: Checking /opt/ETP/bin/gmes/ProtHint/bin as potential path for $PROTHINT_PATH.
Sun Jan 14 22:17:18 2024: Success! Setting $PROTHINT_PATH to /opt/ETP/bin/gmes/ProtHint/bin!
Sun Jan 14 22:17:18 2024: Trying to set $TSEBRA_PATH...
Sun Jan 14 22:17:18 2024: Did not find environment variable $TSEBRA_PATH.
Sun Jan 14 22:17:18 2024: Trying to guess TSEBRA_PATH from location of tsebra.py executable that is available in your $PATH
Sun Jan 14 22:17:18 2024: Checking /opt/TSEBRA/bin as potential path for $TSEBRA_PATH.
Sun Jan 14 22:17:18 2024: Success! Setting $TSEBRA_PATH to /opt/TSEBRA/bin!
Sun Jan 14 22:17:18 2024: Trying to set $CDBTOOLS_PATH...
Sun Jan 14 22:17:18 2024: Did not find environment variable $CDBTOOLS_PATH.
Sun Jan 14 22:17:18 2024: Trying to guess CDBTOOLS_PATH from location of cdbfasta executable that is available in your $PATH
Sun Jan 14 22:17:18 2024: Checking /opt/cdbfasta as potential path for $CDBTOOLS_PATH.
Sun Jan 14 22:17:18 2024: Success! Setting $CDBTOOLS_PATH to /opt/cdbfasta!
Sun Jan 14 22:17:18 2024: ERROR: in file /opt/BRAKER/scripts/braker.pl at line 2505
/home/test/Software/Augustus/bin/augustus not executable on this machine.
INFO:    Cleaning up image...

**Comment by ld9866** [comment]
When we print augustus, then the machine prints 
augustus
AUGUSTUS (3.5.0) is a gene prediction tool.
Sources and documentation at https://github.com/Gaius-Augustus/Augustus

usage:
augustus [parameters] --species=SPECIES queryfilename

'queryfilename' is the filename (including relative path) to the file containing the query sequence(s)
in fasta format.

SPECIES is an identifier for the species. Use --species=help to see a list.

parameters:
--strand=both, --strand=forward or --strand=backward
--genemodel=partial, --genemodel=intronless, --genemodel=complete, --genemodel=atleastone or --genemodel=exactlyone
  partial      : allow prediction of incomplete genes at the sequence boundaries (default)
  intronless   : only predict single-exon genes like in prokaryotes and some eukaryotes
  complete     : only predict complete genes
  atleastone   : predict at least one complete gene
  exactlyone   : predict exactly one complete gene
--singlestrand=true
  predict genes independently on each strand, allow overlapping genes on opposite strands
  This option is turned off by default.
--hintsfile=hintsfilename
  When this option is used the prediction considering hints (extrinsic information) is turned on.
  hintsfilename contains the hints in gff format.
--AUGUSTUS_CONFIG_PATH=path
  path to config directory (if not specified as environment variable)
--alternatives-from-evidence=true/false
  report alternative transcripts when they are suggested by hints
--alternatives-from-sampling=true/false
  report alternative transcripts generated through probabilistic sampling
--sample=n
--minexonintronprob=p
--minmeanexonintronprob=p
--maxtracks=n
  For a description of these parameters see section 2 of RUNNING-AUGUSTUS.md.
--proteinprofile=filename
  When this option is used the prediction will consider the protein profile provided as parameter.
  The protein profile extension is described in section 5 of RUNNING-AUGUSTUS.md.
--progress=true
  show a progressmeter
--gff3=on/off
  output in gff3 format
--predictionStart=A, --predictionEnd=B
  A and B define the range of the sequence for which predictions should be found.
--UTR=on/off
  predict the untranslated regions in addition to the coding sequence. This currently works only for a subset of species.
--noInFrameStop=true/false
  Do not report transcripts with in-frame stop codons. Otherwise, intron-spanning stop codons could occur. Default: false
--noprediction=true/false
  If true and input is in genbank format, no prediction is made. Useful for getting the annotated protein sequences.
--uniqueGeneId=true/false
  If true, output gene identifyers like this: seqname.gN
--/Testing/testMode=prepare, --/Testing/testMode=run, (disabled by default)
  prepare      : prepare a new minimal data set to test comparative Augustus
  intronless   : run prediction over some given minimal data set
  (*) a minimal data set is one retaining only the information need in prediction, usually very small (order of Mb) compared to full sequence data sets (ordet of Gb)

For a complete list of parameters, type "augustus --paramlist". A description of the important ones can be found in the file RUNNING-AUGUSTUS.md.

**Comment by KatharinaHoff** [comment]
I pushed a docker container with the most recent container, today. Please rebuild the singularity image and try with the container augustus (no need to specify the location of that augustus).
