### ISSUE TITLE
braker3 setup.py not found

### ISSUE THREAD

**Issue by MaximePolicarpo** [Gaius-Augustus/BRAKER#745]
Dear BRAKER team,

Thanks a lot for creating a container to run BRAKER3 ! 

I tried to follow the instructions to install the container, but I came across this error : 

singularity exec braker3.sif print braker3 setup.py

FATAL:   "print": executable file not found in $PATH

On the other hand, the command "singularity exec braker3.sif braker.pl" seems to work fine, as I get all the options to run BRAKER.

Thanks a lot for any help ! 

All the best,

Maxime Policarpo

**Comment by Nautilus96** [comment]
Not really a solution, but the contents of the print_setup.py file are displayed here: #597 

I ran into the same problem and couldn't find a fix, but I hope this helps!

**Comment by KatharinaHoff** [comment]
This is not necessary, anymore. Please update to the latest version of BRAKER. setup.py is not required, anymore.
