### ISSUE TITLE
brker3 image is missing the #30 bugfix from compleasm

### ISSUE THREAD

**Issue by epaule** [Gaius-Augustus/BRAKER#746]
Sorry, if that is the wrong reporting location, but it would be great if teambreaker could build a new version to include the compleasm fix from last week (https://github.com/huangnengCSU/compleasm/issues/20), as else compleasm dies downloading file when parsing the md5s

https://hub.docker.com/layers/teambraker/braker3/latest/images/sha256-ea751f781319434131b9a741a3488e0e2b8490522fda8627b2eed9cfc4d32b5e?context=explore&tab=vulnerabilities

**Comment by KatharinaHoff** [comment]
No it’s the right location. I am aware of the problem but currently
traveling. It will be fixed.

Michael Paulini ***@***.***> schrieb am Do. 18. Jan. 2024 um
14:20:

**Comment by KatharinaHoff** [comment]
I have pushed a new image. Both isoseq and latest now contain release 0.2.5 of compleasm.

Since I am traveling, I had limited access to testing resources. It seems to work fine for braker3 mode, that should hold to the other modes of braker as well.
