### ISSUE TITLE
Error in braker.pl at line 5473, .gm_key is up to date, but GeneMark-ETP still doesn't work

### ISSUE THREAD

**Issue by jkmh2** [Gaius-Augustus/BRAKER#749]
**Hi there,

I was running BRAKER3 (short-read RNA and protein data) and it ran into problems during the gmetp.pl step.  Here is the last entry in braker.log:**

# Tue Jan 23 14:09:58 2024: Running gmetp.pl
/usr/bin/perl /opt/GeneMark-ETP-main/bin/gmetp.pl --cfg /home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/GeneMark-ETP/etp_config.yaml --workdir /home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/GeneMar
k-ETP --bam /home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/GeneMark-ETP/etp_data/ --cores 8 --softmask  1>/home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/errors/GeneMark-ETP.stdout 2>/home/jkmh2/US
DA_OmykA_1.1/Practice2_Jan_22_2024/braker/errors/GeneMark-ETP.stderr

**Here is the error from the bash command line:**
ERROR in file /opt/BRAKER-3.0.3/scripts/braker.pl at line 5473
Failed to execute: /usr/bin/perl /opt/GeneMark-ETP-main/bin/gmetp.pl --cfg /home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/GeneMark-ETP/etp_config.yaml --workdir /home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/GeneMark-ETP --bam /home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/GeneMark-ETP/etp_data/ --cores 8 --softmask  1>/home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/errors/GeneMark-ETP.stdout 2>/home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/errors/GeneMark-ETP.stderr
Failed to execute: /usr/bin/perl /opt/GeneMark-ETP-main/bin/gmetp.pl --cfg /home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/GeneMark-ETP/etp_config.yaml --workdir /home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/GeneMark-ETP --bam /home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/GeneMark-ETP/etp_data/ --cores 8 --softmask  1>/home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/errors/GeneMark-ETP.stdout 2>/home/jkmh2/USDA_OmykA_1.1/Practice2_Jan_22_2024/braker/errors/GeneMark-ETP.stderr
The most common problem is an expired or not present file ~/.gm_key or that GeneMark-ETP didn't receive enough evidence from the input data, in this case, see errors/GeneMark-ETP.stderr!

**Here is the GeneMark-ETP.stderr:**
error, file/folder not found: /home/jkmh2/USDA_OmykA_1.1/Practice_Jan_22_2024/braker/GeneMarkETP/
rnaseq/hisat2/mapping_ERX4030517_OmykA_1.1_sorted.bam

**In the "GeneMark-ETP" directory, the "etp_data" directory is empty.  
In /GeneMark-ETP/rnaseq/hisat2 there are bunch of sorted.bam files listed:**
mapping_ERX4030517_OmykA_1.1_sorted.bam  mapping_ERX4030524_OmykA_1.1_sorted.bam  mapping_SRX2894150_OmykA_1.1_sorted.bam  mapping_SRX2894156_OmykA_1.1_sorted.bam  mapping_SRX2894162_OmykA_1.1_sorted.bam
mapping_ERX4030518_OmykA_1.1_sorted.bam  mapping_ERX4030526_OmykA_1.1_sorted.bam  mapping_SRX2894151_OmykA_1.1_sorted.bam  mapping_SRX2894157_OmykA_1.1_sorted.bam  mapping_SRX2894163_OmykA_1.1_sorted.bam
mapping_ERX4030519_OmykA_1.1_sorted.bam  mapping_ERX4030527_OmykA_1.1_sorted.bam  mapping_SRX2894152_OmykA_1.1_sorted.bam  mapping_SRX2894158_OmykA_1.1_sorted.bam  mapping_SRX2894164_OmykA_1.1_sorted.bam
mapping_ERX4030520_OmykA_1.1_sorted.bam  mapping_ERX4030528_OmykA_1.1_sorted.bam  mapping_SRX2894153_OmykA_1.1_sorted.bam  mapping_SRX2894159_OmykA_1.1_sorted.bam
mapping_ERX4030521_OmykA_1.1_sorted.bam  mapping_ERX4030529_OmykA_1.1_sorted.bam  mapping_SRX2894154_OmykA_1.1_sorted.bam  mapping_SRX2894160_OmykA_1.1_sorted.bam
mapping_ERX4030523_OmykA_1.1_sorted.bam  mapping_ERX4030530_OmykA_1.1_sorted.bam  mapping_SRX2894155_OmykA_1.1_sorted.bam  mapping_SRX2894161_OmykA_1.1_sorted.bam

**However, when you try to access the BAM files it says:**
more: cannot open mapping_ERX4030517_OmykA_1.1_sorted.bam: No such file or directory

**It seems like there was a problem with mapping the BAM files.

Even though my .gm_key was not expired, I updated it anyway.  BRAKER still gave the error listed above. 
Here are some commands that show that I am up to date with GeneMark-ES:**  

$ which gmes_petap.pl
/opt/gmes_linux_64_4/gmes_petap.pl
 
$ ./check_install.bash
Checking GeneMark-ES installation
Checking Perl setup
All required Perl modules were found
Checking GeneMark.hmm setup
GeneMark.hmm was found
GeneMark.hmm is set
GeneMark.hmm is executable
Performing GeneMark.hmm test run
All required components for GeneMark-ES were found

**Please help!  I've run out of ideas of what to do.

Thank you,
Johnny**

**Comment by KatharinaHoff** [comment]
Please update BRAKER and its dependencies. The key dependency including
that error message was removed last year. I recommend the singularity
container.

jkmh2 ***@***.***> schrieb am Di. 23. Jan. 2024 um 21:51:

**Comment by jkmh2** [comment]
Thank you for the suggestion.  I got BRAKER to run.  Closing the issue now.
