### ISSUE TITLE
Genemark fails when running RNAseq + Proteing test data

### ISSUE THREAD

**Issue by Nautilus96** [Gaius-Augustus/BRAKER#754]
Hello, 

I've run onto some problems when trying to run Braker on the provided RNAseq and protein test data. 

These are the commands I ran:

`module load conda
conda activate braker3-3.0.7
module load python3/3.8.18
module load genemarketp/1.0
braker.pl --genome /lisc/scratch/evoeco/Valerio/braker_test/BRAKER/example/genome.fa --prot_seq /lisc/scratch/evoeco/Valerio/braker_test/BRAKER/example/proteins.fa --rnaseq_sets_ids ERR5767212 --threads 4 --AUGUSTUS_CONFIG_PATH=/lisc/scratch/evoeco/Valerio/braker_test/config_augustus/ --PROTHINT_PATH=/lisc/app/genemarketp/1.0/bin/gmes/ProtHint/bin  --rnaseq_sets_dir=/lisc/scratch/evoeco/Valerio/braker_test/`

The pipeline fails at the Genemark-ETP step. When digging into the logs, I find the following error within errors/GeneMark-ETP.stderr:

`error on chdir to: /lisc/scratch/evoeco/Valerio/braker/GeneMark-ETP/rnaseq`

GeneMark-ETP/rnaseq is indeed missing, but the program created every other subdirectory successfully, so I am not sure why it failed to create that one in particular. Any advice on how to fix this?

Log of the run:
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/14183230/braker.log)

I am using a conda installation of Braker (3.0.7), installed just a couple of weeks ago.
GeneMark-ETP was installed last November as far as I can tell, and should have both necessary keys (32 and 64)

**Comment by KatharinaHoff** [comment]
Can you use our docker/singularity container? I don't make the conda recipe but we have full control on our containers to debug.

**Comment by Nautilus96** [comment]
Hello,

Thank you for your reply! I downloaded the container, ran the test3.sh script, and everything is working smoothly. I was using the Conda environment since it was already available on our system, but after digging into the GitHub issues, I realized I should have used the container from the start.

I appreciate your time!
