### ISSUE TITLE
braker.codingseq contains coding sequences with introns?

### ISSUE THREAD

**Issue by juanjo255** [Gaius-Augustus/BRAKER#757]
Hello developers,

Thanks for such a useful tool. 

I have a doubt with the braker.codingseq generated with the output. 

Are those coding sequences including introns or they are transcripts like equivalent to a trancriptome.fa?

Thanks for the help,

Juan

**Comment by KatharinaHoff** [comment]
The codingseq file should not contain introns. Please provide an example of where getAnnoFastaFromJoingenes.py produces a wrong output.
