### ISSUE TITLE
compleasm is broken on 18.04 with python 3.69

### ISSUE THREAD

**Issue by cement-head** [Gaius-Augustus/BRAKER#758]
compleasm is broken

$ python3 compleasm.py -run
Traceback (most recent call last):
  File "compleasm.py", line 2743, in <module>
    main()
  File "compleasm.py", line 2626, in main
    subparser = parser.add_subparsers(dest="command", help="Compleasm modules help", required=True)
  File "/usr/lib/python3.6/argparse.py", line 1716, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

**Comment by KatharinaHoff** [comment]
That would be an issue for the compleasm respository. For BRAKER, we provide compleasm in a docker/singularity container. I recommend using that.
