### ISSUE TITLE
ERROR in randomSplit.pl line 47: LOCUS names in genbank file are not unique!

### ISSUE THREAD

**Issue by Hoberti** [Gaius-Augustus/BRAKER#76]
Hi, 
I'm using the last version of BRAKER and Im trying to run it using proteins of short evolutionary distance and RNAseq data. My script is :

braker.pl --species=NewSpecie --genome=Genome.fasta  --bam=sorted.bam --prot_seq=protein.faa --prg=gth --gth2traingenes --fungus --cores=8

The program failed with this error:
ERROR in file /home/BRAKER-master/scripts/braker.pl at line 6845
Failed to execute: perl /usr/share/augustus/scripts/randomSplit.pl /home/braker/train.gb 300 2>/home/braker/errors/randomSplit.stderr

In randomSplit.stderr file
ERROR in randomSplit.pl line 47: LOCUS names in genbank file are not unique!
And I found this error in the gbFilterEtraining.stderr file:
mRNA contains character m
GBProcessor::getGeneList(): GBProcessor::getJoin( ):  failed!!!
Encountered error after reading 823 annotations.
mRNA contains character m
GBProcessor::getGeneList(): GBProcessor::getJoin( ):  failed!!!
Encountered error after reading 1075 annotations.
mRNA contains character m
GBProcessor::getGeneList(): GBProcessor::getJoin( ):  failed!!!
Encountered error after reading 2430 annotations.

Could you help me solve this problem? 
Thank you so much!

**Comment by KatharinaHoff** [comment]
Are you also using the most recent AUGUSTUS release (or current github
code, both should currently work)?

Best,

Katharina

**Comment by KatharinaHoff** [comment]
I am closing this issue because I believe it has been solved.
