### ISSUE TITLE
Cannot resolve accession ( 404 ) when trying to use local files

### ISSUE THREAD

**Issue by simonharnqvist** [Gaius-Augustus/BRAKER#760]
Hi,

I'm having an issue probably related to #621, but with FASTQ files instead. I'm trying to run BRAKER on local FASTQ files, but BRAKER seems to insist on downloading SRA files.

The stderr gives me:
```
2024-02-13T16:38:51 prefetch.3.0.10 err: name not found while resolving query within virtual file system module - failed to resolve accession 'CA_1130_colias_alfacariensis' - Cannot resolve accession ( 404 ); ncbi_phid=939B542307210A5500002E53883C8CC4.1.m_2
```

This is the command I tried to run:
```
braker.pl --genome=[ref path] --species=coliasAlfacariensis--rnaseq_sets_dir=rna_seq --rnaseq_sets_ids=CA_1130_colias_alfacariensis,CA_1130_colias_alfacariensis --GENEMARK_PATH=~ --gff3
```

I've tried changing the names of my samples, but the files names definitely correspond to the given sample names and follow the ID.[12].fastq rule.

Any advice on what I can do to get this to work would be great. Thanks!

**Comment by LarsGab** [comment]
Hi,

sorry for the late reply. 
What exactly are the names of your RNA-seq libraries? For paired-end RNA-Seq reads, the naming convention for BRAKER is either 'ID_[1,2].fastq' or 'ID_[R1,R2].fastq'  (with an underscore and not a dot between ID and 1/2).

Best,
Lars

**Comment by LarsGab** [comment]
This issue may be similar to Issue #777 .
