### ISSUE TITLE
OrthoDB v11 proteome fasta files not fully compatible with BRAKER3

### ISSUE THREAD

**Issue by YanisChrys** [Gaius-Augustus/BRAKER#765]
Hello,

I have downloaded the OrthoDB datasets that are recommended for use with BRAKER in case we dont have our own from here(https://bioinf.uni-greifswald.de/bioinf/partitioned_odb11/) and I am getting the following warning.

```
# WARNING: Detected whitespace in fasta header of file Proteome/Vertebrata.fa.gz. This may later on cause problems! The pipeline will create a new file without spaces or "|" characters and a genome_header.map file to look up the old and new headers. This message will be suppressed from now on!
```

Is this because I am using the unzipped proteome?

Note: I have only tried this with the Vertebrate file.

**Comment by yifeng-evo** [comment]
@YanisChrys  How did you solve it? I have the same issue. Thank you!

**Comment by YanisChrys** [comment]
Hi @yifeng-evo I'm really sorry for the late reply! I believe the problem was indeed that I was using the file while zipped. I looked at your issue (#814 ) and could it be that you're using a compressed file without the compressed extension? I think after I unzipped the file and shortened the headers (just in case) it ran.

**Comment by KatharinaHoff** [comment]
The files need to be unpacked with 

```
gzip file.gz 
```

prior usage with BRAKER.

**Comment by yifeng-evo** [comment]
Thank you! It works now after unpacking!
