### ISSUE TITLE
BRAKER with long read RNA-Seq: which format?

### ISSUE THREAD

**Issue by praimondeau** [Gaius-Augustus/BRAKER#769]
Hello, I'd like to use iso-seq data to annotate my genome, however, it's unclear to me which file i should use? 
My samples were multiplexed in one run, so i have one *subreads.bam+bam.pbi, I have flnc.bam and transcripts.fasta but also hifi.reads.fastq.gz and hifi.reads.fasta.gz for the whole run. 
Thanks

**Comment by praimondeau** [comment]
Hi thanks for the link to the poster. It was helpful. 
If anyone has the same question about format, i used flnc.bam (FLNC reads for my whole run), converted it into fastq with samtools and mapped with minimap2.

**Comment by KatharinaHoff** [comment]
The container was introduced with BRAKER3, so that preprint can be cited.
https://www.biorxiv.org/content/10.1101/2023.06.10.544449v4

praimondeau ***@***.***> schrieb am Di. 2. Apr. 2024 um 16:32:

**Comment by ryvan1021** [comment]
Hello, when I try to run braker3 through the container using:

```
docker exec -it 5d43733fc022 braker.pl --genome=mt8_ul_softmasked.fasta --prot_seq=Viridiplantae.fa --bam=flnc_map_mt8.bam --threads=48 --workingdir=braker3
```
I get this error:
```
# Tue May  7 21:06:23 2024: Trying to guess CDBTOOLS_PATH from location of cdbfasta executable that is available in your $PATH
# Tue May  7 21:06:23 2024: Checking /opt/cdbfasta as potential path for $CDBTOOLS_PATH.
# Tue May  7 21:06:23 2024: Success! Setting $CDBTOOLS_PATH to /opt/cdbfasta!
# Tue May  7 21:06:23 2024: ERROR: in file /opt/BRAKER/scripts/braker.pl at line 3347
BAM file /home/jovyan/flnc_map_mt8.bam does not exist.
```

Any thoughts on what I should do? I tried substituting absolute paths, but I keep getting the same error. Had to run through docker because installing on the cluster with singularity wasn't working for some reason.

Thanks for the great tool!

**Comment by ryvan1021** [comment]
Ah never mind, I think I just didn't mount the image correctly. 'docker run' isn't loading anything so I'll see if it works tomorrow.
