### ISSUE TITLE
Augustus config path error: cp: cannot stat '/usr/share/augustus/config//': No such file or directory

### ISSUE THREAD

**Issue by sanjaysrikakulam** [Gaius-Augustus/BRAKER#772]
Hi, 

Since the last update of the container, we have been facing issues related to the AUGUSTUS tool config and script paths.

**Error**
We are using the container `docker://teambraker/braker3:v3.0.7.3` via singularity, and we get the error `cp: cannot stat '/usr/share/augustus/config//': No such file or directory`

**Solution**
Upon looking into the Dockerfile, I see some leftovers from the last cleanup. Please [remove these lines that overwrite the AUGUSTUS ENVs](https://github.com/Gaius-Augustus/BRAKER/blob/master/Dockerfile#L160-L164)

**Comment by sanjaysrikakulam** [comment]
[PR](https://github.com/Gaius-Augustus/BRAKER/pull/773) removing the overwrite lines

**Comment by KatharinaHoff** [comment]
Thank you! I have merged the request. It was careless of me not to remove that. I will today also push a new image to dockerhub.

**Comment by KatharinaHoff** [comment]
https://hub.docker.com/layers/teambraker/braker3/v3.0.7.4/images/sha256-60448aa9c29d72eb42d2b1bf869e3fa98acbaca5cc6fcad9b0f7097dbd847a8d?context=repo

I will close here. Thanks, again!
