### ISSUE TITLE
Different outputs from same input data

### ISSUE THREAD

**Issue by danielwood1992** [Gaius-Augustus/BRAKER#776]
Hello,

I am finding slightly different sets of genes from different runs of BRAKER3 on the same reference fasta with the same input RNA-seq bams and protein training sets (I have tried this with long-read only, short-read only and long and short read datasets) - it's about 500 genes out of 35,000 (more like 200 with only the short read data). Is this behaviour expected? If the variable genes are more low-confidence, do you have any recommendations of how I might be able to filter these out? (I'm trying to look at presence/absence variants between assemblies so am trying to reduce the number of potential false positives).

Thanks a lot and best wishes,

Daniel Wood

**Comment by KatharinaHoff** [comment]
BRAKER performs random split of genes into training, test and validation sets. This can differ in different runs. We expect some fluctuation, yes. It is not related to how reliable these genes are.
