### ISSUE TITLE
Can this pipeline distinuish the RNAseq data with the fq.gz formart?

### ISSUE THREAD

**Issue by changchuanjun** [Gaius-Augustus/BRAKER#777]
Hello! Thanks for your excellent work on BRAKER pipeline accessions, there is no doubt these pipelines facilatates gene structure annotation with the newly assembling genomes. Here, I have a question that Can this pipeline distinuish the RNAseq data with the fq.gz formart ? When I used this pipeline the command as below.
![1709693840239](https://github.com/Gaius-Augustus/BRAKER/assets/155738984/5f106b7e-f66d-460b-a88a-c439354bb8f1)
I defined the RNAseq data deposited directionary， in the directionary RNAseq datas were fq.gz rather than fastq formart. However, When I ran the script ,It seemed could not find and discriminate the fq.gz ,So it had to download the RNAseq data online. So I am confused that whether this pipeline just know fastq file formart and can not distinguish fq.gz file
Looking forward to your reply sincerely

**Comment by LarsGab** [comment]
Hi,

BRAKER should find RNA-seq libraries ending on `.fq.gz`. Which BRAKER version are you using and what are the file names of your RNA-seq libraries names?

Best, 
Lars

**Comment by changchuanjun** [comment]
BRAKER3, my RNA-seq libraries ending on .fq.gz

**Comment by LarsGab** [comment]
Could you clarify which version number of BRAKER you are using? The current version number can typically be found in the braker.log file, e.g. the current version is v3.0.8. Additionally, could you provide the full filenames of your RNA-seq libraries? BRAKER has a specific naming convention for these files. For unpaired reads, the files should be named `ID.fq.gz`. For paired reads, the filenames should be named like `ID_[1,2].fq.gz` or `ID_[R1,R2].fq.gz`.

**Comment by changchuanjun** [comment]
V3.0.8
![image](https://github.com/Gaius-Augustus/BRAKER/assets/155738984/6a7b00ff-0140-4f87-b7b7-a561a603c2aa)

my RNA-seq libraries names as below. eg SRR4048288_1_paired_clean.fq.gz，SRR4048288_2_paired_clean.fq.gz

![image](https://github.com/Gaius-Augustus/BRAKER/assets/155738984/b4775209-10ec-4216-8c16-a960051aa0c7)

**Comment by LarsGab** [comment]
Thank you for the information. The issue appears to be the `_paired_clean` suffix in your file names. If you remove this suffix and rename them to SRAID_1.fq.gz and SRAID_2.fq.gz, it should resolve the problem.
Best,
Lars

**Comment by changchuanjun** [comment]
Ok, thanks for your reply.Now I have a new problem. I execute gunzip *.fastq command to convert fq.gz file to fastq file.  When i run the script as below. BRAKER reported that absent RNAseq data .I am confused.
![1709732740744](https://github.com/Gaius-Augustus/BRAKER/assets/155738984/6ec5f27c-bcb5-488b-948c-e18ed3af1ddd)

in the braker.log file it reported that Couldn't find local RNA-Seq library for SRR21307590 but actually it is present.
![image](https://github.com/Gaius-Augustus/BRAKER/assets/155738984/a09cf56f-fff4-4c73-b027-566ee787a607)

**Comment by LarsGab** [comment]
The likely cause of the issue is that the RNA-seq libraries are stored outside of your `/home/` directory, which Singularity cannot access by default. To resolve this, you need to bind the` /data/.../RNAseq_fastq` directory to your Singularity container. This can be achieved by adding an additional `-B` option to your singularity exec command. For instance:
`singularity exec -B /path/to/RNA-seq:/path/to/RNA-seq -B $PWD:$PWD ./braker3.sif ...`

**Comment by changchuanjun** [comment]
Yeah, you are right. Thanks for your reminding. 
In addition, I want to ask can I execute command:
 **ln -s /data/.../RNAseq_fastq .** 
and then run singularity exec-B $PWD:$PWD ./braker3.sif ... 
instead of singularity exec -B /path/to/RNA-seq:/path/to/RNA-seq -B $PWD:$PWD ./braker3.sif ...

**Comment by LarsGab** [comment]
In theory, it should work, but I haven't tested it myself. Using the -B option is likely the safer and more reliable approach.

**Comment by changchuanjun** [comment]
Ok,  I see.  Thanks for your guidance and help
