### ISSUE TITLE
BRAKER3 - Finished, with a wierd message

### ISSUE THREAD

**Issue by cement-head** [Gaius-Augustus/BRAKER#782]
Manually installed and compiled BRAKER3 on Ubuntu 22.04 LTS;

Loaded up BRAKER3 and ran it; it _looks_ as if it finished properly (all expected files are out put and the script seems to have done all the cleanup WITHOUT errors)  and the end of the log says this:

```
#**********************************************************************************
#                               BRAKER RUN FINISHED                                
#**********************************************************************************
```

But, I got a couple of weird messages to the terminal:

```

$ braker.pl --threads 48 --makehub --email=************* --busco_lineage=vertebrata_odb10 --species=Goob_goober --genome=goob.softmasked.fasta --prot_seq=vertebrata.fa --rnaseq_sets_ids=ACAGTG,ACTTGA,CTTGTA,GATCAG,GCCAAT,TAGCTT,TGACCA,TTAGGC --rnaseq_sets_dir=/home/RNA-Seq
# Fri Mar 15 10:31:27 2024:Both protein and RNA-Seq data in input detected. BRAKER will be executed in ETP mode (BRAKER3).
#*********
**Use of uninitialized value in subroutine entry at /home/Programs/BRAKER/scripts/braker.pl line 1918.**
# Fri Mar 15 10:31:28 2024: Log information is stored in file /home/goob-Final_Assembly/braker3/braker/braker.log
#*********
# WARNING: in file /home/Programs/BRAKER/scripts/braker.pl at line 1411
file /home/goob-Final_Assembly/braker3/braker/genome.fa contains a highly fragmented assembly (45535 scaffolds). This may lead to problems when running AUGUSTUS via braker in parallelized mode. You set --threads=48. You should run braker.pl in linear mode on such genomes, though (--threads=1).
#*********
**Use of uninitialized value in print at /home/Programs/BRAKER/scripts/braker.pl line 10022.**
```

The first one, use of uninitialized value looks as if it was an empty input file (related to the default location of the AUGUSTUS global install), and looks as if the second one is related to the make_hub.py script (almost at the end), LINE 10022.

**Comment by KatharinaHoff** [comment]
I am trying to figure this out but the current braker.pl has only 10005
lines. Your job complains about line 10022. So something was updated since
you git cloned BRAKER. Can you please git pull your BRAKER version to
update to the latest version and provide the output for that?

**Comment by cement-head** [comment]
/home/cbfgws6/Programs/BRAKER/scripts/braker.pl

**Comment by KatharinaHoff** [comment]
Thanks, yes, I was in a different branch. My mistake. It's a harmless problem, you can ignore the warning. I fixed it in commit https://github.com/Gaius-Augustus/BRAKER/commit/f6480f5c170e45df9d643bbe072949c710952d0f

**Comment by cement-head** [comment]
Cool, then BRAKER3 complleted on a 6.3 Gbp genome! (with a LOT of repeats).

**Comment by KatharinaHoff** [comment]
Good to know! Thx for the feedback!

Andor J Kiss ***@***.***> schrieb am Mo. 1. Apr. 2024 um
19:47:
