### ISSUE TITLE
missing BUSCOs in BRAKER

### ISSUE THREAD

**Issue by zzbbf123** [Gaius-Augustus/BRAKER#784]
Hi: 

I ran Braker3 v3.0.7 with command --busco_lineage embryophyta_odb10 trying to minimize missing BUSCOs. The resulting log file "best_by_compleasm.log" is shown below: 

```
BRAKER is missing 2.35 BUSCOs.
GeneMark is missing 0.62 BUSCOs.
Augustus is missing 0.19 BUSCOs.
All BUSCOs present in augustus.hints.gtf and genemark.gtf will be added to the braker.gtf gene set.
Attempted to merge additional BUSCOs onto braker.gtf but there are no BUSCOs to be added.
The BRAKER gene set /data/braker.gtf is the best one. It lacks 2.35% BUSCOs.
```

Based on my understanding, it appears that BRAKER has the lowest amount of missing BUSCOs at 2.35%. The program attempted to minimize the missing BUSCOs in the final output of BRAKER by re-running TSEBRA, but this attempt was failed because TSEBRA did not identify complete or duplicated BUSCOs without frame shifts (as mentione in issue #660 ). As a result, braker.gtf remains the best option, missing BUSCOs is still 2.35%.

1. I am quite curious about why GeneMark and Augustus are able to predict more BUSCOs than BRAKER. 
2. These additional BUSCOs predicted by GeneMark and Augustus may not be reliable, but they still provide a form of information. If I want to integrate these additional BUSCOs into the BRAKER output,  any command I can use in BRAKER?

Best

**Comment by KatharinaHoff** [comment]
This sounds like a familiar issue. Is your sif file older than 21 days? If
yes, please rebuild your sif file with the latest container. I fixed a
problem 21 days ago, the problem was not in BRAKER but in TSEBRA.

**Comment by zzbbf123** [comment]
yes, you are right. The update makes the result very beautiful and incredibly high...

```
        --------------------------------------------------
        |Results from dataset embryophyta_odb10           |
        --------------------------------------------------
        |C:99.5%[S:76.9%,D:22.6%],F:0.3%,M:0.2%,n:1614    |
        |1606   Complete BUSCOs (C)                       |
        |1241   Complete and single-copy BUSCOs (S)       |
        |365    Complete and duplicated BUSCOs (D)        |
        |5      Fragmented BUSCOs (F)                     |
        |3      Missing BUSCOs (M)                        |
        |1614   Total BUSCO groups searched               |
        --------------------------------------------------
```

I dont have any further questions, please close this issue, thanks.

Best
