### ISSUE TITLE
version 3.0.8 docker: etraining error

### ISSUE THREAD

**Issue by fuesseler** [Gaius-Augustus/BRAKER#788]
Good morning,
I was trying to switch to the newest version of Braker (v.3.0.8) using the docker container but the pipeline fails at the Etraining step:

`ERROR in file /opt/BRAKER/scripts/braker.pl at line 6288
Failed to execute: /opt/Augustus/bin//etraining --species=Sp_56 --AUGUSTUS_CONFIG_PATH=/home/uesseler/miniconda3/pkgs/augustus-3.4.0-pl5321h877ab46_5/config /work/uesseler/docker-braker3-workdir/CtePal_brk3_RNACteno_PROTswissprotodb10vertsaur220324/train.f.gb 1> /work/uesseler/docker-braker3-workdir/CtePal_brk3_RNACteno_PROTswissprotodb10vertsaur220324/gbFilterEtraining.stdout 2>/work/uesseler/docker-braker3-workdir/CtePal_brk3_RNACteno_PROTswissprotodb10vertsaur220324/errors/gbFilterEtraining.stderr
`
I guess the problem might be the double slash here: "/opt/Augustus/bin//etraining" ? I'm not sure if this is a problem with the docker container code, or a problem on my side?

My best regards,
F

**Comment by KatharinaHoff** [comment]
The // is not the problem. What do the stdout and stderr files say?

**Comment by fuesseler** [comment]
Hi!
`Could not locate command line parameters file: /home/uesseler/miniconda3/pkgs/augustus-3.4.0-pl5321h877ab46_5/config/parameters/aug_cmdln_parameters.json.
`
I've added this file now to the augustus config directory and running to check if it works now

**Comment by tanpham15** [comment]
Hi Kathrarina,

Here is my error:

`Failed to execute: /opt/Augustus/bin//etraining --species=Sp_4 --AUGUSTUS_CONFIG_PATH=/data/home/mpx586/.augustus /data/scratch/mpx586/Batesia_hypochlora/RNA/braker3/new_braker2/train.f.gb 1> /data/scratch/mpx586/Batesia_hypochlora/RNA/braker3/new_braker2/gbFilterEtraining.stdout 2>/data/scratch/mpx586/Batesia_hypochlora/RNA/braker3/new_braker2/errors/gbFilterEtraining.stderr`

In the /braker/errors, they reported some errors:

- In file "samtools.sort.rna_trimmed_minimap2.stderr"
`[bam_sort_core] merging from 14 files and 7 in-memory blocks...`

- In file "GeneMark-ETP.stderr":
```
FASTA index file /data/scratch/mpx586/Batesia_hypochlora/RNA/braker3/new_braker2/GeneMark-ETP/data/genome.softmasked.fasta.fai created.
Use of uninitialized value in numeric eq (==) at /opt/ETP/bin/gmes/build_mod.pl line 50.
Use of uninitialized value in numeric eq (==) at /opt/ETP/bin/gmes/build_mod.pl line 56.
04-Apr-24 13:47:58 - INFO: Finding masking penalty maximizing the number of correctly predicted reliable exons in range from 0 to 0.2 with step 0.04
04-Apr-24 13:47:58 - INFO: Running prediction with masking penalty = 0
04-Apr-24 13:53:50 - INFO: Running prediction with masking penalty = 0.04
04-Apr-24 13:59:41 - INFO: Running prediction with masking penalty = 0.08
04-Apr-24 14:05:32 - INFO: Running prediction with masking penalty = 0.12
04-Apr-24 14:11:26 - INFO: Running prediction with masking penalty = 0.16
04-Apr-24 14:17:15 - INFO: Running prediction with masking penalty = 0.2
04-Apr-24 14:23:04 - INFO: Finding masking penalty maximizing the number of correctly predicted reliable exons in range from 0 to 0.04 with step 0.02
04-Apr-24 14:23:04 - INFO: Running prediction with masking penalty = 0.02
04-Apr-24 14:28:57 - INFO: Finding masking penalty maximizing the number of correctly predicted reliable exons in range from 0 to 0.02 with step 0.01
04-Apr-24 14:28:57 - INFO: Running prediction with masking penalty = 0.01
04-Apr-24 14:34:48 - INFO: Selected baseline penalty for the maximum # of correct reliable predictions: 0
04-Apr-24 14:34:48 - INFO: Running prediction with masking penalty = 0.14
04-Apr-24 14:40:38 - INFO: Running prediction with masking penalty = 0.13
04-Apr-24 14:46:31 - INFO: Masking penalty was set to 0.12
Use of uninitialized value in numeric eq (==) at /opt/ETP/bin/gmes/build_mod.pl line 50.
Use of uninitialized value in numeric eq (==) at /opt/ETP/bin/gmes/build_mod.pl line 56.
Use of uninitialized value in numeric eq (==) at /opt/ETP/bin/gmes/build_mod.pl line 50.
Use of uninitialized value in numeric eq (==) at /opt/ETP/bin/gmes/build_mod.pl line 56.
Use of uninitialized value in numeric eq (==) at /opt/ETP/bin/gmes/build_mod.pl line 50.
Use of uninitialized value in numeric eq (==) at /opt/ETP/bin/gmes/build_mod.pl line 56.
```

- In "GeneMark-ETP.stdout"
```
....
# warning, skipping short intron
# warning, skipping short intron
# warning, skipping short intron

90554	29485	61069	32.56	prothint/prothint.gff
47878	29485	18393	61.58	r_hints_nonhc.gtf
```
I am using 8 node * 4 Gb/node.

**Comment by KatharinaHoff** [comment]
What does it say in /data/scratch/mpx586/Batesia_hypochlora/RNA/braker3/new_braker2/gbFilterEtraining.stdout and /data/scratch/mpx586/Batesia_hypochlora/RNA/braker3/new_braker2/errors/gbFilterEtraining.stderr ?

**Comment by tanpham15** [comment]
> What does it say in /data/scratch/mpx586/Batesia_hypochlora/RNA/braker3/new_braker2/gbFilterEtraining.stdout and /data/scratch/mpx586/Batesia_hypochlora/RNA/braker3/new_braker2/errors/gbFilterEtraining.stderr ?

Hi,
When I run both my data and an example of "test3.sh" with braker3_latest.sif, gbFilterEtraining.stderr said:
`Could not locate command line parameters file: /data/home/mpx586/.augustus/parameters/aug_cmdln_parameters.json.`
and I didn't get gbFilterEtraining.stderr when running braker3_isoseq.sif

**Comment by spoonbender76** [comment]
Hi,

I got the same error in the latest container(`singularity build braker3.sif docker://teambraker/braker3:latest`) .

` gbFilterEtraining.stdout ` says
` Could not locate command line parameters file: /home/cnrri01/.augustus/parameters/aug_cmdln_parameters.json.`

and `gbFilterEtraining.stderr` is empty.

**Comment by tanpham15** [comment]
I am done. 30:45:22 of running, here is the resource I used: 4 nodes * 3Gb/node on HPC, (I got the error when I request 6 nodes).

**Comment by KatharinaHoff** [comment]
I think these issues are all related to an outdated local augustus config path folder. I have added the solution to this issue to the README.md (start page of the github repository), you only need to delete the local config folder, once. I think it's resolved, right? I will close. Please reopen if I got this wrong.
