### ISSUE TITLE
Failed to create directory!

### ISSUE THREAD

**Issue by karthickbrlab** [Gaius-Augustus/BRAKER#791]
Braker Failed to create directory!

Sun Mar 24 11:20:59 2024: Log information is stored in file /home/BRAKER/scripts/braker/braker.log
ERROR in file braker.pl at line 1173
Failed to create direcotry /home/BRAKER/scripts/braker/GeneMark-ES!

**Comment by KatharinaHoff** [comment]
This looks like a file system problem, not a BRAKER problem. The executing user needs writing permission.

**Comment by karthickbrlab** [comment]
Found that, BRAKER can't overwrite the file. So it produces error creating directory!.
/home/BRAKER/scripts/braker..

Remove the braker folder from previous run. it will work normally.

By the way, IS THERE ANY OPTION TO OVERWRITE/RERUN IF RUN FAILS PREMATURELY?
