### ISSUE TITLE
error: No spliced alignments were created by Spaln 

### ISSUE THREAD

**Issue by karthickbrlab** [Gaius-Augustus/BRAKER#793]
I just used proteins from arabidopsis thaliana in --prot.seq. 

error: No spliced alignments were created by Spaln (/home/ubuntu/BRAKER/scripts/braker/Spaln/spaln.gff is empty).
This error can be caused by:
    a) The set of input proteins is too small and/or the proteins are too remote.
    b) The gene seeds identified by GeneMark-ES (or the supplied gene seeds in case the option "--geneSeeds" was used) are incorrect. Please try running GeneMark-ES separately to identify errors related to gene seeds (https://github.com/gatech-genemark/ProtHint#genemark-es).

**Comment by tanpham15** [comment]
Hi,

I also got this error message. I used proteins database for Arthropoda.gz. 
Moreover, I rerun GeneMark separately, but I didn't find any error (please check the gmes.log and gmetp.sh.o3447546 for detail)

Best regards,
Tan

**Comment by karthickbrlab** [comment]
hi,

I rerun with Viridiplantae proteins.gz, still getting this error.


cat: nuc_2091718_prot_2091718: No such file or directory
rm: cannot remove 'nuc_2091718_prot_2091718': No such file or directory
/home/ubuntu/deru/Deru_data/genemark/ProtHint/spalnBatch.sh: line 61: /home/ubuntu/deru/Deru_data/genemark/ProtHint/../dependencies/spaln_boundary_scorer: No such file or directory
cat: nuc_2091719_prot_2091719: No such file or directory
rm: cannot remove 'nuc_2091719_prot_2091719': No such file or directory
[Thu Apr  4 09:58:25 2024] 2091719/2091719 (100%) pairs aligned
[Thu Apr  4 09:58:25 2024] Alignment of pairs finished
[Thu Apr  4 09:58:25 2024] Translating coordinates from local pair level to contig level
[Thu Apr  4 09:58:28 2024] Finished spliced alignment
error: No spliced alignments were created by Spaln (/home/ubuntu/BRAKER/scripts/braker/Spaln/spaln.gff is empty).

This error can be caused by:
    a) The set of input proteins is too small and/or the proteins are too remote.
    b) The gene seeds identified by GeneMark-ES (or the supplied gene seeds in case the option "--geneSeeds" was used) are incorrect. Please try running GeneMark-ES separately to identify errors related to gene seeds (https://github.com/gatech-genemark/ProtHint#genemark-es).

ERROR in file braker.pl at line 5355
Failed to execute /home/ubuntu/genemark/ProtHint/prothint.py --threads=1 --geneMarkGtf /home/ubuntu/BRAKER/scripts/braker/GeneMark-ES/genemark.gtf /home/ubuntu/BRAKER/scripts/braker/genome.fa /home/ubuntu/BRAKER/scripts/braker/proteins.fa!

**Comment by karthickbrlab** [comment]
Im closing this issue.

Worked well after reinstallation
