### ISSUE TITLE
ERROR: in file /opt/BRAKER/scripts/braker.pl at line 4490

### ISSUE THREAD

**Issue by Wangray123** [Gaius-Augustus/BRAKER#798]
Hello! 
I am running Braker v2.1.5 in singularity to annotate the genomic data of fungi with RNA data,  then, I get this error message: 
    ERROR: in file /opt/BRAKER/scripts/braker.pl at line 4490
    Genome file /home/data/t150418/workspace/1511Genome/07Braker/1511.genome.fa.masked --softmasking does not exist.

I'm sure the file name and path correctly. And I keep getting this error that i dont really know how to troubleshoot. So hope someone can help.

Details are as follows：
# BRAKER CALL: /opt/BRAKER/scripts/braker.pl --cores 12 --species=Myspecies --genome=/home/data/t150418/workspace/1511Genome/07Braker/1511.genome.fa.masked --softmasking --fungus --bam=/home/data/t150418/workspace/1511Genome/06hisat2/WTrnaseq.bam --gff3
# Mon Apr  8 21:32:13 2024: braker.pl version 2.1.5
# Mon Apr  8 21:32:13 2024: Configuring of BRAKER for using external tools...
# Mon Apr  8 21:32:13 2024: Found environment variable $AUGUSTUS_CONFIG_PATH. Setting $AUGUSTUS_CONFIG_PATH to /home/data/t150418/augustus_config
# Mon Apr  8 21:32:13 2024: Found environment variable $AUGUSTUS_BIN_PATH. Setting $AUGUSTUS_BIN_PATH to /opt/augustus/bin
# Mon Apr  8 21:32:13 2024: Found environment variable $AUGUSTUS_SCRIPTS_PATH. Setting $AUGUSTUS_SCRIPTS_PATH to /opt/augustus/scripts
# Mon Apr  8 21:32:13 2024: Found environment variable $GENEMARK_PATH. Setting $GENEMARK_PATH to /opt/GeneMark-ET/gmes_linux_64
# Mon Apr  8 21:32:13 2024: Found environment variable $BAMTOOLS_PATH. Setting $BAMTOOLS_PATH to /opt/bamtools/bin**
# Mon Apr  8 21:32:13 2024: Found environment variable $SAMTOOLS_PATH. Setting $SAMTOOLS_PATH to /opt/samtools
# Mon Apr  8 21:32:13 2024: Found environment variable $DIAMOND_PATH. Setting $DIAMOND_PATH to /opt/Diamond
# Mon Apr  8 21:32:13 2024: Did not find environment variable $PYTHON3_PATH
# Mon Apr  8 21:32:13 2024: Trying to guess $PYTHON3_PATH from location of python3 executable that is available in your $PATH
# Mon Apr  8 21:32:13 2024: Setting $PYTHON3_PATH to /usr/bin
# Mon Apr  8 21:32:13 2024: Did not find environment variable $CDBTOOLS_PATH
# Mon Apr  8 21:32:13 2024: Trying to guess $CDBTOOLS_PATH from location of cdbfasta executable that is available in your $PATH
# Mon Apr  8 21:32:13 2024: Setting $CDBTOOLS_PATH to /usr/bin
# Mon Apr  8 21:32:13 2024: ERROR: in file /opt/BRAKER/scripts/braker.pl at line 4490
Genome file /home/data/t150418/workspace/1511Genome/07Braker/1511.genome.fa.masked --softmasking does not exist.

**Comment by KatharinaHoff** [comment]
softmasking is default, now. Just delete the option --softmasking.

**Comment by Wangray123** [comment]
Solved now. Thanks a lot！
