### ISSUE TITLE
Queries on Isoseq data in braker

### ISSUE THREAD

**Issue by karthickbrlab** [Gaius-Augustus/BRAKER#799]
hi.
I processed isoseq data and aligned with genome using minimap.
Now how can i proceed to use the bam file in braker.

Im unable to use the singularity for isoseq data.
can i use same protocol as RNAseq data using stringtie?

I tried doing this. I found the floowing errror.
stringtie is required by GeneMark-ETP but it is not an executable file in your $PATH!

Kindly provide your suggestions

**Comment by KatharinaHoff** [comment]
I interprete this as you are not using our container but you are dealing with a local custom software installation. I recommend that you have a look at our Dockerfile https://github.com/Gaius-Augustus/BRAKER/blob/master/Dockerfile lines 206-213 (you need to activate those commented lines). That's where you see what GeneMark-ETP we a cloning and what branch we are checking out. A minimal modification is required in ETP to assemble the long read mapping file with StringTie. Either full that particular ETP branch, or make the local modification, yourself.

ETP comes with a subfolder tools. You may have to add that to your path. stringtie sits in the tools folder.

**Comment by karthickbrlab** [comment]
Im quite new to linux,

How can i pull that particular branch.
or can i just use dockerfile to do so?

Im having some issues with singularity.

thank you

**Comment by KatharinaHoff** [comment]
You may want to either find someone who helps you install Singularity, or take a bash online course. Then ask ChatGPT (or similar service) to convert the docker directives into bash commands. Sorry, I cannot provide support to learn bash. We provide the container because we don't have the resources to support installation issues.

**Comment by karthickbrlab** [comment]
Thanks for the info.

**Comment by karthickbrlab** [comment]
I have installed singularity.

Run failed after this error.
Could not locate command line parameters file: /home/ubuntu/.augustus/parameters/aug_cmdln_parameters.json.

Is there any option to continue the run or otherwise i should start it again freshly.

Thank you

**Comment by KatharinaHoff** [comment]
Please delete the folder /home/ubuntu/.augustus (or place the missing file
in the correct location).

kbsivakumar ***@***.***> schrieb am Fr. 12. Apr. 2024 um
13:36:

**Comment by karthickbrlab** [comment]
Worked well. Thanks for your assistance

**Comment by karthickbrlab** [comment]
hi.

sorry for frequent queries.

I have done braker predictions with isoseq data and protein data.

I have used protein models from arabidopsis and i got 30000 genes, next i have used entire orthodb- viridiplantae protein data, in that run i got 58000 genes.

So which one could be appropriate and good to go?

thank you

**Comment by KatharinaHoff** [comment]
Have you combined them with TSEBRA? You definitely want to filter our
models from the 58000 set, and TSEBRA can do that for you.

kbsivakumar ***@***.***> schrieb am Mo. 15. Apr. 2024 um
09:02:

**Comment by karthickbrlab** [comment]
Yes singularity run had included TSEBRA for transcript selection and i got it from the log file.

So should i go for predictions made from arabidopsis protein model?
