### ISSUE TITLE
GeneMark-ETP license key for singularity container

### ISSUE THREAD

**Issue by pstrope** [Gaius-Augustus/BRAKER#802]
Hi Katharina, I saw in docker hub this:

> the license key for GeneMark-ETP is not residing in the container (yet) and needs to be installed into your home directory. To get help with hat, run:
> 
> singularity exec braker3.sif print_braker3_setup.py

But when I try that command, there is not such py file. 

Is this still an issue, or we don't need to do this anymore for the singularity container?

Thanks,
Pooja

**Comment by KatharinaHoff** [comment]
Thank you for reporting the outdated information. I deleted it from the Dockerhub page.

The key file was dropped several months ago.
