### ISSUE TITLE
ERROR in file /opt/BRAKER/scripts/braker.pl at line 10092, Failed to open directory ${workingdir}

### ISSUE THREAD

**Issue by yyliang12** [Gaius-Augustus/BRAKER#807]
Hi, 

Thanks for developing such a power annotation pipeline!

When I run the BRAKER program, I get an error during the file deleting phase:

```plain
......
# Thu Apr 18 16:41:27 2024: find /home/yanyang_liang/ProgramFiles/2024/03_Aco_Annotation/02_Gene_Annotation/02_BRAKER3/P1_hap1 -empty
# Thu Apr 18 08:41:54 2024: deleting job lst files (if existing)

↑Those are the final records of braker.log
```

The STDERR of the `braker.pl` program is:

```plain
ERROR in file /opt/BRAKER/scripts/braker.pl at line 10092
Failed to open directory /home/yanyang_liang/ProgramFiles/2024/03_Aco_Annotation/02_Gene_Annotation/02_BRAKER3/P1_hap1!
```

The command I ran `braker.pl` was:

```bash
singularity exec -B /home/yanyang_liang:/home/yanyang_liang --writable braker3_sandbox braker.pl \
--gff3 \
--workingdir /home/yanyang_liang/ProgramFiles/2024/03_Aco_Annotation/02_Gene_Annotation/02_BRAKER3/P1_hap1 \
--AUGUSTUS_CONFIG_PATH ${AUGUSTUS_Config_Dir} \
--species ${Species_Name} \
--useexisting \
--threads ${threads} \
--genome ${Soft_Masked_Genome} \
--prot_seq ${Protein_Seq} \
--bam ${BAM_File} > ${log} 2>&1
```

What is more strange is that the **test data** can be completed through the same command properly without any errors popped out. Why would this happen?

Thanks,
Yanyang.

**Comment by KatharinaHoff** [comment]
I have no idea why it happened, but it's part of the cleanup function. You should have all results available, already.

**Comment by yyliang12** [comment]
> I have no idea why it happened, but it's part of the cleanup function. You should have all results available, already.

Hi Dr. Hoff,

Thanks for answering anyway!

I think it might be the some problems with the [Snakemake](https://snakemake.github.io/) script cuz I executed the BRAKER singularity image via Snakemake:
```python
rule BRAKER:
    input:
    output:
    singularity:
        braker.sif
    shell:
        """
        braker.pl
        """
```

I just test the same data using a Bash script with all input files under `${PWD}` path, 
```bash
#!/bin/bash
singularity exec -B ${PWD}:${PWD} braker.pl
```
, turns out the whole `braker.pl` pipeline can be finished completely.

Thanks,
Yanyang.
