### ISSUE TITLE
Error in fix_in_frame_stop_codon_genes_augustus.Ppri5.err

### ISSUE THREAD

**Issue by Gscalves** [Gaius-Augustus/BRAKER#81]
**Hi, I'm trying to execute Braker (2.1.4) pipeline and during the Augusts training step while running the script:**

/conda/acgt/anaconda2/envs/Braker2/bin/python3 /conda/acgt/anaconda2/envs/Braker2/bin/fix_in_frame_stop_codon_genes.py -g /braker/ge
nome.fa -t /braker/augustus.Ppri5.gtf -b /braker/bad_
genes.lst -o augustus.Ppri5_fix_ifs_ -s musa -m on --UTR off --print_utr off -a /conda/acgt/anaconda2/envs/Braker2/config/ -C /lbi/acgt/bioinfo/bin -A /conda/acgt/anaconda2/envs/Braker2/bin/ -S /conda/acgt/anaco
nda2/envs/Braker2/bin/ -H //braker/hintsfile.gff.Ppri5 -e /conda/acgt/anaconda2/envs/Braker2/bin/cfg/gth.cfg  > /braker/fix_in_frame_stop_codon_genes_augustus.Ppri5.log 2> /braker/errors
/fix_in_frame_stop_codon_genes_augustus.Ppri5.err

**I received the following error:**

File "/conda/acgt/anaconda2/envs/Braker2/bin/fix_in_frame_stop_codon_genes.py", line 7
    < !DOCTYPE html >
    ^
SyntaxError: invalid syntax

**Has anyone experienced this issue?**

**Thanks**

**Comment by KatharinaHoff** [comment]
Line 7 of fix_in_frame_stop_codon_genes.py contains a comment (hash character at the beginning of line). The script itself is not part of BRAKER, but of AUGUSTUS. However, this might be a conda issue. I am linking Natasha @npavlovikj , creator of the BRAKER conda receipe, in case she knows what to do in this case.
