### ISSUE TITLE
fails to execute compleasm; error line 4551 in braker.pl

### ISSUE THREAD

**Issue by AAHRU-Ablab** [Gaius-Augustus/BRAKER#811]
BRAKER2 successfully completes when I run the instance without BUSCO lineage (I am using a genome assembly and OrthoDB proteins). I am interested in this additional BUSCO analyses; however, when I run with BUSCO lineage I get an error at the compleasm step. The files are executable and in my path but stalls. Any help would be greatly appreciated. I have recreated the error at "Starting BRAKER on the basis of previously existing BRAKER runs" step with the code:

`perl /home/jason/Desktop/software/BRAKER-3.0.8/scripts/braker.pl --threads=78 --GENEMARK_PATH=/home/jason/Desktop/software/gmes_linux_64_4 --DIAMOND_PATH=/home/jason/Desktop/software/diamond_blast --PROTHINT_PATH=/home/jason/Desktop/software/gmes_linux_64_4/ProtHint/bin --TSEBRA_PATH=/home/jason/Desktop/software/TSEBRA/bin --AUGUSTUS_BIN_PATH=/home/jason/Desktop/software/Augustus/bin --AUGUSTUS_SCRIPTS_PATH=/home/jason/Desktop/software/Augustus/scripts --AUGUSTUS_CONFIG_PATH=/home/jason/Desktop/software/Augustus/config --COMPLEASM_PATH=/home/jason/Desktop/software/compleasm_kit --useexisting --skipAllTraining --genome=masked_sequences.fasta --busco_lineage=actinopterygii_odb10`

### error returned in stdout:
ERROR in file /home/jason/Desktop/software/BRAKER-3.0.8/scripts/braker.pl at line 4551
Failed to execute: /usr/bin/python3 /home/jason/Desktop/software/Augustus/scripts/compleasm_to_hints.py -p /home/jason/Desktop/software/compleasm_kit/compleasm.py -g /home/jason/Desktop/test/braker/braker/genome.fa -d actinopterygii_odb10 -t 78 -o /home/jason/Desktop/test/braker/braker/compleasm_hints.gff 1> /home/jason/Desktop/test/braker/braker/errors/compleasm_to_hints.stderr 2>&1!

### error returned in the compleasm_to_hints.stderr: 
Trying to execute the following command:
/home/jason/Desktop/software/compleasm_kit/compleasm.py run -l actinopterygii_odb10 -a /home/jason/Desktop/test/braker/braker/genome.fa -t 78 -o compleasm_genome_out
Suceeded in executing command.
Error in file /home/jason/Desktop/software/Augustus/scripts/compleasm_to_hints.py at line 49: Return code of subprocess was 1['/home/jason/Desktop/software/compleasm_kit/compleasm.py', 'run', '-l', 'actinopterygii_odb10', '-a', '/home/jason/Desktop/test/braker/braker/genome.fa', '-t', '78', '-o', 'compleasm_genome_out']

**Comment by KatharinaHoff** [comment]
It could be a version problem. What compleasm version are you using? Could
you switch to using our singularity image?

AAHRU-Ablab ***@***.***> schrieb am Di. 23. Apr. 2024 um
17:00:

**Comment by AAHRU-Ablab** [comment]
When I pulled compleasm from Git, the latest (0.2.6) was downloaded instead of the recommended (0.2.5). Also, ran the Singularity instance and it performed flawlessly. Thank you very much for your suggestions!
