### ISSUE TITLE
add transcriptomes to input

### ISSUE THREAD

**Issue by YanisChrys** [Gaius-Augustus/BRAKER#812]
Hello,

I am using published annotations of closely related species to annotate my genomes and they provide of course with the transcriptomes produced during their experiments. (*rna.faa.gz files)  and arguably these are good assembled gene transcripts that also incude UTRs.

Is there a way to use these with BRAKER? Is there a benefit in using these together with the protein sequences they are used to create? Finally, if not, may I suggest including the possibility of including this data in BRAKER?

This could be related to the following issue:

https://github.com/Gaius-Augustus/BRAKER/issues/585

**Comment by KatharinaHoff** [comment]
There are lot of ideas and no  manpower to implement things at the moment.

You can use transcriptome evidence of this type in WebAUGUSTUS.

**Comment by YanisChrys** [comment]
That's understandable, but thank you for replying and thank you for the suggestion! :)
