### ISSUE TITLE
Using OrthoDB proteins and functional annotation

### ISSUE THREAD

**Issue by enriquepola1996** [Gaius-Augustus/BRAKER#815]
Hello dear BRAKER developers,

1. I want to annotate a fungal genome for which I do not have RNA-seq evidence, so I intend to use proteins as evidence, however, I have doubts about how to use this option. I have downloaded the Fungi.fa.gz file from https://bioinf.uni-greifswald.de/bioinf/partitioned_odb11/ and I would like to know if I can use this file directly for annotation, let's say something like this:

braker.pl --genome=genome.fa --prot_seq=Fungi.fa

Is it correct to run the annotation this way or do I have to process that file first?

2. I did a test without evidence and I'm getting two outputs, one from braker and one from Augustus, which one should I use?

```
[user@server braker]$ ls -lh
total 44M
drwx------ 2 user 4.0K Apr 29 17:37 Augustus
drwxrwxr-x 2 user 4.0K Apr 29 17:37 GeneMark-ES
-rw-rw-r-- 1 user 7.4M Apr 29 17:37 braker.aa
-rw-rw-r-- 1 user  22M Apr 29 17:37 braker.codingseq
-rw-rw-r-- 1 user  14M Apr 29 17:37 braker.gtf
-rw-rw-r-- 1 user 111K Apr 29 17:37 braker.log
drwxrwxr-x 2 user 4.0K Apr 29 17:37 errors
-rw-rw-r-- 1 user 5.7K Apr 29 17:10 genome_header.map
drwxrwxr-x 3 user 4.0K Apr 29 17:29 species
-rw-rw-r-- 1 user 1.4K Apr 29 17:37 what-to-cite.txt

[user@server braker]$ ls -lh Augustus/
total 31M
-rw-rw-r-- 1 user 5.3M Apr 29 17:37 augustus.ab_initio.aa
-rw-rw-r-- 1 user  16M Apr 29 17:37 augustus.ab_initio.codingseq
-rw-rw-r-- 1 user 9.6M Apr 29 17:37 augustus.ab_initio.gtf
```

3. The other question is, Is it possible to use the protein file for functional annotation? For example braker.aa or  augustus.ab_initio.aa

I would greatly appreciate the advice.

**Comment by enriquepola1996** [comment]
Thank you very much, it has worked very well for my work.

**Comment by KatharinaHoff** [comment]
We recommend adding RNA-Seq evidence.

We have not assessed accuracy in fungi (but I have used it in practice on
fungi and results seemed ok).
