### ISSUE TITLE
How to fix the --busco_lineage argument issue in braker3?

### ISSUE THREAD

**Issue by RezwanCAAS** [Gaius-Augustus/BRAKER#817]
Hi braker team, I am running this code for braker3 but having this issue regarding 

**Unknown option: busco_lineage
Error in command line arguments**

I have also download the eudicotes lineage as "mb_downloads"

```
module load braker/3.0.3/singularity
export AUGUSTUS_CONFIG_PATH=/Augustus/config/ \

singularity exec -B $PWD,/ibex,/sw /ibex/scratch/projects/ibex_cs_temp/47882/braker3.sif braker.pl \
 --workingdir=~path/braker1/ \
 --genome=genome.fasta.masked \
 --prot_seq=ghb_db_cg_os_le.fa \
 --bam=$RNA_seq
 --crf --busco_lineage=eudicots_odb10 --threads=32 --AUGUSTUS_CONFIG_PATH=/Augustus/config/ \
 --filterOutShort
```

Could you please guide how to fix this busco issue.
moreover, please suggest what more arguments I can add in command as per your expertise.

Regards
Rezwan

**Comment by KatharinaHoff** [comment]
Are you sure you are running the latest container? Just rebuild and confirm.

Rezwan Tariq ***@***.***> schrieb am Do. 2. Mai 2024 um 12:43:

**Comment by RezwanCAAS** [comment]
the server admin team installed the latest one as per their information.
Just now, I change the command like

```
eudicots_odb10=~path/mb_downloads/

--busco_lineage=$eudicots_odb10


```
its working now 
Actaully, I installed the new compleasm version 0.2.6 and download the eudicots lineage as mb_downloads. 
Do you suggest some good arguments in order to have more better results.

Regards
Rezwan

**Comment by RezwanCAAS** [comment]
sorry again, It again shows the same error like 
**Unknown option: busco_lineage
Error in command line arguments**

**Comment by KatharinaHoff** [comment]
I don't trust that information because it says braker3.0.3 in your
initial post. that version did indeed not know that argument. We are now at
3.0.8. You need to rebuild the container image with the latest sources.

**Comment by RezwanCAAS** [comment]
Yes, thank you @KatharinaHoff . It makes sense and admin team has installed the latest one. Now the compleasm is working under braker3.
