### ISSUE TITLE
Unknown option: threads

### ISSUE THREAD

**Issue by Arodiansyah21** [Gaius-Augustus/BRAKER#827]
Hey there,

I attempted to execute Braker using the following script:

home/achmad/Apps/BRAKER/BRAKER/scripts/braker.pl --genome=final_sequence.fasta --prot_seq=reference/protein_brakerdb.fasta --softmasking --workingdir=gene_prediction/braker --threads 100

However, it failed with an error message stating:

Unknown option: threads
Error in command line arguments

Previously, the script ran successfully without the --threads argument, but it took a considerable amount of time to complete. I'm dealing with a large genome of Salacca zalacca.

I've already installed the "threads" Perl module.

Can anyone assist me with this issue? 

Thank you.

**Comment by KatharinaHoff** [comment]
Are you using the latest version? An older version would not know this
option.

Arodiansyah21 ***@***.***> schrieb am Do. 16. Mai 2024 um
10:00:

**Comment by Arodiansyah21** [comment]
Hy Katharina,

We're currently utilizing Braker version 2.1.6. 
Furthermore, do you have guidelines on how to upgrade Braker to the latest version?

I'm worried that if I update to the latest version, our current Braker might not be usable, because I'm still a newbie in this field.

Thank you,

**Comment by Arodiansyah21** [comment]
> Hy Katharina,
> 
> We're currently utilizing Braker version 2.1.6. Furthermore, do you have guidelines on how to upgrade Braker to the latest version?
> 
> I'm worried that if I update to the latest version, our current Braker might not be usable, because I'm still a newbie in this field.
> 
> Thank you,


In my braker version. the output without "--threads" argument resulted like this

**#CPU threads: 1**
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: 
blaablaaablaaa............

So its consume a lot of times haha. Meanwhile, my computer having 112 CPU.

**Comment by KatharinaHoff** [comment]
If you use an older version, you have to use the older usage.

I generally recommend upgrading because a lot issues have been improved,
accuracy has increased. But you are correct, some older features are not
supported, anymore.
