### ISSUE TITLE
proteins of distant relatives

### ISSUE THREAD

**Issue by webbchen** [Gaius-Augustus/BRAKER#84]
Dear Katharina

I'm trying to run braker with hints of distantly related proteins. Is there a way to make augustus accept hint files which are not produced by ProSplign? The suggetsed pipeline contains at least one program which doesn't run in our distribution of Linux because they're ancient (procompart and ProSplign).

Is there a possible workaround for that problem?

**Comment by tomasbruna** [comment]
Hello,

There is a new protein mapping pipeline, ProtHint, available at https://github.com/gatech-genemark/ProtHint. ProSplign is not used in this pipeline anymore. Try the usage example in that repository to verify whether all programs work.

Thank you for this question, I will update the link to this pipeline in the README file.

Tomas
