### ISSUE TITLE
Very satisfying annotations ... Except for one species 

### ISSUE THREAD

**Issue by vpymerel** [Gaius-Augustus/BRAKER#842]
Hello !

I have a question more than an issue, but maybe you can help me,

I am annotating a dozen of arthropods assemblies from a same genus with braker3 (arthropoda prot + RNAseq data),

For all assemblies, the BUSCO genes are predicted satisfactorily (no compleasm): 
- braker3: ~4% BUSCO missing,
- Augustus: ~ 1% BUSCO missing,
- GeneMark: ~1.5% BUSCO missing

Except for one assembly: 
- braker3: 29.99% BUSCO missing,
- Augustus: 6.00% BUSCO missing;
- GeneMark: 6.07% BUSCO missing

I would like to understand the discrepancy, but I don't have any clue of what may be happening,

RNAseq data is similar for each species (tissues, replicates, libraries ...), assembly quality also (chromosomal level, no huge duplication or missing parts),

Have you ever seen anything similar ? Or could you pinpoint me some statistics to get the beginning of an answer ?

Thank you,
V

**Comment by ChuanzhengWei** [comment]
#826 I have the same problem, did you solve it?

**Comment by vpymerel** [comment]
Note quite, I tried having look at fastq and bam stats ... But saw nothing obvious

**Comment by Artifice120** [comment]
I'm no expert, but if I had to guess. 

Maybe the read coverage of the final assembly is not as consistent. You could check with a tool like samtool depth after mapping the origianl reads to the assembly then take the average and standard deviation for each contig and compare it with the other assemblies.

If the average std dev of the coverage is significantly different the assembly could probably be polished.

More of  a guess.

**Comment by bijendrabio** [comment]
> Hello !
> 
> I have a question more than an issue, but maybe you can help me,
> 
> I am annotating a dozen of arthropods assemblies from a same genus with braker3 (arthropoda prot + RNAseq data),
> 
> For all assemblies, the BUSCO genes are predicted satisfactorily (no compleasm):
> 
> * braker3: ~4% BUSCO missing,
> * Augustus: ~ 1% BUSCO missing,
> * GeneMark: ~1.5% BUSCO missing
> 
> Except for one assembly:
> 
> * braker3: 29.99% BUSCO missing,
> * Augustus: 6.00% BUSCO missing;
> * GeneMark: 6.07% BUSCO missing
> 
> I would like to understand the discrepancy, but I don't have any clue of what may be happening,
> 
> RNAseq data is similar for each species (tissues, replicates, libraries ...), assembly quality also (chromosomal level, no huge duplication or missing parts),
> 
> Have you ever seen anything similar ? Or could you pinpoint me some statistics to get the beginning of an answer ?
> 
> Thank you, V

similar issue: https://github.com/Gaius-Augustus/BRAKER/issues/894

**Comment by vpymerel** [comment]
The issue with this dataset was indeed polishing, as suggested by Artifice120. The "poorly annotated assembly" was also "poorly polished" ....

**Comment by bijendrabio** [comment]
> The issue with this dataset was indeed polishing, as suggested by @Artifice120. The "poorly annotated assembly" was also "poorly polished" ....

Do you mean, its due to poor quality of genome assembly used or RNASeq data?
