### ISSUE TITLE
Public RNAseq as evidence for BRAKER? 

### ISSUE THREAD

**Issue by V-JJ** [Gaius-Augustus/BRAKER#849]
Hi!

I have the following question. I want to annotate a publicly available genome using proteins and RNAseq. 
- **Proteins**: one of the available datasets such as arthropodaODB (In absence of a better alternative)
- **RNAseq**: available NCBI data. Given that the available data may com from different individuals and / or tissues,  what would you recommend or strongly advise against? 

For instance, let's suppose that there are RNAseq data obtained for
- The whole organism and/or...
- Tissues specific sequencing

What would you do?
Any recommendation or advice is appreciated,

Thanks
V

**Comment by LarsGab** [comment]
Hello, 

I don't think it's an issue if the RNA-Seq data comes from different individuals or tissues. In our benchmarking, we selected RNA-Seq libraries randomly, without considering the source individuals or tissues. However, it is important to use enough data, we used ~6 RNA-Seq libraries from the SRA per species.

Best, 
Lars

**Comment by V-JJ** [comment]
Hi! 

Understood, clear know! Thanks for you help.
Best,
V
