### ISSUE TITLE
How do I add gene names to the annotation?

### ISSUE THREAD

**Issue by gabelow** [Gaius-Augustus/BRAKER#85]
Hi Katherine, 

I may have missed something obvious, but I've run BRAKER2 using protein hints and can't seem to figure out how to add gene names to the attributes of the resulting .gtf/.gff files. Is this intentional? Any help would be appreciated!

Cheers,
Gabriel

**Comment by KatharinaHoff** [comment]
The typical output format of BRAKER is

```
2R      AUGUSTUS        gene    404059  404511  0.7     +       .       g1
2R      AUGUSTUS        transcript      404059  404511  0.7     +       .       g1.t1
2R      AUGUSTUS        start_codon     404059  404061  .       +       0       transcript_id "g1.t1"; gene_id "g1";
2R      AUGUSTUS        CDS     404059  404511  0.7     +       0       transcript_id "g1.t1"; gene_id "g1";
2R      AUGUSTUS        exon    404059  404511  .       +       .       transcript_id "g1.t1"; gene_id "g1";
2R      AUGUSTUS        stop_codon      404509  404511  .       +       0       transcript_id "g1.t1"; gene_id "g1";
```
The gene name is here g1. Is that type of gene name missing in your augustus.hints.gtf file?

**Comment by gabelow** [comment]
Hi Katherine,

Thank you so much for replying!

That's the sort of gene names that BRAKER is currently giving me, but it isn't also including the equivalent name for that annotation that was supplied to it in the original proteome FASTA file as a hint, e.g.:

glow@fishgen:~genome$ head GCF_000247815.1_FicAlb1.5_protein.fa
>NP_001268892.1_Golgi_apparatus_membrane_protein_TVP23_homolog_B_[Ficedula_albicollis]
MDSGDDIEDVSLFDADDDVSRRSKKSKIRHPVASFFHLFFRVSAIVVYLLCELLTSSFIACMVTIILLLSCDFWAVKNVT
GRLMVGLRWWNQVDDDGRSHWVFEARKVSAQGGRTSSEAESRIFWLGLITCPMIWVIFAFSALFSFKVKWLAVVVMGVVL
QGANLYGYIRCKVGSRKNLTSLATNYLGKQFLRQTMATEDQAAS
>NP_001272809.1_ribonuclease_H1_[Ficedula_albicollis]
MLRWVVAVLSHSCFVPRDGSMFYAVRKGRRTGVYRTWAECQEQVNKFPSASFKKFATEKDAWSFVRAGQPGPQQQQPEPA
GAFGPPAVTQESGSQREEPELNTVCYSTYKRPYEQSTNEEQIAKRVKHDEIHSACSTPTVSEDKFSYMGDFAVVYTDGCC
TGNGRNRARAGIGVYWGPGHPLNTSERLPGRQTNQRAEIHAACKAIEQAKSQNIKKLIVYTDSKFTINGITSWVDNWKTN
GWRTSSGGSVINKEDFERLDNLTKDIEIQWMHIPGHAGFRGNEEADRLAREGACQPKC
>NP_001276784.1_ornithine_decarboxylase_antizyme_1_[Ficedula_albicollis]

This makes it hard to search for orthologs of these genes in the annotation. Do you have a recommended way to do that?

Cheers,
Gabriel

**Comment by KatharinaHoff** [comment]
I am not still not sure what you are looking for. The fasta output format of braker.pl looks like this (for example augustus.hints.aa file):

```>g1.t1
MLRGLPCRPPTPHMMPPYPLAPLPPPFLKRPWKPGLLIPPLPRPPPQGDVHHGALLLAAR
PRYWPRFRAYSSESKPLWCVEGWIPRRQTLFSLRCRDMNIMSLTVRNALLECGGSFGGPK
AGAGAGGSGRGSREGGGRVSGLMPLPNAAV*
>g2.t1
MHSLLQPTGKALHWEFQSSHDEEATGQRFPWSETPRETAQLSMPTSTLENQKPPLVPMSR
DPPTHETGTV*
```

The fasta headers correspond to unique transcript names in the gtf and gff3 file.

Maybe there is a misunderstanding about what GeneMark-ET, AUGUSTUS and BRAKER can do. All three are tools for structural genome annotation, i.e. they provide you with gene structures (and translations of these coding sequences). None of these tools does functional gene annotation. If you want to obtain a functional annotation, try something like interproscan.

**Comment by gabelow** [comment]
Hi Katherine,

AhhI think I understand where I've been mistaken now. Thank you very much for your patience - and thank you for the program! I'll close this thread now.

**Comment by ucbtsh6** [comment]
Hello
My gtf file doesnt have gene__name or transcript__biotype and I want to add it what is the best way to add it to the gtf file without it loose the structure?
