### ISSUE TITLE
Missing information about Solanum lycopersicum RNAseq used in Braker3 paper?

### ISSUE THREAD

**Issue by JBerthelier** [Gaius-Augustus/BRAKER#854]
Dear Braker3 authors, 

I would like to reproduce your Braker3 analyse of Solanum lycopersicum in order to verify my installation.

I retrieved the information of proteinDB used for **close relative included protein set** (Supplemental Table S2). 

However, it looks like the information of RNAseq used for Solanum lycopersicum is missing in the Supplemental Table S15. 

Would it possible to share me which RNAseq data you used ? 

Best regards, 

Jeremy

**Comment by LarsGab** [comment]
Hello,

I'm sorry this information got lost somewhere during the manuscript writing process.

We used following RNA-Seq with following IDs from the SRA:
`SRR21031283, SRR21394845, SRR21394846, SRR21031293, SRR18900583, SRR18087916 `

Best, 
Lars

**Comment by JBerthelier** [comment]
Hello Lars, 

No problem, it happens, thank you for the quick answer! 
That will be useful to me.

Best,

Jeremy
