### ISSUE TITLE
Can not find file: genome_gmst.gtf.

### ISSUE THREAD

**Issue by sunnycqcn** [Gaius-Augustus/BRAKER#857]
Hello Developer,
I am much appreciated for your excellent pipeline.
my command is `test3.sh`
 I met the same issue. I test my data and example data. If I only use protein data as evidence, it is working well. If I only use RNA-seq data as evidence, it is working well. However, I use both protein sequence and RNA-seq as evidence, I will see the error: 
error, file/folder not found: genome_gmst.gtf.
It is wired.
Best,
Fuyou

**Comment by sunnycqcn** [comment]
My log error is following:
ERROR in file /isilon/projects/J-002571_clubroot_src_chen/fuf/miniconda/envs/braker/bin/braker.pl at line 5575
Failed to execute: /isilon/projects/J-002571_clubroot_src_chen/fuf/miniconda/envs/braker/bin/perl /isilon/projects/J-002571_clubroot_src_chen/fuf/miniconda/envs/braker/GeneMark-ETP/bin/gmetp.pl --cfg /isilon/projects/J-003316_Canola-activity-10A/BnGenome/genome/annotion/DHT2.proRNA/GeneMark-ETP/etp_config.yaml --workdir /isilon/projects/J-003316_Canola-activity-10A/BnGenome/genome/annotion/DHT2.proRNA/GeneMark-ETP --bam /isilon/projects/J-003316_Canola-activity-10A/BnGenome/genome/annotion/DHT2.proRNA/GeneMark-ETP/etp_data/ --cores 40 --softmask  1>/isilon/projects/J-003316_Canola-activity-10A/BnGenome/genome/annotion/DHT2.proRNA/errors/GeneMark-ETP.stdout 2>/isilon/projects/J-003316_Canola-activity-10A/BnGenome/genome/annotion/DHT2.proRNA/errors/GeneMark-ETP.stderr
Failed to execute: /isilon/projects/J-002571_clubroot_src_chen/fuf/miniconda/envs/braker/bin/perl /isilon/projects/J-002571_clubroot_src_chen/fuf/miniconda/envs/braker/GeneMark-ETP/bin/gmetp.pl --cfg /isilon/projects/J-003316_Canola-activity-10A/BnGenome/genome/annotion/DHT2.proRNA/GeneMark-ETP/etp_config.yaml --workdir /isilon/projects/J-003316_Canola-activity-10A/BnGenome/genome/annotion/DHT2.proRNA/GeneMark-ETP --bam /isilon/projects/J-003316_Canola-activity-10A/BnGenome/genome/annotion/DHT2.proRNA/GeneMark-ETP/etp_data/ --cores 40 --softmask  1>/isilon/projects/J-003316_Canola-activity-10A/BnGenome/genome/annotion/DHT2.proRNA/errors/GeneMark-ETP.stdout 2>/isilon/projects/J-003316_Canola-activity-10A/BnGenome/genome/annotion/DHT2.proRNA/errors/GeneMark-ETP.stderr
The most common problem is that GeneMark-ETP didn't receive enough evidence from the input data, in this case, see errors/GeneMark-ETP.stderr!

**Comment by KatharinaHoff** [comment]
Please use the singularity container.

sunnycqcn ***@***.***> schrieb am Do. 12. Sept. 2024 um 17:22:

**Comment by sunnycqcn** [comment]
Hello,
Thanks for your reply ASAP.
I can not figure out this error about the root right. I do not have the write permission for root. So when I run my command,
`export BRAKER_SIF=/isilon/projects/J-003316_Canola-activity-10A/BnGenome/genome/annotion/braker3.sif

singularity exec ${BRAKER_SIF} braker.pl --genome=$PWD/DHT3.mask.fa --prot_seq=$PWD/EukaryotaBn.fa --bam=$PWD/DHT3/rnaseq/hisat2/DHT3.bam  \
            --threads 20 --gm_max_intergenic 10000 --nice --busco_lineage eukaryota_odb10 --species=Bn.RP.DHT3 --gff3 --overwrite --nocleanup --workingdir=$PWD/DHT3.RP \
            --AUGUSTUS_CONFIG_PATH=/isilon/projects/J-002571_clubroot_src_chen/fuf/miniconda/envs/braker/config/
            --AUGUSTUS_BIN_PATH=/isilon/projects/J-002571_clubroot_src_chen/fuf/miniconda/envs/braker/bin/ &> DHT33.log
`
I will get the error:
ERROR: in file /opt/BRAKER/scripts/braker.pl at line 842
Failed to create directory !
I checked this issues. This means that I do not have root right.
Do you have a way to change the working folder?
Thanks,
Fuyou

**Comment by KatharinaHoff** [comment]
You have to mount the directory you want to write to (eg $PWD) to the
container with -B

sunnycqcn ***@***.***> schrieb am Fr. 13. Sept. 2024 um 00:32:

**Comment by sunnycqcn** [comment]
Thanks.
It is working well now.
Fuyou
