### ISSUE TITLE
KeyError: 'tx_id' fix_in_frame_stop_codon_genes.py

### ISSUE THREAD

**Issue by utritala** [Gaius-Augustus/BRAKER#86]
Hello, 

While running braker, I got following error:
`Traceback (most recent call last):
  File "/lustre/software/augustus/augustus_3.2/scripts/fix_in_frame_stop_codon_genes.py", line 528, in <module>
    bad_genes.append(g_id_of_tx[tx_id])
KeyError: 'tx_id'`

I understand that its not finding the keys its looking for. But I don't know what is causing this problem. 

My BRAKER command is as follows:
`BRAKER2/BRAKER/scripts/braker.pl --species=vole7 --cores 20 --genome=medaka_consensus.fasta --esmode`

Many thanks for any help you could provide.

**Comment by utritala** [comment]
I have found the problem. The script expects the header line of the bad_genes.lst to start with "#" but it didn't in my case (Why this was, is another issue). I changed the file like the script expected and its running fine now.

**Comment by KatharinaHoff** [comment]
I am glad that this works for you, but it shouldn't really be the source of the problem. When bad_genes.lst are read, files with # are simply skipped, and if they don't exist, that should actually not matter:

```
    with open(args.badGenes, "r") as bad_handle:
        for line in bad_handle:
            if not re.match(r"#.*", line):
                match = re.search(r"(\S+).*", line)
                tx_id = match.group(1)
                bad_tx.append(tx_id)
```

@Anica94 , maybe you have an idea?

**Comment by KatharinaHoff** [comment]
Are you maybe not using the latest AUGUSTUS code from github? (git clone, not release download)

Because we fixed the hash-tag problem in the script that produces bad_genes.lst on August 29th: https://github.com/Gaius-Augustus/Augustus/commit/c637d97eabbc91d0a21339cfab4790af4ee31942#diff-f2f5648a5d82550f6e10aa1ed2d4e9c6
