### ISSUE TITLE
Error running braker ERROR in file /programs/BRAKER-2.1.4/scripts/braker.pl at line 7402

### ISSUE THREAD

**Issue by Neeraj2010** [Gaius-Augustus/BRAKER#87]
Hi, I have been trying to use braker to annotate a fungal genome I assemebled.

I get the error after a considerable amount of run time. I thought it could be an issue with my input file and I tried using a different genome file and still have the same issue. Could this be related to the software itself or is there something with my files that I am missing here. Your help and inputs will be greatly appreciated.
cheers

ERROR in file /programs/BRAKER-2.1.4/scripts/braker.pl at line 7402
Failed to execute: /usr/local/bin/python3 /programs/Augustus-3.3.3/scripts/fix_in_frame_stop_codon_genes.py -g /local/workdir/user/braker/genome.fa -t /local/workdir/user/braker/augustus.hints.gtf -b /local/workdir/user/braker/bad_genes.lst -o augustus.hints_fix_ifs_ -s Sp_1 -m off --UTR off --print_utr off -a /workdir/user/augustus_config/ -C /programs/cdbfasta -A /programs/augustus/bin -S /programs/augustus/scripts -H /local/workdir/user/braker/hintsfile.gff -e /programs/BRAKER-2.1.4/scripts/cfg/gth.cfg  > /local/workdir/user/braker/fix_in_frame_stop_codon_genes_augustus.hints.log 2> /local/workdir/user/braker/errors/fix_in_frame_stop_codon_genes_augustus.hints.err

**Comment by KatharinaHoff** [comment]
Is any content in the files  /local/workdir/user/braker/fix_in_frame_stop_codon_genes_augustus.hints.log and  /local/workdir/user/braker/errors/fix_in_frame_stop_codon_genes_augustus.hints.err ?

**Comment by Neeraj2010** [comment]
Hi Katharina,

There is no content in the /local/workdir/user/braker/fix_in_frame_stop_codon_genes_augustus.hints.log
but the  /local/workdir/user/braker/errors/fix_in_frame_stop_codon_genes_augustus.hints.err had the following in there:

Traceback (most recent call last):
  File "/programs/Augustus-3.3.3/scripts/fix_in_frame_stop_codon_genes.py", line 692, in <module>
    for ifs_line in ifs_handle:
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 168: ordinal not in range(128)

**Comment by KatharinaHoff** [comment]
There is another log file called "fix_IFS_log_" + some random string in your braker job directory. What does that file say?

**Comment by KatharinaHoff** [comment]
I made a new release. Code changed. I hope your problem is solved with the new release. If not, reopen issue.
