### ISSUE TITLE
joingenes removes intron and exon features

### ISSUE THREAD

**Issue by MartijnHolterman** [Gaius-Augustus/BRAKER#88]
So I'm not entirely sure if I should post this as a braker or augustus issue, but since I ran into it using braker I'll post it here. 

I ran into this problem while trying to perform a braker annotation with UTR features. When braker filters your augustus.hints.gtf file to build a training set for the UTR training it is looking for genes with good RNAseq support for intron features. However, of the 20,000 or so genes in my augustus.hints.gtf, only 2 or 3 genes had lines containing intron or exon features. 
It turns out that this is caused by the joingenes program of augustus, the input files have the intron and exon features, but the output doesn't. I don't know why a few genes do keep these features or if this is maybe problem specific to my data set. But to fix it I modified the fix_joingenes_gtf.pl script. So it now not only puts the missing gene feature lines back in, but also the intron and exon feature lines and it seems to work for my data set. The modified bit looks as follows:

```

my %genes;
my $comments = "";
my $tx_id;
my @previous;
while(<STDIN>){
	if(m/^\#/){
		$comments .= $_;
		@previous = ();
	}else{
		chomp;
		my @t = split(/\t/);
		my @t2 = split(/\./, $t[8]);
		if(m/\ttranscript\t/){
			$tx_id = $t2[0];
			if(not(defined($genes{$tx_id}))){
				$genes{$tx_id}{'seq'} = $t[0];
				$genes{$tx_id}{'src'} = $t[1];
				$genes{$tx_id}{'strand'} = $t[6];
				$genes{$tx_id}{'comments'} = $comments;
				$comments = "";
			}
			if(defined($genes{$tx_id}{'start'})){
				if($genes{$tx_id}{'start'} > $t[3]){
					$genes{$tx_id}{'start'} = $t[3];
				}
			}else{
				$genes{$tx_id}{'start'} = $t[3];
			}
			if(defined($genes{$tx_id}{'stop'})){
				if($genes{$tx_id}{'stop'} < $t[4]){
					$genes{$tx_id}{'stop'} = $t[4];
				}
			}else{
				$genes{$tx_id}{'stop'} = $t[4];
			}
			push(@{$genes{$tx_id}{'lines'}}, $t[0]."\t".$t[1]."\t".$t[2]."\t".$t[3]."\t".$t[4]."\t".$t[5]."\t".$t[6]."\t".$t[7]."\ttranscript_id \"".$t[8]."\"; gene_id \"".$tx_id."\"");
		}elsif(m/\tCDS\t/){
			if ($previous[2] eq "CDS"){
				my $start = $previous[4] + 1;
				my $end = $t[3] - 1;
				push(@{$genes{$tx_id}{'lines'}}, $t[0]."\t".$t[1]."\tintron\t".$start."\t".$end."\t.\t".$t[6]."\t.\t".$t[8]);
			}
			push(@{$genes{$tx_id}{'lines'}}, $_);
			push(@{$genes{$tx_id}{'lines'}}, $t[0]."\t".$t[1]."\texon\t".$t[3]."\t".$t[4]."\t.\t".$t[6]."\t.\t".$t[8]);
		}else{
			push(@{$genes{$tx_id}{'lines'}}, $_);
		}
		@previous = @t;
	}
}
```

Hope this is of help to anyone.

**Comment by KatharinaHoff** [comment]
BRAKER is not readily developed to train UTR parameters based on genes predicted with RNA-Seq & proteins. It should work with (unstranded!) RNA-Seq only. But thanks for suggesting this edit, it's included in commit https://github.com/Gaius-Augustus/Augustus/commit/e25f8ed15e25f6372d6cf0d41ffd0552473be7f7 in the Augustus repository.
