### ISSUE TITLE
Issues about the codes provided in paper navigating eukaryotic genome annotation pipeline

### ISSUE THREAD

**Issue by Abieskawa** [Gaius-Augustus/BRAKER#883]
Hello,
I am currently working on a genome around 1.1 Gbp species but with only one set of pair-end RNA-seq data on NCBI. Since there are many reports that GALBA did not have good performance, so I decide to use Braker1 + Braker2 + TSEBRA instead. But after repeat masking with RepeatModeler + RepeatMask with class level, the first step your paper provided leave me a truncated genome.
Here is the paper I specified: [link](https://arxiv.org/abs/2403.19416)

# The result from RepeatModeler + RepeatMask:
```
sed '/^>/d' beltfish_genome_1.fasta.masked | tr -d '\n' | awk '{    masked=gsub(/[a-z]/,"&");    nx=gsub(/[NXnx]/,"");    total=length($0)-nx;    printf "Masked bases: %d Total bases (excluding N and X): %d Ratio: %.4f\n", masked, total, masked/total}'
```
Masked bases: 695266837 Total bases (excluding N and X): 1137567318 Ratio: 0.6112

# The code from p11 (I did slightly modification here because it cannot be executed)
```
#!/bin/bashs
GENOME=beltfish_genome_1.fasta`

cd ~/output/beltfish
```
**The script splitMfasta.pl is from https://github.com/Gaius-Augustus/Augustus**
```
/home/abieskawa/tools/braker_tools/splitMfasta.pl --minsize=25000000 ${GENOME}.masked
```
**Running TRF**
```
ls ${GENOME}.masked.split.*.fa | parallel 'trf {} 2 7 7 80 10 50 500 -d -m -h'
```
**Parsing TRF output**
**The script parseTrfOutput.py is from https://github.com/gatech-genemark/BRAKER2-exp**
```
ls ${GENOME}.masked.split.*.fa.2.7.7.80.10.50.500.dat | parallel '~/tools/braker_tools/parseTrfOutput.py {} --minCopies 1 \
            --statistics {}.STATS > {}.raw.gff 2> {}.parsedLog'

```
**Sorting parsed output**
```
ls ${GENOME}.masked.split.*.fa.2.7.7.80.10.50.500.dat.raw.gff | parallel 'sort -k1,1 -k4,4n -k5,5n {} \
        > {}.sorted 2> {}.sortLog'

```
**Merging GFF**
```
FILES=${GENOME}.masked.split.*.fa.2.7.7.80.10.50.500.dat.raw.gff.sorted
for f in $FILES
do
    bedtools merge -i $f | awk 'BEGIN{OFS="\t"} {print $1,"trf","repeat",$2+1,$3,".",".",".","."}' \
        > $f.merged.gff 2> $f.bedtools_merge.log
done

```
**Masking FASTA chunk**
```
ls ${GENOME}.masked.split.*.fa | parallel 'bedtools maskfasta -fi {} \
       -bed {}.2.7.7.80.10.50.500.dat.raw.gff.sorted.merged.gff -fo {}.combined.masked -soft \
       &> {}.bedtools_mask.log'

```
**Concatenate split genome**
`cat ${GENOME}.masked.split.*.fa.combined.masked > ${GENOME}.fa.combined.masked``

# The result:
```
sed '/^>/d' beltfish_genome_1.fasta.fa.combined.masked | tr -d '\n' | awk '{    masked=gsub(/[a-z]/,"&");    nx=gsub(/[NXnx]/,"");    total=length($0)-nx;    printf "Masked bases: %d Total bases (excluding N and X): %d Ratio: %.4f\n", masked, total, masked/total}'
```
Masked bases: 894518 Total bases (excluding N and X): 1092916 Ratio: 0.8185

**Comment by KatharinaHoff** [comment]
Can you trace where you lost the sequences? They could have gotten lost
either at splitMfasta.pl, bedtools maskfasta, or at the final cat step.

**Comment by Abieskawa** [comment]
It seems to be the problem of cat. When I ran it separately with the shell, it appears to be normal.
Total_Length  Masked_Bases  NX_Bases  Effective_Length  Masking_Ratio
1138003112    703193872     217897    1137785215        0.6180

**Comment by Abieskawa** [comment]
Okay, it seems like that the problem came from the parallel did not finish its work before the cat start, add a 'wait' command does not help for unknown reason. I add a loop force it to print the line number of each split, and the problem solved:
```
for file in $(ls ${GENOME}.masked.split.*.fa.combined.masked | sort -V); do 
    # Get the line count of the current file
    line_count=$(wc -l < "$file")
    # Report the file name and line count, then add its content to the final file
    echo "Add $file with $line_count lines to ${GENOME}.fa.combined.masked"
done
echo "Start to do the job"

for file in $(ls ${GENOME}.masked.split.*.fa.combined.masked | sort -V); do
    cat "$file" >> ${GENOME}.fa.combined.masked
done
```
