### ISSUE TITLE
Failed UTR - aa2nonred.pl

### ISSUE THREAD

**Issue by visoca** [Gaius-Augustus/BRAKER#90]
I am using the latest version (62140de8100653998b4bfcebe560ef7508f8d16d) with the test data included in the example directory to try and get genes using RNASeq + protein hints followed by UTRs only using the produced hints. 
For gene prediction I have used: 

`../scripts/braker 
--cores 12 
--species=test1 
--genome=genome.fa 
--hints=ep.hints 
--bam=RNAseq.bam 
--AUGUSTUS_ab_initio 
--etpmode 
--softmasking 
--gff3 
--workingdir $PWD/test_rnaseq_prots
`

This runs fine, but then I have tried to use the hints to run prediction of UTRs:

`../scripts/braker 
--cores 12 
--species=test1 
--genome=genome.fa 
--bam=RNAseq.bam 
--AUGUSTUS_hints_preds=$PWD/test_rnaseq_prots/augustus.hints.gtf 
--UTR=on 
--flanking_DNA=1707 
--AUGUSTUS_ab_initio 
--softmasking 
--useexisting 
--gff3 
--workingdir $PWD/test_rnaseq_onlyutr
`

This fails when running `aa2nonred.pl`, when trying to create the DIAMOND database; content of `errors/utr.aa2nonred.stderr`:

> diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
> 
> Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
> Check http://github.com/bbuchfink/diamond for updates.
> 
> #CPU threads: 12
> Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
> Database file: /mnt/community/Genomics/apps/braker/2.1.4-62140de/example/test_rnaseq_onlyutr/utr_genes_in_gb.fa.nonreddb
> Opening the database file...  [0.003401s]
> Loading sequences...  [2.3e-05s]
> Writing trailer...  [6e-06s]
> Closing the input file...  [0.000275s]
> Closing the database file...  [0.000776s]
> Database hash = 00000000000000000000000000000000
> Processed 0 sequences, 0 letters.
> Total time = 0.004578s
> diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
> Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
> Check http://github.com/bbuchfink/diamond for updates.
> 
> #CPU threads: 12
> Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
> Temporary directory: /mnt/community/Genomics/apps/braker/2.1.4-62140de/example/test_rnaseq_onlyutr
> Opening the database...  [0.001655s]
> Error: Incomplete database file. Database building did not complete successfully.
> ERROR in file /mnt/community/Genomics/apps/braker/2.1.4-62140de/deps/augustus-3.3.3/scripts/aa2nonred.pl at line 220
> Could not open /mnt/community/Genomics/apps/braker/2.1.4-62140de/example/test_rnaseq_onlyutr/utr_genes_in_gb.fa.blastout!

It seems the problem is with the generation of the fasta file, since `utr_genes_in_gb.fa` doesn't have any sequences, only the sequences names, i.e:
>jg774.t1

>jg536.t1

but `genes_in_gb.gtf` looks fine.
A bit of digging suggests it may be a problem with the `gtf2fasta` subroutine call at:

```
9688         # convert those training genes to protein fasta file
9689         gtf2fasta ($genome, "$otherfilesDir/genes_in_gb.gtf",
9690             "$otherfilesDir/utr_genes_in_gb.fa");
```

**Comment by KatharinaHoff** [comment]
Found the bug, fixed it with commit https://github.com/Gaius-Augustus/BRAKER/commit/57102f8200ffd2d82a608bc17e9ed0d1f44e734e
