### ISSUE TITLE
BRAKER on complex genome

### ISSUE THREAD

**Issue by giulialopatriello95** [Gaius-Augustus/BRAKER#95]
Hi there!

I am using BRAKER to predict genes in a new species, following the approach 2B (training GeneMark-ER supported by RNA-seq spliced alignment information,prediction with AUGUSTUS with that same spliced information). In particular we consider in the analysis the softmasked genome.
My species have a genome size ~300 Mbp and repetitive content ~60%. From the training of Augustus,we have a sensitivity and specificity of ~ 25% at gene level . Is it possible that the high repetitive content of genome can  affect the performance of Augustus and BRAKER?

Thank you for your attention,

Giulia

**Comment by KatharinaHoff** [comment]
Hi Guilia,

yes, a high repeat content can affect gene prediction accuracy. Have you actually softmasked 60% of the genome?

In such cases, I recommend visual inspection of the gene set. You can use for example MakeHub to create a track data hub for visualization with the UCSC genome browser, but any other genome browser will do as well. You should look at: gene structures, RNA-Seq coverage, splice-junctions and repeat masking as tracks. You will then probably spot some problem (e.g. "genes are split even though they shouldn't be" or "entire genes are predicted in repeats" or "genes are fused but they shouldn't be", etc.) I recommend visualizing both GeneMark and AUGUSTUS genes in case of BRAKER.

Best,

Katharina

**Comment by giulialopatriello95** [comment]
Thanks @KatharinaHoff 

Is the fragmentation of the genome another factor affecting the performance of BRAKER? Our genome is also highly fragmented .

Best,

Giulia

**Comment by KatharinaHoff** [comment]
Yes. Fragmentation of genome leads to a low number of complex structures
for training. That’s probably your main issue.
