### ISSUE TITLE
minor: bogus core message

### ISSUE THREAD

**Issue by michaelkarlcoleman** [Gaius-Augustus/BRAKER#99]
This line should follow the next line in order to produce the intended message.

https://github.com/Gaius-Augustus/BRAKER/blob/e276416fd90f21f0d2232cc47a75753b30b59e33/scripts/braker.pl#L3641

**Comment by KatharinaHoff** [comment]
Good point, hahahaha...

FIxed it with commit https://github.com/Gaius-Augustus/BRAKER/commit/521f9efd96141ae787a9bc96fdcefea51a51b9b9
